downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc

* Deploy guide 2.5 updates
* updates to config chapter and new title for deploy guide
* reverting titles
* correcting include title

Deploy guide 2.5 updates (#1493)

---

downstream/aap-common/apache-2.0-license.adoc
downstream/aap-common/gplv3-license-text.adoc
downstream/assemblies/playbooks/assembly-open-source-license.adoc
downstream/modules/playbooks/ref-playbook-execution.adoc
downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
downstream/titles/playbooks/playbooks-getting-started/master.adoc

Add open-source license to Getting started with playbooks
https://issues.redhat.com/browse/AAP-26693

Added open source licence to Playbooks doc

---

downstream/aap-common/apache-2.0-license.adoc
downstream/aap-common/gplv3-license-text.adoc
downstream/assemblies/playbooks/assembly-open-source-license.adoc
downstream/modules/playbooks/ref-playbook-execution.adoc
downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
downstream/titles/playbooks/playbooks-getting-started/master.adoc

* Added open source licence to Playbooks doc https://issues.redhat.com/browse/AAP-26693

Added open source licence to Playbooks doc (#1546)

---

downstream/assemblies/platform/assembly-controller-inventories.adoc
downstream/modules/platform/proc-controller-inv-source-open-shift-virt.adoc
downstream/modules/platform/ref-controller-inventory-plugins.adoc

https://issues.redhat.com/browse/AAP-26688

Add new inventory source docs for OpenShift Virtualization

---

downstream/modules/platform/con-gw-dash-components.adoc
downstream/modules/platform/con-gw-dash-features.adoc

This PR converts the draft of the gateway dashboard content into asciidoc and adds the new modules to the modules/platform directory in the repo.
See draft here for reference:
https://docs.google.com/document/d/1traqmk9K88VLGaLP8xPpnvtdLTx4uP0ql8TVKQhi6gM/edit?usp=drive_link

AAP-18761 convert/create modules for the gateway dashboard

---

downstream/assemblies/builder/assembly-open-source-license.adoc
downstream/titles/builder/docinfo.xml
downstream/titles/builder/master.adoc

Add open-source license to _Creating and using execution environments_
https://issues.redhat.com/browse/AAP-26400

AAP-26400 added open source license to creating and using ees

---

lightspeed/modules/proc_login-vscode-extension.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-23850.
Changes made:
- Added authentication options for both Red Hat and Ansible Lightspeed.
- Added corner case about onprem dev spaces for Red Hat sign-in option.

AAP-23850: Added info. about Red Hat and Lightspeed authentication options

---

downstream/modules/platform/con-gw-dash-components.adoc
downstream/modules/platform/con-gw-dash-features.adoc

This PR backports the changes from #1552 to the 2.5 branch and includes the following changes:
* AAP-18761 convert/create modules for the gateway dashboard
* AAP-18761 - implemented peer review corrections

[Backport] - AAP-18761 convert/create modules for the gateway dashboard (#1552)

---

downstream/modules/platform/con-gw-activity-stream.adoc

This PR backports the changes from #1551 to the 2.5 branch.

[Backport] - AAP-21014 - convert/create module for gateway activity stream (#1551)

---

downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc

Need to explain container images will be removed when upgrading AAP
https://issues.redhat.com/browse/AAP-25760

Added note about removal of container images

---

downstream/assemblies/platform/assembly-aap-backup.adoc
downstream/assemblies/platform/assembly-aap-recovery.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc

[AAP-22069](https://issues.redhat.com/browse/AAP-22069)
[Draft](https://docs.google.com/document/d/1BxaD4Xo0OeGOD6tbsx3o07Vh2Pl0kvNaAPM-dinlOyU/edit)
Adding two new chapters, one for backing up via YAML and one for restoring via YAML. Also made an edit to an existing note to make it clearer.

AAP-22069 adding backup and restore via yaml chapters

---

downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc

Need to explain container images will be removed when upgrading AAP
https://issues.redhat.com/browse/AAP-25760

Added note about removal of container images (#1580)

---

downstream/assemblies/platform/assembly-aap-backup.adoc
downstream/assemblies/platform/assembly-aap-recovery.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc

[AAP-22069](https://issues.redhat.com/browse/AAP-22069)
[Draft](https://docs.google.com/document/d/1BxaD4Xo0OeGOD6tbsx3o07Vh2Pl0kvNaAPM-dinlOyU/edit)
Adding two new chapters, one for backing up via YAML and one for restoring via YAML. Also made an edit to an existing note to make it clearer.

Backport 1582 to 2.4

---

downstream/assemblies/platform/assembly-aap-backup.adoc
downstream/assemblies/platform/assembly-aap-recovery.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc

[AAP-22069](https://issues.redhat.com/browse/AAP-22069)
[Draft](https://docs.google.com/document/d/1BxaD4Xo0OeGOD6tbsx3o07Vh2Pl0kvNaAPM-dinlOyU/edit)
Adding two new chapters, one for backing up via YAML and one for restoring via YAML. Also made an edit to an existing note to make it clearer.

Backport 1582 to 2.5

---

downstream/attributes/attributes.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc

Creating a new attribute for Postgres QL, which as of 2.5 is supported version 15. 
Updating Main branch and 2.5

creating PostgresVers attribute

---

downstream/attributes/attributes.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc

Creating a new attribute for Postgres QL, which as of 2.5 is supported version 15.
Updating Main branch and 2.5

creating PostgresVers attribute (#1587)

---

downstream/attributes/attributes.adoc
downstream/modules/eda/proc-eda-set-up-credential.adoc
downstream/modules/hub/proc-configure-automation-hub-server-gui.adoc
downstream/modules/hub/proc-create-credential.adoc
downstream/modules/platform/proc-controller-add-users-job-templates.adoc
downstream/modules/platform/proc-controller-adding-gpg-key.adoc
downstream/modules/platform/proc-controller-create-credential.adoc
downstream/modules/platform/proc-controller-create-insights-credential.adoc
downstream/modules/platform/proc-controller-edit-credential.adoc
downstream/modules/platform/ref-controller-credentials-getting-started.adoc

This PR updates the attributes for credentials and credential types to be distinct for controller and EDA.

AAP-27282 - Updated attribute for credentials

---

downstream/attributes/attributes.adoc
downstream/modules/eda/proc-eda-set-up-credential.adoc
downstream/modules/hub/proc-configure-automation-hub-server-gui.adoc
downstream/modules/hub/proc-create-credential.adoc
downstream/modules/platform/proc-controller-add-users-job-templates.adoc
downstream/modules/platform/proc-controller-adding-gpg-key.adoc
downstream/modules/platform/proc-controller-create-credential.adoc
downstream/modules/platform/proc-controller-create-insights-credential.adoc
downstream/modules/platform/proc-controller-edit-credential.adoc
downstream/modules/platform/ref-controller-credentials-getting-started.adoc

This PR backports the changes from #1590 to the 2.5 branch.

[Backport] AAP-27282 - Updated attribute for credentials (#1590)

---

downstream/assemblies/devtools/assembly-rhdh-configure.adoc
downstream/assemblies/devtools/assembly-rhdh-install.adoc
downstream/assemblies/devtools/assembly-rhdh-intro.adoc
downstream/assemblies/devtools/assembly-rhdh-planning.adoc
downstream/assemblies/devtools/assembly-rhdh-upgrading-uninstalling.adoc
downstream/assemblies/devtools/assembly-rhdh-using.adoc

AAP-25260 Add assemblies for plug-ins for developer hub

AAP-25260 Add assemblies for plug-ins for developer hub

---

lightspeed/modules/proc_login-vscode-extension.adoc

This PR includes follow-up updates to JIRA https://issues.redhat.com/browse/AAP-23850. 
Changes made:
- Updated procedure content.
- Incorporated dev lead feedback.

AAP-23850-update: Updated the authentication options content

---

downstream/assemblies/platform/assembly-ag-controller-config.adoc
downstream/assemblies/platform/assembly-inventory-file-importing.adoc
downstream/modules/platform/proc-controller-configure-analytics.adoc
downstream/modules/platform/proc-controller-configure-jobs.adoc
downstream/modules/platform/proc-controller-configure-subscriptions.adoc
downstream/modules/platform/proc-controller-configure-system.adoc
downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
downstream/modules/platform/ref-controller-capacity-planning.adoc
downstream/modules/platform/ref-controller-cluster-management.adoc
downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
downstream/titles/controller/controller-admin-guide/master.adoc

Edits to UI based on latest test environment
https://issues.redhat.com/browse/AAP-27309

Corrections to Configuring automation execution

---

downstream/assemblies/platform/assembly-ag-controller-config.adoc
downstream/assemblies/platform/assembly-inventory-file-importing.adoc
downstream/modules/platform/proc-controller-configure-analytics.adoc
downstream/modules/platform/proc-controller-configure-jobs.adoc
downstream/modules/platform/proc-controller-configure-subscriptions.adoc
downstream/modules/platform/proc-controller-configure-system.adoc
downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
downstream/modules/platform/ref-controller-capacity-planning.adoc
downstream/modules/platform/ref-controller-cluster-management.adoc
downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
downstream/titles/controller/controller-admin-guide/master.adoc

* Corrections to Configuring automation execution
Edits to UI based on latest test environment
https://issues.redhat.com/browse/AAP-27309

Corrections to Configuring automation execution (#1598)

---

aap-common/external-site-disclaimer.adoc
aap-common/providing-feedback.adoc
stories/topics/proc-saas-set-up-private.adoc
stories/topics/proc-saas-set-up-public.adoc
stories/topics/ref-saas-default-configs.adoc
stories/topics/ref-saas-planning-configs.adoc

- Updating the feedback and disclaimer modules with aap-common
- Fixing a minor typo in saas-aws

updates to aap-common modules and small typo fix

---

downstream/aap-common/external-site-disclaimer.adoc
downstream/aap-common/providing-feedback.adoc

Updating the feedback and disclaimer modules with aap-common

updating feedback and disclaimer modules in aap-common (#1612)

---

downstream/modules/platform/proc-cli-get-controller-pwd.adoc

[AAP-20941](https://issues.redhat.com/browse/AAP-20941) - Install gateway
Adding some final SME comments on the gateway install updates. (Section 3.3) 
Doc location: Downstream > titles > aap-operator-installation

adding SME comments on final draft

---

downstream/modules/platform/proc-cli-get-controller-pwd.adoc

Adding SME comments to final draft

adding SME comments on final draft (#1621)

---

lightspeed/assemblies/assembly_configuring-vscode-extension.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-27486. 
Changes made:
- Updated connectivity requirements for VS Code.

AAP-27468: Updated connectivity requirements for VS Code

---

downstream/modules/platform/proc-controller-define-filter-with-facts.adoc

Add link to information on host filters
https://issues.redhat.com/browse/AAP-27638

Add note to section on facts and host filters

---

lightspeed/aap-common/external-site-disclaimer.adoc

Just updating aap-common disclaimer to adhere to the style guide and to be consistent with main and saas docs.

updating apap-common disclaimer

---

lightspeed/assemblies/assembly_troubleshooting-lightspeed.adoc
lightspeed/modules/con_lightspeed-process.adoc
lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-25787.
Changes made:
- Added troubleshooting content for Lightspeed on-premise deployment.

AAP-25787: Created troubleshooting doc for Lightspeed on-premise deployment

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/proc-add-operator-execution-nodes.adoc
downstream/modules/platform/proc-controller-ingress-options.adoc
downstream/modules/platform/proc-create-keycloak-client.adoc
downstream/modules/platform/proc-create-keycloak-instance.adoc
downstream/modules/platform/proc-hub-ingress-options.adoc
downstream/modules/platform/proc-install-aap-operator.adoc
downstream/modules/platform/proc-install-cli-aap-operator.adoc
downstream/modules/platform/proc-installing-hub-using-operator.adoc
downstream/modules/platform/proc-operator-access-aap.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc
downstream/modules/platform/proc-operator-external-db-controller.adoc
downstream/modules/platform/proc-operator-external-db-hub.adoc
downstream/modules/platform/proc-update-rhsso-client.adoc

Performing an editorial review of entire doc ahead of 2.5 EA.
Doc title : aap-operator-installation

Adding version 2.5 note on components

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/proc-add-operator-execution-nodes.adoc
downstream/modules/platform/proc-controller-ingress-options.adoc
downstream/modules/platform/proc-create-keycloak-client.adoc
downstream/modules/platform/proc-create-keycloak-instance.adoc
downstream/modules/platform/proc-hub-ingress-options.adoc
downstream/modules/platform/proc-install-aap-operator.adoc
downstream/modules/platform/proc-install-cli-aap-operator.adoc
downstream/modules/platform/proc-installing-hub-using-operator.adoc
downstream/modules/platform/proc-operator-access-aap.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc
downstream/modules/platform/proc-operator-external-db-controller.adoc
downstream/modules/platform/proc-operator-external-db-hub.adoc
downstream/modules/platform/proc-update-rhsso-client.adoc

Performing an editorial review of entire doc ahead of 2.5 EA.
Doc title : aap-operator-installation

Editorial review of entire doc ahead of 2.5 EA (#1628)

---

downstream/modules/platform/con-aap-backup-recommendations.adoc
downstream/modules/platform/con-aap-backup-recovery.adoc
downstream/modules/platform/proc-aap-controller-backup.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
downstream/modules/platform/proc-aap-hub-backup.adoc
downstream/modules/platform/proc-aap-hub-restore.adoc
downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
downstream/modules/platform/proc-aap-platform-gateway-restore.adoc

Performing an editorial review of entire doc ahead of 2.5 EA.
Doc title : aap-operator-backup

Editorial review on backup and recovery doc

---

downstream/modules/platform/con-aap-backup-recommendations.adoc
downstream/modules/platform/con-aap-backup-recovery.adoc
downstream/modules/platform/proc-aap-controller-backup.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
downstream/modules/platform/proc-aap-hub-backup.adoc
downstream/modules/platform/proc-aap-hub-restore.adoc
downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
downstream/modules/platform/proc-aap-platform-gateway-restore.adoc

* Editorial review on backup and recovery doc
* PR suggestion

Editorial review on backup and recovery doc (#1637)

---

downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
downstream/modules/platform/proc-operator-aap-faq.adoc
downstream/modules/platform/proc-operator-access-aap.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc
downstream/modules/platform/proc-operator-link-components.adoc

UI element changed updating across section modules
doc title: aap-operator-installation
doc title: aap-operator-backup

updating UI change

---

downstream/modules/platform/proc-controller-adding-new-inventory.adoc

Correct section on creating host filters
https://issues.redhat.com/browse/AAP-27447

Updating module on creating an inventory

---

downstream/modules/platform/proc-controller-adding-new-inventory.adoc

* Updating module on creating an inventory
Correct section on creating host filters
https://issues.redhat.com/browse/AAP-27447
* Update module on creating an inventory
Added additional verbosity types
Correct section on creating host filters
https://issues.redhat.com/browse/AAP-27447
* Update module on creating an inventory
Additional infornmation
Correct section on creating host filters
https://issues.redhat.com/browse/AAP-27447
* Updating module on creating an inventory
Tidying up
Correct section on creating host filters
https://issues.redhat.com/browse/AAP-27447
* Updating module on creating an inventory
Corrections
Correct section on creating host filters
https://issues.redhat.com/browse/AAP-27447

Updating module on creating an inventory (#1613)

---

downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
downstream/modules/platform/proc-operator-aap-faq.adoc
downstream/modules/platform/proc-operator-access-aap.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc
downstream/modules/platform/proc-operator-link-components.adoc

* Editorial review of entire doc ahead of 2.5 EA (#1628)

updating UI change (#1632)

---

downstream/aap-common/external-site-disclaimer.adoc
downstream/assemblies/platform/assembly-platform-whats-next.adoc
downstream/modules/platform/con-known-proxies.adoc
downstream/modules/platform/con-sticky-sessions.adoc
downstream/modules/platform/con-why-automation-mesh.adoc
downstream/modules/platform/proc-aap-activate-with-credentials.adoc
downstream/modules/platform/proc-aap-activate-with-manifest.adoc
downstream/modules/platform/proc-configure-known-proxies.adoc
downstream/modules/platform/proc-configuring-reverse-proxy.adoc
downstream/modules/platform/proc-control-data-collection.adoc
downstream/modules/platform/proc-enable-proxy-support.adoc

This PR updates the content in the Operations guide to reflect the new platform gateway user interface.

AAP-20549 - Implementing gateway UI changes into the Operations guide

---

downstream/modules/platform/con-gw-managing-access.adoc
downstream/modules/platform/proc-gw-add-admin-organization.adoc
downstream/modules/platform/proc-gw-add-admin-team.adoc
downstream/modules/platform/proc-gw-add-team-organization.adoc
downstream/modules/platform/proc-gw-delete-organization.adoc
downstream/modules/platform/proc-gw-delete-team.adoc
downstream/modules/platform/proc-gw-organizations-exec-env.adoc
downstream/modules/platform/proc-gw-remove-roles-team.adoc
downstream/modules/platform/proc-gw-remove-roles-user.adoc
downstream/modules/platform/proc-gw-team-access-resources.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc
downstream/modules/platform/proc-gw-team-list-view.adoc
downstream/modules/platform/proc-gw-team-remove-user.adoc
downstream/modules/platform/proc-gw-user-access-resources.adoc
downstream/modules/platform/proc-gw-users-list-view.adoc
downstream/snippets/snip-gw-roles-note-multiple-components.adoc

This PR adds new content modules for the centralized Access Management to the platform directory. It also adds a snippet for a common multi-component note. Existing content modules on this topic will be updated in a separate PR.

AAP-19236 - Adding new modules for gateway access management

---

downstream/modules/platform/proc-controller-define-filter-with-facts.adoc

Updated text
Add link to information on host filters
https://issues.redhat.com/browse/AAP-27638

Amended note on facts and host filters

---

downstream/modules/platform/con-gw-managing-access.adoc
downstream/modules/platform/proc-gw-add-admin-organization.adoc
downstream/modules/platform/proc-gw-add-admin-team.adoc
downstream/modules/platform/proc-gw-add-team-organization.adoc
downstream/modules/platform/proc-gw-delete-organization.adoc
downstream/modules/platform/proc-gw-delete-team.adoc
downstream/modules/platform/proc-gw-organizations-exec-env.adoc
downstream/modules/platform/proc-gw-remove-roles-team.adoc
downstream/modules/platform/proc-gw-remove-roles-user.adoc
downstream/modules/platform/proc-gw-team-access-resources.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc
downstream/modules/platform/proc-gw-team-list-view.adoc
downstream/modules/platform/proc-gw-team-remove-user.adoc
downstream/modules/platform/proc-gw-user-access-resources.adoc
downstream/modules/platform/proc-gw-users-list-view.adoc
downstream/snippets/snip-gw-roles-note-multiple-components.adoc

This PR backports the changes from #1647 to the 2.5 branch and includes the following: 
* AAP-19236 - Add new modules for gateway access management
* AAP-19236 - Minor fixes and adding a snippet

[Backport] AAP-19236 - Adding new modules for gateway access management (#1647)

---

downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc

VM-install guide - Correct attributes that don't resolve in code blocks
https://issues.redhat.com/browse/AAP-28102

Correct attributes that don't resolve in code blocks

---

downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc

VM-install guide - Correct attributes that don't resolve in code blocks
https://issues.redhat.com/browse/AAP-28102

2.5 Correct attributes that don't resolve in code blocks (#1656)

---

downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc

VM-install guide - Correct attributes that don't resolve in code blocks
https://issues.redhat.com/browse/AAP-28102

2.4 Correct attributes that don't resolve in code blocks (#1656)

---

downstream/assemblies/platform/assembly-controller-organizations.adoc
downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/assemblies/platform/assembly-controller-users.adoc
downstream/assemblies/platform/assembly-gw-resources.adoc
downstream/modules/platform/proc-gw-organizations-exec-env.adoc
downstream/modules/platform/proc-gw-team-access-resources.adoc

This PR updates and adds the assembly modules for Access management. It also includes the peer review changes made to PR #1647 .

AAP-19236 - Add assemblies for Access Management and peer review changes for modules from 1647

---

downstream/assemblies/platform/assembly-controller-organizations.adoc
downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/assemblies/platform/assembly-controller-users.adoc
downstream/assemblies/platform/assembly-gw-resources.adoc
downstream/modules/platform/proc-gw-organizations-exec-env.adoc
downstream/modules/platform/proc-gw-team-access-resources.adoc

This PR backports the changes from #1653 to the 2.5 branch and includes the following: 
* AAP-19236 - Add assemblies for Access Management and peer review changes from the modules PR
* AAP-19236 - Implemented peer review changes

[Backport] AAP-19236 - Add assemblies for Access Management

---

downstream/modules/platform/proc-install-ha-hub-selinux.adoc

[Docs] NFS SELinux context for Automation Hub is missing
https://issues.redhat.com/browse/AAP-27172

Update SELinux command

---

downstream/modules/platform/proc-install-ha-hub-selinux.adoc

* Update SELinux command
[Docs] NFS SELinux context for Automation Hub is missing
https://issues.redhat.com/browse/AAP-27172
* Update SELinux command
Correction
[Docs] NFS SELinux context for Automation Hub is missing
https://issues.redhat.com/browse/AAP-27172

Update SELinux command (#1652)

---

downstream/modules/platform/con-controller-access-organizations.adoc
downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-controller-create-organization.adoc
downstream/modules/platform/proc-controller-review-organizations.adoc
downstream/modules/platform/ref-controller-organization-notifications.adoc

This PR includes RBAC changes for 2.5 for content on Organizations.

AAP-19133 Update existing modules for organizations for 2.5 RBAC changes

---

downstream/modules/platform/proc-controller-creating-a-team.adoc
downstream/modules/platform/proc-controller-user-permissions.adoc

This PR includes RBAC changes for 2.5 for content on Teams.

AAP-19133 Update content on teams for 2.5 RBAC changes

---

lightspeed/modules/proc_create-connection-secrets.adoc

This PR tracks JIRA https://issues.redhat.com/browse/AAP-26615.
Changes made:
- Added procedure about creating bundle secret to trust custom CA.

AAP-26615: Added info. about creating bundle secret to trust custom CA

---

downstream/modules/platform/con-controller-create-users.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc
downstream/modules/platform/proc-controller-deleting-a-user.adoc
downstream/modules/platform/ref-controller-user-roles.adoc
downstream/modules/platform/ref-controller-user-teams.adoc

This PR includes RBAC changes for 2.5 for content on Users.

AAP-19133 Update content on Users for 2.5 RBAC changes

---

downstream/assemblies/platform/assembly-controller-organizations.adoc
downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/assemblies/platform/assembly-controller-users.adoc
downstream/assemblies/platform/assembly-gw-resources.adoc

This PR backports the changes from #1680 to the 2.5 branch.

[Backport] AAP-19236 fix include statements to include platform/ (#1680)

---

downstream/modules/platform/proc-controller-creating-a-team.adoc
downstream/modules/platform/proc-controller-user-permissions.adoc

This PR backports the changes from #1678 to the 2.5 branch and includes the following:
* AAP-19133 Update content on teams for 2.5 RBAC changes
* AAP-19133 - implement peer review changes

[Backport] AAP-19133 Update content on teams for 2.5 RBAC changes (#1678)

---

downstream/modules/platform/con-controller-access-organizations.adoc
downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-controller-create-organization.adoc
downstream/modules/platform/proc-controller-review-organizations.adoc
downstream/modules/platform/ref-controller-organization-notifications.adoc

This PR backports the changes from #1677 to the 2.5 branch and includes the following:
* AAP-19133 Update existing modules for organizations for 2.5 RBAC changes
* AAP-19133 - implement peer review changes

[Backport] AAP-19133 Update existing modules for organizations for 2.5 RBAC changes (#1677)

---

downstream/modules/platform/con-controller-create-users.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc
downstream/modules/platform/proc-controller-deleting-a-user.adoc
downstream/modules/platform/ref-controller-user-roles.adoc
downstream/modules/platform/ref-controller-user-teams.adoc

This PR backports the changes from #1679 to the 2.5 branch.

[Backport] AAP-19133 Update content on Users for 2.5 RBAC changes (#1679)

---

downstream/modules/platform/con-controller-settings.adoc
downstream/modules/platform/proc-controller-configure-system.adoc

Add missing description
https://issues.redhat.com/browse/AAP-28367

Add description

---

downstream/modules/platform/con-controller-settings.adoc
downstream/modules/platform/proc-controller-configure-system.adoc

Add missing description
https://issues.redhat.com/browse/AAP-28367

Add description (#1689)

---

downstream/attributes/attributes.adoc

Create attributes for docs titles so that external links to other docs in the AAP docset don't break when titles are updated.

AAP-27260 Add attributes for docs titles

---

downstream/modules/platform/proc-add-operator-execution-nodes.adoc

Fixes https://github.com/ansible/aap-docs/issues/1649
Backporting [AAP Receptor doc update #1650](https://github.com/ansible/aap-docs/pull/1650)

Fixes #1649 (#1650)

---

downstream/modules/platform/ref-controller-variables.adoc

Updates the following inventory file variables in the VM installer guide:
Add:
- admin_username
- admin_email
Remove:
- automationcontroller_password
- automationcontroller_username
Update:
- admin_password
Affects: VM-install guide - titles/aap-installation-guide
AAP 2.5 Update the inventory file variables in the VM Install guide
https://issues.redhat.com/browse/AAP-27328

2.4 Update inventory file variables for controller and gateway (#1697)

---

downstream/assemblies/platform/assembly-gw-dashboard.adoc

This PR adds an assembly file for the gateway dashboard content.

AAP-18761-A - add assembly for the gateway dashboard

---

downstream/modules/platform/ref-controller-database-settings.adoc

The  backport of PR #1667 for AAP-23515

AAP-23515 Doc release notes for PostgreSQL upgrade

---

downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
downstream/modules/platform/con-about-automation-mesh.adoc
downstream/modules/platform/con-automation-mesh-node-types.adoc
downstream/modules/platform/proc-set-up-virtual-machines.adoc
downstream/modules/platform/ref-operator-mesh-prerequisites.adoc

* Update commands
Added command for ARM system and corrected sequence.
hackfest mesh doc feedback - command updates
https://issues.redhat.com/browse/AAP-26999
* Update commands
Correction
hackfest mesh doc feedback - command updates
issues.redhat.com/browse/AAP-26999

Update commands (#1703)

---

downstream/modules/platform/proc-set-up-virtual-machines.adoc

* Add note about execution node
hackfest doc feedback - mesh section 2.2
https://issues.redhat.com/browse/AAP-27000
* Add note about execution node
Correction
hackfest doc feedback - mesh section 2.2
https://issues.redhat.com/browse/AAP-27000

Add note about execution node (#1705)

---

lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
lightspeed/modules/con_overview-lightspeed-onpremise.adoc
lightspeed/modules/proc_monitor-onpremise-deployment.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-20599.
Changes made:
- Added the procedure for monitoring Lightspeed on-premise deployments.
- Fixed a doc cross-reference link.

AAP-20599: Added info. monitoring Lightspeed onprem deployment

---

downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
downstream/modules/platform/con-install-mesh.adoc
downstream/modules/platform/proc-editing-inventory-file.adoc
downstream/modules/platform/proc-running-setup-script.adoc
downstream/titles/aap-installation-guide/master.adoc

Included modules from installation doc
hackfest doc updates for mesh - install
https://issues.redhat.com/browse/AAP-26993

Modified instructions for VM-based mesh

---

downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
downstream/modules/platform/con-install-mesh.adoc
downstream/modules/platform/proc-editing-inventory-file.adoc
downstream/modules/platform/proc-running-setup-script.adoc
downstream/titles/aap-installation-guide/master.adoc

* Modified instructions for VM-based mesh
Included modules from installation doc
hackfest doc updates for mesh - install
https://issues.redhat.com/browse/AAP-26993
* Modified instructions for VM-based mesh
Correction
hackfest doc updates for mesh - install
https://issues.redhat.com/browse/AAP-26993
* Modified instructions for VM-based mesh
Corrections
hackfest doc updates for mesh - install
https://issues.redhat.com/browse/AAP-26993

Modified instructions for VM-based mesh (#1696)

---

downstream/modules/eda/con-eda-projects-list-view.adoc
downstream/modules/eda/proc-eda-delete-project.adoc
downstream/modules/eda/proc-eda-editing-a-project.adoc
downstream/modules/eda/proc-eda-set-up-new-project.adoc
downstream/modules/eda/ref-performance-troubleshooting.adoc

Updates applied to the Projects chapter in the EDA controller user guide: 
- Projects
-  Setting up a new project
-  Projects list view
-  Editing a project  
-  Deleting a project

Backport-2.5-1648 (AAP-22930) Update the Projects chapter in the EDA controller user guide

---

downstream/modules/platform/con-gw-create-authentication.adoc
downstream/modules/platform/con-gw-overview-access-auth.adoc
downstream/modules/platform/con-gw-pluggable-authentication.adoc
downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
downstream/modules/platform/proc-gw-configure-auth-details.adoc
downstream/modules/platform/proc-gw-define-rules-triggers.adoc
downstream/modules/platform/proc-gw-review-auth-settings.adoc
downstream/modules/platform/proc-gw-select-auth-type.adoc

This PR converts the content for the overview, authentication plugin, and authentication wizard modules from the Google draft to AsciiDoc.
https://docs.google.com/document/d/1mEYguv3V0WUUHBMc8tsgqlK8RB3ro8IZSlQmMuFfhww/edit#bookmark=kix.mwaeerkmar4y

AAP-29215 - Convert overview and auth wizard content

---

downstream/modules/platform/con-operator-eda-controller-install.adoc
downstream/modules/platform/proc-operator-connect-eda-to-controller.adoc

[AAP-28466](https://issues.redhat.com/browse/AAP-28466)
Converting SME approved [draft](https://docs.google.com/document/d/1G8eAEAkazICAPps0W07bNDp-ZzyRbRA85iXCcnJL3L4/edit#heading=h.p05y5ogaknyo) (operator based installation section only) into asciidoc

creating con and proc modules for operator-based install

---

downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

Just one update made for the Create Rulebook Activations fields: Service Name. Other more extensive changes will be tracked in a separate PR.

AAP-21827 Add new field for new field for the k8s_service_name

---

downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

Added updated fields to the Rulebook Activations chapter along with a note.

AAP-24389 Added Credential field and multi-credential capability

---

downstream/assemblies/platform/assembly-gs-key-functionality.adoc
downstream/modules/platform/con-gs-ansible-lightspeed.adoc
downstream/modules/platform/con-gs-automation-content.adoc
downstream/modules/platform/con-gs-automation-decisions.adoc
downstream/modules/platform/con-gs-automation-execution.adoc
downstream/modules/platform/con-gs-automation-mesh.adoc
downstream/modules/platform/con-gs-dashboard-components.adoc
downstream/modules/platform/con-gs-developer-tools.adoc
downstream/modules/platform/con-gs-final-set-up.adoc
downstream/modules/platform/ref-gs-install-config.adoc
downstream/titles/getting-started/docinfo.xml
downstream/titles/getting-started/master.adoc

* Adding conceptual overview to asciidoc
Create Conceptual overview section of Getting started with AAP
https://issues.redhat.com/browse/AAP-29066
Affects `titles/getting-started`
* Third commit

Adding conceptual overview to asciidoc (#1720)

---

downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

Added updated fields to the Rulebook Activations chapter along with a note.

Backport-2.5-1726 (AAP-24389) Added Credential field and multi-credential capability

---

downstream/modules/platform/con-gw-create-authentication.adoc
downstream/modules/platform/con-gw-overview-access-auth.adoc
downstream/modules/platform/con-gw-pluggable-authentication.adoc
downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
downstream/modules/platform/proc-gw-configure-auth-details.adoc
downstream/modules/platform/proc-gw-define-rules-triggers.adoc
downstream/modules/platform/proc-gw-review-auth-settings.adoc
downstream/modules/platform/proc-gw-select-auth-type.adoc

This PR backports the changes from #1725 to the 2.5 branch.

AAP-29215 - Convert overview and auth wizard content (#1725)

---

downstream/modules/devtools/proc-devtools-create-aap-job.adoc
downstream/modules/devtools/proc-devtools-install-rpm.adoc
downstream/modules/devtools/proc-devtools-save-scm.adoc

AAP-29276a Devtools doc fixes

---

downstream/modules/platform/con-gw-pluggable-authentication.adoc
downstream/modules/platform/proc-gw-configure-auth-details.adoc
downstream/modules/platform/proc-gw-define-rules-triggers.adoc
downstream/modules/platform/proc-gw-review-auth-settings.adoc
downstream/modules/platform/proc-gw-select-auth-type.adoc

This PR implements peer review suggestions from PR #1725 and other minor changes to the authentication wizard content.

AAP-29215 - implement peer review and other fixes from PR1725

---

downstream/modules/platform/con-gw-pluggable-authentication.adoc
downstream/modules/platform/proc-gw-configure-auth-details.adoc
downstream/modules/platform/proc-gw-define-rules-triggers.adoc
downstream/modules/platform/proc-gw-review-auth-settings.adoc
downstream/modules/platform/proc-gw-select-auth-type.adoc

This PR backports the changes from #1745 to the 2.5 branch and includes the following:
* AAP-29215 - implement peer review and other fixes from PR1725
* AAP-29215 - changed procedure headings to gerunds
* AAP-29215 - fix cross reference formatting
* AAP-29215 - include peer review corrections

[Backport] AAP-29215 - implement peer review and other fixes from PR1725 (#1745)

---

stories/topics/proc-saas-set-up-private.adoc

[AAP-23355](https://issues.redhat.com/browse/AAP-23355)
Updating UI elements and adding new steps after a demo. 
Preview: https://g-murray.github.io/aap-builds/saas-aws-saas-set-up-2024-08-16.html

Updating UI steps after demo

---

downstream/modules/platform/con-gw-authenticator-map-examples.adoc
downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
downstream/modules/platform/con-gw-authenticator-map-types.adoc
downstream/modules/platform/proc-gw-allow-mapping.adoc
downstream/modules/platform/proc-gw-role-mapping.adoc
downstream/modules/platform/proc-gw-superuser-mapping.adoc
downstream/modules/platform/ref-controller-organization-mapping.adoc
downstream/modules/platform/ref-controller-team-mapping.adoc

This PR converts the content for the authentication mapping modules from the Google draft to AsciiDoc.
https://docs.google.com/document/d/1mEYguv3V0WUUHBMc8tsgqlK8RB3ro8IZSlQmMuFfhww/edit#bookmark=id.lo8shniq7v3e

AAP-29217 - Convert authentication mapping content

---

downstream/modules/platform/con-gw-authenticator-map-examples.adoc
downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
downstream/modules/platform/con-gw-authenticator-map-types.adoc
downstream/modules/platform/proc-gw-allow-mapping.adoc
downstream/modules/platform/proc-gw-role-mapping.adoc
downstream/modules/platform/proc-gw-superuser-mapping.adoc
downstream/modules/platform/ref-controller-organization-mapping.adoc
downstream/modules/platform/ref-controller-team-mapping.adoc

This PR backports the changes from #1751 to the 2.5 branch.

[Backport] - AAP-29217 - Convert authentication mapping content (#1751)

---

downstream/titles/develop-automation-content/docinfo.xml

2.4 AAP-29500 Update subtitle in Devtools doc

2.4 AAP-29500 Update subtitle in Devtools doc

---

downstream/snippets/snip-gw-authentication-additional-auth-fields.adoc
downstream/snippets/snip-gw-authentication-common-checkboxes.adoc
downstream/snippets/snip-gw-authentication-next-steps.adoc
downstream/snippets/snip-gw-authentication-verification.adoc

This PR is to create snippets for repeated information throughout the authentication procedures.

AAP-29504 - Created snippets for repeated authentication information

---

lightspeed/modules/proc_configure-vscode-extension-onpremise-deployment.adoc
lightspeed/modules/proc_configure-vscode-extension.adoc
lightspeed/modules/proc_log-in-administrator-portal.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-27079. 
Changes made:
Added info. about delay in recognizing AAP subscription.

AAP-27079: Added info. about delay in recognizing AAP subscription

---

downstream/assemblies/platform/assembly_metrics-utility.adoc
downstream/modules/platform/proc_configuring-the-metrics-utility.adoc
downstream/modules/platform/proc_modifying-the-run-schedule.adoc
downstream/modules/platform/ref_fetching-a-monthly-report.adoc

https://issues.redhat.com/browse/AAP-19692
AAP-19692

Document the Metric Collection Utility

---

downstream/modules/platform/proc-gw-authentication-list-view.adoc
downstream/modules/platform/proc-gw-delete-authenticator.adoc
downstream/modules/platform/proc-gw-display-auth-details.adoc
downstream/modules/platform/proc-gw-edit-authenticator.adoc
downstream/modules/platform/proc-gw-searching-authenticator.adoc

This PR converts the content for the managing authentication modules from the Google draft to AsciiDoc.
https://docs.google.com/document/d/1mEYguv3V0WUUHBMc8tsgqlK8RB3ro8IZSlQmMuFfhww/edit#bookmark=kix.sll4ydwxafjs

AAP-29218 - Convert managing authentication content

---

downstream/modules/platform/proc-gw-authentication-list-view.adoc
downstream/modules/platform/proc-gw-delete-authenticator.adoc
downstream/modules/platform/proc-gw-display-auth-details.adoc
downstream/modules/platform/proc-gw-edit-authenticator.adoc
downstream/modules/platform/proc-gw-searching-authenticator.adoc

This PR backports the changes from #1759 to the 2.5 branch and includes the following:
* AAP-29218 - Convert managing authentication content
* AAP-29218 include peer review changes

[Backport] AAP-29218 - Convert managing authentication content (#1759)

---

stories/assembly-saas-planning.adoc
stories/topics/con-saas-automation.adoc
stories/topics/con-saas-intro.adoc
stories/topics/ref-saas-egress-model.adoc
stories/topics/ref-saas-mesh-ingress-model.adoc

[AAP-28861](https://issues.redhat.com/browse/AAP-28861) 
Updates to the introduction section of the Sass documentation - SME reviewed and approved.

AAP-28861- Saas intro update

---

lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
lightspeed/modules/con_overview-lightspeed-onpremise.adoc
lightspeed/modules/proc_monitor-onpremise-deployment.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-20599. 
Changes made:
- Added info. about monitoring Lightspeed on-premise deployments.

AAP-20599-update: Documented info. about monitoring Lightspeed on-premise

---

downstream/assemblies/platform/assembly-gs-platform-admin.adoc
downstream/modules/platform/con-gs-automation-content.adoc
downstream/modules/platform/con-gs-automation-decisions.adoc
downstream/modules/platform/con-gs-automation-execution.adoc
downstream/modules/platform/con-gs-config-authentication.adoc
downstream/modules/platform/con-gs-manage-RBAC.adoc
downstream/modules/platform/proc-gs-logging-in.adoc
downstream/modules/platform/proc-gs-platform-admin-create-user.adoc
downstream/modules/platform/proc-gs-social-auth-github.adoc

* Adding platform admin section to asciidoc
Create Platform admin section of Getting started with AAP
https://issues.redhat.com/browse/AAP-29067
Affects `titles/getting-started`
* Adding final content to admin section
* Adding Github section to platform admin

Adding platform admin section to asciidoc (#1734)

---

downstream/assemblies/platform/assembly-controller-organizations.adoc
downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
downstream/assemblies/platform/assembly-gw-managing-access.adoc
downstream/assemblies/platform/assembly-gw-managing-authentication.adoc
downstream/assemblies/platform/assembly-gw-mapping.adoc
downstream/assemblies/platform/assembly-gw-roles.adoc
downstream/assemblies/platform/assembly-gw-settings.adoc
downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
downstream/modules/platform/ref-controller-organization-notifications.adoc
downstream/titles/central-auth/docinfo.xml
downstream/titles/central-auth/master.adoc
downstream/titles/central-auth/platform

This PR builds out the structure of the new Access management and authentication guide and includes the followings:
Adds new assemblies for the document.
Updates the master.adoc and docinfo.xml files.
Fixes some formatting issues identified in my local build.

AAP-29223 - Create structure for Access management and authentication

---

downstream/modules/eda/proc-eda-set-up-token.adoc

Revert "AAP-24690 Tweaked note after step 5 in Chapter 5 EDA controller user guide"

---

downstream/assemblies/platform/assembly-ug-controller-schedules.adoc
downstream/modules/platform/proc-controller-adding-new-schedule.adoc
downstream/modules/platform/proc-controller-define-schedule-rules.adoc

Update procedures for Schedules
https://issues.redhat.com/browse/AAP-29720

Updated Schedules information

---

downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/modules/platform/proc-access-hub-operator-ui.adoc
downstream/modules/platform/proc-add-controller-access-token.adoc
downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
downstream/modules/platform/proc-configuring-controller-route-options.adoc
downstream/modules/platform/proc-controller-ingress-options.adoc
downstream/modules/platform/proc-create-a-user.adoc
downstream/modules/platform/proc-create-keycloak-client.adoc
downstream/modules/platform/proc-create-keycloak-instance.adoc
downstream/modules/platform/proc-create-keycloak-realm.adoc
downstream/modules/platform/proc-determine-hub-route.adoc
downstream/modules/platform/proc-hub-ingress-options.adoc
downstream/modules/platform/proc-hub-route-options.adoc
downstream/modules/platform/proc-install-aap-operator.adoc
downstream/modules/platform/proc-installing-hub-using-operator.adoc
downstream/modules/platform/proc-installing-the-ansible-platform-operator.adoc
downstream/modules/platform/proc-operator-access-aap.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc
downstream/modules/platform/proc-operator-link-components.adoc
downstream/modules/platform/proc-update-rhsso-client.adoc

* Updating procedure steps to better orientate the user

Installing on Openshift Container Platform - UI updates (#1775)

---

downstream/assemblies/platform/assembly-ug-controller-schedules.adoc
downstream/modules/platform/proc-controller-adding-new-schedule.adoc
downstream/modules/platform/proc-controller-define-schedule-rules.adoc

* Updated Schedules information
Update procedures for Schedules
https://issues.redhat.com/browse/AAP-29720
* Updated schedules information
Correction
Update procedures for Schedules
https://issues.redhat.com/browse/AAP-29720

Updated Schedules information (#1776)

---

lightspeed/modules/proc_start-lightspeed-trial.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-29906. 
Changes made:
- Updated the prerequisites
- Added a few steps in the steps. 
- Minor language edits

AAP-29906: Updated the Starting Lightspeed trial topic with few minor updates

---

downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc

AAP-29953 Fix YAML indentation in devtools example playbook

AAP-29953 Fix YAML indentation in devtools example playbook

---

downstream/attributes/attributes.adoc

This PR updates the attributes file to change the Hub navigation menu selections to represent the UI Parity work.

AAP-28751 -  Update Hub menu attributes for UI Parity work

---

downstream/attributes/attributes.adoc

This PR backports the changes from #1790 to the 2.5 branch.

[Backport] AAP-28751 -  Update Hub menu attributes for UI Parity work (#1790)

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-deploy-redis.adoc
downstream/titles/aap-operator-installation/master.adoc

[AAP-28163 ](https://issues.redhat.com/browse/AAP-28163)
- Adding a section on how to deploy Clustered Redis. 
- Updating Chapter four assembly to include this new section

Adding deploying redis section

---

downstream/modules/platform/proc-operator-deploy-redis.adoc
downstream/titles/aap-operator-installation/master.adoc

[AAP-28163](https://issues.redhat.com/browse/AAP-28163)
Adding a section on how to deploy Clustered Redis.
Updating Chapter four assembly to include this new section

Adding deploying redis section (#1796)

---

downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc

AAP-25510B Corrected typo in new content

---

downstream/assemblies/platform/assembly-inventory-introduction.adoc
downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/platform/proc-set-registry-username-password.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

https://issues.redhat.com/browse/AAP-29120
* Add procedure to set registry variables

Add procedure to set registry variables (#1802)

---

downstream/modules/platform/proc-define-mesh-node-types.adoc

hackfest doc updates for mesh -- node types
https://issues.redhat.com/browse/AAP-27007

Update node procedure

---

downstream/modules/platform/proc-define-mesh-node-types.adoc

hackfest doc updates for mesh -- node types
https://issues.redhat.com/browse/AAP-27007

Update node procedure (#1813)

---

downstream/snippets/snip-gw-authentication-additional-auth-fields.adoc
downstream/snippets/snip-gw-authentication-common-checkboxes.adoc
downstream/snippets/snip-gw-authentication-verification.adoc

This PR backports the changes from #1758 to the 2.5 branch and includes the following:
* AAP-29504 - Created snippets for repeated authentication information
* AAP-29218 corrections from peer review

[Backport] - AAP-29504 - Created snippets for repeated authentication information (#1758)

---

downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
downstream/titles/central-auth/master.adoc

This PR backports the changes from #1819 to the 2.5 branch.

[Backport] am-formatting-2 - Fixing issues with document structure/chapter breakdown (#1819)

---

downstream/modules/platform/proc-aap-controller-backup.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-hub-backup.adoc
downstream/modules/platform/proc-aap-hub-restore.adoc
downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
downstream/modules/platform/proc-aap-platform-gateway-restore.adoc

[AAP-30535](https://issues.redhat.com/browse/AAP-30535)
Most procedures are missing user orientation, such as "Log into OpenShift Container Platform" and "select your AAP deployment" Adding these additional steps in to improve UX.

improving user orientation and some minor style tweaks

---

downstream/modules/platform/proc-aap-controller-backup.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-hub-backup.adoc
downstream/modules/platform/proc-aap-hub-restore.adoc
downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
downstream/modules/platform/proc-aap-platform-gateway-restore.adoc

[AAP-30535](https://issues.redhat.com/browse/AAP-30535)
Most procedures are missing user orientation, such as "Log into OpenShift Container Platform" and "select your AAP deployment" Adding these additional steps in to improve UX.

improving user orientation and some minor style tweaks (#1826)

---

downstream/modules/platform/proc-installing-containerized-aap.adoc

Containerized installer: There's no guide to configure loadbalancer for containerized installer
https://issues.redhat.com/browse/AAP-28700

Add info on configuring load balancer for container installer

---

downstream/modules/platform/proc-installing-containerized-aap.adoc

Containerized installer: There's no guide to configure loadbalancer for containerized installer
https://issues.redhat.com/browse/AAP-28700

Add info on configuring load balancer for container installer (#1831)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/rpm-24-72.adoc
downstream/titles/release-notes/topics/rpm-version-table.adoc

2.4 Release Notes - AAP 2.4 RPM release 5th Sep
https://issues.redhat.com/browse/AAP-30626

2.4 Add rpm release notes RHSA-2024:6428

---

downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
downstream/modules/eda/con-eda-rulebook-activation-list-view.adoc
downstream/modules/eda/proc-eda-activate-webhook.adoc
downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc
downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
downstream/modules/eda/proc-eda-view-activation-output.adoc

Update the Rulebook activations chapter
https://issues.redhat.com/browse/AAP-29949
Affects `titles/eda/eda-user-guide`

Adding new content for 2.5 to rulebook act. chapter

---

downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
downstream/modules/eda/con-eda-rulebook-activation-list-view.adoc
downstream/modules/eda/proc-eda-activate-webhook.adoc
downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc
downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
downstream/modules/eda/proc-eda-view-activation-output.adoc

* Adding new content for 2.5 to rulebook act. chapter
Update the Rulebook activations chapter
https://issues.redhat.com/browse/AAP-29949
Affects `titles/eda/eda-user-guide`
* Further edits to rulebook act. chapter
* Further edits to rulebook chapter

Adding new content for 2.5 to rulebook act. chapter (#1793)

---

downstream/assemblies/topologies/assembly-ocp-topologies.adoc
downstream/titles/topologies/master.adoc

[AAP-28228
](https://issues.redhat.com/browse/AAP-28228)
Files added:
- assembly-ocp-topologies.adoc
- topologies/master.adoc

AAP-28228 added OCP assembly

---

downstream/assemblies/topologies/assembly-container-topologies.adoc
downstream/assemblies/topologies/assembly-rpm-topologies.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

Add RPM and CONT modules to topology docs

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/installer-24-71.adoc
downstream/titles/release-notes/topics/installer-version-table.adoc
downstream/titles/release-notes/topics/rpm-24-71.adoc
downstream/titles/release-notes/topics/rpm-24-72.adoc
downstream/titles/release-notes/topics/rpm-version-table.adoc

2.4 Release Notes - AAP 2.4 RPM release 5th Sep
https://issues.redhat.com/browse/AAP-30626

2.4 Add rpm-24-71 to async release notes

---

downstream/assemblies/topologies/assembly-container-topologies.adoc
downstream/assemblies/topologies/assembly-rpm-topologies.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

2.5 Add RPM and CONT modules to topology docs (#1841)

---

downstream/assemblies/eda/assembly-eda-credential-types.adoc
downstream/assemblies/eda/assembly-eda-credentials.adoc
downstream/modules/eda/con-credential-types-list-view.adoc
downstream/modules/eda/con-credentials-list-view.adoc
downstream/modules/eda/con-custom-credential-types.adoc
downstream/modules/eda/proc-eda-delete-credential.adoc
downstream/modules/eda/proc-eda-edit-credential.adoc
downstream/modules/eda/proc-eda-set-up-credential-types.adoc
downstream/modules/eda/proc-eda-set-up-credential.adoc
downstream/titles/eda/eda-user-guide/master.adoc

Updated the Credentials topics and created a new chapter, Credential types.

AAP-22022 Document the 2.5 changes for Credentials

---

downstream/assemblies/topologies/assembly-container-topologies.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc

Add CONT-A-ENV-A to topology docs

---

downstream/assemblies/topologies/assembly-container-topologies.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc

Add CONT-A-ENV-A to topology docs (#1849)

---

downstream/assemblies/central-auth/assembly-central-auth-automate-keycloak.adoc
downstream/modules/platform/proc-central-auth-install-dependencies.adoc
downstream/modules/platform/proc-central-auth-install-keycloak.adoc
downstream/modules/platform/ref-controller-database-settings.adoc

This is a backport of AAP-19988. The PR for the original was PR 1846.

AAP-19988 (#1846)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/installer-24-72.adoc
downstream/titles/release-notes/topics/installer-version-table.adoc

2.4 Release Notes - AAP 2.4-7.2 Bundle Installer release
https://issues.redhat.com/browse/AAP-28956

2.4 Add bundle installer 2.4-7.2 release notes

---

downstream/assemblies/topologies/assembly-container-topologies.adoc
downstream/assemblies/topologies/assembly-ocp-topologies.adoc
downstream/assemblies/topologies/assembly-overview-supported-deployment-models.adoc
downstream/assemblies/topologies/assembly-rpm-topologies.adoc
downstream/attributes/attributes.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-mesh-nodes.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/titles/topologies/docinfo.xml
downstream/titles/topologies/master.adoc

- Update doc title to "Tested" instead of "Supported"
- Feedback from peer review of KCS articles
- Add automation mesh nodes section

Update topologies based on feedback

---

downstream/assemblies/topologies/assembly-container-topologies.adoc
downstream/assemblies/topologies/assembly-ocp-topologies.adoc
downstream/assemblies/topologies/assembly-overview-supported-deployment-models.adoc
downstream/assemblies/topologies/assembly-rpm-topologies.adoc
downstream/attributes/attributes.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-mesh-nodes.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/titles/topologies/docinfo.xml
downstream/titles/topologies/master.adoc

- Update doc title to "Tested" instead of "Supported"
- Feedback from peer review of KCS articles

2.5 Update topologies based on feedback (#1856)

---

downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc

[AAP-28228](https://issues.redhat.com/browse/AAP-28228)
Edits made following peer review of KCS articles
- https://access.redhat.com/articles/7082955
- https://access.redhat.com/articles/7082956
- ref-ocp-a-env-a.adoc
- ref-ocp-b-env-a.adoc

AAP-28228-B updated OCP-A-ENV-A

---

downstream/modules/platform/ref-guidelines-hosts-groups.adoc

[AAP-29177](https://issues.redhat.com/browse/AAP-29177)
Updated language around symbol restrictions for creating hostnames
See [slack thread](https://redhat-internal.slack.com/archives/C0696FT8NBE/p1723110060346959) for further background info

AAP-29177 updated FDQN guidelines

---

downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc

This PR updates the Creating a user and Teams content with corrections and recent UI changes for https://issues.redhat.com/browse/AAP-29118.

AAP-29118 - Update Creating a user with UI changes

---

downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc

This PR backports the changes from #1863 to the 2.5 branch.

[Backport] AAP-29918 - Update Creating a user with UI changes (#1863)

---

downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
downstream/modules/platform/proc-controller-ingress-options.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc
downstream/modules/platform/proc-operator-link-components.adoc

[AAP-30853](https://issues.redhat.com/browse/AAP-30853) 
- Added information on topologies in the about section
- Applied some SME feedback across multiple sections

aap-30853 topology and minor updates

---

downstream/modules/platform/ref-system-requirements.adoc

[cee.neXT] [Docs] Incorrect operating system information listed in the AAP system requirements.
https://issues.redhat.com/browse/AAP-29234

Updated RHEL requirements

---

downstream/modules/platform/proc-configuring-controller-ldap-security.adoc

Main edits for this request were done in [AAP-30853](https://issues.redhat.com/browse/AAP-30853) just circling back to add a link to the Authentication doc now that it's ready.

Adding link to authentication

---

downstream/modules/platform/proc-configuring-controller-ldap-security.adoc

Main edits for this request were done in [AAP-30853](https://issues.redhat.com/browse/AAP-30853) just circling back to add a link to the Authentication doc now that it's ready.

Adding link to authentication (#1876)

---

downstream/modules/platform/proc-controller-configure-system.adoc

Remove entry from System settings
https://issues.redhat.com/browse/AAP-30850

Remove field from procedure

---

downstream/modules/platform/proc-controller-configure-system.adoc

Remove entry from System settings
https://issues.redhat.com/browse/AAP-30850

Remove field from procedure (#1878)

---

downstream/titles/analytics/aap-common/apache-2.0-license.adoc
downstream/titles/analytics/aap-common/assembly-aap-common.adoc
downstream/titles/analytics/aap-common/boilerplate.adoc
downstream/titles/analytics/aap-common/external-site-disclaimer.adoc
downstream/titles/analytics/aap-common/gplv3-license-text.adoc
downstream/titles/analytics/aap-common/making-open-source-more-inclusive.adoc
downstream/titles/analytics/aap-common/providing-feedback.adoc
downstream/titles/analytics/attributes/attributes.adoc
downstream/titles/analytics/docinfo.xml
downstream/titles/analytics/master.adoc

AAP-26519-A: child of [AAP-26519](https://issues.redhat.com/browse/AAP-26519?filter=-1)
Book title: Using automation analytics 
New files:
- master.adoc
- docinfo.xml
- aap-common/apache-2.0-license.adoc
- aap-common/assembly-aap-common.adoc
- aap-common/boilerplate.adoc
- aap-common/external-site-disclaimer.adoc
- aap-common/gplv3-license-text.adoc
- aap-common/making-open-source-more-inclusive.adoc
- aap-common/providing-feedback.adoc
- attributes/attributes.adoc
New folders: 
- aap-common/
- attributes/

AAP-26519-A created structure for new book title: Using AA

---

downstream/titles/analytics/aap-common/apache-2.0-license.adoc
downstream/titles/analytics/aap-common/assembly-aap-common.adoc
downstream/titles/analytics/aap-common/boilerplate.adoc
downstream/titles/analytics/aap-common/external-site-disclaimer.adoc
downstream/titles/analytics/aap-common/gplv3-license-text.adoc
downstream/titles/analytics/aap-common/making-open-source-more-inclusive.adoc
downstream/titles/analytics/aap-common/providing-feedback.adoc
downstream/titles/analytics/attributes/attributes.adoc
downstream/titles/analytics/docinfo.xml
downstream/titles/analytics/master.adoc

2.5 backport of [PR 1824](https://github.com/ansible/aap-docs/pull/1824)
AAP-26519-A: child of [AAP-26519](https://issues.redhat.com/browse/AAP-26519?filter=-1)
Book title: Using automation analytics
New files:
master.adoc
docinfo.xml
aap-common/apache-2.0-license.adoc
aap-common/assembly-aap-common.adoc
aap-common/boilerplate.adoc
aap-common/external-site-disclaimer.adoc
aap-common/gplv3-license-text.adoc
aap-common/making-open-source-more-inclusive.adoc
aap-common/providing-feedback.adoc
attributes/attributes.adoc
New folders:
aap-common/
attributes/

AAP-26519-A created structure for new book title: Using AA (#1824)

---

downstream/modules/platform/proc-aap-activate-with-credentials.adoc
downstream/modules/platform/proc-aap-activate-with-manifest.adoc
downstream/modules/platform/ref-controller-automation-analytics.adoc

This PR implements the changes to Analytics opt in to the 2.4 docs content.

AAP-30863 update 2.4 docs for automatic Analytics opt in changes

---

downstream/assemblies/platform/assembly-gateway-licensing.adoc
downstream/modules/platform/proc-aap-activate-with-credentials.adoc
downstream/modules/platform/ref-controller-node-counting.adoc

This PR implements the minor peer review changes from the review of Backport #1882.

AAP19528_a - Implement peer review changes from backport PR#1882

---

downstream/assemblies/platform/assembly-gateway-licensing.adoc
downstream/modules/platform/proc-aap-activate-with-credentials.adoc
downstream/modules/platform/ref-controller-node-counting.adoc

This PR backports the changes from #1883 to the 2.5 branch.

[Backport] AAP19528_a - Implement peer review changes from backport PR#1882 (#1883)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/proc-using-postinstall.adoc
downstream/titles/aap-containerized-install/docinfo.xml

Containerized installer - implement hackathon docs feedback
https://issues.redhat.com/browse/AAP-30481

Update containerized install guide

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/proc-using-postinstall.adoc

* Update containerized install guide
Containerized installer - implement hackathon docs feedback
https://issues.redhat.com/browse/AAP-30481

2.5 Update containerized install guide (#1885)

---

downstream/titles/navigator-guide/docinfo.xml
downstream/titles/navigator-guide/master.adoc

Rename navigator guide to Using content navigator, per the Miro board titles.

Rename navigator guide to Using content navigator

---

downstream/titles/navigator-guide/docinfo.xml
downstream/titles/navigator-guide/master.adoc

Rename navigator guide to _Using content navigator_, per the Miro board titles.

2.5 Rename navigator guide to Using content navigator (#1887)

---

downstream/modules/platform/proc-controller-importing-subscriptions.adoc

This PR adds the information about automatic analytics opt in to the Importing a subscription module.

AAP30863-a - Updated 2.4 subscription import to reflect analytics opt in changes

---

downstream/assemblies/platform/assembly-controller-applications.adoc
downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
downstream/modules/platform/proc-controller-apps-create-tokens.adoc
downstream/modules/platform/proc-controller-create-application.adoc
downstream/modules/platform/ref-controller-app-token-functions.adoc
downstream/modules/platform/ref-controller-applications-getting-started.adoc
downstream/modules/platform/ref-controller-revoke-access-token.adoc
downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
downstream/modules/platform/ref-gw-application-functions.adoc
downstream/modules/platform/ref-gw-request-token-after-expiration.adoc

This PR moves and updates the OAuth and Applications content into the Access management guide.

AAP18813 - Adding OAuth/Application content to the access management guide

---

downstream/attributes/attributes.adoc
downstream/titles/topologies/docinfo.xml
downstream/titles/topologies/master.adoc

Update the topology doc title from "Tested deployment models for Ansible Automation Platform" to "Tested deployment models" per Miro board docs titles.

Update topology doc title

---

downstream/attributes/attributes.adoc
downstream/titles/topologies/docinfo.xml
downstream/titles/topologies/master.adoc

Update the topology doc title from "Tested deployment models for Ansible Automation Platform" to "Tested deployment models" per Miro board docs titles.

2.5 Update topology doc title (#1899)

---

downstream/modules/platform/proc-installing-containerized-aap.adoc

Add product docs for containerized + clustered redis
https://issues.redhat.com/browse/AAP-28161

Add Redis config info to containerized installer guide

---

downstream/modules/platform/proc-installing-containerized-aap.adoc

Add product docs for containerized + clustered redis
https://issues.redhat.com/browse/AAP-28161

2.5 Add Redis config info to containerized installer guide (#1905)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc

Containerized installer - implement hackathon docs feedback
https://issues.redhat.com/browse/AAP-30481

Update links in inventory files for containerized install

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc

Containerized installer - implement hackathon docs feedback
https://issues.redhat.com/browse/AAP-30481

2.5 Update links in inventory files for containerized install (#1908)

---

downstream/modules/platform/con-about-operator.adoc

Updating to new iteration of the required topology link.

updating topology link

---

downstream/modules/platform/con-about-operator.adoc

Updating to new iteration of the required topology link.

updating topology link (#1910)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/titles/topologies/master.adoc

Updates to URL and other references as the topology guide title changed from "Supported" to "Tested".

Update url & references to topology guide

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/titles/topologies/master.adoc

Updates to URL and other references as the topology guide title changed from "Supported" to "Tested"

2.5 Update url & references to topology guide (#1912)

---

downstream/attributes/attributes.adoc

Create attributes for docs links so that external links to other docs in the AAP docset don't change when titles are updated.
Backport to 2.5

AAP-31307 Add attributes for title URLs

---

downstream/attributes/attributes.adoc

Adds attributes for the following:
* Full titles
* "base" URL for all titles
* "full" URL with alt-text for all titles

2.4 AAP-31308 Attributes for title names and URLs

---

downstream/attributes/attributes.adoc

Create attributes for docs links so that external links to other docs in the AAP docset don't change when titles are updated.

2.5 AAP-31307 Add attributes for title URLs (#1895)

---

downstream/assemblies/platform/assembly-controller-applications.adoc
downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
downstream/modules/platform/proc-controller-apps-create-tokens.adoc
downstream/modules/platform/proc-controller-create-application.adoc
downstream/modules/platform/ref-controller-app-token-functions.adoc
downstream/modules/platform/ref-controller-applications-getting-started.adoc
downstream/modules/platform/ref-controller-revoke-access-token.adoc
downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
downstream/modules/platform/ref-gw-application-functions.adoc
downstream/modules/platform/ref-gw-request-token-after-expiration.adoc

This PR backports the changes from #1874 to the 2.5 branch and includes the following:
* AAP18813 - Adding OAuth/Application content to the access management guide

AAP18813 - Adding OAuth/Application content to the access management guid (#1874)

---

downstream/attributes/attributes.adoc
downstream/modules/devtools/proc-devtools-install-container.adoc

https://issues.redhat.com/browse/AAP-30395
AAP-30395 Fix JSON example and update devtools attribute

AAP-30395 Fix JSON example and update devtools attribute

---

downstream/attributes/attributes.adoc
downstream/modules/devtools/proc-devtools-install-container.adoc

https://issues.redhat.com/browse/AAP-30395
AAP-30395 Fix JSON example and update devtools attribute

2.4 AAP-30395 Fix JSON example and update devtools attribute (#1926)

---

downstream/attributes/attributes.adoc
downstream/modules/devtools/proc-devtools-install-container.adoc

https://issues.redhat.com/browse/AAP-30395
AAP-30395 Fix JSON example and update devtools attribute

2.5 AAP-30395 Fix JSON example and update devtools attribute (#1926)

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

This PR backports the changes from #1924 to the 2.5 branch.

[Backport] AAP-26512 - Update example for SAML Security Config per SME feedback

---

downstream/attributes/attributes.adoc

AAP-25769 Update ansible-core and PlatformDownloadURL attributes for 2.5

AAP-25769 Update ansible-core and PlatformDownloadURL attributes for 2.5

---

downstream/assemblies/platform/assembly-disconnected-installation.adoc
downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
downstream/modules/platform/proc-completing-post-installation-tasks.adoc
downstream/modules/platform/proc-creating-a-new-web-server-to-host-repositories.adoc
downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc

* AAP-30807 Commented out, and updated text for the 2.5 release.

AAP-30807 Commented out, and updated text for the 2.5 release. (#1929)

---

downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc
downstream/assemblies/platform/assembly-controller-secret-management.adoc
downstream/modules/platform/con-controller-overview-details.adoc
downstream/modules/platform/con-controller-role-based-access-controls.adoc
downstream/modules/platform/proc-controller-configure-analytics.adoc
downstream/modules/platform/proc-controller-importing-subscriptions.adoc
downstream/modules/platform/proc-controller-view-host.adoc
downstream/modules/platform/ref-controller-analytics-reports.adoc
downstream/modules/platform/ref-controller-automation-analytics.adoc
downstream/modules/platform/ref-controller-content-sourcing.adoc
downstream/titles/controller/controller-admin-guide/master.adoc
downstream/titles/controller/controller-user-guide/master.adoc

Remove TBDs from Controller documentation
https://issues.redhat.com/browse/AAP-30985

Removing TBDs from Controller docs

---

downstream/modules/platform/con-controller-role-based-access-controls.adoc
downstream/modules/platform/proc-controller-create-instance-group.adoc

This PR includes a peer review fix for PR #1933.

Include peer review fixes for PR 1933

---

downstream/modules/platform/con-controller-role-based-access-controls.adoc
downstream/modules/platform/proc-controller-create-instance-group.adoc

This PR backports the changes from #1934 to the 2.5 branch.

[Backport] Include peer review fixes for PR 1933 (#1934)

---

downstream/modules/builder/proc-executing-build.adoc
downstream/modules/platform/ref-controller-install-builder.adoc

Unable to run job in custom EE
https://issues.redhat.com/browse/AAP-30674
Affects `controller/user-guide` and `builder`

Adding note about building EE image

---

downstream/assemblies/devtools/assembly-devtools-install.adoc
downstream/modules/devtools/con-devtools-requirements.adoc
downstream/modules/devtools/proc-devtools-install-container.adoc
downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc

AAP-30403 Add registry.redhat.io authentication procedure to devtools doc.

2.5 AAP-30403 Add registry.redhat.io auth procedure to devtools (#1937)

---

downstream/assemblies/devtools/assembly-devtools-install.adoc
downstream/modules/devtools/con-devtools-requirements.adoc
downstream/modules/devtools/proc-devtools-install-container.adoc
downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc

AAP-30403 Add registry.redhat.io authentication procedure to devtools doc.

2.4 AAP-30403 Add registry.redhat.io auth procedure to devtools (#1937)

---

downstream/modules/builder/proc-executing-build.adoc
downstream/modules/platform/ref-controller-install-builder.adoc

Unable to run job in custom EE
https://issues.redhat.com/browse/AAP-30674
Affects `controller/user-guide` and `builder`

Adding note about building EE image (#1870)

---

downstream/assemblies/platform/assembly-platform-install-overview.adoc
downstream/assemblies/platform/assembly-system-requirements.adoc
downstream/modules/platform/proc-benchmark-postgresql.adoc
downstream/modules/platform/proc-enable-hstore-extension.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
downstream/modules/platform/ref-automation-hub-requirements.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/platform/ref-eda-system-requirements.adoc
downstream/modules/platform/ref-gateway-system-requirements.adoc
downstream/modules/platform/ref-ha-hub-reqs.adoc
downstream/modules/platform/ref-postgresql-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc

[AAP-30807](https://issues.redhat.com/browse/AAP-30807) 
Draft: 
https://docs.google.com/document/d/1fIrlSrj8bSSWBVptXWmm0ZFixhZ4mM5pW2CQx_3Oh7A/edit
Tracker:
https://docs.google.com/spreadsheets/d/1APv4UzRGABm8ItMtTY6aiIcxWBtGU_sA/edit?gid=679299608#gid=679299608

AAP-30807 - Converting Overview and System requirements assemblies into repo

---

downstream/modules/platform/proc-define-mesh-node-types.adoc
downstream/modules/platform/proc-set-up-virtual-machines.adoc

Corrections
Corrections from Hackathon for operator-mesh doc
https://issues.redhat.com/browse/AAP-30570

Update procedures for automation mesh

---

downstream/modules/platform/proc-define-mesh-node-types.adoc
downstream/modules/platform/proc-set-up-virtual-machines.adoc

* Update procedures for automation mesh
Corrections
Corrections from Hackathon for operator-mesh doc
https://issues.redhat.com/browse/AAP-30570
---------

Update procedures for automation mesh (#1944)

---

downstream/attributes/attributes.adoc
downstream/modules/devtools/con-devtools-requirements.adoc
downstream/modules/devtools/ref-rhdh-learning.adoc
downstream/modules/platform/con-gs-developer-tools.adoc

Change devtools name to Development tools

2.5 Change devtools name to Development tools (#1949)

---

downstream/attributes/attributes.adoc
downstream/modules/devtools/con-devtools-requirements.adoc
downstream/modules/devtools/ref-rhdh-learning.adoc

Change devtools name to Development tools

2.4 Change devtools name to Development tools (#1949)

---

downstream/assemblies/platform/assembly-gw-settings.adoc
downstream/modules/platform/proc-controller-configure-subscriptions.adoc
downstream/modules/platform/proc-settings-gw-additional-options.adoc
downstream/modules/platform/proc-settings-gw-custom-login.adoc
downstream/modules/platform/proc-settings-gw-password-security.adoc
downstream/modules/platform/proc-settings-gw-security-options.adoc
downstream/modules/platform/proc-settings-gw-session-options.adoc
downstream/modules/platform/proc-settings-platform-gateway.adoc
downstream/modules/platform/proc-settings-troubleshooting.adoc
downstream/modules/platform/proc-settings-user-preferences.adoc

This PR updates the Settings > [menu] content based on hackathon feedback for [AAP-30592]https://issues.redhat.com/browse/AAP-30592

AAP-30592 - Divide the Platform gateway settings into separate procedures by option

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc

Added xrefs to assembly-overview-tested-deployment-models.adoc

AAP-28228-C added xrefs to topology table

---

downstream/attributes/attributes.adoc

Add title, URL attributes for Lightspeed

AAP-31307a Add title, URL attributes for Lightspeed

---

downstream/attributes/attributes.adoc

AAP-31307a Add title, URL attributes for Lightspeed

AAP-31307a Add title, URL attributes for Lightspeed (#1959)

---

downstream/modules/devtools/proc-devtools-install-container.adoc

Update the `devcontainer.json` file in teh devtools doc following the DeveloperTools  ADT 24.9.0 release: https://github.com/ansible/ansible-dev-tools/tree/main/.devcontainer

2.5 AAP-29500 Update devcontainer.json (#1972)

---

downstream/modules/devtools/proc-devtools-install-container.adoc

Update the `devcontainer.json` file in teh devtools doc following the DeveloperTools  ADT 24.9.0 release: https://github.com/ansible/ansible-dev-tools/tree/main/.devcontainer

AAP-29500 Update devcontainer.json (#1972)

---

downstream/modules/platform/ref-automation-hub-requirements.adoc

Remove git artefacts from a platform module.
Affects `/titles/aap-installation-guide`

AAP-30807 Remove git artefacts

---

reviews/RPM Installations 2.5 _ Test.md

This PR is adding a test file for SME review purposes.

adding test review file

---

downstream/attributes/attributes.adoc

AAP-31577 Add attribute for unified platform dashboard
Backport to 2.5 only

AAP-31577 Add attribute for unified platform dashboard

---

downstream/attributes/attributes.adoc

AAP-31577 Add attribute for unified platform dashboard

2.5 AAP-31577 Add attribute for unified platform dashboard (#1984)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/rpm-24-73.adoc
downstream/titles/release-notes/topics/rpm-version-table.adoc

AAP 2.4-7.3 Release notes
https://issues.redhat.com/browse/AAP-31171

2.4 Add RPM 2.4-7.3 async release notes

---

downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

Add Redis VMs to RPM topologies

Update topology docs based on feedback

---

downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

Add Redis VMs to RPM topologies

2.5 Update topology docs based on feedback (#1991)

---

downstream/modules/platform/proc-attaching-subscriptions.adoc

This PR includes the changes requested in https://issues.redhat.com/browse/AAP-30602.

AAP-30602 - Include step to register and update commands to include sudo

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

- [RPM Installation 2.5 Draft](https://docs.google.com/document/d/1fIrlSrj8bSSWBVptXWmm0ZFixhZ4mM5pW2CQx_3Oh7A/edit#heading=h.pcplsjwxwvz8)
- Used this[ Inventory var diff](https://docs.google.com/spreadsheets/d/1wSZiIoDu-_uRY8l1R1vYQlOG5PPrK4MrP3jla8701KA/edit?gid=413143671#gid=413143671) spreadsheet to include container variables to the table: [General variables](https://docs.google.com/document/d/1fIrlSrj8bSSWBVptXWmm0ZFixhZ4mM5pW2CQx_3Oh7A/edit#heading=h.pcplsjwxwvz8)
- Made a revision to the assembly to reorder the tables.

AAP-30807-A: Add General variables for container

---

downstream/modules/platform/ref-eda-system-requirements.adoc

Updated the EDA controller system requirement, per hackathon request and SME suggestions.
Note: This content was approved in a previous PR by SME @jamesmarshall24 in PR https://github.com/ansible/aap-docs/pull/1848. Due to merge conflicts with updated doc (new info no longer matched content in older PR), started new PR to move forward with processes.

AAP-22994B Update disk requirements for Event-Driven Ansible controller

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-images-inventory-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

Addition of the following vars sections:
- ref-images-inventory-variables.adoc
- ref-database-inventory-variables.adoc
- ref-receptor-inventory-variables.adoc

2.5 Update inventory file vars appendix (#2003)

---

downstream/modules/platform/ref-controller-variables.adoc

Update the following file: ref-controller-variables.adoc

Update controller inventory vars appendix

---

downstream/modules/platform/ref-controller-variables.adoc

Update the following file: ref-controller-variables.adoc

2.5 Update controller inventory vars appendix (#2005)

---

downstream/modules/platform/con-declaring-variables.adoc
downstream/modules/platform/proc-installing-with-internet.adoc

[AAP-29294](https://issues.redhat.com/browse/AAP-29294?filter=-1)
- con-declaring-variables.adoc
- proc-installing-with-internet.adoc

AAP-29294 updated version numbers and disclaimer

---

downstream/modules/platform/con-declaring-variables.adoc
downstream/modules/platform/proc-installing-with-internet.adoc

2.5 backport of [PR 2008](https://github.com/ansible/aap-docs/pull/2008)
con-declaring-variables.adoc
proc-installing-with-internet.adoc

AAP-29294 updated version numbers and disclaimer (#2008)

---

downstream/modules/platform/proc-attaching-subscriptions.adoc

This PR backports the changes from #1995 to the 2.5 branch.

[Backport] AAP-30602 - Include step to register and update commands to include sudo (#1995)

---

downstream/modules/devtools/proc-devtools-install-container.adoc

Update devcontainer.json files from https://github.com/ansible/ansible-dev-tools/blob/main/.devcontainer/podman/devcontainer.json and https://github.com/ansible/ansible-dev-tools/blob/main/.devcontainer/docker/devcontainer.json

Devtools: Update devcontainer.json file

---

downstream/modules/devtools/proc-devtools-install-container.adoc

Update devcontainer.json files from https://github.com/ansible/ansible-dev-tools/blob/main/.devcontainer/podman/devcontainer.json and https://github.com/ansible/ansible-dev-tools/blob/main/.devcontainer/docker/devcontainer.json

2.5 Update devcontainer.json file (#2011)

---

downstream/modules/devtools/proc-devtools-install-container.adoc

Update devcontainer.json files from https://github.com/ansible/ansible-dev-tools/blob/main/.devcontainer/podman/devcontainer.json and https://github.com/ansible/ansible-dev-tools/blob/main/.devcontainer/docker/devcontainer.json

2.4 Update devcontainer.json file (#2011)

---

stories/assembly-azure-access.adoc
stories/assembly-azure-connecting-to-aap.adoc
stories/assembly-azure-deploy.adoc
stories/assembly-azure-install-prerequisites.adoc
stories/assembly-azure-install.adoc
stories/assembly-azure-post-deployment-requirements.adoc
stories/topics/con-azure-entitling-subscription.adoc
stories/topics/con-azure-policy.adoc
stories/topics/con-azure-private-dns.adoc
stories/topics/con-azure-user-defined-routing-tables.adoc
stories/topics/con-azure-virtual-appliance-routing.adoc
stories/topics/proc-azure-cancel-deployment.adoc
stories/topics/proc-azure-nw-access-details.adoc
stories/topics/proc-azure-provisioning-aap.adoc
titles/aap-on-azure/stories.adoc

AAP-29709b Azure: Reorganize Azure chapters

[Azure] AAP-29709b Azure: Reorganize Azure chapters

---

downstream/modules/platform/ref-eda-system-requirements.adoc

Updated the EDA controller system requirement, per hackathon request and SME suggestions.

Backport-2.5-2000 (AAP-22994B) Update disk requirements for Event-Driven Ansible controller

---

downstream/modules/platform/proc-controller-create-application.adoc
downstream/modules/platform/ref-controller-applications-getting-started.adoc
downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
downstream/modules/platform/ref-gw-application-functions.adoc
downstream/modules/platform/ref-gw-request-token-after-expiration.adoc

This PR reconciles the "Configuring access to external applications with token-based authentication" to address the latest UI button name and review changes.

18813 - reconciling token auth content with late UI changes

---

downstream/modules/platform/proc-controller-create-application.adoc
downstream/modules/platform/ref-controller-applications-getting-started.adoc
downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
downstream/modules/platform/ref-gw-application-functions.adoc
downstream/modules/platform/ref-gw-request-token-after-expiration.adoc

This PR backports the changes from #2019 to the 2.5 branch.

[Backport] 18813 - reconciling token auth content with late UI changes (#2019)

---

downstream/modules/platform/proc-gw-create-roles.adoc
downstream/modules/platform/proc-gw-delete-roles.adoc
downstream/modules/platform/proc-gw-edit-roles.adoc
downstream/modules/platform/proc-gw-roles.adoc
downstream/snippets/snip-gw-roles-note-multiple-components.adoc

This PR reconciles the chapter 6 Access management content against the post code-freeze test environment UI.

AAP-31745 - Reconcile chapter 6 of the Access management guide

---

downstream/assemblies/platform/assembly-ag-controller-config.adoc
downstream/assemblies/platform/assembly-gw-settings.adoc
downstream/modules/platform/proc-settings-gw-additional-options.adoc
downstream/modules/platform/proc-settings-gw-password-security.adoc
downstream/modules/platform/proc-settings-gw-security-options.adoc
downstream/modules/platform/proc-settings-troubleshooting.adoc
downstream/modules/platform/proc-settings-user-preferences.adoc
downstream/modules/platform/ref-controller-organization-notifications.adoc

This PR reconciles the content for Chapter 7 of the Access management guide with the post code freeze test environment. It also removes the subscription info from the controller docs since it's already covered in the access management docs.

AAP-31742 - Reconcile chapter 7 of Access management guide

---

downstream/attributes/attributes.adoc
downstream/titles/aap-installation-guide/docinfo.xml
downstream/titles/aap-installation-guide/master.adoc

- Change title from _Installing on virtual machines_ -> _**RPM installation**_
- Changed subtitle from _Install Ansible Automation Platform on virtual machines_ -> _**Install the RPM version of Ansible Automation Platform**_ (to be consistent with the containerized subtitle).
- Updated attributes

install-title-update: Changed to RPM installation

---

downstream/attributes/attributes.adoc
downstream/titles/aap-installation-guide/docinfo.xml
downstream/titles/aap-installation-guide/master.adoc

Change title from Installing on virtual machines -> **RPM installation**
Changed subtitle from Install Ansible Automation Platform on virtual machines -> **Install the RPM version of Ansible Automation Platform** (to be consistent with the containerized subtitle).
Updated attributes

[2.5] install-title-update: Changed to RPM installation (#2029)

---

downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc

Fixed a few minor nits in downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc found during peer review of backport

AAP-25510-0922 Corrected minor nits found during peer review of backport.

---

downstream/modules/platform/ref-eda-system-requirements.adoc

Adding an important part of the EDA controller system requirements to `downstream/modules/platform/ref-eda-system-requirements.adoc`

AAP-22994-0922 Added missing part of 3rd bullet for EDA controller sys requirments

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

Adding additional context to the note about the impact of Redis failure on projects.

AAP-28434-0923 Minor correction to Redis note

---

downstream/assemblies/platform/assembly-ag-controller-config.adoc
downstream/assemblies/platform/assembly-gw-settings.adoc
downstream/modules/platform/proc-settings-gw-additional-options.adoc
downstream/modules/platform/proc-settings-gw-password-security.adoc
downstream/modules/platform/proc-settings-gw-security-options.adoc
downstream/modules/platform/proc-settings-troubleshooting.adoc
downstream/modules/platform/proc-settings-user-preferences.adoc
downstream/modules/platform/ref-controller-organization-notifications.adoc

This PR backports the changes from #2022 to the 2.5 branch and includes the following: 
* AAP-31742 - Reconcile chapter 7 of Access management guide
* AAP-31742 - adding peer review changes

[Backport] AAP-31742 - Reconcile chapter 7 of Access management guide (#2022)

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

Backport-2.5-2041 (AAP-28434-0923) Minor update to Redis note (#2041)

---

downstream/assemblies/platform/assembly-controller-organizations.adoc
downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/assemblies/platform/assembly-gw-managing-access.adoc
downstream/modules/platform/con-controller-access-organizations.adoc
downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-controller-create-organization.adoc
downstream/modules/platform/proc-controller-creating-a-team.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc
downstream/modules/platform/proc-controller-deleting-a-user.adoc
downstream/modules/platform/proc-controller-review-organizations.adoc
downstream/modules/platform/proc-controller-user-permissions.adoc
downstream/modules/platform/proc-gw-add-admin-organization.adoc
downstream/modules/platform/proc-gw-add-team-organization.adoc
downstream/modules/platform/proc-gw-delete-organization.adoc
downstream/modules/platform/proc-gw-delete-team.adoc
downstream/modules/platform/proc-gw-edit-roles.adoc
downstream/modules/platform/proc-gw-organizations-exec-env.adoc
downstream/modules/platform/proc-gw-team-access-resources.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc
downstream/modules/platform/proc-gw-team-list-view.adoc
downstream/modules/platform/proc-gw-team-remove-user.adoc
downstream/modules/platform/proc-gw-user-access-resources.adoc
downstream/modules/platform/proc-gw-users-list-view.adoc
downstream/modules/platform/ref-controller-organization-notifications.adoc
downstream/modules/platform/ref-controller-user-roles.adoc
downstream/snippets/snip-gw-roles-note-multiple-components.adoc

This PR reconciles the chapter 5 content of the Access management guide with the post code-freeze test environment.

AAP-31746 Reconciling chapter 5 content of Access management guide

---

downstream/assemblies/platform/assembly-controller-organizations.adoc
downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/assemblies/platform/assembly-gw-managing-access.adoc
downstream/modules/platform/con-controller-access-organizations.adoc
downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-controller-create-organization.adoc
downstream/modules/platform/proc-controller-creating-a-team.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc
downstream/modules/platform/proc-controller-deleting-a-user.adoc
downstream/modules/platform/proc-controller-review-organizations.adoc
downstream/modules/platform/proc-controller-user-permissions.adoc
downstream/modules/platform/proc-gw-add-admin-organization.adoc
downstream/modules/platform/proc-gw-add-team-organization.adoc
downstream/modules/platform/proc-gw-delete-organization.adoc
downstream/modules/platform/proc-gw-delete-team.adoc
downstream/modules/platform/proc-gw-edit-roles.adoc
downstream/modules/platform/proc-gw-organizations-exec-env.adoc
downstream/modules/platform/proc-gw-team-access-resources.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc
downstream/modules/platform/proc-gw-team-list-view.adoc
downstream/modules/platform/proc-gw-team-remove-user.adoc
downstream/modules/platform/proc-gw-user-access-resources.adoc
downstream/modules/platform/proc-gw-users-list-view.adoc
downstream/modules/platform/ref-controller-organization-notifications.adoc
downstream/modules/platform/ref-controller-user-roles.adoc
downstream/snippets/snip-gw-roles-note-multiple-components.adoc

This PR backports the changes from #2026 to the 2.5 branch and includes the following:
* AAP-31746 Reconciling Organization content
* AAP-31746 - Reconcile Team content
* AAP-31746 - reconcile Users content
* AAP-31746 Reconcile the resource content
* AAP-31746 - Added peer review changes

[Backport] AAP-31746 Reconciling chapter 5 content of Access management guide (#2026)

---

downstream/modules/platform/proc-gw-define-rules-triggers.adoc
downstream/modules/platform/proc-gw-editing-a-user.adoc

[AAP-31729](https://issues.redhat.com/browse/AAP-31729) 
[Access management and authentication](https://docs.google.com/document/d/1mEYguv3V0WUUHBMc8tsgqlK8RB3ro8IZSlQmMuFfhww/edit#heading=h.iu6hphvgsnk7)
- added downstream/modules/platform/proc-gw-editing-a-user.adoc
- edited downstream/modules/platform/proc-gw-define-rules-triggers.adoc

AAP-31729: Editing a User & Defining Auth Mapping

---

downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc

* updated eda controller & gateway variables
* Update ref-eda-controller-variables.adoc
Changed EDA to {EDAName}

EDA Controller & EDA Controller Variables Update (#2048)

---

downstream/assemblies/platform/assembly-system-requirements.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/titles/aap-planning-guide/master.adoc

This PR adds conditional tagging to allow content sharing for the system requirements.

Add conditional tagging for reuse of sys reqs content

---

downstream/assemblies/platform/assembly-system-requirements.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/titles/aap-planning-guide/master.adoc

This PR backports the changes from #2054 to the 2.5 branch.

[Backport] Add conditional tagging for reuse of sys reqs content (#2054)

---

downstream/assemblies/platform/assembly-gs-auto-dev.adoc
downstream/modules/platform/con-gs-ansible-roles.adoc
downstream/modules/platform/con-gs-auto-dev-about-inv.adoc
downstream/modules/platform/con-gs-create-automation-content.adoc
downstream/modules/platform/con-gs-define-events-rulebooks.adoc
downstream/modules/platform/con-gs-execution-env.adoc
downstream/modules/platform/con-gs-learn-about-collections.adoc
downstream/modules/platform/con-gs-setting-up-dev-env.adoc
downstream/modules/platform/proc-gs-add-ee-to-job-template.adoc
downstream/modules/platform/proc-gs-auto-dev-create-automation-decision-proj.adoc
downstream/modules/platform/proc-gs-auto-dev-create-automation-execution-proj.adoc
downstream/modules/platform/proc-gs-auto-dev-set-up-decision-env.adoc
downstream/modules/platform/proc-gs-creating-a-role.adoc
downstream/modules/platform/proc-gs-publish-to-a-collection.adoc
downstream/modules/platform/proc-gs-upload-collection.adoc
downstream/modules/platform/proc-gs-use-base-execution-env.adoc

This PR backports the changes from PR 1998 to the 2.5 branch. See [AAP-29086](https://issues.redhat.com/browse/AAP-29068) for more info
* populating content for Getting started as automation dev
* populating modules
* populates modules
* populating EDA and inventory modules
* updates from peer review feedback
* further peer review edits
* small edit
* peer review feedback
* fixing final typos

backport to 2.5: AAP-29068: populating content for Getting started as automation dev (#1998)

---

downstream/modules/platform/ref-example-OCP-architecture.adoc

This PR backports the change from #2059 to the 2.5 branch.

[Backport] pg-image - Fix image case to eliminate build errors (#2059)

---

downstream/titles/analytics/master.adoc

Updated abstract for _Using Automation Analytics_
Files mofidied:
- master.adoc

AAP-26519-C updated abstract

---

downstream/titles/analytics/master.adoc

2.5 backport of [PR 2063](https://github.com/ansible/aap-docs/pull/2063)
Updated abstract for Using Automation Analytics
- master.adoc

AAP-26519-C updated abstract (#2063)

---

downstream/modules/devtools/proc-devtools-install-container.adoc
downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc
downstream/modules/devtools/proc-devtools-working-with-ee.adoc

AAP-30403a Devtools: specify the ID for registry login
Affects `/titles/develop-automation-content/`

AAP-30403a Devtools: specify the id for registry login

---

downstream/modules/devtools/proc-devtools-install-container.adoc
downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc
downstream/modules/devtools/proc-devtools-working-with-ee.adoc

AAP-30403a Devtools: specify the ID for registry login
Affects /titles/develop-automation-content/
Backports #1979

2.4 AAP-30403a Devtools: registry login details (#1979)

---

downstream/modules/devtools/proc-devtools-install-container.adoc
downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc
downstream/modules/devtools/proc-devtools-working-with-ee.adoc

AAP-30403a Devtools: specify the ID for registry login
Affects /titles/develop-automation-content/
Backports #1979

2.5 AAP-30403a Devtools: registry login details (#1979)

---

downstream/modules/platform/ref-example-OCP-architecture.adoc

2.5 backport of [PR 2073](https://github.com/ansible/aap-docs/pull/2073)
Updated image file path for OCP architecture diagram in the Planning guide
master.adoc

AAP-29295-C updated OCP arch diagram (#2073)

---

downstream/modules/platform/con-gw-overview-access-auth.adoc
downstream/modules/platform/proc-attaching-subscriptions.adoc
downstream/modules/platform/proc-gw-define-rules-triggers.adoc
downstream/modules/platform/proc-settings-user-preferences.adoc
downstream/titles/central-auth/master.adoc

This PR reconciles the chapters 1, 2, and 4 content of the Access management guide with the post code-freeze test environment and late review comments.

AAP-31846 - Reconcile chapters 1, 2 and 4 of Access management guide

---

downstream/assemblies/analytics/assembly-automation-savings-planner.adoc
downstream/modules/analytics/con-review-savings-calculations.adoc
downstream/modules/analytics/proc-link-plan-job-template.adoc
downstream/modules/analytics/proc-review-reports.adoc

Updated language in _Using automation analytics_
- assembly-automation-savings-planner.adoc
- con-review-savings-calculations.adoc
- proc-link-plan-job-template.adoc
- proc-review-reports.adoc

AAP-26519-D updated langauge

---

downstream/assemblies/analytics/assembly-automation-savings-planner.adoc
downstream/modules/analytics/con-review-savings-calculations.adoc
downstream/modules/analytics/proc-link-plan-job-template.adoc
downstream/modules/analytics/proc-review-reports.adoc

2.5 backport of [PR 2079](https://github.com/ansible/aap-docs/pull/2079)
Updated language in _Using automation analytics_
- assembly-automation-savings-planner.adoc
- con-review-savings-calculations.adoc
- proc-link-plan-job-template.adoc
- proc-review-reports.adoc

AAP-26519-D updated langauge (#2079)

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Updates to the following vars sections:
- ref-controller-variables.adoc
- ref-database-inventory-variables.adoc
- ref-eda-controller-variables.adoc
- ref-gateway-variables.adoc
- ref-general-inventory-variables.adoc
- ref-hub-variables.adoc

Update inventory file vars appendix

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Updates to the following vars sections:
- ref-controller-variables.adoc
- ref-database-inventory-variables.adoc
- ref-eda-controller-variables.adoc
- ref-gateway-variables.adoc
- ref-general-inventory-variables.adoc
- ref-hub-variables.adoc

2.5 Update inventory file vars appendix (#2082)

---

downstream/attributes/attributes.adoc

This PR adds attributes for platform gateway and Platform gateway to be implemented post 2.5 GA in case of a name change.

Add attributes for platform gateway

---

downstream/attributes/attributes.adoc

This PR backports the changes from #2089 to the 2.5 branch.

[Backport] Add attributes for platform gateway (#2089)

---

downstream/modules/platform/con-gs-auto-op-about-inv.adoc
downstream/modules/platform/con-gs-auto-op-execute-inv.adoc
downstream/modules/platform/con-gs-auto-op-job-templates.adoc
downstream/modules/platform/con-gs-automation-execution-jobs.adoc
downstream/modules/platform/proc-gs-auto-op-launch-template.adoc
downstream/modules/platform/proc-gs-auto-op-projects.adoc
downstream/modules/platform/proc-gs-auto-op-review-job-output.adoc
downstream/modules/platform/proc-gs-auto-op-review-job-status.adoc

See[ AAP-29069 ](https://issues.redhat.com/browse/AAP-29069)for more info.

AAP-29069 pt 2: populates remaining modules for automation operator section

---

downstream/assemblies/builder/assembly-publishing-exec-env.adoc
downstream/assemblies/hub/assembly-populate-container-registry.adoc
downstream/modules/builder/proc-customize-ee-image.adoc
downstream/modules/builder/proc-installing-builder.adoc
downstream/modules/builder/ref-scenario-using-authentication-ee.adoc

Corrections, but some links are to non-existent docs
Correct Creating and Using Execution Environments
https://issues.redhat.com/browse/AAP-31913

Update Creating and Using Execution Environments

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/titles/aap-containerized-install/master.adoc

Updates:
- Add appendix to Containerized installation doc
- Correct typos, use of attributes
- Update intro description to Inventory file variables section
- Update ordering of inventory file variable sections

Update inventory file appendix for RPM and Containerized installers

---

downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc

[AAP-31998](https://issues.redhat.com/browse/AAP-31998) pre-release checklist for hardening and compliance guide
- ref-sensitive-variables-install-inventory.adoc

AAP-31998 updated version number

---

downstream/modules/builder/proc-installing-builder.adoc

[AAP-31992](https://issues.redhat.com/browse/AAP-31992) pre-release checklist for creating and using execution environments
- proc-installing-builder.adoc

AAP-31992 updated aap version number

---

downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc

2.5 backport of [PR 2097](https://github.com/ansible/aap-docs/pull/2097)
[AAP-31998](https://issues.redhat.com/browse/AAP-31998) pre-release checklist for hardening and compliance guide
ref-sensitive-variables-install-inventory.adoc

AAP-31998 updated version number (#2097)

---

downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/titles/topologies/master.adoc

- Add link to test-topologies repo (will be made public at GA)
- Correct typo in OCP-A-ENV-A topology

Add link to ansible/test-topologies repo

---

downstream/assemblies/platform/assembly-platform-install-overview.adoc
downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/platform/con-install-scenario-recommendations.adoc
downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/platform/ref-eda-system-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc

[AAP-30807](https://issues.redhat.com/browse/AAP-30807) is tracking the publication process of [RPM Installation 2.5 Draft](https://docs.google.com/document/d/1fIrlSrj8bSSWBVptXWmm0ZFixhZ4mM5pW2CQx_3Oh7A/edit#heading=h.s5lh1pa44x46).
This PR has misc edits that include last minute revisions made by SMEs and stakeholders.

AAP-30807 Sanity Check: Misc edits from RPM draft

---

downstream/assemblies/platform/assembly-platform-install-overview.adoc
downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/platform/con-install-scenario-recommendations.adoc
downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/platform/ref-eda-system-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc

[AAP-30807](https://issues.redhat.com/browse/AAP-30807) is tracking the publication process of [RPM Installation 2.5 Draft](https://docs.google.com/document/d/1fIrlSrj8bSSWBVptXWmm0ZFixhZ4mM5pW2CQx_3Oh7A/edit#heading=h.s5lh1pa44x46).
This PR has misc edits that include last minute revisions made by SMEs and stakeholders.

[2.5] AAP-30807-Sanity-Check: Misc edits from RPM draft (#2113)

---

lightspeed/modules/proc_create-connection-secrets.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-31798. 
Changes made:
- Removed erroneous text that remained in the files after resolving merge conflicts.

AAP-31798: Resolved the merge conflict text error

---

downstream/assemblies/eda/assembly-eda-decision-environments.adoc
downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc

Update the Decision environments chapter in the Automation decisions guide
https://issues.redhat.com/browse/AAP-31876

Edits to DE section of Automation decisions guide

---

downstream/assemblies/eda/assembly-eda-decision-environments.adoc
downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc

Update the Decision environments chapter in the Automation decisions guide
https://issues.redhat.com/browse/AAP-31876

Edits to DE section of Automation decisions guide (#2122)

---

downstream/modules/platform/proc-RPM-install-eda-controller.adoc

Update the inventory file used in Using Event-Driven Ansible 2.5 with Ansible Automation Platform 2.4 so it matches the inventory file used in the associated topology i.e. RPM-B-ENV-B.
https://docs.google.com/document/d/1aGQ1vrVADmsI79kwnyeVq3moQvEvXn6Hal8dc3v9X80/edit#heading=h.3r4rp122sgzc

2.4 Update inventory file for mixed RPM deployment

---

downstream/modules/platform/proc-controller-add-users-job-templates.adoc

Pre-release updates to Using automation execution
https://issues.redhat.com/browse/AAP-31370

Adding correct link to Users section

---

downstream/modules/platform/proc-controller-add-users-job-templates.adoc

Pre-release updates to Using automation execution
https://issues.redhat.com/browse/AAP-31370

Adding correct link to Users section (#2131)

---

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
downstream/assemblies/hub/assembly-validated-content.adoc
downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc
downstream/modules/hub/proc-configure-content-signing-on-pah.adoc
downstream/modules/hub/proc-configure-proxy-remote.adoc
downstream/modules/hub/proc-set-community-remote.adoc
downstream/modules/hub/proc-set-rhcertified-remote.adoc
downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc

See [AAP-20548](https://issues.redhat.com/browse/AAP-20548) for more info.

AAP-20548: Managing automation content doc updates

---

downstream/assemblies/devtools/assembly-rhdh-install-ocp-operator.adoc
downstream/attributes/attributes.adoc
downstream/modules/devtools/con-rhdh-recommended-preconfig.adoc
downstream/modules/devtools/proc-rhdh-backup-operator-configmap.adoc
downstream/modules/devtools/proc-rhdh-configure-aap-details.adoc
downstream/modules/devtools/proc-rhdh-create-custom-configmap-operator-install.adoc
downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
downstream/modules/devtools/proc-rhdh-operator-add-custom-configmap-cr.adoc
downstream/modules/devtools/proc-rhdh-operator-install-add-plugins-app-config.adoc
downstream/titles/aap-plugin-rhdh-install/master.adoc

AAP-32141 Add Installing on Operator chapter to RHDH install guide
Affects titles/aap-plugin-rhdh-install/

AAP-32141 Add Installing on Operator chapter to RHDH install guide

---

downstream/modules/builder/ref-scenario-using-authentication-ee.adoc

Correction
Correct Creating and Using Execution Environments
https://issues.redhat.com/browse/AAP-31913

Correct link in execution enviroments

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/rpm-24-74.adoc
downstream/titles/release-notes/topics/rpm-version-table.adoc

AAP 2.4-7.4 Release notes
https://issues.redhat.com/browse/AAP-31819

2.4 Add RPM 2.4-7.4 async release notes

---

downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc

This PR changes xrefs to links in the Managing automation content guide.

2.5 Fixed broken formatting preventing successful build (#2153)

---

downstream/modules/builder/ref-scenario-using-authentication-ee.adoc

* Correct link in execution enviroments
https://issues.redhat.com/browse/AAP-31913

Correct link in execution enviroments (#2130)

---

downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc

Replaced with LOG_AGGREGATOR_ACTION_QUEUE_SIZE
[Doc Bug] : API setting LOG_AGGREGATOR_MAX_DISK_USAGE_GB misses ACTION.
https://issues.redhat.com/browse/AAP-32085

Replace LOG_AGGREGATOR_MAX_DISK_USAGE_GB (#2125)

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc

Update links in the Tested deployment models doc to ensure they work correctly.

Update links in topology guide

---

downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/proc-add-operator-execution-nodes.adoc
downstream/modules/platform/proc-configuring-controller-ldap-security.adoc

Just fixing one link that reference the old title name, and tidying up two others with a more accurate description

2.5 links fix

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc

Update links in the Tested deployment models doc to ensure they work correctly.

2.5 Update links in topology guide (#2161)

---

downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/proc-add-operator-execution-nodes.adoc
downstream/modules/platform/proc-configuring-controller-ldap-security.adoc

Just fixing one link that reference the old title name, and tidying up two others with a more accurate description

2.5 links fix (#2160)

---

downstream/modules/devtools/proc-devtools-create-aap-job.adoc
downstream/modules/devtools/proc-devtools-install-rpm.adoc

AAP-32187 Updating 2.5 Devtools links
Affects titles/develop-automation-content/

AAP-32187 Updating 2.5 Devtools links

---

downstream/modules/devtools/proc-devtools-create-aap-job.adoc
downstream/modules/devtools/proc-devtools-install-rpm.adoc

AAP-32187 Updating 2.5 Devtools links
Affects titles/develop-automation-content/

2.5 AAP-32187 Updating 2.5 Devtools links (#2164)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

Updating links in `titles/aap-containerized-install`

Update links in containerized install guide

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

Updating links in titles/aap-containerized-install

2.5 Update links in containerized install guide (#2166)

---

downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-backup-recovery.adoc
downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-controller.adoc
downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-aap-packages.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-invalid-credentials.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-pending.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-permissions.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-resolve-module.adoc
downstream/titles/troubleshooting-aap/master.adoc

Update links in `titles/troubleshooting-aap`

2.5 Update links in troubleshooting guide (#2170)

---

downstream/modules/platform/con-RPM-install-eda-post-steps.adoc

Update link in `titles/eda-controller/eda-controller-install`

2.4 Update link in eda 2.5 controller 2.4 doc

---

downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
downstream/titles/release-notes/topics/aap-25-known-issues.adoc
downstream/titles/release-notes/topics/aap-25.adoc
downstream/titles/release-notes/topics/platform-intro.adoc

Backport PR [#2177](https://github.com/ansible/aap-docs/pull/2177) from main to AAP v2.5.

Backport pull request #2177 from main to 2.5

---

downstream/modules/hub/proc-basic-repo-sync.adoc

Fixes an xref that's breaking the doc build.

Managing automation content guide: broken xref fix

---

downstream/assemblies/platform/assembly-inventory-introduction.adoc

[AAP-31800](https://issues.redhat.com/browse/AAP-31800)
Updated self-referencing link in _Planning your installation_
- assembly-inventory-introduction.adoc

AAP-31800 updated self-referencing link

---

lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
lightspeed/modules/con_lightspeed-key-features.adoc
lightspeed/modules/proc_create-connection-secrets.adoc
lightspeed/modules/proc_create-lightspeed-instance.adoc
lightspeed/modules/proc_update-redirect-uri.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-29570.
Changes made:
- Updated Lightspeed on-premise docs for AAP 2.5 support

AAP-26942: Updated Lightspeed on-premise docs for AAP 2.5 support

---

downstream/assemblies/eda/assembly-eda-projects.adoc
downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

- Updated the cross-reference list of topics in the Automation decisions guide
- Updated the original resources list

AAP-32212 Updates to the overview chapter of Automation Decisions guide

---

downstream/assemblies/eda/assembly-eda-projects.adoc
downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

- Updated the cross-reference list of topics in the Automation decisions guide
- Updated the original resources list

Backport-2.5-2187 Updates to the overview chapter of Automation Decisions guide (#2187)

---

downstream/titles/aap-plugin-rhdh-using/master.adoc

RHDH remove text preview notice

RHDH remove text preview notice

---

downstream/titles/eda-controller/eda-controller-install/docinfo.xml

Update subtitle for Using EDA 2.5 with AAP 2.4
https://issues.redhat.com/browse/AAP-32241
Affects `titles/eda-controller-install`

Updating the subtitle for Using EDA 2.5 with AAP 2.4

---

downstream/assemblies/devtools/assembly-devtools-create-roles-collection.adoc
downstream/assemblies/devtools/assembly-devtools-develop-collections.adoc
downstream/modules/devtools/con-devtools-plan-roles-collection.adoc
downstream/modules/devtools/con-devtools-roles-collection-prerequisites.adoc
downstream/modules/devtools/proc-devtools-create-new-role-in-collection.adoc
downstream/modules/devtools/proc-devtools-docs-roles-collection.adoc
downstream/modules/devtools/proc-devtools-migrate-existing-roles-collection.adoc
downstream/modules/devtools/proc-devtools-molecule-test-roles-collection.adoc
downstream/modules/devtools/proc-devtools-publish-roles-collection-pah.adoc
downstream/modules/devtools/proc-devtools-run-roles-collection.adoc
downstream/modules/devtools/proc-devtools-scaffold-roles-collection.adoc
downstream/modules/devtools/proc-devtools-use-roles-collections-aap.adoc
downstream/titles/develop-automation-content/master.adoc

AAP-30912  Add roles collections chapter to the Devtools guide.

AAP-30912 Devtools - Add roles collections chapter (#2148)

---

downstream/modules/platform/proc-define-mesh-node-types.adoc
downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc
downstream/modules/platform/ref-operator-mesh-prerequisites.adoc

Fix links in operator-mesh guide

---

downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
downstream/modules/platform/con-install-mesh.adoc
downstream/modules/platform/proc-editing-inventory-file.adoc

Fixed links in automation-mesh guide

---

downstream/assemblies/platform/assembly-ag-controller-clustering.adoc
downstream/assemblies/platform/assembly-ag-controller-troubleshooting.adoc
downstream/assemblies/platform/assembly-inventory-file-importing.adoc
downstream/modules/platform/proc-controller-cluster-deprovision-instances.adoc
downstream/modules/platform/proc-controller-configure-jobs.adoc
downstream/modules/platform/proc-controller-configure-system.adoc
downstream/modules/platform/proc-controller-management-notifications.adoc
downstream/modules/platform/proc-controller-set-up-prometheus.adoc
downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
downstream/modules/platform/ref-controller-cluster-install.adoc
downstream/modules/platform/ref-controller-connect-to-host.adoc
downstream/modules/platform/ref-controller-performance-troubleshooting.adoc

Correct links in Controller Admin

---

downstream/modules/platform/proc-define-mesh-node-types.adoc
downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc
downstream/modules/platform/ref-operator-mesh-prerequisites.adoc

Fix links in operator-mesh guide (#2189)

---

downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
downstream/modules/platform/con-install-mesh.adoc
downstream/modules/platform/proc-editing-inventory-file.adoc

Fixed links in automation-mesh guide (#2190)

---

downstream/assemblies/platform/assembly-planning-installation.adoc
downstream/assemblies/platform/assembly-system-requirements.adoc
downstream/modules/platform/con-about-eda-controller.adoc
downstream/modules/platform/con-editing-inventory-files.adoc
downstream/modules/platform/ref-containerized-system-requirements.adoc

[AAP-32244](https://issues.redhat.com/browse/AAP-32244) 1
Files modified: 
- con-editing-inventory-files.adoc
- ref-containerized-system-requirements.adoc
- assembly-system-requirements.adoc
- con-about-eda-controller.adoc
- assembly-planning-installation.adoc

AAP-32244-planning updated links 1

---

downstream/assemblies/platform/assembly-planning-installation.adoc
downstream/assemblies/platform/assembly-system-requirements.adoc
downstream/modules/platform/con-about-eda-controller.adoc
downstream/modules/platform/con-editing-inventory-files.adoc
downstream/modules/platform/ref-containerized-system-requirements.adoc

2.5 backport of [2207
](https://github.com/ansible/aap-docs/pull/2207)
[AAP-32244](https://issues.redhat.com/browse/AAP-32244) 1
con-editing-inventory-files.adoc
ref-containerized-system-requirements.adoc
assembly-system-requirements.adoc
con-about-eda-controller.adoc
assembly-planning-installation.adoc

AAP-32244-planning updated links 1 (#2207)

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

[AAP-32244](https://issues.redhat.com/browse/AAP-32244) 2
- assembly-network-ports-protocols.adoc

AAP-32244 updated links

---

downstream/modules/platform/proc-define-mesh-node-types.adoc
downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc
downstream/modules/platform/ref-operator-mesh-prerequisites.adoc

* Fix links in operator-mesh guide
More links
* Fix links in operator-mesh guide
Correction

Aap 32226 2nd (#2200)

---

downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
downstream/assemblies/platform/assembly-ag-controller-troubleshooting.adoc
downstream/modules/platform/con-controller-cleanup-expired-sessions.adoc
downstream/modules/platform/ref-controller-cleanup-expired-tokens.adoc
downstream/modules/platform/ref-controller-old-job-history.adoc
downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
downstream/modules/platform/ref-controller-run-a-playbook.adoc
downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc

* Correct links in Controller Admin
More links
* Correct links in Controller Admin
More corrections
* Correct links in Controller Admin
More links

Correct links in Controller Admin (#2197)

---

downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc

Should be a link
Fix reference in Controller Admin Guide
https://issues.redhat.com/browse/AAP-32256

Fix xref in Controller Admin

---

downstream/modules/platform/con-install-mesh.adoc

Fix links in automation mesh guide

---

downstream/assemblies/platform/assembly-controller-best-practices.adoc
downstream/assemblies/platform/assembly-controller-instances.adoc
downstream/assemblies/platform/assembly-controller-topology-viewer.adoc
downstream/modules/platform/con-controller-administration.adoc
downstream/modules/platform/con-controller-capacity-determination.adoc
downstream/modules/platform/con-controller-configure-hostname-notifications.adoc
downstream/modules/platform/con-controller-settings.adoc
downstream/modules/platform/proc-controller-access-topology-viewer.adoc
downstream/modules/platform/proc-controller-adding-a-project.adoc
downstream/modules/platform/proc-controller-inv-source-vm-vcenter.adoc
downstream/modules/platform/proc-controller-pass-extra-variables-provisioning-callbacks.adoc
downstream/modules/platform/proc-controller-set-up-gitlab-webhook.adoc
downstream/modules/platform/proc-controller-sourced-from-project.adoc
downstream/modules/platform/proc-projects-using-collections-with-hub.adoc
downstream/modules/platform/ref-controller-credential-terraform.adoc
downstream/modules/platform/ref-controller-export-old-scripts.adoc
downstream/modules/platform/ref-controller-extra-variables.adoc
downstream/modules/platform/ref-controller-install-builder.adoc
downstream/modules/platform/ref-controller-instance-group-policies.adoc

Pre-release updates to Using automation execution
https://issues.redhat.com/browse/AAP-31370

Fixing broken links in using (#2209)

---

downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc

Should be a link
Fix reference in Controller Admin Guide
https://issues.redhat.com/browse/AAP-32256

Fix xref in Controller Admin (#2213)

---

downstream/assemblies/platform/assembly-ag-controller-clustering.adoc
downstream/assemblies/platform/assembly-ag-controller-troubleshooting.adoc
downstream/assemblies/platform/assembly-inventory-file-importing.adoc
downstream/modules/platform/proc-controller-cluster-deprovision-instances.adoc
downstream/modules/platform/proc-controller-configure-jobs.adoc
downstream/modules/platform/proc-controller-configure-system.adoc
downstream/modules/platform/proc-controller-management-notifications.adoc
downstream/modules/platform/proc-controller-set-up-prometheus.adoc
downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
downstream/modules/platform/ref-controller-cluster-install.adoc
downstream/modules/platform/ref-controller-connect-to-host.adoc
downstream/modules/platform/ref-controller-performance-troubleshooting.adoc

Correct links in Controller Admin (#2194)

---

downstream/assemblies/platform/assembly-controller-credentials.adoc
downstream/assemblies/platform/assembly-ug-controller-instance-groups.adoc
downstream/modules/platform/con-controller-deprovision-instance-groups.adoc
downstream/modules/platform/proc-controller-create-job-template.adoc
downstream/modules/platform/proc-controller-verify-container-group.adoc

Pre-release updates to Using automation execution
https://issues.redhat.com/browse/AAP-31370

Fixing final broken links in ug

---

downstream/modules/playbooks/ref-create-variables.adoc

Fixed  links
Fix links in Getting Started with Playbooks
https://issues.redhat.com/browse/AAP-32259

Fix links in Getting Started with Playbooks

---

downstream/assemblies/platform/assembly-controller-credentials.adoc
downstream/assemblies/platform/assembly-ug-controller-instance-groups.adoc
downstream/modules/platform/con-controller-deprovision-instance-groups.adoc
downstream/modules/platform/proc-controller-create-job-template.adoc
downstream/modules/platform/proc-controller-verify-container-group.adoc

2.5 backport of [PR 2211](https://github.com/ansible/aap-docs/pull/2211)
[AAP-32244](https://issues.redhat.com/browse/AAP-32244) 2
- assembly-network-ports-protocols.adoc

Fixing final broken links in ug (#2218)

---

downstream/modules/playbooks/ref-create-variables.adoc

Fixed  links
Fix links in Getting Started with Playbooks
https://issues.redhat.com/browse/AAP-32259

Fix links in Getting Started with Playbooks (#2217)

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
downstream/assemblies/eda/assembly-simplified-event-routing.adoc
downstream/modules/eda/proc-eda-set-up-rhaap-credential.adoc
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

Found minor errors (typos, link titles, etc.) in the following modules:
- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
- downstream/assemblies/eda/assembly-simplified-event-routing.adoc
- downstream/modules/eda/proc-eda-set-up-rhaap-credential.adoc
- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

AAP-32260 Minor corrections found when scanning the newly published Using automation decisions guide.

---

downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc

Please correct the recommendation to install "git-core" instead of "git". Thanks.
Suboptimal troubleshooting hint
https://issues.redhat.com/browse/AAP-32261

Update git to git-core in containerized install

---

downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc

Please correct the recommendation to install "git-core" instead of "git". Thanks.
Suboptimal troubleshooting hint
https://issues.redhat.com/browse/AAP-32261

2.5 Update git to git-core in containerized install (#2238)

---

downstream/modules/devtools/proc-rhdh-create.adoc

AAP-30989
Add requirements for collection namespaces

AAP-30989 RHDH Add collection naming convention requirements

---

downstream/modules/analytics/con-jobs-explorer.adoc
downstream/modules/analytics/proc-ignoring-nested-workflows-jobs.adoc

2.5 backport of [PR 2248](https://github.com/ansible/aap-docs/pull/2248)
AAP-32244
- analytics/con-jobs-explorer.adoc
- analytics/proc-ignoring-nested-workflows-jobs.adoc

AAP-32244 fixed links in using AA (#2248)

---

downstream/assemblies/hub/assembly-delete-container.adoc
downstream/modules/hub/con-approval-pipeline.adoc
downstream/modules/hub/con-container-registry.adoc
downstream/modules/hub/proc-add-container-readme.adoc
downstream/modules/hub/proc-approve-collection.adoc
downstream/modules/hub/proc-create-credential.adoc
downstream/modules/hub/proc-export-collection.adoc
downstream/modules/hub/proc-push-container.adoc
downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
downstream/modules/hub/proc-reject-collections.adoc
downstream/modules/hub/proc-revert-repository-version.adoc
downstream/modules/hub/proc-sync-image.adoc
downstream/modules/hub/proc-tag-image.adoc

This PR ports the changes from [PR 2233](https://github.com/ansible/aap-docs/pull/2233) to the 2.5 branch.

backport to 2.5: minor UI updates (#2233)

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

Corrected link to "Using EDA 2.5 with AAP 2.4" guide in Using automation decisions, Chapter 1.

AAP-32260 Correct broken links in Using automation decisions

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

Corrected link to "Using EDA 2.5 with AAP 2.4" guide in Using automation decisions, Chapter 1.

Backport-2.5-2252 (AAP-32260) Correct broken links in Using automation decisions

---

downstream/assemblies/devtools/assembly-devtools-create-roles-collection.adoc
downstream/assemblies/devtools/assembly-devtools-develop-collections.adoc
downstream/modules/devtools/con-devtools-plan-roles-collection.adoc
downstream/modules/devtools/con-devtools-roles-collection-prerequisites.adoc
downstream/modules/devtools/proc-devtools-create-new-role-in-collection.adoc
downstream/modules/devtools/proc-devtools-docs-roles-collection.adoc
downstream/modules/devtools/proc-devtools-migrate-existing-roles-collection.adoc
downstream/modules/devtools/proc-devtools-molecule-test-roles-collection.adoc
downstream/modules/devtools/proc-devtools-publish-roles-collection-pah.adoc
downstream/modules/devtools/proc-devtools-run-roles-collection.adoc
downstream/modules/devtools/proc-devtools-scaffold-roles-collection.adoc
downstream/modules/devtools/proc-devtools-use-roles-collections-aap.adoc
downstream/titles/develop-automation-content/master.adoc

AAP-30912  Add roles collections chapter to the Devtools guide.

2.4 AAP-30912 Devtools - Add roles collections chapter (#2148)

---

downstream/assemblies/platform/assembly-disconnected-installation.adoc
downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/platform/con-aap-installation-prereqs.adoc
downstream/modules/platform/proc-completing-post-installation-tasks.adoc
downstream/modules/platform/ref-automation-hub-requirements.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/platform/ref-eda-system-requirements.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-postgresql-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc

Links
Fix broken links in Installation Guide
https://issues.redhat.com/browse/AAP-32433

Fixed  broken links in Installation Guide

---

downstream/assemblies/platform/assembly-controller-instances.adoc
downstream/modules/platform/con-controller-notification-workflow.adoc
downstream/modules/platform/proc-controller-add-users-job-templates.adoc
downstream/modules/platform/proc-controller-associate-instances-to-instance-group.adoc
downstream/modules/platform/proc-controller-create-container-group.adoc
downstream/modules/platform/proc-controller-create-credential-type.adoc
downstream/modules/platform/proc-controller-create-credential.adoc
downstream/modules/platform/proc-controller-create-custom-notifications.adoc
downstream/modules/platform/proc-controller-create-host.adoc
downstream/modules/platform/proc-controller-create-insights-credential.adoc
downstream/modules/platform/proc-controller-create-insights-project.adoc
downstream/modules/platform/proc-controller-create-instance-group.adoc
downstream/modules/platform/proc-controller-create-notification-template.adoc
downstream/modules/platform/proc-controller-customize-pod-spec.adoc
downstream/modules/platform/proc-controller-inv-source-aap.adoc
downstream/modules/platform/proc-controller-inv-source-rh-virt.adoc
downstream/modules/platform/proc-controller-inv-source-terraform.adoc
downstream/modules/platform/proc-controller-remediate-insights-inventory.adoc
downstream/modules/platform/proc-controller-set-up-github-webhook.adoc
downstream/modules/platform/proc-controller-verify-container-group.adoc
downstream/modules/platform/proc-controller-view-host.adoc
downstream/modules/platform/ref-controller-content-sourcing.adoc
downstream/modules/platform/ref-controller-credential-machine.adoc
downstream/modules/platform/ref-controller-credential-network.adoc
downstream/modules/platform/ref-controller-credential-openShift.adoc
downstream/modules/platform/ref-controller-credential-openStack.adoc
downstream/modules/platform/ref-controller-credential-terraform.adoc
downstream/modules/platform/ref-controller-credential-vault.adoc
downstream/modules/platform/ref-removing-instances.adoc

Updates to UI in using automation execution
https://issues.redhat.com/browse/AAP-32375

Edits to UI in using automation execution

---

downstream/assemblies/platform/assembly-controller-instances.adoc
downstream/modules/platform/con-controller-notification-workflow.adoc
downstream/modules/platform/proc-controller-add-users-job-templates.adoc
downstream/modules/platform/proc-controller-associate-instances-to-instance-group.adoc
downstream/modules/platform/proc-controller-create-container-group.adoc
downstream/modules/platform/proc-controller-create-credential-type.adoc
downstream/modules/platform/proc-controller-create-credential.adoc
downstream/modules/platform/proc-controller-create-custom-notifications.adoc
downstream/modules/platform/proc-controller-create-host.adoc
downstream/modules/platform/proc-controller-create-insights-credential.adoc
downstream/modules/platform/proc-controller-create-insights-project.adoc
downstream/modules/platform/proc-controller-create-instance-group.adoc
downstream/modules/platform/proc-controller-create-notification-template.adoc
downstream/modules/platform/proc-controller-customize-pod-spec.adoc
downstream/modules/platform/proc-controller-inv-source-aap.adoc
downstream/modules/platform/proc-controller-inv-source-rh-virt.adoc
downstream/modules/platform/proc-controller-inv-source-terraform.adoc
downstream/modules/platform/proc-controller-remediate-insights-inventory.adoc
downstream/modules/platform/proc-controller-set-up-github-webhook.adoc
downstream/modules/platform/proc-controller-verify-container-group.adoc
downstream/modules/platform/proc-controller-view-host.adoc
downstream/modules/platform/ref-controller-content-sourcing.adoc
downstream/modules/platform/ref-controller-credential-machine.adoc
downstream/modules/platform/ref-controller-credential-network.adoc
downstream/modules/platform/ref-controller-credential-openShift.adoc
downstream/modules/platform/ref-controller-credential-openStack.adoc
downstream/modules/platform/ref-controller-credential-terraform.adoc
downstream/modules/platform/ref-controller-credential-vault.adoc
downstream/modules/platform/ref-removing-instances.adoc

Updates to UI in using automation execution
https://issues.redhat.com/browse/AAP-32375

Edits to UI in using automation execution (#2251)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/installer-24-74.adoc
downstream/titles/release-notes/topics/installer-version-table.adoc

Add bundle 2.4-7.4 to release notes
AAP 2.4-7.4 Release notes
https://issues.redhat.com/browse/AAP-31819

2.4 Add bundle 2.4-7.4 to release notes

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
downstream/modules/platform/ref-OCP-system-requirements.adoc
downstream/modules/platform/ref-containerized-system-requirements.adoc

AAP-32244 updated incorrect links
- topologies/assembly-overview-tested-deployment-models.adoc
- ref-OCP-system-requirements.adoc
- ref-containerized-system-requirements.adoc

AAP-32244 fixed incorrect links

---

downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
downstream/titles/release-notes/topics/aap-25-known-issues.adoc

This PR backports PR [#2258](https://github.com/ansible/aap-docs/pull/2258 from main to AAP v2.5.

Backport pull request #2258 from main to 2.5

---

downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

Update the ansible-core version and the PostgreSQL versions in Tested deployment models
Incorrect Ansible Core in AAP 2.5 documentation
https://issues.redhat.com/browse/AAP-32814

2.5 Update ansible-core version and PostgreSQL version in topologies (#2282)

---

downstream/titles/aap-operator-installation/docinfo.xml
downstream/titles/aap-operator-installation/master.adoc

The 's' in the OpenShift is incorrecly lower case. Fixing in Master.adoc and docinfo.xml

fixing OCP title

---

downstream/assemblies/builder/assembly-using-builder.adoc
downstream/assemblies/builder/platform
downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
downstream/titles/builder/master.adoc
downstream/titles/builder/platform

Move disconnected EE content to builder guide
https://issues.redhat.com/browse/AAP-24986

Add disconnected execution environments to doc

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/aap-25-2-patch-release-7-oct-2024.adoc

This is a patch release that includes several fixes and enhancements.

Patch release notes for AAP 2.5-2-October-7, 2024

---

downstream/assemblies/platform/assembly-update-container.adoc
downstream/assemblies/platform/assembly-update-ocp.adoc
downstream/assemblies/platform/assembly-update-rpm.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-backup-aap-rpm.adoc
downstream/modules/platform/proc-installing-with-internet.adoc
downstream/modules/platform/proc-inventory-file-setup-rpm.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc
downstream/modules/platform/proc-update-aap-container.adoc
downstream/modules/platform/proc-update-aap-on-ocp.adoc
downstream/titles/updating-aap/master.adoc

This PR backports the changes from #2290 to the 2.5 branch and includes the following:
* dd-2286 - Fix conversion issues with Update guide
* dd-2286 - Fix procedure numbering in container procedure
* dd-2286 - peer review fixes and removing extraneous files
* added peer review suggestion

dd-2286 - fix conversion issues in the Updating guide (#2290)

---

downstream/titles/updating-aap/master.adoc

This PR adds the :experimental: tag to the master.adoc to fix button and other formatting.

dd-updguide - Add experimental tagk to fix formatting

---

downstream/assemblies/platform/assembly-update-container.adoc
downstream/assemblies/platform/assembly-update-ocp.adoc
downstream/assemblies/platform/assembly-update-rpm.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-backup-aap-rpm.adoc
downstream/modules/platform/proc-installing-with-internet.adoc
downstream/modules/platform/proc-inventory-file-setup-rpm.adoc
downstream/titles/updating-aap/master.adoc

Performing a sanity check of `titles/updating-aap`.
Correcting typos, removing unnecessary comments etc.
Document 2.5 to 2.5.x upgrade steps
https://issues.redhat.com/browse/AAP-31734

Updates to updating-aap

---

downstream/assemblies/platform/assembly-update-container.adoc
downstream/assemblies/platform/assembly-update-ocp.adoc
downstream/assemblies/platform/assembly-update-rpm.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-backup-aap-rpm.adoc
downstream/modules/platform/proc-installing-with-internet.adoc
downstream/modules/platform/proc-inventory-file-setup-rpm.adoc
downstream/titles/updating-aap/master.adoc

Performing a sanity check of titles/updating-aap.
Correcting typos, removing unncessary comments etc.
Document 2.5 to 2.5.x upgrade steps
https://issues.redhat.com/browse/AAP-31734

2.5 Updates to updating-aap (#2297)

---

downstream/modules/platform/con-controller-api-basic-auth.adoc
downstream/modules/platform/con-controller-api-oauth2-token.adoc
downstream/modules/platform/con-controller-api-sso-auth.adoc
downstream/modules/platform/con-controller-api-tools.adoc
downstream/modules/platform/proc-controller-api-session-auth.adoc

Update Automation execution API overview
https://issues.redhat.com/browse/AAP-32935
Affects `title/controller-api-overview`

Updating UI and links in API overview

---

downstream/modules/platform/con-controller-api-basic-auth.adoc
downstream/modules/platform/con-controller-api-oauth2-token.adoc
downstream/modules/platform/con-controller-api-sso-auth.adoc
downstream/modules/platform/con-controller-api-tools.adoc
downstream/modules/platform/proc-controller-api-session-auth.adoc

* Updating UI and links in API overview
Update Automation execution API overview
https://issues.redhat.com/browse/AAP-32935
Affects `title/controller-api-overview`
* Final edits to links in API overview
* API overview adding links

Updating UI and links in API overview (#2295)

---

downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
downstream/modules/platform/con-ocp-supported-install.adoc

Updating xref format from <<title>> to xref:ID+context[title]

fixing xref

---

downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
downstream/modules/platform/con-ocp-supported-install.adoc

fixing xref (#2303)

---

downstream/titles/release-notes/topics/aap-25-2-patch-release-7-oct-2024.adoc

RPM
Container (namespace)
Container (cluster)
Bundle Installer

This commit fixes links for the errata advsories in patch release 2.5-2.

---

downstream/assemblies/platform/assembly-operator-debugging.adoc
downstream/modules/platform/con-operator-ansible-verbosity.adoc

[AAP-32371](https://issues.redhat.com/browse/AAP-32371) 
Adding a new assembly for degubbing and adding a module on Ansible verbosity to it.

Adding debugging chapter

---

downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc

[AAP-33019](https://issues.redhat.com/browse/AAP-33019)
[Draft](https://docs.google.com/document/d/1LABc8WTToJJXaBvWUfV-VaYdBJkOPWQRNsEQiY8-fdc/edit) - SME approved
Adding new section on how to upgrade receptors

Adding updating receptors section to op-mesh guide

---

downstream/titles/release-notes/topics/aap-25-2-patch-release-7-oct-2024.adoc

Fixes an issue raised by Satoe.

Removed extraneous internal numeration from the errata.

---

downstream/modules/eda/proc-eda-set-up-new-project.adoc

Added the **Verify SSL** checkbox to the 2.4 EDA Controller user guide (using content from 2.5 Using automation decisions guide as the example).

AAP-16082 Added Verify SSL checkbox option to the setting projects topic in the 2.4 EDA controller user guide

---

downstream/assemblies/platform/assembly-aap-upgrades.adoc
downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/con-aap-upgrades.adoc
downstream/modules/platform/con-backup-aap.adoc
downstream/modules/platform/ini/clustered-nodes.ini
downstream/modules/platform/proc-account-linking.adoc
downstream/modules/platform/proc-choosing-obtaining-installer.adoc
downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

See [AAP-30808](https://issues.redhat.com/browse/AAP-30808) for more info.

AAP-30808: Upgrade/migration guide asciidoc conversion 

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/proc-using-postinstall.adoc

Update postinstall info in Containerized installation.
- Add info for loading a license file
- Update postinstall section to denote required inventory file variables
- Some additional spelling/grammar/attribute clean up
Containerized installation - update postinstall information
https://issues.redhat.com/browse/AAP-32710

Containerized installation - update postinstall information

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/proc-using-postinstall.adoc

Update postinstall info in Containerized installation.
- Add info for loading a license file
- Update postinstall section to denote required inventory file variables
- Some additional spelling/grammar/attribute clean up
Containerized installation - update postinstall information
https://issues.redhat.com/browse/AAP-32710

2.5 Containerized installation - update postinstall information (#2325)

---

downstream/assemblies/platform/assembly-appendix-operator-crs.adoc
downstream/modules/platform/ref-operator-crs.adoc

[AAP-33160](https://issues.redhat.com/browse/AAP-33160)
Updating the Appendix section of the [Installing on OCP doc](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/installing_on_openshift_container_platform/index) for 2.5 Event 2.

Adding appendix as part of event 2

---

downstream/modules/hub/proc-create-namespace.adoc
downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc

This PR fixes the formatting of buttons in 2 procedures.

Fix incorrect formatting of buttons

---

downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc

[AAP-29834](https://issues.redhat.com/browse/AAP-29834)
- Updating receptor section of the automation mesh guide

Updating receptor section

---

stories/topics/con-saas-intro.adoc
stories/topics/con-saas-monitoring.adoc
stories/topics/con-saas-updates-and-maintenance.adoc
titles/saas-aws/docinfo.xml
titles/saas-aws/master.adoc

[AAP-29834](https://issues.redhat.com/browse/AAP-29834)
- Adding link to receptions section 
- Added a note around the retention policy of jobs
- Minor tweaks to content and title. (Page not created in pantheon ye, so no need to update there)

linking to auto mesh receptors section

---

downstream/assemblies/platform/assembly-inventory-introduction.adoc

[Doc]Example inventory files in AAP 2.5 docs don't include necessary parameters.
https://issues.redhat.com/browse/AAP-32701

Add gateway variables to example inventory file

---

downstream/assemblies/platform/assembly-inventory-introduction.adoc

[Doc]Example inventory files in AAP 2.5 docs don't include necessary parameters.
https://issues.redhat.com/browse/AAP-32701

Add gateway variables to example inventory file (#2339)

---

downstream/assemblies/platform/assembly-metrics-utility.adoc
downstream/modules/platform/proc-configuring-the-metrics-utility.adoc

Fis issue in Controller Admin Guide
https://issues.redhat.com/browse/AAP-33452

Removed context marker to make build work

---

downstream/assemblies/platform/assembly-metrics-utility.adoc
downstream/modules/platform/proc-configuring-the-metrics-utility.adoc

Fis issue in Controller Admin Guide
https://issues.redhat.com/browse/AAP-33452

Removed context marker to make build work (#2344)

---

downstream/modules/platform/ref-system-requirements.adoc

[Doc]AAP 2.5 system requirements should include RHEL 8.8
https://issues.redhat.com/browse/AAP-32708

Added RHEL 8.8 to 2.5 system requirements

---

downstream/modules/platform/ref-operator-ocp-version.adoc

[AAP-33381](https://issues.redhat.com/browse/AAP-33381)
Updating the OCP version that is compatible with AAP OP 2.5

Updating OCP version

---

downstream/modules/platform/proc-install-ha-hub-selinux.adoc

Add explict statement stating 'NFS is external server'
https://issues.redhat.com/browse/AAP-32889

Add note about external server (#2352)

---

stories/assembly-saas-post-install-config.adoc

[AAP-33171](https://issues.redhat.com/browse/AAP-33171)
[AAP-33170](https://issues.redhat.com/browse/AAP-33170)
Adding a warning admontion around settings that must not be edited.

Adding warning admonition

---

downstream/modules/hub/proc-create-namespace.adoc
downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc

This PR backports the changes from #2335 to the 2.5 branch.

[Backport] - Fix incorrect formatting of buttons (#2335)

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc

[AAP-33302](https://issues.redhat.com/browse/AAP-33302)
- Fixing the AnsibleAutomationPlatform YAML
- Some other minor tweaks and typos

Updates required from AAP-33302

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc

* Updates required from AAP-33475
* yaml code indent fix

Updates required from AAP-33302 (#2361)

---

downstream/modules/platform/con-gw-clustered-redis.adoc

[AAP-32330](https://issues.redhat.com/browse/AAP-32330) - Updated planning guide with changes to clustered redis content
- con-gw-clustered-redis.adoc

AAP-32330 updated planning guide with redis changes

---

downstream/modules/platform/ref-general-inventory-variables.adoc

Also reordered the list to be alphabetical
[Docs] Update description of CA variables in Containerized installer documentation
https://issues.redhat.com/browse/AAP-33585

Added descriptions for ca_tls_* variables

---

attributes/attributes.adoc
stories/assembly-saas-post-install-config.adoc
stories/topics/con-saas-automation-mesh.adoc
stories/topics/con-saas-automation.adoc
stories/topics/con-saas-intro.adoc
stories/topics/con-saas-shape.adoc
stories/topics/ref-saas-egress-model.adoc
stories/topics/ref-saas-mesh-ingress-model.adoc

Quick fix to incorrect links and a few other minor tweaks, as called out in the Oct 17th Hackathon,

fixing saas links and attribute

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc

Commented out until a working procedure is provided.
remove postinstall from documentation
https://issues.redhat.com/browse/AAP-33779

Removed post-install steps

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc

Commented out until a working procedure is provided.
remove postinstall from documentation
https://issues.redhat.com/browse/AAP-33779

Removed post-install steps (#2377)

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
downstream/assemblies/topologies/assembly-rpm-topologies.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-mesh-nodes.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc

- Add RPM growth and RPM mixed growth topologies
- Add/update Redis information across RPM and Cont topologies
- Misc spelling/grammar/attributes clean up
Relevent to the following 2 Jiras:
- https://issues.redhat.com/browse/AAP-32383
- https://issues.redhat.com/browse/AAP-32331

Update Tested deployment models doc

---

downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc

[Doc Bug] : API setting LOG_AGGREGATOR_MAX_DISK_USAGE_GB misses ACTION.
https://issues.redhat.com/browse/AAP-32937

Replace LOG_AGGREGATOR_MAX_DISK_USAGE

---

downstream/modules/platform/proc-operator-upgrade.adoc

[Section 2.4](https://docs.google.com/document/d/1FGdlVKNDyOZswVg8mfWWqp3r6otvgAu9ZlceTFpRVDk/edit) was waiting on a KCS article to be created for event two.

Adding in KCS article required for event2 content

---

downstream/modules/platform/proc-cli-get-controller-pwd.adoc
downstream/modules/platform/proc-install-cli-aap-operator.adoc

AAP-32794 updates (#2378)

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-external-db-controller.adoc
downstream/modules/platform/proc-operator-external-db-gateway.adoc

[AAP-33715](https://issues.redhat.com/browse/AAP-33715)
Adding a new section on how to configure and move the DB externally. Updating the existing controller and hub sections to include gateway in the note.

AAP-33715 adding postgres db section

---

downstream/modules/platform/proc-install-cli-aap-operator.adoc

fix build error - [subs="+quotes"] should not be there

fix build error

---

downstream/attributes/attributes.adoc

Fix the attributes that reference the Controller getting started guide.

2.4 Fix  title attribute

---

downstream/attributes/attributes.adoc

Fix the attributes that reference the Analytics guides.

2.4 Fix analytics title attributes

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

Missing connection between hub and controller
https://issues.redhat.com/browse/AAP-33907

Added controller to hub connection to table

---

downstream/assemblies/devtools/assembly-devtools-ansible-sign.adoc
downstream/assemblies/devtools/assembly-devtools-builder.adoc
downstream/assemblies/devtools/assembly-devtools-create-plugins-collection.adoc
downstream/assemblies/devtools/assembly-devtools-lint.adoc
downstream/assemblies/devtools/assembly-devtools-molecule.adoc
downstream/assemblies/devtools/assembly-devtools-navigator.adoc
downstream/assemblies/devtools/assembly-devtools-pytest-ansible.adoc
downstream/assemblies/devtools/assembly-devtools-tox-ansible.adoc
downstream/modules/devtools/con-devtools-plan-plugins-collection.adoc
downstream/modules/devtools/con-devtools-plugins-collection-prerequisites.adoc
downstream/modules/devtools/proc-devtools-scaffold-plugins-collection.adoc
downstream/titles/develop-automation-content/master.adoc

Scaffolding chapters in the devtools doc for content relating to collections for modules / plug-ins.

AAP-33897 Devtools Add scaffolding collections chapter

---

downstream/modules/platform/con-aap-upgrade-planning.adoc

This PR adds the info requested [here](https://docs.google.com/document/d/1OMNZzknJdVDtTd3MnAj8s34PtSHC-yN23efGeUeWhbw/edit?disco=AAABXhC--Rw).

Adds note about backup environment to Upgrade/Migration guide

---

downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

Update the Redis HA and colocation information to clarify where you can and cannot colocate.
Topology updates for RPM Redis support
https://issues.redhat.com/browse/AAP-32331

Update Redis HA in Tested deployment models

---

downstream/modules/platform/ref-eda-system-requirements.adoc

Note format is incorrect
https://issues.redhat.com/browse/AAP-34072

Corrected note format

---

downstream/modules/platform/ref-eda-system-requirements.adoc

Note format is incorrect
https://issues.redhat.com/browse/AAP-34072

Corrected note format (#2409)

---

downstream/assemblies/hub/assembly-delete-container.adoc
downstream/assemblies/hub/assembly-populate-container-registry.adoc
downstream/assemblies/hub/assembly-pull-image.adoc
downstream/assemblies/hub/assembly-setup-container-repository.adoc
downstream/modules/hub/proc-add-group-to-container-repo.adoc
downstream/modules/hub/proc-obtain-images.adoc
downstream/modules/hub/proc-pull-image.adoc
downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
downstream/modules/hub/proc-reject-collections.adoc
downstream/modules/hub/proc-sync-image.adoc
downstream/modules/hub/proc-tag-image.adoc
downstream/modules/platform/con-gs-execution-env.adoc

This PR is associated with the JIRA tracking broken link fixes, [AAP-15176](https://issues.redhat.com/browse/AAP-15176).

Fixes broken links and typos in managing automation content guide

---

downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

Tweaked previous statement originally proposed in PR https://github.com/ansible/aap-docs/pull/2418 and rearranged the order of the bullet list to ensure clarity.

AAP-30120-B Tweaked admonition bullets for setting up rulebook activation

---

downstream/attributes/attributes.adoc
downstream/modules/platform/proc-account-linking.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
downstream/titles/upgrade/docinfo.xml
downstream/titles/upgrade/master.adoc

[AAP-29859](https://issues.redhat.com/browse/AAP-29859)
- `modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc`: Made revisions base on [draft of mixed environments doc for upgrades](https://docs.google.com/document/d/1a5x-ABiT7MTYkd0qOd6lPVw4Fd3FA8-3KVJYEyoy4F0/edit#heading=h.ovcge493ndqs) (text in pink)
- `modules/platform/proc-account-linking.adoc`: Added last sentence from this [upgrade and migration draft](https://docs.google.com/document/d/1OMNZzknJdVDtTd3MnAj8s34PtSHC-yN23efGeUeWhbw/edit) (pg 11)
- `titles/upgrade/master.adoc`  and `titles/upgrade/docinfo.xml `: Changed title to _RPM upgrade and migration_
-`attributes/attributes.adoc`: Changed title attribute

AAP-29859: Revise first two paragraphs

---

downstream/attributes/attributes.adoc
downstream/modules/platform/proc-account-linking.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
downstream/titles/upgrade/docinfo.xml
downstream/titles/upgrade/master.adoc

[AAP-29859](https://issues.redhat.com/browse/AAP-29859)
modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc: Made revisions base on [draft of mixed environments doc for upgrades](https://docs.google.com/document/d/1a5x-ABiT7MTYkd0qOd6lPVw4Fd3FA8-3KVJYEyoy4F0/edit#heading=h.ovcge493ndqs) (text in pink)
modules/platform/proc-account-linking.adoc: Added last sentence from this [upgrade and migration draft](https://docs.google.com/document/d/1OMNZzknJdVDtTd3MnAj8s34PtSHC-yN23efGeUeWhbw/edit) (pg 11)
titles/upgrade/master.adoc and titles/upgrade/docinfo.xml : Changed title to RPM upgrade and migration
-attributes/attributes.adoc: Changed title attribute

[2.5] AAP-29859: Revise first two paragraphs (#2431)

---

downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/proc-account-linking.adoc
downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc

This PR addresses [Phil's feedback in the RPM upgrade/migration guide ](https://docs.google.com/document/d/1OMNZzknJdVDtTd3MnAj8s34PtSHC-yN23efGeUeWhbw/edit?usp=sharing).

Adds SME feedback to RPM upgrade guide

---

downstream/modules/platform/proc-account-linking.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

This PR makes minor fixes noted in the backport for #2431

Minor fixes for PR 2431

---

downstream/modules/platform/proc-account-linking.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

This PR backports the changes from #2435 to the 2.5 branch.

[Backport] Minor fixes for PR 2431 (#2435)

---

downstream/titles/release-notes/async/aap-25-3-28-oct.adoc

Update the 2.5-3 async RNS with the remaining Jiras
AAP 2.5 (3) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-33685

2.5 Update 2.5-3 async RNs (#2444)

---

downstream/modules/platform/proc-account-linking.adoc

This PR addresses requests from Phil Griffiths to include link to OIDC KCS article.
[Upgrade and migration draft 2.5](https://docs.google.com/document/d/1OMNZzknJdVDtTd3MnAj8s34PtSHC-yN23efGeUeWhbw/edit?usp=sharing)

Add-KCS-link: Article on fixing broken OIDC

---

downstream/modules/platform/proc-account-linking.adoc

This PR addresses requests from Phil Griffiths to include link to OIDC KCS article.
[Upgrade and migration draft 2.5](https://docs.google.com/document/d/1OMNZzknJdVDtTd3MnAj8s34PtSHC-yN23efGeUeWhbw/edit?usp=sharing)

[2.5] Add-KCS-link: Article on fixing broken OIDC (#2453)

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc

This PR adds the prerequisite details to the Upgrade guide.

Add upgrade prerequisite details

---

downstream/assemblies/platform/assembly-update-rpm.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc

This PR backports the change from #2459 to the 2.5 branch.

[Backport] Change xref to link in a shared file (#2459)

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/proc-account-linking.adoc

This PR fixes formatting issues with the upgrade guide.

2457 - fix formatting issues in upgrade guide

---

downstream/modules/platform/ref-controller-configs.adoc

Links point to ansible.com
https://issues.redhat.com/browse/AAP-34659

Corrected links

---

downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
downstream/modules/platform/proc-controller-create-application.adoc
downstream/modules/platform/ref-controller-app-token-functions.adoc
downstream/modules/platform/ref-controller-refresh-existing-token.adoc
downstream/modules/platform/ref-controller-revoke-access-token.adoc
downstream/modules/platform/ref-controller-token-session-management.adoc

This PR backports the changes from #2476 to the 2.5 branch and includes the following:
* AAP-34814 - update application OAuth paths
* Added SME feedback changes

[Backport] AAP-34814 - update application OAuth paths (#2476)

---

downstream/modules/platform/proc-controller-create-container-group.adoc

Need to add a hyperlink in Doc
https://issues.redhat.com/browse/AAP-31717

Adding sample service account to user guide

---

downstream/modules/platform/proc-controller-create-container-group.adoc

Need to add a hyperlink in Doc
https://issues.redhat.com/browse/AAP-31717

Adding sample service account to user guide (#2381)

---

downstream/titles/release-notes/topics/aap-25-removed-features.adoc

Added the Python versions that have been removed as supported remote versions.
Resolves: #2414
See also: AAP-33894

Added line to clarify Python version removal.

---

downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc

Tweaked note for RH AAP credential chapter.

AAP-29905B Tweaked note in RH AAP credential chapter

---

downstream/titles/release-notes/topics/aap-25.adoc

Release notes update for Automation Analytics opt in
https://issues.redhat.com/browse/AAP-31286

Add release note entry for automation analytics opt in

---

downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
downstream/modules/platform/proc-creating-a-secret.adoc
downstream/modules/platform/proc-creating-controller-form-view.adoc
downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc

[AAP-33475](https://issues.redhat.com/browse/AAP-33475) 
- Updating examples for each individual component in 2.4 docs (Controller, Hub, EDA) to include better storage to prevent issues down the line.
- Improving instructions for Hub install proc
- removing unnecessary duplicate module.

aap-33475 2.4 specific edits

---

downstream/titles/release-notes/topics/aap-25.adoc

Release notes update for Automation Analytics opt in
https://issues.redhat.com/browse/AAP-31286

2.5 Add release note entry for automation analytics opt in (#2495)

---

downstream/modules/platform/ref-postgresql-requirements.adoc

[AAP-32732](https://issues.redhat.com/browse/AAP-32732)
Adding a note on ICU support to the 2.4 doc.

Adding note on ICU support to 2.4 doc

---

downstream/assemblies/platform/assembly-controller-best-practices.adoc
downstream/assemblies/platform/assembly-controller-credentials.adoc
downstream/assemblies/platform/assembly-ug-controller-instance-groups.adoc
downstream/assemblies/platform/assembly-ug-controller-work-with-webhooks.adoc
downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
downstream/modules/platform/con-controller-overview-details.adoc
downstream/modules/platform/con-controller-role-based-access-controls.adoc
downstream/modules/platform/con-controller-settings.adoc
downstream/modules/platform/con-controller-workflow-visualizer.adoc
downstream/modules/platform/proc-controller-access-topology-viewer.adoc
downstream/modules/platform/proc-controller-add-source.adoc
downstream/modules/platform/proc-controller-adding-new-inventory.adoc
downstream/modules/platform/proc-controller-create-container-group.adoc
downstream/modules/platform/proc-controller-create-custom-notifications.adoc
downstream/modules/platform/proc-controller-define-schedule-rules.adoc
downstream/modules/platform/proc-controller-set-up-github-webhook.adoc
downstream/modules/platform/proc-controller-set-up-gitlab-webhook.adoc
downstream/modules/platform/proc-controller-sourced-from-project.adoc
downstream/modules/platform/proc-controller-view-jobs-associated-with-instance-group.adoc
downstream/modules/platform/proc-scm-git-subversion.adoc
downstream/modules/platform/ref-controller-content-sourcing.adoc
downstream/modules/platform/ref-controller-credential-gitHub-pat.adoc
downstream/modules/platform/ref-controller-credential-gitLab-pat.adoc
downstream/modules/platform/ref-controller-credential-terraform.adoc
downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc

Using automation execution guide post-GA edits
https://issues.redhat.com/browse/AAP-34521
Affects `titles/user-guide`

Minor edits to user guide

---

downstream/assemblies/platform/assembly-controller-best-practices.adoc
downstream/assemblies/platform/assembly-controller-credentials.adoc
downstream/assemblies/platform/assembly-ug-controller-instance-groups.adoc
downstream/assemblies/platform/assembly-ug-controller-work-with-webhooks.adoc
downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
downstream/modules/platform/con-controller-overview-details.adoc
downstream/modules/platform/con-controller-role-based-access-controls.adoc
downstream/modules/platform/con-controller-settings.adoc
downstream/modules/platform/con-controller-workflow-visualizer.adoc
downstream/modules/platform/proc-controller-access-topology-viewer.adoc
downstream/modules/platform/proc-controller-add-source.adoc
downstream/modules/platform/proc-controller-adding-new-inventory.adoc
downstream/modules/platform/proc-controller-create-container-group.adoc
downstream/modules/platform/proc-controller-create-custom-notifications.adoc
downstream/modules/platform/proc-controller-define-schedule-rules.adoc
downstream/modules/platform/proc-controller-set-up-github-webhook.adoc
downstream/modules/platform/proc-controller-set-up-gitlab-webhook.adoc
downstream/modules/platform/proc-controller-sourced-from-project.adoc
downstream/modules/platform/proc-controller-view-jobs-associated-with-instance-group.adoc
downstream/modules/platform/proc-scm-git-subversion.adoc
downstream/modules/platform/ref-controller-content-sourcing.adoc
downstream/modules/platform/ref-controller-credential-gitHub-pat.adoc
downstream/modules/platform/ref-controller-credential-gitLab-pat.adoc
downstream/modules/platform/ref-controller-credential-terraform.adoc
downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc

* Minor edits to user guide
Using automation execution guide post-GA edits
https://issues.redhat.com/browse/AAP-34521
Affects `titles/user-guide`
* Further minor corrections to UG
* Final edits to UG

Minor edits to user guide (#2426)

---

downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc

Revert "AAP-29905B Tweaked note in RH AAP credential chapter"

---

downstream/modules/hub/con-offline-token-active.adoc
downstream/modules/hub/proc-create-api-token-pah.adoc
downstream/modules/hub/proc-create-api-token.adoc

See [AAP-33331](https://issues.redhat.com/browse/AAP-33331) for more info.

AAP-33331: clarifies instructions on keeping offline hub token active

---

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/modules/platform/proc-creating-a-secret.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc
downstream/modules/platform/proc-operator-link-components.adoc

[AAP-33475](https://issues.redhat.com/browse/AAP-33475)
Updating examples for AAP CR to include  storage spec. (fresh install, and for linking existing components)
removing unnecessary duplicate module.

aap-33475 2.5 specific edits

---

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/modules/platform/proc-creating-a-secret.adoc
downstream/modules/platform/proc-operator-deploy-central-config.adoc
downstream/modules/platform/proc-operator-link-components.adoc

[AAP-33475](https://issues.redhat.com/browse/AAP-33475)
Updating examples for AAP CR to include storage spec. (fresh install, and for linking existing components)
removing unnecessary duplicate module.

aap-33475 2.5 specific edits (#2497)

---

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/modules/platform/proc-operator-create_crs.adoc
downstream/modules/platform/ref-operator-crs.adoc

The steps are very vague. Adding more detailed steps and an example to follow.

Applying updates from AAP-35076

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc

[AAP-35119](https://issues.redhat.com/browse/AAP-35119)
Updated introductory paragraph to [Chapter 1. Overview of tested deployment models](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/tested_deployment_models/overview-tested-deployment-models)
- assembly-overview-tested-deployment-models.adoc

AAP-35119 updated overview to tested topologies

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc

[AAP-35120](https://issues.redhat.com/browse/AAP-35120)
Updated introductory paragraph to [Chapter 1. Overview of tested deployment models](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/tested_deployment_models/overview-tested-deployment-models)
assembly-overview-tested-deployment-models.adoc

AAP-35119 updated overview to tested topologies (#2511)

---

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/modules/platform/proc-operator-create_crs.adoc
downstream/modules/platform/ref-operator-crs.adoc

* Applying updates from AAP-35076

Applying updates from AAP-35076 (#2509)

---

aap-common/boilerplate.adoc
attributes/attributes.adoc
titles/aap-on-azure/stories.adoc
titles/saas-aws/stories.adoc

Update the boilerplate text in Azure and SaaS docs, and add attributes for AAP menus and AAP docs URLs.

Clouds - update attributes and boilerplate text

---

attributes/attributes.adoc

Clouds - add Azure and SaaS attributes to clouds attributes

Clouds - add Azure and SaaS attributes to clouds attributes

---

downstream/attributes/attributes.adoc

Add attributes for Clouds docs (#2528)

2.5 Add attributes for Clouds docs (#2528)

---

downstream/attributes/attributes.adoc

2.4 Add attributes for Clouds docs (#2528)

2.4 Add attributes for Clouds docs (#2528)

---

attributes/attributes.adoc

Clouds: Update SaaS title attributes

Clouds: Update SaaS title attributes

---

downstream/attributes/attributes.adoc

Update SaaS title attributes in downstream docs

Update SaaS title attributes in downstream docs

---

downstream/attributes/attributes.adoc

2.4 Update SaaS title attributes in downstream docs (#2533)

2.4 Update SaaS title attributes in downstream docs (#2533)

---

downstream/attributes/attributes.adoc

2.5 Update SaaS title attributes in downstream docs (#2533)

2.5 Update SaaS title attributes in downstream docs (#2533)

---

titles/saas-aws/title-attributes.adoc

Clouds - update title-attribute file for SaaS doc

Clouds - update title-attribute file for SaaS doc

---

downstream/attributes/attributes.adoc

Add Red Hat to SaaS title attribute

Add Red Hat to SaaS title attribute

---

downstream/attributes/attributes.adoc

Add Red Hat to SaaS title attribute

Add Red Hat to SaaS title attribute (#2540)

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-33062 to provide more details regarding LDAP Group types.

AAP-33062 - add more details for LDAP Group types

---

downstream/modules/platform/proc-running-setup-script-for-updates.adoc

Fix link in RPM upgrade guide

---

downstream/attributes/attributes.adoc

Update Satellite version
https://issues.redhat.com/browse/AAP-35288

Updated Satellite version

---

downstream/attributes/attributes.adoc

Update Satellite version
https://issues.redhat.com/browse/AAP-35288

Updated Satellite version (#2547)

---

downstream/assemblies/eda/assembly-eda-decision-environments.adoc
downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
downstream/modules/eda/ref-eda-controller-install-builder.adoc

Updated the "Building a custom decision environment for Event-Driven Ansible" topic, downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc

AAP-30113 Emphasize correct decision environment usage in docs

---

downstream/assemblies/eda/assembly-eda-decision-environments.adoc
downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
downstream/modules/eda/ref-eda-controller-install-builder.adoc

Updated [Chapter 5. Decision Environment](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-decision-environments) in the Using automation decisions guide.

AAP-30113 Emphasize correct decision environment usage in docs (#2513)

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc
downstream/modules/platform/proc-define-mesh-node-types.adoc

* Added not about receptor not listening
Explain in documentation that receptor is not listening on first controller
https://issues.redhat.com/browse/AAP-23036
* Added note about receptor not listening
Explain in documentation that receptor is not listening on first controller
https://issues.redhat.com/browse/AAP-23036

Added note about receptor not listening (#2514)

---

downstream/modules/platform/ref-ansible-inventory-variables.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

* Add missing receptor vars to inventory appendix https://issues.redhat.com/browse/AAP-35192

2.5 Add missing receptor vars to inventory appendix (#2559)

---

attributes/attributes.adoc
stories/assembly-saas-intro.adoc
stories/assembly-saas-pull-push.adoc
stories/topics/con-saas-automation.adoc
stories/topics/con-saas-backup-and-diaster-recovery.adoc
stories/topics/con-saas-control-plane.adoc
stories/topics/con-saas-deployment-self-service.adoc
stories/topics/con-saas-hosted-components.adoc
stories/topics/con-saas-identity-and-access-management.adoc
stories/topics/con-saas-service-uptime.adoc

AAP 32543 Clouds - Add Service uptime section in SaaS
Affects `aap-docs/titles/saas-aws`

AAP 32543 Clouds - Add Service uptime section in SaaS

---

downstream/attributes/attributes.adoc
downstream/modules/platform/proc-define-mesh-node-types.adoc

2.5 AAP-32543 Clarify options in mesh node types definition (#2553)

---

stories/assembly-azure-connecting-to-aap.adoc
stories/topics/con-azure-about.adoc
stories/topics/proc-azure-nw-private-deploy.adoc
titles/aap-on-azure/docinfo.xml
titles/aap-on-azure/master.adoc
titles/aap-on-azure/title-attributes.adoc

AAP-35811 Azure doc cleanup before 2.5 work starts

AAP-35811 Azure doc cleanup before 2.5 work starts

---

stories/topics/con-azure-aks-cidr.adoc

Update Pod CIDR requirements in the Azure documentation per https://access.redhat.com/articles/6973251

AAP-29301 Azure - update pod CIDR requirements

---

stories/topics/con-azure-aks-cidr.adoc

AAP-29301a Azure - Fix pod service case

---

downstream/assemblies/hub/assembly-hub-create-api-token.adoc

See [AAP-35099](https://issues.redhat.com/browse/AAP-35099) for more info

AAP-35099: adds info for token management with PAH and keycloak

---

stories/topics/con-saas-shape.adoc

[AAP-35863](https://issues.redhat.com/browse/AAP-35863)
AAP Service Hop Nodes Description Incorrect

AAP-35863 Clarifying hop nodes bullet

---

downstream/modules/platform/proc-controller-credential-create-openshift-account.adoc

Update sample service account details
https://issues.redhat.com/browse/AAP-36116

Editing sample service account details

---

downstream/modules/platform/proc-controller-credential-create-openshift-account.adoc

* Editing sample service account details
Update sample service account details
https://issues.redhat.com/browse/AAP-36116
* Update per peer review

Editing sample service account details (#2583)

---

stories/topics/proc-azure-configure-ad-sso.adoc

[AAP-35957](https://issues.redhat.com/browse/AAP-35957) 
- Updating Azure AD references to Microsoft Entra ID.

AAP-35957 updating Azure AD references to Microsoft Entra ID

---

downstream/titles/release-notes/async/aap-25-4-20-nov.adoc

These release notes cover the current enhancements and bug fixes for the AAP 2.5 (4) release on November 20, 2024.
Resolves: AAP-35387

AAP 2.5 (4) Async Release-Updated Release Notes

---

downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
downstream/titles/release-notes/master.adoc

AAP 2.5 (4) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-35387

Add release notes for async-2.5-4

---

downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
downstream/titles/release-notes/master.adoc

AAP 2.5 (4) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-35387

2.5 Add release notes for async-2.5-4 (#2595)

---

downstream/modules/platform/proc-aap-controller-backup.adoc

This PR backports the changes from #2599 to the 2.5 branch.

[Backport] - Fixed broken link caused by PR 2330 (#2599)

---

downstream/modules/platform/proc-aap-controller-backup.adoc

This PR backports the fix for #2599 to the 2.4 branch.

[Backport] Fixed broken link caused by PR 2330 (#2599)

---

downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
downstream/modules/platform/proc-controller-set-up-azure.adoc

* Adding Microsoft Entra ID reference to docs
Update documentation to refer to Microsoft Entra ID, formerly Azure Active Directory
https://issues.redhat.com/browse/AAP-35957
* Second commit for Azure edits
* Final edits to Azure updates

Adding Microsoft Entra ID reference to docs (#2578)

---

downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc

Re-adding ref-automation-controller-authentication.adoc which was removed in error when resolving a conflict

Re-adding controller auth ref

---

downstream/assemblies/hub/assembly-hub-create-api-token.adoc
downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
downstream/modules/hub/con-offline-token-active.adoc
downstream/modules/hub/con-token-management-hub.adoc
downstream/modules/hub/proc-create-api-token-pah.adoc
downstream/modules/hub/proc-create-api-token.adoc
downstream/modules/hub/proc-create-requirements-file.adoc
downstream/modules/hub/proc-set-community-remote.adoc
downstream/modules/hub/proc-set-rhcertified-remote.adoc

This PR affects `assembly-syncing-to-cloud-repo.adoc` and all the modules included in that assembly.

Adds context attribute to assembly in Managing automation content

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-controller-set-up-SAML.adoc
downstream/modules/platform/proc-operator-aap-faq.adoc
downstream/modules/platform/proc-operator-enable-https-redirect.adoc

[AAP-36295](https://issues.redhat.com/browse/AAP-36295) 
- Adding REDIRECT_IS_HTTPS set up to Openshift documentation
- Adding a note in the SAML setup section of the Access and Authentication doc

AAP-36295 HTTPS updates

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-controller-set-up-SAML.adoc
downstream/modules/platform/proc-operator-aap-faq.adoc
downstream/modules/platform/proc-operator-enable-https-redirect.adoc

AAP-36295 HTTPS updates (#2622)

---

downstream/modules/platform/proc-controller-set-up-azure.adoc

Had to copy 2.4 from original PR.
Fix snippet error in 2.4 Controller Admin Guide
https://issues.redhat.com/browse/AAP-36587

Correct azure module to work in 2.4 and 2.5 (#2624)

---

downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc

* Adding custom inventory script example
Improved custom inventory script documentation for Controller
https://issues.redhat.com/browse/AAP-11874
* Tech review edits
* Adding further details re custom inventory script

Adding custom inventory script example (#1941)

---

lightspeed/modules/con_overview-lightspeed-onpremise.adoc

This PR addresses JIRA 
Changes made:
Added OCP in the prerequisites for Lightspeed onpremise deployment.

AAP-35860: Updated the prerequisites for Lightspeed onpremise

---

lightspeed/modules/proc_multi-task-recs.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-35926. 
Changes made:
Added info. about the multitask prompt split over multiple lines capability.

AAP-35926: Updated the the docs with VSCode multi-line prompts feature

---

downstream/modules/platform/ref-controller-variables.adoc

Remove supervisor_start_retry_count from AAP 2.4 and 2.5 docs
https://issues.redhat.com/browse/AAP-36524

Remove controller variable

---

downstream/titles/release-notes/topics/aap-25.adoc

Affects: `titles/release-notes`
[Saas] Create a new feature blurb for release notes
https://issues.redhat.com/browse/AAP-36199

Add release note entry for AAP Service on AWS

---

downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc

Correct bullet list style in Installation Guide (parallel structure)
https://issues.redhat.com/browse/AAP-36720

Update note format

---

downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc

Affects: `titles/topologies`
Update product docs to include IBM Z arch test support for CONT topologies
https://issues.redhat.com/browse/AAP-35969

Add IBM-Z to CONT topologies

---

downstream/modules/platform/proc-completing-post-installation-tasks.adoc

Documentation for disconnected installation ask the users to do commands that are not possible
https://issues.redhat.com/browse/AAP-36454

Removed incorrect subsections

---

downstream/modules/platform/proc-configuring-the-metrics-utility.adoc

* Minor edits to metrics utility section
* Adding RHEL attribute

Minor edits to metrics utility section (#2644)

---

downstream/modules/platform/proc-completing-post-installation-tasks.adoc

Remove incorrect statement from installation guide
https://issues.redhat.com/browse/AAP-36826

Removed incorrect statement

---

downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
downstream/titles/release-notes/async/aap-25-5-4-dec.adoc
downstream/titles/release-notes/master.adoc

AAP 2.5 (5) Async Release
https://issues.redhat.com/browse/AAP-36423

2.5 Add async rns for async 2.5-5 (#2648)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/async-24-26-3-dec.adoc

Uncomment the next async RNs so they can be published in line with the release
AAP 2.4 (26) Async Release
https://issues.redhat.com/browse/AAP-36437

2.4 Update async release notes

---

downstream/titles/release-notes/async/aap-25-5-3-dec.adoc
downstream/titles/release-notes/master.adoc

Uncomment the next async RNs so they can be published in line with the release
AAP 2.5 (5) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-36432

Update 2.5-5 async release notes

---

downstream/titles/release-notes/async/aap-25-5-3-dec.adoc
downstream/titles/release-notes/master.adoc

Uncomment the next async RNs so they can be published in line with the release
AAP 2.5 (5) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-36432

2.5 Update 2.5-5 async release notes (#2651)

---

downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc

Correct formatting error
https://issues.redhat.com/browse/AAP-37026

Corrected formatting error

---

downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc

Correct formatting error
https://issues.redhat.com/browse/AAP-37026

Corrected formatting error (#2658)

---

downstream/modules/platform/ref-hub-variables.adoc

Add the equivalent containerized variable to the inventory vars appendix
Private automation hub variable discrepancy in docs
https://issues.redhat.com/browse/AAP-36513

Add hub_seed_collections to inventory vars appendix

---

downstream/modules/platform/ref-hub-variables.adoc

Add the equivalent containerized variable to the inventory vars appendix
Private automation hub variable discrepancy in docs
https://issues.redhat.com/browse/AAP-36513

2.5 Add hub_seed_collections to inventory vars appendix (#2667)

---

downstream/modules/aap-hardening/con-logging-log-capture.adoc
downstream/modules/platform/proc-gs-use-base-execution-env.adoc

Fixes broken links from the [November broken links report](https://docs.google.com/spreadsheets/d/1hv2Xn6-r6LJlkz9PxGUJgycFVnpT3egP2iFk3pOan4M/edit?gid=64075153#gid=64075153). See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.

AAP-15176: fixes broken links from nov broken links report

---

downstream/modules/platform/proc-cli-get-controller-pwd.adoc

[AAP-37117](https://issues.redhat.com/browse/AAP-37117)
Adding "oc get secret/example-admin-password -o jsonpath={.data.password} | base64 --decode" command to CLI section

AAP-37117 adding a proc on decoding the base64 password

---

downstream/modules/platform/proc-cli-get-controller-pwd.adoc

AAP-37117 adding a proc on decoding the base64 password (#2675)

---

downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc

Backport PR https://github.com/ansible/aap-docs/pull/2688 from main to AAP v2.5.

Backport pull request #2688 from main to 2.5

---

ansible-inside/stories/asssembly-ansible-inside-install-intro.adoc
ansible-inside/titles/reporting-guide/docinfo.xml
ansible-inside/topics/proc-ansible-inside-install-registry.adoc

AAP-37559a Update version for Ansible Inside 1.3
Affects ansible inside reporting guide and installation guide

AAP-37559a Update version for Ansible Inside 1.3

---

downstream/modules/hub/proc-obtain-images.adoc

See [AAP-36858](https://issues.redhat.com/browse/AAP-36858) for more detail.

AAP-36858: removes satellite link from section on pulling EEs

---

downstream/titles/release-notes/async/aap-25-12-18-dec.adoc

Resolves: AAP-37057
See also: AAP-37319

Release Notes for the December 18, 2024 patch release.

---

downstream/modules/platform/ref-gateway-controller-ext-db.adoc
downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
downstream/modules/platform/ref-gateway-controller-hub-ext-db.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

Add redis_mode to inventory variables
Doc Bug in RHAAP 2.5 RPM Installation
https://issues.redhat.com/browse/AAP-37501

Update inventory file variable

---

downstream/modules/platform/proc-configure-controller-OCP.adoc

[AAP-37533](https://issues.redhat.com/browse/AAP-37533)
Adding newer versions to the prereqs of chapter 4.1

Adding later versions to chapter 4.1 of OCP perf guide

---

downstream/modules/platform/ref-gateway-controller-ext-db.adoc
downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
downstream/modules/platform/ref-gateway-controller-hub-ext-db.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

Add redis_mode to inventory variables
Doc Bug in RHAAP 2.5 RPM Installation
https://issues.redhat.com/browse/AAP-37501

Update inventory file variable (#2693)

---

downstream/titles/release-notes/async/aap-25-12-18-dec.adoc

Resolves: AAP-37057
See also: AAP-37319

Release Notes for the December 18, 2024 patch release. (#2700)

---

downstream/titles/release-notes/topics/async-24-12-18-dec.adoc

Release notes for the 2.4 patch release on 12-18-24 Dec.

---

downstream/modules/platform/proc-aap-activate-with-credentials.adoc
downstream/modules/platform/proc-aap-activate-with-manifest.adoc
downstream/modules/platform/proc-aap-create-subscription-allocation.adoc

This PR updates the Satellite version as requested by https://issues.redhat.com/browse/AAP-35016. It also fixes a minor formatting issue in the subscription verification details.

AAP-35016 - Update Satellite version and minor formatting fix

---

downstream/modules/platform/proc-aap-activate-with-credentials.adoc
downstream/modules/platform/proc-aap-activate-with-manifest.adoc
downstream/modules/platform/proc-aap-create-subscription-allocation.adoc

This PR backports the changes from #2717 to the 2.5 branch.

[Backport] AAP-35016 - Update Satellite version and minor formatting fix (#2717)

---

downstream/modules/platform/proc-aap-create-subscription-allocation.adoc

This PR changes the hardcoded 6.16 satellite version with the attribute.

Replaced satellite version number with the defined attribute

---

stories/topics/con-saas-deployment-self-service.adoc

[AAP-37637](https://issues.redhat.com/browse/AAP-37637)
Adding additional information around the deprovisioning process for Saas

AAP-37637 Deprovisioning edits

---

downstream/attributes/attributes.adoc

Add comment in attributes for aap-on-gcp deprecation

Add comment in attributes for aap-on-gcp deprecation

---

stories/topics/con-saas-deployment-self-service.adoc

[AAP-38427](https://issues.redhat.com/browse/AAP-38427)
Need to add the following to [section 5.1.2](https://docs.redhat.com/en/documentation/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_service_on_aws/saas-service-definition#con-saas-deployment-self-service)
"If you initiate a cancellation, your deployment will shut down within a few hours."

Updating cancellation information

---

downstream/modules/platform/proc-settings-gw-security-options.adoc

This PR corrects a typo to change in to is.

AAP-38268 - corrected typo

---

downstream/modules/platform/con-hs-eda-controller.adoc
downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc
downstream/modules/platform/proc-hs-eda-setup.adoc

The following files are specific to RPM installations and needed to be updated to account for container installations also:
- proc-add-eda-safe-plugin-var.adoc
- proc-hs-eda-setup.adoc
Add conditional statements to account for both RPM and CONT based procedures.
Affects titles:
- aap-containerized-install
- aap-installation-guide
Containerized installation - Ensure inventory file code snippets contain correct samples for RPM and CONT AAP
https://issues.redhat.com/browse/AAP-36654

2.5 Update eda config procedures in Containerized installation (#2753)

---

downstream/titles/release-notes/async/aap-25-20250115.adoc

Release notes for 15 January 2025. AAP-2.5(20250115)

---

downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc

Modified instruuctions and made corrections
Procedure to connect nodes through mesh ingress has multiple issues
https://issues.redhat.com/browse/AAP-38347

Changes to mesh ingress information

---

downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc

* Changes to mesh ingress information
Modified instruuctions and made corrections
Procedure to connect nodes through mesh ingress has multiple issues
https://issues.redhat.com/browse/AAP-38347
* Changes to mesh ingress information
Added apiVersion and additional steps.
Procedure to connect nodes through mesh ingress has multiple issues
https://issues.redhat.com/browse/AAP-38347
* Changes to mesh ingress information
Correction
Procedure to connect nodes through mesh ingress has multiple issues
https://issues.redhat.com/browse/AAP-38347
* Changes to mesh ingress information
Correction
Procedure to connect nodes through mesh ingress has multiple issues
https://issues.redhat.com/browse/AAP-38347
* Changes to mesh ingress information
Corrections
Procedure to connect nodes through mesh ingress …

Changes to mesh ingress information (#2748)

---

downstream/modules/platform/proc-setup-postgresql-ext-database.adoc

Product Docs State That External Databases Are Not Supported
https://issues.redhat.com/browse/AAP-37869

Removed postgres message

---

downstream/modules/platform/proc-setup-postgresql-ext-database.adoc

* Removed postgres message
Product Docs State That External Databases Are Not Supported
https://issues.redhat.com/browse/AAP-37869

Removed postgres message (#2762)

---

downstream/titles/release-notes/async/aap-25-20250115.adoc

* Release notes for 15 January 2025. AAP-2.5(20250115)
Resolves:AAP-38195
* Update aap-25-20250115.adoc
* Update aap-25-20250115.adoc

Release notes for 15 January 2025. AAP-2.5(20250115) (#2758)

---

downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc

Correct fomatting error
https://issues.redhat.com/browse/AAP-38588

Correct note formatting

---

downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc

Correct fomatting error
https://issues.redhat.com/browse/AAP-38588

Correct note formatting (#2772)
