- bin/sync_cloud_docs.sh
Add a script to the `/bin` directory to sync the AAP on AWS content to the production docs repo on Gitlab.
> Add Jenkins job for AAP on AWS docs

- stories/topics/proc-azure-update-route-tables.adoc
Adding `quay.io` back with the addition of quay cdn match that was added with https://github.com/ansible/aap-docs/pull/42
> Re-adding quay.io for Azure firewall rule requirement

- aap-common/external-site-disclaimer.adoc
Add a file to the `downstream/aap-common/` directory. It contains approved text that disclaims responsibility for the content in external websites.
> Add disclaimer for links to external websites

- stories/topics/proc-azure-update-route-tables.adoc
Expand the domain list in the _Outbound routing through virtual appliances_ section of the AAP on Azure docs.
> Add domains to outbound routing list

- stories/assembly-aap-azure-install.adoc
- stories/topics/proc-azure-cancel-deployment.adoc
- stories/topics/proc-azure-monitor-deployment-engine.adoc
- stories/topics/proc-azure-provisioning-aap.adoc
Azure:
Describe how to open the deployment engine, and use it to monitor and cancel AAP deployments.
> Azure: Add Deployment engine docs

- stories/assembly-aws-intro.adoc
- stories/assembly-gcp-intro.adoc
- stories/topics/con-azure-about.adoc
Remove references to Automation Services Catalog in Azure, GCP, and AWS docs.
> Remove references to Automation Services Catalog

- bin/sync_cloud_docs.sh
Modify Jenkins script for aap-clouds-2.2.1:
- Delete references to Azure, as the 2.2.2 page on the Customer portal will only show docs for self-managed AoC.
> 2.2.1 Modify Jenkins sync script

- aap-common/providing-direct-documentation-feedback.adoc
- titles/aap-on-aws/stories.adoc
- titles/aap-on-gcp/stories.adoc
Add direct docs feedback module in AoC 2.2.1 docs (AWS and GCP)
> 2.2.1 Add Direct docs feedback module

- stories/topics/proc-aap-aws-application-upgrade.adoc
- stories/topics/proc-aap-aws-backup-and-recovery.adoc
- stories/topics/proc-aap-aws-create-extension-nodes.adoc
- stories/topics/proc-aap-aws-prepare-environment.adoc
- stories/topics/proc-aap-aws-removing-extension-nodes.adoc
- stories/topics/proc-aap-aws-secure-hub-controller-connection.adoc
- stories/topics/proc-aap-gcp-application-upgrade.adoc
- stories/topics/proc-aap-gcp-backup-process.adoc
- stories/topics/proc-aap-gcp-restore-process.adoc
- stories/topics/proc-azure-podidentity.adoc
- stories/topics/proc-secure-controller-load-balancer.adoc
Remove `[source,bash]` line preceding codeblocks
Removing the [source,bash] asciidoc tag so that the `$` prompt is not included when the copy/paste icon is used in the published docs in the customer portal
Backports #131 to aap-clouds-2.2.1
> 2.2.1 Remove source,bash line preceding codeblocks

- stories/topics/con-azure-aks-cidr.adoc
Update the AKS CIDR Blocks requirements in [Azure guide](https://access.redhat.com/documentation/en-us/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#azure_aks-cidr_azure-intro) to align with[ KCS article](https://access.redhat.com/articles/6973251#aks-networking-configuration-5)
> Update the AKS CIDR Blocks requirements in Azure guide

- stories/assembly-aws-networking-access.adoc
Fix the `id` for `stories/assembly-aws-networking-access.adoc` so that current external links referencing this chapter do not break.
No internal `xref` instances reference this assembly.
The path to the affected assembly is updated in a local build.
> AWS Fix assembly ID

- stories/assembly-gcp-backup-and-restore.adoc
Fix the `id` for `stories/assembly-gcp-backup-and-restore.adoc` so that current external links referencing this chapter do not break.
No internal `xref` instances reference this assembly.
The path to the affected assembly is updated in a local build of this PR.
Broken link: https://access.redhat.com/documentation/en-us/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_from_gcp_marketplace_guide/assembly-aap-gcp-backup-and-recovery
> GCP Fix ID for backup and restore assembly

- aap-common/proc-aap-list-available-playbooks.adoc
- stories/assembly-aws-deploying-extension-nodes.adoc
Fix the `id` for `assembly-aws-deploying-extension-nodes.adoc` so that current external links referencing this chapter do not break.
No internal `xref` instances reference this assembly.
The path to the affected assembly is updated in a local build of this PR.
NOTE: This assembly originally contained procedures for both deploying and removing extension nodes. Check that the  link should point to the deployment of extension nodes.
Broken link: https://access.redhat.com/documentation/en-us/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_from_aws_marketplace_guide/assembly-aap-aws-extension
> AWS Fix ID for deploy extension nodes assembly

- README.adoc
- stories/assembly-gcp-backup-and-restore.adoc
- stories/topics/con-gcp-backup-process.adoc
- stories/topics/con-gcp-restore-process.adoc
- stories/topics/proc-gcp-create-data-file.adoc
- stories/topics/proc-gcp-generate-restore-yml-file.adoc
- stories/topics/proc-gcp-run-backup-playbook.adoc
- stories/topics/proc-gcp-run-restore-command.adoc
- stories/topics/ref-gcp-populate-backup-file.adoc
- stories/topics/ref-gcp-populate-restore-file.adoc
Contains all backup and restore update suggestions for GCP.
Clarifies some topics, and updates expected outputs.
Removes existing VPC documentation and details it is unsupported.
Noting that the following links 404 as of now. Would be nice if we can redirect these broken links to their expected locations.
Bad Link: https://access.redhat.com/documentation/en-us/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_from_gcp_marketplace_guide/assembly-aap-gcp-backup-and-recovery
Updated Value: https://access.redhat.com/documentation/en-us/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_from_gcp_marketplace_guide/assembly-gcp-backup-and-restore
> GCP - Backup and restore updates

- aap-common/proc-aap-pull-command-container-image.adoc
- stories/assembly-gcp-backup-and-restore.adoc
- stories/topics/con-aws-pull-container-image.adoc
- stories/topics/con-aws-pull-deploy-container-image.adoc
- stories/topics/proc-aws-backup-platform-stack.adoc
- stories/topics/proc-aws-from-stack-pull-container-image.adoc
- stories/topics/proc-aws-set-container-image.adoc
- stories/topics/proc-aws-upgrade-pull-container-image.adoc
- stories/topics/proc-gcp-backup-container-image.adoc
- stories/topics/proc-gcp-create-data-file.adoc
- stories/topics/proc-gcp-from-stack-pull-container-image.adoc
- stories/topics/proc-gcp-pull-backup-container-image.adoc
- stories/topics/proc-gcp-setup-environment.adoc
- stories/topics/proc-gcp-upgrade-pull-container-image.adoc
- stories/topics/ref-aws-permissions-to-manage-nodes.adoc
Remove `[source,bash]` line preceding codeblocks
Removing the [source,bash] asciidoc tag so that the `$` prompt is not included when the copy/paste icon is used in the published docs in the customer portal
> Delete source,bash from line preceding codeblocks

- aap-common/providing-direct-documentation-feedback.adoc
- titles/aap-on-aws/stories.adoc
- titles/aap-on-azure/stories.adoc
- titles/aap-on-gcp/stories.adoc
Add direct documentation feedback module to the aap-common folder.
Include the direct documentation module in all titles
Backport to 2.4
> Add Direct Doc Feedback text to all Ansible on Clouds guides

- stories/topics/proc-gcp-create-data-file.adoc
- stories/topics/proc-gcp-deleting-backups-playbook.adoc
- stories/topics/proc-gcp-generate-restore-yml-file.adoc
- stories/topics/proc-gcp-generate-upgrade-data-file.adoc
- stories/topics/proc-gcp-generate-variables.adoc
- stories/topics/proc-gcp-listing-backups-playbook.adoc
Cross references to the technical note module were failing because they used the module title instead of the module ID.
Affects `/titles/aap-on-gcp`.
> Fix xrefs to technical note

- bin/sync_cloud_docs.sh
Modify Jenkins script for aap-clouds-2.3:
Delete references to Azure, as the 2.3 page on the Customer portal will only show docs for self-managed AoC.
> aap-clouds-2.3 Modify Jenkins sync script

- archive/archived-topics/proc-gcp-extension-nodes.adoc
`topics/proc-gcp-extension-nodes.adoc` was deleted in PR #224 
Restore it to the archive.
> 2.4 Restore proc-gcp-extension-nodes.adoc to archive

- aap-common/ref-aap-using-playbooks.adoc
Couldn't find duplicate, moved one into a more sensible position
GCP Doc: the gcp_check_aoc_version playbook was documented twice in the Chapter 7.6
https://issues.redhat.com/browse/AAP-14549
> Tidied list of playbooks

- aap-common/proc-aap-pull-command-container-image.adoc
- stories/topics/con-aws-pull-container-image.adoc
- stories/topics/con-aws-pull-deploy-container-image.adoc
- stories/topics/con-gcp-pull-deploy-container-image.adoc
- stories/topics/con-gcp-pull-remove-container-image.adoc
- stories/topics/con-gcp-use-container-image.adoc
- stories/topics/proc-aws-set-container-image.adoc
- stories/topics/proc-aws-upgrade-pull-container-image.adoc
- stories/topics/proc-gcp-backup-container-image.adoc
- stories/topics/proc-gcp-upgrade-pull-container-image.adoc
Also removes emea ops image, as this is no longer necessary and it is not being published.
https://issues.redhat.com/browse/AAP-14163
This issue updates our image reference in our documentation to be our expected image reference once published
> Update RHEL suffix to rhel9 from rhel8

- aap-common/assembly-appendix-release-notes.adoc
- stories/assembly-aws-intro.adoc
- stories/assembly-gcp-intro.adoc
- stories/assembly-gcp-upgrade.adoc
- stories/topics/con-aws-application-architecture.adoc
- stories/topics/con-aws-upgrade-backup-process.adoc
- stories/topics/con-gcp-application-architecture.adoc
- stories/topics/con-gcp-upgrade-backup-process.adoc
- stories/topics/con-gcp-upgrade-upgrading.adoc
https://issues.redhat.com/browse/AAP-14166
Fixes Intro formatting to ensure at same level for both AWS/GCP - 
Also fixes AWS/GCP upgrade navigation bar steps, to ensure they are formatted correctly -
> Doc formatting fixes

- stories/topics/proc-gcp-deploying-extension-nodes.adoc
This PR adds a note to documentation - [section 2.6 of Red Hat Ansible Automation Platform from GCP Marketplace Guide ](https://dxp-docp-prod.apps.ext-waf.spoke.prod.us-west-2.aws.paas.redhat.com/documentation/en-us/ansible_on_clouds/2.4/html-single/red_hat_ansible_automation_platform_from_gcp_marketplace_guide/index?lb_target=preview&check_logged_in=1#proc-gcp-deploying-extension-nodes)about handling UI error when selecting network options.
JIRA: https://issues.redhat.com/browse/AAP-14124
> Update doc to add note for handling networking ui error

- downstream/titles/release-notes/topics/new-features-oct-2020.adoc
- downstream/titles/release-notes/topics/tower-intro-382.adoc
AAP-15176 fixes broken links in release notes
This PR backports changes from [PR 1308](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1308) to the 2.4 branch. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> Backport to 2.4: AAP-15176 fixes broken links in release notes (#1308)

- release-notes/topics/new-features-oct-2020.adoc
- release-notes/topics/tower-intro-382.adoc
This PR backports changes from [PR 1308](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1308) to the 2.3 branch. See AAP-15176 for more info.
> AAP-15176: fix broken links in release notes v 2.3

- release-notes/topics/new-features-oct-2020.adoc
- release-notes/topics/tower-intro-382.adoc
This PR backports changes from [PR 1308](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1308) to the 2.3 branch. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> Backport to 2.2: AAP-15176 fix broken links in release notes v2.2

- downstream/modules/platform/con-aap-upgrade-prereq.adoc
- downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
This PR fixes broken links in the Upgrade and Migration Guide. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> AAP-15176 Fix broken links in Upgrade and Migration Guide

- downstream/modules/platform/con-aap-upgrade-prereq.adoc
- downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
- downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
This PR backports changes in [PR 279](https://github.com/ansible/aap-docs/pull/279) to the 2.4 branch. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> Backport to 2.4: AAP-15176 fix broken links in Upgrade and Migration Guide

- downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
- downstream/modules/platform/con-aap-upgrade-prereq.adoc
- downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
This PR backports changes in [PR 279](https://github.com/ansible/aap-docs/pull/279) to the 2.3 branch. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> Backport to 2.3: AAP-15176 Fix broken links in Upgrade and Migration Guide (#279)

- downstream/assemblies/central-auth/assembly-central-auth-add-user-storage.adoc
Migrates [PR#1311 from the RedHatInsights repo](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1311) to 2.3.
…Admin Guide (#1311)
* AAP-3481 Added new note and link to Chapt 8.4 in the Server Admin Guide (#1234)
AAP-3481 Added new note and link about LDAP group mappings in chpt 8.4 in Server Admin Guide
* Backport-2.3-1234 Added note to chapter 2 and links to the RHSSO Server Admin Guide
* Backport-2.3-1234 Added note to chapter 2 and links to the RHSSO Server Admin Guide
* Backport-2.3-1234 Added note to chapter 2 and links to the RHSSO Server Admin Guide
* Backport-2.3-1234 Added note to chapter 2 and links to the RHSSO Server Admin Guide
* Backport-2.3-1234 Added note to chapter 2 and links to the RHSSO Server Admin Guide
* Backport-2.3-1234 …
> 2.3 Added new note and link to Chapt 8.4 in the Server (RedHatInsights)

- downstream/modules/eda/proc-eda-activate-webhook.adoc
Updating route to be HTTPS and job name to append the port
Route needs updating to properly work for EDA
https://issues.redhat.com/browse/AAP-15433
> Updating route for webhook rulebooks

- downstream/modules/eda/proc-eda-activate-webhook.adoc
Updating route to be HTTPS and job name to append the port
Route needs updating to properly work for EDA
https://issues.redhat.com/browse/AAP-15433
> Updating route for webhook rulebooks (#295)

- downstream/modules/aap-hardening/con-credential-management-planning.adoc
Fix an xref in an aap-hardening module: In the xref, include the context from the assembly that contains the module that's referenced.
> Add context to xref in aap-hardening module

- aap-common/assembly-appendix-release-notes.adoc
- stories/assembly-gcp-monitoring-logging.adoc
This PR adds a note to documentation - [Chapter 9: Logging and Monitoring ](https://dxp-docp-prod.apps.ext-waf.spoke.prod.us-west-2.aws.paas.redhat.com/documentation/en-us/ansible_on_clouds/2.4/html-single/red_hat_ansible_automation_platform_from_gcp_marketplace_guide/index?lb_target=preview&check_logged_in=1#assembly-gcp-monitoring-logging) regarding logging and monitoring deprecation in future release. 
Jira: https://issues.redhat.com/browse/AAP-15317
> Update GCP doc to add deprecation note for logging and monitoring

- downstream/modules/aap-hardening/con-automation-credentials.adoc
- downstream/modules/aap-hardening/con-credential-management-planning.adoc
- downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
- downstream/modules/aap-hardening/ref-dns-load-balancing.adoc
- downstream/modules/aap-hardening/ref-private-automation-hub-authentication.adoc
2.4 Backport for [PR324](https://github.com/ansible/aap-docs/pull/324)
Re [AAP-14809](https://issues.redhat.com/browse/AAP-14809), revisions for the following files:
con-automation-credentials.adoc
con-credential-management-planning.adoc
ref-automation-controller-authentication.adoc
ref-dns-load-balancing.adoc
ref-private-automation-hub-authentication.adoc
Comments and suggested changes resolved in[ Google doc](https://docs.google.com/document/d/1A6VLRNEzvKw4GWhcQpIMpSN9ylFpMGsGLeIUU-7p19I/edit)
> AAP-14809-2.1-a updated sections 2.1.3-2.1.5 (#324)

- downstream/modules/platform/proc-approving-the-imported-collection.adoc
This PR fixes a broken link to the automation hub console in the Installation Guide. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more details.
> AAP-15176: fixes broken link in the Installation Guide

- downstream/modules/platform/proc-approving-the-imported-collection.adoc
This PR backports the changes from [PR 326](https://github.com/ansible/aap-docs/pull/326) to the 2.3 branch. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more infoo.
> Backport to 2.3: AAP-15176: fixes broken link in the Installation Guide

- downstream/modules/platform/proc-approving-the-imported-collection.adoc
This PR backports the changes in [PR 326](https://github.com/ansible/aap-docs/pull/326) to 2.4. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> Backport to 2.4: AAP-15176: fixes broken link in the Installation Guide

- downstream/modules/platform/ref-hub-variables.adoc
Corrected typo in Ansible automation hub variables section of AAP installation guide
[DDF] This looks like a tyop (should be search, rather than seach)?
https://issues.redhat.com/browse/AAP-14834
> Correct typo in installation guide

- downstream/modules/platform/ref-hub-variables.adoc
Corrected typo in Ansible automation hub variables section of AAP installation guide
[DDF] This looks like a tyop (should be search, rather than seach)?
https://issues.redhat.com/browse/AAP-14834
> Correct typo in installation guide (#348)

- downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
- downstream/modules/platform/proc-configure-controller-OCP.adoc
- downstream/titles/ocp_performance_guide/master.adoc
Adding chapter for configuring controller on OCP to minimize outage during upgrade
Document best practices and configuration requirement for tolerating k8s upgrade
https://issues.redhat.com/browse/AAP-12903
Affects `titles/ocp_performance-guide`
> Configuring automation controller on OCP

- downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
- downstream/modules/platform/proc-configure-controller-OCP.adoc
- downstream/titles/ocp_performance_guide/master.adoc
* Configuring automation controller on OCP
Adding chapter for configuring controller on OCP to minimize outage upgrade
Document best practices and configuration requirement for tolerating k8s upgrade
https://issues.redhat.com/browse/AAP-12903
Affects `titles/ocp_performance-guide`
* Edits per technical review
* Edit as per peer review
> Configuring automation controller on OCP (#278)

- downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
- downstream/modules/platform/proc-configure-controller-OCP.adoc
- downstream/titles/ocp_performance_guide/master.adoc
* Configuring automation controller on OCP
Adding chapter for configuring controller on OCP to minimize outage upgrade
Document best practices and configuration requirement for tolerating k8s upgrade
https://issues.redhat.com/browse/AAP-12903
Affects `titles/ocp_performance-guide`
* Edits per technical review
* Edit as per peer review
> Configuring automation controller on OCP (#278) (#352)

- downstream/assemblies/platform/assembly-aap-manifest-files.adoc
This PR fixes a broken link in the 2.3 version of the Operations Guide. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> AAP-15176: fixes broken link in operations guide v2.3

- downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
This PR fixes a broken link in the 2.3 version of the automation mesh guide. See [AAP 15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> AAP-15176: fixes broken link in automation mesh guide v2.3

- downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
Link to Jira issue: [AAP-15836](https://issues.redhat.com/browse/AAP-15836)
Section **2.3.2.1 Configure centralized logging**
- Changed `var/log/awx` to `var/lib/awx`
- Changed `<FQDN>` to `<automation controller server>
- Removed reference to "button" in line 34
`
> [2.4] AAP-15836: Removed reference to the word button (#367)

- downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
- downstream/modules/platform/ref-hub-configs.adoc
Fixes a link in v2.2 of Installation Guide table 2.4 and a formatting issue in the appendix. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for further detail.
> Link fix and formatting fix in Installation Guide v2.2

- downstream/modules/platform/proc-installing-ansible-core.adoc
- downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
Fixes a title and codeblock indentation.
Affects `titles/aap-containerized-install`
> Fix formatting and title in containerized install doc

- downstream/modules/platform/proc-installing-ansible-core.adoc
- downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
Backports #377 to 2.4
Fixes a title and codeblock indentation.
Affects `titles/aap-containerized-install`
> Fix formatting and title in containerized install doc (#377)

- downstream/assemblies/hub/assembly-user-access.adoc
This PR includes an assembly that was missed in the Getting started guide and updates some leveloffsets to correct topic nesting.
> AAP15779 - adding missing assembly

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Change link description attribute from "ControllerName" to "HubName" in Installing Red Hat Ansible Automation Platform guide.
[DDF] This should be "Single automation hub with external (customer provided) database"
https://issues.redhat.com/browse/AAP-15760
> Replace link description of automation controller with automation hub

- downstream/assemblies/eda/assembly-eda-credentials.adoc
- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
- downstream/modules/eda/con-credentials-list-view.adoc
- downstream/modules/eda/proc-eda-delete-credential.adoc
- downstream/modules/eda/proc-eda-edit-credential.adoc
- downstream/modules/eda/proc-eda-set-up-credential.adoc
- downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
- downstream/modules/eda/proc-eda-set-up-new-project.adoc
- downstream/titles/eda/eda-user-guide/docinfo.xml
- downstream/titles/eda/eda-user-guide/master.adoc
Adding Chapter 2. Setting up credentials for Event-Driven Ansible controller
[DOCS][EDA] missing section and a wrong link for EDA credentials
https://issues.redhat.com/browse/AAP-16054
> Adding Credentials chapter to EDA user guide

- downstream/assemblies/eda/assembly-eda-credentials.adoc
- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
- downstream/modules/eda/con-credentials-list-view.adoc
- downstream/modules/eda/proc-eda-delete-credential.adoc
- downstream/modules/eda/proc-eda-edit-credential.adoc
- downstream/modules/eda/proc-eda-set-up-credential.adoc
- downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
- downstream/modules/eda/proc-eda-set-up-new-project.adoc
- downstream/titles/eda/eda-user-guide/docinfo.xml
- downstream/titles/eda/eda-user-guide/master.adoc
* Adding Credentials chapter to EDA user guide
Adding Chapter 2. Setting up credentials for Event-Driven Ansible controller
[DOCS][EDA] missing section and a wrong link for EDA credentials
https://issues.redhat.com/browse/AAP-16054
* Edits as per peer review
> Adding Credentials chapter to EDA user guide (#409)

- downstream/assemblies/platform/assembly-system-requirements.adoc
- downstream/modules/platform/ref-eda-system-requirements.adoc
- Added a new module "Event-Driven Ansible controller system requirements" to both the Installation and Planning guides.
- This was added to the assembly for the overall system requirements chapter (Chapter 4 in the Planning Guide and Chapter 2 in the Installation Guide)
> Backport-2.4-398 AAP-13785 New minimum requirement for EDA controller section

- downstream/modules/platform/con-why-migrate-ansible-core-212.adoc
- downstream/modules/platform/con-why-migrate-ansible-core-213.adoc
This PR fixes some broken link formatting in the Installation Guide v2.2. See [AAP 15176](https://issues.redhat.com/browse/AAP-15176) for context.
> AAP-15176: fixes link formatting in 2.2 version of install guide

- downstream/modules/platform/con-pod-specification-mods.adoc
This PR fixes one instance of incorrect xref formatting in the Performance considerations for operator based installations guide. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for context.
> AAP-15176: fixes xref formatting in ocp guide

- downstream/modules/platform/con-pod-specification-mods.adoc
This PR backports the changes in [PR 471](https://github.com/ansible/aap-docs/pull/471) to the 2.4 release. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for context.
> AAP-15176: fixes xref formatting in ocp guide (#471)

- downstream/assemblies/platform/assembly-install-upgrade-pah.adoc
- downstream/modules/central-auth/proc-aap-configure-centralauth.adoc
Correct typo with variable from automation_pg_password to automationhub_pg_password
[DDF] I'm not sure this is the correct parameter to use? Should it not be automationHUB_pg_password?
https://issues.redhat.com/browse/AAP-16095
> Correct variable typo for automationhub_pg_password

- downstream/modules/central-auth/proc-aap-configure-centralauth.adoc
- downstream/titles/hub/install/master.adoc
Correct typo with variable from automation_pg_password to automationhub_pg_password
[DDF] I'm not sure this is the correct parameter to use? Should it not be automationHUB_pg_password?
https://issues.redhat.com/browse/AAP-16095
> Correct variable typo for automationhub_pg_password (#481)

- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Adding a note under the `execution environments` field regarding the pull policy
[DOCS] Chapter 6.1 of the user guide should have a note regarding the pull policy
https://issues.redhat.com/browse/AAP-16401
> [EDA] Adding pull policy admonition

- downstream/modules/platform/con-install-scenario-examples.adoc
- downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
- downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Replace typos FDQN with correct abbreviation FQDN
[DDF] Inventory requires FQDN ?
https://issues.redhat.com/browse/AAP-15819
> Correct typo of FQDN abbreviation

- downstream/modules/platform/con-install-scenario-examples.adoc
- downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
- downstream/modules/platform/ref-guidelines-hosts-groups.adoc
* Correct typo of FQDN abbreviation
Replace typos FDQN with correct abbreviation FQDN
[DDF] Inventory requires FQDN ?
https://issues.redhat.com/browse/AAP-15819
* Implement feedback based on peer-review
> Correct typo of FQDN abbreviation (#496)

- downstream/modules/platform/ref-aap-containerized-dns-config.adoc
Correct broken link to "Setting up an unbound DNS server - Red Hat Enterprise Linux 9"
[DDF] Link is broken
https://issues.redhat.com/browse/AAP-16502
> Correct broken link typo in Containerized AAP Installation Guide

- downstream/modules/platform/ref-aap-containerized-dns-config.adoc
* Correct broken link typo in Containerized AAP Installation Guide
Correct broken link to "Setting up an unbound DNS server - Red Hat Enterprise Linux 9"
[DDF] Link is broken
https://issues.redhat.com/browse/AAP-16502
* Update link to Controller instead of Tower user guide based on feedback
> Correct broken link typo in Containerized AAP Installation Guide (#509)

- downstream/modules/platform/ref-system-requirements.adoc
This PR backports the changes from #523 to the 2.4 branch and includes the following:
* AAP-15839 - replaced information in system requirements section with link to planning guide
* AAP-15839 - fixed link to specify the table for automation hub
> AAP-15839 [Backport] - replaced information in system requirements section with link

- lightspeed/titles/lightspeed-user-guide/master.adoc
Add placeholders for assemblies in main doc.
The idea is that you un-comment one line, fix the assembly name, and create a PR to merge that new assembly.
This is to facilitate the process whereby you use one PR per assembly.
> Lightspeed: Add placeholders for assemblies in main doc

- downstream/assemblies/platform/assembly-install-aap-operator.adoc
Correct typos in assembly-install-aap-operator.adoc
[DDF] Typo, please correct
https://issues.redhat.com/browse/AAP-16825
> Correct typo in prereqs section of Installing AAP operator on OCP guide

- downstream/assemblies/hub/assembly-collection-import-export.adoc
- downstream/assemblies/hub/assembly-remote-management.adoc
- downstream/assemblies/hub/assembly-repo-management.adoc
- downstream/modules/hub/con-approval-pipeline.adoc
- downstream/modules/hub/con-repo-rbac.adoc
- downstream/modules/hub/proc-adding-collections-repository.adoc
- downstream/modules/hub/proc-basic-repo-sync.adoc
- downstream/modules/hub/proc-create-remote.adoc
- downstream/modules/hub/proc-create-repository.adoc
- downstream/modules/hub/proc-export-collection.adoc
- downstream/modules/hub/proc-import-collection.adoc
- downstream/modules/hub/proc-provide-remote-access.adoc
- downstream/modules/hub/proc-revert-repository-version.adoc
This PR backports the changes from [PR 559](https://github.com/ansible/aap-docs/pull/559) to the 2.4 release.
> AAP 15795: Editorial changes to Managing Content  (#559)

- downstream/modules/platform/ref-guidelines-hosts-groups.adoc
- downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
Created a new section, Event-Driven Ansible controller, under heading [8.1. Guidelines for hosts and groups](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_planning_guide/about_the_installer_inventory_file#ref-guidelines-hosts-groups).
> AAP-13758 EDA Installation information for hosts and groups

- downstream/modules/platform/ref-guidelines-hosts-groups.adoc
- downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
Created a new section, Event-Driven Ansible controller, under heading [8.1. Guidelines for hosts and groups](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_planning_guide/about_the_installer_inventory_file#ref-guidelines-hosts-groups) in the AAP Planning Guide.
Added an additional "Important" admonition to section [3.1.1.6 Single Event-Driven Ansible controller node with internal database](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-single-eda-controller-with-internal-db_platform-install-scenario) in the AAP Installation Guide.
> Backport AAP-13758 EDA Installation information for hosts and groups

- downstream/modules/hub/proc-add-user-to-group.adoc
- downstream/modules/hub/proc-assigning-permissions.adoc
- downstream/modules/hub/proc-create-groups.adoc
Adding links from the Managing content guide to the Getting started guide, to avoid duplication of content
[HubDocathon] Link duplicate topics from Managing content guide to the Getting started guide
https://issues.redhat.com/browse/AAP-16028
Affects `titles/hub/managing-content`
> Link duplicate topics in hub documentation

- downstream/modules/hub/proc-add-user-to-group.adoc
- downstream/modules/hub/proc-assigning-permissions.adoc
- downstream/modules/hub/proc-create-groups.adoc
Adding links from the Managing content guide to the Getting started guide, to avoid duplication of content
[HubDocathon] Link duplicate topics from Managing content guide to the Getting started guide
https://issues.redhat.com/browse/AAP-16028
Affects `titles/hub/managing-content`
> Link duplicate topics in hub documentation (#584)

- downstream/archive/archived-modules/platform/ref-network-ports-protocols.adoc
- downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Update GalaxyNG S3 URL to reflect the new URL
[DDF] With the recent release of GalaxyNG, the new S3 URL is: https://ansible-galaxy-ng.s3.dualstack.us-east-1.amazonaws.com
https://issues.redhat.com/browse/AAP-16874
> Update GalaxyNG S3 URL

- downstream/archive/archived-modules/platform/ref-network-ports-protocols.adoc
- downstream/assemblies/platform/assembly-network-ports-protocols.adoc
* Update GalaxyNG S3 URL
Update GalaxyNG S3 URL to reflect the new URL
[DDF] With the recent release of GalaxyNG, the new S3 URL is: https://ansible-galaxy-ng.s3.dualstack.us-east-1.amazonaws.com
https://issues.redhat.com/browse/AAP-16874
* Update based on peer review feedback
> Update GalaxyNG S3 URL (#596)

- downstream/modules/platform/proc-using-postinstall.adoc
Separate one code block into two to make it easier to copy relevant information
[DDF] This should be a separate code block so you can actually copy paste it in your terminal.
https://issues.redhat.com/browse/AAP-16743
> Break out code blocks for easier copying of config details

- downstream/modules/platform/proc-using-postinstall.adoc
Separate one code block into two to make it easier to copy relevant information [DDF] This should be a separate code block so you can actually copy paste it in your terminal. https://issues.redhat.com/browse/AAP-16743
> Break out code blocks for easier copying of config details (#612)

- lightspeed/titles/lightspeed-release-notes/master.adoc
- lightspeed/titles/lightspeed-user-guide/master.adoc
Removes intro assembly from release notes master.adoc
Removes empty assemblies from user guide master.adoc
We will add back the assemblies when they are ready.
> Updates master.adocs so they will build

- downstream/titles/release-notes/attributes
- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/aap-24.adoc
- downstream/titles/release-notes/topics/controller-440.adoc
- downstream/titles/release-notes/topics/docs-24.adoc
- downstream/titles/release-notes/topics/eda-24.adoc
- downstream/titles/release-notes/topics/errata-24-aug-10.adoc
- downstream/titles/release-notes/topics/errata-24-aug-28.adoc
- downstream/titles/release-notes/topics/errata-24-jul-26.adoc
- downstream/titles/release-notes/topics/errata-24-sep-12.adoc
- downstream/titles/release-notes/topics/errata-24-sep-24.adoc
- downstream/titles/release-notes/topics/hub-464.adoc
- downstream/titles/release-notes/topics/operator-240.adoc
- downstream/titles/release-notes/topics/platform-intro.adoc
- downstream/titles/release-notes/topics/upgrading.adoc
* Add bundle errata releases to 2.4 release notes
Add the Ansible bundle errata releases to the 2.4 Release Notes
https://issues.redhat.com/browse/AAP-16768
* Update release notes based on peer review feedback
Update release notes based on peer review feedback including: added attributes symlink, replaced relevant keywords with attributes, various spelling & grammar updates, & updates to improve clarity.
Add the Ansible bundle errata releases to the 2.4 Release Notes
https://issues.redhat.com/browse/AAP-16768
> Add bundle errata releases to 2.4 release notes (#578)

- lightspeed/titles/lightspeed-release-notes/master.adoc
To fix build problems for lightspeed release notes, move the inclusivity statement below the title in master.adoc
> Lightspeed: Move inclusivity statement below title

- downstream/modules/platform/ref-postgresql-requirements.adoc
This PR backports the changes from #641 to the 2.4 branch.
> AAP-15671 - [Backport] Removed controller and hub from the postgresql requirements table (#641)

- downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
- Corrected the code sample, per advice from SMEs in jira comments.
- Also, removed the Important admonition stating, "Automation controller must be installed before you populate the inventory file with the following Event-Driven Ansible variables." Per SME, a partner, and a customer, this is not true. We were told to add this note months ago.
> AAP-15899 Updated EDA controller scenario in installation guide

- downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
- Corrected the code sample in the Installation Guide, section 3.1.1.6, per advice from SMEs in jira comments.
- Also, removed the Important admonition stating, "Automation controller must be installed before you populate the inventory file with the following Event-Driven Ansible variables." Per SME, a partner, and a customer, this is not true. We were told to add this note months ago.
> Backport 2.4 685 AAP-15899 Updated EDA controller scenario in installation guide

- downstream/assemblies/platform/assembly-planning-installation.adoc
- downstream/attributes/attributes.adoc
Add RHEL (Red Hat Enterprise Linux) attribute to the docs for quick reference
Add an attribute for RHEL to the aap-docs repo
https://issues.redhat.com/browse/AAP-17745
> Add RHEL attribute to the docs

- downstream/assemblies/platform/assembly-planning-installation.adoc
- downstream/attributes/attributes.adoc
Add RHEL (Red Hat Enterprise Linux) attribute to the docs for quick reference
Add an attribute for RHEL to the aap-docs repo
https://issues.redhat.com/browse/AAP-17745
> Add RHEL attribute to the docs (#711)

- downstream/modules/hub/proc-configure-automation-hub-server-cli.adoc
Update galaxy server url in example to include 'content/rh-certified/'
[DDF] When mirroring rh-certified or community repositories, the url for the Private Automation Hub must be:
https://issues.redhat.com/browse/AAP-17372
> Update galaxy server url in example

- downstream/modules/hub/proc-configure-automation-hub-server-cli.adoc
Update galaxy server url in example to include 'content/rh-certified/'
[DDF] When mirroring rh-certified or community repositories, the url for the Private Automation Hub must be:
https://issues.redhat.com/browse/AAP-17372
> Update galaxy server url in example (#728)

- downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
- downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
Added "Important" admonition to the Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform, Chapter 6, informing customers that they should give their EDA controller a different name if they are deploying it in the same namespace as other AAP  components. 
(Note to ask Christian Adams: Do we inform the customer where they should do this renaming? It doesn't seem to be in the contents of Chapter 6 where we talk about deploying EDA on OCP. I might be missing something. Please advise.)
> AAP-14288 Added an admonition about creating a different name for EDA controller

- downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
- downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
- Added "Important" admonition to the Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform, Chapter 6, informing customers that they should give their EDA controller a different name if they are deploying it in the same namespace as other AAP components.
- Also, per @rooftopcellist, added a new step to specify name for EDA controller that's distinct from OpenShift Container Platform namespace
> Backport-2.4-725 (for AAP-14288) Added an admonition about creating a different name for EDA controller

- bin/sync_cloud_docs.sh
Add a new book for GCP release notes.
- This PR does not modify the release notes content. It includes the release notes assembly from the current GCP guide as a temporary measure to test the docs build.
- It modifies the script that syncs to the Gitlab production repo.
Additional tasks: 
- Add master.adoc and docinfo.xml to the production repo - DONE (PR-28)
- Create a title in Pantheon - DONE
> Clouds: Add GCP release notes book to Clouds docs

- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/bundle-installer-24-24.adoc
Add bundle installer release 2.4-2.4 updates to AAP release notes
2.4 Release Notes - AAP 2.4-2.4 Bundle Installer Release
https://issues.redhat.com/browse/AAP-18030
> Add bundle installer release 2.4-2.4 updates to AAP release notes

- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/bundle-installer-24-24.adoc
Add bundle installer release 2.4-2.4 updates to AAP release notes
2.4 Release Notes - AAP 2.4-2.4 Bundle Installer Release
https://issues.redhat.com/browse/AAP-18030
> Add bundle installer release 2.4-2.4 updates to AAP release notes (#750)

- downstream/modules/platform/con-controller-instance-groups.adoc
- downstream/modules/platform/ref-controller-audit-functionality.adoc
Adding info on disassociating control plane instance groups
Unable to associate or disassociate instances from Control Plane Instance Group
https://issues.redhat.com/browse/AAP-15717
> Add info for control plane instance groups

- downstream/modules/platform/con-controller-instance-groups.adoc
- downstream/modules/platform/ref-controller-audit-functionality.adoc
* Add info for control plane instance groups
Adding info on disassociating control plane instance groups
Unable to associate or disassociate instances from Control Plane Instance Group
https://issues.redhat.com/browse/AAP-15717
> Add info for control plane instance groups (#763)

- downstream/titles/release-notes/topics/bundle-installer-24-11.adoc
- downstream/titles/release-notes/topics/bundle-installer-24-12.adoc
Remove Operator related release items from bundle installer release notes. These will be added at a later date in their own section.
Remove Operator related release items from bundle installer releases in AAP Release Notes
https://issues.redhat.com/browse/AAP-18174
> Remove Operator related items from bundle installer release notes

- downstream/titles/release-notes/topics/bundle-installer-24-11.adoc
- downstream/titles/release-notes/topics/bundle-installer-24-12.adoc
Remove Operator related release items from bundle installer release notes. These will be added at a later date in their own section. https://issues.redhat.com/browse/AAP-18174
> Remove Operator related items from bundle installer release notes (#768)

- downstream/modules/platform/ref-hub-variables.adoc
[DDF] An LDAPSearch object that finds all LDAP groups that users might belong to. If your configuration makes any references
https://issues.redhat.com/browse/AAP-16762
> Added ldap variables to hub variables

- downstream/modules/platform/proc-projects-using-collections-with-hub.adoc
Broken link in Automation Controller User Guide
https://issues.redhat.com/browse/AAP-18279
> Fixing broken link in controller user guide

- downstream/modules/platform/proc-projects-using-collections-with-hub.adoc
* Fixing broken link in controller user guide
Broken link in Automation Controller User Guide
https://issues.redhat.com/browse/AAP-18279
* Second commit, fixing broken links in controller UG
* Third commit, editing link title
> Fixing broken link in controller user guide (#789)

- aap-common/proc-aap-list-available-playbooks.adoc
- aap-common/proc-aap-playbooks.adoc
- aap-common/ref-aap-using-playbooks.adoc
This PR updates GCP documentation to reflect replacement of `gcp_add_labels` and `gcp_remove_labels` playbooks with `gcp_manage_labels`  that handles both the functionalities in a unified playbook.
Jira for reference: https://issues.redhat.com/browse/AAP-18317
> Update GCP documentation for gcp_manage_labels playbook

- downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
Added an admonition to section "[3.1.1.7 Single Event-Driven Ansible controller node with internal database](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_installation_guide/index#ref-single-eda-controller-with-internal-db_platform-install-scenario)" in the AAP Installation Guide.
> AAP-15692 Single EDA controller with internal database requires minimum automation controller 2.4

- README.adoc
- aap-common/proc-aap-list-available-playbooks.adoc
- aap-common/proc-aap-pull-command-container-image.adoc
- attributes/attributes.adoc
- stories/assembly-gcp-release-notes-24.adoc
- stories/assembly-gcp-upgrade.adoc
- stories/topics/con-gcp-pull-deploy-container-image.adoc
- stories/topics/con-gcp-pull-remove-container-image.adoc
- stories/topics/con-gcp-restore-process.adoc
- stories/topics/con-gcp-upgrade-backup-process.adoc
- stories/topics/con-gcp-use-container-image.adoc
- stories/topics/proc-gcp-backup-container-image.adoc
- stories/topics/proc-gcp-pull-backup-container-image.adoc
- stories/topics/proc-gcp-restore-container-image.adoc
- stories/topics/proc-gcp-running-upgrade.adoc
- stories/topics/proc-gcp-upgrade-pull-container-image.adoc
- stories/topics/ref-gcp-release-notes-2-2-20230215-00.adoc
- stories/topics/ref-gcp-release-notes-2-3-20230221-00.adoc
- stories/topics/ref-gcp-release-notes-2-4-20230630-00.adoc
- stories/topics/ref-gcp-release-notes-2-4-20231024-00.adoc
- titles/release-notes-gcp/stories.adoc
Backports #838 to aap-clouds-2.4 branch:
* Add content for 2.4.20231024-00 GCP release notes (#741)
* Update GCP SMAC version to ops image version mapping to allow multipl… (#748)
* Update GCP SMAC version to ops image version mapping to allow multiple micro versions in each major.minor version
* add more info on figuring out current SMAC version
* Point restore and backup to the newer info on figuring out the aoc version and ops image to use
> Clouds-2.4: Add GCP release notes (#838)

- downstream/modules/platform/proc-configuring-discovery.adoc
Adding command for restarting controller when configuring websocket
Documentation for "Websocket configuration" does not list command to restart the controller service
https://issues.redhat.com/browse/AAP-18715
Affects `titles/aap-operations-guide`
> Adding step for controller websocket configuration (#860)

- downstream/modules/platform/ref-controller-variables.adoc
Commenting out postgres_max_connections inventory variable until controller 4.5 released.
Affects `/titles/aap-installation-guide/`
> Commenting postgres_max_connections variable until controller 4.5 released

- downstream/modules/platform/ref-ansible-inventory-variables.adoc
- downstream/modules/platform/ref-controller-variables.adoc
- downstream/modules/platform/ref-eda-controller-variables.adoc
- downstream/modules/platform/ref-general-inventory-variables.adoc
- downstream/modules/platform/ref-hub-variables.adoc
Backports the following commits to 2.4:
- #488 
- #801 
- #867 
Affects titles/aap-installation-guide
- Adds an inventory variable (`postgres_max_connections `) to controller, but this is only valid for controller v 4.5
- Implements editorial changes to installation guide
- Comments out `postgres_max_connections` - uncomment this when controller 4.5 is released.
> AAP install Guide editorial revamp and controller 4.5 variable (#488)(#801)(#867)

- downstream/titles/release-notes/topics/aap-24.adoc
Update release notes to include GA of AAP on IBM Power, IBM Z, and IBM LinuxONE architectures
Updating release notes documentation for the GA of AAP on Power and Z
https://issues.redhat.com/browse/AAP-16503
> Update release notes to include GA of AAP on Power and Z

- lightspeed/assemblies/assembly_assigning-seat-licenses.adoc
- lightspeed/modules/proc_remove-seat-licenses.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-18404.
Changes:
- Added info. about removing Lightspeed licenses for deactivated RH-SSO users.
> AAP-18404: Added info. about removing licenses for deactivated users

- downstream/modules/platform/con-aap-upgrade-planning.adoc
Added a new discrete heading to [Chapter 2.1 in the RH AAP Upgrade and Migration Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_upgrade_and_migration_guide/index#aap-upgrade-planning_aap-upgrading-platform) that informs the customer to stop all activations before beginning the upgrade process if they plan to deploy EDA, per proposal from SMEs.
> AAP-14712 Add content to upgrade/migration guide for disabling activations for EDA

- downstream/modules/platform/con-aap-upgrade-planning.adoc
Added a new discrete heading to [Chapter 2.1 in the RH AAP Upgrade and Migration Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_upgrade_and_migration_guide/index#aap-upgrade-planning_aap-upgrading-platform) that informs the customer to stop all activations before beginning the upgrade process if they plan to deploy EDA, per proposal from SMEs.
> Added content to stop EDA activations before upgrade to AAP 2.4

- downstream/modules/platform/proc-controller-create-job-template.adoc
Fixing broken link in Job templates section
Documentation for "Job templates" refer to a wrong link for patterns in the limit section
https://issues.redhat.com/browse/AAP-18785
> Fixing broken link

- downstream/modules/platform/proc-controller-create-job-template.adoc
Fixing broken link in Job templates section
Documentation for "Job templates" refer to a wrong link for patterns in the limit section
https://issues.redhat.com/browse/AAP-18785
> Fixing broken link (#898)

- downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
Fixed broken xrefs in https://github.com/ansible/aap-docs/pull/886:
Unknown ID or title "ref-controller-web-server-tuning", used as an internal cross reference
Unknown ID or title "con-controller-job-events-processing", used as an internal cross reference
Unknown ID or title "ref-capacity-settings-control-execution", used as an internal cross reference
Unknown ID or title "con-controller-monitor-controller", used as an internal cross reference
> AAP-13268-B fixed broken xrefs in PR 886

- downstream/modules/eda/ref-eda-controller-tasks.adoc
- downstream/modules/platform/con-aap-example-architecture.adoc
- downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Completed the following:
- Replaced the EDA acronym with the attributes (spelled out) in the following 2 files that impact the **AAP Planning Guide** and **Getting started with Event-Driven Ansible**, respectively: 
- `con-aap-example-architecture.adoc`, [2.1 Example AAP Architecture](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_planning_guide/index#aap_example_architecture_planning) 
- `ref-eda-controller-tasks.adoc`, [Chapter 4, Using Event-Driven Ansible controller](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/getting_started_with_event-driven_ansible_guide/index#using-event-driven-ansible-controller)
- Replaced the EDA acronym throughout …
> AAP-18896 Remove instances of EDA acronym; replace with spelled out attributes

- downstream/modules/eda/ref-eda-controller-tasks.adoc
- downstream/modules/platform/con-aap-example-architecture.adoc
- downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Completed the following:
- Replaced the EDA acronym with the attributes (spelled out) in the following 2 files that impact the AAP Planning Guide and Getting started with Event-Driven Ansible, respectively:
- con-aap-example-architecture.adoc, [2.1 Example AAP Architecture](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_planning_guide/index#aap_example_architecture_planning)
- ref-eda-controller-tasks.adoc, [Chapter 4, Using Event-Driven Ansible controller](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/getting_started_with_event-driven_ansible_guide/index#using-event-driven-ansible-controller)
- Replaced the EDA acronym throughout …
> Backport-2.4-888 Remove instances of EDA acronym and replace w/ attribute

- downstream/modules/platform/con-aap-example-architecture.adoc
Removed any instance of EDA from 2.3 docs: 
- 4th bullet, [section 2.1 of Chapter 2. Example AAP architecture](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_planning_guide/aap_architecture#aap_example_architecture_planning).
> AAP-18896B Remove EDA or Event-Driven Ansible from 2.3 docs

- lightspeed/modules/con-lightspeed-about.adoc
- lightspeed/modules/con_lightspeed-key-features.adoc
- lightspeed/modules/con_training-data.adoc
- lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-19195. 
Changes made:
Removed 'single-tenant' references from the following files:
- titles/lightspeed-user-guide/modules/con-lightspeed-about.adoc
- titles/lightspeed-user-guide/modules/con_lightspeed-key-features.adoc
- titles/lightspeed-user-guide/modules/con_training-data.adoc
- titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc
> AAP-19195: Removed single-tenant references

- downstream/modules/platform/ref-hub-configs.adoc
Backports update from [PR 920](https://github.com/hherbly/aap-docs/pull/new/bp-2.4-install-guide-broken-links) to the 2.4 release.
See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for further detail
> bp 2.4: AAP-15176 fix broken link in installation guide (#920)

- downstream/modules/platform/con-controller-overview-details.adoc
- downstream/modules/platform/proc-controller-create-job-template.adoc
- downstream/modules/platform/ref-controller-credential-machine.adoc
- downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc
This PR ports updates from[ PR 924](https://github.com/ansible/aap-docs/pull/924) to the 2.4 release. 
* Fix broken links in controller user guide
* update based on peer review feedback
* feedback based on peer review
> Backport to 2.4: AAP-15176 Fix broken links in controller user guide (#924)

- stories/topics/proc-azure-monitor-deployment-engine.adoc
The Azure team are adding Single Sign On in the deployment driver; the login will require both the admin password and a new or existing RH account for the SSO portion.
Affects `/titles/aap-on-azure`
> Azure Add RH account sign-in to deployment engine driver

- downstream/modules/platform/con-install-scenario-recommendations.adoc
- downstream/modules/platform/proc-verify-controller-installation.adoc
- downstream/modules/platform/proc-verify-eda-controller-installation.adoc
- downstream/modules/platform/proc-verify-hub-installation.adoc
This PR addresses the change requested in https://issues.redhat.com/browse/AAP-16022 to clarify that admin is the default initial log in userid and can not be changed in the inventory file.
> AAP-16022 - updated the information to state admin is default userid

- downstream/assemblies/platform/assembly-installing-hub-operator.adoc
- downstream/modules/platform/proc-installing-hub-using-operator.adoc
- downstream/modules/platform/ref-ocp-additional-configs.adoc
This PR adds info on setting a download count configuration for automation hub on OCP. The change will appear in the Deploying the RH AAP operator on OpenShift Container Platform guide. 
See[ AAP-18088](https://issues.redhat.com/browse/AAP-18088) for further context.
> AAP-18088: adds info on download count configuration; fixes a namespace error

- downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
Fix missing link in section “4.2.1 System requirements for disconnected installation” in the installation guide
Red Hat Ansible Automation Platform Installation Guide: Link broken
https://issues.redhat.com/browse/AAP-19268
> Fix missing link in Red Hat AAP Installation Guide (#932)

- downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
This PR backports the changes from #594 to the 2.4 branch.
> [Backport] - AAP-16378 Added ldap-ca.crt for the LDAP certificate selection (#594)

- lightspeed/modules/con_overview-and-best-practices.adoc
THIs PR addresses JIRA issue https://issues.redhat.com/browse/AAP-19290.
Changes:
- Fixed typo: postgresqul-setup > postgresql-setup in file con_overview-and-best-practices.adoc.
> AAP-19290: Fixed typo in Lightspeed docs

- downstream/modules/platform/proc-controller-creating-a-user.adoc
- downstream/modules/platform/ref-controller-user-roles.adoc
- downstream/modules/platform/ref-controller-user-teams.adoc
Reference to the UI in the Teams section is incorrect
Incorrect menu selection in Controller User's Guide
https://issues.redhat.com/browse/AAP-19671
> Fixing incorrect UI in controller user guide

- downstream/modules/platform/proc-controller-creating-a-user.adoc
- downstream/modules/platform/ref-controller-user-roles.adoc
- downstream/modules/platform/ref-controller-user-teams.adoc
* Fixing incorrect UI in controller user guide
Reference to the UI in the Teams section is incorrect
Incorrect menu selection in Controller User's Guide
https://issues.redhat.com/browse/AAP-19671
> Fixing incorrect UI in controller user guide (#963)

- downstream/attributes/attributes.adoc
Group together mesh related attributes and remove duplicate automation mesh attribute: MeshName
Remove duplicate attribute for automation mesh and add AutomationMeshStart attribute
https://issues.redhat.com/browse/AAP-19776
> Remove duplicate automation mesh attribute

- downstream/attributes/attributes.adoc
Remove duplicate automation mesh attribute: MeshName
Remove duplicate attribute for automation mesh and add AutomationMeshStart attribute
https://issues.redhat.com/browse/AAP-19776
> Remove duplicate automation mesh attribute (#968)

- downstream/assemblies/builder/assembly-definition-file-breakdown.adoc
- downstream/modules/builder/con-additional-build-files.adoc
- downstream/modules/builder/con-additional-custom-build-steps.adoc
- downstream/modules/builder/con-building-definition-file.adoc
- downstream/modules/builder/con-container_file.adoc
- downstream/modules/builder/con-definition-dependencies.adoc
- downstream/modules/builder/con-galaxy-dependencies.adoc
- downstream/modules/builder/con-optional-build-command-arguments.adoc
- downstream/modules/builder/con-python-dependencies.adoc
- downstream/modules/builder/con-system-dependencies.adoc
- downstream/modules/builder/con-why-builder.adoc
- downstream/modules/builder/proc-installing-builder.adoc
- downstream/modules/builder/ref-definition-file-images.adoc
This PR ports the changes from [PR 957](https://github.com/ansible/aap-docs/pull/957) to the 2.4 release. See [AAP-17700](https://issues.redhat.com/browse/AAP-17700) for more info. 
* add prereqs to procedure for installing builder
* updates sample definition file example
* adds SME edits to definition file breakdown assembly
* formatting fix
* format fixes
* changes based on SME feedback
* fix attribute
* edits based on team member peer review
> Backport to 2.4: Updates to Builder Documentation

- downstream/modules/platform/proc-aap-controller-backup.adoc
- downstream/modules/platform/proc-aap-controller-restore.adoc
- downstream/modules/platform/proc-aap-hub-backup.adoc
This PR backports the changes from #948 to the 2.3 branch and includes the following:
* AAP-14300 Add verification steps for controller backup and restore
* AAP-14300 corrected the working for the restore setction
* AAP-14300 - Changed from text to attribute for automation controller
> [Backport] AAP-14300 Add verification steps for controller backup and restore (#948)

- downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc
- downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc
- downstream/modules/automation-hub/proc-pushing-container-images-from-your-local.adoc
2.3 backport of [PR 973](https://github.com/ansible/aap-docs/pull/973)
Updated signing script and procedures in line with [AAP-10305](https://issues.redhat.com/browse/AAP-10305)
Updated content in [Google doc](https://docs.google.com/document/d/17S1ZrkTMpFZV4Cpc9x9QqamdIKt5_SJdIhmyTkj_d40/edit)
proc-configuring-the-client-to-verify-signatures.adoc
proc-deploying-your-system-for-container-signing.adoc
proc-pushing-container-images-from-your-local.adoc
Affects `titles/hub/manage-containers`
> AAP-10305 modified hub signing procedures (#973)

- downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
This PR ports the changes from [PR 989](https://github.com/ansible/aap-docs/pull/989/files) to the 2.4 release. See [AAP-10252](https://issues.redhat.com/browse/AAP-10252) for more info.
> Backport to 2.4: AAP-10252 add note to remind user not to leave fields blank (#989)

- downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
This PR ports the changes from [PR 989](https://github.com/ansible/aap-docs/pull/989/files) to the 2.3 release. See [AAP-10252](https://issues.redhat.com/browse/AAP-10252) for more info.
> Backport to 2.3: AAP-10252 add note to remind user not to leave fields blank (#989)

- downstream/modules/builder/con-additional-build-files.adoc
- downstream/modules/builder/con-building-definition-file.adoc
- downstream/modules/builder/ref-scenario-using-authentication-ee.adoc
This PR ports the changes from [PR 980](https://github.com/ansible/aap-docs/pull/980/files) to the 2.4 release. See [AAP-17700](https://issues.redhat.com/browse/AAP-17700) for more detail. 
* attribute fix
* update addit'l build file config in section 3.2
* removed one extra space from yaml file
* edits based on SME feedback--cleaned up sample yaml
> Backport to 2.4: AAP-17700 Further updates to Builder documentation (#980)

- downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
Update bundle installer 2.4-4 release notes based on SME feedback. Change an item from Security Fix to Bug Fix.
2.4 Release Notes - AAP 2.4-4 Bundle Installer Release
https://issues.redhat.com/browse/AAP-20389
> Update bundle installer 2.4-4 release notes based on SME feedback

- downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
Update bundle installer 2.4-4 release notes based on SME feedback. Change an item from Security Fix to Bug Fix.
2.4 Release Notes - AAP 2.4-4 Bundle Installer Release
https://issues.redhat.com/browse/AAP-20389
> Update bundle installer 2.4-4 release notes based on SME feedback (#999)

- downstream/assemblies/eda/assembly-installation-eda-controller.adoc
- downstream/modules/platform/ref-eda-system-requirements.adoc
Added a note that contains a link to a KCS article that describes how to enable the cgroup v2 for RHEL 8 systems. Note included in the following docs: 
- AAP Planning Guide, [Chapter 4.4 EDA controller system requirements](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_planning_guide/platform-system-requirements#event-driven-ansible-system-requirements)
- AAP Installation Guide, [Chapter 2.4 EDA controller system requirements](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_installation_guide/index#event-driven-ansible-system-requirements)
- Getting Started with EDA, [Chapter 3.1 Installing Event-Driven Ansible controller on …
> AAP-18798 Added a note with link to article re: adding cgroup V2 enabled

- downstream/assemblies/platform/assembly-installing-hub-operator.adoc
Just adding an already existing module into the Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform doc.
[AAP-20860](https://issues.redhat.com/browse/AAP-20860)
>  adding proc-enable-hstore-extension.adoc to assembly

- downstream/assemblies/platform/assembly-installing-hub-operator.adoc
Just adding an already existing module into the Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform doc.
[AAP-20860](https://issues.redhat.com/browse/AAP-20860)
>  adding proc-enable-hstore-extension.adoc to assembly (#1020)

- downstream/assemblies/eda/assembly-installation-eda-controller.adoc
- downstream/modules/platform/ref-eda-system-requirements.adoc
Added a note that contains a link to a KCS article that describes how to enable the cgroup v2 for RHEL 8 systems. Note included in the following docs:
- AAP Planning Guide, [Chapter 4.4 EDA controller system requirements](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_planning_guide/platform-system-requirements#event-driven-ansible-system-requirements)
- AAP Installation Guide, [Chapter 2.4 EDA controller system requirements](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_installation_guide/index#event-driven-ansible-system-requirements)
- Getting Started with EDA, [Chapter 3.1 Installing Event-Driven Ansible controller on …
> Backport-2.4-1015 Added a note with link to article re: adding cgroup V2 enabled (#1015)

- downstream/modules/platform/con-install-scenario-recommendations.adoc
Removed database support statement until a decision is made about the support.
Please correct the docs for AAP2.4 state : Internal databases [database] are not supported.
https://issues.redhat.com/browse/AAP-20847
> Removed statement on database support

- downstream/modules/builder/con-about-ee.adoc
- downstream/modules/builder/con-ee-precedence.adoc
- downstream/modules/builder/proc-customize-ee-image.adoc
- downstream/modules/builder/ref-definition-file-images.adoc
Replace plain text with attribute for content in the builder module. Affects `/titles/builder` and `/titles/builder/builder`.
> Replace plain text with attribute for content in the builder module

- lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc
This PR addresses PM feedback to update First paragraph of Chapter 7 of the Ansible Lightspeed User Guide: "Your organization must have a valid Red Hat Ansible Lightspeed with IBM watsonx Code Assistant subscription to use Ansible code bot." 
It should not reference WCA. Update should be: "Your organization must have an active subscription to Red Hat Ansible Automation Platform to use Ansible code bot."
> remove-wca-prereq: Modified prereq for Ansible code bot

- downstream/modules/core/con-ansible-roles.adoc
- downstream/modules/core/con-content-collections.adoc
- downstream/modules/core/con-execution-environments.adoc
Replace plain text with attributes for content in the core module. Affects `/titles/dev-guide/core`
> Replace plain text with attributes for content in the core module

- downstream/assemblies/platform/assembly-planning-mesh.adoc
- downstream/modules/platform/con-about-automation-mesh.adoc
- downstream/modules/platform/con-automation-mesh-node-types.adoc
- downstream/modules/platform/proc-defining-node-types.adoc
- downstream/titles/automation-mesh/docinfo.xml
- downstream/titles/automation-mesh/master.adoc
Renamed the guide in the master and docinfo files, and mae some of the note changes from AAP-19132
Rename existing automation mesh guide
https://issues.redhat.com/browse/AAP-20269
> Renaming mesh guide

- downstream/modules/dev-guide/proc-create-collections.adoc
- downstream/modules/dev-guide/proc-create-role.adoc
Replace plain text with attributes for content in the dev-guide module.
- ./aap-operations-guide/platform/dev-guide
- ./upgrade/platform/dev-guide
- ./aap-operator-installation/platform/dev-guide
- ./aap-installation-guide/platform/dev-guide
- ./aap-planning-guide/platform/dev-guide
- ./automation-mesh/platform/dev-guide
- ./ocp_performance_guide/platform/dev-guide
- ./controller/controller-user-guide/platform/dev-guide
- ./controller/controller-admin-guide/platform/dev-guide
- ./controller/controller-getting-started/platform/dev-guide
- ./aap-operator-backup/platform/dev-guide
- ./aap-containerized-install/platform/dev-guide
- ./dev-guide/dev-guide
> Replace plain text with attributes for content in the dev-guide module

- downstream/modules/platform/proc-renew-ssl-cert.adoc
Add openssl commands to validate SSL certs
Need to include openssl commands to validate the custom SSL certificates for AAP/PAH
https://issues.redhat.com/browse/AAP-20776
> Add openssl commands to validate SSL certs

- downstream/modules/platform/proc-renew-ssl-cert.adoc
Add openssl commands to validate SSL certs
Need to include openssl commands to validate the custom SSL certificates for AAP/PAH
https://issues.redhat.com/browse/AAP-20776
> Add openssl commands to validate SSL certs (#1046)

- downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
- downstream/modules/hub/proc-configure-proxy-remote.adoc
- downstream/modules/hub/proc-set-community-remote.adoc
- downstream/modules/hub/proc-set-rhcertified-remote.adoc
This PR backports the changes from [PR 1019](https://github.com/ansible/aap-docs/pull/1019) to the 2.4 branch. For the initial request see [AAP-19025](https://issues.redhat.com/browse/AAP-19025).
> Bp to 2.4: AAP 19025 create procedure for updating proxy remote settings and updated link title

- downstream/modules/platform/ref-hub-variables.adoc
This PR backports the changes from [PR 784](https://github.com/ansible/aap-docs/pull/784) to the 2.4 branch. See[ AAP-18084](https://issues.redhat.com/browse/AAP-18084) for more info.
* AAP-18084 adds collection count variable to ansible automation hub variables table in appendix
* edit based on peer review feedback
> BP to 2.4: AAP-18084 adds collection count variable to ansible automation hub variables table in appendix

- downstream/modules/platform/ref-controller-credential-aap.adoc
- downstream/modules/platform/ref-controller-credential-insights.adoc
- downstream/modules/platform/ref-controller-credential-virtualization.adoc
Add 'file', 'extra_vars' and 'env' injectors for each credential type in the Documentation
https://issues.redhat.com/browse/AAP-14751
> Adding injectors information

- downstream/modules/platform/ref-controller-credential-aap.adoc
- downstream/modules/platform/ref-controller-credential-insights.adoc
- downstream/modules/platform/ref-controller-credential-virtualization.adoc
Add 'file', 'extra_vars' and 'env' injectors for each credential type in the Documentation
https://issues.redhat.com/browse/AAP-14751
> Adding injectors information (#1049)

- downstream/titles/release-notes/master.adoc
Correct heading level for installer 2.4-6 release notes
2.4 Release Notes - AAP 2.4-6 Installer Release
https://issues.redhat.com/browse/AAP-21131
> Correct heading level for installer 2.4-6 release notes

- downstream/modules/hub/proc-add-user-to-group.adoc
- downstream/modules/hub/proc-assigning-permissions.adoc
- downstream/modules/hub/proc-configure-automation-hub-server-gui.adoc
- downstream/modules/hub/proc-configure-content-signing-on-pah.adoc
- downstream/modules/hub/proc-create-api-token.adoc
- downstream/modules/hub/proc-create-credential.adoc
- downstream/modules/hub/proc-create-groups.adoc
- downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
- downstream/modules/hub/proc-shared-filesystem.adoc
- downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
```
./aap-operations-guide
./upgrade
./aap-operator-installation
./aap-installation-guide
./aap-planning-guide
./operator-mesh
./automation-mesh
./ocp_performance_guide
./controller/controller-user-guide
./controller/controller-admin-guide
./controller/controller-getting-started
./controller/controller-api-guide
./aap-operator-backup
./aap-containerized-install
./builder
./hub/managing-content
./hub/getting-started
```
> Replace plain text with attributes for content in the hub module

- downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
- downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
- downstream/assemblies/platform/assembly-controller-api-browsing-api.adoc
- downstream/assemblies/platform/assembly-controller-api-conventions.adoc
- downstream/assemblies/platform/assembly-controller-api-filter.adoc
- downstream/assemblies/platform/assembly-controller-api-pagination.adoc
- downstream/assemblies/platform/assembly-controller-api-readonly-fields.adoc
- downstream/assemblies/platform/assembly-controller-api-search.adoc
- downstream/assemblies/platform/assembly-controller-api-sorting.adoc
- downstream/assemblies/platform/assembly-controller-api-tools.adoc
- downstream/modules/platform/ref-controller-api-tools.adoc
- downstream/titles/controller/controller-api-guide/master.adoc
Adding content for section 1 as well as assemblies to master.adoc
Create section 1 of the Automation Controller API Guide
https://issues.redhat.com/browse/AAP-21361
> Create section 1 of controller API guide

- downstream/modules/platform/proc-controller-import-CA-cert-LDAP.adoc
Update to LDAP CA import steps in controller admin guide
[Docs] Ansible Controller docs refer to old Tower KB for configuring LDAPs
https://issues.redhat.com/browse/AAP-21177
> Updating LDAP CA steps

- downstream/modules/platform/proc-controller-import-CA-cert-LDAP.adoc
Update to LDAP CA import steps in controller admin guide
[Docs] Ansible Controller docs refer to old Tower KB for configuring LDAPs
https://issues.redhat.com/browse/AAP-21177
> Updating LDAP CA steps (#1080)

- downstream/modules/playbooks/ref-create-variables.adoc
See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
> AAP-15176: fixes broken links in getting started with ansible playbooks guide

- downstream/modules/playbooks/ref-create-variables.adoc
This PR backports the changes from [PR 1078](https://github.com/ansible/aap-docs/pull/1078) to the 2.4 branch. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info. 
* fixes broken links in getting started with ansible playbooks guide
* fixes incorrect capitalizations
> Backport to 2.4 - AAP-15176: fixes broken links in getting started with ansible playbooks guide (#1078)

- downstream/modules/hub/proc-create-api-token-pah.adoc
- downstream/modules/hub/proc-create-api-token.adoc
This PR ports the changes from[ PR 1077](https://github.com/ansible/aap-docs/pull/1077) to the 2.4 branch. See [AAP-20141](https://issues.redhat.com/browse/AAP-20141) for more info.
> Backport to 2.4: AAP-20141: adds note about api token never expiring (#1077)

- downstream/assemblies/platform/assembly-controller-api-conventions.adoc
- downstream/assemblies/platform/assembly-controller-api-filter.adoc
- downstream/assemblies/platform/assembly-controller-api-pagination.adoc
- downstream/assemblies/platform/assembly-controller-api-search.adoc
- downstream/assemblies/platform/assembly-controller-api-sorting.adoc
- downstream/modules/platform/proc-controller-api-browsing-api.adoc
- downstream/modules/platform/proc-controller-api-filtering.adoc
- downstream/modules/platform/proc-controller-api-sorting.adoc
- downstream/modules/platform/proc-controller-api-using-pagination.adoc
- downstream/modules/platform/ref-controller-api-advanced-queries.adoc
- downstream/modules/platform/ref-controller-api-conventions.adoc
- downstream/modules/platform/ref-controller-api-field-lookups.adoc
Adding content for sections 3, 4, 5, 6, and 7
Create sections 3, 4, 5, 6, and 7 of the Automation Controller API Guide
https://issues.redhat.com/browse/AAP-21476
> Create sections 3, 4, 5, 6, and 7 of controller API guide

- downstream/assemblies/platform/assembly-controller-api-conventions.adoc
- downstream/assemblies/platform/assembly-controller-api-filter.adoc
- downstream/assemblies/platform/assembly-controller-api-pagination.adoc
- downstream/assemblies/platform/assembly-controller-api-search.adoc
- downstream/assemblies/platform/assembly-controller-api-sorting.adoc
- downstream/modules/platform/proc-controller-api-browsing-api.adoc
- downstream/modules/platform/proc-controller-api-filtering.adoc
- downstream/modules/platform/proc-controller-api-sorting.adoc
- downstream/modules/platform/proc-controller-api-using-pagination.adoc
- downstream/modules/platform/ref-controller-api-advanced-queries.adoc
- downstream/modules/platform/ref-controller-api-conventions.adoc
- downstream/modules/platform/ref-controller-api-field-lookups.adoc
* Create sections 3, 4, 5, 6, and 7 of controller API guide
Adding content for sections 3, 4, 5, 6, and 7
Create sections 3, 4, 5, 6, and 7 of the Automation Controller API Guide
https://issues.redhat.com/browse/AAP-21476
> Create sections 3, 4, 5, 6, and 7 of controller API guide (#1094)

- downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
* Add requirement for UBI CDN FQDN
Added requirement for cdn-ubi.redhat.com
UBI CDN FQDN not listed as a requirement for EEs
https://issues.redhat.com/browse/AAP-21282
* Add requirement for UBI CDN FQDN
Correction
UBI CDN FQDN not listed as a requirement for EEs
https://issues.redhat.com/browse/AAP-21282
* Add requirement for UBI CDN FQDN
Correction from review
UBI CDN FQDN not listed as a requirement for EEs
https://issues.redhat.com/browse/AAP-21282
* Add requirements for UBI CDN FQDN
Minor correction to remove legacy entries.
Note that ^ should be AAP-21282
UBI CDN FQDN not listed as a requirement for EEs
https://issues.redhat.com/browse/AAP-21282
> Add requirement for UBI CDN FQDN (#1099)

- downstream/assemblies/navigator/assembly-review-ee-navigator.adoc
- downstream/attributes/attributes.adoc
- downstream/modules/navigator/con-navigator-collections.adoc
- downstream/modules/navigator/proc-browse-collections-tui.adoc
- downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
- downstream/modules/navigator/proc-review-ee-tui.adoc
- downstream/modules/navigator/ref-navigator-command-summary.adoc
```
./navigator-guide/navigator
./dev-guide/navigator
```
> Replace plain text with attributes for content in the navigator module

- downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
- downstream/modules/platform/ref-eda-controller-variables.adoc
- downstream/modules/platform/ref-eda-system-requirements.adoc
- downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Updates to address issue AAP-18707 include the following:
- Deploying AAP Operator on OCP guide
- [Chapter 6](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/deploy-eda-controller-on-aap-operator-ocp) in the [Deploying AAP operator on OCP guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/index).
- AAP Installation Guide
- [Chapter 2.4 Event-Driven Ansible controller system requirements](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_ins …
> Backport-2.4-1050 AAP-18707 Updated procedure with EDA max running activations

- downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
- downstream/modules/platform/ref-controller-extra-variables.adoc
Missing documentation on job template's extra vars
https://issues.redhat.com/browse/AAP-4442
Affects `titles/controller-admin-guide` and `controller-user-guide`
> Adding missing info to extra vars section

- downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
- downstream/modules/platform/ref-controller-extra-variables.adoc
* Adding note to extra vars section
Missing documentation on job template's extra vars
https://issues.redhat.com/browse/AAP-4442
Affects `titles/controller-admin-guide` and `controller-user-guide`
* Third commit
> Adding missing info to extra vars section (#1132)

- downstream/modules/platform/proc-change-ssl-installer.adoc
- downstream/modules/platform/ref-eda-controller-variables.adoc
This PR ports the changes from [PR 1130](https://github.com/ansible/aap-docs/pull/1130) to the 2.4 branch. See [AAP-20863](https://issues.redhat.com/browse/AAP-20863) for more info. 
* Adds EDA controller variables to procedure for changing SSL certification
* adds eda controller ssl variables to variable index in installation guide
* edits based on technical SME feedback
> AAP-20863: Adds EDA controller variables to procedure for changing SSL certification (#1130)

- lightspeed/modules/proc_provide-feedback.adoc
- lightspeed/modules/proc_troubleshooting-lightspeed-config.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-19591. 
Changes made:
- Added links to contact both Red Hat and IBM Support.
> AAP-19591: Added RH and IBM support links

- downstream/modules/platform/con-why-migrate-venvs-ee.adoc
- downstream/modules/platform/proc-apply-selinux-context.adoc
- downstream/modules/platform/proc-choosing-obtaining-installer.adoc
- downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
- downstream/modules/platform/proc-controller-awx-manage-utility.adoc
- downstream/modules/platform/proc-controller-importing-subscriptions.adoc
- downstream/modules/platform/proc-controller-use-an-exec-env.adoc
- downstream/modules/platform/proc-create-password-hashes.adoc
- downstream/modules/platform/proc-customizing-pod-specs.adoc
- downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc
- downstream/modules/platform/proc-install-cli-aap-operator.adoc
- downstream/modules/platform/proc-installing-with-internet.adoc
- downstream/modules/platform/proc-update-ee-image-locations.adoc
- downstream/modules/platform/proc-update-rhsso-client.adoc
- downstream/modules/platform/proc-upgrade-installer.adoc
- downstream/modules/platform/proc-verify-controller-installation.adoc
- downstream/modules/platform/ref-container-resource-requirements.adoc
- downstream/modules/platform/ref-controller-amazon-web-services.adoc
- downstream/modules/platform/ref-controller-automation-analytics.adoc
- downstream/modules/platform/ref-controller-aws-cloud.adoc
I'm breaking up platform module updates into mulitiple PRs to prevent merge conflicts.
```
./aap-operations-guide/platform
./upgrade/platform
./aap-operator-installation/platform
./aap-installation-guide/platform
./aap-planning-guide/platform
./operator-mesh/platform
./automation-mesh/platform
./ocp_performance_guide/platform
./controller/controller-user-guide/platform
./controller/controller-admin-guide/platform
./controller/controller-getting-started/platform
./controller/controller-api-guide/platform
./aap-operator-backup/platform
./aap-containerized-install/platform
```
> Replace plain text with attributes for content in the platform module

- downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
Minor syntax edit
https://issues.redhat.com/browse/AAP-4442
> Correction to The _awx-manage_ Utility section

- downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
Minor syntax edit
https://issues.redhat.com/browse/AAP-4442
> Correction to The _awx-manage_ Utility section (#1149)

- downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
- downstream/assemblies/platform/assembly-ag-controller-security-best-practices.adoc
- downstream/assemblies/platform/assembly-ag-instance-and-container-groups.adoc
- downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
- downstream/assemblies/platform/assembly-controller-credentials.adoc
- downstream/assemblies/platform/assembly-controller-instances.adoc
- downstream/assemblies/platform/assembly-controller-inventories.adoc
- downstream/assemblies/platform/assembly-controller-job-templates.adoc
- downstream/assemblies/platform/assembly-disconnected-installation.adoc
- downstream/assemblies/platform/assembly-install-aap-operator.adoc
- downstream/assemblies/platform/assembly-install-upgrade-pah.adoc
- downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
- downstream/assemblies/platform/assembly-installing-controller-operator.adoc
- downstream/assemblies/platform/assembly-installing-hub-operator.adoc
- downstream/assemblies/platform/assembly-inventory-file-importing.adoc
- downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
- downstream/assemblies/platform/assembly-planning-installation.adoc
- downstream/assemblies/platform/assembly-platform-install-overview.adoc
- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
- downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
- downstream/assemblies/platform/assembly-supported-installation-scenarios.adoc
- downstream/assemblies/platform/assembly-system-requirements.adoc
- downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
AAP-21516 Update links to use `BaseURL` attribute in platform assemblies
> AAP-21516 Update links to use BaseURL attribute in platform assemblies

- downstream/modules/dev-guide/proc-create-collections.adoc
- downstream/modules/dev-guide/proc-create-role.adoc
This PR is specific to the 2.3 branch and version of our docs. The main PR is #1044
```
./aap-operations-guide/platform/dev-guide
./upgrade/platform/dev-guide
./aap-operator-installation/platform/dev-guide
./aap-installation-guide/platform/dev-guide
./aap-planning-guide/platform/dev-guide
./automation-mesh/platform/dev-guide
./ocp_performance_guide/platform/dev-guide
./controller/controller-user-guide/platform/dev-guide
./controller/controller-admin-guide/platform/dev-guide
./controller/controller-getting-started/platform/dev-guide
./aap-operator-backup/platform/dev-guide
./aap-containerized-install/platform/dev-guide
./dev-guide/dev-guide
```
> Replace plain text with attributes for content in the dev-guide module.

- downstream/assemblies/hub/assembly_ppah-installation.adoc
- downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
- downstream/modules/hub/proc-sync-image.adoc
- downstream/modules/hub/proc_ppah-download-aap.adoc
- downstream/modules/hub/proc_ppah-install-ansible-core.adoc
- downstream/modules/hub/proc_ppah-install-dev.adoc
- downstream/modules/hub/proc_ppah-install-ha.adoc
- downstream/modules/hub/proc_ppah-online-offline-install.adoc
- downstream/modules/hub/proc_ppah-prepare-rhel-host.adoc
- downstream/modules/hub/ref_ppah-access.adoc
- downstream/modules/hub/ref_ppah-config.adoc
- downstream/modules/platform/con-aap-example-architecture.adoc
- downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
- downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
- downstream/modules/platform/proc-downloading-containerized-aap.adoc
- downstream/modules/platform/proc-install-ansible-colls.adoc
- downstream/modules/platform/proc-installing-ansible-core.adoc
- downstream/modules/platform/proc-installing-containerized-aap.adoc
- downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
- downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
- downstream/modules/platform/proc-update-ee-image-locations.adoc
- downstream/modules/platform/proc-using-postinstall.adoc
- downstream/modules/platform/ref-aap-containerized-dns-config.adoc
- downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
- downstream/modules/platform/ref-ldap-config-on-pah.adoc
rename :_content-type: variable
Replace the :_content-type: variable with the :_mod-docs-content-type: variable.
Modular Documentation: rename :_content-type: variable
https://issues.redhat.com/browse/AAP-17451
> Replacing variables

- downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
- downstream/modules/hub/proc-sync-image.adoc
- downstream/modules/platform/con-aap-example-architecture.adoc
- downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
- downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
- downstream/modules/platform/proc-downloading-containerized-aap.adoc
- downstream/modules/platform/proc-install-ansible-colls.adoc
- downstream/modules/platform/proc-installing-ansible-core.adoc
- downstream/modules/platform/proc-installing-containerized-aap.adoc
- downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
- downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
- downstream/modules/platform/proc-update-ee-image-locations.adoc
- downstream/modules/platform/proc-using-postinstall.adoc
- downstream/modules/platform/ref-aap-containerized-dns-config.adoc
- downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
- downstream/modules/platform/ref-ldap-config-on-pah.adoc
rename :_content-type: variable
Replace the :_content-type: variable with the :_mod-docs-content-type: variable.
Modular Documentation: rename :_content-type: variable
https://issues.redhat.com/browse/AAP-17451
> Replacing variables (#1181)

- downstream/modules/automation-hub/proc-sync-image.adoc
- downstream/modules/platform/con-aap-example-architecture.adoc
- downstream/modules/platform/proc-update-ee-image-locations.adoc
- downstream/modules/platform/proc_configuring-tls-with-aap-operator.adoc
- downstream/modules/platform/ref-ldap-config-on-pah.adoc
rename :_content-type: variable
Replace the :_content-type: variable with the :_mod-docs-content-type: variable.
Modular Documentation: rename :_content-type: variable
https://issues.redhat.com/browse/AAP-17451
> rename :_content-type: variable

- downstream/assemblies/platform/assembly-installing-hub-operator.adoc
- downstream/modules/platform/proc-installing-hub-using-operator.adoc
- downstream/modules/platform/ref-ocp-additional-configs.adoc
This PR backports the changes from [PR 915](https://github.com/ansible/aap-docs/pull/915) to the 2.4 branch. See [AAP-18088](https://issues.redhat.com/browse/AAP-18088) for more info. 
* AAP-18088: adds info on download count configuration; fixes a namespace error
* edit based on SME feedback--removed api_root setting from sample yaml
> AAP-18088: adds info on download count configuration; fixes a namesapce error (#915)

- downstream/assemblies/platform/assembly-disconnected-installation.adoc
Fixed a typo in the Red Hat Ansible Automation Platform Installation Guide Correct typo in Red Hat Ansible Automation Platform Installation Guide https://issues.redhat.com/browse/AAP-22151
> Correct typo in Red Hat Ansible Automation Platform Installation Guide

- downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
- downstream/modules/platform/proc-add-operator-execution-nodes.adoc
- downstream/titles/aap-operator-installation/master.adoc
[AAP-20279](https://issues.redhat.com/browse/AAP-20779)
"Need a detailed document for upgrading AAP operator with on premise execution nodes"
[Red Hat Ansible Automation Platform Performance Considerations for Operator Based Installations](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_performance_considerations_for_operator_based_installations/index)
Created a new assembly and procedure and linked them to the master.adoc. 
Downstream>titles>aap-operator-installation
> Creating new section to operator deploy guide as part of AAP-20779

- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/bundle-installer-24-61.adoc
Add bundle-installer-2.4-6.1 to release notes
2.4 Release Notes - AAP 2.4-6.1 Bundle Installer Release
https://issues.redhat.com/browse/AAP-21892
> Add bundle-installer-2.4-6.1 to release notes (#1205)

- downstream/assemblies/platform/assembly-controller-set-up-social-authentication.adoc
SAML users have a label of "Social" in the userlist, causing confusion
https://issues.redhat.com/browse/AAP-22314
> Adding links to SAML auth in chapt. 21

- downstream/assemblies/platform/assembly-controller-set-up-social-authentication.adoc
* Adding links to SAML auth in chapt. 21
SAML users have a label of "Social" in the userlist, causing confusion
https://issues.redhat.com/browse/AAP-22314
* Second commit, style guide edits.
> Adding links to SAML auth in chapt. 21 (#1206)

- downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Just fixing some small erros noticed after [AAP-20779](https://issues.redhat.com/browse/AAP-20779) was published 
Location : proc-add-operator-execution-nodes.adoc
> fixing typo and Icon size for AAP-20779

- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
This PR ports the changes from[ PR 1208](https://github.com/ansible/aap-docs/pull/1208) to the 2.4 branch. See [AAP-19094](https://issues.redhat.com/browse/AAP-19094) for more info.
> Backport to 2.4: AAP 19094 fixed formatting to make API link inactive (#1208)

- downstream/assemblies/central-auth/assembly-central-auth-add-user-storage.adoc
- downstream/assemblies/central-auth/assembly-central-auth-hub.adoc
- downstream/assemblies/central-auth/assembly-central-auth-identity-broker.adoc
- downstream/assemblies/dev-guide/assembly-tools-components.adoc
- downstream/assemblies/eda/assembly-ansible-rulebooks.adoc
- downstream/assemblies/eda/assembly-installation-eda-controller.adoc
- downstream/assemblies/eda/assembly-using-eda-controller.adoc
AAP-21516 Update links to use `BaseURL` attribute in assemblies.
> Update links to use BaseURL attribute in assemblies

- downstream/assemblies/central-auth/assembly-central-auth-add-user-storage.adoc
- downstream/assemblies/central-auth/assembly-central-auth-hub.adoc
- downstream/assemblies/central-auth/assembly-central-auth-identity-broker.adoc
- downstream/assemblies/dev-guide/assembly-tools-components.adoc
- downstream/assemblies/eda/assembly-ansible-rulebooks.adoc
- downstream/assemblies/eda/assembly-installation-eda-controller.adoc
- downstream/assemblies/eda/assembly-using-eda-controller.adoc
Backports #1226 to 2.4
AAP-21516 Update links to use `BaseURL` attribute in assemblies.
> 2.4 Update links to use BaseURL attribute in assemblies (#1226)

- downstream/attributes/attributes.adoc
This PR defines attributes for the 2.4 release. These attributes map to the definitions previously created for 2.5. Once merged, I will update the attributes for 2.5 and later. Builds used to create these attributes:
https://console.redhat.com/ for Analytics selections
https://awx.dev-ui.gcp.testing.ansible.com/#/home for Controller selections
https://eda.dev-ui.gcp.testing.ansible.com/overview for EDA selections
https://galaxy.dev-ui.gcp.testing.ansible.com/ui/search/ for Hub selections
> Adding attributes for menu selections for 2.4

- downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc
Correct link in EE mount options documentation
https://issues.redhat.com/browse/AAP-22827
> Correcting link to Podman docs in EE chapter

- downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
2.4 backport of [PR 1239](https://github.com/ansible/aap-docs/pull/1239)
[AAP-22950](https://issues.redhat.com/browse/AAP-22950)
Updated Figure 2.2. Ansible Automation Platform Network ports and protocols within [2.1.2. Network, firewall, and network services planning for Ansible Automation Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_hardening_guide/index#con-network-firewall-services_hardening-aap)
with new diagram (see [DXD-637](https://issues.redhat.com/browse/DXD-637) for information on updates).
> AAP-22950 updated figure 2.2 (#1239)

- downstream/modules/platform/proc-controller-adding-gpg-key.adoc
- downstream/modules/platform/ref-controller-metrics-monitoring.adoc
https://issues.redhat.com/browse/AAP-20052
affects `titles/controller-admin-guide` and `controller-user-guide`
> Automation Controller Administration Guide/ User Guide typos/Link error?

- downstream/assemblies/platform/assembly-system-requirements.adoc
- downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
* Add section on setting up database
[CEE.NExt]Add PseudoCode for the Db user permission for the external DB.
https://issues.redhat.com/browse/AAP-19951
* Add section on setting up database
Added to installation guide
[CEE.NExt]Add PseudoCode for the Db user permission for the external DB.
https://issues.redhat.com/browse/AAP-19951
* Add section on setting up database
Removed duplicate
[CEE.NExt]Add PseudoCode for the Db user permission for the external DB.
https://issues.redhat.com/browse/AAP-19951
* Add section on setting up database
Corrections
[CEE.NExt]Add PseudoCode for the Db user permission for the external DB.
https://issues.redhat.com/browse/AAP-19951
> Add section on setting up database (#1240)

- downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
[DOC] Remove statement about newer rsyslog from controller documentation
https://issues.redhat.com/browse/AAP-15372
> Removing note for rsyslog in controller admin guide

- downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
* Removing note for rsyslog in controller admin guide
[DOC] Remove statement about newer rsyslog from controller documentation
https://issues.redhat.com/browse/AAP-15372
> Removing note for rsyslog in controller admin guide (#1251)

- downstream/titles/release-notes/master.adoc
The doc title name should match exactly what's on Pantheon otherwise the publish will fail. Reverting the title back to how it was previously before implementing feedback.
> Correct release note title name

- downstream/titles/release-notes/master.adoc
The doc title name should match exactly what's on Pantheon otherwise the publish will fail. Reverting the title back to how it was previously before implementing feedback.
> Correct release note title name (#1267)

- downstream/assemblies/platform/assembly-system-requirements.adoc
- downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Transferred changes from 2.4 and main. (No backport)
[CEE.NExt]Add PseudoCode for the Db user permission for the external DB.
https://issues.redhat.com/browse/AAP-19951
> Add section on setting up database

- downstream/modules/platform/con-aap-upgrade-planning.adoc
Documentation for "Upgrading to Red Hat Ansible Automation Platform 2.4" has wrong link
https://issues.redhat.com/browse/AAP-23273
> Update documentation links

- downstream/modules/platform/con-aap-upgrade-planning.adoc
Documentation for "Upgrading to Red Hat Ansible Automation Platform 2.4" has wrong link
https://issues.redhat.com/browse/AAP-23273
> Update documentation links (#1276)

- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/bundle-installer-24-62.adoc
2.4 Release Notes - AAP 2.4-6.2 Bundle installer release
https://issues.redhat.com/browse/AAP-23336
> Add bundle-installer-2.4-6.2 to release notes

- downstream/modules/platform/proc-operator-external-db-controller.adoc
- downstream/modules/platform/proc-operator-external-db-hub.adoc
Changed awx value for correct value
API version specified in the documentation of AAP Operator installation is incorrect
https://issues.redhat.com/browse/AAP-22949
> Corrected API version

- downstream/modules/platform/proc-operator-external-db-controller.adoc
- downstream/modules/platform/proc-operator-external-db-hub.adoc
Changed awx value for correct value
API version specified in the documentation of AAP Operator installation is incorrect
https://issues.redhat.com/browse/AAP-22949
> Corrected API version (#1279)

- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/bundle-installer-24-62.adoc
2.4 Release Notes - AAP 2.4-6.2 Bundle installer release
https://issues.redhat.com/browse/AAP-23336
> Add bundle-installer-2.4-6.2 to release notes (#1278)

- downstream/modules/platform/con-aap-upgrade-planning.adoc
Correction
Documentation for "Upgrading to Red Hat Ansible Automation Platform 2.4" has wrong link
https://issues.redhat.com/browse/AAP-23273
> Update documentation links (#1282)

- downstream/titles/aap-operator-installation/master.adoc
[AAP-23500](https://issues.redhat.com/browse/AAP-23500) Deploying the AAP operator on OCP – remove content related to upgrades.
Commenting out Chapter 9. Not to be included in 2.5
location downstream > titles > aap-operator-installation > master.adoc
> [AAP-22627] Commenting out Chapter 9. Not to be included in 2.5

- downstream/attributes/attributes.adoc
- downstream/snippets/snip_menu-top-ac.adoc
- downstream/snippets/snip_menu-top-ae.adoc
Once the unified platform is fully implemented, some of the menu selections will become tertiary. In order to simplify the updates, I have included snippets to cover those instances. While the content for 2.4 will be the same, they will become unique in the future releases. I've also updated the attributes file to group the menu selections effected by these instances and include comments for future reference.
> Update for 2.4 primary menu snippets

- downstream/assemblies/navigator/assembly-executing-content.adoc
- downstream/assemblies/navigator/assembly-intro-navigator.adoc
- downstream/assemblies/navigator/assembly-review-ee-navigator.adoc
- downstream/assemblies/navigator/assembly-settings-navigator.adoc
- downstream/attributes/attributes.adoc
- downstream/modules/navigator/con-about-ansible-navigator.adoc
- downstream/modules/navigator/con-about-navigator-settings.adoc
- downstream/modules/navigator/con-navigator-collections.adoc
- downstream/modules/navigator/con-navigator-modes.adoc
- downstream/modules/navigator/proc-review-ansible-config-tui.adoc
- downstream/modules/navigator/proc-review-artifact.adoc
- downstream/modules/navigator/ref-faq-navigator.adoc
- downstream/modules/navigator/ref-navigator-command-summary.adoc
- downstream/modules/navigator/ref-navigator-config-settings.adoc
- downstream/modules/navigator/ref-navigator-general-settings.adoc
- downstream/modules/navigator/ref-navigator-inventory-settings.adoc
- downstream/modules/navigator/ref-navigator-replay-settings.adoc
- downstream/modules/navigator/ref-navigator-run-settings.adoc
- downstream/modules/platform/con-about-navigator.adoc
According to Official Red Hat product names list (OPL), the correct usage is "automation content navigator".
It would be helpful to set the attributes like this:
- :Navigator: automation content navigator
- :NavigatorStart: Automation content navigator
Additionally, the usage of these attributes should be reviewed throughout the docs set to ensure it's used correctly.
Update Navigator attribute and add NavigatorStart attribute
https://issues.redhat.com/browse/AAP-21433
> Add NavigatorStart attribute and update Navigator attribute

- downstream/assemblies/navigator/assembly-executing-content.adoc
- downstream/assemblies/navigator/assembly-intro-navigator.adoc
- downstream/assemblies/navigator/assembly-review-ee-navigator.adoc
- downstream/assemblies/navigator/assembly-settings-navigator.adoc
- downstream/attributes/attributes.adoc
- downstream/modules/navigator/con-about-ansible-navigator.adoc
- downstream/modules/navigator/con-about-navigator-settings.adoc
- downstream/modules/navigator/con-navigator-collections.adoc
- downstream/modules/navigator/con-navigator-modes.adoc
- downstream/modules/navigator/proc-review-ansible-config-tui.adoc
- downstream/modules/navigator/proc-review-artifact.adoc
- downstream/modules/navigator/ref-faq-navigator.adoc
- downstream/modules/navigator/ref-navigator-command-summary.adoc
- downstream/modules/navigator/ref-navigator-config-settings.adoc
- downstream/modules/navigator/ref-navigator-general-settings.adoc
- downstream/modules/navigator/ref-navigator-inventory-settings.adoc
- downstream/modules/navigator/ref-navigator-replay-settings.adoc
- downstream/modules/navigator/ref-navigator-run-settings.adoc
- downstream/modules/platform/con-about-navigator.adoc
According to Official Red Hat product names list (OPL), the correct usage is "automation content navigator".
It would be helpful to set the attributes like this:
- :Navigator: automation content navigator
- :NavigatorStart: Automation content navigator
Additionally, the usage of these attributes should be reviewed throughout the docs set to ensure it's used correctly.
Update Navigator attribute and add NavigatorStart attribute
https://issues.redhat.com/browse/AAP-21433
> Add NavigatorStart attribute and update Navigator attribute (#1293)

- downstream/attributes/attributes.adoc
Adding Lightspeed attributes to the AAP docs because the DevTools doc refers to Lightspeed.
> Add attributes for Ansible Lightspeed

- downstream/attributes/attributes.adoc
Backports #1308 to 2.4
Adds Lightspeed attributes to the platform docs because the DevTools doc refers to the Lightspeed feature.
> 2.4 Add attributes for Ansible Lightspeed (#1308)

- downstream/assemblies/builder/assembly-publishing-exec-env.adoc
The attribute given doesn't exist and was replaced with {ExecEnvShort}s
AAP-23620
https://issues.redhat.com/browse/AAP-23620
> Corrected Attribute Name

- downstream/assemblies/builder/assembly-publishing-exec-env.adoc
The attribute given doesn't exist and was replaced with {ExecEnvShort}s
AAP-23620
https://issues.redhat.com/browse/AAP-23620
> Corrected Attribute Name (#1312)

- downstream/snippets/snip_menu-top-ac.adoc
- downstream/snippets/snip_menu-top-ae.adoc
This PR deletes the snippets for tertiary menus because the new docs experience allows them to be coded with the menu:selection1[selection2 > selection3] and makes the snippets an unnecessary workaround.
> Remove snippets for tertiary menus

- downstream/attributes/attributes.adoc
This PR fixes an issue with the same attribute used more than once. The duplicate attributes (MenuAMCredentials and MenuAMCredentialType) have been removed and defined only once in the file.
> Removed duplicate attribute definition

- downstream/attributes/attributes.adoc
This PR backports the changes from #1328 to the 2.4  branch and includes the following changes:
* Removed duplicate attribute definition
* 23715A fixed typo found in peer review
> [Backport] - Removed duplicate attribute definition (#1328)

- downstream/attributes/attributes.adoc
- downstream/modules/platform/con-aap-upgrades-legacy.adoc
- downstream/modules/platform/ref-system-requirements.adoc
- Added `CoreInstVers`. This is the Ansible-core version required to install AAP.
- Added `CoreUseVers`. This is the Ansible-core version used by the AAP control plane and EEs.
- Removed `AnsibleCoreVers`. This is replaced by `CoreUseVers`.
- Removed `AnsibleInstallVers`. This is replaced by `CoreInstVers`.
Add and update Ansible-core attributes in aap-docs
https://issues.redhat.com/browse/AAP-23165
> Add and update Ansible-core attributes in aap-docs

- downstream/attributes/attributes.adoc
- downstream/modules/platform/con-aap-upgrades-legacy.adoc
- downstream/modules/platform/ref-system-requirements.adoc
- Added CoreInstVers. This is the Ansible-core version required to install AAP
- Added CoreUseVers. This is the Ansible-core version used by the AAP control plane and EEs
- Removed AnsibleCoreVers. This is replaced by CoreUseVers
- Removed AnsibleInstallVers. This is replaced by CoreInstVers
Add and update Ansible-core attributes in aap-docs
https://issues.redhat.com/browse/AAP-23165
> Add and update Ansible-core attributes in aap-docs (#1339)

- downstream/modules/platform/ref-postgresql-requirements.adoc
[Docs] Planning Guide should have the RAM and CPU requirement for Postgres system.
https://issues.redhat.com/browse/AAP-20172
> Add CPU and RAM requirements for Postgres in planning guide (#1341)

- downstream/modules/platform/ref-controller-api-config-settings.adoc
Automation Controller API Overview typo
https://issues.redhat.com/browse/AAP-23917
> Plus symbols not rendering correctly in asciidoc

- downstream/modules/platform/ref-controller-api-config-settings.adoc
* Plus symbols not rendering correctly in asciidoc
Automation Controller API Overview typo
https://issues.redhat.com/browse/AAP-23917
> Plus symbols not rendering correctly in asciidoc (#1343)

- downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
Replace Mesh Ingress section in Operator-mesh guide
https://issues.redhat.com/browse/AAP-22845
> Added mesh ingress section back into doc for 2.5

- lightspeed/modules/con-lightspeed-about.adoc
- lightspeed/modules/con_lightspeed-key-features.adoc
- lightspeed/modules/con_overview-and-best-practices.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-24195. 
Changes made:
- Added info. that Lightspeed supports user prompts in English language only, along with a corner case.
> AAP-24195: Added info. about languages supported for Ansible Lightspeed prompts

- stories/assembly-saas-planning.adoc
- stories/topics/con-saas-intro.adoc
- stories/topics/ref-saas-default-configs.adoc
- stories/topics/ref-saas-planning-configs.adoc
[AAP-23356 ](https://issues.redhat.com/browse/AAP-23356 )SaaS documentation - Add planning chapter
Cretaing and linking the modules for the Planning chapter assembly
Location : aap-clouds-latest > stories > topics
> Adding modules for planning Assembly (AAP-23356)

- downstream/assemblies/platform/assembly-controller-glossary.adoc
This should show up as a bold term but is displaying with 3 = like this: === Source Credential
AAP-24465
https://issues.redhat.com/browse/AAP-24465
> Formatting issue in Controller UG Glossary section

- downstream/assemblies/platform/assembly-controller-glossary.adoc
* Formatting issue in Controller UG Glossary section
This should show up as a bold term but is displaying with 3 = like this: === Source Credential
AAP-24465
https://issues.redhat.com/browse/AAP-24465
* Formatting issue in Controller UG Glossary section
This should show up as a bold term but is displaying with 3 = like this: === Source Credential
AAP-24465
https://issues.redhat.com/browse/AAP-24465
> Formatting issue in Controller UG Glossary section (#1370)

- stories/assembly-azure-support.adoc
This PR adds information about the AKS Private DNS zone, the customers soon having the ability to partially manage the Private DNS zones in the managed resource group, and cleans up the capitalization to match Azure docs.
Draft for now until we're live with these changes.
> Updating the info for private dns zone being customer managable.

- downstream/modules/platform/con-controller-capacity-determination.adoc
Typo in attribute in Automation Controller User Guide
https://issues.redhat.com/browse/AAP-24759
> Corrected link

- downstream/assemblies/platform/assembly-ag-controller-secret-handling.adoc
- downstream/modules/platform/con-controller-secret-handling.adoc
Documentation should clarify if local users are needed
https://issues.redhat.com/browse/AAP-19240
> Add notes about use of local users

- downstream/attributes/attributes.adoc
Update the {BaseURL} attribute so that links to Red Hat docs point to `docs.redhat.com` instead of `access.redhat.com`.
Backporting to 2.4 only: the attribute isn't in the 2.3 branch and we haven't cut the branch for 2.5 yet.
> 2.4 Update BaseURL attribute to docs.redhat.com site (#1344)

- downstream/assemblies/devtools/assembly-testing-playbooks.adoc
- downstream/titles/develop-automation-content/master.adoc
Remove chapter about molecule from Devtools book. 
Add it back in when molecule examples are added to the community documentation.
Affects `/titles/develop-automation-content/`
> AAP-17190 Remove molecule chapter from devtools guide

- downstream/assemblies/devtools/assembly-testing-playbooks.adoc
- downstream/titles/develop-automation-content/master.adoc
Remove chapter about molecule from Devtools book. 
Add it back in when molecule examples are added to the community documentation.
Affects `/titles/develop-automation-content/`
> 2.4 AAP-17190 Remove molecule chapter from devtools guide (#1396)

- downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
[AAP-25067](https://issues.redhat.com/browse/AAP-25067)
Removing an incorrect sentence that was causing confusion
Doc location: downstream > titles > assembly-operator-add-execution-nodes.adoc
> AAP-25067 removing incorrect sentence

- downstream/templates/installer-rn-template.adoc
- downstream/templates/rpm-rn-template.adoc
Add `installer-rn-template.adoc` and `rpm-rn-template.adoc` for use when creating async release notes.
Automate generation of async release notes
https://issues.redhat.com/browse/AAP-19076
> Add async release note templates

- downstream/templates/installer-rn-template.adoc
- downstream/templates/rpm-rn-template.adoc
Add `installer-rn-template.adoc` and `rpm-rn-template.adoc` for use when creating async release notes.
Automate generation of async release notes
https://issues.redhat.com/browse/AAP-19076
> 2.4 Backport 1400 to 24

- downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
[AAP-25067](https://issues.redhat.com/browse/AAP-25067)
Removing an incorrect sentence that was causing confusion
Doc location: downstream > titles > assembly-operator-add-execution-nodes.adoc
> AAP-25067 removing incorrect sentence (#1401)

- downstream/modules/platform/proc-controller-inv-source-terraform.adoc
Modify the link to terraform_state inventory plugin to improve readability.
Related to https://github.com/ansible-collections/cloud.terraform/pull/145
> Modify the link to terraform_state inventory plugin

- downstream/journeys/dev-tools-personas.md
This PR adds an MD file that defines downstream personas for Ansible Developer Tools. These personas describe the intended audience for the documentation and outlines the needs, attitude, and knowledge of each persona. The defined personas help put the audience into context and understand the level of expertise of each user as well as the level of verbosity for the content.
As a follow on PR, we can add journey maps that describe expected paths for each persona.
> create dev tools personas

- downstream/archive/archived-modules/platform/ref-network-ports-protocols.adoc
Removing the incorrect use of AAP acroynms from "ref-network-ports-protocols.adoc"
> Removing AAP acronyms

- downstream/templates/installer-rn-template.adoc
- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/installer-24-7.adoc
- downstream/titles/release-notes/topics/installer-version-table.adoc
- downstream/titles/release-notes/topics/rpm-version-table.adoc
2.4 Release Notes - AAP 2.4-7 Bundle installer release
https://issues.redhat.com/browse/AAP-24793
> Add 2.4-7 bundle installer release to release notes

- downstream/titles/release-notes/topics/rpm-24-7.adoc
2.4 Release Notes - AAP 2.4-7 Bundle installer release
https://issues.redhat.com/browse/AAP-24793
> Update CVE python packages to include each version

- downstream/titles/aap-planning-guide/master.adoc
- downstream/titles/ocp_performance_guide/docinfo.xml
- downstream/titles/ocp_performance_guide/master.adoc
Fixing a mismatch between master.adoc and docinfo.xml and removing the dash in operator-based because it's causing issues with Pantheon.
> Fixed mismatch in docinfo and master

- downstream/titles/aap-planning-guide/master.adoc
- downstream/titles/ocp_performance_guide/docinfo.xml
- downstream/titles/ocp_performance_guide/master.adoc
This PR backports the fixes from #1446 to the 2.4 branch.
> [Backport] - Fixed mismatch in docinfo and master (#1446)

- downstream/titles/aap-installation-guide/master.adoc
This PR fixes a mismatch between the master.adoc and docinfo.xml file in the installation guide.
> Fix title issue in AAP install guide

- downstream/modules/platform/con-operator-upgrade-prereq.adoc
Adding in a missing hyperlink as part of [AAP-23886](https://issues.redhat.com/browse/AAP-23886)
doc location: aap-docs > downstream > titles > aap-operator-install
> adding missing hyperlink as part of aap-23886

- downstream/modules/platform/con-operator-upgrade-prereq.adoc
Adding in a missing hyperlink as part of [AAP-23886](https://issues.redhat.com/browse/AAP-23886)
doc location: aap-docs > downstream > titles > aap-operator-install
> adding missing hyperlink as part of aap-23886 (#1451)

- lightspeed/assemblies/assembly_setting-up-lightspeed.adoc
AAP-20958 Lightspeed Set `grandparent-context` value for assembly that contains nested assemblies.
When an assembly contains nested assemblies, the `parent-context` variable is set by the nested assemblies.
After the nested assemblies, you need to restore the context to the original `parent-context` (ie the value before the nesting).
This PR does this by creating a variable called `grandparent-context`.
> AAP-20958 Lightspeed Set grandparent-context for assembly with nesting

- lightspeed/modules/con_overview-lightspeed-onpremise.adoc
- lightspeed/modules/proc_create-connection-secrets.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-25663.
Changes made:
IBM released its WCA on-premise docs yesterday. In this PR, I'm adding the relevant WCA on-premise doc links to Red Hat Ansible Lightspeed on-premise deployment docs.
> AAP-25663: Update IBM WCA on-premise doc links in Lightspeed on-premise docs

- downstream/assemblies/platform/assembly-aap-backup.adoc
- downstream/assemblies/platform/assembly-aap-recovery.adoc
- downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
- downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
Preparing 2.5 content 
[AAP-22718](https://issues.redhat.com/browse/AAP-22718)
Adding content to proc modules:
- downstream/assemblies/platform/assembly-aap-backup.adoc
- downstream/assemblies/platform/assembly-aap-recovery.adoc
> Adding proc content (AAP-22718)

- stories/topics/proc-azure-update-route-tables.adoc
AAP-25889 Azure - link to a KCS article that customers / support can refer to for the list of domains to allow, instead of listing the domains in the docs, because this list is frequently updated.
> AAP-25889 Azure - link to kcs article for list of domains

- downstream/assemblies/hub/assembly-populate-container-registry.adoc
- downstream/modules/hub/proc-obtain-images.adoc
Added warnings about the depreciation of RHSM manifests & manifest lists, interchangeably called subscription allocations, to:
- Assembly chapters 5. Populating your private automation hub container registry
- Procedure chapter 5.1 Pulling images for use in automation hub
In 5.1, I also added reference links for
- Added links for Satellite Release Dates, as it relates to the one exception to the currently existing depreciation
- Transition of Red Hat's subscription services to console.redhat.com from the Customer Portal
Because the use of consoleDOT is new to the user potentially, I have also added two steps to the procedure in 5.1 addressing that.
> Adding manifest deprication warning to execution environments doc

- lightspeed/modules/con_overview-lightspeed-onpremise.adoc
- lightspeed/modules/con_wca-key-model-id.adoc
- lightspeed/modules/proc_create-connection-secrets.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-25853.
Changes made:
#1: Updated the prerequisites and other places where we've mentioned the info. about needing IBM watsonx Code Assistant trial and paid plans. Replaced them with needing "IBM watsonx Code Assistant for Red Hat Ansible Lightspeed on Cloud Pak for Data" .. I know..the name is a mouthful! Here's the IBM doc link for your reference: https://www.ibm.com/docs/SSQNUZ_5.0.x/svc-welcome/wxca-ansible.html
#2: The hyperlinks currently pointing to IBM WCA docs are now updated to point to the relevant IBM watsonx Code Assistant for Red Hat Ansible Lightspeed on Cloud Pak for Data docs.
> AAP-25853: Update on-premise deployment docs to include IBM CPD requirement

- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Added a note at the end of [section 6.1 Setting up a rulebook activation](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/event-driven_ansible_controller_user_guide/index#eda-set-up-rulebook-activation) in the EDA controller user guide to inform users that when an activation shuts down, any tasks that are waiting to be performed will be canceled and an info level message will be sent to the activation log. Tracked in jira [AAP-24694](https://issues.redhat.com/browse/AAP-24694).
> AAP-24694 Added note about rulebook activations shutting down and canceling jobs on controller.

- lightspeed/assemblies/assembly_configuring-vscode-extension.adoc
- lightspeed/modules/proc_log-out-of-portal.adoc
This PR addresses an older JIRA https://github.com/sayjadha/aap-docs/pull/new/AAP-22995. The docs were published earlier [on here](https://docs.redhat.com/en/documentation/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant/2.x_latest/html-single/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant_user_guide/index#log-out-of-portal_logging-in-out-lightspeed-portal), but I simply missed updating the JIRA. 
Updates made:
- Reused the logout module in 'Chapter 5. Installing and configuring the Ansible VS Code extension'
-  Changed 'Ansible Lightspeed Portal' to Ansible Lightspeed Service
> AAP-22995: Reused logout procedure in VS Code chapter

- downstream/modules/platform/proc-verify-controller-installation.adoc
- downstream/modules/platform/proc-verify-eda-controller-installation.adoc
- downstream/modules/platform/proc-verify-hub-installation.adoc
As per AAP-16427 and its comments, I have added a step (now step 2) that instructs users to login with their Satellite credentials and, if it is the first time they are logging in since installation, upload their manifest file in:
1. [3.5 Verifying installation of automation hub](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#proc-verify-hub-installation_platform-install-scenario)
2. [3.4 Verifying installation of automation controller](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#proc-verify-controller-installation_platform-install-s …
> added a second step to verification modules about satellite login

- lightspeed/assemblies/assembly_configuring-vscode-extension.adoc
- lightspeed/modules/con_lightspeed-key-features.adoc
- lightspeed/modules/con_lightspeed-process.adoc
- lightspeed/modules/proc_create-connection-secrets.adoc
- lightspeed/modules/proc_create-lightspeed-instance.adoc
- lightspeed/modules/proc_create-oauth-app.adoc
- lightspeed/modules/proc_install-aap-lightspeed-operator.adoc
- lightspeed/modules/proc_login-vscode-extension.adoc
- lightspeed/modules/proc_update-connection-secrets.adoc
- lightspeed/modules/proc_update-redirect-uri.adoc
- lightspeed/modules/proc_view-playbook-explanation.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-25608.
Changes made:
#1: Specified VS code connection URLs (outbound domains). 
$2: Checked all instances throughout the Lightspeed docs and use Asciidoc button macro for consistency in places where the menu wasn't used as expected.
$3: Updated 'Key features' section to include new updates namely: model customization, telemetry and admin dashboard, on-premise deployment and playbook generation. **Content is reused from release notes**, no changes made to the blurbs. Release notes are here for your reference: https://docs.redhat.com/en/documentation/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant/2.x_latest/html-single/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant_release_notes/index
> AAP-25608: Lightspeed doc improvements

- attributes/attributes.adoc
- stories/topics/con-azure-security.adoc
- stories/topics/proc-azure-configure-ad-sso.adoc
- stories/topics/proc-azure-create-service-principal.adoc
Update the Azure docs: Microsoft Entra ID is replacing Azure Active Directory (Azure AD).
However, the AAP UI still contains Azure AD references, so these have not been changed.
> AAP-25848 Change Azure Active Directory (AD) to Microsoft Entra ID

- lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-26616. 
Change made:
Added a note stating 'Ansible code bot doesn't need IBM watsonx Code Assistant'
> AAP-26616: Added info. that code bot doesn't need IBM watsonx Code Assistant

- lightspeed/modules/proc_troubleshooting-vscode.adoc
This PR addresses AAP-23395, which was originally added to ongoing troubleshooting inline messages (AAP-22335) effort, but reusing it here because the troubleshooting activity is still WIP and delayed than originally planned. Content was reviewed as part of the ongoing error messaging effort. 
Change made:
Added error message about Ansible Lightspeed Task Generation in Playbooks does not work with Remote SSH Extension for workspaces with large number of roles.
> AAP-23395: Reused  known issue about using remote SSH extension from existing inline troubleshooting doc

- downstream/modules/platform/ref-controller-variables.adoc
Replaced Automation controller with {ControllerName}, and EDA with {EDAName}.
> Fixed naming content with proper attribute.

- downstream/modules/platform/ref-controller-variables.adoc
Replaced Automation controller with {ControllerName}, and EDA with {EDAName}.
> Fixed naming content with proper attribute. (#1527)

- downstream/modules/platform/proc-controller-use-an-exec-env.adoc
Fixed "typing error" to "type" in the Controller User Guide
AAP-24968
https://issues.redhat.com/browse/AAP-24968
> Fixed spelling error in Controller User Guide

- downstream/modules/platform/proc-controller-use-an-exec-env.adoc
Fixed "typing error" to "type" in the Controller User Guide
AAP-24968
https://issues.redhat.com/browse/AAP-24968
> Fixed spelling error in Controller User Guide (#1531)

- downstream/modules/platform/proc-controller-adding-new-inventory.adoc
- downstream/modules/platform/proc-scm-git-subversion.adoc
- downstream/titles/controller/controller-user-guide/docinfo.xml
Fix minor typos found in the user guide
https://issues.redhat.com/browse/AAP-26955
> Fix typo in User guide sub-heading

- downstream/assemblies/builder/assembly-open-source-license.adoc
- downstream/titles/builder/docinfo.xml
- downstream/titles/builder/master.adoc
2.5 backport for [PR 1566](https://github.com/ansible/aap-docs/pull/1566)
Add open-source license to Creating and using execution environments
https://issues.redhat.com/browse/AAP-26400
> AAP-26400 added open source license to creating and using ees (#1566)

- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/installer-24-71.adoc
- downstream/titles/release-notes/topics/installer-version-table.adoc
2.4 Release Notes - AAP 2.4-7.1 Bundle Installer release
https://issues.redhat.com/browse/AAP-26751
> 2.4 Add 2.4-7.1 bundle installer release to release notes

- downstream/modules/platform/con-gw-roles.adoc
- downstream/modules/platform/proc-gw-create-roles.adoc
- downstream/modules/platform/proc-gw-delete-roles.adoc
- downstream/modules/platform/proc-gw-edit-roles.adoc
- downstream/modules/platform/proc-gw-roles.adoc
This PR backports the changes from the #1572 to the 2.5 branch and includes the following changes:
* AAP-19920 Creating new modules for Roles
* AAP-19920 - corrections based on peer review
* AAP-19920 Added missing title for Roles concept module
> [Backport] AAP-19920 Convert/create modules for gateway roles (#1572)

- downstream/modules/platform/ref-system-requirements.adoc
Explicitly list RHEL 9.0 as supported in the base system requirements in the planning guide
Explicitly list RHEL 9 as supported
https://issues.redhat.com/browse/AAP-26227
> List RHEL 9.0 as supported in planning guide

- downstream/assemblies/platform/assembly-aap-backup.adoc
- downstream/assemblies/platform/assembly-aap-recovery.adoc
- downstream/assemblies/platform/assembly-configure-aap-operator.adoc
- downstream/assemblies/platform/assembly-installing-controller-operator.adoc
- downstream/assemblies/platform/assembly-installing-hub-operator.adoc
- downstream/modules/platform/con-ocp-supported-install.adoc
- downstream/modules/platform/con-resource-operator-overview.adoc
- downstream/modules/platform/proc-access-hub-operator-ui.adoc
- downstream/modules/platform/proc-add-controller-access-token.adoc
- downstream/modules/platform/proc-cli-get-controller-pwd.adoc
- downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
- downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
- downstream/modules/platform/proc-configuring-controller-route-options.adoc
- downstream/modules/platform/proc-controller-ingress-options.adoc
- downstream/modules/platform/proc-enable-hstore-extension.adoc
- downstream/modules/platform/proc-hub-ingress-options.adoc
- downstream/modules/platform/proc-hub-route-options.adoc
- downstream/modules/platform/proc-install-cli-aap-operator.adoc
- downstream/modules/platform/proc-operator-access-aap.adoc
- downstream/modules/platform/proc-operator-external-db-controller.adoc
- downstream/modules/platform/proc-operator-external-db-hub.adoc
- downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
- downstream/titles/aap-operator-installation/master.adoc
[AAP-20941](https://issues.redhat.com/browse/AAP-20941) - Install gateway
[AAP-22178](https://issues.redhat.com/browse/AAP-22718) - Gateway Backup and restore sections
Preparing operator docs ahead of the 2.5 EA release
Docs:
-  **Red Hat Ansible Automation Platform operator backup and recovery guide**
-  **Installing on OpenShift Container Platform** 
(formally known as the Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform) 
Locations:
Doc location: Downstream > titles > aap-operator-installation
Doc location Downstream > titles > aap-operator-backup
Updates:
- Updating existing chapters to allign ahead of the new Gateway content.
- Uncommenting the module include statements for gateway install
- Uncommenting module include statements for backup …
> Preparing the AAP Operator  guides for EA

- downstream/modules/platform/ref-controller-api-field-lookups.adoc
Addresses API behavior change from previous release regarding default exact matches.
https://issues.redhat.com/browse/AAP-27347
> Added note to API guide for filtering exact matches

- downstream/modules/platform/ref-controller-api-field-lookups.adoc
Addresses API behavior change from previous release regarding default exact matches.
https://issues.redhat.com/browse/AAP-27347
> Added note to API guide for filtering exact matches (#1606)

- downstream/snippets/technology-preview.adoc
Update the tech preview notice to follow the guidelines in the supplementary style guide.
Note that the snippet is generic and is not enclosed in an admonition.
This is so that we can reuse the snippet, for example:
```
[IMPORTANT]
====
<New Feature> is a Technology Preview feature only.
include::snippets/technology-preview.adoc[]
====
```
> Update tech preview notice per supplementary style guide

- downstream/snippets/technology-preview.adoc
Update the tech preview notice to follow the guidelines in the supplementary style guide.
Note that the snippet is generic and is not enclosed in an admonition.
This is so that we can reuse the snippet, for example:
```
[IMPORTANT]
====
<New Feature> is a Technology Preview feature only.
include::snippets/technology-preview.adoc[]
====
```
> 2.4 Update tech preview notice per supplementary style guide (#1639)

- downstream/snippets/technology-preview.adoc
Update the tech preview notice to follow the guidelines in the supplementary style guide.
Note that the snippet is generic and is not enclosed in an admonition.
This is so that we can reuse the snippet, for example:
```
[IMPORTANT]
====
<New Feature> is a Technology Preview feature only.
include::snippets/technology-preview.adoc[]
====
```
> 2.5 Update tech preview notice per supplementary style guide (#1639)

- downstream/aap-common/external-site-disclaimer.adoc
- downstream/assemblies/platform/assembly-platform-whats-next.adoc
- downstream/modules/platform/con-known-proxies.adoc
- downstream/modules/platform/con-sticky-sessions.adoc
- downstream/modules/platform/con-why-automation-mesh.adoc
- downstream/modules/platform/proc-aap-activate-with-credentials.adoc
- downstream/modules/platform/proc-aap-activate-with-manifest.adoc
- downstream/modules/platform/proc-configure-known-proxies.adoc
- downstream/modules/platform/proc-configuring-reverse-proxy.adoc
- downstream/modules/platform/proc-control-data-collection.adoc
- downstream/modules/platform/proc-enable-proxy-support.adoc
This PR backports the changes from #1604 to the 2.5 branch and includes the following:
* AAP-20549 - Implementing gateway UI changes into the Operations guide
* AAP-20540 - Updated information for user analytics tracking
> [Backport] AAP-20549 - Implementing gateway UI changes into the Operations guide (#1604)

- downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
As part of the docX initiative to improve operator docs I have reviewed and refreshed the EDA section which had outdated UI elements. [AAP-27987](https://issues.redhat.com/browse/AAP-27987)
- Updated the UI to be more accurate
- Reordered the steps to focus on form view instructions first, then YAML view. 
**Note**  if you're going to build the doc, the chapter for EDA is commented out of master as its not included in 2.5 presently
> [DocX] Updating the UI steps of the EDA Chapter of the deploy guide

- downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
As part of the docX initiative to improve operator docs I have reviewed and refreshed the EDA section which had outdated UI elements. [AAP-28105](https://issues.redhat.com/browse/AAP-28105)
Updated the UI to be more accurate
Reordered the steps to focus on form view instructions first, then YAML view.
> Updating the EDA section of the deploy guide (#1659)

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Update ordering and hierarchy of HA automation hub sections in VM-install guide
No file contents were updated, the files themselves are just being rearranged.
VM-install guide - HA automation hub should be moved up a level in the document hierarchy
https://issues.redhat.com/browse/AAP-28097
> Update ordering and hierarchy of HA automation hub sections in VM-install guide

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
VM-install guide - HA automation hub should be moved up a level in the document hierarchy
https://issues.redhat.com/browse/AAP-28097
> 2.5 Update ordering and hierarchy of HA automation hub sections in VM-install guide (#1664)

- downstream/modules/platform/ref-controller-trial-evaluation.adoc
update URL of trial license from ansible.com to redhat.com
https://issues.redhat.com/browse/AAP-26587
> Update URL of trial licence

- downstream/modules/platform/ref-controller-trial-evaluation.adoc
update URL of trial license from ansible.com to redhat.com
https://issues.redhat.com/browse/AAP-26587
> Update URL of trial licence (#1671)

- downstream/assemblies/platform/assembly-controller-organizations.adoc
- downstream/assemblies/platform/assembly-controller-teams.adoc
- downstream/assemblies/platform/assembly-controller-users.adoc
- downstream/assemblies/platform/assembly-gw-resources.adoc
This PR corrects the access management assemblies to include platform/ in the include statements.
> AAP-19236 fix include statements to include platform/

- downstream/modules/eda/con-eda-rulebook-activation-list-view.adoc
- downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
- downstream/modules/eda/proc-eda-view-activation-output.adoc
- downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc
This PR covers just a few sections of the EDA controller user guide since multiple sections are being covered under separate jiras that required changes beyond the scope of UI parity. 
Covered in this PR: 
- downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc (Settting up a new decision environment)
- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc (Setting up a rulebook activation)
- downstream/modules/eda/con-eda-rulebook-activation-list-view.adoc (Rulebook activation list view)
- downstream/modules/eda/proc-eda-view-activation-output.adoc (Viewing activation output)
- downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc (Viewing rule audit actions)
> AAP-20543 Ensure UI parity for just a couple of sections for EDA controller  guide

- downstream/modules/eda/con-eda-rulebook-activation-list-view.adoc
- downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
- downstream/modules/eda/proc-eda-view-activation-output.adoc
- downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc
This PR covers just a few sections of the EDA controller user guide since multiple sections are being covered under separate jiras that required changes beyond the scope of UI parity.
Covered in this PR:
downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc (Settting up a new decision environment)
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc (Setting up a rulebook activation)
downstream/modules/eda/con-eda-rulebook-activation-list-view.adoc (Rulebook activation list view)
downstream/modules/eda/proc-eda-view-activation-output.adoc (Viewing activation output)
downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc (Viewing rule audit actions)
> Backport-2.5-1682 Ensure UI parity for just a couple of sections for EDA controller 

- downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Add steps for configuring mTLS authentication for user provided databases in the VM-install guide. This includes example inventory files.
Affects: VM-install guide i.e. aap-installation-guide
[Docs] - Add certificate auth support for postgres.py
https://issues.redhat.com/browse/AAP-27560
> Add steps for configuring mTLS authentication for user provided DBs

- downstream/attributes/attributes.adoc
Create attributes for docs titles so that external links to other docs in the AAP docset don't break when titles are updated.
Backports #1589
> 2.5 AAP-27260 Add attributes for docs titles (#1589)

- downstream/modules/eda/con-modifying-simultaneous-activations.adoc
- downstream/modules/eda/proc-modifying-activations-after-install.adoc
- downstream/modules/eda/proc-modifying-memory-after-install.adoc
- downstream/modules/eda/ref-performance-troubleshooting.adoc
Applied updates specifically for 2.5 GA, per information from SME @jamesmarshall24 , and other syntactical/UI/style edits (found during peer review for backporting the chapter to 2.5 branch and general discovery while working on content).
> AAP-28448 Update performance tuning chapter in EDA controller user guide for 2.5

- downstream/modules/eda/con-modifying-simultaneous-activations.adoc
- downstream/modules/eda/proc-modifying-activations-after-install.adoc
- downstream/modules/eda/proc-modifying-memory-after-install.adoc
- downstream/modules/eda/ref-performance-troubleshooting.adoc
Applied updates specifically for 2.5 GA, per information from SME @jamesmarshall24 , and other syntactical/UI/style edits (found during peer review for backporting the chapter to 2.5 branch and general discovery while working on content).
Updates to the following: 
- downstream/modules/eda/con-modifying-simultaneous-activations.adoc
- downstream/modules/eda/proc-modifying-activations-after-install.adoc
- downstream/modules/eda/proc-modifying-memory-after-install.adoc
- downstream/modules/eda/ref-performance-troubleshooting.adoc
> Backport-2.5-1676 Update performance tuning chapter in EDA controller user guide

- downstream/modules/platform/ref-controller-variables.adoc
- downstream/modules/platform/ref-gateway-variables.adoc
Updates the following inventory file variables in the VM installer guide:
Add:
- automationgateway_admin_email
- automationgateway_admin_username
- admin_username
- admin_email
Remove:
- automationcontroller_password
- automationcontroller_username
Update:
- automationgateway_admin_password
- admin_password
Affects: VM-install guide - titles/aap-installation-guide
AAP 2.5 Update the inventory file variables in the VM Install guide
https://issues.redhat.com/browse/AAP-27328
> Update inventory file variables for controller and gateway

- downstream/modules/platform/ref-controller-variables.adoc
- downstream/modules/platform/ref-gateway-variables.adoc
Updates the following inventory file variables in the VM installer guide:
Add:
- automationgateway_admin_email
- automationgateway_admin_username
- admin_username
- admin_email
Remove:
- automationcontroller_password
- automationcontroller_username
Update:
- automationgateway_admin_password
- admin_password
Affects: VM-install guide - titles/aap-installation-guide
AAP 2.5 Update the inventory file variables in the VM Install guide
https://issues.redhat.com/browse/AAP-27328
> 2.5 Update inventory file variables for controller and gateway (#1697)

- downstream/assemblies/platform/assembly-gw-dashboard.adoc
This PR backports the changes from #1700 to the 2.5 branch and includes the following:
* AAP-18761-A - add assembly for the gateway dashboard
* AAP-18761-A - include peer review changes
> [Backport] AAP-18761-A - add assembly for the gateway dashboard (#1700)

- downstream/modules/builder/con-ee-precedence.adoc
[Docs] DEFAULT_EXECUTION_ENVIRONMENT setting is not present at api/v2/settings/jobs/ as mentioned in AAP document
https://issues.redhat.com/browse/AAP-28741
> Updated default execution environment setting

- downstream/modules/builder/con-ee-precedence.adoc
[Docs] DEFAULT_EXECUTION_ENVIRONMENT setting is not present at api/v2/settings/jobs/ as mentioned in AAP document
https://issues.redhat.com/browse/AAP-28741
> Updated default execution environment setting (#1708)

- downstream/modules/platform/proc-running-setup-script.adoc
Update text in docs to tell users ansible-core 2.16 must be installed before running setup.sh
https://issues.redhat.com/browse/AAP-29119
> Add admonition to use of installer setup script

- downstream/modules/platform/proc-running-setup-script.adoc
Update text in docs to tell users ansible-core 2.16 must be installed before running setup.sh
https://issues.redhat.com/browse/AAP-29119
> Add admonition to use of installer setup script (#1718)

- downstream/modules/platform/proc-create-secret-key-secret.adoc
Link to Jira issue: [AAP-28685](https://issues.redhat.com/browse/AAP-28685)
- Revised typo in secret example to use `password` instead of `secret_key`
- Added note for additional context.
> AAP-28685: Fix typo in secret example

- downstream/modules/platform/con-operator-upgrade-prereq.adoc
Fixed broken link...URL missing forward-slash between ``documentation/red_hat_ansible``.. URL needs to be: https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_operator_backup_and_recovery_guide/index#aap-backup-recommendations
> Fixed broken link to Backup recommendations section

- downstream/modules/platform/con-operator-upgrade-prereq.adoc
Fixed broken link...URL missing forward-slash between ``documentation/red_hat_ansible``: https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html-single/red_hat_ansible_automation_platform_operator_backup_and_recovery_guide/index#aap-backup-recommendations
> Fixed broken link to Backup recommendations section (#1723)

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Remove EDA 2.5 w/controller 2.4 install steps from 2.5 doc
https://issues.redhat.com/browse/AAP-29246
Affects 'titles/aap-installation-guide'
> Removing EDA 2.5 with controller 2.4 install steps

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Remove EDA 2.5 w/controller 2.4 install steps from 2.5 doc
https://issues.redhat.com/browse/AAP-29246
Affects 'titles/aap-installation-guide'
> Removing EDA 2.5 with controller 2.4 install steps (#1728)

- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Just one update made for the Create Rulebook Activations fields: Service Name. Other more extensive changes will be tracked in a separate PR.
> Backport-2.5-1722 (AAP-21827) Add new field for the k8s_service_name

- downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
AAP-29276 Add minimum Python 3.10 requirement to navigator doc
Affects `/titles/navigator`
> AAP-29276 Add minimum Python 3.10 requirement to navigator doc

- downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
AAP-29276 Add minimum Python 3.10 requirement to navigator doc
Affects `/titles/navigator`
> 2.4 AAP-29276 Add minimum Python 3.10 requirement to navigator doc (#1738)

- downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
AAP-29276 Add minimum Python 3.10 requirement to navigator doc
Affects `/titles/navigator`
> 2.5 AAP-29276 Add minimum Python 3.10 requirement to navigator doc (#1738)

- downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
- downstream/snippets/container-upgrades.adoc
Document the requirement that upgrade from 2.4 containerized TP is not supported
Created a snippet for this text /snippets/container-upgrades.adoc
https://issues.redhat.com/browse/AAP-28343
> Document the requirement that upgrade from 2.4 containerized TP is not supported

- lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
- lightspeed/modules/proc_configure-vscode-extension-onpremise-deployment.adoc
- lightspeed/modules/proc_create-connection-secrets.adoc
- lightspeed/modules/proc_create-lightspeed-instance.adoc
- lightspeed/modules/proc_create-oauth-app.adoc
- lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc
- lightspeed/modules/proc_update-connection-secrets.adoc
- lightspeed/modules/proc_update-redirect-uri.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-29499.
Changes made:
- Reverted changes made in PR https://github.com/ansible/aap-docs/pull/1707. Some additional steps need to be added to the procedure, and because the PR is merged, this ticket reverses that change and starts afresh.
- Added hyperlinks to the 'troubleshooting on-prem deployment issues' topic from 'Setting up Lightspeed on-premise deployment'
> AAP-29499: Added on-prem troubleshooting cross-reference and removed on-prem monitoring content

- lightspeed/modules/con_lightspeed-key-features.adoc
- lightspeed/titles/lightspeed-release-notes/modules/lightspeed-intro.adoc
- lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-august2024.adoc
- lightspeed/titles/lightspeed-user-guide/master.adoc
This PR is an addendum to JIRA https://issues.redhat.com/browse/AAP-25298.
Changes made:
- Added 'Lightspeed trials' info. in key features section.
- Added cross ref. to 'Lightspeed trials' topic in the release notes.
- Removed a duplicate section 'logging in to Lightspeed admin portal'
> AAP-25298-update: Updated trial urls and removed duplicate topic

- downstream/assemblies/platform/assembly_metrics-utility.adoc
- downstream/modules/platform/proc_configuring-the-metrics-utility.adoc
- downstream/modules/platform/proc_modifying-the-run-schedule.adoc
- downstream/modules/platform/ref_fetching-a-monthly-report.adoc
This is the backport for [PR 1735](https://github.com/ansible/aap-docs/pull/1735/files). It backports the work in that PR to the 2.5 branch. 
See [AAP-19692](https://issues.redhat.com/browse/AAP-19692) for more detail.
> Document the Metric Collection Utility (#1735)

- downstream/modules/eda/proc-eda-set-up-token.adoc
For the EDA controller user guide, chapter 5.1, tweaked the note after step 5 to include permissions to execute job and workflow templates. (Note: this update will occur in the 2.4 guide, but will be applied to 2.5 separately since the process will change slightly.)
> AAP-24690 Tweaked note after step 5 in Chapter 5 EDA controller user guide

- downstream/modules/eda/proc-eda-set-up-token.adoc
For the EDA controller user guide, chapter 5.1, tweaked the note after step 5 to include permissions to execute job and workflow templates. (Note: this update will occur in the 2.4 guide, but will be applied to 2.5 separately since the process will change slightly.)
> AAP-24690 Tweaked note about write-scope status for controller token

- downstream/assemblies/platform/assembly-controller-organizations.adoc
- downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
- downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
- downstream/assemblies/platform/assembly-gw-managing-access.adoc
- downstream/assemblies/platform/assembly-gw-managing-authentication.adoc
- downstream/assemblies/platform/assembly-gw-mapping.adoc
- downstream/assemblies/platform/assembly-gw-roles.adoc
- downstream/assemblies/platform/assembly-gw-settings.adoc
- downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
- downstream/modules/platform/ref-controller-organization-notifications.adoc
- downstream/titles/central-auth/docinfo.xml
- downstream/titles/central-auth/master.adoc
- downstream/titles/central-auth/platform
This PR backports the changes from #1769 to the 2.5 branch and includes the following:
* AAP-29223 - Create structure for Access management and authentication guide
* AAP29223 - add symlink to assemblies/platform
* AAP-29223 - formatting fixes
* AAP-29223 Fixed duplicate ids in assemlies and other corrections
> [Backport] AAP-29223 - Create structure for Access management and authentication (#1769)

- downstream/archive/archived-modules/platform/con-inventory-introduction.adoc
- downstream/modules/platform/ref-controller-database-settings.adoc
Added warning that the air-gapped exception to the deprecation of manifests, which currently applies to all other use cases, is disappearing with Satellite 6.16 as per AAP-15722.
> Added warning to "About inventory installer file" AAP-15722

- downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
AAP-29953 Fix YAML indentation in devtools example playbook
Backports #1787 to 2.4
> 2.4 AAP-29953 Fix YAML indentation in devtools example playbook (#1787)

- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Added a note at the end of [section 6.1 Setting up a rulebook activation](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/event-driven_ansible_controller_user_guide/index#eda-set-up-rulebook-activation) in the EDA controller user guide to inform users that when an activation shuts down, any tasks that are waiting to be performed will be canceled and an info level message will be sent to the activation log. Tracked in jira [AAP-24694](https://issues.redhat.com/browse/AAP-24694).
> Backport-2.5-1385 (AAP-24694) Added note about rulebook activations shutting down and canceling jobs on controller

- downstream/modules/platform/ref-controller-database-settings.adoc
Backport of PR #1780
Added warning that the air-gapped exception to the deprecation of manifests, which currently applies to all other use cases, is disappearing with Satellite 6.16 as per AAP-15722.
> Backport of AAP-15722: about inventory install file

- downstream/modules/platform/proc-controller-add-organization-user.adoc
- downstream/modules/platform/proc-controller-creating-a-team.adoc
- downstream/modules/platform/proc-controller-creating-a-user.adoc
- downstream/modules/platform/proc-controller-deleting-a-user.adoc
- downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
- downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
- downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
- downstream/modules/platform/proc-controller-github-organization-setttings.adoc
- downstream/modules/platform/proc-controller-github-settings.adoc
- downstream/modules/platform/proc-controller-github-team-settings.adoc
- downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
- downstream/modules/platform/proc-controller-set-up-LDAP.adoc
- downstream/modules/platform/proc-controller-set-up-SAML.adoc
- downstream/modules/platform/proc-controller-set-up-azure.adoc
- downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
- downstream/modules/platform/proc-controller-set-up-radius.adoc
- downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
- downstream/modules/platform/proc-controller-user-permissions.adoc
- downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
- downstream/modules/platform/proc-gw-local-authentication.adoc
- downstream/modules/platform/proc-gw-remove-roles-team.adoc
- downstream/modules/platform/proc-gw-remove-roles-user.adoc
- downstream/modules/platform/ref-controller-user-roles.adoc
This PR backports the changes from #1760 to the 2.5 branch and includes the following: 
* AAP-29213 - Convert authentication type content
* AAP-29213 - fixing formatting issues
* AAP-29213 - fixed duplicate id and removed duplicate file
* AAP-29213 - fix snippets formatting in local auth
* AAP-29213 - Fixed formatting issues to get a clean build
* AAP-29213 - removing an unused file
* AAP-29213 - formatting fixes and UI updates
* AAP-29213 - Fixed missing space in a step and replaced erroneous keycloak content
* AAP-29213 - incorporating peer review feedback
> [Backport] - AAP-29213 - Convert authentication type content (#1760)

- downstream/assemblies/platform/assembly-inventory-introduction.adoc
- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
- downstream/modules/platform/proc-set-registry-username-password.adoc
- downstream/modules/platform/ref-general-inventory-variables.adoc
Add to docs to create a token at access.redhat.com/terms-based-registry/accounts is necessary for entering a registry_username and registry_password
https://issues.redhat.com/browse/AAP-29120
> Add procedure to set registry variables

- downstream/assemblies/platform/assembly-VM-eda-controller-install.adoc
- downstream/assemblies/platform/assembly-eda-controller-post-install.adoc
- downstream/modules/platform/con-VM-install-eda-post-steps.adoc
- downstream/titles/eda-controller/eda-controller-install/docinfo.xml
- downstream/titles/eda-controller/eda-controller-install/master.adoc
Adding steps for VM install with hub and removing operator and container based steps
VM - New content to install and configure EDA 2.5 with controller 2.4
https://issues.redhat.com/browse/AAP-23518
Affects `titles/eda-controller/eda-controller-install`
> Adding post install steps for VM install

- downstream/assemblies/platform/assembly-configure-aap-operator.adoc
- downstream/modules/platform/con-ocp-supported-install.adoc
- downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
- downstream/modules/platform/proc-operator-deploy-central-config.adoc
[AAP-30293](https://issues.redhat.com/browse/AAP-30293)
Updating incorrect use of Note admonition in the Installing on OpenShift Container Platform document. Converting these instances to the correct format.
i.e From "NOTE:" to [NOTE] with '===='
> fixing note adminotions (#1809)

- downstream/archive/archived-assemblies/platform/assembly-aap-manifest-files.adoc
- downstream/titles/aap-operations-guide/master.adoc
[AAP-30336](https://issues.redhat.com/browse/AAP-30336) 
Commented out [Ch 2 Obtaining a file manifest](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_operations_guide/assembly-aap-obtain-manifest-files#assembly-aap-obtain-manifest-files) within the Operations guide to avoid duplication with Access management and authentication 
Archived assembly-aap-manifest-files.adoc
> AAP-30336 remove subscription info from operations guide

- downstream/archive/archived-assemblies/platform/assembly-aap-manifest-files.adoc
- downstream/titles/aap-operations-guide/master.adoc
2.5 backport of [PR 1817](https://github.com/ansible/aap-docs/pull/1817)
[AAP-30336](https://issues.redhat.com/browse/AAP-30336)
Commented out [Ch 2 Obtaining a file manifest](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_operations_guide/assembly-aap-obtain-manifest-files#assembly-aap-obtain-manifest-files) within the Operations guide to avoid duplication with Access management and authentication
Archived assembly-aap-manifest-files.adoc
> AAP-30336 remove subscription info from operations guide (#1817)

- downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
- downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
- downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
- downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
- downstream/titles/central-auth/master.adoc
This PR fixes typos in leveloffsets and other formatting to correct the chapter layout of the document.
> am-formatting-2 - Fixing issues with document structure/chapter breakdown

- downstream/assemblies/eda/assembly-eda-projects.adoc
- downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Added notes in 3 places about the impact of HA Redis failure on EDA controller resources:
- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
- downstream/assemblies/eda/assembly-eda-projects.adoc
- downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
> AAP-28434 Added notes about the impact of Redis failure on EDA controller resources

- downstream/assemblies/eda/assembly-eda-projects.adoc
- downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Added notes in 3 places about the impact of HA Redis failure on EDA controller resources:
downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
downstream/assemblies/eda/assembly-eda-projects.adoc
downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
> Backport-2.5-1830 AAP-28434 Added notes about the impact of Redis failure on EDA controller resources

- downstream/titles/hub/managing-content/docinfo.xml
- downstream/titles/hub/managing-content/master.adoc
This PR fixes the title for the Managing content document to reflect what was decided in the Miro board https://miro.com/app/board/uXjVNGGa88w=/
> Fix the title for Managing content document

- downstream/assemblies/topologies/assembly-ocp-topologies.adoc
- downstream/titles/topologies/master.adoc
2.5 backport of [PR 1837](https://github.com/ansible/aap-docs/pull/1837)
[AAP-28228](https://issues.redhat.com/browse/AAP-28228)
Files added:
assembly-ocp-topologies.adoc
topologies/master.adoc
> AAP-28228 added OCP assembly (#1837)

- downstream/titles/hub/managing-content/docinfo.xml
- downstream/titles/hub/managing-content/master.adoc
This PR fixes the Managing automation content in Ansible Automation Platform to Managing automation content per Slack conversation here: https://redhat-internal.slack.com/archives/C04NT5T2V28/p1725639042037859
> Fix Managing content document title to remove AAP

- downstream/titles/hub/managing-content/docinfo.xml
- downstream/titles/hub/managing-content/master.adoc
This PR backports the changes from #1844 to the 2.5 branch.
> [Backport] Fix Managing content document title to remove AAP (#1844)

- downstream/assemblies/topologies/assembly-ocp-topologies.adoc
- downstream/modules/topologies/ref-ocp-a-env-a.adoc
- downstream/modules/topologies/ref-ocp-b-env-a.adoc
2.5 backport of [PR 1843](https://github.com/ansible/aap-docs/pull/1843)
[AAP-28228](https://issues.redhat.com/browse/AAP-28228)
Files added:
ref-ocp-a-env-a.adoc
ref-ocp-b-env-a.adoc
assembly-ocp-topologies.adoc
> AAP-28228-A added ref modules for OCP (#1843)

- downstream/modules/platform/ref-guidelines-hosts-groups.adoc
2.4 backport of PR 1861
[AAP-29177](https://issues.redhat.com/browse/AAP-29177)
Updated language around symbol restrictions for creating hostnames
> AAP-29177 updated FDQN guidelines (#1861)

- downstream/titles/analytics/job-explorer/master.adoc
Remove attributes from `master.adoc` for _Evaluating your Automation controller job runs using the Job Explorer_ to prevent Pantheon build failures. 
Only needed for 2.3: 2.4 and 2.5 are OK.
Affects `titles/analytics/job-explorer`
> Remove attributes from job-explorer title

- downstream/attributes/attributes.adoc
Backport to 2.5
Update the title attribute for the Navigator guide.
The title files were updated in #1887
> Update title attributes for navigator

- downstream/attributes/attributes.adoc
Update the title attribute for the Navigator guide.
The title files were updated in 2.5 in https://github.com/ansible/aap-docs/pull/1888
> 2.5 Update title attributes for navigator (#1891)

- downstream/titles/aap-installation-guide/master.adoc
- downstream/titles/aap-operations-guide/master.adoc
- downstream/titles/aap-operator-backup/master.adoc
- downstream/titles/aap-operator-installation/master.adoc
- downstream/titles/aap-planning-guide/master.adoc
- downstream/titles/automation-mesh/docinfo.xml
- downstream/titles/automation-mesh/master.adoc
- downstream/titles/central-auth/master.adoc
- downstream/titles/dev-guide/master.adoc
- downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
- downstream/titles/hub/getting-started/master.adoc
- downstream/titles/hub/high-availability/master.adoc
- downstream/titles/hub/install/master.adoc
- downstream/titles/hub/manage-containers/master.adoc
- downstream/titles/ocp_performance_guide/master.adoc
- downstream/titles/upgrade/master.adoc
- downstream/titles/worker-install/master.adoc
2.3 Remove attributes from title names because they're causing build failures in Pantheon.
> 2.3 Remove attributes from title names

- downstream/assemblies/platform/assembly-inventory-introduction.adoc
AAP-29296-B: child of [AAP-29296](https://issues.redhat.com/browse/AAP-29296)
Updated **Chapter 8. About the installer inventory file** of the Planning guide. See [[WIP] v2.5 Red Hat Ansible Automation Platform planning guide](https://docs.google.com/document/d/1tCXiQxr0WspctajD7Hxwji9zsaOaPMl-WhRsB1sF-qs/edit).
Modified files:
- assembly-inventory-introduction.adoc
> AAP-29296-B updated About the installer inventory file

- downstream/assemblies/platform/assembly-inventory-introduction.adoc
2.5 backport of [PR 1917](https://github.com/ansible/aap-docs/pull/1917)
AAP-29296-B: child of [AAP-29296](https://issues.redhat.com/browse/AAP-29296)
Updated Chapter 8. About the installer inventory file of the Planning guide. See [[WIP] v2.5 Red Hat Ansible Automation Platform planning guide](https://docs.google.com/document/d/1tCXiQxr0WspctajD7Hxwji9zsaOaPMl-WhRsB1sF-qs/edit).
Modified files:
assembly-inventory-introduction.adoc
> AAP-29296-B updated About the installer inventory file (#1917)

- downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
- downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-playbooks.adoc
- downstream/modules/devtools/proc-devtools-extension-run-ansible-navigator.adoc
- downstream/modules/devtools/proc-devtools-testing-playbook.adoc
Update docs to use attributes for referencing the Navigator title and URL.
Affects 
* `titles/troubleshooting-aap/`
* `titles/upgrade/`
* `titles/develop-automation-content/`
> 2.4 Use attributes to reference Navigator Title and URL (#1894)

- downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
- downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-playbooks.adoc
- downstream/modules/devtools/proc-devtools-extension-run-ansible-navigator.adoc
- downstream/modules/devtools/proc-devtools-testing-playbook.adoc
Update docs to use attributes for referencing the Navigator title and URL.
Affects 
* `titles/troubleshooting-aap/`
* `titles/upgrade/`
* `titles/develop-automation-content/`
> 2.5 Use attributes to reference Navigator Title and URL (#1894)

- downstream/modules/platform/proc-controller-set-up-SAML.adoc
This PR fixes the example under the step for SAML Security Config to have the parameters on a line by themselves for easier usability.
> AAP-26512 - Update example for SAML Security Config per SME feedback

- downstream/assemblies/platform/assembly-disconnected-installation.adoc
- downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
- downstream/modules/platform/proc-completing-post-installation-tasks.adoc
- downstream/modules/platform/proc-creating-a-new-web-server-to-host-repositories.adoc
- downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
- downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Commented out several sections due to obsolescence. Made edits to update version numbers, context, system requirements, etc.
These changes were made due to the new installation methods which simplify both installation in a connected, and disconnected network.
Partially resolves: AAP-30807
> AAP-30807 Commented out, and updated text for the 2.5 release.

- downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc
- downstream/assemblies/platform/assembly-controller-secret-management.adoc
- downstream/modules/platform/con-controller-overview-details.adoc
- downstream/modules/platform/con-controller-role-based-access-controls.adoc
- downstream/modules/platform/proc-controller-configure-analytics.adoc
- downstream/modules/platform/proc-controller-importing-subscriptions.adoc
- downstream/modules/platform/proc-controller-view-host.adoc
- downstream/modules/platform/ref-controller-analytics-reports.adoc
- downstream/modules/platform/ref-controller-automation-analytics.adoc
- downstream/modules/platform/ref-controller-content-sourcing.adoc
- downstream/titles/controller/controller-admin-guide/master.adoc
- downstream/titles/controller/controller-user-guide/master.adoc
This PR backports the changes from #1867 to the 2.5 branch and includes the following:
* Removing TBDs from Controller docs
Remove TBDs from Controller documentation
https://issues.redhat.com/browse/AAP-30985
* Removing TBDs from Controller docs
Added link
Remove TBDs from Controller documentation
https://issues.redhat.com/browse/AAP-30985
* Removing TBDs from Controller docs
Added Analytics back to Configuring AE
Remove TBDs from Controller documentation
https://issues.redhat.com/browse/AAP-30985
* Adding changes to Ian's PR-1867 in his absence
---------
> [Backport] Removing TBDs from Controller docs (#1867)

- downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
AAP-30716 Add YAML separator in devtools example
> AAP-30716 Add YAML separator in devtools example

- downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
AAP-30716 Add YAML separator in devtools example
Backports https://github.com/ansible/aap-docs/pull/1942
> 2.4AAP-30716 Add YAML separator in devtools example (#1942)

- downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
AAP-30716 Add YAML separator in devtools example
Backports https://github.com/ansible/aap-docs/pull/1942
> 2.5 AAP-30716 Add YAML separator in devtools example (#1942)

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
- downstream/modules/platform/con-adding-subscription-manifest.adoc
- downstream/modules/platform/con-ha-hub-installation.adoc
- downstream/modules/platform/con-install-scenario-recommendations.adoc
- downstream/modules/platform/proc-running-setup-script.adoc
- downstream/modules/platform/proc-set-registry-username-password.adoc
- downstream/modules/platform/proc-verify-aap-installation.adoc
- downstream/modules/platform/ref-gateway-controller-ext-db.adoc
- downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
Backport for[ PR#1936](https://github.com/ansible/aap-docs/pull/1936)
Using [RPM installation 2.5 Draft](https://docs.google.com/document/d/1fIrlSrj8bSSWBVptXWmm0ZFixhZ4mM5pW2CQx_3Oh7A/edit#heading=h.iaypu8e8mkj4) as source of truth.
NOTE that I left out content from section Adding a safe variable plugin to Event-Driven Ansible controller. This section is part of [PR#1794](https://github.com/ansible/aap-docs/pull/1794/files) - content created by @jself-sudoku. To merge after this assembly has been successfully merged and backported.
[AAP-30807](https://issues.redhat.com/browse/AAP-30807) Converting platform/assembly-platform-install-scenario.adoc
Link to [2.5 install guide tracker](https://docs.google.com/spreadsheets/d/1APv4UzRGABm8ItMtTY6aiIcxWBtGU_sA/edit?gid=679299608#gid=679299608)
> [2.5] AAP-30807: Edit 2.4 links (#1936)

- downstream/assemblies/platform/assembly-gw-settings.adoc
- downstream/modules/platform/proc-controller-configure-subscriptions.adoc
- downstream/modules/platform/proc-settings-gw-additional-options.adoc
- downstream/modules/platform/proc-settings-gw-custom-login.adoc
- downstream/modules/platform/proc-settings-gw-password-security.adoc
- downstream/modules/platform/proc-settings-gw-security-options.adoc
- downstream/modules/platform/proc-settings-gw-session-options.adoc
- downstream/modules/platform/proc-settings-platform-gateway.adoc
- downstream/modules/platform/proc-settings-troubleshooting.adoc
- downstream/modules/platform/proc-settings-user-preferences.adoc
This PR backports the changes from #1956 to the 2.5 branch and includes the following: 
* AAP-30592 - Divide the Platform gateway settings into separate procedures by option
* AAP-30592 - implemented peer review fixes
> [Backport] AAP-30592 - Divide the Platform gateway settings into separate procedures by option (#1956)

- downstream/assemblies/platform/assembly-aap-platform-components.adoc
- downstream/assemblies/platform/assembly-inventory-introduction.adoc
- downstream/modules/platform/con-about-platform-gateway.adoc
- downstream/modules/platform/ref-guidelines-hosts-groups.adoc
AAP-29296-B: child of [AAP-29296](https://issues.redhat.com/browse/AAP-29296)
Updated Planning guide with Platform gateway content. See [[WIP] v2.5 Red Hat Ansible Automation Platform planning guide](https://docs.google.com/document/d/1tCXiQxr0WspctajD7Hxwji9zsaOaPMl-WhRsB1sF-qs/edit).
Modified files:
- assembly-inventory-introduction.adoc
- con-about-platform-gateway.adoc
- ref-guidelines-hosts-groups.adoc
> AAP-29296-D added platform gateway content to the planning guide

- downstream/assemblies/platform/assembly-aap-platform-components.adoc
- downstream/assemblies/platform/assembly-inventory-introduction.adoc
- downstream/modules/platform/con-about-platform-gateway.adoc
- downstream/modules/platform/ref-guidelines-hosts-groups.adoc
2.5 backport of [PR 1953](https://github.com/ansible/aap-docs/pull/1953)
AAP-29296-B: child of [AAP-29296](https://issues.redhat.com/browse/AAP-29296)
Updated Planning guide with Platform gateway content. See [[WIP] v2.5 Red Hat Ansible Automation Platform planning guide](https://docs.google.com/document/d/1tCXiQxr0WspctajD7Hxwji9zsaOaPMl-WhRsB1sF-qs/edit).
Modified files:
- assembly-inventory-introduction.adoc
- con-about-platform-gateway.adoc
- ref-guidelines-hosts-groups.adoc
> AAP-29296-D added platform gateway content to the planning guide (#1953)

- downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
2.5 backport of [PR 1966](https://github.com/ansible/aap-docs/pull/1966)
Added xrefs to assembly-overview-tested-deployment-models.adoc
> AAP-28228-C added xrefs to topology table (#1966)

- downstream/titles/aap-operations-guide/master.adoc
This PR removes the activating manifest files from the Operations guide because the content as moved to the Access management guide.
> opg-fix - Removed activating manifest files 

- downstream/assemblies/platform/assembly-controller-secret-management.adoc
- downstream/modules/platform/ref-controller-config-json.adoc
This PR fixes broken xrefs in the Using automation execution guide caused by content being moved to the new Access management or other guide.
> cae-fix - Correcting broken xrefs due to information moving to a new document

- downstream/assemblies/platform/assembly-controller-secret-management.adoc
- downstream/modules/platform/ref-controller-config-json.adoc
This PR backports the changes from #1985 to the 2.5 branch.
> [Backport] cae-fix - Correcting broken xrefs due to information moving to a new document (#1985)

- downstream/titles/aap-operations-guide/master.adoc
This PR backports the changes from #1983 to the 2.5 branch.
> [Backport] opg-fix - Removed activating manifest files because this is now covered in the access management guide (#1983)

- downstream/modules/platform/ref-eda-controller-variables.adoc
This PR fixes a few errors in the EDA variables that were preventing the installation guide from building.
> edavar - Fixed errors in the EDA variables preventing the doc from building

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
- downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc
- downstream/modules/platform/proc-add-insights-plugin-eda-variable.adoc
Added a new procedure:
- downstream/titles/aap-installation-guide/platform/platform/proc-add-eda-safe-plugin-var.adoc
> AAP-25510 Create safe plugin variable for Red Hat Insights EDA plugin and others

- downstream/assemblies/platform/assembly-system-requirements.adoc
- downstream/modules/platform/ref-OCP-system-requirements.adoc
- downstream/modules/platform/ref-RPM-system-requirements.adoc
- downstream/modules/platform/ref-containerized-system-requirements.adoc
2.5 backport of [PR 1915](https://github.com/ansible/aap-docs/pull/1915)
AAP-29296-A: child of [AAP-29296](https://issues.redhat.com/browse/AAP-29296)
Updated system requirements section of the Planning guide. See [[WIP] v2.5 Red Hat Ansible Automation Platform planning guide](https://docs.google.com/document/d/1tCXiQxr0WspctajD7Hxwji9zsaOaPMl-WhRsB1sF-qs/edit).
Files added:
ref-OCP-system-requirements.adoc
ref-RPM-system-requirements.adoc
ref-containerized-system-requirements.adoc
assemblies/platform/assembly-system-requirements.adoc
> AAP-29296-A updated system requirements (#1915)

- downstream/assemblies/platform/assembly-network-ports-protocols.adoc
[AAP-29295](https://issues.redhat.com/browse/AAP-29295?filter=-1)
Updated **Table 2. Network ports and protocols** within the _Planning guide_. See  [[WIP] v2.5 Red Hat Ansible Automation Platform planning guide](https://docs.google.com/document/d/1tCXiQxr0WspctajD7Hxwji9zsaOaPMl-WhRsB1sF-qs/edit) for source.
- assembly-network-ports-protocols.adoc
> AAP-29295-A updated network ports and protocols table

- downstream/assemblies/platform/assembly-network-ports-protocols.adoc
2.5 backport of [PR 2009](https://github.com/ansible/aap-docs/pull/2009)
[AAP-29295](https://issues.redhat.com/browse/AAP-29295?filter=-1)
Updated Table 2. Network ports and protocols within the Planning guide. See [[WIP] v2.5 Red Hat Ansible Automation Platform planning guide](https://docs.google.com/document/d/1tCXiQxr0WspctajD7Hxwji9zsaOaPMl-WhRsB1sF-qs/edit) for source.
assembly-network-ports-protocols.adoc
> AAP-29295-A updated network ports and protocols table (#2009)

- downstream/modules/platform/ref-eda-controller-variables.adoc
This PR backports the changes from #1996 to the 2.5 branch.
> [Backport] edavar - Fixed errors in the EDA variables preventing the doc from building (#1996)

- downstream/modules/platform/proc-controller-set-up-SAML.adoc
This PR adds the example to the SAML security config step per https://issues.redhat.com/browse/AAP-26512
> 26512 - put SAML security config example in the 2.4 content

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
- downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc
Added a new procedure to installation scenarios section of the Installation guide:
- downstream/titles/aap-installation-guide/platform/platform/proc-add-eda-safe-plugin-var.adoc
> Backport-2.5-1784 (AAP-25510) Create safe plugin variable for various plugins

- downstream/modules/platform/proc-gw-create-roles.adoc
- downstream/modules/platform/proc-gw-delete-roles.adoc
- downstream/modules/platform/proc-gw-edit-roles.adoc
- downstream/modules/platform/proc-gw-roles.adoc
- downstream/snippets/snip-gw-roles-note-multiple-components.adoc
This PR backports the changes from #2023 to the 2.5 branch.
> [Backport] AAP-31745 - Reconcile chapter 6 of the Access management guide (#2023)

- downstream/modules/topologies/ref-cont-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-b.adoc
Update the Redis port numbers in the Network ports and protocols tables for the following topologies:
- RPM-B-ENV-A
- RPM-B-ENV-B
- CONT-B-ENV-A
> Update port numbers in topology docs

- downstream/modules/topologies/ref-cont-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-b.adoc
Update the Redis port numbers in the Network ports and protocols tables for the following topologies:
- RPM-B-ENV-A
- RPM-B-ENV-B
- CONT-B-ENV-A
> 2.5 Update port numbers in topology docs (#2037)

- downstream/modules/platform/proc-install-aap-operator.adoc
- downstream/modules/platform/proc-install-cli-aap-operator.adoc
[AAP-31823](https://issues.redhat.com/browse/AAP-31823)
Adding the following 'Important note' to both install chapters (chapter 2 and 3):
"You can only install a single instance of the {OperatorPlatform} into a single namespace. 
Installing multiple instances in the same namespace can lead to improper operation for both operator instances."
Also made some minor tweaks to word choice and active voice.
> Add install-related note to operator install doc

- downstream/modules/platform/proc-install-aap-operator.adoc
- downstream/modules/platform/proc-install-cli-aap-operator.adoc
[AAP-31823](https://issues.redhat.com/browse/AAP-31823)
Adding the following 'Important note' to both install chapters (chapter 2 and 3):
"You can only install a single instance of the {OperatorPlatform} into a single namespace.
Installing multiple instances in the same namespace can lead to improper operation for both operator instances."
Also made some minor tweaks to word choice and active voice.
> Adding note on installing to a single namespace only (#2043)

- downstream/modules/platform/proc-gw-define-rules-triggers.adoc
- downstream/modules/platform/proc-gw-editing-a-user.adoc
This is a 2.5 backport for PR #2050 
[AAP-31729](https://issues.redhat.com/browse/AAP-31729)
[Access management and authentication](https://docs.google.com/document/d/1mEYguv3V0WUUHBMc8tsgqlK8RB3ro8IZSlQmMuFfhww/edit#heading=h.iu6hphvgsnk7)
- added downstream/modules/platform/proc-gw-editing-a-user.adoc
- edited downstream/modules/platform/proc-gw-define-rules-triggers.adoc
> Backport for PR #2050 AAP-31729: Editing a User & Defining Auth Mapping

- downstream/modules/platform/ref-example-OCP-architecture.adoc
This PR fixes the case for the image callin in the planning guide to successfully build the document.
> pg-image - Fix image case to eliminate build errors

- downstream/modules/devtools/proc-devtools-install-container.adoc
AAP-30402 Set docker path to `docker` or `podman` in dev containers extension
Affects `/titles/develop-automation-content/`
> AAP-30402 Set docker path in dev containers extension

- downstream/assemblies/devtools/assembly-devtools-install.adoc
- downstream/modules/devtools/proc-devtools-extension-set-language.adoc
- downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
AAP-30415
The Ansible VS Code extension requires the Ansible language to be associated with files.
> AAP-30415 Describe Ansible language file association in VSCode extension

- downstream/assemblies/devtools/assembly-writing-running-playbook.adoc
- downstream/modules/devtools/proc-devtools-set-up-ansible-config.adoc
- downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
- downstream/modules/devtools/proc-scaffolding-playbook-project.adoc
AAP-30411 Add description of how to set up ansible.cfg for devtools project.
Fixed some ID and context tags.
> AAP-30411 Set up ansible.cfg for devtools project

- downstream/modules/devtools/proc-devtools-install-container.adoc
Backports #2028 
AAP-30402 Set docker path to docker or podman in dev containers extension
Affects /titles/develop-automation-content/
> 2.5 AAP-30402 Set docker path in dev containers extension (#2028)

- downstream/modules/devtools/proc-devtools-install-container.adoc
Backports #2028 
AAP-30402 Set docker path to docker or podman in dev containers extension
Affects /titles/develop-automation-content/
> 2.4 AAP-30402 Set docker path in dev containers extension (#2028)

- downstream/assemblies/devtools/assembly-devtools-install.adoc
- downstream/modules/devtools/proc-devtools-extension-set-language.adoc
- downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
AAP-30415
The Ansible VS Code extension requires the Ansible language to be associated with files.
Backports #1948
> 2.5 AAP-30415 Describe Ansible language file association (#1948)

- downstream/assemblies/devtools/assembly-devtools-install.adoc
- downstream/modules/devtools/proc-devtools-extension-set-language.adoc
- downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
AAP-30415
The Ansible VS Code extension requires the Ansible language to be associated with files.
Backports #1948
> 2.4 AAP-30415 Describe Ansible language file association (#1948)

- downstream/assemblies/devtools/assembly-writing-running-playbook.adoc
- downstream/modules/devtools/proc-devtools-set-up-ansible-config.adoc
- downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
- downstream/modules/devtools/proc-scaffolding-playbook-project.adoc
AAP-30411 Add description of how to set up ansible.cfg for devtools project.
Fixed some ID and context tags.
Backports #2031
> 2.4 AAP-30411 Set up ansible.cfg for devtools project (#2031)

- downstream/assemblies/devtools/assembly-writing-running-playbook.adoc
- downstream/modules/devtools/proc-devtools-set-up-ansible-config.adoc
- downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
- downstream/modules/devtools/proc-scaffolding-playbook-project.adoc
Backports #2031 
AAP-30411 Add description of how to set up ansible.cfg for devtools project.
Fixed some ID and context tags.
> 2.5 AAP-30411 Set up ansible.cfg for devtools project (#2031)

- downstream/modules/devtools/proc-devtools-install-container.adoc
AAP-30714 The devtools container is based on a UBI minimal image, which uses microdnf as a package manager, not yum or dnf.
> AAP-30714 Devtools container package manager is microdnf

- downstream/modules/platform/ref-eda-system-requirements.adoc
Adding an important part of the EDA controller system requirements to downstream/modules/platform/ref-eda-system-requirements.adoc
> Backport-2.5-2040 Added missing part of 3rd bullet for EDA controller sys reqs

- downstream/modules/devtools/proc-devtools-install-container.adoc
Backports #2078 to 2.5
AAP-30714 The devtools container is based on a UBI minimal image, which uses microdnf as a package manager, not yum or dnf.
Affects titles/develop-automation-content
> 2.5 AAP-30714 Devtools container package manager is microdnf (#2078)

- downstream/modules/devtools/proc-devtools-install-container.adoc
Backports #2078 to 2.4
AAP-30714 The devtools container is based on a UBI minimal image, which uses microdnf as a package manager, not yum or dnf.
Affects titles/develop-automation-content
> AAP-30714 Devtools container package manager is microdnf (#2078)

- downstream/modules/platform/con-gs-auto-op-about-inv.adoc
- downstream/modules/platform/con-gs-auto-op-execute-inv.adoc
- downstream/modules/platform/con-gs-auto-op-job-templates.adoc
- downstream/modules/platform/con-gs-automation-execution-jobs.adoc
- downstream/modules/platform/proc-gs-auto-op-launch-template.adoc
- downstream/modules/platform/proc-gs-auto-op-projects.adoc
- downstream/modules/platform/proc-gs-auto-op-review-job-output.adoc
- downstream/modules/platform/proc-gs-auto-op-review-job-status.adoc
This PR backports the changes from [PR 2091](https://github.com/ansible/aap-docs/pull/2091) to the 2.5 branch. See [AAP-29069](https://github.com/ansible/aap-docs/pull/2091) for more info.
> backport to 2.5: AAP-29069 populates remaining modules for automation operator section (#2091)

- downstream/titles/aap-containerized-install/master.adoc
Add new topic on Horizontal Scaling that was already added to the RPM Installation Guide to the Containerized Installation Guide. 
Note to @michellemacrh : Since this topic is in it's own assembly and will likely be expanded to include procedures to use HS in separate subsections for controller, hub, and possibly mesh, I added the HS assembly right after the first assembly.
> AAP-31856 Added the HS assembly to Containerized Install Guide

- downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
Add the new chapter that was originally added to the RPM installation guide, titled "Adding the EDA safe plugins var" (downstream/assemblies/platform/assembly-aap-containerized-installation.adoc) to the Containerized Install guide.
> AAP-31861 Add the safe plugin for EDA procedure to the Containerized Install guide

- downstream/titles/aap-containerized-install/docinfo.xml
Backporting the change of abstract to 2.5 so it's correct for GA.
> 2.5 Update abstract of Containerized installation guide

- downstream/modules/topologies/ref-ocp-a-env-a.adoc
- downstream/titles/topologies/master.adoc
- Add link to test-topologies repo (will be made public at GA)
- Correct typo in OCP-A-ENV-A topology
> 2.5 Add link to ansible/test-topologies repo (#2103)

- downstream/modules/topologies/ref-cont-a-env-a.adoc
- downstream/modules/topologies/ref-cont-b-env-a.adoc
- downstream/modules/topologies/ref-ocp-a-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-b.adoc
Update OS to include AArch64 support in addition to x86_64 for relevant topologies.
> Update tested OS architecture for relevant topologies

- downstream/modules/topologies/ref-cont-a-env-a.adoc
- downstream/modules/topologies/ref-cont-b-env-a.adoc
- downstream/modules/topologies/ref-ocp-a-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-b.adoc
Update OS to include AArch64 support in addition to x86_64.
> 2.5 Update tested OS architecture for relevant topologies (#2107)

- downstream/titles/aap-containerized-install/master.adoc
Add new topic on Horizontal Scaling that was already added to the RPM Installation Guide to the Containerized Installation Guide.
> Backport-2.5-2086 Added the HS assembly to Containerized Install Guide

- downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
Add the new chapter that was originally added to the RPM installation guide, titled "Adding the EDA safe plugins var" (downstream/assemblies/platform/assembly-aap-containerized-installation.adoc) to the Containerized Install guide.
> Backport-2.5-2092 Added the safe plugin for EDA procedure to the Containerized Install guide

- downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
- downstream/assemblies/hub/assembly-managing-collections-hub.adoc
- downstream/assemblies/hub/assembly-managing-private-collections.adoc
- downstream/assemblies/hub/assembly-repo-management.adoc
- downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
- downstream/assemblies/hub/assembly-synclists.adoc
- downstream/assemblies/hub/assembly-validated-content.adoc
- downstream/assemblies/hub/assembly-working-with-namespaces.adoc
- downstream/modules/hub/con-approval-pipeline.adoc
- downstream/modules/hub/con-rh-certified-synclist.adoc
- downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc
- downstream/modules/hub/proc-configure-proxy-remote.adoc
- downstream/modules/hub/proc-create-content-developers.adoc
- downstream/modules/hub/proc-create-namespace.adoc
- downstream/modules/hub/proc-create-repository.adoc
- downstream/modules/hub/proc-create-requirements-file.adoc
- downstream/modules/hub/proc-create-synclist.adoc
- downstream/modules/hub/proc-delete-namespace.adoc
- downstream/modules/hub/proc-downloading-signature-public-keys.adoc
- downstream/modules/hub/proc-edit-namespace.adoc
- downstream/modules/hub/proc-review-collection-imports.adoc
- downstream/modules/hub/proc-set-community-remote.adoc
- downstream/modules/hub/proc-set-rhcertified-remote.adoc
- downstream/modules/hub/proc-uploading-collections.adoc
- downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
See [AAP-20548](https://issues.redhat.com/browse/AAP-20548) for more information.
> aap-20548: UI parity update for managing content in hub

- downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
- downstream/assemblies/hub/assembly-managing-collections-hub.adoc
- downstream/assemblies/hub/assembly-repo-management.adoc
- downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
- downstream/assemblies/hub/assembly-synclists.adoc
- downstream/assemblies/hub/assembly-validated-content.adoc
- downstream/assemblies/hub/assembly-working-with-namespaces.adoc
- downstream/modules/hub/con-rh-certified-synclist.adoc
- downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc
- downstream/modules/hub/proc-configure-proxy-remote.adoc
- downstream/modules/hub/proc-create-content-developers.adoc
- downstream/modules/hub/proc-create-namespace.adoc
- downstream/modules/hub/proc-create-repository.adoc
- downstream/modules/hub/proc-create-requirements-file.adoc
- downstream/modules/hub/proc-create-synclist.adoc
- downstream/modules/hub/proc-delete-namespace.adoc
- downstream/modules/hub/proc-downloading-signature-public-keys.adoc
- downstream/modules/hub/proc-edit-namespace.adoc
- downstream/modules/hub/proc-review-collection-imports.adoc
- downstream/modules/hub/proc-set-community-remote.adoc
- downstream/modules/hub/proc-set-rhcertified-remote.adoc
- downstream/modules/hub/proc-uploading-collections.adoc
- downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
This PR backports the changes from [PR 1609](https://github.com/ansible/aap-docs/pull/1609) to the 2.5 branch. See [AAP-20548](https://issues.redhat.com/browse/AAP-20548) for more info.
> Backport to 2.5: aap-20548: UI parity update for managing content in hub (#1609)

- downstream/attributes/attributes.adoc
- downstream/modules/devtools/proc-devtools-working-with-ee.adoc
2.4 Fix URL attribute to use multi-page on docs.redhat.com
URL attributes were using `html-single` for docs.redhat.com (ie whole doc is shown) instead of `html` (multi-page).
Previous links used multi-page.
However, the URLs for assemblies / modules change depending on whether `html` or `html-single` is used in a link.
For example
**multi-page (`html`):**
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/automation_controller_user_guide/assembly-controller-applications#proc-controller-apps-create-tokens
**single-page (`html-single`):**
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html-single/automation_controller_user_guide/index#proc-controller-apps-create-tokens
All of our links were configured for all releases up …
> 2.4 Fix URL attribute to use multi-page on docs.redhat.com

- downstream/attributes/attributes.adoc
URL attributes were using `html-single` for docs.redhat.com (ie whole doc is shown) instead of `html` (multi-page).
Previous links used multi-page.
However, the URLs for assemblies / modules change depending on whether html or html-single is used in a link.
For example
**multi-page (`html`):**
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/automation_controller_user_guide/assembly-controller-applications#proc-controller-apps-create-tokens
**single-page (`html-single`):**
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html-single/automation_controller_user_guide/index#proc-controller-apps-create-tokens
All of our links were configured for all releases up to and including 2.4 for the multi-page version.
This PR will …
> Update URL attributes to use html instead of html-single

- downstream/assemblies/platform/assembly-gs-auto-dev.adoc
- downstream/modules/platform/proc-controller-use-an-exec-env.adoc
This PR fixes a broken link and an extraneous } tag in the Getting started guide.
> gsfix - Fixed broken formatting preventing successful build

- downstream/assemblies/platform/assembly-gs-auto-dev.adoc
- downstream/modules/platform/proc-controller-use-an-exec-env.adoc
This PR backports the changes from #2134 to the 2.5 branch and includes the following:
* gsfix - Fixed broken formatting preventing successful build
* gsfix Removed extraneous closing bracket
> gsfix - Fixed broken formatting preventing successful build (#2134)

- downstream/modules/platform/ref-eda-system-requirements.adoc
This PR backports the changes from #2138 to the 2.5 branch.
> [Backport] Update link to EDA 2.5 with 2.4 controller doc (#2138)

- downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
Fixes "provisioning callbacks" link -- was missed in [PR 2136](https://github.com/ansible/aap-docs/pull/2136)
> Getting started with AAP: small link fix

- downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
This PR ports the changes from [PR 2140](https://github.com/ansible/aap-docs/pull/2140) to the 2.5 branch.
> Backport to 2.5: small link fix (#2140)

- downstream/attributes/attributes.adoc
URL attributes were using `html-single` for docs.redhat.com (ie whole doc is shown) instead of `html` (multi-page).
Previous links used multi-page.
However, the URLs for assemblies / modules change depending on whether html or html-single is used in a link.
For example
**multi-page (`html`):**
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/automation_controller_user_guide/assembly-controller-applications#proc-controller-apps-create-tokens
**single-page (`html-single`):**
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html-single/automation_controller_user_guide/index#proc-controller-apps-create-tokens
All of our links were configured for all releases up to and including 2.4 for the multi-page version.
This PR will …
> Update URL attribute to use html instead of html-single (#2118)

- downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
- downstream/assemblies/hub/assembly-validated-content.adoc
- downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc
- downstream/modules/hub/proc-configure-content-signing-on-pah.adoc
- downstream/modules/hub/proc-configure-proxy-remote.adoc
- downstream/modules/hub/proc-set-community-remote.adoc
- downstream/modules/hub/proc-set-rhcertified-remote.adoc
- downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
This PR ports the changes from [PR 2117](https://github.com/ansible/aap-docs/pull/2117) to the 2.5 branch. See [AAP-20548](https://issues.redhat.com/browse/AAP-20548) for more.
> Backport to 2.5: AAP-20548: Managing automation content doc updates (#2117)

- downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
This PR changes xrefs to links in the Managing automation content guide.
> Fixed broken formatting preventing successful build

- downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
Replaced with LOG_AGGREGATOR_ACTION_QUEUE_SIZE
[Doc Bug] : API setting LOG_AGGREGATOR_MAX_DISK_USAGE_GB misses ACTION.
https://issues.redhat.com/browse/AAP-32085
> Replace LOG_AGGREGATOR_MAX_DISK_USAGE_GB

- downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
- downstream/modules/hub/proc-obtaining-org-collection-url.adoc
Fixes `xref`s that were causing the Managing automation content build to fail in Pantheon.
Affects `hub/managing-content/`
> Fix broken xrefs in Managing automation content

- downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
- downstream/modules/hub/proc-obtaining-org-collection-url.adoc
Fixes `xref`s that were causing the Managing automation content build to fail in Pantheon.
Affects `hub/managing-content/`
> 2.5 Fix broken xrefs in Managing automation content (#2156)

- downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
- downstream/titles/release-notes/topics/aap-25-known-issues.adoc
- downstream/titles/release-notes/topics/aap-25.adoc
- downstream/titles/release-notes/topics/platform-intro.adoc
This PR is an update to AAP 2.5 release notes work (https://github.com/ansible/aap-docs/pull/2034, and JIRA  https://issues.redhat.com/browse/AAP-31661). 
Changes made:
- Added new known issue AAP-30585.
- Adjusted table width of 2 tables
- Updated a hyperlink.
> AAP-31661-update: Updated AAP 2.5 Release Notes

- downstream/modules/hub/proc-basic-repo-sync.adoc
This PR ports the changes from [PR 2180 ](https://github.com/ansible/aap-docs/pull/2180)to the 2.5 branch.
> Managing automation content guide: broken xref fix (#2180)

- downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
This PR backports the changes from #2175 to the 2.5 branch and includes the following:
* Late update to correct content for triggers
* Added peer review change
* Comparison fixed to be bold
* fixed comparison to uppercase
> [Backport] Late update to correct content for triggers (#2175)

- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Added an "Additional resources" section to the overview of the Using automation decisions guide that includes links to the **Roles** and **Adding roles for a user** sections in the Access management and authentication guide.
> AAP-30117 Add link to user permissions in the Using automation decisions guide

- downstream/assemblies/devtools/assembly-rhdh-install-ocp-operator.adoc
- downstream/attributes/attributes.adoc
- downstream/modules/devtools/con-rhdh-recommended-preconfig.adoc
- downstream/modules/devtools/proc-rhdh-backup-operator-configmap.adoc
- downstream/modules/devtools/proc-rhdh-configure-aap-details.adoc
- downstream/modules/devtools/proc-rhdh-create-custom-configmap-operator-install.adoc
- downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
- downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
- downstream/modules/devtools/proc-rhdh-operator-add-custom-configmap-cr.adoc
- downstream/modules/devtools/proc-rhdh-operator-install-add-plugins-app-config.adoc
- downstream/titles/aap-plugin-rhdh-install/master.adoc
AAP-32141 Add Installing on Operator chapter to RHDH install guide
Affects titles/aap-plugin-rhdh-install/
Preview here: https://ariordan-redhat.github.io/aap-builds/aap-plugin-rhdh-install-scaffold-plugin-operator-install-2024-09-26.html
> AAP-32141 Add Installing on Operator chapter to RHDH install guide

- downstream/assemblies/devtools/assembly-devtools-create-roles-collection.adoc
- downstream/assemblies/devtools/assembly-devtools-develop-collections.adoc
- downstream/modules/devtools/con-devtools-plan-roles-collection.adoc
- downstream/modules/devtools/con-devtools-roles-collection-prerequisites.adoc
- downstream/modules/devtools/proc-devtools-create-new-role-in-collection.adoc
- downstream/modules/devtools/proc-devtools-docs-roles-collection.adoc
- downstream/modules/devtools/proc-devtools-migrate-existing-roles-collection.adoc
- downstream/modules/devtools/proc-devtools-molecule-test-roles-collection.adoc
- downstream/modules/devtools/proc-devtools-publish-roles-collection-pah.adoc
- downstream/modules/devtools/proc-devtools-run-roles-collection.adoc
- downstream/modules/devtools/proc-devtools-scaffold-roles-collection.adoc
- downstream/modules/devtools/proc-devtools-use-roles-collections-aap.adoc
- downstream/titles/develop-automation-content/master.adoc
AAP-30912  Add roles collections chapter to the Devtools guide.
Build preview here: https://ariordan-redhat.github.io/aap-builds/develop-automation-content-aap-30912-2024-09-27.html
> AAP-30912 Devtools - Add roles collections chapter

- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Added a link to two sections in the Access management and authentication guide: Roles and Adding roles for a user.
> Backport-2.5-2176 (AAP-30117) Add link to user permissions in the Using automation decisions guide (#2176)

- downstream/modules/platform/proc-gw-organizations-exec-env.adoc
- downstream/modules/platform/ref-controller-clear-sessions.adoc
- downstream/modules/platform/ref-controller-organization-notifications.adoc
This PR fixes the broken links in the Access management guide that were flagged by the link checker script.
> Fix broken links in the Access management guide

- downstream/modules/platform/proc-gw-organizations-exec-env.adoc
- downstream/modules/platform/ref-controller-clear-sessions.adoc
- downstream/modules/platform/ref-controller-organization-notifications.adoc
This PR backports the changes from #2185 to the 2.5 branch and includes the following:
* Fix broken links in the Access management guide
* Added <assemblyID>#<moduleID> to fix broken links
> [Backport] Fix broken links in the Access management guide (#2185)

- downstream/assemblies/platform/assembly-inventory-introduction.adoc
2.5 backport of [PR 2168](https://github.com/ansible/aap-docs/pull/2168)
[AAP-31800](https://issues.redhat.com/browse/AAP-31800)
Updated self-referencing link in Planning your installation
assembly-inventory-introduction.adoc
> AAP-31800 updated self-referencing link (#2168)

- downstream/titles/troubleshooting-aap/master.adoc
Comment out a troubleshooting section that is relevant to the controller UI which should no longer be accessed.
> Remove reference to controller UI in troubleshooting guide

- downstream/titles/troubleshooting-aap/master.adoc
Comment out a troubleshooting section that is relevant to the controller UI which should no longer be accessed.
> 2.5 Remove reference to controller UI in troubleshooting guide (#2199)

- downstream/modules/platform/ref-gs-install-config.adoc
This PR ports the changes from [PR 2222](https://github.com/ansible/aap-docs/pull/2222) to the 2.5 branch.
> backport to 2.5: broken link fix for Getting started with AAP

- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
- downstream/assemblies/eda/assembly-simplified-event-routing.adoc
- downstream/modules/eda/proc-eda-set-up-rhaap-credential.adoc
- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Found minor errors (typos, link titles, etc.) in the following modules:
- downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
- downstream/assemblies/eda/assembly-simplified-event-routing.adoc
- downstream/modules/eda/proc-eda-set-up-rhaap-credential.adoc
- downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
> Backport-2.5-2225 (AAP-32260) Minor corrections found in Using automation decisions guide. (#2225)

- downstream/assemblies/platform/assembly-controller-organizations.adoc
Changed generic template assembly id [assembly-my-user-story_{context}] to something unique.
> Fixing assembly ID to be unique in Organizations content

- downstream/assemblies/platform/assembly-controller-organizations.adoc
This PR backports the changes from #2229 to the 2.5 branch.
> Fixing assembly ID to be unique in Organizations content (#2229)

- downstream/attributes/attributes.adoc
This PR fixes a formatting issue with the Automation Content menu attribute for Signature Keys and Repositories.
> Fixed problem with Automation Content menu attribute

- downstream/attributes/attributes.adoc
This PR backports the changes from #2230 to the 2.5 branch and includes the following:
* Fixed problem with Automation Content menu attribute
* Fixed API token attribute
> [Backport] Fixed problem with Automation Content menu attribute (#2230)

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
There was an [ongoing discussion](https://docs.google.com/document/d/1fIrlSrj8bSSWBVptXWmm0ZFixhZ4mM5pW2CQx_3Oh7A/edit#heading=h.iaypu8e8mkj4) in this RPM install draft regarding RPM enterprise and growth inventory files. 
I've replaced the 3 specific examples with the enterprise inventory file to be consistent with the supported topologies listed in the [Tested deployment models](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/tested_deployment_models/rpm-topologies#example_enterprise_inventory_file) guide. 
I will need to raise the question of adding the RPM growth inventory file to confirm that it belongs in event 1 and not 2 of the RPM installation guide.
> RPM installation guide: Add enterprise inventory file link

- downstream/modules/platform/ref-general-inventory-variables.adoc
Correct variable typo in ref-general-inventory-variables.adoc
docs - ca_tls_cert is incorrect in appendix-inventory-file-vars
https://issues.redhat.com/browse/AAP-32358
> Correct typo in appendix variables section

- downstream/modules/platform/ref-general-inventory-variables.adoc
Correct variable typo in ref-general-inventory-variables.adoc
docs - ca_tls_cert is incorrect in appendix-inventory-file-vars
https://issues.redhat.com/browse/AAP-32358
> 2.5 Correct typo in appendix variables section (#2236)

- downstream/assemblies/platform/assembly-network-ports-protocols.adoc
2.5 backport of [PR 2235](https://github.com/ansible/aap-docs/pull/2235)
[AAP-32244](https://issues.redhat.com/browse/AAP-32244) 3
assembly-network-ports-protocols.adoc
> AAP-32244 updated links (#2235)

- downstream/assemblies/devtools/assembly-rhdh-using.adoc
https://issues.redhat.com/browse/AAP-28962
Add optional requirement for a developer gub account so that users can access the learning paths linked from the Ansible plug-ins on RHDH.
> AAP-29062 RHDH Add requirement for developer hub portal account

- downstream/assemblies/devtools/assembly-rhdh-using.adoc
https://issues.redhat.com/browse/AAP-28962
Add optional requirement for a developer gub account so that users can access the learning paths linked from the Ansible plug-ins on RHDH.
> AAP-29062 RHDH Add requirement for developer hub portal account (#2241)

- downstream/modules/devtools/proc-rhdh-create.adoc
AAP-30989
Add requirements for collection namespaces
> 2.5 AAP-30989 RHDH Add collection naming convention requirements (#2242)

- downstream/modules/devtools/proc-rhdh-create.adoc
AAP-30989
Add requirements for collection namespaces
> 2.4 AAP-30989 RHDH Add collection naming convention requirements (#2242)

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
There was an [ongoing discussion](https://docs.google.com/document/d/1fIrlSrj8bSSWBVptXWmm0ZFixhZ4mM5pW2CQx_3Oh7A/edit#heading=h.iaypu8e8mkj4) in this RPM install draft regarding RPM enterprise and growth inventory files.
I've replaced the 3 specific examples with the enterprise inventory file to be consistent with the supported topologies listed in the [Tested deployment models](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/tested_deployment_models/rpm-topologies#example_enterprise_inventory_file) guide.
I will need to raise the question of adding the RPM growth inventory file to confirm that it belongs in event 1 and not 2 of the RPM installation guide.
> [2.5] RPM installation guide: Add enterprise inventory file link (#2228)

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Fixed broken link by replacing {linkTopologies} with {URLTopologies}
> Fix broken link in RPM install guide 

- downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Fixed broken link by replacing {linkTopologies} with {URLTopologies} and squiggly line.
> [2.5] RPM-fix-link:Remove Squiggly line (#2255)

- downstream/modules/platform/proc-installing-containerized-aap.adoc
Update the inventory files in the containerized install guide to allow for copy and paste of each inventory file correctly.
Containerized AAP install guide and installer need to be reconciled
https://issues.redhat.com/browse/AAP-32473
> Update inventory files to allow for copy/paste

- downstream/modules/platform/proc-installing-containerized-aap.adoc
Update the inventory files in the containerized install guide to allow for copy and paste of each inventory file correctly.
Containerized AAP install guide and installer need to be reconciled
https://issues.redhat.com/browse/AAP-32473
> 2.5 Update inventory files to allow for copy/paste (#2262)

- downstream/modules/platform/proc-installing-containerized-aap.adoc
- downstream/modules/topologies/ref-cont-a-env-a.adoc
- downstream/modules/topologies/ref-cont-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-b.adoc
Update the AsciiDoc syntax for the code blocks for inventory file examples to ensure the copy and paste command on docs.redhat.com works correctly.
Corrected for containerized install guide and topologies documentation.
Containerized AAP install guide and installer need to be reconciled
https://issues.redhat.com/browse/AAP-32473
> Update inventory file code blocks to allow copy paste

- downstream/modules/platform/proc-installing-containerized-aap.adoc
- downstream/modules/topologies/ref-cont-a-env-a.adoc
- downstream/modules/topologies/ref-cont-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-b.adoc
Update the AsciiDoc syntax for the code blocks for inventory file examples to ensure the copy and paste command on docs.redhat.com works correctly.
Corrected for containerized install guide and topologies documentation.
Containerized AAP install guide and installer need to be reconciled
https://issues.redhat.com/browse/AAP-32473
> 2.5 Update inventory file code blocks to allow copy paste (#2264)

- downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
- downstream/titles/release-notes/topics/aap-25-known-issues.adoc
This PR addresses a few updates to the AAP 2.5 release notes per recent update requests. Once this PR is merged, the changes must be backported to 2.5 branch. 
Changes made:
- Added a new known issue (https://issues.redhat.com/browse/AAP-32208)
- Added more deprecated APIs (JIRA: https://issues.redhat.com/browse/AAP-32298) 
Google doc: [[Draft AAP 2.5 release notes](https://docs.google.com/document/d/1R795y4V8p_UzNCaBmKpaG1lmJQDH4JTFZ_axh05fCI0/edit?usp=sharing)]
> AAP-31661-update2: Added known issue and deprecated APIs

- downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
- downstream/modules/platform/ref-OCP-system-requirements.adoc
- downstream/modules/platform/ref-containerized-system-requirements.adoc
2.5 backport of [PR 2267](https://github.com/ansible/aap-docs/pull/2267)
AP-32244 updated incorrect links
- topologies/assembly-overview-tested-deployment-models.adoc
- ref-OCP-system-requirements.adoc
- ref-containerized-system-requirements.adoc
> backport-2.5-2267

- downstream/titles/release-notes/topics/rpm-24-74.adoc
Correct a formatting issue for the 2.4 async release notes
Affected file: rpm-24-74.adoc
> 2.4 Correct formatting issue in 2.4 async release notes

- lightspeed/assemblies/assembly_managing-admin-dashboard-telemetry.adoc
- lightspeed/modules/con_telemetry-data-collection-notice.adoc
- lightspeed/modules/con_training-data.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-31240.
Changes made:
- Specified what's categorized as 'operational telemetry' and 'admin dashboard telemetry'.
- Added a note stating that no telemetry data is collected in an Ansible Lightspeed on-premise deployment.
> AAP-31240: Updated the Telemetry docs per customer ask

- downstream/titles/updating-aap/master.adoc
Update module reference link in Updating from Ansible Automation Platform 2.5 to 2.5.x as it resulted in a docs build failure.
Affected file: `downstream/titles/updating-aap/master.adoc`
Updated from `include::../../modules/platform/proc-update-aap-on-ocp.adoc[leveloffset=+2]`
To `include::platform/platform/proc-update-aap-on-ocp.adoc[leveloffset=+2]`
Document 2.5 to 2.5.x upgrade steps
https://issues.redhat.com/browse/AAP-31734
> Update module reference link to ensure title builds successfully

- downstream/titles/updating-aap/master.adoc
Update module reference link in Updating from Ansible Automation Platform 2.5 to 2.5.x as it resulted in a docs build failure.
Updated from `include::../../modules/platform/proc-update-aap-on-ocp.adoc[leveloffset=+2]`
To `include::platform/platform/proc-update-aap-on-ocp.adoc[leveloffset=+2]`
> 2.5 Update module reference link to ensure title builds successfully (#2275)

- downstream/modules/topologies/ref-cont-a-env-a.adoc
- downstream/modules/topologies/ref-cont-b-env-a.adoc
- downstream/modules/topologies/ref-ocp-a-env-a.adoc
- downstream/modules/topologies/ref-ocp-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-a.adoc
- downstream/modules/topologies/ref-rpm-b-env-b.adoc
Update the ansible-core version and the PostgreSQL versions in Tested deployment models.
I made use of the relevant attributes `{CoreInstVers}` and `{PostgresVers}` to make these easier to update in the future.
Incorrect Ansible Core in AAP 2.5 documentation
https://issues.redhat.com/browse/AAP-32814
> Update ansible-core version and PostgreSQL version in topologies

- downstream/titles/release-notes/master.adoc
- downstream/titles/release-notes/topics/aap-25-2-patch-release-7-oct-2024.adoc
* Patch release notes for AAP 2.5-2-October-7, 2024. This is a patch release that includes several fixes and enhancements.
* Update aap-25-2-patch-release-7-oct-2024.adoc
* Update aap-25-2-patch-release-7-oct-2024.adoc
* Update aap-25-2-patch-release-7-oct-2024.adoc
* Update aap-25-2-patch-release-7-oct-2024.adoc
> Patch release notes for AAP 2.5-2-October-7, 2024 (#2288)

- downstream/titles/updating-aap/master.adoc
This PR backports the change from #2293 to the 2.5 branch.
> dd-updguide - Add experimental tagk to fix formatting (#2293)

- downstream/titles/release-notes/topics/aap-25-2-patch-release-7-oct-2024.adoc
* Removed extraneous internal numeration from the errata.
Fixes an issue raised by Satoe.
* Update aap-25-2-patch-release-7-oct-2024.adoc
* Update aap-25-2-patch-release-7-oct-2024.adoc
> Removed extraneous internal numeration from the errata. (#2318)
