downstream/assemblies/platform/assembly-aap-migration.adoc
downstream/modules/platform/con-aap-migration-considerations.adoc
downstream/modules/platform/con-aap-migration-prepare.adoc
downstream/modules/platform/proc-aap-create_controller.adoc
downstream/modules/platform/proc-aap-create_eda.adoc
downstream/modules/platform/proc-aap-create_hub.adoc
downstream/modules/platform/proc-aap-migration-backup.adoc
downstream/modules/platform/proc-aap-migration.adoc
downstream/modules/platform/proc-create-postresql-secret.adoc
downstream/modules/platform/proc-create-secret-key-secret.adoc
downstream/modules/platform/proc-post-migration-cleanup.adoc
downstream/modules/platform/proc-verify-network-connectivity.adoc
downstream/titles/aap-operator-installation/master.adoc

[AAP-33159](https://issues.redhat.com/browse/AAP-33159)
Updating the migration section of the [Installing on OCP doc](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/installing_on_openshift_container_platform/index) for 2.5 Event 2.

Event 2 migration content updates

---

downstream/titles/release-notes/async/aap-25-1-7-oct.adoc
downstream/titles/release-notes/async/aap-25-2-14-oct.adoc
downstream/titles/release-notes/master.adoc

Add release notes for patch 2 for AAP 2.5 scheduled for release 14th Oct.
Draft doc: https://docs.google.com/document/d/1R795y4V8p_UzNCaBmKpaG1lmJQDH4JTFZ_axh05fCI0/edit#heading=h.jn2xcct2bgfe

2.5 Add patch 2 release notes (#2332)

---

downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-gw-editing-a-user.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc
downstream/modules/platform/proc-gw-users-list-view.adoc

This PR addresses the content updates needed for org/team/user migration and superuser for 2.5 Event 2 to address the changes requested in https://issues.redhat.com/browse/AAP-21556 and https://issues.redhat.com/browse/AAP-24050.

AAP-21556 - org/team/user migration and superuser identification for AAP-24050

---

downstream/modules/platform/ref-system-requirements.adoc

* Added RHEL 8.8 to 2.5 system requirements
[Doc]AAP 2.5 system requirements should include RHEL 8.8
https://issues.redhat.com/browse/AAP-32708
* Added RHEL 8.8 to 2.5 system requirements
Correction
https://issues.redhat.com/browse/AAP-32708

Added RHEL 8.8 to 2.5 system requirements (#2350)

---

downstream/modules/platform/con-why-automation-mesh.adoc
downstream/modules/platform/proc-change-ssl-installer.adoc

Corrections to links in two modules in the 2.5 [Operating AAP guide](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/operating_ansible_automation_platform/index)

AAP-32980 Corrected broken links and incorrect titles in the Operating AAP guide

---

downstream/modules/platform/con-why-automation-mesh.adoc
downstream/modules/platform/proc-change-ssl-installer.adoc

Corrections to links in two modules in the 2.5 [Operating AAP guide](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/operating_ansible_automation_platform/index)

Backport-2.5-2356 Corrected broken links and incorrect titles in the Operating AAP guide

---

stories/assembly-saas-post-install-config.adoc

[AAP-33170](https://issues.redhat.com/browse/AAP-33170) 
Undoing changes as no longer needed for Base URL settings.

removing base url info from warning

---

downstream/modules/troubleshooting-aap/proc-troubleshoot-must-gather.adoc

Update the must-gather image location version to match up with 2.5
[Docs] Update AAP must gather image name in documentation
https://issues.redhat.com/browse/AAP-33519

Update must-gather version in troubleshooting guide

---

downstream/modules/troubleshooting-aap/proc-troubleshoot-must-gather.adoc

Update the must-gather image location version to match up with 2.5
[Docs] Update AAP must gather image name in documentation
https://issues.redhat.com/browse/AAP-33519

2.5 Update must-gather version in troubleshooting guide (#2363)

---

lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-31305.
Changes made:
- Added a troubleshooting section on disabling SSL certificate validation in Lightspeed operator.

AAP-31305: Added info. about disabling SSL cert validation in Lightspeed operator

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
downstream/modules/platform/ref-containerized-troubleshoot-install.adoc

Update inventory variable references to match INI formatting For example, change from: `gateway_nginx_http_port: 8500` to `gateway_nginx_http_port=8500`
Containerized installer has mix of json and ini
https://issues.redhat.com/browse/AAP-33697

Update Containerized installation inventory variable references

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
downstream/modules/platform/ref-containerized-troubleshoot-install.adoc

Update inventory variable references to match INI formatting For example, change from: `gateway_nginx_http_port: 8500` to `gateway_nginx_http_port=8500`
Containerized installer has mix of json and ini
https://issues.redhat.com/browse/AAP-33697

2.5 Update Containerized installation inventory variable references (#2370)

---

downstream/modules/platform/proc-account-linking.adoc

See [AAP-32998](https://issues.redhat.com/browse/AAP-32998) for more info.

AAP-32998: Adds links about OAuth application migration to the Upgrade/Migration guide

---

downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc

Update the port variables referenced in "Accessing Ansible Automation Platform" in Containerized installation.
containerized installer ports are wrong in the documentation
https://issues.redhat.com/browse/AAP-33760

Update port variables in Containerized installation

---

downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc

Update the port variables referenced in "Accessing Ansible Automation Platform"
containerized installer ports are wrong in the documentation
https://issues.redhat.com/browse/AAP-33760

2.5 Update port variables in Containerized installation (#2383)

---

downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc

* Replace LOG_AGGREGATOR_MAX_DISK_USAGE
[Doc Bug] : API setting LOG_AGGREGATOR_MAX_DISK_USAGE_GB misses ACTION.
https://issues.redhat.com/browse/AAP-32937
* Replace LOG_AGGREGATOR_MAX_DISK_USAGE
Correction
[Doc Bug] : API setting LOG_AGGREGATOR_MAX_DISK_USAGE_GB misses ACTION.
https://issues.redhat.com/browse/AAP-32937
* Replace LOG_AGGREGATOR_MAX_DISK_USAGE
Correction
[Doc Bug] : API setting LOG_AGGREGATOR_MAX_DISK_USAGE_GB misses ACTION.
https://issues.redhat.com/browse/AAP-32937

Replace LOG_AGGREGATOR_MAX_DISK_USAGE (#2343)

---

downstream/modules/platform/proc-cli-get-controller-pwd.adoc
downstream/modules/platform/proc-install-cli-aap-operator.adoc

[AAP-32794](https://issues.redhat.com/browse/AAP-32794) 
Chapter 3. Installing Ansible Automation Platform Operator from the OpenShift Container Platform CLI in the new Ansible Automation Platform 2.5 documentation does not configure the AnsibleAutomationPlatform object as required for the new deployment.

AAP-32794 updates

---

downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc

Add the following variables to the inventory file examples for the enterprise container topology
- postgresql_admin_username
- postgresql_admin_password
This affects Supported deployment models and Containerized installation docs.
Documentation for enterprise containerized 2.5 installation has misleading inventory example
https://issues.redhat.com/browse/AAP-33520

Add required vars to cont-b inventory files

---

downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc

Add the following variables to the inventory file examples for the enterprise container topology
- postgresql_admin_username
- postgresql_admin_password
This affects Supported deployment models and Containerized installation docs.
Documentation for enterprise containerized 2.5 installation has misleading inventory example
https://issues.redhat.com/browse/AAP-33520

2.5 Add required vars to cont-b inventory files (#2390)

---

downstream/assemblies/topologies/assembly-ocp-topologies.adoc

Add a note to the Operator topologies section of Tested deployment models to denote the single namespace limitation.
Add install-related note to Tested deployment models for OCP
https://issues.redhat.com/browse/AAP-33878

Add note to Operator topologies section of Tested deployment models

---

downstream/modules/platform/proc-aap-controller-backup.adoc

This resolves [AAP-32994](https://issues.redhat.com/browse/AAP-32994), which corrects the error message in the event of a backup failure. I am unable to add Chris Meyers (chrismeyersfsu) as a reviewer but he needs to sign off in this.

Updated the note for a backup failure status.

---

downstream/modules/platform/proc-aap-controller-backup.adoc

This resolves [AAP-32994](https://issues.redhat.com/browse/AAP-32994), which corrects the error message in the event of a backup failure. I am unable to add Chris Meyers (chrismeyersfsu) as a reviewer but he needs to sign off in this.

Updated the note for a backup failure status. (#2329)

---

downstream/modules/platform/con-hs-eda-controller.adoc
downstream/titles/aap-containerized-install/master.adoc

* Add conditional text to Horizontal scaling in EDA
Add conditional content to con-hs-eda-controller.adoc to account for the differences between RPM and Container installations.
Correct inventory file attributes for containerized installer in horizontal scaling content
https://issues.redhat.com/browse/AAP-33624

2.5 Add conditional text to Horizontal scaling in EDA (#2402)

---

downstream/assemblies/platform/assembly-controller-credentials.adoc

Controller UI allows to create duplicate credentials without organization
https://issues.redhat.com/browse/AAP-25150

Adding note about duplicate credentials

---

downstream/assemblies/platform/assembly-controller-credentials.adoc

Controller UI allows to create duplicate credentials without organization
https://issues.redhat.com/browse/AAP-25150

Adding note about duplicate credentials (#2380)

---

downstream/titles/release-notes/topics/aap-25-removed-features.adoc

remote version only applies to Ansible version 2.17.
Resolves: AAP-33894

Added a short note denoting the Python 3.5 removal as a supported

---

downstream/assemblies/platform/assembly-update-ocp.adoc
downstream/modules/platform/proc-update-aap-on-ocp.adoc
downstream/titles/aap-operator-installation/master.adoc
downstream/titles/updating-aap/master.adoc

See [AAP-34122](https://issues.redhat.com/browse/AAP-34122) for more info.

AAP-34122: moves assembly from upgrading 2.5 to 2.5x to Installing on OCP guide

---

downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

Added an extra point to the admonition in the proc-eda-set-up-rulebook-activation.adoc module. Alerts users/customers to only select 1 RH AAP credential when setting up a rulebook activation using the RH AAP credential.

AAP-30120 Added extra bullet to the admonition in Setting up a rulebook activation section

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-update-aap-container.adoc

With event 2, the update content from Updating from Ansible Automation Platform 2.5 to 2.5.x should be migrated into the associated install guides. This PR addresses the Containerized installation guide.
Move upgrade content into the Containerized installation guide
https://issues.redhat.com/browse/AAP-34068

Add update content to Containerized installation

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-update-aap-container.adoc

With event 2, the update content from Updating from Ansible Automation Platform 2.5 to 2.5.x should be migrated into the associated install guides. This PR addresses the Containerized installation guide.
Move upgrade content into the Containerized installation guide
https://issues.redhat.com/browse/AAP-34068

2.5 Add update content to Containerized installation (#2422)

---

downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

The mixed enterprise topology needs to be updated to account for 3 VMs for gateway and eda
Topology updates for RPM Redis support
https://issues.redhat.com/browse/AAP-32331

Update RPM-B-ENV-B topology for Redis

---

downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

Added an extra point to the admonition in the proc-eda-set-up-rulebook-activation.adoc module. Alerts users/customers to only select 1 RH AAP credential when setting up a rulebook activation using the RH AAP credential.

Backport-2.5-2418 AAP-30120 Added extra bullet to the admonition in Setting up a rulebook activation

---

downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

The mixed enterprise topology needs to be updated to account for 3 VMs for gateway and eda
Topology updates for RPM Redis support
https://issues.redhat.com/browse/AAP-32331

2.5 Update RPM-B-ENV-B topology for Redis (#2424)

---

downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
downstream/titles/builder/master.adoc

This PR fixes a typo in the leveloffset setting in the builder master file and adds missing "/" to links that were flagged as broken.

Minor fixes to correct broken link and doc formatting

---

downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
downstream/titles/builder/master.adoc

This PR backports the changes from #2432 to the 2.5 branch.

[Backport] Minor fixes to correct broken link and doc formatting (#2432)

---

downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/proc-account-linking.adoc
downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc

This PR ports the changes from [PR 2437](https://github.com/ansible/aap-docs/pull/2437) to the 2.5 branch.

Backport to 2.5: Adds SME feedback to RPM upgrade guide (#2437)

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc

Installation scenarios in the [RPM Installation guide](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/index) were under a different sub-heading than the previous version of the [RH Installation Guide (2.4)](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/index). 
Moved topics numbered as 3.2.2.1 - 3.2.2.7 in the guide under sub-heading [3.2.2. Setting registry_username and registry_password](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/assembly-platform-install-scenario#proc-set-registry-username-password) to the most appropriate sub-heading [3.2.1 Inventory file recommendations based …

AAP-33892 Moved install scenarios to appropriate sub-heading

---

downstream/titles/release-notes/async/aap-25-1-7-oct.adoc
downstream/titles/release-notes/async/aap-25-2-14-oct.adoc
downstream/titles/release-notes/async/aap-25-3-28-oct.adoc
downstream/titles/release-notes/async/async-updates.adoc
downstream/titles/release-notes/master.adoc

- Added release notes for event 2 `aap-25-3-28-oct.adoc`
- Updated `aap-25-2-14-oct.adoc` and `aap-25-1-7-oct.adoc` to include errata advisories
- Updated `async-updates.adoc` and included in the release notes `master.adoc`
AAP 2.5 (3) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-33685

Add release notes for async 2.5-3 aka event 2

---

downstream/titles/release-notes/async/aap-25-1-7-oct.adoc
downstream/titles/release-notes/async/aap-25-2-14-oct.adoc
downstream/titles/release-notes/async/aap-25-3-28-oct.adoc
downstream/titles/release-notes/async/async-updates.adoc
downstream/titles/release-notes/master.adoc

- Added release notes for event 2 `aap-25-3-28-oct.adoc`
- Updated `aap-25-2-14-oct.adoc` and `aap-25-1-7-oct.adoc` to include errata advisories
- Updated `async-updates.adoc` and included in the release notes `master.adoc`
AAP 2.5 (3) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-33685

2.5 Add release notes for async 2.5-3 aka event 2 (#2441)

---

downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/con-aap-upgrades.adoc

This PR fixes broken xrefs in the RPM upgrade and migration guide preventing the document from building.

Fixes broken xrefs in RPM upgrade and migration guide

---

downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/con-aap-upgrades.adoc

This PR backports the changes from #2443 to the 2.5 branch.

[Backport] Fixes broken xrefs in RPM upgrade and migration guide (#2443)

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc

Installation scenarios in the [RPM Installation guide](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/index) were under a different sub-heading than the previous version of the [RH Installation Guide (2.4)](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/index).
Moved topics numbered as 3.2.2.1 - 3.2.2.7 in the guide under sub-heading [3.2.2. Setting registry_username and registry_password](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/assembly-platform-install-scenario#proc-set-registry-username-password) to the most appropriate sub-heading [3.2.1 Inventory file recommendations based …

Backport-2.5-2436 (AAP-33892) Moved install scenarios to appropriate sub-heading (#2436)

---

downstream/modules/platform/con-aap-upgrades.adoc
downstream/modules/platform/proc-choosing-obtaining-installer.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

This PR covers the work needed to include 2.5 to 2.5x upgrade information in the RPM upgrade and migration guide.

AAP-34122 - Move content from Updating AAP 2.5 to 2.5x to upgrade guide

---

downstream/modules/platform/con-aap-upgrades.adoc
downstream/modules/platform/proc-choosing-obtaining-installer.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

This PR backports the changes from #2455  to the 2.5 branch.

[Backport] AAP-34122 - Move content from Updating AAP 2.5 to 2.5x to upgrade guide (#2445)

---

downstream/assemblies/platform/assembly-update-rpm.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc

This PR fixes a broken xref in a shared file by converting it to a link.

Change xref to link in a shared file

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc

This PR backports the changes from #2457 to the 2.5 branch.

[Backport] Add upgrade prerequisite details (#2457)

---

downstream/assemblies/platform/assembly-update-rpm.adoc

This PR removes conditional tagging left behind during a previous fix.

Remove conditional tagging not used

---

downstream/assemblies/platform/assembly-update-rpm.adoc

This PR backports the changes from the #2461 to the 2.5 branch.

[Backport] Remove conditional tagging not used (#2461)

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/proc-account-linking.adoc

This PR backports the changes from #2463 to the 2.5 branch.

[Backport] 2457 - fix formatting issues in upgrade guide (#2463)

---

lightspeed/modules/proc_update-redirect-uri.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-32735.
Changes made:
- In the 'Updating the redirect URIs' procedure, added the steps to configure Lightspeed logout on AAP Gateway under VM.

AAP-32735: Added steps to configure Lightspeed logout on AAP Gateway under VM

---

downstream/modules/platform/proc-gw-editing-a-user.adoc

This PR fixes an error in the Editing a user procedure to remove EDA users from the upgrade details. EDA user migration is not supported.

Fix error in Editing a user procedure

---

downstream/modules/platform/proc-gw-editing-a-user.adoc

This PR backports the changes from #2467 to the 2.5 branch and includes the following:
* Fix error in Editing a user procedure
* Adding peer review changes

[Backport] Fix error in Editing a user procedure (#2467)

---

downstream/titles/release-notes/topics/platform-intro.adoc

The release notes still include content stating that upgrades are unsupported but they are now that the event 2 async has been released. Removed this content to ensure up to date functionality is reflected in the docs
Remove unsupported upgrade content from release notes
https://issues.redhat.com/browse/AAP-34772

Remove upgrades unsupported content from release notes

---

downstream/titles/release-notes/topics/platform-intro.adoc

The release notes still include content stating that upgrades are unsupported but they are now that the event 2 async has been released. Removed this content to ensure up to date functionality is reflected in the docs
Remove unsupported upgrade content from release notes
https://issues.redhat.com/browse/AAP-34772

2.5 Remove upgrades unsupported content from release notes (#2471)

---

downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
downstream/modules/platform/proc-controller-create-application.adoc
downstream/modules/platform/ref-controller-app-token-functions.adoc
downstream/modules/platform/ref-controller-refresh-existing-token.adoc
downstream/modules/platform/ref-controller-revoke-access-token.adoc
downstream/modules/platform/ref-controller-token-session-management.adoc

This PR updates the application OAuth paths to correctly reflect gateway:
`/api/o/token/` changed to `/o/token/`
`/api/o/revoke-token/` changed to `/o/revoke-token/`
`http://<controller>/api/o/revoke_token/ -i` changed to `http://<gateway>/o/revoke_token/ -i`
`/api/v2/tokens/` changed to `/gateway/api/v1/tokens/`

AAP-34814 - update application OAuth paths

---

downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

Update the relevant redis_tls_cert and redis_tls_key vars in the inventory variables appendix for Containerized installation.
DOCS - Redis_tls_cert and redis_tls_key missing from inventory vars appendix
https://issues.redhat.com/browse/AAP-32788

Update redis_tls_cert and key vars in appendix

---

downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

* Update the relevant redis_tls_cert and redis_tls_key vars in the inventory variables appendix for the containerized installer

2.5 Update redis_tls_cert and key vars in appendix (#2484)

---

downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc

Correction
DOCS - Ansible plugins for RHDH - Indententation error in examples
https://issues.redhat.com/browse/AAP-34042

Corrected yaml indentation

---

downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc

Correction
DOCS - Ansible plugins for RHDH - Indententation error in examples
https://issues.redhat.com/browse/AAP-34042

Corrected yaml indentation (#2478)

---

downstream/titles/release-notes/topics/aap-25-removed-features.adoc

Added the Python versions that have been removed as supported remote versions.
Resolves: #2414
See also: AAP-33894

Added line to clarify Python version removal. (#2487)

---

downstream/attributes/attributes.adoc

Fixes the naming convention for the attribute from upgrade_migration
to
rpm_upgrade_migration
Resolves: AAP-34824

This fixes the naming convention for the attribute URLUpgrade

---

downstream/attributes/attributes.adoc

Fixes the naming convention for the attribute from upgrade_migration
to
rpm_upgrade_migration
Resolves: AAP-34824

This fixes the naming convention for the attribute URLUpgrade (#2489)

---

downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc
downstream/modules/eda/con-replacing-controller-tokens.adoc
downstream/modules/eda/proc-eda-delete-controller-token.adoc
downstream/modules/eda/proc-eda-delete-rulebook-activations-with-cont-tokens.adoc
downstream/modules/eda/proc-eda-set-up-credential.adoc
downstream/modules/eda/proc-eda-set-up-rhaap-credential.adoc

Added new modules to [Chapter 7. Red Hat Ansible Automation Platform credential](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-set-up-rhaap-credential-type):
- downstream/modules/eda/con-replacing-controller-tokens.adoc
- downstream/modules/eda/proc-eda-delete-controller-token.adoc
- downstream/modules/eda/proc-eda-delete-rulebook-activations-with-cont-tokens.adoc

AAP-29905 Added new modules to the RH AAP credentials chapter

---

downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc
downstream/modules/eda/con-replacing-controller-tokens.adoc
downstream/modules/eda/proc-eda-delete-controller-token.adoc
downstream/modules/eda/proc-eda-delete-rulebook-activations-with-cont-tokens.adoc
downstream/modules/eda/proc-eda-set-up-credential.adoc
downstream/modules/eda/proc-eda-set-up-rhaap-credential.adoc

Added new modules to [Chapter 7. Red Hat Ansible Automation Platform credential](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-set-up-rhaap-credential-type):
- downstream/modules/eda/con-replacing-controller-tokens.adoc
- downstream/modules/eda/proc-eda-delete-controller-token.adoc
- downstream/modules/eda/proc-eda-delete-rulebook-activations-with-cont-tokens.adoc

 Backport-2.5-2469 (AAP-29905) Added new modules to the RH AAP credentials chapter (#2469)

---

downstream/modules/hub/con-offline-token-active.adoc
downstream/modules/hub/proc-create-api-token-pah.adoc
downstream/modules/hub/proc-create-api-token.adoc

This PR backports the changes from [PR 2492](https://github.com/ansible/aap-docs/pull/2492) to the 2.4 branch. See [AAP-33331](https://issues.redhat.com/browse/AAP-33331) for more info.

Backport to 2.4: AAP-33331: clarifies instructions on keeping offline hub token active

---

downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc

Updated the note in downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc (follows Google draft).

AAP-29905B Correction to note to link user to replacing tokens with RHAAP creds

---

downstream/modules/platform/proc-controller-api-browsing-api.adoc

Incorrect path for REST API info
https://issues.redhat.com/browse/AAP-34823

Updating path for REST api

---

downstream/modules/platform/proc-controller-api-browsing-api.adoc

Incorrect path for REST API info
https://issues.redhat.com/browse/AAP-34823

Updating path for REST api (#2501)

---

downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc

Update the Troubleshooting appendix of Containerized installation to included added context for troublehsooting execution environments
Affects `titles/aap-containerized-install`
Containerized installation - Add troubleshooting info for execution environments
https://issues.redhat.com/browse/AAP-34464

Add troubleshooting info for execution environments

---

downstream/assemblies/platform/assembly-aap-architecture.adoc

2.5 backport of [PR 2510](https://github.com/ansible/aap-docs/pull/2510)
[AAP-35120](https://issues.redhat.com/browse/AAP-35120)
Updated introductory paragraph to [Ch 2 Red Hat Ansible Automation Platform Architecture](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/planning_your_installation/aap_architecture)
assembly-aap-architecture.adoc

AAP-35120 updated architecture introduction (#2510)

---

downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc

* Add troubleshooting info for execution environments
Update the Troubleshooting appendix of Containerized installation to included added context for troublehsooting execution environments
Affects `titles/aap-containerized-install`
Containerized installation - Add troubleshooting info for execution environments
https://issues.redhat.com/browse/AAP-34464
* Update based on peer review feedback

2.5 Add troubleshooting info for execution environments (#2516)

---

downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc

Addresses [AAP-28125](https://issues.redhat.com/browse/AAP-28125) to deprecate the receptor option for worker python. Based on the changes made in [PR #1101](https://github.com/ansible/receptor/pull/1101).
***This needs to be backported to 2.4***

Added deprecation note for receptor.

---

attributes/attributes.adoc
stories/topics/con-azure-about.adoc

Self-managed Azure is not upgrading to the new AAP release for a while, so we need an attribute to track the current Azure version.

Clouds - Add attributes for current AAP version on Azure

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR backports the changes from #2537 to the 2.5 branch and includes the following:
* AAP-33062 - add more details for LDAP Group types
* AAP-33062 - added peer review suggestions

[Backport] AAP-33062 - add more details for LDAP Group types (#2537)

---

downstream/modules/platform/proc-running-setup-script-for-updates.adoc

Fix link in RPM upgrade guide
Affects `titles/upgrade/`

Fix link in RPM upgrade guide (#2545)

---

downstream/modules/platform/proc-aap-controller-backup.adoc

Addresses [AAP-32993](https://issues.redhat.com/browse/AAP-32993) by clarifying the format of the deployment name. I am unable to add Chris Meyers (chrismeyersfsu) as a reviewer but he needs to sign off in this.
The output will read as follows:
> In the **Deployment name** field, enter the name of the AutomationController custom resource object of the deployed Ansible Automation Platform instance being backed up. This name was created when you [created your AutomationController object](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html-single/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/index#aap-create_controller).

Elaborated on deployment name for backing up to clarify expected format.

---

downstream/modules/platform/proc-controller-create-container-group.adoc

Revamp the permissions for "pods/log" resource of an AAP container group
https://issues.redhat.com/browse/AAP-14596

Updating "pods/log" resource

---

downstream/modules/topologies/ref-cont-a-env-a.adoc

Add the missing port number 27199 in the Network Ports table to the CONT-A-ENV-A (Growth Container) tested topology.
Affects: `titles/topologies`
Tested deployment models - Update CONT-A-ENV-A port table to include 27199
https://issues.redhat.com/browse/AAP-35150

Add port 27199 to CONT-A-ENV-A in Supported deployment models

---

downstream/modules/topologies/ref-cont-a-env-a.adoc

Add the missing port number 27199 in the Network Ports table to the CONT-A-ENV-A (Growth Container) tested topology.
Affects `titles/topologies`
Tested deployment models - Update CONT-A-ENV-A port table to include 27199
https://issues.redhat.com/browse/AAP-35150

2.5 Add port 27199 to CONT-A-ENV-A in Supported deployment models (#2549)

---

downstream/modules/platform/proc-controller-create-container-group.adoc

Revamp the permissions for "pods/log" resource of an AAP container group
https://issues.redhat.com/browse/AAP-14596

Updating "pods/log" resource (#2523)

---

downstream/modules/platform/ref-ansible-inventory-variables.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

Add missing receptor vars (receptor_listener_port, receptor_listener_protocol) to the Inventory file variables appendix
Affects: `titles/aap-containerized-install` and `titles/aap-installation-guide`
Containerized installation - Update receptor inventory file vars in Inventory file variables
https://issues.redhat.com/browse/AAP-35192

Add missing receptor vars to inventory appendix

---

downstream/attributes/attributes.adoc
downstream/modules/platform/proc-define-mesh-node-types.adoc

Affects `/titles/operator-mesh/`
Part of AAP-32543
DO NOT PUBLISH THIS UNTIL SaaS IS RELEASED, because one of the updated files mentions SaaS!
Might be best to delay the backport to 2.5 for this reason.

AAP-32543 Clarify options in mesh node types definition

---

downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc

Describe how to view container logs for a pod from the OpenShift UI so that the user can verify that the plug-ins have been installed.
Affects `titles/aap-plugin-rhdh-install/`

AAP-34041 plug-ins: view container logs on OCP UI

---

downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc

Describe how to view container logs for a pod from the OpenShift UI so that the user can verify that the plug-ins have been installed.
Affects `titles/aap-plugin-rhdh-install/`

2.5 AAP-34041 plug-ins: view container logs on OCP UI (#2561)

---

downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc

Describe how to view container logs for a pod from the OpenShift UI so that the user can verify that the plug-ins have been installed.
Affects `titles/aap-plugin-rhdh-install/`

2.4 AAP-34041 plug-ins: view container logs on OCP UI (#2561)

---

downstream/modules/platform/proc-controller-cluster-deprovision-instances.adoc

Part of an ongoing project to fix broken links in the AAP doc set. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.

AAP-15176: fixes broken link in Configuring automation execution guide

---

downstream/modules/platform/proc-controller-cluster-deprovision-instances.adoc

This PR ports the changes from [PR 2566](https://github.com/ansible/aap-docs/pull/2566) to the 2.5 branch. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.

backport to 2.5: AAP-15176 fixes broken link in Configuring automation execution guide (#2566)

---

downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/ref-hub-variables.adoc

Add shared storage info to the installation section and include the relevant variables in the appendix
Affects: `titles/aap-containerized-install` and `titles/aap-installation-guide`
[doc] hub_shared_data_path missing in doc
https://issues.redhat.com/browse/AAP-30613

2.5 Add shared storage info to Containerized installation (#2570)

---

downstream/assemblies/hub/assembly-hub-create-api-token.adoc

This PR ports the changes from [PR 2574](https://github.com/ansible/aap-docs/pull/2574) to the 2.5 branch. See [AAP-35099](https://issues.redhat.com/browse/AAP-35099) for more.

Backport to 2.5: AAP-35099: adds info for token management with PAH and keycloak (#2574)

---

downstream/assemblies/hub/assembly-hub-create-api-token.adoc

This PR ports the changes from https://github.com/ansible/aap-docs/pull/2574 to the 2.4 branch. See [AAP-35099](https://issues.redhat.com/browse/AAP-35099) for more.

Backport to 2.4: AAP-35099: adds info for token management with PAH and keycloak (#2574)

---

downstream/modules/platform/con-gw-authenticator-map-triggers.adoc

This PR backports the changes made in #2579 to the 2.5 branch.

AAP-33304: Document case-sensitivity of authenticator map group triggers (#2579)

---

downstream/titles/release-notes/async/aap-25-4-20-nov.adoc

* AAP 2.5 (4) Async Release-Updated Release Notes
These release notes cover the current enhancements and bug fixes for the AAP 2.5 (4) release on November 20, 2024.
Resolves: AAP-35387
* Update aap-25-4-20-nov.adoc
* Update aap-25-4-20-nov.adoc
* Update aap-25-4-20-nov.adoc
* Update aap-25-4-20-nov.adoc
* Update aap-25-4-20-nov.adoc
* Update aap-25-4-20-nov.adoc
* Update aap-25-4-20-nov.adoc
* Update aap-25-4-20-nov.adoc

AAP 2.5 (4) Async Release-Updated Release Notes (#2588)

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc

Add information for troubleshooting the logs and containers in Containerized installation
Affects: `titles/aap-containerized-install`
Small additions to AAP Containerized Install Guide Troubleshooting section
https://issues.redhat.com/browse/AAP-33026

Add container troubleshooting info

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc

Add information for troubleshooting the logs and containers in Containerized installation
Affects: `titles/aap-containerized-install`
Small additions to AAP Containerized Install Guide Troubleshooting section
https://issues.redhat.com/browse/AAP-33026

2.5 Add container troubleshooting info (#2590)

---

downstream/modules/platform/proc-setup-postgresql-ext-database.adoc

Re-adding this content as the backport wasn't merged.
[Docs] Certificate auth support (mTLS) for ProgreSQL external DB instructions no longer present (overwritten)
https://issues.redhat.com/browse/AAP-36108

Add mTLS configuration for external databases

---

downstream/modules/platform/proc-setup-postgresql-ext-database.adoc

Re-adding this content as the backport wasn't merged.
[Docs] Certificate auth support (mTLS) for ProgreSQL external DB instructions no longer present (overwritten)
https://issues.redhat.com/browse/AAP-36108

2.5 Add mTLS configuration for external databases (#2592)

---

downstream/modules/platform/proc-aap-controller-backup.adoc

This PR backports the changes from #2330 to the 2.4 branch and includes the following:
* Elaborated on deployment name for backing up to clarify expected format.
* Updated step to describe the field better and how the user can find the name.

Elaborated on deployment name for backing up to clarify expected format (#2330)

---

downstream/modules/platform/proc-aap-controller-backup.adoc

This PR backports the changes from #2330 to the 2.5 branch and includes the following:
* Elaborated on deployment name for backing up to clarify expected format.
* Updated step to describe the field better and how the user can find the name.

[Backport] Elaborated on deployment name for backing up to clarify expected format (#2330)

---

downstream/modules/platform/proc-aap-controller-backup.adoc

This PR fixes a broken xref created by the changes from #2330. xrefs can't be used to link to another document, a link must be used.

Fixed broken link caused by PR 2330

---

downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
downstream/modules/platform/proc-controller-set-up-azure.adoc

Update documentation to refer to Microsoft Entra ID, formerly Azure Active Directory
https://issues.redhat.com/browse/AAP-35957

Adding Microsoft Entra ID reference to docs

---

lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
lightspeed/assemblies/assembly_generating-playbooks.adoc
lightspeed/titles/lightspeed-release-notes/master.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-11dec2024.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-35215.
Changes made:
- Updated references in the Lightspeed User guide for playbook generation support on onprem deployments. 
- Added a release notes announcement.

AAP-35215: Updated Lightspeed docs for playbook generation support on Lightspeed onpremise deployments

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR adds a note regarding signed certificates to the LDAP configuration doc as requested by AAP-36326.

Add note to LDAP configuration regarding signed certificates

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR backports the changes from #2611 to the 2.5 branch.

[Backport] Add note to LDAP configuration regarding signed certificates (#2611)

---

downstream/modules/hub/con-token-management-hub.adoc

Removes "context" from the module ID in con-token-management-hub.adoc.

Fixes module ascii formatting in the Managing automation content guide

---

downstream/modules/hub/con-token-management-hub.adoc

This PR ports the changes from [PR 2614](https://github.com/ansible/aap-docs/pull/2614) to the 2.5 branch.

Backport to 2.5: fixes module ascii formatting (#2614)

---

downstream/assemblies/platform/assembly-install-aap-operator.adoc
downstream/modules/eda/con-modifying-simultaneous-activations.adoc
downstream/modules/eda/proc-modifying-activations-during-install.adoc
downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/con-operator-custom-resources.adoc
downstream/modules/platform/ref-operator-crs.adoc

Enhancement to content about management of maximum running activations:
- Using automation decisions modules
- downstream/modules/eda/con-modifying-simultaneous-activations.adoc
- downstream/modules/eda/proc-modifying-activations-during-install.adoc
- Installing on OpenShift Container Platform
- downstream/modules/platform/con-operator-custom-resources.adoc
- downstream/modules/platform/ref-operator-crs.adoc

Backport-backport-2.5-2602 Enhance docs re: the management of maximum running activations

---

downstream/assemblies/hub/assembly-hub-create-api-token.adoc
downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
downstream/modules/hub/con-offline-token-active.adoc
downstream/modules/hub/con-token-management-hub.adoc
downstream/modules/hub/proc-create-api-token-pah.adoc
downstream/modules/hub/proc-create-api-token.adoc
downstream/modules/hub/proc-create-requirements-file.adoc
downstream/modules/hub/proc-set-community-remote.adoc
downstream/modules/hub/proc-set-rhcertified-remote.adoc

This PR ports the changes from [PR 2616](https://github.com/ansible/aap-docs/pull/2616/files) to the 2.5 branch. See [AAP 35928](https://issues.redhat.com/browse/AAP-35928) for context.

Backport to 2.5: Adds context attribute to assembly in Managing automation content 

---

downstream/modules/hub/proc-create-api-token.adoc

It looks like this error originated from a missed backport. The "main" version is as it should be.

Fixes ascii error in Note in Managing automation content guide

---

downstream/modules/platform/ref-controller-variables.adoc

Remove supervisor_start_retry_count from AAP 2.4 and 2.5 docs
https://issues.redhat.com/browse/AAP-36524

Removed 2.4 controller variable

---

lightspeed/attributes/attributes.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-34003. 
Changes made:
Imported AAP 2.5 attributes to Lightspeed docs so that they are consistent throughout the doc sets.

AAP-34003: Import AAP 2.5 attributes to Lightspeed docs

---

downstream/modules/platform/proc-upgrading-between-minor-aap-releases.adoc

update 2.4 docs to reflect breaking change around backups/restores
https://issues.redhat.com/browse/AAP-36246
Affects `titles/aap-installation-guide`

Add note regarding unsupported backups for earlier releases

---

downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc

Affects: `titles/topologies`
Update product docs to include IBM Z arch test support for CONT topologies
https://issues.redhat.com/browse/AAP-35969

2.5 Add IBM-Z to CONT topologies (#2642)

---

downstream/modules/platform/proc-configuring-the-metrics-utility.adoc

Openshift mis-capitalized in "Configuring automation execution"
https://issues.redhat.com/browse/AAP-36691

Minor edits to metrics utility section

---

downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
downstream/titles/release-notes/async/aap-25-5-4-dec.adoc
downstream/titles/release-notes/master.adoc

Note: the async release notes file is commented out in the `master.adoc` file until the release notes are ready to be published.
AAP 2.5 (5) Async Release
https://issues.redhat.com/browse/AAP-36423

Add async rns for async 2.5-5

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc

Satellite 6.16 has been released and still supports subscription allocations. This PR updates the language to reflect this. 
The update will appear in the "Important" admonition [here](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/managing_automation_content/managing-containers-hub#populate-container-registry). 
This work is being tracked in [AAP-36858](https://issues.redhat.com/browse/AAP-36858)

Updates subscription info for Satellite users in managing automation content guide

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc

This PR ports the changes from [PR 2620](https://github.com/ansible/aap-docs/pull/2620) to the 2.5 branch. See [AAP-36858](https://issues.redhat.com/browse/AAP-36858) for more context.

Backport to 2.5: Updates subscription info for Satellite users in managing automation content guide

---

downstream/modules/platform/ref-receptor-inventory-variables.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-36921.
Changes made:
- Added info. about the new 'receptor_datadir' variable and its caveats.

AAP-36921: Added info. about receptor_datadir variable

---

downstream/modules/platform/ref-receptor-inventory-variables.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-36921.
Changes made:
After updating the docs in PR https://github.com/ansible/aap-docs/pull/2655, I realized that I entered the detail in the wrong column (container variable name). This ticket rectifies the error, and adds the new variable in the correct 'RPM variable name' column.

AAP-36921-update: Added info. about receptor_datadir variable

---

downstream/modules/platform/ref-receptor-inventory-variables.adoc

This PR backports PR https://github.com/ansible/aap-docs/pull/2656 from main to 2.5.

Backport PR #2656 from main to 2.5.

---

downstream/modules/platform/ref-controller-variables.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-36921.
Changes made:
- Added info. about the new 'receptor_datadir' variable and its caveats.
- Added info. about the 'receptor_listener_protocol' that was perhaps missed from being included in 2.4 docs.

AAP-36921-2.4: Added info. about receptor variables

---

downstream/modules/platform/proc-controller-enable-provision-callbacks.adoc

Documentation for provisioning callbacks provides the wrong curl options
https://issues.redhat.com/browse/AAP-37039

Editing curl command

---

downstream/modules/platform/proc-controller-enable-provision-callbacks.adoc

Documentation for provisioning callbacks provides the wrong curl options
https://issues.redhat.com/browse/AAP-37039

Editing curl command (#2661)

---

downstream/modules/eda/proc-modifying-activations-after-install.adoc
downstream/modules/platform/con-operator-custom-resources.adoc

Issue [AAP-36614](https://issues.redhat.com/browse/AAP-36614) picks up on the problem described in [AAP-32980](https://issues.redhat.com/browse/AAP-32980). Discovered two minor necessary updates:
- Using automation decisions guide - update section [10.1.1.2. Modifying the number of simultaneous rulebook activations after Event-Driven Ansible controller installation](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-performance-tuning#modifying-activations-after-install) in the same manner as we did for section [10.1.1.1. Modifying the number of simultaneous rulebook activations during Event-Driven Ansible controller installation](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_aut …

AAP-36614 Apply updates for EDA max activations and correct link to OCP appendix

---

downstream/modules/eda/proc-modifying-activations-after-install.adoc
downstream/modules/platform/con-operator-custom-resources.adoc

Issue [AAP-36614](https://issues.redhat.com/browse/AAP-36614) picks up on the problem described in [AAP-32980](https://issues.redhat.com/browse/AAP-32980). Discovered two minor necessary updates:
- Using automation decisions guide - update section [10.1.1.2. Modifying the number of simultaneous rulebook activations after Event-Driven Ansible controller installation](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-performance-tuning#modifying-activations-after-install) in the same manner as we did for section [10.1.1.1. Modifying the number of simultaneous rulebook activations during Event-Driven Ansible controller installation](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_aut …

Backport-2.5-2663 (AAP-36614) Apply updates for EDA max activations and correct link to OCP apdx

---

downstream/modules/platform/con-adding-subscription-manifest.adoc

See [AAP-37105 ](https://issues.redhat.com/browse/AAP-37105)for more info.

AAP-37105: fixes incorrect link in the RPM Install guide

---

downstream/modules/platform/con-adding-subscription-manifest.adoc

This PR ports the changes from [PR 2673](https://github.com/ansible/aap-docs/pull/2673) to the 2.5 branch. See [AAP-37105](https://issues.redhat.com/browse/AAP-37105) for more.

Backport to 2.5: AAP-37105: fixes incorrect link (#2673)

---

downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc

[AAP-35971](https://issues.redhat.com/browse/AAP-35971)
- In Tested deployment models, move tested architectures (x86_64, AArch64) into a new row "CPU architecture".
- Update OCP topologies in Tested deployment models to include "s390x (IBM Z)" in the new CPU architecture row.

Adding edits from AAP-35971

---

downstream/modules/platform/ref-controller-setup-considerations.adoc

[Docs] 20 node limit in docs is obselete
https://issues.redhat.com/browse/AAP-23909

Removing 20 node limit from 2.4 doc

---

downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

Update the inventory file examples to match what's included when downloading the installers
Affects titles:
- `aap-containerized-install`
- `topologies`
Update the installer inventory files to match the ones supplied to the user
https://issues.redhat.com/browse/AAP-37239

Update inventory file examples

---

downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

Update the inventory file examples to match what's included when downloading the installers
Affects titles:
- `aap-containerized-install`
- `topologies`
Update the installer inventory files to match the ones supplied to the user
https://issues.redhat.com/browse/AAP-37239

2.5 Update inventory file examples (#2683)

---

downstream/modules/platform/ref-guidelines-hosts-groups.adoc

2.5 backport of [PR 2685](https://github.com/ansible/aap-docs/pull/2685)
[AAP-36934](https://issues.redhat.com/browse/AAP-36934)
ref-guidelines-hosts-groups.adoc
Google doc reference:
[DRAFT_Planning your installation_2.5](https://docs.google.com/document/d/1S4kHwLS7ctFsUN24mYk4IkmXQeGwffQ3WbChSdlbGQ4/edit?tab=t.0)
SME approval:
[Slack thread](https://redhat-internal.slack.com/archives/C035VBWU98D/p1733865799056479?thread_ts=1733828990.373669&cid=C035VBWU98D)
[Google doc comment](https://docs.google.com/document/d/1S4kHwLS7ctFsUN24mYk4IkmXQeGwffQ3WbChSdlbGQ4/edit?disco=AAABaB1TT1U)

AAP-36934 added note on external databases (#2685)

---

downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-36937.
Changes made:
Added notes about using external customer-created databases in the draft RPM installation guide, in the following sections:
- Setting up an external (customer supported) database
- Database variables
The changes were reviewed by the SME in the Google doc draft.

AAP-36937: Added info. external database and variable behavior

---

lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-11dec2024.adoc

This PR fixes and error caused by a duplicated file ID in the Lightspeed Release Notes.

Fix error in Lightspeed RN

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc
downstream/modules/hub/proc-obtain-images.adoc

This PR removes the subscription information in [this section of the Managing automation content guide](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/managing_automation_content/managing-containers-hub#obtain-images), specifically the info in the admonitions. See [AAP-3658 ](https://issues.redhat.com/browse/AAP-36858)for more info.

AAP-36858: updates subscription info in managing automation content guide

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc
downstream/modules/hub/proc-obtain-images.adoc

This PR backports the changes from [PR 2682](https://github.com/ansible/aap-docs/pull/2682) to the 2.5 branch. See [AAP-36858](https://issues.redhat.com/browse/AAP-36858) for more detail.

backport to 2.5: AAP-36858: updates subscription info in managing automation content guide

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc
downstream/modules/hub/proc-obtain-images.adoc

This PR backports the changes from [PR 2682](https://github.com/ansible/aap-docs/pull/2682) to the 2.4 branch. See [AAP-36858](https://issues.redhat.com/browse/AAP-36858) for more detail.

backport to 2.4: AAP-36858: updates subscription info in managing automation content guide

---

downstream/modules/hub/proc-obtain-images.adoc

This PR ports the changes from [PR 2698](https://github.com/ansible/aap-docs/pull/2698) to the 2.5 branch. See [AAP-36858](https://issues.redhat.com/browse/AAP-36858) for more detail.

backport to 2.5: AAP-36858 removes satellite link from section on pulling EEs (#2698)

---

downstream/modules/platform/proc-controller-inv-source-aap.adoc
downstream/modules/platform/proc-controller-inv-source-insights.adoc
downstream/modules/platform/proc-controller-inv-source-openstack.adoc
downstream/modules/platform/proc-controller-inv-source-rh-virt.adoc

Fix incorrect mention of gcp_compute / gce in Insights inventory plugin sections
https://issues.redhat.com/browse/AAP-37363

Fixing errors in inventory plugin sections

---

downstream/assemblies/topologies/assembly-appendix-topology-resources.adoc
downstream/titles/topologies/master.adoc

Adds this content to an appendix at the end of the document as it's relevant for all current topologies
Docs: Add link to IBM configuration documentation in Tested deployment models
https://issues.redhat.com/browse/AAP-37192

Add IBM support link to Tested deployment models

---

downstream/assemblies/topologies/assembly-appendix-topology-resources.adoc
downstream/titles/topologies/master.adoc

Adds this content to an appendix at the end of the document as it's relevant for all current topologies
Docs: Add link to IBM configuration documentation in Tested deployment models
https://issues.redhat.com/browse/AAP-37192

2.5 Add IBM support link to Tested deployment models (#2704)

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

This PR adds a note to the SAML setting for extra_data based on the information in https://issues.redhat.com/browse/AAP-33505.

AAP-33505 - Add clarifying note for SAML IDP extra_data details

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

This PR backports the changes from #2711 to the 2.5 branch and includes the following commits:
* AAP-33505 - Add clarifying note for SAML IDP extra_data details
* Added SME review changes

[Backport] AAP-33505 - Add clarifying note for SAML IDP extra_data details (#2711)

---

downstream/modules/platform/proc-aap-create-subscription-allocation.adoc

This PR backports the changes from #2719 to the 2.5 branch.

[Backport] Replaced satellite version number with the defined attribute (#2719)

---

downstream/modules/platform/proc-controller-azure-resource-manager.adoc
downstream/modules/platform/proc-controller-inv-source-gce.adoc

Add correct credentials link to GCE section
https://issues.redhat.com/browse/AAP-37382
Affects 'titles/controller-user-guide'

Correcting credentials link in user guide

---

downstream/modules/platform/proc-controller-azure-resource-manager.adoc
downstream/modules/platform/proc-controller-inv-source-gce.adoc

Add correct credentials link to GCE section
https://issues.redhat.com/browse/AAP-37382
Affects 'titles/controller/user-guide'

Correcting credentials link in user guide (#2724)

---

downstream/modules/platform/proc-controller-create-container-group.adoc

[Doc Bug] : Container group service account example missing.
https://issues.redhat.com/browse/AAP-38107

Minor correction to container group procedure

---

downstream/modules/platform/proc-controller-create-container-group.adoc

[Doc Bug] : Container group service account example missing.
https://issues.redhat.com/browse/AAP-38107

Minor correction to container group procedure (#2736)

---

downstream/assemblies/platform/assembly-controller-management-jobs.adoc

Remove docs on "Cleanup Expired OAuth 2 Tokens"
https://issues.redhat.com/browse/AAP-37805

Removing cleanup string from controller docs

---

downstream/assemblies/platform/assembly-controller-management-jobs.adoc

Remove docs on "Cleanup Expired OAuth 2 Tokens"
https://issues.redhat.com/browse/AAP-37805

Removing cleanup string from controller docs (#2738)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc

Update the prereqs in Containerized installation to denote RHEL 9.2 or later as opposed to just RHEL 9.2
[Docs] update Red Hat Enterprise Linux (RHEL) version in Containerized installer documentation
https://issues.redhat.com/browse/AAP-38119

Update RHEL requirements for containerized installation

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc

Update the prereqs in Containerized installation to denote RHEL 9.2 or later as opposed to just RHEL 9.2
[Docs] update Red Hat Enterprise Linux (RHEL) version in Containerized installer documentation
https://issues.redhat.com/browse/AAP-38119

2.5 Update RHEL requirements for containerized installation (#2741)

---

downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-35970. 
Changes made: 
In Tested deployment models for RPM installation:
-  Moved tested architectures (x86_64, AArch64) into a new row "CPU architecture".
- Updated RPM topologies to include "s390x (IBM Z)" in the new CPU architecture row.
The above updates are made in the ' Tested system configurations' table for RPM growth topology, RPM mixed growth topology, RPM enterprise topology, and RPM mixed enterprise topology.

AAP-35970: AAP-35970: Added IBM Z arch test support in RPM topologies

---

downstream/assemblies/platform/assembly-controller-applications.adoc
downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR adds the changes requested for the customer docs in https://issues.redhat.com/browse/AAP-37120. 
Once a KCS article is published to handle this via the API, the LDAP note will be update to include a link to the article.

Added notice that OAuth and LDAP data migration is not supported in the platform ui

---

downstream/assemblies/platform/assembly-controller-applications.adoc
downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR backports the changes from #2370 to the 2.5 branch.

[Backport] Added notice that OAuth and LDAP data migration is not supported in the platform ui (#2730)

---

downstream/modules/platform/proc-settings-gw-security-options.adoc

This PR backports the changes from #2752 to the 2.5 branch.

[Backport] AAP-38268 - corrected typo (#2752)

---

downstream/modules/platform/proc-gw-role-mapping.adoc
downstream/modules/platform/proc-gw-superuser-mapping.adoc

This PR corrects the Superuser mapping content to correctly follow the superuser workflow rather than the Role workflow. It also corrects a UI selection in the Role mapping content.

AAP-38561 - Corrected superuser mapping content

---

downstream/modules/platform/proc-gw-role-mapping.adoc
downstream/modules/platform/proc-gw-superuser-mapping.adoc

This PR backports the changes from #2759 to the 2.5 branch.

[Backport] AAP-28561 - Corrected superuser mapping content (#2759)

---

downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/snippets/redis-colocation-containerized.adoc

Update the Redis colocation note for the containerized enterprise topology. Redis can be colocated on controller but not on execution nodes or the PostgreSQL database. This is specific to the containerized install.
Clearly spell out colocation capabilities of Redis, RPM and Containerized
https://issues.redhat.com/browse/AAP-36021

Update redis colocation info for Containerized enterprise topology

---

downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
downstream/modules/platform/proc-controller-configure-transparent-SAML.adoc
downstream/modules/platform/proc-controller-set-up-SAML.adoc

No Documentation Exists for Transparent SAML Logins in AAP 2.5
https://issues.redhat.com/browse/AAP-38120

Adding Transparent SAML Login proc in AAP 2.5

---

downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
downstream/modules/platform/proc-controller-configure-transparent-SAML.adoc
downstream/modules/platform/proc-controller-set-up-SAML.adoc

* Adding Transparent SAML Login proc in AAP 2.5
No Documentation Exists for Transparent SAML Logins in AAP 2.5
https://issues.redhat.com/browse/AAP-38120

Adding Transparent SAML Login proc in AAP 2.5 (#2743)

---

downstream/modules/platform/con-gw-clustered-redis.adoc

This PR updates the Redis doc to explicitly state the requirement for 6VMs and includes a link to the deployment topologies to address customer feedback in https://issues.redhat.com/browse/AAP-36580.

AAP-36580 added a note that explicitly states 6 VMs are required

---

downstream/modules/platform/con-gw-clustered-redis.adoc

This PR backports the changes from #2781 to the 2.5 branch.

[Backport] AAP-36580 added a note that explicitly states 6 VMs are required (#2781)

---

lightspeed/modules/con_overview-lightspeed-onpremise.adoc
lightspeed/modules/proc_monitor-onpremise-deployment.adoc
lightspeed/modules/proc_multi-task-recs.adoc
lightspeed/modules/proc_single-task-recs.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-38563. 
Changes made:
- Corrected the broken links that pointed to AAP docs.

AAP-38563: Corrected the broken AAP guide URLs

---

downstream/modules/platform/ref-postgresql-requirements.adoc

This PR backports PR https://github.com/ansible/aap-docs/pull/2793 from main to AAP 2.5 repo.

AAP-38369: Updated a crossreference to point to downstream docs (#2793)

---

downstream/modules/eda/con-custom-credential-types.adoc

Per request in [AAP-35762](https://issues.redhat.com/browse/AAP-35762), added newly supported injectors `file` and `env` along with descriptions to the Injector configuration section of the Custom credential types sub-chapter in the Using automation decisions guide. Updates to downstream/modules/eda/con-custom-credential-types.adoc.

AAP-35762 Added newly supported file and env injectors

---

downstream/modules/eda/con-custom-credential-types.adoc

Per request in [AAP-35762](https://issues.redhat.com/browse/AAP-35762), added newly supported injectors file and env along with descriptions to the Injector configuration section of the Custom credential types sub-chapter in the Using automation decisions guide. Updates to downstream/modules/eda/con-custom-credential-types.adoc.

Backport-2.5-2785 (AAP-35762) Added newly supported file and env injectors (#2785)

---

downstream/modules/platform/con-gw-clustered-redis.adoc

This PR updates the note to eliminate confusion regarding Redis colocation between RPM and containerized deployments.

AAP-38856 updated note to specify that colocation limitation is specific to RPM

---

downstream/modules/platform/con-gw-clustered-redis.adoc

This PR backports the changes from #2807 to the 2.5 branch and includes the following:
* AAP-38856 updated note to specify that colocation limitation is specific to RPM
* Added contianerized colocation details

AAP-38856 updated note to specify that colocation limitation is specific to RPM (#2807)

---

downstream/modules/platform/ref-hub-variables.adoc

Replaced automationhub_main_url
Replace entry for automationhub_main_url
https://issues.redhat.com/browse/AAP-39218

Replaced missing variable

---

downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc

See [AAP-31257](https://issues.redhat.com/browse/AAP-31257) for more info.

AAP-31257: corrects typos and attributes in the managing automation content guide

---

downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc

This PR backports the changes from [PR 2822](https://github.com/ansible/aap-docs/pull/2822) to the 2.5 branch. See [AAP-34599](https://issues.redhat.com/browse/AAP-34599) for more.

backport to 2.5: AAP-31257: corrects typos and attributes in the managing automation content guide (#2822)

---

downstream/modules/eda/con-event-streams.adoc

Per AAP-38758, removed Mutual TLS from the event stream type table in [6.1 Event streams](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/simplified-event-routing#event-streams) in the [Using automation decisions guide](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/index).

AAP-38758 Removed the unsupported Mutual TLS entry

---

downstream/modules/eda/con-event-streams.adoc

Per AAP-38758, removed Mutual TLS from the event stream type table in [6.1 Event streams](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/simplified-event-routing#event-streams) in the [Using automation decisions guide](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/index).

Backport -2.5-2819 (AAP-38758) Removed the unsupported Mutual TLS entry

---

downstream/modules/platform/proc-gw-superuser-mapping.adoc

This PR removes the information specific to Role mapping from the Superuser mapping section.

Removed information regarding role mapping from superuser mapping

---

downstream/modules/platform/proc-gw-superuser-mapping.adoc

This PR backports the changes from #2830 to the 2.5 branch.

removed information regarding role mapping from superuser mapping (#2830)

---

downstream/modules/platform/proc-installing-with-internet.adoc

[AAP-30609](https://issues.redhat.com/browse/AAP-30609)
Clarified commands for [installing with internet access](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/planning_your_installation/index#proc-installing-with-internet_planning). See [google doc](https://docs.google.com/document/d/1eYyOfZnNT30ZyZWpb8Di29wZ_Nf1xSqGkxGpXKptLk4/edit?tab=t.0#heading=h.v9wks5gmaxlp) for SME guidance.
- proc-installing-with-internet.adoc

AAP-30609 updated script for installing with internet access

---

downstream/modules/platform/proc-installing-with-internet.adoc

2.5 backport for [PR 2770](https://github.com/ansible/aap-docs/pull/2770)
[AAP-30609](https://issues.redhat.com/browse/AAP-30609)
Clarified commands for [installing with internet access](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/planning_your_installation/index#proc-installing-with-internet_planning). See [google doc](https://docs.google.com/document/d/1eYyOfZnNT30ZyZWpb8Di29wZ_Nf1xSqGkxGpXKptLk4/edit?tab=t.0#heading=h.v9wks5gmaxlp) for SME guidance.
proc-installing-with-internet.adoc

AAP-30609 updated script for installing with internet access (#2770)

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

Update the receptor-related inventory file vars to add more clarity and ensure RPM and CONT equivalents are defined.
In ref-controller-variables.adoc:
- note_type
- peers
In ref-receptor-variables.adoc:
- receptor_type
- receptor_peers
Containerized installation - improvements to receptor inventory vars in the appendix
https://issues.redhat.com/browse/AAP-39338

Update receptor inventory file vars in appendix

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

* Update receptor inventory file vars in appendix
Update the receptor-related inventory file vars to add more clarity and ensure RPM and CONT equivalents are defined.
In ref-controller-variables.adoc:
- note_type
- peers
In ref-receptor-variables.adoc:
- receptor_type
- receptor_peers
Containerized installation - improvements to receptor inventory vars in the appendix
https://issues.redhat.com/browse/AAP-39338
* Updates based on SME feedback

2.5 Update receptor inventory file vars in appendix (#2851)

---

downstream/modules/hub/proc-adding-an-execution-environment.adoc
downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc

This PR updates the [procedure for signing execution environments](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/managing_automation_content/managing-containers-hub#deploying-your-system-for-container-signing) in the Managing automation content guide. See [AAP-34599](https://issues.redhat.com/browse/AAP-34599) for more info.

AAP-34599: updates procedure for signing EEs

---

downstream/modules/hub/proc-adding-an-execution-environment.adoc
downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc

This PR backports the changes from [PR 2821](https://github.com/ansible/aap-docs/pull/2821) to the 2.5 branch. See [AAP-34599](https://issues.redhat.com/browse/AAP-34599) for more info.

backport to 2.5: AAP-34599: updates procedure for signing EEs (#2821)

---

downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
downstream/titles/release-notes/async/aap-25-5-3-dec.adoc

corresponding JIRA ticket number.
Resolves:AAP-37433

Update release notes for 11/20/24 and 12/04/24 with the

---

downstream/titles/release-notes/topics/aap-25-known-issues.adoc

AAP-38830 resolved the known issue that necessetated the snippet in the RN. Now that it's resolved, the snippet should be removed from the release notes.
Update Docs for hub_seed_collections=true for containerized installer
https://issues.redhat.com/browse/AAP-38830

Remove snippet from known issues as it is resolved

---

downstream/titles/release-notes/topics/aap-25-known-issues.adoc

AAP-38830 resolved the known issue that necessetated the snippet in the RN. Now that it's resolved, the snippet should be removed from the release notes.
Update Docs for hub_seed_collections=true for containerized installer
https://issues.redhat.com/browse/AAP-38830

Remove snippet from known issues as it is resolved (#2870)

---

downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc

This PR adds an additional resources block to the containerized install guide with a relevant link to the managing automation content guide. See [AAP-34599 ](https://issues.redhat.com/browse/AAP-34599)for more.

AAP-34599: adds additional resources block to containerized guide

---

downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc

Fix a broken xref in `titles/hub/managing-content` that was causing the build to fail.
Replace the xref with a link because this module will be used in an assembly in another book.

Fix xref in hub module

---

downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc

Fix a broken xref in `titles/hub/managing-content` that was causing the build to fail.
Replace the xref with a link because this module will be used in an assembly in another book.

2.5 Fix xref in hub module (#2879)

---

downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc

This PR ports the changes from [PR 2856](https://github.com/ansible/aap-docs/pull/2856/files) to the 2.5 branch. See [AAP-34599](https://issues.redhat.com/browse/AAP-34599) for more info.

backport to 2.5: AAP-34599: adds additional resources block to containerized guide 

---

downstream/modules/platform/ref-configuring-inventory-file.adoc
downstream/modules/platform/ref-ha-hub-reqs.adoc
downstream/modules/platform/ref-hub-variables.adoc

- Update ref-ha-hub-reqs.adoc to denote NFS is the supported shared storage type for RPM installs.
- Update ref-configuring-inventory-file.adoc to ensure all supported storage backend options are documented for Container installs - NFS, Azure Blob, and S3.
- Update ref-hub-variables.adoc to ensure all inventory file vars relevant to storage backends for hub are documented.
Document supported automation hub shared storage options
https://issues.redhat.com/browse/AAP-29150

Update storage backend options for more clarity (#2869)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
downstream/modules/platform/ref-ansible-inventory-variables.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

- Separate the procedure out into its own file specific to containerized installation
- Update the inventory vars with the vars needed for ext db configuration
- Update ordering of inventory vars appendix so it's alphabetical
Docs - Ensure external database setup steps are documented per the current functionality
https://issues.redhat.com/browse/AAP-39006

Update containerized installation ext db configuration

---

downstream/modules/hub/proc-adding-an-execution-environment.adoc
downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
downstream/modules/hub/proc-using-podman-ensure-image-signed.adoc

This PR ports the changes from [PR 2896](https://github.com/ansible/aap-docs/pull/2896) to the 2.5 branch. See [AAP-37377](https://issues.redhat.com/browse/AAP-37377) for more.

Backport to 2.5: AAP-37377 Updates attribute in Managing automation content guide

---

downstream/modules/platform/ref-operator-crs.adoc

Set eda.disabled to true
BUG - Logic error within the custom resource definition for gateway that would deploy EDA instead of just connecting to Controller and Hub
https://issues.redhat.com/browse/AAP-40045

Correct custom resource definition (#2904)

---

downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc

Updated the Access rules for applications and tokens to remove incorrect information related to organization administrators.

AAP-38726 - Removed incorrect access notes for org admin for tokens/apps

---

downstream/modules/platform/proc-enable-hstore-extension.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc

[Docs] hstore extension information is missing for the AAP Containerized Installation
https://issues.redhat.com/browse/AAP-39769

Add hstore proc to Containerized installation

---

downstream/modules/platform/proc-enable-hstore-extension.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc

[Docs] hstore extension information is missing for the AAP Containerized Installation
https://issues.redhat.com/browse/AAP-39769

2.5 Add hstore proc to Containerized installation (#2912)

---

downstream/modules/platform/proc-install-aap-operator.adoc

AnsibleLightspeed Custom Resource and Ansible Lightspeed Operator is being deployed when installing the AAP 2.4 operator which is not accounted for in the documentation
Adding a verification section to the install chapter where a user can confirm what should be including in their deployment

AAP-32834 2.4 specific changes

---

downstream/modules/platform/proc-install-aap-operator.adoc

AnsibleLightspeed Custom Resource and Ansible Lightspeed Operator is being deployed when installing the AAP 2.4 and 2.5 operator which is not accounted for in the documentation
- Adding a verification section to the install chapter where a user can confirm what should be including in their deployment 
- Also touched up the information for cluster scoped channel

Adding CR details to Installing chapter

---

downstream/modules/platform/proc-gw-editing-a-user.adoc

This PR backports the changes from #2925 to the 2.5 branch and includes the following:
* AAP-39927 Added descriptions for the service level administrator checkboxes
* AAP-39927 - updated statement to indicate that Platform admins can revoke or assign
* AAP-39927 - implement peer review changes
* AAP-39927 - changed hub to content in description

AAP-39927 Added descriptions for the service level administrator checkboxes (#2925)

---

downstream/titles/release-notes/async/aap-25-20250213.adoc

Added/updated the following to the version table:
Container-based installer Ansible Automation Platform (bundle) 2.5-10 
Container-based installer Ansible Automation Platform (online) 2.5-10 
RPM-based installer Ansible Automation Platform (bundle) 2.5-8.1
RPM-based installer Ansible Automation Platform (online) 2.5-8
Added the following to Known Issues:
Deploying the platform gateway on FIPS enabled RHEL 9 is currently not supported.(AAP-39146)

Updated release note content for asyn-20250213

---

downstream/titles/release-notes/async/aap-25-20250213.adoc

Added/updated the following to the version table:
Container-based installer Ansible Automation Platform (bundle) 2.5-10 Container-based installer Ansible Automation Platform (online) 2.5-10 RPM-based installer Ansible Automation Platform (bundle) 2.5-8.1 RPM-based installer Ansible Automation Platform (online) 2.5-8
Added the following to Known Issues:
Deploying the platform gateway on FIPS enabled RHEL 9 is currently not supported.(AAP-39146)

Updated release not content for asyn-20250213 (#2929)

---

downstream/modules/builder/con-about-ee.adoc

This PR ports the changes from[ PR 2931](https://github.com/ansible/aap-docs/pull/2931) to the 2.5 branch. See [AAP-40325](https://issues.redhat.com/browse/AAP-40325) for more.

backport to 2.5: AAP-40325: updates ansible core version in EE guide (#2931)

---

downstream/assemblies/platform/assembly-operator-upgrade.adoc

This PR includes the post upgrade steps for the migration of users and SSO configurations to AAP 2.5 after a successful upgrade.

40016 - Adding post upgrade assembly to the OCP guide

---

downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc

AAP2.5 containerized topologies port is incorrect.
https://issues.redhat.com/browse/AAP-40365

Correct port no typo in CONT topologies

---

downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc

AAP2.5 containerized topologies port is incorrect.
https://issues.redhat.com/browse/AAP-40365

2.5 Correct port no typo in CONT topologies (#2934)

---

downstream/assemblies/platform/assembly-operator-upgrade.adoc

This PR backports the changes from #2933 to the 2.5 branch.

[Backport] 40016 - Adding post upgrade assembly to the OCP guide (#2933)

---

downstream/modules/platform/proc-operator-deploy-redis.adoc

[AAP-40435](https://issues.redhat.com/browse/AAP-40435)
[Step 5.ii ](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/installing_on_openshift_container_platform/index#installing-hub-operator) "redis_mode: clustered", should be "redis_mode: cluster"

AAP-40435 - Typo fix

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc

This PR ports the changes from [PR 2943](https://github.com/ansible/aap-docs/pull/2943) to the 2.5 branch. See [AAP-40425](https://issues.redhat.com/browse/AAP-40425) for more.

Backport to 2.5: AAP-4025 updates admonition about container image pulls in hub guide (#2943)

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc

This PR ports the changes from https://github.com/ansible/aap-docs/pull/2943 to the 2.4 branch. See [AAP-40425](https://issues.redhat.com/browse/AAP-40425) for more.

Backport to 2.4: AAP-40425 updates admonition about container image pulls in hub guide (#2943)

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc

This PR ports the changes from https://github.com/ansible/aap-docs/pull/2943 to the 2.3 branch. See [AAP-40425](https://issues.redhat.com/browse/AAP-40425) for more.

Backport to 2.3: AAP-40425 updates admonition for pulling container images

---

downstream/modules/platform/proc-gw-config-keycloak-settings.adoc

This PR adds information for re-enabling the audience in keycloak authentication configurations and provides a link to the python docs to address errors in keycloak configs.

AAP-37455 - added information for re-enabling the audience in keycloak

---

ansible-inside/topics/proc-ansible-inside-install-registry.adoc
ansible-inside/topics/ref-ansible-inside-prereqs.adoc

AAP-36668 Update RPMs and EEs for Ansible Inside 1.3

AAP-36668 Update RPMs and EEs for Ansible Inside 1.3

---

downstream/assemblies/platform/assembly-aap-platform-components.adoc
downstream/titles/aap-planning-guide/master.adoc

[AAP-34926](https://issues.redhat.com/browse/AAP-34926)
Removed [Chapter 2: Red Hat Ansible Automation Platform Architecture](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/planning_your_installation/index#aap_architecture) from _Planning your Installation_ and re-organize the guide as follows:
- Chapter 1. Planning your Red Hat Ansible Automation Platform Installation
- Chapter 2. Red Hat Ansible Automation Platform components
- Chapter 3. Caching and queueing system
- Chapter 4. Overview of tested deployment models
- Chapter 5. System requirements
- Chapter 6. Network ports and protocols
- Chapter 7. Choosing and obtaining a Red Hat Ansible Automation Platform installer
- Chapter 8. About the installer inventory file
Files modified: 
- …

AAP-34926 updated Planning guide organization

---

downstream/assemblies/platform/assembly-aap-platform-components.adoc
downstream/titles/aap-planning-guide/master.adoc

2.5 backport of [PR 2891](https://github.com/ansible/aap-docs/pull/2891)
[AAP-34926](https://issues.redhat.com/browse/AAP-34926)
- master.adoc

AAP-34926 updated Planning guide organization (#2891)

---

downstream/assemblies/platform/assembly-aap-platform-components.adoc

Fixed typo in https://github.com/ansible/aap-docs/pull/2891
[AAP-34926](https://issues.redhat.com/browse/AAP-34926)

AAP-34926A fixed typo

---

downstream/modules/platform/proc-controller-user-permissions.adoc
downstream/modules/platform/ref-controller-user-roles.adoc

This PR adds a note that explicitly states the users and teams can not be added to organizations through the Roles procedure to address https://issues.redhat.com/browse/AAP-40151.

AAP-40151 - added note about adding users and teams to organizations

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
downstream/modules/platform/ref-postgresql-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc

This PR addresses doc updates for JIRA https://issues.redhat.com/browse/AAP-37564. 
Changes made in incremental stages:
- In RPM installation, added ICU support for PostgreSQL databases + minor language edits.
- In containerized installation, added section for 'PostgreSQL requirements' and added ICU support for PostgreSQL databases.
- In operator enterprise topology, ICU support for PostgreSQL databases.

AAP-37564: Added ICU support for PostgreSQL database

---

lightspeed/modules/con_overview-lightspeed-onpremise.adoc
lightspeed/modules/proc_create-connection-secrets.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-40686.
Changes made:
- Updated the URLs of 'watsonx Code Assistant for Red Hat Ansible Lightspeed on Cloud Pak for Data docs' with the latest version URLs.

AAP-40686: AAP-40686: Updated the Lightspeed User Guide with latest IBM doc URLs

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc
downstream/modules/platform/ref-using-custom-tls-certificates.adoc

Update the section "Using custom TLS certificates" in Containerized installation
- Ensure all vars are correctly documented for use
- Ensure it's clear what vars to use for what scenarios
- Referenced vars are documented in the appendix
Containerized installation - Add Redis TLS certs to Using custom TLS certs section
https://issues.redhat.com/browse/AAP-39523

Update using custom TLS certs ref

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc
downstream/modules/platform/ref-using-custom-tls-certificates.adoc

Update the section "Using custom TLS certificates" in Containerized installation
- Ensure all vars are correctly documented for use
- Ensure it's clear what vars to use for what scenarios
- Referenced vars are documented in the appendix
Containerized installation - Add Redis TLS certs to Using custom TLS certs section
https://issues.redhat.com/browse/AAP-39523

2.5 Update using custom TLS certs ref (#2985)

---

downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc

Per instructions from meeting with SMEs, `de-supported` will be replaced with `de-minimal` images for decision environments, until further notice. 
Will refer to `de-minimal` only for now to prevent confusion for users. EDA collections have been added by @jamesmarshall24 to `de-minimal` images for now.

AAP-36005 Removed instances of de-supported options

---

downstream/modules/hub/con-token-management-hub.adoc

See [AAP-36148](https://issues.redhat.com/browse/AAP-36148) for more

AAP-36148: adds note reminding users that basic auth/service accounts are not supported for hub authentication

---

downstream/assemblies/hub/assembly-hub-create-api-token.adoc

This PR ports the changes from https://github.com/ansible/aap-docs/pull/2975 to the 2.4 branch. See [AAP-36148](https://issues.redhat.com/browse/AAP-36148) for more.

[Bp 2.4] AAP-36148: adds note reminding users that basic auth/service accounts are not supported in hub

---

downstream/assemblies/platform/assembly-controller-secret-management.adoc
downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
downstream/modules/platform/proc-controller-github-app-token.adoc

Docs for Ansible Automation Platform source control authentication with GitHub Apps instead of PAT
https://issues.redhat.com/browse/AAP-37274

Adding Git Hub app token proc

---

downstream/assemblies/platform/assembly-controller-secret-management.adoc
downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
downstream/modules/platform/proc-controller-github-app-token.adoc

* Adding Git Hub app token proc
Docs for Ansible Automation Platform source control authentication with GitHub Apps instead of PAT
https://issues.redhat.com/browse/AAP-37274
* Fixing UI spelling error

Adding Git Hub app token proc (#3015)

---

downstream/assemblies/eda/assembly-eda-credentials.adoc
downstream/modules/eda/proc-eda-duplicate-credential.adoc

Added a new module to the [Credentials](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credentials) chapter: 
- "Copying a credential", downstream/modules/eda/proc-eda-duplicate-credential.adoc

AAP-35987 Added new procedure for copying credentials

---

downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc

Per work required for [AAP-36005](https://issues.redhat.com/browse/AAP-36005) (previous PR https://github.com/ansible/aap-docs/pull/2632): 
* AAP-36005 Removed instances of de-supported options as de-minimal is the main option for now
* AAP-36005 Updated the RHEL versions for decision environment container links

AAP-41122 - Backport ticket for AAP-36005 (`de-minimal` vs. `de-supported` images for building DEs)

---

downstream/assemblies/eda/assembly-eda-credentials.adoc
downstream/modules/eda/proc-eda-duplicate-credential.adoc

Added a new module to the [Credentials](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credentials) chapter:
- "Copying a credential", downstream/modules/eda/proc-eda-duplicate-credential.adoc

[2.5 Backport] AAP-35987 [DOC] Document Copy Credential in EDA for parity with AAP

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

Change postgreSQL to Redis
[Docs] Wrong Redis services in "Network Ports and Protocols"
https://issues.redhat.com/browse/AAP-41021

Correct port service type

---

downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/modules/platform/proc-aap-add-allowed-registries.adoc

[AAP-40833](https://issues.redhat.com/browse/AAP-40833)   Manually adding Hub Operator as an EE image source to the OCP cluster policy
New module added to Section 7 in 2.5. 
Same module to be added to Section 13 in 2.4

 AAP-40833 edits

---

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/modules/platform/proc-aap-add-allowed-registries.adoc

[AAP-40833](https://issues.redhat.com/browse/AAP-40833) Manually adding Hub Operator as an EE image source to the OCP cluster policy
New module added to Section 7 in 2.5.
Same module to be added to Section 13 in 2.4

AAP-40833 2.4 edits

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/ref-system-requirements.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/cont-tested-vm-config.adoc

Minimum Supported Versions Need to Call Out Specific Major RHEL Versions
https://issues.redhat.com/browse/AAP-41627

Add callout for RHEL support in aap-docs

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/ref-system-requirements.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/cont-tested-vm-config.adoc

Minimum Supported Versions Need to Call Out Specific Major RHEL Versions
https://issues.redhat.com/browse/AAP-41627

2.5 Add callout for RHEL support in aap-docs (#3070)

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

The User Permanent ID is a required field in the SAML configuration process. The UI currently does not label the field as required, so I've added that information to the step in the procedure to eliminate confusion.

AAP-36381 - add required statement to User Permanent ID field

---

downstream/assemblies/platform/assembly-edge-manager-intro.adoc
downstream/modules/platform/con-edge-manager-core-capabilities.adoc
downstream/titles/edge-manager/edge-manager-user-guide/master.adoc

* Adding Edge Manager intro/overview to docs
[Docs] Flight Control Introduction
https://issues.redhat.com/browse/AAP-39616
Affects `titles/edgem-manager-user-guide`
* Tech review edits
* Tech review edits of intro section
* Edits to intro section

Adding Edge Manager intro/overview to docs (#2991)

---

downstream/modules/platform/proc-controller-configure-analytics.adoc
downstream/modules/platform/proc-controller-create-insights-credential.adoc

* Adding service account info to controller docs
Document controller changes needed for service accounts
https://issues.redhat.com/browse/AAP-36066
Affects `titles/controller-user-guide``
* Tech review edits
* Fixing punctuation error
* Tech review further edits
* Minor wording edit in service account proc
* Final tech review changes
* Peer review update

Adding service account info to controller docs (#2978)

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

In the Notes admonition of [Chapter 1. Event-Driven Ansible controller overview](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_decisions/index#eda-user-guide-overview), updated the current URL for EDA API docs

AAP-42062 Correct the URL for the EDA API docs in Chapt 1 of Using automation decisions

---

downstream/titles/topologies/docinfo.xml

Fixed a typo in the abstract sentence of "topologies".
https://issues.redhat.com/browse/AAP-42122

AAP-42122: Fixed typo in topologies

---

downstream/titles/topologies/docinfo.xml

Backport for:
Fixed a typo in the abstract sentence of "topologies".
https://issues.redhat.com/browse/AAP-42122

Backport-2.5-3092: AAP-42122 Fixed typo in topologies (#3092)

---

lightspeed/assemblies/assembly_administering-ansible-lightspeed.adoc
lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
lightspeed/assemblies/assembly_starting-lightspeed-trial.adoc
lightspeed/modules/con_overview-lightspeed-onpremise.adoc
lightspeed/modules/proc_monitor-onpremise-deployment.adoc
lightspeed/modules/proc_multi-task-recs.adoc
lightspeed/modules/proc_remove-seat-licenses.adoc
lightspeed/modules/proc_use-rest-api.adoc

This PR addresses the following:
- JIRA https://issues.redhat.com/browse/AAP-39112  - docs for using Lightspeed REST API.
- Slack request to add info. about 'trial accounts not requiring API key and model ID'. Slack thread: https://redhat-internal.slack.com/archives/C068PH68Y6B/p1742198334830579.

AAP-39112: Developed docs for Lightspeed REST API

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-upgrade-external-db-gateway.adoc

[AAP-38389](https://issues.redhat.com/browse/AAP-38389) 
Our [current documentation](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/installing_on_openshift_container_platform/operator-upgrade_operator-platform-doc#upgrading-operator_operator-upgrade) for AAP operator contains steps for upgrading AAP2.4 to AAP2.5 but the steps to upgrade are missing for the scenario when the database is external. 
[Draft](https://docs.google.com/document/d/1p6PV40xWe4E2XEQ9MChaURAklf3X-zJ91dJZzJE4YwU/edit?tab=t.0) with SME approved edits

AAP-38389 Ext DB upgrade edits

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

[AAP-41743](https://issues.redhat.com/browse/AAP-41743) requests for an update to [Chapter 6. Network ports and protocols](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/planning_your_installation/index#ref-network-ports-protocols_planning) in the **Ansible Automation Platform Network ports and protocols** table. Specifically, we need to add an entry for Port 8443, which must be open for Event-Driven Ansible.
cc: @emurtoug (owner of the Planning guide)

AAP-41743 Missing Information About Port 8443 being required for EDA in Network port table

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

AAP-42062: In the Notes admonition of [Chapter 1. Event-Driven Ansible controller overview](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_decisions/index#eda-user-guide-overview), updated the current URL for EDA API docs.

Backport-2.5-3090 (AAP-42062) Correct the URL for the EDA API docs in the automation decisions guide

---

lightspeed/modules/proc_configure-vscode-extension.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-20march2025.adoc

This JIRA addresses minor updates to PR https://github.com/ansible/aap-docs/pull/3110  as part of JIRA https://issues.redhat.com/browse/AAP-34928 .
Changes made: Added hyperlinks to release notes blurb.

AAP-34928-update: Added URLs in release notes blurb

---

downstream/modules/platform/ref-containerized-system-requirements.adoc

In the Planning your installation guide, fixed broken link to containerized installation requirements.
https://issues.redhat.com/projects/AAP/issues/AAP-42276?filter=myopenissues

AAP-42276: Fixed broken link to containerized installation requirements

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-42027.
Changes made:
- Added prerequisite that controller 4.5 is the minimum version supported to upgrade to AAP 2.5.
- Fixed a few typos.

AAP-42027: Added automation controller v4.5 in upgrade prerequirements

---

downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
downstream/assemblies/platform/assembly-operator-upgrade.adoc
downstream/assemblies/platform/assembly-update-ocp.adoc

[AAP-42431](https://issues.redhat.com/browse/AAP-42431) - Add consistent attribute and OCP title usage to the Operator docs
Some chapter titles use the full "Red Hat OpenShift Container Platform" title while others use "OpenShift Container Platform". We need to update this for a consistent approach throughout. 
Titles that need updating:
Chapter 3
Chapter 4
Chapter 10

Fixing titles to be uniform

---

downstream/titles/release-notes/async/aap-25-20250326.adoc

Deleted container-based online installer line.
Updated the date in the table.

Release note update async-2.5.20250326 (#3168)

---

downstream/modules/platform/proc-gs-logging-in.adoc

This PR removes a step instructing the user to opt-in to automation analytics from the first login flow. See [AAP-42638](https://issues.redhat.com/browse/AAP-42638) for more.

AAP-42638: removes info about analytics opt-in in first login process

---

downstream/modules/platform/proc-gs-logging-in.adoc

This PR ports the changes from [PR 3171](https://github.com/ansible/aap-docs/pull/3171) to the 2.5 branch. See [AAP-42638](https://issues.redhat.com/browse/AAP-42638) for more.

Backport to 2.5:AAP-42638 removes info about analytics opt-in in first login process (#3171)

---

downstream/titles/release-notes/async/aap-25-20250326.adoc

Added {GatewayStart} 2.5.20250326
Added Container-based  installer {PlatformNameShort} (online) 2.5-11 
Updated container-based installer to versoin 2.5-11.1

Updated version numbers and added content

---

downstream/titles/release-notes/async/aap-25-20250326.adoc

Added {GatewayStart} 2.5.20250326
Added Container-based  installer {PlatformNameShort} (online) 2.5-11 
Updated container-based installer to versoin 2.5-11.1

Updated version numbers and added content (#3177)

---

downstream/modules/platform/proc-aap-migrate-SAML-users.adoc

Support for migrating legacy auth users is now supported in the UI. This PR removes the steps to manually configure this setting via the API and includes information about using the Auto migrate users from UI selection instead.

41494 - removed details about migrating via the API

---

downstream/modules/platform/proc-aap-migrate-SAML-users.adoc

This PR backports the changes from #3181 to the 2.5 branch.

[Backport] - 41494 - removed details about migrating via the API (#3181)

---

downstream/modules/eda/proc-eda-copy-rulebook-activation.adoc

**Note:** This PR updates changes that were applied in the original PR #[3147](https://github.com/ansible/aap-docs/pull/3147), changing instances of "copy" to "duplicate", per request from the PDT.
[AAP-37305](https://issues.redhat.com/browse/AAP-37305) Create a sub-section in the [Rulebook Activation chapter of the Using automation decisions guide](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_decisions/index#eda-rulebook-activations) that focuses on how to create a copy of an existing rulebook activation.

AAP-37305-DUP Document how to duplicate an existing rulebook activation

---

downstream/modules/eda/proc-eda-duplicate-credential.adoc

[AAP-42948](https://issues.redhat.com/browse/AAP-42948) required updates to all EDA resources that had the capability to duplicate fields during set-up. This includes the section formerly entitled "[Copying a credential](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credentials#eda-duplicate-credential)", which will become "Duplicating a credential" after the upcoming release (May 7th) and publishing.
**Note:** The backport for this jira will be delayed and handled in a separate jira that will be created after this PR is merged.

AAP-42948 Changed all instances of copy to duplicate, per latest platform UI

---

downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc

Changed ' to a backtick for `infra.controller_configuration`
This shouldn't require a SME review, just needs a peer review.
https://issues.redhat.com/browse/AAP-43262

AAP-43262: Fixed code formatting for infra.controller_configuration in table

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc

This PR backports PR https://github.com/ansible/aap-docs/pull/3221 from main to AA 2.5 repo.

Backport PR #3221 from main to AAP 2.5

---

downstream/modules/platform/proc-controller-create-container-group.adoc

Container Group documentation is incorrect for recent versions of OpenShift
https://issues.redhat.com/browse/AAP-41641

Editing container group procedure

---

downstream/modules/platform/proc-controller-create-container-group.adoc

* Editing container group procedure
Container Group documentation is incorrect for recent versions of OpenShift
https://issues.redhat.com/browse/AAP-41641
* FIxing minor formatting error

Editing container group procedure (#3231)

---

downstream/modules/platform/proc-controller-create-container-group.adoc

Container Group documentation is incorrect for recent versions of OpenShift
https://issues.redhat.com/browse/AAP-41641

Editing container group proc in 2.4 doc

---

downstream/modules/platform/proc-operator-upgrade.adoc

[AAP-43648](https://issues.redhat.com/browse/AAP-43648)
[OCP docs] EDA 2.4 to 2.5 upgrades are not supported
EDA 2.4 is not supported for upgrade to 2.5. A user should remove the EDA deployment, then clean EDA database and upgrade. A very low number of customers experience this issue, so rather than detail the full steps a important admonition with the following needs to be added to the Upgrades section:
"Upgrading from Event-Driven Ansible 2.4 is not supported. If you’re using Event-Driven Ansible 2.4 in production, contact Red Hat before you upgrade."

AAP-43648 Adding note on EDA 2.4-2.5 support

---

downstream/modules/platform/proc-install-cli-aap-operator.adoc

[AAP-43744](https://issues.redhat.com/browse/AAP-43744) Update the wording for section 4.2
The wording in section 4.2 for the 2.5 AAP Operator docs is confusing.  I think we should refer to "Installing the AAP Operator in a namespace" as that, rather than "Subscribing a namespace to an operator".

AAP-43744 updating title for 2.4 and 2.5

---

downstream/modules/platform/proc-install-cli-aap-operator.adoc

[AAP-43744](https://issues.redhat.com/browse/AAP-43744) Update the wording for section 4.2
Also, this part does not make sense:
"You can only subscribe a single instance of the Ansible Automation Platform Operator into a single namespace. Subscribing multiple instances in the same namespace can lead to improper operation for both operator instances." 
The Openshift UI will not let you install multiple of the same operator in a given namespace.  So I think we could probably remove that line entirely.

AAP-43744 sentence to be removed

---

downstream/modules/hub/proc-push-container.adoc

This PR ports the changes from [PR 3241 ](https://github.com/ansible/aap-docs/pull/3241) to the 2.5 branch. See[ AAP-39723](https://issues.redhat.com/browse/AAP-39723) for more.

bp 2.5: AAP-3241 corrects login instructions (#3241)

---

downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
downstream/modules/platform/con-aap-legacy-user-login.adoc
downstream/modules/platform/con-aap-migrate-LDAP-users.adoc
downstream/modules/platform/proc-aap-migrate-LDAP-users.adoc
downstream/modules/platform/proc-aap-migrate-SAML-users.adoc

This PR backports the changes from #3264 to the 2.5 branch and includes the following:
* AAP-40546 - Add Migrating LDAP users content to the Upgrade guide
* AAP-40546 - minor formatting fixes
* AAP-40546 - implemented peer review suggestions

[Backport] AAP-40546 - Add Migrating LDAP users content to the Upgrade guide (#3264)

---

downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/platform/ref-eda-system-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/snippets/rpm-tested-vm-config.adoc

- Update references to IOPS to ensure it's capitalized as IOPS not IOPs.
- Also update all IOPS requirements to 3000.
Missing disk IOPS information in AAP Installation Documentation
https://issues.redhat.com/browse/AAP-43311

Update IOPS to a standardized 3000

---

downstream/modules/platform/proc-aap-platform-gateway-backup.adoc

[AAP-43381](https://issues.redhat.com/browse/AAP-43381) 
Adding a note on using a precreated PVC for AAP backups

AAP-43381 Edits - Note on precreated PVCs

---

downstream/modules/platform/con-controller-additional-settings.adoc

Clarify references to "custom.py" in "Configuring automaton execution" documentation
https://issues.redhat.com/browse/AAP-43895

Adding clarity to additional settings for controller

---

downstream/modules/platform/con-controller-additional-settings.adoc

* Updating additional settings for controller
Clarify references to "custom.py" in "Configuring automaton execution" documentation
https://issues.redhat.com/browse/AAP-43895
* Adding additional line
* Updating wording
* Adding attribute

Adding clarity to additional settings for controller (#3279)

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR backports the changes from #3276 to the 2.5 branch and includes the following:
* AAP-42888 - Add information for support of LDAPUnion for multiple user searches
* AAP-42888 - Fixed brackets based on SME feedback
* Fixed another set of brackets
* Minor grammar/style fixes
* Added peer review suggestions

[Backport] AAP-42888 - Add information for support of LDAPUnion for multiple user searches (#3276)

---

downstream/modules/builder/con-about-ee.adoc

AAP 2.5 EE uses Python 3.11 introducing non-obvious manual changes
https://issues.redhat.com/browse/AAP-40730

Update python version

---

downstream/modules/builder/con-about-ee.adoc

AAP 2.5 EE uses Python 3.11 introducing non-obvious manual changes
https://issues.redhat.com/browse/AAP-40730

Update python version (#3292)

---

downstream/modules/platform/ref-system-requirements.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-42705. Other relevant updates were already handled by @michellemacrh in her JIRA https://issues.redhat.com/browse/AAP-43311 and PR: https://github.com/ansible/aap-docs/pull/3268
Changes made: 
Updated the storage requirement to min. 60 GB and the column width.

AAP-42705: Updated the storage requirements for VMs

---

downstream/modules/platform/ref-system-requirements.adoc

This PR backports PR #3297 from main to AAP 2.5 branch.

AAP-42705: Updated the storage requirements for VMs (#3297)

---

downstream/modules/platform/ref-controller-refresh-existing-token.adoc
downstream/modules/platform/ref-controller-revoke-access-token.adoc

This PR updates the gateway api token path as described in https://issues.redhat.com/browse/AAP-42905.

AAP-42905 - Corrected gateway token API path

---

downstream/modules/hub/con-rh-certified-synclist.adoc
downstream/modules/hub/proc-create-remote.adoc

This PR ports the changes from [PR 3287](https://github.com/ansible/aap-docs/pull/3287) to the 2.5 branch. See [AAP-39751](https://issues.redhat.com/browse/AAP-39751) for more.

backport to 2.5: AAP-39751: Notes that hub does not check other repos for dependencies

---

downstream/modules/hub/con-rh-certified-synclist.adoc
downstream/modules/hub/proc-create-remote.adoc

This PR ports the changes from https://github.com/ansible/aap-docs/pull/3287 to the 2.4 branch. See [AAP-39751](https://issues.redhat.com/browse/AAP-39751) for more.

backport to 2.4: AAP-39751: Notes that hub does not check other repos for dependencies

---

downstream/assemblies/platform/assembly-appendix-operator-crs.adoc

[AAP-44196](https://issues.redhat.com/browse/AAP-44196) - Add clarity on name variable usage in CRs
Adding the following tip to help users understand the 'name' variable has multi use
"Tip: You can link in existing components by specifying the component name under the `name` variable. You can also use `name` to create a custom name for a new component."

AAP-44196 Adding Tip Admonition

---

downstream/modules/dev-guide/proc-create-role.adoc

Backports #3313 from main to 2.4
Documentation update regarding creating roles on AAP 2.4
https://issues.redhat.com/browse/AAP-22090

2.4 Update link to creating roles in Creator guide (#3313)

---

downstream/modules/platform/con-gw-authenticator-map-triggers.adoc

This PR explicitly states that group identifiers must be entered in lowercase.

AAP-44016 - Update note that group identifiers must be entered in lowercase

---

downstream/modules/platform/con-gw-authenticator-map-triggers.adoc

This PR backports the changes from #3311 to the 2.5 branch.

[Backport] AAP-44016 - Update note that group identifiers must be entered in lowercase (#3311)

---

downstream/assemblies/hub/assembly-synclists.adoc
downstream/modules/hub/con-rh-certified-synclist.adoc
downstream/modules/hub/proc-create-synclist.adoc

This PR ports the changes from [PR 3328](https://github.com/ansible/aap-docs/pull/3328) to the 2.5 branch. See [AAP-41334](https://issues.redhat.com/browse/AAP-41334) for more context.

bp to 2.5: AAP-41334: Updates content syncing instructions (#3328)

---

downstream/modules/platform/ref-controller-performance-troubleshooting.adoc

Add note regarding wait time for Job outputs to load
https://issues.redhat.com/browse/AAP-44736

Editing controller job output section

---

downstream/modules/platform/ref-adding-execution-nodes.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

Update ref-adding-execution-nodes.adoc to denote that using groups for receptor_peers is not currently possible.
Containerised Installation (Mesh) - Can't establish connections from the execution nodes to the controller nodes
https://issues.redhat.com/browse/AAP-42614

Update Adding execution nodes in Containerized installation

---

downstream/modules/platform/ref-adding-execution-nodes.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

Backports #3342 from main to 2.5
Update ref-adding-execution-nodes.adoc to denote that using groups for receptor_peers is not currently possible.
Containerised Installation (Mesh) - Can't establish connections from the execution nodes to the controller nodes
https://issues.redhat.com/browse/AAP-42614

2.5 Update Adding execution nodes in Containerized installation (#3342)

---

downstream/assemblies/platform/assembly-controller-api-search.adoc
downstream/assemblies/platform/assembly-controller-api-sorting.adoc
downstream/modules/platform/proc-controller-api-browsing-api.adoc
downstream/modules/platform/proc-controller-api-sorting.adoc
downstream/modules/platform/proc-controller-api-using-pagination.adoc

Update Automation Controller 2.5 Documentation to Correct REST API References
https://issues.redhat.com/browse/AAP-40896

Updating API references in controller API guide

---

downstream/assemblies/platform/assembly-controller-api-search.adoc
downstream/assemblies/platform/assembly-controller-api-sorting.adoc
downstream/modules/platform/proc-controller-api-browsing-api.adoc
downstream/modules/platform/proc-controller-api-sorting.adoc
downstream/modules/platform/proc-controller-api-using-pagination.adoc

Update Automation Controller 2.5 Documentation to Correct REST API References
https://issues.redhat.com/browse/AAP-40896

Updating API references in controller API guide (#3344)

---

downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Platform gateway variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40602

Update the gateway inventory file vars

---

downstream/modules/platform/con-gw-authenticator-map-triggers.adoc

This PR removes the phrase "..are case-sensitive and..." based on https://issues.redhat.com/browse/AAP-44016.

AAP-44016 - removed case-sensitive statement

---

downstream/modules/platform/con-gw-authenticator-map-triggers.adoc

This PR backports the changes from #3351 to the 2.5 branch.

[Backport] AAP-44016 - removed case-sensitive statement (#3351)

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc

[AAP-44926](https://issues.redhat.com/browse/AAP-44926) - Remove section 5.5 (upgrade EDB) from 2.5 docs

Removing section not applicable to 2.5 docs

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-redis-inventory-variables.adoc

Updates the general inventory file vars appendix and adds a redis vars file for redis specific vars.
General variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40600

Update general inventory file vars appendix

---

downstream/modules/devtools/proc-rhdh-operator-add-sidecar-container.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar-container.adoc

Backports #3358 
AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install and uninstall procedures
Affects `/titles/aap-plugin-rhdh-install`

2.5 AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install (#3358)

---

downstream/modules/devtools/proc-rhdh-operator-add-sidecar-container.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar-container.adoc

Backports #3358 
AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install and uninstall procedures
Affects `/titles/aap-plugin-rhdh-install`

2.4 AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install (#3358)

---

downstream/assemblies/platform/assembly-edge-manager-manage-apps.adoc
downstream/modules/platform/ref-edge-manager-specify-apps-inline.adoc

* Adding content from RHEM upstream to chapter 7
Add "Specifying Applications Inline" section to Chapter 7
https://issues.redhat.com/browse/AAP-44688
* Adding module to assembly

Adding content from RHEM upstream to chapter 7 (#3340)

---

downstream/assemblies/platform/assembly-edge-manager-device-fleets.adoc
downstream/modules/platform/con-edge-manager-device-selection-strat.adoc
downstream/modules/platform/con-edge-manager-device-targeting.adoc
downstream/modules/platform/con-edge-manager-limit-device.adoc
downstream/modules/platform/con-edge-manager-rollout-device-selection.adoc
downstream/modules/platform/con-edge-manager-rollout-disruption.adoc
downstream/modules/platform/proc-edge-manager-add-devices-cli.adoc
downstream/modules/platform/proc-edge-manager-add-devices-ui.adoc
downstream/modules/platform/ref-edge-manager-disruption-parameters.adoc
downstream/modules/platform/ref-edge-manager-success-threshold.adoc

* Adding `rollout policies` to RHEM doc
Add "Rollout policies" section to Chapter 8
https://issues.redhat.com/browse/AAP-44689
* Fixing title format
* Fixing grammar error
* Fixing line breaks in assembly

Adding `rollout policies` to RHEM doc (#3334)

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
downstream/modules/aap-hardening/ref-architecture.adoc
downstream/snippets/container-upgrades.adoc
downstream/titles/release-notes/async/aap-25-3-28-oct.adoc
downstream/titles/release-notes/topics/aap-25.adoc

Backports #3372 from main to 2.5 
The topology support statement in Tested deployment models is updated to clarify support for deployments outside of the published reference architectures.
Update Statement for Supported Topologies
https://issues.redhat.com/browse/AAP-44586

2.5 Update tested topology support wording (#3372)

---

README.adoc

fix repo name in README

---

downstream/assemblies/platform/assembly-controller-credentials.adoc
downstream/assemblies/platform/assembly-controller-execution-environments.adoc
downstream/assemblies/platform/assembly-controller-inventories.adoc
downstream/assemblies/platform/assembly-controller-projects.adoc
downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc

* Change copy to duplicate
[Doc] Update docs to reflect change from "Copy" to "Duplicate"
https://issues.redhat.com/browse/AAP-39300
* Change copy to duplicate
Additional infromation added to include these changes.
[Doc] Update docs to reflect change from "Copy" to "Duplicate"
https://issues.redhat.com/browse/AAP-39300
* Change copy to duplicate
Correction
[Doc] Update docs to reflect change from "Copy" to "Duplicate"
https://issues.redhat.com/browse/AAP-39300

Change copy to duplicate (#3288)

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR backports the changes from #3370 to the 2.5 branch and includes the following:
* AAP-40199 improvements to LDAP configuration content
* AAP-40199 - minor grammar and formatting fixes
* AAP-40199 - include peer review suggestions

[Backport] AAP-40199 improvements to LDAP configuration content (#3370)

---

downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc
downstream/modules/platform/ref-redis-inventory-variables.adoc

Docs - Containerized installation - Document use of compression when performing a backup
https://issues.redhat.com/browse/AAP-39129

Add compression vars to backup proc for Containerized installation

---

downstream/assemblies/eda/assembly-eda-credentials.adoc
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

This update, which changes changes the admonition from "IMPORTANT" to "NOTE", will be added to the changes for the original ticket, [AAP-40240](https://issues.redhat.com/browse/AAP-40240), covered by PR #[3272](https://github.com/ansible/aap-docs/pull/3272). This is also according to RH and IBM styles and standards.

Backport 2.5 3284 Changes admonition from IMPORTANT to NOTE, per discussion

---

downstream/modules/eda/proc-eda-duplicate-credential.adoc

[AAP-42948](https://issues.redhat.com/browse/AAP-42948) required updates to all EDA resources that had the capability to duplicate fields during set-up. This includes the section formerly entitled "[Copying a credential](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credentials#eda-duplicate-credential)", which will become "Duplicating a credential" after the upcoming release (May 7th) and publishing.

Backport-2.5-3210 (AAP-42948) Changed all instances of copy to duplicate in Credentials chapter

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc

Backports #3401 from main to 2.5 
Adds a procedure for gathering logs for Containerized AAP installation.
Affects: titles/aap-containerized-install
Containerized installation - gathering logs for troubleshooting
https://issues.redhat.com/browse/AAP-42047

2.5 Add gathering logs proc to Containerized installation (#3401)

---

downstream/modules/platform/ref-cont-aap-system-requirements.adoc

Backports #3400 from main to 2.5
Adds info about Podman limitations when using an NFS share for the user home directory
Affected guide: titles/aap-containerized-install
AAP 2.5 Containerized Deployment will not install properly if install user has shared NFS home directory - need note added to docs addressing this
https://issues.redhat.com/browse/AAP-44390

2.5 Add Rootless Podman and NFS info to Containerized installation (#3400)

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR comments out the changes for LDAP username case sensitivity because the code change release date was moved from May 7th to June 4th. The changes will be added back and published at the new release date.

AAP-43543 - Unpublish LDAP case sensitivity changes until code release

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR backports the changes from #3432 to the 2.5 branch to unpublish changes that have not been release in the code yet.

[Backport] AAP-43543 - Unpublish LDAP case sensitivity changes until code release (#3432)

---

downstream/attributes/attributes.adoc

This PR adds an attribute for the new Policy selection of the Settings menu in the 2.5 navigation.

Add a menu attribute for Settings>Policy

---

downstream/attributes/attributes.adoc

This PR backports the changes from #3435 to the 2.5 branch and includes the following:
* Add a menu attribute for Settings>Policy
* Fixed a spacing issue
* Fixed the nested attribute error

[Backport] Add a menu attribute for Settings>Policy (#3435)

---

downstream/assemblies/platform/assembly-aap-recovery.adoc

Removing recovery modules that are no longer needed as everything is through gateway now
Removing:
include::platform/proc-aap-controller-restore.adoc[leveloffset=+1]
include::platform/proc-aap-controller-yaml-restore.adoc[leveloffset=+1]
include::platform/proc-aap-hub-restore.adoc[leveloffset=+1]

AAP-45780 Remove outdated modules

---

downstream/assemblies/devtools/assembly-rhdh-ocp-required-installation.adoc
downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
downstream/modules/devtools/proc-rhdh-configure-showcase-location.adoc
downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
downstream/modules/devtools/proc-rhdh-download-plugins.adoc
downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator.adoc
downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
downstream/modules/devtools/proc-self-service-download-tar.adoc
downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc
downstream/modules/devtools/ref-rhdh-full-helm-chart-ansible-plugins.adoc

Update Ansible Plug-ins documentation to be compatible with Ansible plugins 1.5 file naming, and to add a parameter to the ConfigMap to allow the plug-ins to work.
Preview: https://ariordan-redhat.github.io/aap-builds/aap-plugin-rhdh-install-plugins-1.5-updates-2025-05-12.html
Affects `downstream/titles/aap-plugin-rhdh-install`

Ansible Plugins 1.5 - updates to plug-ins installation doc

---

downstream/modules/builder/con-additional-build-files.adoc

In con-additional-build-files.adoc the var `additional_build_steps` was referenced when it should be `additional_build_files`.
docs execution environment config has wrong value of additional_build_files
https://issues.redhat.com/browse/AAP-45864

Correct typo in Creating and consuming execution environments

---

stories/topics/con-saas-connectivity.adoc

[AAP-45863](https://issues.redhat.com/browse/AAP-45863) Product Documentation Updates for CIDR range request process for customers
location: aap-clouds-latest > Titles > saas-aws
No backport required.

AAP-45863 edits

---

downstream/modules/builder/con-additional-build-files.adoc

Backports #3463 from main to 2.5
In con-additional-build-files.adoc the var `additional_build_steps` was referenced when it should be `additional_build_files`.
docs execution environment config has wrong value of additional_build_files
https://issues.redhat.com/browse/AAP-45864

2.5 Correct typo in Creating and consuming execution environments (#3463)

---

downstream/modules/builder/con-additional-build-files.adoc

Backports #3463  from main to 2.4
In con-additional-build-files.adoc the var `additional_build_steps` was referenced when it should be `additional_build_files`.
docs execution environment config has wrong value of additional_build_files
https://issues.redhat.com/browse/AAP-45864

2.4 Correct typo in Creating and consuming execution environments (#3463)

---

downstream/titles/self-service-using/docinfo.xml
downstream/titles/self-service-using/master.adoc

Rename AAP self-service user guide from "Technical preview" to "Technology preview"

Rename AAP self-service user guide

---

downstream/modules/platform/ref-ansible-inventory-variables.adoc

Backports #3469 from main to 2.5
Auditing the inventory file vars documented in Containerized installation to ensure all vars referenced in the doc are also listed in the appendix.
All vars mentioned in Containerized installation should also be mentioned in the inventory file appendix
https://issues.redhat.com/browse/AAP-45788

2.5 Update ansible inventory vars (#3469)

---

downstream/modules/devtools/proc-self-service-telemetry-disable.adoc

Update the Disabling Telemetry for AAP self-service to use the Helm chart instead of a ConfigMap. This change means that telemetry settings will be preserved if the Helm chart is redeployed.

Update self-service telemetry disable method

---

downstream/modules/devtools/proc-self-service-telemetry-disable.adoc

Update the Disabling Telemetry for AAP self-service to use the Helm chart instead of a ConfigMap. This change means that telemetry settings will be preserved if the Helm chart is redeployed.

2.5 Update self-service telemetry disable method (#3477)

---

downstream/snippets/inventory-rpm-a-env-b.adoc

Update the RPM mixed growth topology inventory file to include the `[database]` group
Missing database group on the example inventory file on EDA documentation
https://issues.redhat.com/browse/AAP-44186

Update RPM-A-ENV-B inventory file

---

downstream/snippets/inventory-rpm-a-env-b.adoc

Update the RPM miixed growth topology inventory file to include the `[database]` group
Missing database group on the example inventory file on EDA documentation
https://issues.redhat.com/browse/AAP-44186

2.5 Update RPM-A-ENV-B inventory file (#3484)

---

downstream/modules/platform/proc-gw-team-access-resources.adoc
downstream/modules/platform/proc-gw-user-access-resources.adoc

This PR addresses the docs changes for https://issues.redhat.com/browse/AAP-28022. Direct Team and User access is not available for remote registry resources.

AAP-28022 - Added note re: access for Remote Registries

---

downstream/assemblies/platform/assembly-aap-backup-recovery.adoc
downstream/assemblies/platform/assembly-aap-backup.adoc
downstream/assemblies/platform/assembly-aap-recovery.adoc
downstream/assemblies/platform/assembly-aap-troubleshoot-backup-recovery.adoc
downstream/modules/platform/con-aap-backup-recommendations.adoc
downstream/modules/platform/con-aap-backup-recovery.adoc
downstream/modules/platform/proc-aap-controller-backup.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
downstream/modules/platform/proc-aap-hub-backup.adoc
downstream/modules/platform/proc-aap-hub-restore.adoc
downstream/modules/platform/proc-troubleshoot-same-name.adoc

[AAP-45898](https://issues.redhat.com/browse/AAP-45898)
Review OCP Backup and restore documentation using the Mod doc templates checklist.
Reviewed the OCP backup and restore documentation using the [Mod doc templates checklist](https://docs.google.com/document/d/13NAUVAby1y1qfT77QFIZrMBhi872e7IEvAC9MUpGXbQ/edit?tab=t.0).
[Backup and restore](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/backup_and_recovery_for_operator_environments/index)

Applying mod doc checklist to 2.4 version

---

downstream/assemblies/platform/assembly-controller-login.adoc
downstream/titles/controller/controller-user-guide/master.adoc

Added modular docs and UI compliance to Chapter 2 [Logging into automation controller after installation](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#controller-login) .
Includes adding a topic ID to the master.adoc file and spaces between include statements, per Emily Murphy, mod-docs SME.

AAP-45078 Check Using automation execution for UI and modular compliance.

---

downstream/assemblies/platform/assembly-controller-login.adoc
downstream/titles/controller/controller-user-guide/master.adoc

Added modular docs and UI compliance to Chapter 2 [Logging into automation controller after installation](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#controller-login) .
Includes adding a topic ID to the master.adoc file and spaces between include statements, per Emily Murphy, mod-docs SME.

Backport-2.5-3460 (AAP-45078) Check Using automation execution for modular compliance

---

downstream/assemblies/platform/assembly-aap-migration.adoc
downstream/assemblies/platform/assembly-appendix-operator-crs.adoc
downstream/assemblies/platform/assembly-controller-resource-operator.adoc
downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc
downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/assemblies/platform/assembly-operator-upgrade.adoc
downstream/assemblies/platform/assembly-update-ocp.adoc
downstream/modules/platform/proc-operator-create_crs.adoc

[AAP-45897](https://issues.redhat.com/browse/AAP-45897) Review installing on OCP documentation using the Mod doc templates checklist.
Reviewed the Installing on OCP documentation using the [Mod doc templates checklist](https://docs.google.com/document/d/13NAUVAby1y1qfT77QFIZrMBhi872e7IEvAC9MUpGXbQ/edit?tab=t.0).
[Installing on OCP](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/installing_on_openshift_container_platform/index)

Fixing spacing in assemblies and ensuring parent context is present

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc

Containerized installation - Assembly - Troubleshooting
https://issues.redhat.com/browse/AAP-45976

Add spaces between module refs in troubleshooting assembly

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc

Backports #3506 from main to 2.5

2.5 Add spaces between module refs in troubleshooting assembly (#3506)

---

stories/assembly-azure-connecting-to-aap.adoc
stories/assembly-azure-deploy.adoc
stories/assembly-azure-install-prerequisites.adoc
stories/assembly-azure-intro.adoc
stories/assembly-azure-post-deployment-requirements.adoc
titles/aap-on-azure/stories.adoc

[AAP-46214](https://issues.redhat.com/browse/AAP-46214) Update Azure documentation using the Mod doc templates checklist.
To prepare for the tool migration I need to review AoC documentation using the [Mod doc templates checklist](https://docs.google.com/document/d/13NAUVAby1y1qfT77QFIZrMBhi872e7IEvAC9MUpGXbQ/edit?tab=t.0). The following docs are in scope for Aoc:
[Red Hat Ansible Automation Platform Service on AWS](https://docs.redhat.com/en/documentation/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_service_on_aws/index)
Note: After meeting with the ToolX team they confirmed they have a script for adding the :mod-docs-content-type: and for removing `{context}` so those can be ignored in this review.

Azure mod doc checklist review

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-managed-nodes-for-containerized-installation.adoc
downstream/modules/platform/proc-restore-aap-container.adoc
downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
downstream/modules/platform/proc-update-aap-container.adoc
downstream/modules/platform/ref-configuring-inventory-file.adoc
downstream/modules/platform/ref-cont-aap-system-requirements.adoc
downstream/modules/platform/ref-containerized-system-requirements.adoc

Backports #3493 from main to 2.5
* Update system requirements for Containerized installation
- Update the system requirements prereqs in Containerized installation
- Add a new procedure for configuring user accounts on the hosts
Containerized Installation Documentation Lacks Details on User Accounts for AAP Components
https://issues.redhat.com/browse/AAP-37230
* updates to id values

Update system requirements for Containerized installation (#3493)

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/eda/ref-installing-eda-controller-on-aap.adoc
downstream/modules/hub/ref-variables-connect-hub-sso.adoc
downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
downstream/modules/platform/con-controller-additional-settings.adoc
downstream/modules/platform/proc-change-ssl-installer.adoc
downstream/modules/platform/ref-ansible-inventory-variables.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/modules/platform/ref-images-inventory-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc
downstream/modules/platform/ref-redis-inventory-variables.adoc
downstream/snippets/inventory-cont-a-env-a.adoc
downstream/snippets/inventory-cont-b-env-a.adoc
downstream/snippets/inventory-rpm-a-env-a.adoc
downstream/snippets/inventory-rpm-a-env-b.adoc
downstream/snippets/inventory-rpm-b-env-a.adoc
downstream/snippets/inventory-rpm-b-env-b.adoc

Backports #3521 from main to 2.5
Updating the assembly-appendix-inventory-file-vars.adoc and associated modules to adhere to modular docs best practices
Containerized installation - Assembly - Inventory file variables
https://issues.redhat.com/browse/AAP-45911

2.5 Update inventory file vars appendix for mod docs (#3521)

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR adds the LDAP case sensitivity information back in to be published with the 5/28 Async release.

Re-adding the LDAP case sensitivity details for publication 5/28

---

downstream/assemblies/platform/assembly-aap-activate.adoc
downstream/modules/platform/proc-aap-activate-with-credentials.adoc
downstream/modules/platform/proc-controller-configure-subscriptions.adoc

This PR backports the changes from #3545 to the 2.5 branch and includes the following:
* AAP-42977 - Add service account details to Settings and Subscriptions content
* AAP-42977 - add peer review suggestions

[Backport] AAP-42977 - Add service account details to Settings and Subscriptions content (#3545)

---

downstream/assemblies/hub/assembly-working-with-namespaces.adoc
downstream/modules/hub/proc-delete-collection.adoc

See [AAP-45411 ](https://issues.redhat.com/browse/AAP-45411)for more info.

AAP-45411: adds module on deleting collections

---

downstream/assemblies/hub/assembly-working-with-namespaces.adoc
downstream/modules/hub/proc-delete-collection.adoc

This PR ports the changes from [PR 3530](https://github.com/ansible/aap-docs/pull/3530) to the 2.5 branch. See [AAP-45411 ](https://issues.redhat.com/browse/AAP-45411)for more info.

bp to 2.5: AAP-45411: adds module on deleting collections (#3530)

---

downstream/modules/platform/ref-postgresql-requirements.adoc

Dead link for database tuning in AAP 2.4 docs
https://issues.redhat.com/browse/AAP-46466
Affects `titles/aap-planning-guide`

Updating controller link in 2.4 planning guide

---

downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-45517. 
Changes made:
- Changed "Ensure you have upgraded to automation controller 2.5 or later before upgrading your Red Hat Ansible Automation Platform." to "Ensure you have upgraded to the latest version of Ansible Automation Platform 2.4 before upgrading your Red Hat Ansible Automation Platform." in all instances.

AAP-45517: AAP-45517: Corrected the version no. in upgrade doc

---

downstream/assemblies/platform/assembly-controller-inventories.adoc
downstream/assemblies/platform/assembly-controller-inventory-templates.adoc
downstream/modules/platform/proc-controller-add-source.adoc
downstream/modules/platform/proc-controller-inv-source-vm-esxi.adoc
downstream/modules/platform/ref-controller-inventory-plugins.adoc
downstream/modules/platform/ref-controller-inventory-sources.adoc

* Add VMware-ESXi to inventory plugin types.
Docs : Update AAP core docs on inventory plugins
https://issues.redhat.com/browse/AAP-41239
* Add VMware-ESXi to inventory plugin types
Corrections from tech review
Docs : Update AAP core docs on inventory plugins
https://issues.redhat.com/browse/AAP-41239
* Add VMware-ESXi to inventory plugin types
Corrections
Docs : Update AAP core docs on inventory plugins
https://issues.redhat.com/browse/AAP-41239
* Add VMware-ESXi to inventory plugins
Correction
Docs : Update AAP core docs on inventory plugins
https://issues.redhat.com/browse/AAP-41239
* Add VMware-ESXi to inventory plugins
Correction to link/xref
Docs : Update AAP core docs on inventory plugins
https://issues.redhat.com/browse/AAP-41239
* Add VMware-ESXi to inventory plugin types …

Add VMware-ESXi to inventory plugin types. (#3588)

---

downstream/modules/eda/con-modifying-simultaneous-activations.adoc

Per [AAP-47128](https://issues.redhat.com/browse/AAP-47128), fixed broken links here:
- [Modifying the number of simultaneous rulebook activations](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-performance-tuning#modifying-simultaneous-activations), specifically the link in the note pointing [here](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/installing_on_openshift_container_platform/operator-install-operator_operator-platform-doc#modifying_the_number_of_simultaneous_rulebook_activations_during_or_after_event_driven_ansible_controller_installation).
- [Modifying the number of simultaneous rulebook activations during or after Event-Driven Ansible controller …

Backport-2.5-3614 Fixed broken links in Using automation decisions guide 

---

downstream/modules/platform/proc-cont-aap-hub-storage.adoc
downstream/modules/platform/ref-hub-variables.adoc

Backports #3635  from main to 2.5.
Add the formatting requirements for hub_shared_data_path.
Containerized installation - update hub_shared_data_path to show example format
https://issues.redhat.com/browse/AAP-43903

2.5 Update hub_shared_data_path to add req format (#3635)

---

downstream/modules/topologies/ref-ocp-b-env-a.adoc

Adds a link to the test-topologies GitHub repo for ocp-b.env-a CR files
OCP Enterprise environment missing yaml example
https://issues.redhat.com/browse/AAP-41747

Add link to ocp-b.env-a CR

---

downstream/modules/topologies/ref-ocp-b-env-a.adoc

Backports #3671 from main to 2.5
Adds a link to the test-topologies GitHub repo for ocp-b.env-a CR files
OCP Enterprise environment missing yaml example
https://issues.redhat.com/browse/AAP-41747

2.5 Add link to ocp-b.env-a CR (#3671)

---

downstream/modules/platform/proc-configure-a-config-map.adoc
downstream/modules/platform/proc-controller-metrics-utility-ocp.adoc
downstream/modules/platform/proc-controller-metrics-utility-rhel.adoc
downstream/modules/platform/proc-deploy-controller.adoc
downstream/modules/platform/proc-modifying-the-run-schedule.adoc
downstream/modules/platform/ref-fetching-a-monthly-report.adoc

2.5 backport of https://github.com/ansible/aap-docs/pull/3660
[AAP-45856](https://issues.redhat.com/browse/AAP-45856) [Doc] Update published subscription and metrics-utility content in configuring automation execution
- proc-configure-a-config-map.adoc
- proc-controller-metrics-utility-ocp.adoc
- proc-controller-metrics-utility-rhel.adoc
- proc-deploy-controller.adoc
- proc-modifying-the-run-schedule.adoc
- ref-fetching-a-monthly-report.adoc
Title:
- controller-admin-guide

AAP-45856-A Updated metrics-utility content (2) (#3660)

---

downstream/assemblies/eda/assembly-eda-rulebook-troubleshooting.adoc

Per [AAP-40717](https://issues.redhat.com/browse/AAP-40717), added content about tracking IDs for log filtering to the [Rulebook activations troubleshooting chapter, overview section](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_decisions/index#eda-rulebook-troubleshooting).

AAP-40717 EDA logging enhancements in the EDA user guide

---

downstream/assemblies/eda/assembly-eda-rulebook-troubleshooting.adoc

Per [AAP-40717](https://issues.redhat.com/browse/AAP-40717), added content about tracking IDs for log filtering to the [Rulebook activations troubleshooting chapter, overview section](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_decisions/index#eda-rulebook-troubleshooting).

Backport-2.5-3665 (AAP-40717) EDA logging enhancements in the EDA user guide

---

downstream/modules/platform/proc-controller-api-session-auth.adoc
downstream/titles/controller/controller-api-overview/master.adoc

* Updating controller API overview
Documentation feedback: 10.1. Using session authentication section shows wrong API end in AAP 2.5 official document
https://issues.redhat.com/browse/AAP-47612

Updating controller API overview (#3670)

---

downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-restore-aap-container.adoc

Backports #3711 from main to 2.5
Default backup/restore directory is "~/backups" instead of "./backups"
https://issues.redhat.com/browse/AAP-47250

2.5 Update default backup dir location (#3711)

---

downstream/modules/platform/con-edge-manager-build-bootc.adoc
downstream/modules/platform/proc-edge-manager-install-CLI.adoc

Required fix in AAP documentation for RHEM CLI installation
https://issues.redhat.com/browse/AAP-47982

Updating CLI command for Edge manager

---

downstream/modules/platform/ref-cont-aap-system-requirements.adoc

Corrects a broken link in the system requirements section of Containerized installation
https://issues.redhat.com/browse/DOCS-2807

Correct broken link in Containerized installation

---

downstream/assemblies/eda/assembly-eda-credential-types.adoc
downstream/modules/eda/con-credential-types-injector-config.adoc
downstream/modules/eda/con-credential-types-input-config.adoc
downstream/modules/eda/con-custom-credential-types.adoc
downstream/modules/eda/proc-eda-set-up-credential-types.adoc

Prepped [Chapter 3. Credential types](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credential-types) in the Using automation decisions guide for migration compliance. 
- Includes removing the **Input configuration** and **Injector configuration** discrete headings from the conceptual topic and adding the content to two new conceptual modules that align 1 level beneath the "Custom credential types" topic.

AAP-46216 Modular and migration compliance for Using automation decisions, chapter 3

---

downstream/attributes/attributes.adoc
downstream/modules/platform/ref-system-requirements.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc
downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/rpm-env-a-tested-system-config.adoc
downstream/snippets/rpm-env-b-tested-system-config.adoc

Backports #3676 from main to 2.5
* Update ansible-core version reqs for containerized AAP
Add clarity about the ansible-core version requirements in Containerized installation.
[Docs]Documentation gives mixed messages about ansible-core version for install
https://issues.redhat.com/browse/AAP-47449
* Updates based on SME feedback

2.5 Update ansible-core version reqs for containerized AAP (#3676)

---

downstream/snippets/cont-tested-system-config.adoc
downstream/titles/release-notes/async/aap-25-20250702.adoc

Backports #3746  from main to 2.5 
Update the Operating system section of system requirements for the Containerized installer for RHEL 10
Update containerized AAP 2.5 documentation for RHEL 10 support
https://issues.redhat.com/browse/AAP-47083
add release note entry

2.5 Update CONT RHEL requirements (#3746)

---

downstream/assemblies/platform/assembly-controller-pac.adoc

This PR ports the changes from [PR 3654](https://github.com/ansible/aap-docs/pull/3654) to the 2.5 branch. This work is being tracked in [AAP-45907](https://issues.redhat.com/browse/AAP-45907).

bp to 2.5: AAP-45907: removes mentions of feature flag from PaC docs (#3654)

---

downstream/modules/platform/proc-controller-set-up-azure.adoc

Documentation incorrectly states using unique IDs is mandatory for Microsoft Entra ID
https://issues.redhat.com/browse/AAP-45439

Updating Note about Microsoft Entra IDs

---

downstream/assemblies/eda/assembly-eda-credentials.adoc
downstream/modules/eda/con-credentials-list-view.adoc
downstream/modules/eda/proc-eda-delete-credential.adoc
downstream/modules/eda/proc-eda-duplicate-credential.adoc
downstream/modules/eda/proc-eda-edit-credential.adoc
downstream/modules/eda/proc-eda-set-up-credential.adoc

Backport to PR # 3722: Prepped [Chapter 2. Credentials](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credentials) in the Using automation decisions guide for migration compliance.

Backport-2.5-3722 to AAP-46213 Modularization & migration prep

---

downstream/assemblies/eda/assembly-eda-credential-types.adoc
downstream/modules/eda/con-credential-types-injector-config.adoc
downstream/modules/eda/con-credential-types-input-config.adoc
downstream/modules/eda/con-custom-credential-types.adoc
downstream/modules/eda/proc-eda-set-up-credential-types.adoc

Backport to PR # 3733: Prepped [Chapter 3. Credential types](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credential-types) in the Using automation decisions guide for migration compliance. 
- Includes removing the **Input configuration** and **Injector configuration** discrete headings from the conceptual topic and adding the content to two new conceptual modules that align 1 level beneath the "Custom credential types" topic.

Backport-2.5-3733 to AAP-46216 Modularization & migration prep

---

downstream/modules/platform/ref-controller-analytics-gathering.adoc

Remove non-existing "--until" command-line option from host_metric documentation
https://issues.redhat.com/browse/AAP-49089

Remove unnecessary parameter

---

downstream/modules/platform/ref-controller-analytics-gathering.adoc

Remove non-existing "--until" command-line option from host_metric documentation
https://issues.redhat.com/browse/AAP-49089

Remove unnecessary parameter (#3802)

---

lightspeed/modules/proc_provide-feedback.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-48959.
Changes made:
The note to use Matrix channel for providing feedback was removed, as Matrix channel was deprecated sometime along the way.

AAP-48959: Removed Matrix feedback note from Lightspeed docs

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-rpm-aap.adoc
downstream/assemblies/troubleshooting-aap/assembly-diagnosing-the-problem.adoc
downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc
downstream/modules/aap-migration/proc-ocp-target-import.adoc
downstream/modules/platform/con-certs-per-service-considerations.adoc
downstream/modules/platform/con-hs-eda-controller.adoc
downstream/modules/platform/con-hs-eda-sizing-scaling.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-configure-hub-azure-storage.adoc
downstream/modules/platform/proc-configure-hub-s3-storage.adoc
downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
downstream/modules/platform/proc-hs-eda-setup.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-managed-nodes-for-containerized-installation.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/proc-rpm-troubleshoot-generating-logs.adoc
downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
downstream/modules/platform/proc-update-aap-container.adoc
downstream/modules/platform/ref-configuring-inventory-file.adoc
downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-permissions.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-resolve-module.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-timeout.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-must-gather.adoc

Correcting issues flagged by the asciidoctor-dita-vale tool.
Affected titles:
- `titles/aap-containerized-install`
- `titles/troubleshooting-aap`
- `titles/aap-migration`
Ansible DITA readiness (2025-07-09) - Michelle
https://issues.redhat.com/browse/AAP-49393

Ansible DITA readiness

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-rpm-aap.adoc
downstream/assemblies/troubleshooting-aap/assembly-diagnosing-the-problem.adoc
downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc
downstream/modules/aap-migration/proc-ocp-target-import.adoc
downstream/modules/platform/con-certs-per-service-considerations.adoc
downstream/modules/platform/con-hs-eda-controller.adoc
downstream/modules/platform/con-hs-eda-sizing-scaling.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-configure-hub-azure-storage.adoc
downstream/modules/platform/proc-configure-hub-s3-storage.adoc
downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
downstream/modules/platform/proc-hs-eda-setup.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-managed-nodes-for-containerized-installation.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/proc-rpm-troubleshoot-generating-logs.adoc
downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
downstream/modules/platform/proc-update-aap-container.adoc
downstream/modules/platform/ref-configuring-inventory-file.adoc
downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-permissions.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-resolve-module.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-job-timeout.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-must-gather.adoc

Backports #3818 from main to 2.5
Correcting issues flagged by the asciidoctor-dita-vale tool.
Affected titles:
- `titles/aap-containerized-install`
- `titles/troubleshooting-aap`
- `titles/aap-migration`
Ansible DITA readiness (2025-07-09) - Michelle
https://issues.redhat.com/browse/AAP-49393

2.5 Ansible DITA readiness (#3818)

---

downstream/modules/platform/ref-controller-backup-restore-considerations.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-48687. 
Changes made:
Added note about disk space for /var/backups in RPM install guide. 
Pending: Checking the appropriate location for doc update in 'Configuring automation execution' guide authors.

AAP-48687: Added info. about disk space for /var/backups

---

downstream/assemblies/platform/assembly-ug-controller-setting-up-insights.adoc
downstream/modules/platform/con-controller-create-insights-inventory.adoc
downstream/modules/platform/proc-controller-create-insights-credential.adoc
downstream/modules/platform/proc-controller-remediate-insights-inventory.adoc

Using automation execution UI and modular compliance chapter 28
https://issues.redhat.com/browse/AAP-45162

DITA migration changes: CUG Ch 28

---

downstream/archive/archived-assemblies/hub/assembly-hub-create-api-token.adoc
downstream/archive/archived-assemblies/hub/assembly_ppah-installation.adoc
downstream/assemblies/hub/assembly-collection-import-export.adoc
downstream/assemblies/hub/assembly-container-user-access.adoc
downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
downstream/assemblies/hub/assembly-populate-container-registry.adoc
downstream/assemblies/hub/assembly-pull-image.adoc
downstream/assemblies/hub/assembly-remote-management.adoc
downstream/assemblies/hub/assembly-repo-management.adoc
downstream/assemblies/hub/assembly-setup-container-repository.adoc
downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
downstream/assemblies/hub/assembly-synclists.adoc

This work is being tracked in [AAP-49578](https://issues.redhat.com/browse/AAP-49578)
Changes include:
- changes xrefs to links in all assemblies in managing automation content
- Adds spaces between include statements in assemblies
- removes discrete headings from assemblies

AAP-49578: DITA conversion, xrefs to links in Managing automation content guide

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
downstream/modules/platform/proc-restore-aap-container.adoc
downstream/modules/platform/proc-update-aap-container.adoc
downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
downstream/modules/platform/ref-images-inventory-variables.adoc
downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/inventory-cont-a-env-a.adoc
downstream/snippets/inventory-cont-b-env-a.adoc

Backports #3906 from main to 2.6 
Update Containerized installation for AAP 2.6
https://issues.redhat.com/browse/AAP-48592

2.6 Update Containerized installation for AAP 2.6 (#3906)

---

downstream/modules/platform/proc-operator-config-csrf-gateway.adoc
downstream/modules/platform/ref-operator-ocp-version.adoc

Just fixing an issue where the heading in my table didn't recognise the attribute. Confirmed fix after building. 
Also removed a full stop after a link that was causing an issue.

Fixing table headers in crsf section of OCP guide

---

downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc

Backports #3918 from main to 2.6
Configuring automation execution - Update backup and restore note to ensure clarity regarding the latest version prerequisite
https://issues.redhat.com/browse/AAP-46263

2.6 Update backup/restore note (#3918)

---

downstream/modules/platform/con-gs-automation-execution.adoc

This PR ports the changes from [PR 3922](https://github.com/ansible/aap-docs/pull/3922) to the 2.5 branch. This work is being tracked in [AAP-45942](https://issues.redhat.com/browse/AAP-45942).

Bp to 2.5: AAP-45952: adds PaC info to getting started guide intro (#3922)

---

.gitignore
.vale.ini
stories/topics/con-saas-backup-and-diaster-recovery.adoc

Need to add 'af-south-1' (primary) and 'af-southeast-2' (backup) regions to the  [5.2.4. Backup and disaster recovery](https://docs.redhat.com/en/documentation/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_service_on_aws/index#con-saas-backup-and-diaster-recovery) section of the Saas guide.

AAP-50575 edits

---

downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc

* Adding callback URL field info to OIDC auth section
[DOCS] Generic OIDC Authenticator Does Not Provide a Callback URL
https://issues.redhat.com/browse/AAP-49860
* Tech review edit

Adding callback URL field info to OIDC auth section (#3883)

---

downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-restore-aap-container.adoc

Backports #3946 from main to 2.6
Containerized installation - Update backup & restore procedures to ensure clarity regarding the latest version prerequisite
https://issues.redhat.com/browse/AAP-46266

2.6 Add backup/restore note to Containerized installation (#3946)

---

downstream/assemblies/platform/assembly-planning-mesh.adoc

Include specific reference to AWS Managed coverage within automation mesh docs for operator-based envs.
https://issues.redhat.com/browse/AAP-50358

Add reference to AWS

---

downstream/assemblies/platform/assembly-planning-mesh.adoc

Include specific reference to AWS Managed coverage within automation mesh docs for operator-based envs.
https://issues.redhat.com/browse/AAP-50358

Add reference to AWS (#3957)

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-postgresql-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-50126. Update applies to RPM install guide 2.4 only, so no backport needed. 
Changes made:
- Updated references of PostgreSQL 13 to PostgreSQL 15.
- Added cross-reference to relevant KCS article.

AAP-50126: Updated PG 13 to PG 15 references

---

downstream/modules/platform/proc-controller-review-organizations.adoc

This PR ports the change from [PR 3969](https://github.com/ansible/aap-docs/pull/3969) to the 2.5 branch.

Bp to 2.5: fixes menu formatting in one module (#3969)

---

downstream/modules/platform/proc-controller-review-organizations.adoc

This PR ports the change from https://github.com/ansible/aap-docs/pull/3969 to the 2.6 branch.

bp to 2.6: fixes menu formatting in one module (#3969)

---

downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc

Backports #3986 from main to 2.6 
Adds a Container details table to Containerized installation guide
Containerized installation - update "Diagnosing the problem" with a mapping of container names and their usage
https://issues.redhat.com/browse/AAP-42439

2.6 Add container details table (#3986)

---

downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc

Backports #3986 from main to 2.5
Adds a Container details table to Containerized installation guide
Containerized installation - update "Diagnosing the problem" with a mapping of container names and their usage
https://issues.redhat.com/browse/AAP-42439

2.5 Add container details table (#3986)

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Backports #3990 from main to 2.6
RPM installer - update nginx_tls_protocols default value in documentation
https://issues.redhat.com/browse/AAP-48089

2.6 Update nginx_tls_protocols default value (#3990)

---

downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-gw-create-roles.adoc
downstream/modules/platform/proc-gw-delete-roles.adoc
downstream/modules/platform/proc-gw-edit-roles.adoc
downstream/modules/platform/proc-gw-editing-a-user.adoc
downstream/modules/platform/proc-gw-roles.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc

This work is being tracked in[ AAP-45594](https://issues.redhat.com/browse/AAP-45594)

AAP-45594: Removes references to component tabs in RBAC docs

---

downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-gw-create-roles.adoc
downstream/modules/platform/proc-gw-delete-roles.adoc
downstream/modules/platform/proc-gw-edit-roles.adoc
downstream/modules/platform/proc-gw-editing-a-user.adoc
downstream/modules/platform/proc-gw-roles.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc

This PR ports the changes from [PR 3972](https://github.com/ansible/aap-docs/pull/3972) to the 2.6 release. This work is being tracked in[ AAP-45594](https://issues.redhat.com/browse/AAP-45594).

Bp to 2.6: AAP-45594: Removes references to component tabs in RBAC docs (#3972)

---

downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc

AAP-44556 Add registry check in devtools doc
Per the Jira issue, and after consultation with the Devtools team, removed references to Docker, because the rest of the doc refers to Podman only.

2.6 AAP-44556 Add registry check in devtools doc (#4000)

---

downstream/modules/devtools/proc-devtools-extension-settings.adoc

AAP-44558 Devtools: Add info about VSCode workspaces
Explain how to make the workspace configuration accessible or available with a fresh installation of VS Code.

AAP-44558 Devtools: Add info about VSCode workspaces

---

downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/snippets/redis-colocation-containerized.adoc

Backports #4013 from main to 2.5
External Redis is currently not supported for CONT and RPM topologies.
Clarify external Redis support for CONT and RPM topologies
Affects: `titles/topologies`
https://issues.redhat.com/browse/AAP-50975

2.5 Add External Redis support statement (#4013)

---

downstream/titles/release-notes/topics/aap-25.adoc

Removed "high availability" from new feature description for EDA horizontal scaling.

Backport-2.5-4035 to AAP-51371 - Corrected statement about horizontal scaling for EDA

---

downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
downstream/modules/platform/ref-controller-cleanup-old-data.adoc
downstream/modules/platform/ref-controller-cluster-management.adoc
downstream/modules/platform/ref-controller-inventory-import.adoc

Configuring automation execution UI and modular compliance chapter 16
https://issues.redhat.com/browse/AAP-46736

DITA migration changes (2.6): CAG Ch 16

---

downstream/assemblies/platform/assembly-controller-log-files.adoc
downstream/modules/platform/ref-controller-log-files-containerized.adoc
downstream/modules/platform/ref-controller-log-files.adoc

Affects title: `titles/controller/controller-admin-guide`
[Docs] Improve documentation regarding logs in containerized AAP installation
https://issues.redhat.com/browse/AAP-48586

Add controller logs for containerized AAP

---

downstream/assemblies/platform/assembly-controller-log-files.adoc
downstream/modules/platform/ref-controller-log-files-containerized.adoc
downstream/modules/platform/ref-controller-log-files.adoc

Backports #4065 from main to 2.6
Affects title: `titles/controller/controller-admin-guide`
[Docs] Improve documentation regarding logs in containerized AAP installation
https://issues.redhat.com/browse/AAP-48586

2.6 Add controller logs for containerized AAP (#4065)

---

downstream/assemblies/platform/assembly-controller-log-files.adoc
downstream/modules/platform/ref-controller-log-files-containerized.adoc
downstream/modules/platform/ref-controller-log-files.adoc

Backports #4065 from main to 2.5
Affects title: `titles/controller/controller-admin-guide`
[Docs] Improve documentation regarding logs in containerized AAP installation
https://issues.redhat.com/browse/AAP-48586

2.5 Add controller logs for containerized AAP (#4065)

---

downstream/assemblies/platform/assembly-gs-key-functionality.adoc
downstream/modules/platform/con-aap-notifications-feed.adoc
downstream/titles/getting-started/master.adoc

This PR re-formats an rss feed address so it doesn't get flagged as a broken link and re-locates a concept module in the Getting started with AAP guide. This work is being tracked in [AAP-51442](https://issues.redhat.com/browse/AAP-51442).

AAP-51442: broken link correction and module relocation

---

downstream/assemblies/platform/assembly-gs-key-functionality.adoc
downstream/modules/platform/con-aap-notifications-feed.adoc
downstream/titles/getting-started/master.adoc

This PR ports the changes from [PR 4080](https://github.com/ansible/aap-docs/pull/4080) to the 2.5 branch. This work is being tracked in [AAP-51442](https://issues.redhat.com/browse/AAP-51442).

Bp to 2.5: AAP-51442 fixes rss feed flagged as broken link and moves one module

---

downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc

A heading in the Troubleshooting AAP guide was not rendering correctly, so that it looked like this:
For whatever reason, the fix is to add another space before this module's include statement in assembly-troubleshoot-jobs.adoc. Now it is rendering correctly.

Minor formatting update to fix a heading in Troubleshooting AAP

---

downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc

This PR ports the changes from [PR 4103](https://github.com/ansible/aap-docs/pull/4103) to the 2.6 branch.

backport to 2.6: Minor formatting update to fix a heading in the Troubleshooting AAP guide (#4103)

---

downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/ref-hub-variables.adoc

[AAP-51877](https://issues.redhat.com/browse/AAP-51877)
Document the parameter hub_data_path_exclude for the Containerized Backup
- Update the Automation Hub variables with the hub_data_path_exclude details from the table in https://gitlab.cee.redhat.com/ansible/aap-containerized-installer#automation-hub
- Add information on the backup section defining that it is possible to exclude unwanted paths (NFS-specific providers with paths in which the data is duplicated, like .snapshots, etc.)

AAP-51877 edits to Hub variables and backup sections

---

downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
downstream/modules/platform/proc-change-ssl-installer.adoc

Refactors the section Renewing and changing the SSL/TLS certificates in "Operating Ansible Automation Platform" guide to ensure clear delineation between deployment types.
Reorganize content in "Renewing and changing the SSL certificate" of the Operating AAP guide
https://issues.redhat.com/browse/AAP-52027

Refactor Chapter 6 of Operating AAP guide

---

downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
downstream/modules/platform/proc-change-ssl-installer.adoc

Backports #4113 from main to 2.6
Refactors the section Renewing and changing the SSL/TLS certificates in "Operating Ansible Automation Platform" guide to ensure clear delineation between deployment types.
Reorganize content in "Renewing and changing the SSL certificate" of the Operating AAP guide
https://issues.redhat.com/browse/AAP-52027

2.6 Refactor Chapter 6 of Operating AAP guide (#4113)

---

downstream/modules/platform/ref-database-inventory-variables.adoc

Backports #4059 from main to 2.5
Containerized and RPM Installer Docs - Document postgresql_extra_settings inventory variable
https://issues.redhat.com/browse/AAP-50483

2.5 Adds postgres_extra_settings to inventory appendix (#4059)

---

downstream/snippets/cont-tested-system-config.adoc
downstream/titles/release-notes/async/aap-25-20250702.adoc

Containerized installation - remove "for enterprise" from RHEL 10 reqs
https://issues.redhat.com/browse/AAP-52074

Update RHEL 10 reqs for containerized

---

downstream/snippets/cont-tested-system-config.adoc
downstream/titles/release-notes/async/aap-25-20250702.adoc

Backports #4137 from main to 2.6
Containerized installation - remove "for enterprise" from RHEL 10 reqs
https://issues.redhat.com/browse/AAP-52074

2.6 Update RHEL 10 reqs for containerized (#4137)

---

downstream/snippets/cont-tested-system-config.adoc
downstream/titles/release-notes/async/aap-25-20250702.adoc

Backports #4137 from main to 2.5
Containerized installation - remove "for enterprise" from RHEL 10 reqs
https://issues.redhat.com/browse/AAP-52074

2.5 Update RHEL 10 reqs for containerized (#4137)

---

stories/topics/ref-saas-egress-model.adoc

[AAP-51578](https://issues.redhat.com/browse/AAP-51578)
Missing information in the AAP installation guide for adding execution nodes that uses the mesh ingress option in AWS-Managed AAP documentations.
Adding a sentence and link that redirects to the Automation mesh guide.

Adding redirect to automation mesh guide

---

downstream/modules/platform/proc-controller-team-mapping.adoc

[Docs] Authentication mapping for teams does not work if "join_condition": "and" with attributes
https://issues.redhat.com/browse/AAP-51465

Updating team mapping section

---

downstream/modules/platform/proc-controller-team-mapping.adoc

[Docs] Authentication mapping for teams does not work if "join_condition": "and" with attributes
https://issues.redhat.com/browse/AAP-51465

Updating team mapping section (#4142)

---

downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
downstream/modules/platform/proc-change-tls-certs-installer.adoc

Backports #4155 from main to 2.5
* Adds changing certs proc for containerized aap
Affected title: titles/aap-operations-guide
Containerized AAP missing in the "Renewing and changing the SSL certificate" Section
https://issues.redhat.com/browse/AAP-47079

2.5 Adds changing certs proc for containerized aap (#4155)

---

downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc
downstream/modules/eda/con-replacing-controller-tokens.adoc
downstream/modules/eda/proc-eda-delete-controller-token.adoc
downstream/modules/eda/proc-eda-delete-rulebook-activations-with-cont-tokens.adoc

Prepped [Chapter 6. Red Hat Ansible Automation Platform credential](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-set-up-rhaap-credential-type) in the Using automation decisions guide for migration compliance.

Backport-2.5-4182 to AAP-46220 Applied pre-migration updates to content for chapter 6 (#4182)

---

downstream/modules/platform/ref-controller-credential-terraform.adoc

https://issues.redhat.com/browse/AAP-50894

Added clarification to Terraform backend configuration

---

downstream/modules/troubleshooting-aap/proc-troubleshoot-subnet-conflict.adoc

Backports #4196 from main to 2.6
[Share Feedback] troubleshooting_ansible_automation_platform/troubleshoot-networking#troubleshoot-networking
https://issues.redhat.com/browse/DOCS-2255

2.6 Update CIDR IP address (#4196)

---

downstream/modules/troubleshooting-aap/proc-troubleshoot-subnet-conflict.adoc

Backports #4196 from main to 2.5
[Share Feedback] troubleshooting_ansible_automation_platform/troubleshoot-networking#troubleshoot-networking
https://issues.redhat.com/browse/DOCS-2255

2.5 Update CIDR IP address (#4196)

---

downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc

Notice now takes into consideration lifecycle events rather than major releases.

Updated deprecation notice for installer

---

downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc

Notice now takes into consideration lifecycle events rather than major releases.

Updated deprecation notice for installer (#4215)

---

downstream/modules/platform/ref-containerized-troubleshoot-install.adoc

Backports #4222 from main to 2.6
Outdated containerized installer parameters
https://issues.redhat.com/browse/AAP-52189

2.6 Update containerized troubleshooting vars (#4222)

---

downstream/modules/platform/ref-containerized-troubleshoot-install.adoc

Backports #4222 from main to 2.5
Outdated containerized installer parameters
https://issues.redhat.com/browse/AAP-52189

2.5 Update containerized troubleshooting vars (#4222)

---

downstream/modules/platform/con-RPM-install-eda-post-steps.adoc

Fixed broken link in [Using Event-Driven Ansible 2.5 with Ansible Automation Platform 2.4](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/using_event-driven_ansible_2.5_with_ansible_automation_platform_2.4/index) that should link to [Pushing a container image to private automation hub](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/creating_and_using_execution_environments/populate-container-registry#push-containers) topic.

AAP-53064 Corrected link to Pushing an EE to PAH, per link report

---

downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
downstream/modules/platform/con-gw-troubleshoot-generic-oidc.adoc
downstream/modules/platform/proc-gw-config-jwt-algorithms.adoc
downstream/modules/platform/proc-gw-enable-debugging.adoc
downstream/modules/platform/proc-gw-troubleshoot-oidc-scope-mismatch.adoc

* Adding troubleshooting section to generic OIDC
[DOCS] Document "IGNORE_DEFAULT_SCOPE" for OIDC auth
https://issues.redhat.com/browse/AAP-52259
* Adding attributes

Adding troubleshooting section to generic OIDC (#4250)

---

downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/modules/platform/proc-content-signing-hub-on-ocp.adoc

This PR ports the changes from [PR 4253](https://github.com/ansible/aap-docs/pull/4253) to the 2.5 branch. This work is being tracked in [AAP-29944](https://issues.redhat.com/browse/AAP-29944).

2.5 backport: AAP-29944: adds content signing for hub on OCP procedure (#4253)

---

downstream/attributes/attributes.adoc
downstream/modules/platform/ref-upgrade-scenarios-container.adoc
downstream/modules/platform/ref-upgrade-scenarios-openshift.adoc
downstream/modules/platform/ref-upgrade-scenarios-rpm.adoc

Backports #4315 from main to 2.6
* Update Support matrix for upgrade scenarios
Affected title: `planning-your-upgrade`
Update the Support matrix for upgrade scenarios "Process" column to include inline links to the relevant documentation
https://issues.redhat.com/browse/AAP-53516

2.6 Update Support matrix for upgrade scenarios (#4315)

---

downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc

[AAP-49903](https://issues.redhat.com/browse/AAP-49903)
Documentation for S3 compatible buckets does not fully document available options
Just updating wording to be more accurate with what is documented in hub docs.

Removing incorrect verbiage as per AAP-49903

---

downstream/modules/platform/proc-operator-deploy-redis.adoc

[AAP-51597](https://issues.redhat.com/browse/AAP-51597)
Section explaining the switch from clustered Redis mode to standalone Redis mode in an operator-based installation

AAP-51597 edits

---

downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
downstream/assemblies/platform/assembly-controller-api-search.adoc
downstream/assemblies/platform/assembly-controller-api-sorting.adoc
downstream/modules/platform/con-controller-api-oauth2-token.adoc
downstream/modules/platform/proc-controller-api-browsing-api.adoc
downstream/modules/platform/proc-controller-api-enable-users-oauth.adoc
downstream/modules/platform/proc-controller-api-filtering.adoc
downstream/modules/platform/proc-controller-api-search.adoc
downstream/modules/platform/proc-controller-api-sorting.adoc
downstream/modules/platform/proc-controller-api-using-pagination.adoc
downstream/modules/platform/ref-controller-api-config-settings.adoc
downstream/modules/platform/ref-controller-api-field-lookups.adoc

Docs - 2.5 API Examples Outdated
https://issues.redhat.com/browse/AAP-45587

Updating controller API examples

---

downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
downstream/modules/platform/con-gw-pat-migration.adoc
downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
downstream/modules/platform/proc-controller-github-organization-settings.adoc
downstream/modules/platform/proc-controller-github-settings.adoc
downstream/modules/platform/proc-controller-github-team-settings.adoc
downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
downstream/modules/platform/proc-controller-set-up-LDAP.adoc
downstream/modules/platform/proc-controller-set-up-SAML.adoc
downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
downstream/modules/platform/proc-controller-set-up-radius.adoc
downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
downstream/modules/platform/proc-gw-local-authentication.adoc

[DOCS] 2.6 - Remove legacy auth step from auth type procedures
https://issues.redhat.com/browse/AAP-53902

Removing legacy auth step from Access Management

---

downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
downstream/modules/vault-aap/con-vault-intro.adoc
downstream/modules/vault-aap/proc-vault-configuring-kv2-secret-get-lookup.adoc
downstream/modules/vault-aap/proc-vault-configuring-kv2-secret.adoc
downstream/modules/vault-aap/proc-vault-creating-credential-type.adoc

https://issues.redhat.com/browse/AAP-54033
After talking with Aine about how to fix them. The links won't work if you try to publish from main, but this is what's been done:
- For Vault: I needed to add vault-product# in front of the topic ID, so the format is:
`link:{URLHashiGuide}/vault-product#<topidId>[<topicName>]`
- For Terraform: Replaced hardcoded 2.5 in the link to `{PlatformVers}
Please let me know if you have questions. I'll be able to test the links after I backport these changes to 2.5 and 2.6 branches.

AAP-54033: Fix broken links

---

downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
downstream/modules/vault-aap/con-vault-intro.adoc
downstream/modules/vault-aap/proc-vault-configuring-kv2-secret-get-lookup.adoc
downstream/modules/vault-aap/proc-vault-configuring-kv2-secret.adoc
downstream/modules/vault-aap/proc-vault-creating-credential-type.adoc

* Fix Vault links
* Replaced 2.5 with version attribute
Backport for #4352

Backport for 2.5 AAP-54033: Fix broken links (#4352)

---

downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-controller-creating-a-team.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc
downstream/modules/platform/proc-gw-add-admin-organization.adoc
downstream/modules/platform/proc-gw-add-admin-team.adoc
downstream/modules/platform/proc-gw-add-team-organization.adoc
downstream/modules/platform/proc-gw-delete-team.adoc
downstream/modules/platform/proc-gw-editing-a-user.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc
downstream/modules/platform/proc-gw-users-list-view.adoc

This PR ports the changes from [PR 4354](https://github.com/ansible/aap-docs/pull/4354) to the 2.6 branch. This work is being tracked in [AAP-52315](https://issues.redhat.com/browse/AAP-52315).

2.6 backport: AAP-52315: updates links in RBAC content (#4354)

---

downstream/modules/platform/con-aap-upgrade-overview.adoc

https://issues.redhat.com/browse/AAP-53954
This is an additional PR for this issue. The last row had a placeholder in the last row in the Gdoc. That has now been updated and I've populated the placeholder.
Related to #4345

Update for AAP-53954: Added description and links to last row

---

downstream/modules/platform/ref-gateway-variables.adoc

Backports #4109 from main to 2.5
Adds automationgateway_uwsgi_processes (RPM) and gateway_uwsgi_processes (Cont) to inventory vars appendix
Affects: Containerized installation and RPM installation
Document automationgateway_uwsgi_processes parameter in rpm installer
https://issues.redhat.com/browse/AAP-52025

2.5 Adds gateway_uwsgi_processes to inventory appendix (#4109)

---

downstream/assemblies/eda/assembly-eda-rulebook-troubleshooting.adoc
downstream/modules/eda/proc-eda-activation-keeps-restarting.adoc
downstream/modules/eda/proc-eda-activation-stuck-pending.adoc
downstream/modules/eda/proc-eda-cannot-connect-to-controller.adoc
downstream/modules/eda/proc-eda-event-streams-not-sending-events.adoc

Prepped [Chapter 8. Rulebook activations troubleshooting](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-rulebook-troubleshooting) in the Using automation decisions guide for migration compliance.

Backport-2.5-4413 to AAP-46222 Pre-migration prep for Chapter 8, Using automation decisions

---

downstream/assemblies/eda/assembly-eda-rule-audit.adoc
downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc
downstream/modules/eda/proc-eda-view-rule-audit-details.adoc
downstream/modules/eda/proc-eda-view-rule-audit-events.adoc

Prepped [Chapter 9. Rule Audit](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-rule-audit) in the Using automation decisions guide for migration compliance.

Backport-2.5-4415 for AAP-46223 Pre-migration work EDA user guide, Chapter 9

---

downstream/assemblies/eda/assembly-eda-rule-audit.adoc
downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc
downstream/modules/eda/proc-eda-view-rule-audit-details.adoc
downstream/modules/eda/proc-eda-view-rule-audit-events.adoc

Prepped [Chapter 9. Rule Audit](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-rule-audit) in the Using automation decisions guide for migration compliance.

Backport-2.6-4415 for AAP-46223 Pre-migration work EDA user guide, Chapter 9

---

downstream/assemblies/security/assembly-aap-security-use-cases.adoc

This PR ports the changes from [PR 4452](https://github.com/ansible/aap-docs/pull/4452) to the 2.6 branch.

2.6 backport: fixes typo (#4452)

---

downstream/assemblies/platform/assembly-gateway-licensing.adoc
downstream/assemblies/platform/assembly-platform-install-overview.adoc
downstream/modules/platform/proc-remove-EDA-2.4-db.adoc
downstream/modules/platform/ref-upgrade-api-specific-changes.adoc

This PR is a follow-up doc update as part of JIRA https://issues.redhat.com/browse/AAP-54229.
Changes made:
- Latest comments from @lynne maynard on PR https://github.com/ansible/aap-docs/pull/4313. 
- Some minor doc placement + formatting + URL updates that I felt needed to be made when performing a self review of the RPM upgrade docs.

AAP-54229-update: Self review of RPM upgrade guide 2.6

---

downstream/modules/platform/proc-controller-scm-ssh-proxy-config.adoc

Backports #4469 from main to 2.5
proc-controller-scn-ssh-proxy-config.adoc didn't have a correct terminated code-block which caused all content below it not to show in the published docs
Also corrects some formatting issues to assist with AsciiDoc/DITA conversion.
[Docs] Missing "Renewing and Changing the SSL Certificate" section
https://issues.redhat.com/browse/AAP-54522

2.5 Corrects build issue preventing content from showing (#4469)

---

downstream/attributes/attributes.adoc

2.6 correct links in Planning your upgrade guide
https://issues.redhat.com/browse/AAP-54892

Updates the RPM upgrade guide attributes

---

downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-playbooks.adoc
downstream/modules/platform/proc-aap-generate-manifest-file.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-aap-packages.adoc

2.6 correct links in Planning your upgrade guide
https://issues.redhat.com/browse/AAP-54892

Updates broken links in various 2.6 guides

---

downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-playbooks.adoc
downstream/modules/platform/proc-aap-generate-manifest-file.adoc
downstream/modules/troubleshooting-aap/proc-troubleshoot-aap-packages.adoc

Backports #4503 from main to 2.5
2.6 correct links in Planning your upgrade guide
https://issues.redhat.com/browse/AAP-54892

2.5 Updates broken links in various 2.6 guides (#4503)

---

downstream/modules/platform/con-gw-overview-access-auth.adoc
downstream/modules/platform/proc-aap-enable-disable-auth.adoc

[Docs] Fix 2.5 Access management broken build
https://issues.redhat.com/browse/AAP-54922

Fixing build issue for acccess management 2.5

---

downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc

Corrected the link to [Actions](https://ansible.readthedocs.io/projects/rulebook/en/latest/actions.html) in the ansible.readthedocs.io, which changed after publishing in previous version.

Backport-2.5-4510 to AAP-53847 Corrected link to current location of Actions content

---

downstream/modules/platform/proc-attaching-subscriptions.adoc

Updates troubleshooting section to describe how to list the repositories before enabling the correct one. Also clarifies this is for legacy accounts not using SCA.
arm directions are not called out for containzied install
https://issues.redhat.com/browse/AAP-53407

Update Attaching your subscription troubleshooting

---

downstream/modules/platform/proc-attaching-subscriptions.adoc

Backports #4460 from main to 2.5
* Update Attaching your subscription troubleshooting
Updates troubleshooting section to describe how to list the repositories before enabling the correct one. Also clarifies this is for legacy accounts not using SCA.
arm directions are not called out for containzied install
https://issues.redhat.com/browse/AAP-53407
* updates based on SME feedback

2.5 Update Attaching your subscription troubleshooting (#4460)

---

downstream/assemblies/eda/assembly-eda-event-filter-plugins.adoc
downstream/modules/eda/con-eda-author-event-filters.adoc

Prepped [Chapter 12. Event filter plugins](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/using_automation_decisions/eda-event-filter-plugins) in the Using automation decisions guide for migration compliance.

Backport-2.5-4526 to AAP-46228 Pre-migration work EDA user guide, Chapter 12

---

downstream/assemblies/eda/assembly-eda-logging-strategy.adoc
downstream/modules/eda/ref-eda-logging-samples.adoc

Prepped [Chapter 13. Event-Driven Ansible logging strategy](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/using_automation_decisions/eda-logging-strategy) in the Using automation decisions guide for migration compliance.

Backport-2.5-4547 to AAP-46230 Pre-migration work EDA user guide, Chapter 13

---

downstream/assemblies/eda/assembly-eda-logging-strategy.adoc
downstream/modules/eda/ref-eda-logging-samples.adoc

Prepped [Chapter 13. Event-Driven Ansible logging strategy](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/using_automation_decisions/eda-logging-strategy) in the Using automation decisions guide for migration compliance.

Backport-2.6-4547 to AAP-46230 Pre-migration work EDA user guide, Chapter 13

---

downstream/modules/hub/proc-uploading-collections.adoc

This PR ports the changes from [PR 4558](https://github.com/ansible/aap-docs/pull/4558) to the 2.5 branch. This work is being tracked in [AAP-54971](https://issues.redhat.com/browse/AAP-54971).

2.5 backport: AAP-54971: Adds note about collection size limit for uploading to hub docs

---

downstream/assemblies/platform/assembly-gateway-licensing.adoc
downstream/modules/platform/ref-controller-node-counting.adoc
downstream/modules/platform/ref-controller-trial-evaluation.adoc

This PR ports the changes from [PR 4569](https://github.com/ansible/aap-docs/pull/4569) to the 2.6 branch. This work is being tracked in [AAP-55095](https://issues.redhat.com/browse/AAP-55095)

2.6 backport: AAP-55095: updates language around subscriptions, removes references to licenses

---

downstream/assemblies/platform/assembly-gw-managing-authentication.adoc
downstream/modules/platform/con-gw-gcp-network-port-limits.adoc
downstream/modules/platform/proc-gw-gcp-increase-port-limits.adoc

* Updating managing auth chapter
Update documentation about openshift minimal ports per VM when running in gcp
https://issues.redhat.com/browse/AAP-53684
---------

Updating managing auth chapter (#4624)

---

downstream/titles/release-notes/topics/aap-26-known-issues.adoc

2.6 Release notes: add issues for self-service
Also added to 2.5, but not as a backport.

2.6 Release notes: add issues for self-service
