downstream/modules/platform/ref-general-inventory-variables.adoc

Add redis_cluster_ip information to inventory file vars appendix
https://issues.redhat.com/browse/AAP-36803

Add redis_cluster_ip to inventory vars appendix

---

downstream/modules/platform/ref-general-inventory-variables.adoc

Add redis_cluster_ip information to inventory file vars appendix
https://issues.redhat.com/browse/AAP-36803

2.5 Add redis_cluster_ip to inventory vars appendix (#2786)

---

downstream/modules/platform/proc-pulling-the-secret.adoc

Correcting order of commands
errors in procedure to pull the secret for OCP based deployments
https://issues.redhat.com/browse/AAP-38348

Correcting pull the secret section

---

downstream/modules/platform/proc-pulling-the-secret.adoc

* Correcting pull the secret section
Correcting order of commands
errors in procedure to pull the secret for OCP based deployments
https://issues.redhat.com/browse/AAP-38348
* Correcting the pull secret section
Changes to file structure
errors in procedure to pull the secret for OCP based deployments
https://issues.redhat.com/browse/AAP-38348

Correcting pull the secret section (#2775)

---

downstream/modules/platform/ref-postgresql-requirements.adoc

This PR addresses JIRA https://github.com/sayjadha/aap-docs/pull/new/AAP-38369. 
Changes made:
- Updated a crossreference to point to downstream docs

AAP-38369: Updated a crossreference to point to downstream docs

---

downstream/modules/platform/ref-general-inventory-variables.adoc

Add Setting registry_username and registry_password content to Containerized installation
https://issues.redhat.com/browse/AAP-37656

correcting broken URL

---

downstream/modules/platform/ref-general-inventory-variables.adoc

Add Setting registry_username and registry_password content to Containerized installation
https://issues.redhat.com/browse/AAP-37656

2.5 correcting broken URL (#2799)

---

downstream/titles/release-notes/async/aap-25-20250122.adoc
downstream/titles/release-notes/master.adoc

Release Notes for 01-22-2025 release.

---

downstream/titles/release-notes/async/aap-25-20250122.adoc
downstream/titles/release-notes/master.adoc

Release Notes for 01-22-2025 release. (#2803)

---

downstream/titles/release-notes/async/aap-25-20250122.adoc

* Updated heading, and added a note for Openshift.
Resolves:AAP-38172

2.5 Relnote 2.5.20250122 (#2805)

---

downstream/modules/platform/ref-hub-variables.adoc

* Replaced missing variable
Replaced automationhub_main_url
Replace entry for automationhub_main_url
https://issues.redhat.com/browse/AAP-39218
* Replaced missing variable
Corrections
Replace entry for automationhub_main_url
https://issues.redhat.com/browse/AAP-39218

Replaced missing variable (#2809)

---

downstream/titles/release-notes/async/aap-25-20250129.adoc
downstream/titles/release-notes/master.adoc

Release notes for the 2.5-20250129 patch release.

---

downstream/titles/release-notes/async/aap-25-20250129.adoc
downstream/titles/release-notes/master.adoc

Release notes for the 2.5-20250129 patch release. (#2813)

---

lightspeed/modules/proc_troubleshooting-vscode.adoc

JIRA : https://issues.redhat.com/browse/AAP-39144
Changes made:
Added troubleshooting details for proxy configuration.

AAP-39144: Added troubleshooting info. For proxy-releted vscode errors

---

downstream/titles/release-notes/async/aap-25-20250129.adoc

Final changes to the 2.5-20250129 release notes. (#2816)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/async-24-20250129.adoc

Release notes for the 2.4-20250129 release.

---

downstream/titles/release-notes/async/aap-25-12-18-dec.adoc

Fixed a misspelled attribute in the release notes for 12/18/2024.

---

downstream/images/svg/extensions.svg

AAP-39409 Add directory for SVG files

2.4 AAP-39409 Add directory for SVG files (#2827)

---

downstream/images/svg/extensions.svg

AAP-39409 Add directory for SVG files

2.5 AAP-39409 Add directory for SVG files (#2827)

---

lightspeed/images/extensions.svg

AAP-39409 Add directory for SVG files

Lightspeed: AAP-39409 Add directory for SVG files

---

downstream/modules/platform/ref-system-requirements.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-37837.
Changes made:
- Added repo. selection prerequisite for RPM installation

AAP-37837: Added repo. selection prerequisite for RPM installation

---

downstream/modules/platform/ref-system-requirements.adoc

Backport PR #2847  from main to AAP v2.5

Backport pull request #2847 from main to 2.5 

---

downstream/modules/platform/ref-controller-organization-mapping.adoc

AAP 2.4 missing remove_auditors documentation
https://issues.redhat.com/browse/AAP-38836
Affects `controller-user-guide`

Adding remove_auditors to 2.4 controller user guide

---

stories/topics/proc-azure-provisioning-aap.adoc

[AAP-39490](https://issues.redhat.com/browse/AAP-39490) requests adding some information on the tags tab as part of the 2.5 release but the same information is relevant for the current version also.

Adding missing tab info to 2.x version

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

Added [rulebook troubleshooting](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-rulebook-troubleshooting) cross-reference to overview chapter.
JIRA: https://issues.redhat.com/browse/AAP-39557

AAP-39557 Added assembly to overview

---

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc

Added [rulebook troubleshooting](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-rulebook-troubleshooting) cross-reference to overview chapter.
JIRA: https://issues.redhat.com/browse/AAP-39557

Backport-2.5-2859: AAP-39557 Added assembly to overview (#2859)

---

downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
downstream/titles/release-notes/async/aap-25-5-3-dec.adoc

* Update release notes for 11/20/24 and 12/04/24 with the corresponding JIRA ticket number.
Resolves:AAP-37433
* Update aap-25-4-18-nov.adoc
* Update aap-25-5-3-dec.adoc

Update release notes for 11/20/24 and 12/04/24 with the (#2861)

---

attributes/attributes.adoc

Updating the platformVers attribute

updtaing platformvers attribute

---

downstream/modules/platform/proc-post-migration-cleanup.adoc

[AAP-38722](https://issues.redhat.com/browse/AAP-38722) - [Draft](https://docs.google.com/document/d/1Ds5E_ILJD_o78cihXk7P5DYIyLnc1xbvG9PSRZJ0WrI/edit?tab=t.0)
Adding some more instructions around post migration clean up.

Adding edits from AAP-38722

---

downstream/modules/platform/proc-post-migration-cleanup.adoc

[AAP-38722](https://issues.redhat.com/browse/AAP-38722) - [Draft](https://docs.google.com/document/d/1Ds5E_ILJD_o78cihXk7P5DYIyLnc1xbvG9PSRZJ0WrI/edit?tab=t.0)
Adding some more instructions around post migration clean up.

Adding edits from AAP-38722 (#2864)

---

downstream/assemblies/flight-control/flight-control
downstream/assemblies/platform/assembly-flight-control-troubleshooting.adoc
downstream/attributes/attributes.adoc
downstream/modules/platform/proc-flight-control-generate-device-log.adoc
downstream/modules/platform/proc-flight-control-view-device-config.adoc
downstream/titles/flight-control/flight-control-user-guide/docinfo.xml
downstream/titles/flight-control/flight-control-user-guide/flight-control
downstream/titles/flight-control/flight-control-user-guide/master.adoc
downstream/titles/flight-control/flight-control-user-guide/platform

* Creating Flight Control troubleshooting section
[Docs] Flight Control - Troubleshooting
https://issues.redhat.com/browse/AAP-39628
Affects `titles/flight-control-user-guide`

Creating Flight Control troubleshooting section (#2853)

---

downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
downstream/modules/platform/proc-verify-network-connectivity.adoc

[AAP-39765](https://issues.redhat.com/browse/AAP-39765)
Awx references in the Installing on OCP guide and Backup and restore guide that need to be updated to AutomationController
Edits made but want confirmation before publishing [See Slack](https://redhat-internal.slack.com/archives/C019LBHATBP/p1738334503825599)

Updating awx to AutomationController

---

downstream/modules/platform/ref-operator-crs.adoc

[AAP-39552](https://issues.redhat.com/browse/AAP-39552)
AAP install fails when lightspeed disabled false is in yaml - removing from code block

Removing Lightspeed from code block

---

downstream/modules/platform/proc-controller-set-up-logging.adoc

Correct formatting of controller logging.
https://issues.redhat.com/browse/AAP-39959

Correct formatting of logging section

---

downstream/modules/platform/proc-controller-set-up-logging.adoc

Correct formatting of controller logging.
https://issues.redhat.com/browse/AAP-39959

Correct formatting of logging section (#2887)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
downstream/modules/platform/ref-ansible-inventory-variables.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

* Update containerized installation ext db configuration
- Separate the procedure out into its own file specific to containerized installation
- Update the inventory vars with the vars needed for ext db configuration
- Update ordering of inventory vars appendix so it's alphabetical
Docs - Ensure external database setup steps are documented per the current functionality
https://issues.redhat.com/browse/AAP-39006

2.5 Update containerized installation ext db configuration (#2893)

---

downstream/modules/hub/proc-adding-an-execution-environment.adoc
downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
downstream/modules/hub/proc-using-podman-ensure-image-signed.adoc

See [AAP-37377](https://issues.redhat.com/browse/AAP-37377) for more.

AAP-37377: Updates attribute in Managing automation content

---

downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/con-aap-migrate-normal-users.adoc
downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/con-aap-upgrades.adoc
downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
downstream/modules/platform/proc-aap-migrate-admin-users.adoc
downstream/modules/platform/proc-account-linking.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc
downstream/titles/upgrade/master.adoc

This PR backports the #2898 urgent changes from the main branch to the 2.5 branch.

[Backport] AAP-40016 - Adding post upgrade details to address escalated customer pain points (#2898)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-restore-aap-container.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

* Add restore procedure to Containerized installation
Containerized installation - Add public documentation for restore from backup
https://issues.redhat.com/browse/AAP-34722

2.5 Add restore procedure to Containerized installation (#2902)

---

downstream/modules/platform/ref-operator-crs.adoc

Set eda.disabled to true
BUG - Logic error within the custom resource definition for gateway that would deploy EDA instead of just connecting to Controller and Hub
https://issues.redhat.com/browse/AAP-40045

Correct custom resource definition

---

downstream/assemblies/platform/assembly-install-aap-operator.adoc
downstream/modules/platform/proc-install-aap-operator.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc

[AAP-38821](https://issues.redhat.com/browse/AAP-38821)
- Edits made to the start chapter 2 of the Installing on OCP guide & Important note removed
- Note added to the Op growth topology section

[AAP-38821] Namespace-Scoped Deployments in OCP and Topology 

---

downstream/assemblies/platform/assembly-install-aap-operator.adoc
downstream/modules/platform/proc-install-aap-operator.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc

[AAP-38821] Namespace-Scoped Deployments in OCP and Topology  (#2910)

---

downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
downstream/modules/platform/con-aap-migrate-normal-users.adoc
downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
downstream/modules/platform/proc-aap-migrate-admin-users.adoc

This PR adds the peer review suggestions and additional feedback to the Post upgrade steps content for https://issues.redhat.com/browse/AAP-40122.

AAP-40122 - Adding feedback and peer review changes to Post upgrade content

---

downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
downstream/modules/platform/con-aap-migrate-normal-users.adoc
downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
downstream/modules/platform/proc-aap-migrate-admin-users.adoc

This PR backports the changes from #2916 to the 2.5 branch and includes the following:
* Adding feedback and peer review changes to Post upgrade content
* Removed note

[Backport] AAP-40122 - Adding feedback and peer review changes to Post upgrade content (#2916)

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

[AAP-40078](https://issues.redhat.com/browse/AAP-40078) 
- assembly-network-ports-protocols.adoc

AAP-40078 updated important note

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

2.5 backport of [PR 2921](https://github.com/ansible/aap-docs/pull/2921)
[AAP-40078](https://issues.redhat.com/browse/AAP-40078)
assembly-network-ports-protocols.adoc

AAP-40078 updated important note (#2921)

---

downstream/modules/platform/proc-gw-editing-a-user.adoc

This PR adds the service level administrator checkboxes and a description for Editing migrated admin users.

AAP-39927 Added descriptions for the service level administrator checkboxes

---

downstream/titles/release-notes/async/aap-25-20250213.adoc
downstream/titles/release-notes/master.adoc

* Async release notes for the 2.5-20250213 release.
Resolves:AAP-39670
See also:AAP-39656
* Update aap-25-20250213.adoc
* Update aap-25-20250213.adoc
* Update aap-25-20250213.adoc
* Update aap-25-20250213.adoc
* Update aap-25-20250213.adoc
* Update aap-25-20250213.adoc
* Update aap-25-20250213.adoc

Async release notes for the 2.5-20250213 release. (#2927)

---

downstream/modules/builder/con-about-ee.adoc

See [AAP-40325](https://issues.redhat.com/browse/AAP-40325) for more.

AAP-40325: updates ansible core version in EE guide

---

downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
downstream/assemblies/platform/assembly-edge-manager-troubleshooting.adoc
downstream/modules/platform/con-edge-manager-access-devices.adoc
downstream/modules/platform/proc-edge-manager-access-devices-cli.adoc
downstream/modules/platform/proc-edge-manager-access-devices-web-ui.adoc
downstream/modules/platform/proc-edge-manager-create-apps.adoc
downstream/modules/platform/proc-edge-manager-generate-device-log.adoc
downstream/modules/platform/proc-edge-manager-manage-apps-cli.adoc
downstream/modules/platform/proc-edge-manager-manage-apps-ui.adoc
downstream/modules/platform/proc-edge-manager-manage-apps.adoc
downstream/modules/platform/proc-edge-manager-monitor-device-resources-cli.adoc
downstream/modules/platform/proc-edge-manager-monitor-device-resources-web-ui.adoc
downstream/modules/platform/proc-edge-manager-view-device-config.adoc
downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
downstream/modules/platform/ref-edge-manager-monitor-device.adoc
downstream/titles/flight-control/flight-control-user-guide/master.adoc

* Adding Managing devices section to repo
[Docs] Flight Control - Document Managing devices
https://issues.redhat.com/browse/AAP-39626
Affects `titles/flight-control-user-guide`
* Adding modules to Manage devices chapter
* Further edits to manage devices section

Adding Managing devices section to repo (#2873)

---

downstream/titles/release-notes/async/aap-25-20250213.adoc

ansible.eda collection has been updated to 2.4.0.(AAP-39577)

Revised the async release notes with eda collection update

---

downstream/titles/release-notes/async/aap-25-20250213.adoc

ansible.eda collection has been updated to 2.4.0.(AAP-39577)

Revised the async release notes with eda collection update (#2937)

---

downstream/modules/platform/proc-aap-migrate-SAML-users.adoc

This PR incorporates the suggested changes made by the SME.

AAP-39910 - Added SME draft review feedback

---

downstream/modules/platform/proc-aap-migrate-SAML-users.adoc

This PR backports the changes from #2941 to the 2.5 branch and includes the following: 
* AAP-39910 - Added SME draft review feedback
* Fixed bold formatting placement
* Added peer review changes

[Backport] AAP-39910 - Added SME draft review feedback (#2941)

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc

See [AAP-40425](https://issues.redhat.com/browse/AAP-40425) for more.

AAP-40425: updates admonition about container image pulls in Managing automation content

---

downstream/modules/platform/proc-gw-config-keycloak-settings.adoc

This PR backports the changes from #2953 to the 2.5 branch.

[Backport] AAP-37455 - added information for re-enabling the audience in keycloak (#2953)

---

downstream/assemblies/platform/assembly-edge-manager-config.adoc
downstream/modules/platform/ref-edge-manager-additional-fields.adoc
downstream/modules/platform/ref-edge-manager-field-selectors.adoc
downstream/modules/platform/ref-edge-manager-fields-discovery.adoc
downstream/modules/platform/ref-edge-manager-supported-operators.adoc
downstream/titles/flight-control/flight-control-user-guide/master.adoc

[Docs] Document configuration of Flight Control service
https://issues.redhat.com/browse/AAP-39622
Affects `titles/flight-control-user-guide`

Adding Edge manager config section to repo

---

downstream/assemblies/platform/assembly-edge-manager-config.adoc
downstream/modules/platform/ref-edge-manager-additional-fields.adoc
downstream/modules/platform/ref-edge-manager-field-selectors.adoc
downstream/modules/platform/ref-edge-manager-fields-discovery.adoc
downstream/modules/platform/ref-edge-manager-supported-operators.adoc
downstream/titles/flight-control/flight-control-user-guide/master.adoc

* Adding Edge manager config section to repo
[Docs] Document configuration of Flight Control service
https://issues.redhat.com/browse/AAP-39622
Affects `titles/flight-control-user-guide`
* Updates to field selectors section

Adding Edge manager config section to repo (#2939)

---

downstream/modules/platform/proc-create-secret-key-secret.adoc

[AAP-38504](https://issues.redhat.com/browse/AAP-38504) 
Updating the Creating a secret key secret section to specific secret keys are needed for all components

Edits to creating a secret key section

---

ansible-inside/images/svg/vscode-extensions-icon.svg

AAP-39409 Add directory for SVG files

AAP-39409 Ansible Inside Add directory for SVG files

---

downstream/assemblies/platform/assembly-aap-platform-components.adoc

2.5 backport of  https://github.com/ansible/aap-docs/pull/2973
[AAP-34926](https://issues.redhat.com/browse/AAP-34926)

AAP-34926A fixed typo (#2973)

---

downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
downstream/modules/platform/con-aap-migrate-normal-users.adoc
downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
downstream/modules/platform/proc-account-linking.adoc

This PR provides additional resources to ease customer frustration with migration to 2.5.

AAP-40475 - added link to demo video

---

downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
downstream/modules/platform/con-aap-migrate-normal-users.adoc
downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
downstream/modules/platform/proc-account-linking.adoc

This PR backports the changes from #2967 to the 2.5 branch and includes the following:
* AAP-40475 - added link to demo video
* AAP-40475 - Added link to demonstration video and clarified the language for migration
* AAP-40475 - fixed attribute usage
* AAP-40475 - fixed spacing and highlighted the term migration
* AAP-40475 - added peer review changes

[Backport] AAP-40475 - added link to demo video (#2967)

---

downstream/modules/platform/proc-controller-user-permissions.adoc
downstream/modules/platform/ref-controller-user-roles.adoc

This PR backports the changes from #2977 to the 2.5 branch.

[Backport] AAP-40151 - added note about adding users and teams to organizations (#2977)

---

lightspeed/modules/proc_create-connection-secrets.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-40690. 
Changes made: 
- Corrected the auth_api_url value for AAP 2.5.

AAP-40690: Corrected the auth_api_url value

---

downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc

Update Tested Topology Docs to Reflect RHEL 8 Testing
https://issues.redhat.com/browse/AAP-39568

Add rhel 8 to RPM topologies

---

downstream/titles/release-notes/async/aap-25-20250225.adoc
downstream/titles/release-notes/master.adoc

* Release notes for the 2.5.20250225 async release.
Resolves:AAP-40386
* Update aap-25-20250225.adoc
* Update aap-25-20250225.adoc

Release notes for the 2.5.20250225 async release. (#2986)

---

downstream/titles/release-notes/async/aap-25-20250225.adoc

Fix typo in async release notes for Feb 25th, 2025

Feb 25 async release notes - fix typo

---

downstream/titles/release-notes/async/aap-25-20250225.adoc

Fix typo in async release notes for 25th Feb 2025

2.5 Feb 25 async release notes - fix typo (#2988)

---

downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc

Incorrect version in "Using automation execution" doc
https://issues.redhat.com/browse/AAP-40521

Correct version in Controller UG

---

downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc

Incorrect version in "Using automation execution" doc
https://issues.redhat.com/browse/AAP-40521

Correct version in Controller UG (#2994)

---

downstream/modules/platform/con-hs-eda-controller.adoc
downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc

Containerized installation - ensure code blocks adhere to style guide & copy/paste works correctly
https://issues.redhat.com/browse/AAP-40153

Update code-blocks in Containerized installation

---

downstream/modules/platform/con-hs-eda-controller.adoc
downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc

Containerized installation - ensure code blocks adhere to style guide & copy/paste works correctly
https://issues.redhat.com/browse/AAP-40153

2.5 Update code-blocks in Containerized installation (#2997)

---

downstream/modules/platform/proc-add-operator-execution-nodes.adoc

[AAP-41074](https://issues.redhat.com/browse/AAP-41074) 
Updating the platform version number, and a few improvements to work choice.

Updating platform version with attribute

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

This PR updates the SAML configuration procedure to expand on steps, provide additional examples, expand pre-requisite details and other changes to help customers with the complicated configuration.

AAP-4020 - Updates to improve SAML configuration procedure

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

This PR backports the changes from #3004 to the 2.5 branch and includes the following:
* AAP-4020 - Updates to improve SAML configuration procedure
* AAP-40200 - added peer review changes

[Backport] AAP-4020 - Updates to improve SAML configuration procedure (#3004)

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

This PR fixes a broken procedure step from PR #3004

Fixed broken step formatting

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

This PR backports the fix from #3006 to the 2.5 branch.

[Backport] Fixed broken step formatting (#3006)

---

downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc

This PR updates the Access rules for applications and tokens to correctly reflect the current behavior in AAP.

Further updates to access rules section

---

downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc

This PR backports the changes from #3008 to the 2.5 branch.

[Backport] Further updates to access rules section (#3008)

---

downstream/modules/platform/proc-operator-deploy-central-config.adoc

[AAP-39713](https://issues.redhat.com/browse/AAP-39713) - Add note of auto_upgrade parameter to docs

Adding auto_upgrade instructions

---

downstream/modules/platform/proc-operator-deploy-central-config.adoc

* Adding auto_upgrade instructions

Adding auto_upgrade instructions (#3012)

---

downstream/titles/release-notes/async/aap-25-20250305.adoc
downstream/titles/release-notes/master.adoc

AAP 2.5 (20250305) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-41095

Add async release notes 20250305

---

downstream/titles/release-notes/async/aap-25-20250305.adoc
downstream/titles/release-notes/master.adoc

AAP 2.5 (20250305) Async Release - Update Async Release Notes
https://issues.redhat.com/browse/AAP-41095

2.5 Add async release notes 20250305 (#3011)

---

downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
downstream/modules/platform/ref-controller-search-tips.adoc

Add note regarding search limitations to Using AE guide
https://issues.redhat.com/browse/AAP-41269

Added note about search restriction

---

downstream/modules/platform/ref-hub-variables.adoc

Automation hub variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40596

Update hub inventory vars

---

downstream/assemblies/platform/assembly-controller-improving-performance.adoc
downstream/modules/platform/con-websocket-setup.adoc
downstream/modules/platform/proc-configuring-discovery.adoc
downstream/titles/aap-operations-guide/master.adoc

Removed assembly and put content into modules
Move Websocket configuration chapter from Operations Guide to Configuring Automation execution
https://issues.redhat.com/browse/AAP-41418

Move websocket content to controller admin

---

downstream/assemblies/platform/assembly-controller-improving-performance.adoc
downstream/modules/platform/con-websocket-setup.adoc
downstream/modules/platform/proc-configuring-discovery.adoc
downstream/titles/aap-operations-guide/master.adoc

Removed assembly and put content into modules
Move Websocket configuration chapter from Operations Guide to Configuring Automation execution
https://issues.redhat.com/browse/AAP-41418

Move websocket content to controller admin (#3029)

---

downstream/assemblies/platform/assembly-install-aap-operator.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/con-operator-upgrade-prereq.adoc

[AAP-41386](https://issues.redhat.com/browse/AAP-41386) - System requirements reference in Operator install/upgrade doc
titles > aap-operator-installation

Adding system requirements notes

---

downstream/assemblies/platform/assembly-install-aap-operator.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/con-operator-upgrade-prereq.adoc

This request was approved and merged in [PR#3031](https://github.com/ansible/aap-docs/pull/3031). Then accidentally rebased so now I'm doing it again and will merge it myself

Yaml fix...again

---

downstream/modules/devtools/proc-devtools-install-container.adoc

Update the procedure for scaffolding a devcontainer file.

AAP-40672 Devtools - modify devcontainer creation

---

downstream/modules/devtools/proc-devtools-install-container.adoc

Update the procedure for scaffolding a devcontainer file.

2.5 AAP-40672 Devtools - modify devcontainer creation (#3033)

---

downstream/modules/devtools/proc-devtools-install-container.adoc

Update the procedure for scaffolding a devcontainer file.

2.4 AAP-40672 Devtools - modify devcontainer creation (#3033)

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

Change postgreSQL to Redis
[Docs] Wrong Redis services in "Network Ports and Protocols"
https://issues.redhat.com/browse/AAP-41021

Correct port service type (#3052)

---

downstream/modules/devtools/proc-devtools-install-rpm.adoc

Update the Devtools RPM installation procedure.

AAP-41404 Update devtools RPM installation

---

downstream/modules/devtools/proc-devtools-install-rpm.adoc

Update the Devtools RPM installation procedure.

2.5 AAP-41404 Update devtools RPM installation (#3054)

---

downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc

Containerized installation - add install command for install with extra vars
https://issues.redhat.com/browse/AAP-40801

Update install proc for Containerized installation

---

downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc

* Update install proc for Containerized installation
Containerized installation - add install command for install with extra vars
https://issues.redhat.com/browse/AAP-40801

2.5 Update install proc for Containerized installation (#3058)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/async-24-20250312.adoc

Release notes for async 2.4.2025031 release.

---

downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/modules/platform/proc-aap-add-allowed-registries.adoc

* AAP-40833 edits
* PR suggestion

 AAP-40833 edits (#3065)

---

downstream/modules/platform/proc-controller-build-workflow.adoc

Update to Workflow visualizer section
https://issues.redhat.com/browse/AAP-39862

Adding note about connecting steps in WF visualizer

---

downstream/modules/platform/proc-controller-build-workflow.adoc

* Adding note about connecting steps in WF visualizer
Update to Workflow visualizer section
https://issues.redhat.com/browse/AAP-39862
* Minor wording change

Adding note about connecting steps in WF visualizer (#3024)

---

downstream/modules/platform/proc-controller-set-up-SAML.adoc

This PR backports the changes from #2818 to the 2.5 branch and includes the following:
* Fixed merge conflict
* Added peer review suggestion

[Backport] AAP-36381 - add required statement to User Permanent ID field (#2818)

---

downstream/modules/platform/ref-controller-variables.adoc

Automation controller variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40597

Update controller inventory vars

---

stories/topics/con-saas-backup-and-diaster-recovery.adoc

[AAP-41879](https://issues.redhat.com/browse/AAP-41879) Product Documentation Updates for new regions
- Adding 3 new regions and their backups

AAP-41879 - Adding new regions

---

downstream/modules/platform/proc-controller-create-insights-credential.adoc

Document controller changes needed for service accounts
https://issues.redhat.com/browse/AAP-36066

Removing Insights updates from service account work (#3086)

---

downstream/modules/aap-hardening/con-planning-considerations.adoc
downstream/modules/platform/proc-controller-set-up-logging.adoc

Fix broken links in Hardening Guide
https://issues.redhat.com/browse/AAP-42031

Fix broken links in hardening guide

---

downstream/modules/aap-hardening/con-planning-considerations.adoc
downstream/modules/platform/proc-controller-set-up-logging.adoc

Fix broken links in Hardening Guide
https://issues.redhat.com/browse/AAP-42031

Fix broken links in hardening guide (#3088)

---

downstream/modules/platform/ref-controller-set-up-jump-host.adoc

[Docs] Improve "Set up a jump host to use with automation controller" section in AAP 2.5 documentation
https://issues.redhat.com/browse/AAP-40487

Update jump host information

---

downstream/modules/platform/ref-controller-set-up-jump-host.adoc

* Update jump host information
[Docs] Improve "Set up a jump host to use with automation controller" section in AAP 2.5 documentation
https://issues.redhat.com/browse/AAP-40487
* Update jump host information
Corrections from technical review
[Docs] Improve "Set up a jump host to use with automation controller" section in AAP 2.5 documentation
https://issues.redhat.com/browse/AAP-40487
* Update jump host infromation
Correction
[Docs] Improve "Set up a jump host to use with automation controller" section in AAP 2.5 documentation
https://issues.redhat.com/browse/AAP-40487
* Update jump host information
Corrections from peer review
[Docs] Improve "Set up a jump host to use with automation controller" section in AAP 2.5 documentation
https://issues.redhat.com/browse/AAP-40487
* Update jump …

Update jump host information (#3091)

---

downstream/assemblies/platform/assembly-edge-manager-architecture.adoc
downstream/modules/platform/con-edge-manager-agent-service.adoc
downstream/modules/platform/con-edge-manager-api-server.adoc
downstream/titles/edge-manager/edge-manager-user-guide/master.adoc

* Adding RHEM architecture section to repo
[Docs] Edge Manager Architecture
https://issues.redhat.com/browse/AAP-39617
* Final edits to architecture section

Adding RHEM architecture section to repo (#3079)

---

downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
downstream/modules/platform/con-edge-manager-config-providers.adoc
downstream/modules/platform/proc-edge-manager-update-os-cli.adoc
downstream/modules/platform/ref-edge-manager-K8s-cluster.adoc
downstream/modules/platform/ref-edge-manager-config-git-repo.adoc
downstream/modules/platform/ref-edge-manager-config-http.adoc
downstream/modules/platform/ref-edge-manager-config-inline.adoc

[Docs] Flight Control - Document Managing devices
Affects `titles-edge-manager-user-guide`

Adding final sections to manage devices chapter

---

downstream/assemblies/platform/assembly-aap-architecture.adoc
downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
downstream/attributes/attributes.adoc
downstream/modules/platform/ref-configuring-inventory-file.adoc
downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/snippets/enterprise-topologies.adoc
downstream/snippets/growth-topologies.adoc
downstream/snippets/mixed-topologies.adoc
downstream/titles/release-notes/topics/aap-25.adoc

Create attributes and snippets for the different topology shapes
https://issues.redhat.com/browse/AAP-32858

Add attributes for topologies (#3100)

---

downstream/assemblies/platform/assembly-edge-manager-config.adoc
downstream/assemblies/platform/assembly-edge-manager-rbac-auth.adoc
downstream/titles/edge-manager/edge-manager-user-guide/master.adoc

[Docs] RHEM - Document authentication
https://issues.redhat.com/browse/AAP-39624

Adding authentication section to RHEM doc

---

downstream/assemblies/platform/assembly-edge-manager-config.adoc
downstream/assemblies/platform/assembly-edge-manager-rbac-auth.adoc
downstream/titles/edge-manager/edge-manager-user-guide/master.adoc

[Docs] RHEM - Document authentication
https://issues.redhat.com/browse/AAP-39624

Adding authentication section to RHEM doc (#3102)

---

downstream/modules/platform/ref-using-custom-tls-certificates.adoc

Containerized installation - Add note about combining CA certs in "Using custom TLS certificates"
https://issues.redhat.com/browse/AAP-42157

Update "Using custom TLS certificates" in Containerized installation

---

downstream/modules/platform/proc-controller-create-insights-credential.adoc
downstream/modules/platform/ref-controller-automation-analytics.adoc

Document controller changes needed for service accounts
https://issues.redhat.com/browse/AAP-36066
Affects `titles-controller-admin-guide` and `titles-controller-user-guide`

Adding service account info to 2.4 docs

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-upgrade-external-db-gateway.adoc

* AAP-38389 Ext DB upgrade edits

AAP-38389 Ext DB upgrade edits (#3106)

---

stories/topics/con-saas-backup-and-diaster-recovery.adoc

[AAP-42252](https://issues.redhat.com/browse/AAP-42252) - Docs: Updates for new regions ca-central-1 and us-east-2

Adding ca-central-1 and it's backup us-east-2

---

downstream/assemblies/platform/assembly-aap-activate.adoc
downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
downstream/assemblies/platform/assembly-configure-egress-proxy.adoc
downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
downstream/modules/hub/proc-set-community-remote.adoc
downstream/modules/platform/con-known-proxies.adoc
downstream/modules/platform/con-sticky-sessions.adoc
downstream/modules/platform/proc-change-ssl-controller.adoc
downstream/modules/platform/proc-change-ssl-installer.adoc
downstream/modules/platform/proc-configure-known-proxies.adoc
downstream/modules/platform/proc-configuring-reverse-proxy.adoc
downstream/modules/platform/proc-controller-proxy-settings.adoc
downstream/modules/platform/proc-enable-proxy-support.adoc
downstream/modules/platform/proc-proxy-AWS-inventory-sync.adoc
downstream/modules/platform/proc-renew-ssl-cert.adoc
downstream/modules/platform/proc-set-EDA-proxy.adoc
downstream/modules/platform/ref-automation-mesh-proxy.adoc
downstream/modules/platform/ref-system-proxy-config.adoc
downstream/modules/platform/ref_proxy-backends.adoc
downstream/titles/aap-operations-guide/master.adoc

Added new assembly and edited others
Update and refactor Operations Guide
https://issues.redhat.com/browse/AAP-40606

Update and refactor Operations Guide

---

downstream/assemblies/platform/assembly-aap-activate.adoc
downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
downstream/assemblies/platform/assembly-configure-egress-proxy.adoc
downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
downstream/modules/hub/proc-set-community-remote.adoc
downstream/modules/platform/con-known-proxies.adoc
downstream/modules/platform/con-sticky-sessions.adoc
downstream/modules/platform/proc-change-ssl-controller.adoc
downstream/modules/platform/proc-change-ssl-installer.adoc
downstream/modules/platform/proc-configure-known-proxies.adoc
downstream/modules/platform/proc-configuring-reverse-proxy.adoc
downstream/modules/platform/proc-controller-proxy-settings.adoc
downstream/modules/platform/proc-enable-proxy-support.adoc
downstream/modules/platform/proc-proxy-AWS-inventory-sync.adoc
downstream/modules/platform/proc-renew-ssl-cert.adoc
downstream/modules/platform/proc-set-EDA-proxy.adoc
downstream/modules/platform/ref-automation-mesh-proxy.adoc
downstream/modules/platform/ref-system-proxy-config.adoc
downstream/modules/platform/ref_proxy-backends.adoc
downstream/titles/aap-operations-guide/master.adoc

* Update and refactor Operations Guide
Added new assembly and edited others
Update and refactor Operations Guide
https://issues.redhat.com/browse/AAP-40606
* Update and refactor Operations Guide
Corrections and tweaks.
Update and refactor Operations Guide
https://issues.redhat.com/browse/AAP-40606
* Update and refactor operations guide
Corrections from peer review
Update and refactor Operations Guide
https://issues.redhat.com/browse/AAP-40606
* Update and refactor operations guide
Correction
Update and refactor Operations Guide
https://issues.redhat.com/browse/AAP-40606

Update and refactor Operations Guide (#3107)

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/platform/con-backup-aap.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-39133.
Changes made:
- Reused 'backup AAP instance' procedure from upgrade guide into RPM install guide. 
- Updated the procedure to include the new compression variables.
- Updated the 'General variables' section in RPM install guide to include the new compression variables.

AAP-39133: Added backup procedure with new compression variables

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/platform/con-backup-aap.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

This PR backports PR #3119 from main to AAP 2.5.

Backport pull request #3119 from main to AAP 2.5

---

downstream/assemblies/platform/assembly-edge-manager-images-.adoc
downstream/assemblies/platform/assembly-edge-manager-images.adoc
downstream/modules/platform/con-edge-manager-build-prereq.adoc
downstream/modules/platform/con-edge-manager-build.adoc
downstream/modules/platform/proc-edge-manager-build-bootc-image.adoc
downstream/modules/platform/proc-edge-manager-build-sign-image.adoc
downstream/modules/platform/proc-edge-manager-image-pullsecrets.adoc
downstream/modules/platform/proc-edge-manager-install-CLI.adoc
downstream/modules/platform/proc-edge-manager-request-cert.adoc

[Docs] Document building images for Edge Manager
https://issues.redhat.com/browse/AAP-39623

Adding procedure section of RHEM building images

---

downstream/assemblies/platform/assembly-edge-manager-images.adoc
downstream/modules/platform/con-edge-manager-build-prereq.adoc
downstream/modules/platform/con-edge-manager-build.adoc
downstream/modules/platform/proc-edge-manager-build-bootc-image.adoc
downstream/modules/platform/proc-edge-manager-build-sign-image.adoc
downstream/modules/platform/proc-edge-manager-image-pullsecrets.adoc
downstream/modules/platform/proc-edge-manager-install-CLI.adoc
downstream/modules/platform/proc-edge-manager-request-cert.adoc

* Adding procedure section of RHEM building images
[Docs] Document building images for Edge Manager
https://issues.redhat.com/browse/AAP-39623

Adding procedure section of RHEM building images (#3141)

---

downstream/modules/platform/con-gs-execution-env.adoc

PR:  https://issues.redhat.com/browse/AAP-42061

AAP-42061: Removed extra "s" from Getting Started guide

---

downstream/modules/platform/con-gs-execution-env.adoc

PR: https://github.com/ansible/aap-docs/pull/3143
Jira: https://issues.redhat.com/browse/AAP-42061

Backport-2.5-3143: AAP-42061 - Removed extra s from Getting Started guide (#3143)

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

This PR backports PR #3144  from main to AAP v2.5.

Backport pull request #3144 from main to 2.5

---

downstream/titles/release-notes/async/aap-25-20250312.adoc
downstream/titles/release-notes/topics/aap-25-fixed-issues.adoc

Add release notes for Anaible plug-ins for RHDH v 1.2

AAP-40573 release notes - ansible plug-ins

---

downstream/modules/aap-hardening/ref-interactive-session-timeout.adoc

Typo - AAP 2.5 hardening and compliance document
https://issues.redhat.com/browse/AAP-42425

Correct typo (#3151)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/ansible-plugins-1.2.adoc

Add release notes for Ansible plug-ins for RHDH v 1.2

2.4 AAP-40573 Ansible plug-ins - updates for RHDH 1.4 (#2966)

---

downstream/titles/release-notes/async/aap-25-20250326.adoc
downstream/titles/release-notes/master.adoc

* Release notes for async 2.520250326.
Resolves:AAP-41955
* Update aap-25-20250326.adoc

Release notes for async 2.520250326. (#3157)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/async-24-20250326.adoc

Release notes for async release 2.4.20250326.

---

downstream/assemblies/platform/assembly-controller-applications.adoc
downstream/modules/platform/proc-controller-create-application.adoc

This PR adds the details for adding External application links and notes that the functionality is a Technology Preview feature only.

AAP-42232 - Add External application link details

---

downstream/modules/platform/proc-edge-manager-sign-disk-image.adoc
downstream/modules/platform/proc-edge-manager-virt.adoc
downstream/modules/platform/proc-edge-manager-vmware.adoc
downstream/modules/platform/ref-edge-manager-platform-requirements.adoc

[Docs] Document building images for Edge Manager
https://issues.redhat.com/browse/AAP-39623

Adding final sections to RHEM building images

---

downstream/modules/platform/proc-edge-manager-sign-disk-image.adoc
downstream/modules/platform/proc-edge-manager-virt.adoc
downstream/modules/platform/proc-edge-manager-vmware.adoc
downstream/modules/platform/ref-edge-manager-platform-requirements.adoc

[Docs] Document building images for Edge Manager
https://issues.redhat.com/browse/AAP-39623

Adding final sections to RHEM building images (#3162)

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-configure-haproxy-load-balancer.adoc
downstream/modules/platform/proc-cont-aap-hub-storage.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-restore-aap-container.adoc
downstream/modules/platform/proc-update-aap-container.adoc
downstream/modules/platform/ref-configuring-inventory-file.adoc
downstream/modules/platform/ref-cont-aap-system-requirements.adoc
downstream/snippets/inventory-cont-a-env-a.adoc

Containerized installation - Improve the flow of performing an install
https://issues.redhat.com/browse/AAP-40803

Update structure of Containerized installation

---

downstream/assemblies/platform/assembly-controller-applications.adoc
downstream/modules/platform/proc-controller-create-application.adoc

This PR backports the changes from #3160 to the 2.5 branch.

[Backport] AAP-42232 - Add External application link details (#3160)

---

stories/topics/con-saas-automation.adoc
stories/topics/ref-saas-egress-model.adoc
stories/topics/ref-saas-mesh-ingress-model.adoc

[AAP-41292](https://issues.redhat.com/browse/AAP-41292) - Docs update: Ansible SaaS connectivity clarity
[Draft with edits](https://docs.google.com/document/d/1Ooo5VPXwGAoii3py7KSW8rllLtGxcdXvHzIpjmNO8GI/edit?tab=t.0#heading=h.r7lw0gyushsz)

AAP-41292 connectivity clarity edits

---

downstream/assemblies/platform/assembly-aap-activate.adoc

Replace includes for Access management and conditionalize for Operations Guide
Conditionalize assembly for Access management
https://issues.redhat.com/browse/AAP-42657

Conditionalize assembly to include in two guides (#3173)

---

downstream/titles/release-notes/topics/async-24-20250326.adoc

Updated collection bundle installer to 2.4-10.1
Deleted "devel" from Receptor

Updated version number. Deleted a word.

---

downstream/titles/release-notes/topics/async-24-20250326.adoc

Updated controller version to 4.5.20

Updated controller version

---

downstream/modules/platform/ref-database-inventory-variables.adoc

Database variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40598

Update database inventory vars

---

downstream/modules/platform/ref-database-inventory-variables.adoc

* Update database inventory vars
Database variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40598
* Updates based on technical review feedback

2.5 Update database inventory vars (#3125)

---

downstream/modules/platform/proc-configuring-controller-ldap-security.adoc

[AAP-39432](https://issues.redhat.com/browse/AAP-39432) 
Updating proc for LDAPS authentication for 2.5 gateway.

AAP-39432 edits

---

downstream/modules/platform/ref-database-inventory-variables.adoc

Database variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40598

corrects formatting

---

downstream/modules/platform/proc-configuring-controller-ldap-security.adoc

AAP-39432 edits (#3185)

---

downstream/modules/platform/ref-images-inventory-variables.adoc

Image variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40601

Update inventory vars for images vars

---

downstream/modules/platform/ref-images-inventory-variables.adoc

* Update inventory vars for images vars
Image variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40601
* Updates based on technical feedback
* Adds gateway image vars

2.5 Update inventory vars for images vars (#3140)

---

downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
downstream/modules/platform/ref-cont-aap-system-requirements.adoc

Containerized installation - update PostgreSQL requirements section to include more detail
https://issues.redhat.com/browse/AAP-40802

Update DB requirements for Containerized installation

---

downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
downstream/modules/platform/ref-cont-aap-system-requirements.adoc

Containerized installation - update PostgreSQL requirements section to include more detail
https://issues.redhat.com/browse/AAP-40802

2.5 Update DB requirements for Containerized installation (#3194)

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/modules/platform/con-operator-csrf-management.adoc
downstream/modules/platform/proc-controller-ingress-options.adoc
downstream/modules/platform/proc-hub-ingress-options.adoc
downstream/modules/platform/proc-operator-config-csrf-gateway.adoc

[AAP-41175](https://issues.redhat.com/browse/AAP-41175)
2.5 CSRF Management with Operator Docs
Adding two new sections to the Installing on OCP doc. 
Also fixing some minor typos/case usage in the Hub and controller sections

[AAP-41175] 2.5 CSRF Management with Operator Docs

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/modules/platform/con-operator-csrf-management.adoc
downstream/modules/platform/proc-controller-ingress-options.adoc
downstream/modules/platform/proc-hub-ingress-options.adoc
downstream/modules/platform/proc-operator-config-csrf-gateway.adoc

* AAP-41175-csrf-edits
* missing link

[AAP-41175] 2.5 CSRF Management with Operator Docs (#3183)

---

downstream/modules/platform/proc-operator-upgrade-external-db-gateway.adoc

* AAP-42782 edits
* Actually adding the attribute now

AAP-42782 edits (#3200)

---

downstream/modules/platform/con-operator-csrf-management.adoc

Link only brought user to top of doc, fixed to bring to exact location.

improving hyperlink accuracy

---

downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/cont-tested-vm-config.adoc
downstream/snippets/enterprise-topologies.adoc
downstream/snippets/growth-topologies.adoc
downstream/snippets/mixed-topologies.adoc
downstream/snippets/rpm-env-a-tested-system-config.adoc
downstream/snippets/rpm-env-b-tested-system-config.adoc
downstream/snippets/rpm-tested-vm-config.adoc

Tested deployment models - consolidate content to prevent duplication
https://issues.redhat.com/browse/AAP-36284

Create snippets for Tested deployment models

---

downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/cont-tested-vm-config.adoc
downstream/snippets/enterprise-topologies.adoc
downstream/snippets/growth-topologies.adoc
downstream/snippets/mixed-topologies.adoc
downstream/snippets/rpm-env-a-tested-system-config.adoc
downstream/snippets/rpm-env-b-tested-system-config.adoc
downstream/snippets/rpm-tested-vm-config.adoc

Tested deployment models - consolidate content to prevent duplication
https://issues.redhat.com/browse/AAP-36284

2.5 Create snippets for Tested deployment models (#3208)

---

downstream/titles/controller/controller-user-guide/docinfo.xml
downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
downstream/titles/edge-manager/edge-manager-user-guide/master.adoc

[Docs] Build RHEM doc for review and corrections
https://issues.redhat.com/browse/AAP-43034

Updating title of RHEM doc

---

downstream/titles/controller/controller-user-guide/docinfo.xml
downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
downstream/titles/edge-manager/edge-manager-user-guide/master.adoc

[Docs] Build RHEM doc for review and corrections
https://issues.redhat.com/browse/AAP-43034

Updating title of RHEM doc (#3213)

---

stories/topics/proc-saas-enabling-aws-privatelink.adoc

[AAP-42964](https://issues.redhat.com/browse/AAP-42964) - AAP on AWS PrivateLink Doc Updates for Multiple Regions
Updating templates to include information for multiple regions.

AAP-42964 edits

---

downstream/assemblies/platform/assembly-operator-install-planning.adoc

Level offset was incorrectly set to +2 instead of +1. This PR fixes that.

Fixing level offset issue

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-42630. 
Changes made:
Added prereq. for RHEL 9.5 issue.

AAP-42630: Added prerequisite for RHEL 9.5 issue

---

downstream/titles/release-notes/async/aap-25-20250409.adoc

Release notes for async 2.5-20250409.

---

downstream/titles/release-notes/async/aap-25-20250409.adoc

* Release notes for async 2.5-20250409.
Resolves:AAP-42750
* Update aap-25-20250409.adoc
* Update aap-25-20250409.adoc
* Update aap-25-20250409.adoc
* Update aap-25-20250409.adoc
* Update aap-25-20250409.adoc
* Update aap-25-20250409.adoc

Release notes for async 2.5-20250409. (#3224)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/async-24-20250409.adoc

Updated master.adoc
Resolves:AAP-43097

Release notes for async 2.4-20250409.

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Document the extra_settings variables for the containerized installer
https://issues.redhat.com/browse/AAP-42626

Add extra_settings inventory file vars

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Document the extra_settings variables for the containerized installer
https://issues.redhat.com/browse/AAP-42626

2.5 Add extra_settings inventory file vars (#3234)

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc

This PR addresses a minor edit to JIRA https://issues.redhat.com/browse/AAP-42630.
Changes made:
Incorporated Scott Harwell's feedback to the prereq. for RHEL 9.5 issue in RPM upgrade and migration guide.

AAP-42630-update: Incorporated Scott Harwell's feedback in RPM upgrade guide

---

downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc

Broken links report March 25 2025
https://issues.redhat.com/browse/AAP-43726

Fixing broken links in Containerized installation

---

downstream/modules/hub/proc-push-container.adoc

Work tracked in [AAP-39723](https://issues.redhat.com/browse/AAP-39723).

AAP-39723: updates login flow to push EEs to PAH

---

downstream/modules/devtools/con-devtools-requirements.adoc

2.5 Update con-devtools-requirements.adoc (#3259)

---

downstream/modules/devtools/con-devtools-requirements.adoc

Update con-devtools-requirements.adoc (#3259)

---

downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Event-Driven Ansible controller variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40599

Update inventory vars for EDA

---

downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

PR backports #3232 from main to 2.5

2.5 Update inventory vars for EDA (#3232)

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-rpm-aap.adoc
downstream/modules/platform/ref-rpm-troubleshoot-generating-logs.adoc
downstream/titles/aap-installation-guide/master.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-42952. 
Changes made:
- Created a troubleshooting section for RPM installation.
- Added info. about generating logs for troubleshooting purposes.

AAP-42952: AAP-42952: Added procedure for gathering logs for troubleshooting RPM installation

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-rpm-aap.adoc
downstream/modules/platform/ref-rpm-troubleshoot-generating-logs.adoc
downstream/titles/aap-installation-guide/master.adoc

This PR backports PR 3267 from main to AAP 2.5 branch.

Backport PR # 3267 from main to AAP 2.5 branch

---

downstream/modules/platform/proc-controller-set-up-azure.adoc

This PR updates the configuration details for Microsoft Entra ID authentication to include details about the new Group Claims field.

AAP-43417 - Update Entra ID configuration to include Group claims info

---

downstream/modules/platform/proc-setup-postgresql-ext-database.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-37000.
Changes made:
- Added procedures for enablign mTLS authentication and using custom certificates
-  Updated the variables wherever necessary

AAP-37000: Updated procedure and variables for deploying external db

---

downstream/modules/platform/proc-controller-set-up-azure.adoc

This PR backports the changes for #3265 to the 2.5 branch and includes the following:
* AAP-43417 - Update Entra ID configuration to include Group claims info
* AAP-43417 - minor corrections for formatting

[Backport] AAP-43417 - Update Entra ID configuration to include Group claims info (#3265)

---

downstream/modules/platform/proc-setup-postgresql-ext-database.adoc

This PR backports PR #3273 3273 from main to AAP 2.5 branch.

Backport pull request #3273 from main to 2.5

---

downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
downstream/modules/devtools/proc-rhdh-add-custom-configmap.adoc
downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc

Update broken links to RHDH documentation in the Ansible plug-ins installation guide.

AAP-43726 Update links in plug-ins installation guide

---

downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
downstream/modules/devtools/proc-rhdh-add-custom-configmap.adoc
downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc

AAP-43726 Update links in plug-ins installation guide

2.5 AAP-43726 Update links in plug-ins installation guide (#3257)

---

downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
downstream/modules/devtools/proc-rhdh-add-custom-configmap.adoc
downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc

* AAP-43726 Update links in plug-ins installation guide

2.4 AAP-43726 Update links in plug-ins installation guide (#3257)

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR updates the LDAP Configuration details to include information for addition of support for multi user searches.

AAP-42888 - Add information for support of LDAPUnion for multiple user searches

---

downstream/assemblies/eda/assembly-eda-credentials.adoc
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc

For [AAP-40240](https://issues.redhat.com/browse/AAP-40240), changed admonition from "IMPORTANT" to "NOTE", per discussion with Ansible docs team members.

AAP-40240-NOTE Changed admonition from IMPORTANT to NOTE, per discussion

---

downstream/modules/platform/proc-controller-set-up-azure.adoc

This PR backports the changes from #3285 to the 2.5 branch and includes the following:
* AAP-40219 - add info re: Azure parameters used by AAP/other clarifications
* Formatting and wording corrections
* Fixed spacing issues

AAP-40219 - add info re: Azure parameters used by AAP/other clarifications (#3285)

---

downstream/assemblies/platform/assembly-controller-credentials.adoc
downstream/assemblies/platform/assembly-controller-execution-environments.adoc
downstream/assemblies/platform/assembly-controller-inventories.adoc
downstream/assemblies/platform/assembly-controller-projects.adoc
downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc

[Doc] Update docs to reflect change from "Copy" to "Duplicate"
https://issues.redhat.com/browse/AAP-39300

Change copy to duplicate

---

downstream/modules/platform/ref-using-custom-tls-certificates.adoc

[AAP Setup] gateway_tls_cert and gateway_tls_key is not working as expected.
https://issues.redhat.com/browse/AAP-39956

Update Using custom TLS certificates in Containerized installation

---

downstream/modules/platform/ref-using-custom-tls-certificates.adoc

Backports #3291 from main to 2.5

2.5 Update Using custom TLS certificates in Containerized installation (#3291)

---

lightspeed/modules/proc_troubleshooting-vscode.adoc

This PR addresses troubleshooting updates that came from SME discussion + Slack convo. There was no JIRA associated with this request. 
Changes made:
Added troubleshooting info. about proxy and network errors.

Troubleshooting-updates: Included additional troubleshooting info

---

downstream/modules/hub/con-rh-certified-synclist.adoc
downstream/modules/hub/proc-create-remote.adoc

This PR represents work described in [AAP-39751](https://issues.redhat.com/browse/AAP-39751). This doc update was requested in [AAP-39408](https://issues.redhat.com/browse/AAP-39408).

AAP-39751: Notes that hub does not check other repos for dependencies

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-troubleshoot-ext-db.adoc

[[AAP-17406](https://issues.redhat.com/browse/AAP-17406)] Troubleshooting an external data base with unexpected datastyle sets
Creating a new proc for troubleshooting EDB issues. 
[Draft](https://docs.google.com/document/d/1U9DTX68uxp0Ag6432TCcziunCBIZsCiEPP5j67AiZVg/edit?tab=t.0) approved by SME

AAP-17406 edits

---

downstream/assemblies/platform/assembly-configure-aap-operator.adoc
downstream/modules/platform/proc-operator-troubleshoot-ext-db.adoc

AAP-17406 edits (#3289)

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

Change port assignment for Controller to OCP connection
https://issues.redhat.com/browse/AAP-44160

Changed OCP port assignment (#3302)

---

downstream/modules/platform/ref-controller-refresh-existing-token.adoc
downstream/modules/platform/ref-controller-revoke-access-token.adoc

This PR backports the changes from #3299.

[Backport] AAP-42905 - Corrected gateway token API path (#3299)

---

downstream/modules/platform/proc-aap-create-aap-object.adoc
downstream/modules/platform/proc-create-secret-key-secret.adoc
downstream/modules/platform/proc-operator-deploy-redis.adoc
downstream/modules/platform/proc-operator-upgrade.adoc

[AAP-44093](https://issues.redhat.com/browse/AAP-44093) 
Adding a note on the redis_storage_size variable and correcting a few typos I spotted on my travels

AAP-44093 edits and some stray typos

---

downstream/modules/platform/proc-aap-create-aap-object.adoc
downstream/modules/platform/proc-create-secret-key-secret.adoc
downstream/modules/platform/proc-operator-deploy-redis.adoc
downstream/modules/platform/proc-operator-upgrade.adoc

* AAP-44093 edits and some stray typos

AAP-44093 edits and some stray typos (#3319)

---

downstream/attributes/attributes.adoc

Adds an attribute for the installer / installation program, to minimise the impact of future name changes

2.4 Add attribute for Installer (#3321)

---

downstream/attributes/attributes.adoc

Adds an attribute for the installer / installation program, to minimise the impact of future name changes

2.5 Add attribute for Installer (#3321)

---

downstream/modules/platform/ref-system-requirements.adoc

This PR backports PR #3325 from main to AAP 2.5 branch.

Backport PR #3325 from main to AAP 2.5

---

downstream/assemblies/hub/assembly-synclists.adoc
downstream/modules/hub/con-rh-certified-synclist.adoc
downstream/modules/hub/proc-create-synclist.adoc

Work related to this PR is being tracked in [AAP-41334](https://issues.redhat.com/browse/AAP-41334).

AAP-41334: Updates content syncing instructions

---

downstream/modules/platform/ref-controller-performance-troubleshooting.adoc

Add note regarding wait time for Job outputs to load
https://issues.redhat.com/browse/AAP-44736

Editing controller job output section (#3338)

---

downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Backports #3256  from main to 2.5
* Update the gateway inventory file vars
Platform gateway variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40602
* updates based on SME feedback
* Updates based on SME feedback

2.5 Update the gateway inventory file vars (#3256)

---

downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-variables.adoc

This PR backports PR #3349 from main branch to AAP 2.5 branch.

Backport PR #3349 from main to AAP 2.5 branch.

---

lightspeed/modules/proc_view-logs.adoc
lightspeed/titles/lightspeed-release-notes/master.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-20march2025.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-28april2025.adoc

This PR addresses release notes blurb for functionality https://issues.redhat.com/browse/AAP-43404.
Changes made:
- Added release notes blurb
- Made other minor edits

AAP-43404-rn: Added release notes blurb and other minor updates

---

downstream/modules/devtools/proc-rhdh-operator-add-sidecar-container.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar-container.adoc

AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install

AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-redis-inventory-variables.adoc

Backports #3310  from main to 2.5
* Update general inventory file vars appendix
Updates the general inventory file vars appendix and adds a redis vars file for redis specific vars.
General variables - Appendix Inventory file variables improvements
https://issues.redhat.com/browse/AAP-40600
* Updates based on SME feedback
* updates based on SME feedback

2.5 Update general inventory file vars appendix (#3310)

---

stories/topics/con-saas-deployment-self-service.adoc

[[AAP-44580](https://issues.redhat.com/browse/AAP-44580)] Update the verbiage for the deprovisioning process
[Draft](https://docs.google.com/document/d/1jR-q7pfGM-GuH4H25lzTIS9tOWFei6WHy-PARAZOqck/edit?tab=t.0) with approved by SME

AAP-44580 edits

---

downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
downstream/modules/aap-hardening/ref-architecture.adoc
downstream/snippets/container-upgrades.adoc
downstream/titles/release-notes/async/aap-25-3-28-oct.adoc
downstream/titles/release-notes/topics/aap-25.adoc

The topology support statement in Tested deployment models is updated to clarify support for deployments outside of the published reference architectures.
Update Statement for Supported Topologies
https://issues.redhat.com/browse/AAP-44586

Update tested topology support wording

---

downstream/modules/builder/con-building-definition-file.adoc

fix indents execution environment definition file.

fix indents execution environment definition

---

downstream/modules/builder/con-building-definition-file.adoc

Backport #1419 from main to 2.5

2.5 fix indents executiion environment definition (#1419)

---

README.adoc

Backports #1869 from main to 2.5

2.5 fix repo name (#1869)

---

downstream/modules/platform/ref-controller-launch-jobs-with-curl.adoc

Backports #2686 from main to 2.5

2.5 fix url (#2686)

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR implements requested improvements to the LDAP configuration content to add more field explanations and examples.

AAP-40199 improvements to LDAP configuration content

---

downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
downstream/assemblies/platform/assembly-metrics-utility.adoc
downstream/modules/platform/proc-configure-a-config-map.adoc
downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
downstream/modules/platform/proc-deploy-controller.adoc
downstream/modules/platform/proc-modifying-the-run-schedule.adoc
downstream/modules/platform/ref-ccsp.adoc
downstream/modules/platform/ref-configuring-metrics-utility.adoc
downstream/modules/platform/ref-controller-cluster-instance-behavior.adoc
downstream/modules/platform/ref-fetching-a-monthly-report.adoc
downstream/modules/platform/ref-renewal-guidance.adoc
downstream/modules/platform/ref-report-types.adoc
downstream/modules/platform/ref-select-a-date-range.adoc
downstream/modules/platform/ref-show-ephemeral-use.adoc
downstream/modules/platform/ref-storage-invocation.adoc
downstream/modules/platform/ref-supported-storage.adoc

* Update chapter on metric-utility
New modules added. +new content
Asciidoc conversion for metrics-utilities docs (Ch 11 in configuring automation execution)
https://issues.redhat.com/browse/AAP-44185

2.5 Update chapter on metric-utility (#3322)

---

downstream/assemblies/devtools/assembly-self-service-deregister-templates.adoc
downstream/assemblies/devtools/assembly-self-service-feedback.adoc
downstream/assemblies/devtools/assembly-self-service-rbac.adoc
downstream/assemblies/devtools/assembly-self-service-scm-credentials-private-repos.adoc
downstream/assemblies/devtools/assembly-self-service-using-overview.adoc
downstream/assemblies/devtools/assembly-self-service-using-prereqs.adoc
downstream/assemblies/devtools/assembly-self-service-using-repo-setup.adoc
downstream/assemblies/devtools/assembly-self-service-working-templates.adoc
downstream/attributes/attributes.adoc
downstream/modules/devtools/proc-self-service-add-scm-credentials-aap.adoc
downstream/modules/devtools/proc-self-service-add-template.adoc
downstream/modules/devtools/proc-self-service-create-collection-repo.adoc
downstream/modules/devtools/proc-self-service-create-pattern-loader-repo.adoc
downstream/modules/devtools/proc-self-service-deregister-dynamic-templates.adoc
downstream/modules/devtools/proc-self-service-deregister-preinstalled-templates.adoc
downstream/modules/devtools/proc-self-service-export-collection-pah.adoc
downstream/modules/devtools/proc-self-service-launch-template.adoc
downstream/modules/devtools/proc-self-service-set-up-rbac.adoc
downstream/modules/devtools/proc-self-service-share-credentials-aap.adoc
downstream/modules/devtools/proc-self-service-verify-rbac.adoc
downstream/titles/release-notes/topics/aap-25.adoc
downstream/titles/self-service-using/docinfo.xml
downstream/titles/self-service-using/master.adoc

AAP-45308 Self-service Install and usage guides
Affects `titles/self-service-using`

AAP-45308 Self-service Install and usage guides (#3394)

---

downstream/assemblies/platform/assembly-install-aap-gateway.adoc
downstream/assemblies/platform/assembly-operator-configure-aap-components.adoc
downstream/assemblies/platform/assembly-operator-configure-gateway.adoc
downstream/assemblies/platform/assembly-operator-install-operator.adoc
downstream/modules/platform/proc-operator-access-aap.adoc
downstream/modules/platform/proc-operator-upgrade.adoc
downstream/modules/platform/proc-update-aap-on-ocp.adoc
downstream/titles/aap-operator-installation/master.adoc

[AAP-42568](https://issues.redhat.com/browse/AAP-42568)
Installation of Ansible Automation Gateway Unclear 
Restructuring doc to be clearer for the various admins who use it. 
downstream/titles/aap-operator-installation

AAP-42568 - restructing doc

---

downstream/assemblies/platform/assembly-aap-backup.adoc

[AAP-45253](https://issues.redhat.com/browse/AAP-45253) - Remove outdated sections for controller and hub backup

Removing sections no longer required as gateway exists

---

downstream/assemblies/platform/assembly-aap-activate.adoc
downstream/assemblies/platform/assembly-controller-subscription-management.adoc
downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
downstream/modules/platform/con-host-metrics-dashboard.adoc
downstream/modules/platform/con-host-metrics-subscriptions.adoc
downstream/modules/platform/con-soft-deletion.adoc
downstream/modules/platform/con-view-hosts-in-CLI.adoc
downstream/modules/platform/con-view-hosts-in-ui.adoc
downstream/modules/platform/proc-aap-activate-with-manifest.adoc
downstream/modules/platform/proc-controller-awx-manage-utility.adoc
downstream/modules/platform/ref-delete-hosts-api-endpoint.adoc
downstream/titles/controller/controller-admin-guide/master.adoc

* Adding Subscription Management to Controller Admin
Added assembly and first modules
Asciidoc conversion for subscription content in configuring automation execution
https://issues.redhat.com/browse/AAP-43840
* Adding Subsciption Managemt to Controller admin
Build problem investigation
Asciidoc conversion for subscription content in configuring automation execution
https://issues.redhat.com/browse/AAP-43840
* Adding Subscription Management to Controller Admin
Added remaining modules
Asciidoc conversion for subscription content in configuring automation execution
https://issues.redhat.com/browse/AAP-43840
* Adding Subscription Manager to Controller Admin
Corrections
Asciidoc conversion for subscription content in configuring automation execution
https://issues.redhat.com/browse/AAP-43840

Adding Subscription Management to Controller Admin (#3385)

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR fixes a few formatting issues in examples for LDAP configuration steps.

Minor formatting fixes highlighted by the SME

---

downstream/modules/platform/proc-controller-set-up-LDAP.adoc

This PR backports the changes from #3410 to the 2.5 branch.

[Backport] Minor formatting fixes highlighted by the SME (#3410)

---

downstream/modules/platform/proc-controller-delete-job-template.adoc

Rename icon
https://issues.redhat.com/browse/AAP-45437

Rename delete icon

---

downstream/modules/platform/proc-controller-delete-job-template.adoc

Rename icon
https://issues.redhat.com/browse/AAP-45437

Rename delete icon (#3414)

---

downstream/modules/platform/con-controller-api-basic-auth.adoc

Docs mention old api endpoints
https://issues.redhat.com/browse/AAP-44795

Updating controller API endpoints (#3363)

---

downstream/titles/aap-operator-installation/master.adoc

Adding in the configuring automation hub module which was removed in error.

adding in missing module

---

downstream/assemblies/devtools/assembly-self-service-accessing-deployment.adoc
downstream/assemblies/devtools/assembly-self-service-create-ocp-registry.adoc
downstream/assemblies/devtools/assembly-self-service-deregister-templates.adoc
downstream/modules/devtools/proc-self-service-create-ocp-auth-secrets.adoc
downstream/modules/devtools/proc-self-service-install-helm-from-catalog.adoc
downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
downstream/modules/devtools/proc-self-service-sync-frequency.adoc

AAP-45308 Add sync frequency section to portal install doc (#3418)

AAP-45308 Add sync frequency section to portal install doc (#3418)

---

downstream/titles/release-notes/async/aap-25-20250507.adoc
downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/tech-preview.adoc

* Draft of the rn for the 2.5.20250507 async release.
* Release notes for the 2.5.20250507 asyn release.
Resolves:AAP-43457
* Update aap-25-20250507.adoc
* Update aap-25-20250507.adoc
* Update aap-25-20250507.adoc
* Update aap-25-20250507.adoc
* Update aap-25-20250507.adoc
* Update aap-25-20250507.adoc

Rn 2.5.20250507 (#3423)

---

downstream/titles/release-notes/topics/aap-25.adoc

Delete the release note for self-service tech preview. 
Release has been deferred.

AAP-45307 Delete release note for self service tech preview

---

downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/snippets/cont-tested-vm-config.adoc

Update the system requirements for containerized installs to include guidance on sizing for installation directory if in a dedicated partition.
Containerized installation - add more clarity on storage size requirements
https://issues.redhat.com/browse/AAP-40799

Update local disk req for CONT installs

---

downstream/assemblies/platform/assembly-edge-manager-install.adoc
downstream/attributes/attributes.adoc
downstream/modules/platform/con-edge-manager-agent-service.adoc
downstream/modules/platform/con-edge-manager-api-server.adoc
downstream/modules/platform/con-edge-manager-set-up-oauth.adoc
downstream/modules/platform/proc-edge-manager-bootc.adoc
downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
downstream/modules/platform/proc-edge-manager-oauth-auto.adoc
downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
downstream/modules/platform/ref-edge-manager-certificates.adoc
downstream/modules/platform/ref-edge-manager-config-inline.adoc
downstream/titles/edge-manager/edge-manager-user-guide/master.adoc

[Docs] Flight Control Document installation
https://issues.redhat.com/browse/AAP-39620

Adding install steps to RHEM doc

---

downstream/assemblies/platform/assembly-edge-manager-install.adoc
downstream/attributes/attributes.adoc
downstream/modules/platform/con-edge-manager-agent-service.adoc
downstream/modules/platform/con-edge-manager-api-server.adoc
downstream/modules/platform/con-edge-manager-set-up-oauth.adoc
downstream/modules/platform/proc-edge-manager-bootc.adoc
downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
downstream/modules/platform/proc-edge-manager-oauth-auto.adoc
downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
downstream/modules/platform/ref-edge-manager-certificates.adoc
downstream/modules/platform/ref-edge-manager-config-inline.adoc
downstream/titles/edge-manager/edge-manager-user-guide/master.adoc

* Adding install steps to RHEM doc
[Docs] Flight Control Document installation
https://issues.redhat.com/browse/AAP-39620
* Adding steps from tech review to RHEM install
* Further tech review edits
* Minor edit
* Adding Edge Manager title attributes
* Finalizing RHEM installation steps
* Further tech review edits on installing chapter

Adding install steps to RHEM doc (#3379)

---

downstream/assemblies/platform/assembly-controller-pac.adoc
downstream/modules/platform/con-pac-policies-rules.adoc
downstream/modules/platform/proc-configure-pac-enforcement.adoc
downstream/modules/platform/proc-configure-pac-settings.adoc
downstream/modules/platform/proc-enable-pac.adoc
downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
downstream/modules/platform/proc-pac-add-policy-to-org.adoc
downstream/modules/platform/proc-pac-add-policy-to-template.adoc
downstream/modules/platform/ref-pac-inputs-outputs.adoc
downstream/titles/controller/controller-admin-guide/master.adoc

This PR creates the assembly and modules for the policy as code documentation. See [AAP-40838](https://issues.redhat.com/browse/AAP-40838) for more.

AAP-40838: creates policy as code assemblies and modules

---

downstream/assemblies/platform/assembly-controller-pac.adoc
downstream/modules/platform/con-pac-policies-rules.adoc
downstream/modules/platform/proc-configure-pac-enforcement.adoc
downstream/modules/platform/proc-configure-pac-settings.adoc
downstream/modules/platform/proc-enable-pac.adoc
downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
downstream/modules/platform/proc-pac-add-policy-to-org.adoc
downstream/modules/platform/proc-pac-add-policy-to-template.adoc
downstream/modules/platform/ref-pac-inputs-outputs.adoc
downstream/titles/controller/controller-admin-guide/master.adoc

This PR ports the changes from [PR 3434](https://github.com/ansible/aap-docs/pull/3441) to the 2.5 branch. See [AAP-4038](https://issues.redhat.com/browse/AAP-40838) for more.

Bp to 2.5: AAP-40838: creates policy as code assemblies and modules (#3434)

---

downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc

[Docs] Update RHEM install steps
https://issues.redhat.com/browse/AAP-45701

Updating RHEM install steps

---

downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc

[Docs] Update RHEM install steps
https://issues.redhat.com/browse/AAP-45701

Updating RHEM install steps (#3443)

---

downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc

Adding changes from AAP-45701 to reset main

Adding changes from AAP-45701 to reset main

---

downstream/modules/platform/proc-configure-pac-settings.adoc

Edits based on feedback [in this slack conversation](https://redhat-internal.slack.com/archives/C081QCKEF0A/p1747067076735419?thread_ts=1747061068.635819&cid=C081QCKEF0A). This work is being tracked in [AAP-40838 ](https://issues.redhat.com/browse/AAP-40838).

AAP-40838: PaC minor edits based on SME feedback

---

downstream/modules/platform/proc-configure-pac-settings.adoc

This PR ports the changes from[ PR 3450](https://github.com/ansible/aap-docs/pull/3450) to the 2.5 branch. See [AAP-40838](https://issues.redhat.com/browse/AAP-40838) for more info.

Backport to 2.5: AAP-40838: minor edits based on SME feedback (#3450)

---

downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
downstream/assemblies/hub/assembly-synclists.adoc
downstream/modules/hub/proc-create-requirements-file.adoc
downstream/modules/hub/proc-create-synclist.adoc
downstream/modules/hub/proc-set-rhcertified-remote.adoc

This work is being tracked in [AAP-41334](https://issues.redhat.com/browse/AAP-41334).

AAP-41334: Updates info on requirements files in Managing automation content

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/modules/platform/ref-cont-aap-system-requirements.adoc
downstream/modules/platform/ref-using-custom-tls-certificates.adoc

Backports #3454 from main to 2.5
Updates to Containerized installation based on walkthrough of an install.
Containerized installation - documentation improvements
https://issues.redhat.com/browse/AAP-43145

2.5 Update Containerized installation (#3454)

---

downstream/assemblies/devtools/assembly-rhdh-ocp-required-installation.adoc
downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
downstream/modules/devtools/proc-rhdh-configure-showcase-location.adoc
downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
downstream/modules/devtools/proc-rhdh-download-plugins.adoc
downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator.adoc
downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
downstream/modules/devtools/proc-self-service-download-tar.adoc
downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc
downstream/modules/devtools/ref-rhdh-full-helm-chart-ansible-plugins.adoc

Update names and configmap for ansible-plugins 1.5

2.5 Update names and configmap for ansible-plugins 1.5 (#3449)

---

downstream/assemblies/devtools/assembly-self-service-telemetry-capture.adoc
downstream/attributes/attributes.adoc
downstream/modules/devtools/con-self-service-telemetry-data.adoc
downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
downstream/modules/devtools/proc-self-service-install-verify.adoc
downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
downstream/modules/devtools/proc-self-service-sync-frequency.adoc
downstream/modules/devtools/proc-self-service-telemetry-disable.adoc
downstream/modules/devtools/proc-self-service-view-configmap.adoc
downstream/modules/devtools/proc-self-service-view-deployment-logs.adoc
downstream/titles/self-service-install/docinfo.xml
downstream/titles/self-service-install/master.adoc

Add a procedure to disable telemetry data collection in Ansible self-service.

Self-service: Rename; add proc to disable telemetry

---

downstream/assemblies/devtools/assembly-self-service-telemetry-capture.adoc
downstream/attributes/attributes.adoc
downstream/modules/devtools/con-self-service-telemetry-data.adoc
downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
downstream/modules/devtools/proc-self-service-install-verify.adoc
downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
downstream/modules/devtools/proc-self-service-sync-frequency.adoc
downstream/modules/devtools/proc-self-service-telemetry-disable.adoc
downstream/modules/devtools/proc-self-service-view-configmap.adoc
downstream/modules/devtools/proc-self-service-view-deployment-logs.adoc
downstream/titles/self-service-install/docinfo.xml
downstream/titles/self-service-install/master.adoc

Rename AAP self-service technical preview to AAP self-service technology preview.
Add a procedure to disable telemetry.

2.5 Self-service: Rename; add proc to disable telemetry (#3445)

---

downstream/titles/self-service-using/docinfo.xml
downstream/titles/self-service-using/master.adoc

Rename AAP self-service user guide from "Technical preview" to "Technology preview"

2.5 Rename AAP self-service user guide (#3467)

---

downstream/modules/platform/ref-ansible-inventory-variables.adoc

Auditing the inventory file vars documented in Containerized installation to ensure all vars referenced in the doc are also listed in the appendix.
All vars mentioned in Containerized installation should also be mentioned in the inventory file appendix
https://issues.redhat.com/browse/AAP-45788

Update ansible inventory vars

---

downstream/assemblies/platform/assembly-controller-pac.adoc
downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
downstream/modules/platform/proc-pac-add-policy-to-org.adoc
downstream/modules/platform/proc-pac-add-policy-to-template.adoc
downstream/modules/platform/ref-pac-inputs-outputs.adoc

See [AAP-40838](https://issues.redhat.com/browse/AAP-40838) for more.

AAP-40838: PaC input/output table

---

downstream/assemblies/platform/assembly-controller-pac.adoc
downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
downstream/modules/platform/proc-pac-add-policy-to-org.adoc
downstream/modules/platform/proc-pac-add-policy-to-template.adoc
downstream/modules/platform/ref-pac-inputs-outputs.adoc

This PR ports the changes from [PR 3441](https://github.com/ansible/aap-docs/pull/3441) to the 2.5 branch. See [AAP-40838](https://issues.redhat.com/browse/AAP-40838) for more info.

AAP-40838: PaC input/output table (#3441)

---

downstream/titles/release-notes/topics/async-24-12-18-dec.adoc
downstream/titles/release-notes/topics/async-24-20250129.adoc
downstream/titles/release-notes/topics/async-24-20250312.adoc
downstream/titles/release-notes/topics/async-24-20250326.adoc
downstream/titles/release-notes/topics/async-24-20250409.adoc
downstream/titles/release-notes/topics/async-24-20250507.adoc
downstream/titles/release-notes/topics/async-24-26-3-dec.adoc

Readjusted the 05/07 table to reflect the same order for consistency.
Resolves:AAP-38741 and AAP-43326

Added tables to all async releases from 12/24 to 04/25

---

lightspeed/modules/proc_create-connection-secrets.adoc
lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-45195. 
Changes made:
- Added info. about new key `model_verify_ssl` in both procedure and troubleshooting info.

AAP-45195: AAP-45195: Updated docs with new model_verify_ssl key

---

downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
downstream/assemblies/platform/assembly-control-plane-adjustments.adoc
downstream/assemblies/platform/assembly-pod-spec-modifications.adoc
downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc
downstream/modules/platform/con-alternative-capacity-limits.adoc
downstream/modules/platform/con-pod-specification-mods.adoc
downstream/modules/platform/proc-configure-controller-OCP.adoc
downstream/modules/platform/proc-customizing-pod-specs.adoc
downstream/modules/platform/proc-enable-pods-ref-images.adoc
downstream/modules/platform/proc-specify-nodes-job-execution.adoc
downstream/modules/platform/ref-assign-pods-to-nodes.adoc
downstream/modules/platform/ref-container-resource-requirements.adoc
downstream/modules/platform/ref-requests-limits.adoc
downstream/modules/platform/ref-resource-management-pods-containers.adoc
downstream/modules/platform/ref-resource-types.adoc
downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc
downstream/modules/platform/ref-set-custom-pod-timeout.adoc
downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
downstream/titles/ocp_performance_guide/master.adoc

[AAP-45899](https://issues.redhat.com/browse/AAP-45899) Review OCP Performance considerations documentation using the Mod doc templates checklist.
Reviewed the OCP Performance considerations documentation using the [Mod doc templates checklist](https://docs.google.com/document/d/13NAUVAby1y1qfT77QFIZrMBhi872e7IEvAC9MUpGXbQ/edit?tab=t.0). 
[Performance considerations](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/performance_considerations_for_operator_environments/index)

Performing migration checklist review for OCP Performance considerations

---

downstream/assemblies/platform/assembly-aap-backup-recovery.adoc
downstream/assemblies/platform/assembly-aap-backup.adoc
downstream/assemblies/platform/assembly-aap-recovery.adoc
downstream/assemblies/platform/assembly-aap-troubleshoot-backup-recovery.adoc
downstream/modules/platform/con-aap-backup-recommendations.adoc
downstream/modules/platform/con-aap-backup-recovery.adoc
downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
downstream/modules/platform/proc-troubleshoot-same-name.adoc

[AAP-45898](https://issues.redhat.com/browse/AAP-45898)
Review OCP Backup and restore documentation using the Mod doc templates checklist.
Reviewed the OCP backup and restore documentation using the [Mod doc templates checklist](https://docs.google.com/document/d/13NAUVAby1y1qfT77QFIZrMBhi872e7IEvAC9MUpGXbQ/edit?tab=t.0).
[Backup and restore](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/backup_and_recovery_for_operator_environments/index)

OCP backup and restore module checklist review

---

downstream/assemblies/platform/assembly-install-aap-operator.adoc
downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
downstream/assemblies/platform/assembly-operator-install-operator.adoc
downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/con-operator-additional-resources.adoc
downstream/modules/platform/con-operator-csrf-management.adoc
downstream/modules/platform/con-operator-custom-resources.adoc
downstream/modules/platform/proc-install-aap-operator-chatbot.adoc
downstream/modules/platform/proc-install-aap-operator.adoc
downstream/modules/platform/proc-install-cli-aap-operator.adoc
downstream/modules/platform/proc-operator-link-components.adoc
downstream/modules/platform/ref-operator-ocp-version.adoc

[AAP-45897](https://issues.redhat.com/browse/AAP-45897) Review installing on OCP documentation using the Mod doc templates checklist.
Reviewed the Installing on OCP documentation using the [Mod doc templates checklist](https://docs.google.com/document/d/13NAUVAby1y1qfT77QFIZrMBhi872e7IEvAC9MUpGXbQ/edit?tab=t.0).
[Installing on OCP](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/installing_on_openshift_container_platform/index)

Module review checklist for Installing on OCP

---

downstream/modules/platform/proc-gw-team-access-resources.adoc
downstream/modules/platform/proc-gw-user-access-resources.adoc

This PR backports the changes from #3487 to the 2.5 branch.

[Backport] AAP-28022 - Added not re: access for Remote Registries (#3487)

---

downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc

This PR backports PR #3491 from main to AAP 2.5 branch.

Backport PR #3491 from main branch to AAP 2.5 branch

---

downstream/assemblies/platform/assembly-controller-search.adoc
downstream/modules/platform/ref-controller-other-search-considerations.adoc
downstream/modules/platform/ref-controller-search-sort.adoc
downstream/modules/platform/ref-controller-search-tips.adoc
downstream/modules/platform/ref-controller-search-values-related-fields.adoc
downstream/modules/platform/ref-controller-values-for-search-fields.adoc

Ensured modular documentation compliance for [Chapter 4 Search](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#assembly-controller-search) (can handle UI compliance when there's an environment available.).

AAP-45080 Updates to ensure mod doc compliance

---

downstream/assemblies/platform/assembly-controller-user-interface.adoc
downstream/modules/platform/con-controller-administration.adoc
downstream/modules/platform/con-controller-infrastructure.adoc
downstream/modules/platform/con-controller-settings.adoc

Ensured modular documentation compliance for [Chapter 3 The User Interface](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#assembly-controller-user-interface) (can handle UI compliance when there's an environment available.).

AAP-45079 Using automation execution UI and modular compliance chapter 3

---

downstream/assemblies/platform/assembly-controller-user-interface.adoc
downstream/modules/platform/con-controller-administration.adoc
downstream/modules/platform/con-controller-infrastructure.adoc
downstream/modules/platform/con-controller-settings.adoc

Ensured modular documentation compliance for [Chapter 3 The User Interface](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#assembly-controller-user-interface) (can handle UI compliance when there's an environment available).

Backport-2.5-3489 (AAP-45079) Using automation execution modular compliance chapter 3

---

downstream/assemblies/platform/assembly-controller-search.adoc
downstream/modules/platform/ref-controller-other-search-considerations.adoc
downstream/modules/platform/ref-controller-search-sort.adoc
downstream/modules/platform/ref-controller-search-tips.adoc
downstream/modules/platform/ref-controller-search-values-related-fields.adoc
downstream/modules/platform/ref-controller-values-for-search-fields.adoc

Ensured modular documentation compliance for [Chapter 4 Search](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#assembly-controller-search) (can handle UI compliance when there's an environment available.).

Backport-2.5-3490 (AAP-45080) Using automation execution modular compliance chapter 4

---

downstream/assemblies/hub/assembly-validated-content.adoc
downstream/modules/hub/con-token-management-hub.adoc
downstream/modules/hub/proc-create-synclist.adoc
downstream/modules/hub/proc-set-community-remote.adoc
downstream/modules/hub/proc-set-rhcertified-remote.adoc

See [AAP-41334](https://issues.redhat.com/browse/AAP-41334) for further info.

AAP-41334: reorganizes syncing procedures for clarity + adds KB on resource requirements

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/ref-containerized-troubleshoot-config.adoc
downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc

Containerized installation - Assembly - Troubleshooting
https://issues.redhat.com/browse/AAP-45976

Update troubleshooting section of Containerized installation to adhere to modular docs guidelines

---

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/ref-containerized-troubleshoot-config.adoc
downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc

Backports #3503 from main to 2.5
* Update Containerized installation to adhere to modular docs guidelines
https://issues.redhat.com/browse/AAP-45888

2.5 Update troubleshooting section of Containerized installation to adhere to modular docs guidelines (#3503)

---

downstream/assemblies/platform/assembly-aap-migration.adoc
downstream/assemblies/platform/assembly-controller-resource-operator.adoc
downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/assemblies/platform/assembly-operator-upgrade.adoc
downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/titles/aap-operator-installation/master.adoc

[AAP-45897](https://issues.redhat.com/browse/AAP-45897) Review installing on OCP documentation using the Mod doc templates checklist.
Reviewed the Installing on OCP documentation using the [Mod doc templates checklist](https://docs.google.com/document/d/13NAUVAby1y1qfT77QFIZrMBhi872e7IEvAC9MUpGXbQ/edit?tab=t.0).
[Installing on OCP](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/installing_on_openshift_container_platform/index)

Tidying up 2.4 assembly

---

downstream/modules/platform/proc-update-aap-container.adoc

Containerized Installation Documentation Lacks Details on User Accounts for AAP Components
https://issues.redhat.com/browse/AAP-37230

correct broken xref

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/eda/ref-installing-eda-controller-on-aap.adoc
downstream/modules/hub/ref-variables-connect-hub-sso.adoc
downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
downstream/modules/platform/con-controller-additional-settings.adoc
downstream/modules/platform/proc-change-ssl-installer.adoc
downstream/modules/platform/ref-ansible-inventory-variables.adoc
downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-database-inventory-variables.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
downstream/modules/platform/ref-gateway-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/modules/platform/ref-images-inventory-variables.adoc
downstream/modules/platform/ref-receptor-inventory-variables.adoc
downstream/modules/platform/ref-redis-inventory-variables.adoc
downstream/snippets/inventory-cont-a-env-a.adoc
downstream/snippets/inventory-cont-b-env-a.adoc
downstream/snippets/inventory-rpm-a-env-a.adoc
downstream/snippets/inventory-rpm-a-env-b.adoc
downstream/snippets/inventory-rpm-b-env-a.adoc
downstream/snippets/inventory-rpm-b-env-b.adoc

Updating the assembly-appendix-inventory-file-vars.adoc and associated modules to adhere to modular docs best practices
Containerized installation - Assembly - Inventory file variables
https://issues.redhat.com/browse/AAP-45911

Update inventory file vars appendix for mod docs

---

downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
downstream/modules/platform/con-controller-surveys.adoc
downstream/modules/platform/proc-controller-adding-permissions.adoc
downstream/modules/platform/proc-controller-create-job-template.adoc
downstream/modules/platform/proc-controller-delete-job-template.adoc
downstream/modules/platform/proc-controller-launch-job-template.adoc
downstream/modules/platform/ref-controller-intro-job-template.adoc
downstream/modules/platform/ref-controller-job-template-variables.adoc

* Update Ch 6 Job Templates for UI and migration
Using automation execution UI and modular compliance chapter 6 (Job Templates)
https://issues.redhat.com/browse/AAP-45082
* Update Ch6 Job Templates for UI and migration
Corrected card view
Using automation execution UI and modular compliance chapter 6 (Job Templates)
https://issues.redhat.com/browse/AAP-45082
* Update Ch6 Job templates
Correction
Using automation execution UI and modular compliance chapter 6 (Job Templates)
https://issues.redhat.com/browse/AAP-45082
* Update Ch6 for UI and migration
Corrections
Using automation execution UI and modular compliance chapter 6 (Job Templates)
https://issues.redhat.com/browse/AAP-45082
* Update Ch 6 Job templates
Correction
Using automation execution UI and modular compliance chapter 6 (Job …

Update Ch 6 Job Templates for UI and migration (#3510)

---

downstream/modules/platform/ref-pac-inputs-outputs.adoc

See [AAP-46197 ](https://issues.redhat.com/browse/AAP-46197)for more details.

AAP-46197: improves table formatting for readability

---

downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
downstream/modules/platform/con-controller-work-with-permissions.adoc
downstream/modules/platform/con-controller-workflow-notifications.adoc
downstream/modules/platform/proc-controller-build-workflow.adoc
downstream/modules/platform/proc-controller-copy-workflow-job-template.adoc
downstream/modules/platform/proc-controller-create-workflow-template.adoc

Using automation execution UI and modular compliance chapter 8
https://issues.redhat.com/browse/AAP-45084

Modularizing chapter 8 of controller user guide

---

downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
downstream/modules/platform/con-controller-work-with-permissions.adoc
downstream/modules/platform/con-controller-workflow-notifications.adoc
downstream/modules/platform/proc-controller-build-workflow.adoc
downstream/modules/platform/proc-controller-copy-workflow-job-template.adoc
downstream/modules/platform/proc-controller-create-workflow-template.adoc

* Modularizing chapter 8 of controller user guide
Using automation execution UI and modular compliance chapter 8
https://issues.redhat.com/browse/AAP-45084
* Modular compliance chapter 8

Modularizing chapter 8 of controller user guide (#3515)

---

downstream/modules/platform/ref-pac-inputs-outputs.adoc

This PR ports the changes from [PR 3517 ](https://github.com/ansible/aap-docs/pull/3517)to the 2.5 branch. See [AAP-46197 ](https://issues.redhat.com/browse/AAP-46197)for more details.

Backport to 2.5: AAP-46197: Updates table formatting for readability

---

downstream/assemblies/platform/assembly-ug-controller-workflows.adoc
downstream/modules/platform/con-controller-role-based-access-controls.adoc
downstream/modules/platform/ref-controller-intro-job-template.adoc
downstream/modules/platform/ref-controller-workflows-extra-variables.adoc

Using automation execution UI and modular compliance chapter 9
https://issues.redhat.com/browse/AAP-45085

Modularizing chapter 9 of controller user guide

---

downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc
downstream/attributes/attributes.adoc
downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc
downstream/modules/platform/proc-create-chatbot-config-secret.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-45761. 
Changes made:
- Updated docs for Azure OpenAI support.
- Created attributes for AI product names.
- Moved intro. content into a concept topic per mod docs guidelines.

AAP-45761: Added docs and attributes for Azure OpenAI support

---

downstream/assemblies/platform/assembly-ug-controller-schedules.adoc
downstream/modules/platform/proc-controller-add-new-schedule-from-resource.adoc
downstream/modules/platform/proc-controller-adding-new-schedule.adoc
downstream/modules/platform/proc-controller-define-schedule-exceptions.adoc
downstream/modules/platform/proc-controller-define-schedule-rules.adoc

* Modularizing chapter 10 of controller user guide
Using automation execution UI and modular compliance chapter 10
https://issues.redhat.com/browse/AAP-45086
* Final edits to Chapter 10

Modularizing chapter 10 of controller user guide (#3535)

---

downstream/assemblies/platform/assembly-controller-projects.adoc
downstream/modules/platform/proc-controller-adding-a-project.adoc
downstream/modules/platform/proc-controller-updating-a-project.adoc
downstream/modules/platform/proc-projects-manage-playbooks-manually.adoc
downstream/modules/platform/proc-scm-git-subversion.adoc
downstream/modules/platform/proc-scm-insights.adoc
downstream/modules/platform/ref-projects-collections-support.adoc
downstream/modules/platform/ref-projects-galaxy-support.adoc
downstream/modules/platform/ref-projects-manage-playbooks-with-source-control.adoc
downstream/modules/platform/ref-work-with-permissions.adoc

* Modularizing chapter 11 of controller user guide
Using automation execution UI and modular compliance chapter 10
https://issues.redhat.com/browse/AAP-45087

Modularizing chapter 11 of controller user guide (#3539)

---

downstream/titles/release-notes/async/aap-25-20250528.adoc

Release notes for async 2.5.20250528

---

downstream/titles/release-notes/async/aap-25-20250528.adoc

* Release notes for async 2.5.20250528
Resolves:AAP-45741
* Update aap-25-20250528.adoc
* Update aap-25-20250528.adoc
* Update aap-25-20250528.adoc

Release notes for async 2.5.20250528 (#3542)

---

downstream/modules/platform/proc-gs-logging-in.adoc

Work for this PR is being tracked in [AAP-44919](https://issues.redhat.com/browse/AAP-44919).

AAP-44919: updates procedure for finding your subscription

---

downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc

This PR addresses a formatting error as part of JIRA https://issues.redhat.com/browse/AAP-45761 . 
Changes made:
- Removed a bulleted item formatting that got erroneously left behind.

AAP-45761-update: Corrected a formatting error

---

downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc

This PR backports PR #3572 from main branch to AAP 2.5 branch.

Backport PR #3572 from main branch to AAP 2.5 branch

---

lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
lightspeed/modules/con_overview-lightspeed-onpremise.adoc
lightspeed/modules/proc_create-connection-secrets.adoc
lightspeed/titles/lightspeed-release-notes/master.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-11dec2024.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-20march2025.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-28april2025.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-29may2025.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-august2024.adoc

This PR includes doc updates for JIRA https://issues.redhat.com/browse/AAP-43213.
Changes made:
- Included new content + modified existing content for hybrid model support.
- Added release notes blurb for hybrid model support + made minor formatting updates.

AAP-43213: AAP-43213: Added info. about hybrid deployment model

---

downstream/assemblies/platform/assembly-gs-platform-admin.adoc
downstream/modules/platform/proc-adding-a-subscription.adoc
downstream/modules/platform/proc-gs-logging-in.adoc

This work is being tracked in [AAP-44919](https://issues.redhat.com/browse/AAP-44919).

AAP-44919: updates subscription procedure

---

downstream/assemblies/platform/assembly-gs-platform-admin.adoc
downstream/modules/platform/proc-adding-a-subscription.adoc
downstream/modules/platform/proc-gs-logging-in.adoc

This PR ports the changes from [PR 3575](https://github.com/ansible/aap-docs/pull/3575) to the 2.5 branch. See [AAP-44919](https://issues.redhat.com/browse/AAP-44919) for more info.

backport to 2.5: AAP-44919: updates subscription procedure (#3575)

---

downstream/titles/aap-operator-installation/master.adoc

[AAP-46322](https://issues.redhat.com/browse/AAP-46322) Add licensing topics to Operator install guide
titles > aap-operator-installation

Adding License assembly to OCP

---

downstream/modules/platform/proc-adding-a-subscription.adoc

This PR ports the changes from [PR 3591](https://github.com/ansible/aap-docs/pull/3591) to the 2.5 branch. See [AAP-44919](https://issues.redhat.com/browse/AAP-44919) for more info.

bp to 2.5: AAP-44919: fixes formatting error (#3591)

---

downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
downstream/modules/platform/ref-gw-request-token-after-expiration.adoc

This PR expands on the conceptual information re: tokens and updates the information based on the token expiration changes. The code changes are set to release on June 4 and the content should be published at that time.

AAP-43751 - Add changes for token expiration change 

---

downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc

AAP-47171 Update link to RHDH docs

AAP-47171 Update link to RHDH docs

---

downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc

2.4 AAP-47171 Update link to RHDH docs (#3608)

2.4 AAP-47171 Update link to RHDH docs (#3608)

---

downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc

2.5 AAP-47171 Update link to RHDH docs (#3608)

2.5 AAP-47171 Update link to RHDH docs (#3608)

---

downstream/assemblies/platform/assembly-gs-auto-dev.adoc
downstream/assemblies/platform/assembly-gs-key-functionality.adoc
downstream/modules/platform/proc-set-domain-of-interest.adoc

This work is being tracked in [AAP-39301](https://issues.redhat.com/browse/AAP-39301).

AAP-39301: Adds domain of interest info to getting started with AAP guide

---

downstream/assemblies/platform/assembly-deprovisioning-mesh.adoc
downstream/modules/platform/proc-deprovision-group.adoc
downstream/modules/platform/proc-deprovision-isolated-groups.adoc

Split procedure
DITA pre-migration tasks: Automation mesh
https://issues.redhat.com/browse/AAP-47324

Correct file for pre-migration

---

downstream/titles/release-notes/async/aap-25-20250507.adoc
downstream/titles/release-notes/async/aap-25-20250528.adoc
downstream/titles/release-notes/async/aap-25-20250609.adoc
downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/tech-preview.adoc

Resolves:AAP-46448
Moved AI content from the May 28 async release section to the main technology preview section.
Added a Policy as Code entry to the Technology Preview section in the May 7 async release notes.

Release notes for the async 2025-06-09 release (#3623)

---

stories/topics/con-azure-infrastructure-usage.adoc
stories/topics/proc-azure-accessing-aap.adoc

[AAP-47163](https://issues.redhat.com/browse/AAP-47163) DITA pre-migration tasks: Ansible on Clouds
Fixed issues with examples in the following procedures:
- proc-azure-accessing-aap.adoc
- con-azure-infrastructure-usage.adoc

AAP-47163 Examples fixed for DITA

---

downstream/assemblies/platform/assembly-deprovisioning-mesh.adoc
downstream/modules/platform/proc-deprovision-group.adoc
downstream/modules/platform/proc-deprovision-isolated-groups.adoc

Split procedure
DITA pre-migration tasks: Automation mesh
https://issues.redhat.com/browse/AAP-47324

Correct file for pre-migration (#3620)

---

downstream/assemblies/platform/assembly-deprovisioning-mesh.adoc
downstream/modules/platform/proc-deprovision-isolated-nodes.adoc
downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc

Split procedure
DITA pre-migration tasks. Automation mesh
https://issues.redhat.com/browse/AAP-47319

Premigration tasks for Automation mesh (#3619)

---

downstream/modules/platform/proc-deprovision-isolated-groups.adoc
downstream/modules/platform/proc-deprovision-isolated-nodes.adoc

Corrections
Fix admonitions in automation mesh
https://issues.redhat.com/browse/AAP-47401

Correct admonition format (#3631)

---

downstream/modules/platform/proc-cont-aap-hub-storage.adoc
downstream/modules/platform/ref-hub-variables.adoc

Add the formatting requirements for `hub_shared_data_path`.
Affected title: `titles/aap-containerized-install`
Containerized installation - update hub_shared_data_path to show example format
https://issues.redhat.com/browse/AAP-43903

Update hub_shared_data_path to add req format

---

downstream/modules/platform/proc-deprovision-group.adoc
downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc

Fix example blocks for DITA migration
https://issues.redhat.com/browse/AAP-47405

Reformat example blocks

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/async-24-202500609.adoc

Release notes for the asyn 2.4-20250609 release

---

downstream/archive/archived-modules/platform/proc-cont-aap-hub-storage.adoc
downstream/archive/archived-modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/assemblies/platform/assembly-configure-hub-storage.adoc
downstream/assemblies/platform/assembly-setup-postgresql-ext-database.adoc
downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc
downstream/modules/platform/proc-configure-ext-db-mtls.adoc
downstream/modules/platform/proc-configure-hub-azure-storage.adoc
downstream/modules/platform/proc-configure-hub-nfs-storage.adoc
downstream/modules/platform/proc-configure-hub-s3-storage.adoc
downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
downstream/modules/platform/proc-hs-eda-setup.adoc
downstream/modules/platform/proc-setup-ext-db-with-admin-creds.adoc
downstream/modules/platform/proc-setup-ext-db-without-admin-creds.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc

Pre-migration updates for:
- titles/aap-containerized-install
- titles/topologies
No net new content, just making existing content modular & archiving the original un-modularized content. 
DITA pre-migration tasks for Containerized installer & Tested deployment models
https://issues.redhat.com/browse/AAP-47340

Pre-migration updates

---

downstream/modules/platform/proc-deprovision-group.adoc
downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc

* Reformat example blocks
Fix example blocks for DITA migration
https://issues.redhat.com/browse/AAP-47405
* Reformat example blocks
Correction
Fix example blocks for DITA migration
https://issues.redhat.com/browse/AAP-47405
* Correct admonition format
Corrections
Fix admonitions in automation mesh
https://issues.redhat.com/browse/AAP-47401

Reformat example blocks (#3633)

---

downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
downstream/modules/platform/proc-set-domain-of-interest.adoc
downstream/modules/platform/ref-controller-intro-job-template.adoc

[Docs] Document ability to select domains of interest within the AAP UI [Controller]
https://issues.redhat.com/browse/AAP-47408

Adding domains of interest module to controller

---

downstream/assemblies/platform/assembly-mesh-design-patterns.adoc
downstream/assemblies/platform/assembly-planning-mesh.adoc
downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
downstream/modules/platform/con-automation-mesh-node-types.adoc
downstream/modules/platform/con-install-mesh.adoc
downstream/modules/platform/ref-mesh-minimum-resilient-config.adoc

Corrections
DITA pre-migration tasks. Automation mesh
https://issues.redhat.com/browse/AAP-47657

Update automation mesh for DITA migration (#3667)

---

downstream/modules/platform/con-aap-upgrades.adoc

This PR backports PR #3642 from main to AAP 2.5 repo.

Backport PR #3642 from main to AAP 2.5 repo.

---

downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
downstream/modules/platform/proc-define-mesh-node-types.adoc
downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
downstream/modules/platform/proc-pulling-the-secret.adoc
downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc

DITA pre-migration tasks. Operator mesh
https://issues.redhat.com/browse/AAP-47667

Update Operator Mesh for DITA migration

---

downstream/modules/platform/proc-configure-a-config-map.adoc
downstream/modules/platform/proc-controller-metrics-utility-ocp.adoc
downstream/modules/platform/proc-controller-metrics-utility-rhel.adoc
downstream/modules/platform/proc-deploy-controller.adoc
downstream/modules/platform/proc-modifying-the-run-schedule.adoc
downstream/modules/platform/ref-fetching-a-monthly-report.adoc

[AAP-45856](https://issues.redhat.com/browse/AAP-45856) [Doc] Update published subscription and metrics-utility content in configuring automation execution
- proc-configure-a-config-map.adoc
- proc-controller-metrics-utility-ocp.adoc
- proc-controller-metrics-utility-rhel.adoc
- proc-deploy-controller.adoc
- proc-modifying-the-run-schedule.adoc
- ref-fetching-a-monthly-report.adoc
Title:
- controller-admin-guide

AAP-45856-A Updated metrics-utility content (2)

---

downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
downstream/modules/platform/proc-define-mesh-node-types.adoc
downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
downstream/modules/platform/proc-pulling-the-secret.adoc
downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc

DITA pre-migration tasks. Operator mesh
https://issues.redhat.com/browse/AAP-47667

Update Operator Mesh for DITA migration (#3674)

---

downstream/modules/platform/con-automation-mesh-node-types.adoc

Correct link in Operator Mesh guide
https://issues.redhat.com/browse/AAP-47729

Correct link in Peers section

---

downstream/modules/platform/con-automation-mesh-node-types.adoc

Correct link in Operator Mesh guide
https://issues.redhat.com/browse/AAP-47729

Correct link in Peers section (#3679)

---

lightspeed/modules/con_overview-lightspeed-onpremise.adoc
lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-29may2025.adoc

This PR is an update to JIRA https://issues.redhat.com/browse/AAP-43213.
Change made: Corrected an attribute in release notes and user guide.

AAP-43213-update: Corrected an attribute

---

downstream/attributes/attributes.adoc

This work is being tracked in [AAP-47754](https://issues.redhat.com/browse/AAP-47754).

AAP-47754: updates attribute for policy settings

---

downstream/modules/builder/proc-installing-builder.adoc

Correction
Broken Link Report June 9 2025
https://issues.redhat.com/browse/AAP-47893

Correct broken link in builder doc

---

downstream/modules/builder/proc-installing-builder.adoc

Correction
Broken Link Report June 9 2025
https://issues.redhat.com/browse/AAP-47893

Correct broken link in builder doc (#3689)

---

downstream/assemblies/platform/assembly-aap-activate.adoc
downstream/assemblies/platform/assembly-controller-pac.adoc
downstream/modules/platform/proc-configure-pac-enforcement.adoc
downstream/modules/platform/proc-configure-pac-settings.adoc
downstream/modules/platform/proc-controller-find-subscription.adoc

This work is being tracked in [AAP-47553](https://issues.redhat.com/browse/AAP-47553).

AAP-47553: PaC docs add reminder to configure global and resource settings

---

downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc

Tested deployment models - Clarify external & AAP managed DB per topology
https://issues.redhat.com/browse/AAP-48015

Add clarification to database for topologies

---

downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc

Tested deployment models - Clarify external & AAP managed DB per topology
https://issues.redhat.com/browse/AAP-48015

2.5 Add clarification to database for topologies (#3708)

---

downstream/assemblies/platform/assembly-controller-hosts.adoc
downstream/modules/platform/proc-controller-create-host.adoc
downstream/modules/platform/proc-controller-view-host.adoc

Corrections
Using automation execution UI and modular compliance chapter 16
https://issues.redhat.com/browse/AAP-45150

DITA migration updates: Ch 16

---

downstream/assemblies/platform/assembly-aap-platform-components.adoc
downstream/modules/platform/con-about-controller.adoc
downstream/modules/platform/con-about-postgres.adoc

* Add controller and database descriptions
Missing components (Automation Controller and Database) in the Planning your installation document
https://issues.redhat.com/browse/AAP-48022

Add controller and database descriptions (#3725)

---

downstream/assemblies/platform/assembly-aap-platform-components.adoc
downstream/modules/platform/con-about-controller.adoc
downstream/modules/platform/con-about-postgres.adoc

Missing components (Automation Controller and Database) in the Planning your installation document
https://issues.redhat.com/browse/AAP-48022

Add missing sections

---

downstream/assemblies/platform/assembly-controller-instances.adoc
downstream/modules/platform/proc-define-mesh-node-types.adoc

Using automation execution UI and modular compliance chapter 19
https://issues.redhat.com/browse/AAP-45153

DITA migration changes: CUG Ch 19

---

downstream/assemblies/platform/assembly-controller-instances.adoc
downstream/modules/platform/proc-define-mesh-node-types.adoc

Using automation execution UI and modular compliance chapter 19
https://issues.redhat.com/browse/AAP-45153

DITA migration changes: CUG Ch 19 (#3734)

---

downstream/assemblies/platform/assembly-gs-auto-dev.adoc
downstream/assemblies/platform/assembly-gs-auto-op.adoc
downstream/modules/hub/proc-create-api-token-pah.adoc
downstream/modules/hub/proc-create-api-token.adoc
downstream/modules/hub/proc-create-requirements-file.adoc
downstream/modules/platform/con-gs-about-builder.adoc
downstream/modules/platform/proc-gs-add-ee-to-job-template.adoc
downstream/modules/platform/proc-gs-use-base-execution-env.adoc
downstream/modules/platform/ref-gs-about-container-registries.adoc

This PR ports the changes from [PR 3729](https://github.com/ansible/aap-docs/pull/3729) to the 2.5 branch. This work is being tracked in [AAP-48159](https://issues.redhat.com/browse/AAP-48159).

bp to 2.5: AAP-48159 Modular structure edits for AEM migration

---

downstream/assemblies/platform/assembly-controller-execution-environments.adoc
downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc
downstream/modules/platform/proc-controller-troubleshoot-ee-mount.adoc
downstream/modules/platform/proc-controller-use-an-exec-env.adoc
downstream/modules/platform/ref-controller-build-exec-envs.adoc
downstream/modules/platform/ref-controller-building-exec-env.adoc
downstream/modules/platform/ref-controller-install-builder.adoc

Using automation execution UI and modular compliance chapter 20
https://issues.redhat.com/browse/AAP-45154

DITA migration changes for CUG Ch 20

---

downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/cont-tested-vm-config.adoc
downstream/snippets/rpm-env-a-tested-system-config.adoc
downstream/snippets/rpm-env-b-tested-system-config.adoc
downstream/snippets/rpm-tested-vm-config.adoc

Updates to Tested deployment models. Some mod docs compliance updates and some addition/removal of content.
https://issues.redhat.com/browse/AAP-48661

Update Tested deployment models

---

downstream/modules/topologies/ref-cont-a-env-a.adoc
downstream/modules/topologies/ref-cont-b-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-a.adoc
downstream/modules/topologies/ref-rpm-a-env-b.adoc
downstream/modules/topologies/ref-rpm-b-env-a.adoc
downstream/modules/topologies/ref-rpm-b-env-b.adoc
downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/cont-tested-vm-config.adoc
downstream/snippets/rpm-env-a-tested-system-config.adoc
downstream/snippets/rpm-env-b-tested-system-config.adoc
downstream/snippets/rpm-tested-vm-config.adoc

Backports #3741 from main to 2.5 
Updates to Tested deployment models
https://issues.redhat.com/browse/AAP-48661

2.5 Update Tested deployment models (#3741)

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc
downstream/modules/platform/ref-redis-inventory-variables.adoc

Add the following vars
- controller_create_preload_data
- images_tmp_dir
- redis_tls_remote
Misc formatting updates.
Affected title: `titles/aap-containerized-install`
Containerized installation - update inventory file appendix
https://issues.redhat.com/browse/AAP-48292

Update inventory file vars

---

downstream/titles/release-notes/async/aap-25-20250702.adoc
downstream/titles/release-notes/master.adoc

Release notes for asycn release 2.5.20250702

---

downstream/titles/release-notes/async/aap-25-20250702.adoc
downstream/titles/release-notes/master.adoc

Release notes for asycn release 2.5.20250702 (#3749)

---

downstream/assemblies/platform/assembly-controller-ee-setup-reference.adoc
downstream/modules/platform/ref-controller-ee-configuration-options.adoc

Using automation execution UI and modular compliance chapter 21
https://issues.redhat.com/browse/AAP-45155

DITA migration changes for CUG CH 21

---

downstream/assemblies/platform/assembly-controller-ee-setup-reference.adoc
downstream/modules/platform/ref-controller-ee-configuration-options.adoc

* DITA migration changes for CUG CH 21
Using automation execution UI and modular compliance chapter 21
https://issues.redhat.com/browse/AAP-45155
* DITA migration changes for CUG CH 21
Correction
Using automation execution UI and modular compliance chapter 21
https://issues.redhat.com/browse/AAP-45155

DITA migration changes for CUG CH 21 (#3757)

---

downstream/titles/release-notes/async/aap-25-20250702.adoc

This update adds an enhancemente for Ansible
Lightspeed intelligent assistant
Resolves:AAP-44011

Update to the async release notes 2.5.20250702

---

downstream/titles/release-notes/async/aap-25-20250115.adoc

Pre-migration work for conversion

Fixed a nested block issue.

---

downstream/titles/release-notes/async/aap-25-20250115.adoc

Pre-migration work for conversion

Fixed a nested block issue. (#3769)

---

downstream/assemblies/aap-migration/assembly-source-containerized.adoc
downstream/assemblies/aap-migration/assembly-source-rpm.adoc

Backports #3773 from main to 2.5

2.5 update broken link (#3773)

---

downstream/assemblies/platform/assembly-edge-manager-images.adoc
downstream/assemblies/platform/assembly-edge-manager-install.adoc
downstream/modules/platform/con-edge-manager-os-img-script.adoc
downstream/modules/platform/proc-edge-manager-image-build.adoc
downstream/modules/platform/proc-edge-manager-install-CLI.adoc
downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
downstream/modules/platform/proc-edge-manager-log-into-CLI.adoc
downstream/modules/platform/proc-edge-manager-oauth-auto.adoc
downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
downstream/modules/platform/proc-edge-manager-request-cert.adoc

RHEM installation steps improvements
https://issues.redhat.com/browse/AAP-48360

Improving RHEM install and CLI steps

---

downstream/assemblies/platform/assembly-edge-manager-images.adoc
downstream/assemblies/platform/assembly-edge-manager-install.adoc
downstream/modules/platform/con-edge-manager-os-img-script.adoc
downstream/modules/platform/proc-edge-manager-image-build.adoc
downstream/modules/platform/proc-edge-manager-install-CLI.adoc
downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
downstream/modules/platform/proc-edge-manager-log-into-CLI.adoc
downstream/modules/platform/proc-edge-manager-oauth-auto.adoc
downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
downstream/modules/platform/proc-edge-manager-request-cert.adoc

* Improving RHEM install and CLI steps
RHEM installation steps improvements
https://issues.redhat.com/browse/AAP-48360
* Further edits to RHEM install

Improving RHEM install and CLI steps (#3774)

---

downstream/modules/platform/proc-operator-scaling-down-aap.adoc
downstream/titles/aap-operator-installation/master.adoc

[AAP-44664](https://issues.redhat.com/browse/AAP-44664) - New module: Scaling down Red Hat Ansible Automation Platform deployments.
[Draft](https://docs.google.com/document/d/1X4JW6rQQzUE4GGGxlqTz4lFFEgpDlw9FWpgAg616Eqg/edit?tab=t.0)

AAP-44664 edits

---

downstream/assemblies/platform/assembly-controller-activity-stream.adoc

Using automation execution UI and modular compliance chapter 24
https://issues.redhat.com/browse/AAP-45158

Modularizing chapter 24 of controller user guide

---

downstream/assemblies/platform/assembly-ug-controller-notifications.adoc
downstream/modules/platform/con-controller-configure-hostname-notifications.adoc
downstream/modules/platform/con-controller-enable-notifications.adoc
downstream/modules/platform/con-controller-notification-hierarchy.adoc
downstream/modules/platform/con-controller-notification-types.adoc
downstream/modules/platform/con-controller-notification-workflow.adoc
downstream/modules/platform/proc-controller-create-custom-notifications.adoc
downstream/modules/platform/proc-controller-create-notification-template.adoc
downstream/modules/platform/proc-controller-reset-tower-base.adoc
downstream/modules/platform/ref-controller-notification-email.adoc
downstream/modules/platform/ref-controller-notification-grafana.adoc
downstream/modules/platform/ref-controller-notification-irc.adoc
downstream/modules/platform/ref-controller-notification-mattermost.adoc
downstream/modules/platform/ref-controller-notification-rocketchat.adoc
downstream/modules/platform/ref-controller-notification-slack.adoc
downstream/modules/platform/ref-controller-notification-twilio.adoc
downstream/modules/platform/ref-controller-notification-webhook-payloads.adoc
downstream/modules/platform/ref-controller-notification-webhook.adoc
downstream/modules/platform/ref-controller-notifications-api.adoc

* Editing controller files for DITA
Using automation execution UI and modular compliance chapter 25
https://issues.redhat.com/browse/AAP-45159

Editing controller files for DITA (#3794)

---

downstream/assemblies/devtools/assembly-rhdh-ocp-required-installation.adoc
downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
downstream/modules/devtools/proc-rhdh-configure-showcase-location.adoc
downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator.adoc
downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
downstream/modules/devtools/proc-self-service-download-tar.adoc
downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc
downstream/modules/devtools/ref-rhdh-full-helm-chart-ansible-plugins.adoc

Update names and configmap for ansible-plugins 1.5 (#3449)

2.4 Update names and configmap for ansible-plugins 1.5 (#3449)

---

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
downstream/modules/hub/proc-basic-repo-sync.adoc
downstream/modules/hub/proc-create-api-token-pah.adoc
downstream/modules/hub/proc-create-api-token.adoc
downstream/modules/hub/proc-obtain-images.adoc
downstream/modules/hub/proc-offline-token-active.adoc

This work is being tracked in [AAP-48159](https://issues.redhat.com/browse/AAP-48159).

AAP-48159: DITA updates: fixes heading issue

---

downstream/assemblies/platform/assembly-ug-controller-attributes-custom-notifications.adoc
downstream/modules/platform/ref-controller-supported-attributes.adoc

Using automation execution UI and modular compliance chapter 26
https://issues.redhat.com/browse/AAP-45160

Editing controller files for DITA

---

downstream/assemblies/platform/assembly-ug-controller-attributes-custom-notifications.adoc
downstream/modules/platform/ref-controller-supported-attributes.adoc

Using automation execution UI and modular compliance chapter 26
https://issues.redhat.com/browse/AAP-45160

Editing controller files for DITA (#3806)

---

downstream/modules/hub/proc-create-api-token.adoc

This PR fixes a mistake that was introduced during the last round of DITA/Migration-related changes.

AAP-48519: fixes backporting mistake

---

lightspeed/modules/proc_create-connection-secrets.adoc
lightspeed/titles/lightspeed-release-notes/modules/ref-release-notes.adoc

This PR is an update to JIRA https://issues.redhat.com/browse/AAP-34014. The functionality was missed from being cherry-picked in the 26 June AAP release as initially intended. The functionality is planned to be included in the subsequent AAP functionality, but until then, the advice is to remove the doc updates.
This PR removes the doc updates for disabling anonymization functionality.

AAP-34014-remove: Removed doc update for model anonymization functionality

---

downstream/assemblies/platform/assembly-aap-migration.adoc

[AAP-49300](https://issues.redhat.com/browse/AAP-49300)
Current AAP 2.5 RPM -> OpenShift Procedure does not work
Updating migration section as per AAP-49300

Updating migration section as per AAP-49300

---

downstream/modules/platform/ref-general-inventory-variables.adoc

Add inventory file var "client_request_timeout" to Containerized installation
https://issues.redhat.com/browse/AAP-45170

Add client_request_timeout to inventory vars

---

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
downstream/assemblies/platform/assembly-setup-postgresql-ext-database.adoc
downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-downloading-containerized-aap.adoc
downstream/modules/platform/proc-enable-hstore-extension.adoc
downstream/modules/platform/proc-installing-containerized-aap.adoc
downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
downstream/modules/platform/proc-set-registry-username-password.adoc
downstream/modules/platform/proc-setup-ext-db-without-admin-creds.adoc
downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
downstream/modules/platform/proc-update-aap-container.adoc
downstream/modules/platform/ref-ansible-inventory-variables.adoc
downstream/modules/platform/ref-configuring-inventory-file.adoc
downstream/modules/platform/ref-cont-aap-system-requirements.adoc
downstream/modules/platform/ref-containerized-troubleshoot-install.adoc

Backports #3852 from main to 2.5 
Misc updates to Containerized installation guide
Update Containerized installation
https://issues.redhat.com/browse/AAP-49805

2.5 Updates to Containerized installation (#3852)

---

downstream/snippets/cont-tested-system-config.adoc
downstream/snippets/rpm-env-a-tested-system-config.adoc

Updates the system requirements for CONT and RPM topologies in Tested deployment models.

updates system requirements for topologies

---

downstream/modules/platform/ref-controller-backup-restore-considerations.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR backports PR #3827 from main to AAP 2.5 branch.

Backport PR #3827 from main to AAP 2.5 branch

---

downstream/assemblies/platform/assembly-inventory-file-importing.adoc
downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc

Configuring automation execution modular compliance chapters 5
https://issues.redhat.com/browse/AAP-46721

Editing controller files for DITA (#3859)

---

downstream/assemblies/platform/assembly-controller-pac.adoc
downstream/modules/platform/proc-configure-pac-settings.adoc
downstream/modules/platform/ref-pac-inputs-outputs.adoc

Configuring automation execution modular compliance chapter 7
https://issues.redhat.com/browse/AAP-46724

Editing controller files for DITA (#3864)

---

downstream/assemblies/platform/assembly-ug-controller-setting-up-insights.adoc
downstream/modules/platform/con-controller-create-insights-inventory.adoc
downstream/modules/platform/proc-controller-create-insights-credential.adoc
downstream/modules/platform/proc-controller-remediate-insights-inventory.adoc

Using automation execution UI and modular compliance chapter 28
https://issues.redhat.com/browse/AAP-45162

DITA migration changes: CUG Ch 28 (#3865)

---

downstream/assemblies/platform/assembly-controller-best-practices.adoc
downstream/modules/platform/ref-controller-autoscaling.adoc
downstream/modules/platform/ref-controller-continuous-integration.adoc
downstream/modules/platform/ref-controller-file-directory-structure.adoc
downstream/modules/platform/ref-controller-inv-variable-management.adoc
downstream/modules/platform/ref-controller-large-host-counts.adoc
downstream/modules/platform/ref-controller-source-control.adoc
downstream/modules/platform/ref-controller-use-dynamic-inv-sources.adoc

Using automation execution UI and modular compliance chapter 29
https://issues.redhat.com/browse/AAP-45163

DITA migration changes: CUG Ch 29 (#3868)

---

downstream/assemblies/platform/assembly-controller-glossary.adoc

Using automation execution UI and modular compliance Glossary
https://issues.redhat.com/browse/AAP-49902

DITA migration changes: CUG Glossary

---

downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-aap.adoc
downstream/modules/terraform-aap/con-terraform-intro.adoc
downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
downstream/modules/terraform-aap/proc-terraform-creating-credential.adoc
downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc

For the Getting Started with Terraform guide, replaced some text with attributes and used the Vale DITA extension to check DITA compatibility.
https://issues.redhat.com/browse/AAP-49823

AAP-49823: Replace text with attributes and run vale dita check

---

downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-aap.adoc
downstream/modules/terraform-aap/con-terraform-intro.adoc
downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
downstream/modules/terraform-aap/proc-terraform-creating-credential.adoc
downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc

Backport for https://issues.redhat.com/browse/AAP-49823

Backport for AAP-49823: Replace text with attributes and run vale dita check (#3872)

---

downstream/assemblies/platform/assembly-controller-glossary.adoc

Using automation execution UI and modular compliance Glossary
https://issues.redhat.com/browse/AAP-49902

DITA migration changes: CUG Glossary (#3871)

---

downstream/modules/platform/ref-controller-building-exec-env.adoc

Broken Link Report July 7 2025
https://issues.redhat.com/browse/AAP-49568

Fixing broke link in CUG

---

downstream/modules/platform/con-aap-notifications-feed.adoc
downstream/titles/aap-planning-guide/master.adoc

[AAP-49847](https://issues.redhat.com/browse/AAP-49847) Product Documentation Updates for notification feed
Updating the following guides to include the notification feed module
[Planning your installation](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/planning_your_installation/index)
[Getting started with Ansible Automation Platform](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/getting_started_with_ansible_automation_platform/index)

Fixing ID in notification feed module

---

downstream/aap-common/apache-2.0-license.adoc
downstream/aap-common/gplv3-license-text.adoc
downstream/aap-common/open-source-apache.adoc
downstream/aap-common/open-source-gnu3.adoc

DITA pre-migration tasks. Open Source licence files
https://issues.redhat.com/browse/AAP-49629

DITA migration tasks: Add doc type to licences

---

downstream/aap-common/apache-2.0-license.adoc
downstream/aap-common/gplv3-license-text.adoc
downstream/aap-common/open-source-apache.adoc
downstream/aap-common/open-source-gnu3.adoc

DITA pre-migration tasks. Open Source licence files
https://issues.redhat.com/browse/AAP-49629

DITA migration tasks: Add doc type to licences (#3884)

---

downstream/assemblies/platform/assembly-aap-activate.adoc
downstream/assemblies/platform/assembly-controller-metrics.adoc
downstream/assemblies/platform/assembly-controller-subscription-management.adoc
downstream/modules/platform/proc-controller-awx-manage-utility.adoc
downstream/modules/platform/proc-controller-set-up-prometheus.adoc
downstream/modules/platform/proc-view-hosts-in-ui.adoc

Configuring automation execution modular compliance chapters 10-11
https://issues.redhat.com/browse/AAP-46728 and https://issues.redhat.com/browse/AAP-46729
Affects titles/controller-admin-guide

Editing controller files for DITA (#3888)

---

downstream/modules/aap-hardening/proc-configure-hashicorp-credentials.adoc

Correct attribute error in hardening guide
https://issues.redhat.com/browse/AAP-50258

Fixed attribute error

---

downstream/modules/aap-hardening/proc-configure-sudo-for-service-account.adoc

Correct spelling error in Hardening guide
https://issues.redhat.com/browse/AAP-50266

Corrected spelling error

---

downstream/modules/aap-hardening/proc-configure-hashicorp-credentials.adoc

Correct attribute error in hardening guide
https://issues.redhat.com/browse/AAP-50258

Fixed attribute error (#3896)

---

downstream/modules/aap-hardening/proc-configure-sudo-for-service-account.adoc

Correct spelling error in Hardening guide
https://issues.redhat.com/browse/AAP-50266

Corrected spelling error (#3897)

---

bin/sync_docs.sh
bin/sync_ocp_latest.sh

Add sync scripts for 2.6.
The Jenkins job picks this script up for syncing to the production repo.

Add sync scripts for AAP 2.6

---

downstream/snippets/inventory-rpm-a-env-a.adoc
downstream/snippets/inventory-rpm-b-env-a.adoc

Create AAP 2.6 inventory files for Tested deployment models
https://issues.redhat.com/browse/AAP-47926

Create AAP 2.6 inventory files for Tested deployment models

---

downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc

Backports #3914 from main to 2.6

updating Containerized installation (#3914)

---

downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc

Backports #3914 from main to 2.5

2.5 updating Containerized installation (#3914)

---

downstream/assemblies/security/assembly-firewall-policy-manage.adoc
downstream/assemblies/security/assembly-idps.adoc
downstream/modules/security/con-about-firewall-policy-management.adoc
downstream/modules/security/con-automate-idps-rules.adoc
downstream/modules/security/con-automating-firewall-rules.adoc
downstream/modules/security/con-requirements.adoc
downstream/modules/security/proc-creating-firewall-rule.adoc
downstream/modules/security/proc-creating-idps-rule.adoc
downstream/modules/security/proc-deleting-firewall-rule.adoc
downstream/modules/security/proc-verifying-idps-install.adoc

DITA pre-migration tasks. Security automation Guide
https://issues.redhat.com/browse/AAP-49630

DITA migration changes: Security automation

---

.gitignore
downstream/modules/platform/proc-operator-external-db-controller.adoc

[AAP-50403](https://issues.redhat.com/browse/AAP-50403)
[OCP docs] Update the system requirements for PostgreSQL for AAP 2.4

Updating gitignore and pg

---

downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc

Configuring automation execution - Update backup and restore note to ensure clarity regarding the latest version prerequisite
https://issues.redhat.com/browse/AAP-46263

Update backup/restore note

---

downstream/modules/aap-migration/con-migration-process-overview.adoc

[AAP-50441](https://issues.redhat.com/browse/AAP-50441)
[2.6/2.5] Update the Migration doc with migration definition

AAP-50441-migration-edits

---

downstream/modules/topologies/ref-installation-deployment-models.adoc
downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/snippets/rpm-env-a-tested-system-config.adoc
downstream/titles/topologies/master.adoc

Update Tested deployment models for AAP 2.6
https://issues.redhat.com/browse/AAP-47918

Update Tested deployment models for 2.6

---

downstream/modules/platform/proc-operator-external-db-controller.adoc
downstream/modules/platform/proc-operator-external-db-gateway.adoc
downstream/modules/platform/proc-operator-external-db-hub.adoc

[AAP-48233](https://issues.redhat.com/browse/AAP-48233)
[2.6] OCP - Docs Support for PostgreSQL 16 & 17

Updating main with PG tweaks

---

downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-restore-aap-container.adoc

Containerized installation - Update backup & restore procedures to ensure clarity regarding the latest version prerequisite
https://issues.redhat.com/browse/AAP-46266

Add backup/restore note to Containerized installation

---

downstream/modules/platform/proc-backup-aap-container.adoc
downstream/modules/platform/proc-restore-aap-container.adoc

Backports #3946 from main to 2.5
Containerized installation - Update backup & restore procedures to ensure clarity regarding the latest version prerequisite
https://issues.redhat.com/browse/AAP-46266

2.5 Add backup/restore note to Containerized installation (#3946)

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc

Backports #3950 from main to 2.6 
Incorrect Controller version in documentation
https://issues.redhat.com/browse/AAP-44204

2.6 Update controller version (#3950)

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc

Backports #3950 from main to 2.5 
Incorrect Controller version in documentation
https://issues.redhat.com/browse/AAP-44204

2.5 Update controller version (#3950)

---

downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
downstream/modules/platform/proc-controller-set-up-logging.adoc
downstream/modules/platform/ref-controller-activity-stream-schema.adoc
downstream/modules/platform/ref-controller-job-status-changes.adoc
downstream/modules/platform/ref-controller-log-aggregators.adoc
downstream/modules/platform/ref-controller-logs.adoc
downstream/modules/platform/ref-controller-scan-fact-tracking-schema.adoc
downstream/modules/platform/ref-controller-troubleshoot-logging.adoc

Configuring automation execution UI and modular compliance chapter 9
https://issues.redhat.com/browse/AAP-46726

DITA migration changes: CAG Ch 9 (#3953)

---

downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
downstream/modules/platform/ref-controller-credential-network.adoc

Broken Link Report July 21 2025
https://issues.redhat.com/browse/AAP-50562

Corrected links (#3935)

---

downstream/modules/platform/proc-controller-review-organizations.adoc

This PR fixes a small formatting error in proc-controller-review-organizations.adoc.

Menu formatting fix

---

downstream/assemblies/eda/assembly-eda-credential-types.adoc
downstream/assemblies/eda/assembly-eda-decision-environments.adoc
downstream/assemblies/eda/assembly-eda-event-filter-plugins.adoc
downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc
downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
downstream/modules/eda/con-modifying-simultaneous-activations.adoc
downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
downstream/modules/eda/proc-eda-config-remote-sys-to-events.adoc
downstream/modules/eda/proc-eda-create-event-stream-credential.adoc
downstream/modules/eda/proc-eda-create-event-stream.adoc
downstream/modules/eda/proc-eda-delete-controller-token.adoc
downstream/modules/eda/proc-eda-set-up-credential-types.adoc
downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-project.adoc
downstream/modules/eda/proc-eda-set-up-rhaap-credential.adoc
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
downstream/modules/eda/proc-eda-set-up-token.adoc
downstream/modules/eda/proc-eda-view-activation-output.adoc
downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc
downstream/modules/eda/proc-eda-view-rule-audit-details.adoc
downstream/modules/eda/proc-modifying-activations-during-install.adoc
downstream/modules/eda/ref-eda-logging-samples.adoc

Pre-migration updates on multiple files in the Using automation decisions guide to pass Vale validation test before migrating content to DITA/AEM. Includes updates from PR #3875.

Backport-2.5-3875 to AAP-49612: DITA Pre-migration prep work - Using automation decisions guide

---

downstream/titles/release-notes/async/aap-25-20250730.adoc
downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/tech-preview.adoc

Relaase notes for async 2.5-20250730

---

downstream/titles/release-notes/async/aap-25-20250730.adoc
downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/tech-preview.adoc

Relaase notes for async 2.5-20250730 (#3977)

---

downstream/assemblies/platform/assembly-using-custom-tls-certificates.adoc
downstream/modules/platform/con-redis-cert-considerations.adoc

Document update for containerised AAP 2.5 custom Redis Cluster certificate
https://issues.redhat.com/browse/AAP-48450

Add redis cert considerations

---

downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc

Adds a Container details table to Containerized installation guide
Containerized installation - update "Diagnosing the problem" with a mapping of container names and their usage
https://issues.redhat.com/browse/AAP-42439

Add container details table

---

downstream/assemblies/eda/assembly-eda-projects.adoc
downstream/modules/eda/con-credentials-list-view.adoc
downstream/modules/eda/con-eda-projects-list-view.adoc
downstream/modules/eda/proc-eda-delete-project.adoc
downstream/modules/eda/proc-eda-editing-a-project.adoc

Prepped [Chapter 4. Projects](https://content-stage.docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-projects) in the Using automation decisions guide for migration compliance.
Also, includes downstream/modules/eda/con-credentials-list-view.adoc with further compliance for concept modules (no imperative statements).

Backport-2.5-3980 for AAP-46217 Pre-migration compliance for Chpt 4 

---

downstream/assemblies/eda/assembly-eda-projects.adoc
downstream/modules/eda/con-credentials-list-view.adoc
downstream/modules/eda/con-eda-projects-list-view.adoc
downstream/modules/eda/proc-eda-delete-project.adoc
downstream/modules/eda/proc-eda-editing-a-project.adoc

Prepped [Chapter 4. Projects](https://content-stage.docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-projects) in the Using automation decisions guide for migration compliance.
Also, includes downstream/modules/eda/con-credentials-list-view.adoc with further compliance for concept modules (no imperative statements).

Backport-2.6-3980 for AAP-46217 Pre-migration compliance for Chpt 4

---

downstream/assemblies/platform/assembly-aap-recovery.adoc
downstream/modules/platform/proc-aap-platform-ext-DB-restore.adoc
downstream/modules/platform/proc-aap-platform-pvc-restore.adoc

[AAP-50259](https://issues.redhat.com/browse/AAP-50259)
Backup and restore - PVCs support and restore to external DBs
[Draft](https://docs.google.com/document/d/1iA3OYBc4YVsb0K_hYk0rkuPu8raEcY6WZvdJxTcpoaI/edit?tab=t.0) - SME approved

AAP-50259 PVC edits

---

downstream/modules/platform/con-pod-specification-mods.adoc
downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
downstream/modules/platform/proc-customizing-pod-specs.adoc
downstream/modules/platform/proc-enable-pods-ref-images.adoc
downstream/modules/platform/proc-specify-nodes-job-execution.adoc
downstream/modules/platform/proc-troubleshoot-same-name.adoc
downstream/modules/platform/ref-assign-pods-to-nodes.adoc
downstream/modules/platform/ref-resource-types.adoc
downstream/modules/platform/ref-set-custom-pod-timeout.adoc

Doing a secondary sweep of OCP docs now that there was more AEM guidance provided

DITA fixes for ocp backup and performancde guides

---

downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
downstream/modules/platform/con-gw-manage-oauth2-external-users.adoc
downstream/modules/platform/proc-gw-enable-oauth2-external-users.adoc
downstream/modules/platform/proc-gw-oauth2-security-controls.adoc

Document External User OAuth2 Token Security Considerations
https://issues.redhat.com/browse/AAP-50313
Affects `central-auth`

Adding OAuth2 token creation chapter (#4012)

---

downstream/assemblies/platform/assembly-ag-controller-secret-handling.adoc
downstream/modules/platform/ref-controller-connection-security.adoc
downstream/modules/platform/ref-controller-external-access.adoc
downstream/modules/platform/ref-controller-managed-nodes.adoc

Configuring automation execution UI and modular compliance chapter 14
https://issues.redhat.com/browse/AAP-46734

DITA migration changes: CAG Ch14

---

downstream/assemblies/platform/assembly-ag-controller-secret-handling.adoc
downstream/modules/platform/ref-controller-connection-security.adoc
downstream/modules/platform/ref-controller-external-access.adoc
downstream/modules/platform/ref-controller-managed-nodes.adoc

Configuring automation execution UI and modular compliance chapter 14
https://issues.redhat.com/browse/AAP-46734

DITA migration changes: CAG Ch14 (#4022)

---

downstream/assemblies/devtools/assembly-rhdh-subscription-warnings.adoc
downstream/modules/devtools/con-devtools-requirements.adoc
downstream/modules/devtools/con-devtools-roles-collection-prerequisites.adoc
downstream/modules/devtools/proc-devtools-install-container.adoc
downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
downstream/modules/devtools/proc-rhdh-configure-devtools-server.adoc
downstream/modules/devtools/proc-rhdh-configure-showcase-location.adoc
downstream/modules/devtools/proc-rhdh-warning-invalid-aap-config.adoc
downstream/modules/devtools/proc-self-service-create-oauth-app.adoc
downstream/modules/devtools/ref-rhdh-dashboard.adoc

AAP-51375 Migration: Change devtools xrefs to links (#4025)

AAP-51375 Migration: Change devtools xrefs to links (#4025)

---

downstream/assemblies/platform/assembly-ag-controller-security-best-practices.adoc
downstream/modules/platform/con-controller-granting-access.adoc
downstream/modules/platform/con-controller-understand-architecture.adoc
downstream/modules/platform/ref-controller-available-resources.adoc
downstream/modules/platform/ref-controller-django-password-policies.adoc
downstream/modules/platform/ref-controller-existing-security.adoc

Configuring automation execution UI and modular compliance chapter 15
https://issues.redhat.com/browse/AAP-46735

DITA migration changes: CAG Ch15

---

downstream/archive/archived-assemblies/builder/assembly-definition-file-breakdown.adoc
downstream/archive/archived-assemblies/dev-guide/assembly-migrate-ansible-versions.adoc
downstream/archive/archived-assemblies/dev-guide/assembly-tools-components.adoc
downstream/archive/archived-assemblies/platform/assembly-supported-installation-scenarios.adoc
downstream/archive/archived-assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/archive/archived-modules/aap-hardening/ref-complex-patching-scenarios.adoc
downstream/archive/archived-modules/devtools/proc-create-molecule-scenario.adoc
downstream/archive/archived-modules/devtools/proc-rhdh-add-additional-scm.adoc
downstream/archive/archived-modules/devtools/ref-devtools-run-roles-collection.adoc
downstream/assemblies/devtools/assembly-devtools-create-roles-collection.adoc
downstream/assemblies/devtools/assembly-devtools-extension-set-language.adoc
downstream/assemblies/devtools/assembly-devtools-install.adoc
downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
downstream/assemblies/platform/assembly-controller-secret-management.adoc
downstream/assemblies/platform/assembly-platform-install-overview.adoc
downstream/modules/aap-hardening/con-platform-components.adoc
downstream/modules/devtools/proc-devtools-extension-run-ansible-navigator.adoc
downstream/modules/devtools/proc-devtools-extension-set-language.adoc
downstream/modules/devtools/proc-devtools-extension-set-persistant-file.adoc
downstream/modules/devtools/proc-devtools-extension-settings.adoc
downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
downstream/modules/devtools/proc-devtools-migrate-existing-roles-collection.adoc
downstream/modules/devtools/proc-rhdh-add-plugin-software-templates.adoc
downstream/modules/devtools/proc-rhdh-configure-pah-url.adoc
downstream/modules/devtools/proc-rhdh-create.adoc

[AAP-51447](https://issues.redhat.com/browse/AAP-51447)
DITA pre-migration tasks: RelatedLinks

DITA Readiness - Related Links

---

downstream/archive/archived-assemblies/builder/assembly-definition-file-breakdown.adoc
downstream/archive/archived-assemblies/dev-guide/assembly-migrate-ansible-versions.adoc
downstream/archive/archived-assemblies/dev-guide/assembly-tools-components.adoc
downstream/archive/archived-assemblies/platform/assembly-supported-installation-scenarios.adoc
downstream/archive/archived-assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
downstream/archive/archived-modules/aap-hardening/ref-complex-patching-scenarios.adoc
downstream/archive/archived-modules/devtools/proc-create-molecule-scenario.adoc
downstream/archive/archived-modules/devtools/proc-rhdh-add-additional-scm.adoc
downstream/archive/archived-modules/devtools/ref-devtools-run-roles-collection.adoc
downstream/assemblies/devtools/assembly-devtools-create-roles-collection.adoc
downstream/assemblies/devtools/assembly-devtools-extension-set-language.adoc
downstream/assemblies/devtools/assembly-devtools-install.adoc
downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
downstream/assemblies/platform/assembly-controller-secret-management.adoc
downstream/assemblies/platform/assembly-platform-install-overview.adoc
downstream/modules/aap-hardening/con-platform-components.adoc
downstream/modules/devtools/proc-devtools-extension-run-ansible-navigator.adoc
downstream/modules/devtools/proc-devtools-extension-set-language.adoc
downstream/modules/devtools/proc-devtools-extension-set-persistant-file.adoc
downstream/modules/devtools/proc-devtools-extension-settings.adoc
downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
downstream/modules/devtools/proc-devtools-migrate-existing-roles-collection.adoc
downstream/modules/devtools/proc-rhdh-add-plugin-software-templates.adoc
downstream/modules/devtools/proc-rhdh-configure-pah-url.adoc
downstream/modules/devtools/proc-rhdh-create.adoc

* DITA Readiness - DevTools
* PR suggestion

DITA Readiness - Related Links (#4029)

---

downstream/assemblies/platform/assembly-controller-glossary.adoc
downstream/modules/platform/ref-controller-activity-stream-schema.adoc
downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
downstream/modules/platform/ref-controller-credential-network.adoc
downstream/modules/platform/ref-controller-log-aggregators.adoc
downstream/modules/platform/ref-controller-old-job-history.adoc

Broken Link Report August 4 2025
https://issues.redhat.com/browse/AAP-51442

Correct links in controller guides

---

downstream/assemblies/platform/assembly-controller-glossary.adoc
downstream/modules/platform/ref-controller-activity-stream-schema.adoc
downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
downstream/modules/platform/ref-controller-credential-network.adoc
downstream/modules/platform/ref-controller-log-aggregators.adoc
downstream/modules/platform/ref-controller-old-job-history.adoc

Broken Link Report August 4 2025
https://issues.redhat.com/browse/AAP-51442

Correct links in controller guides (#4066)

---

downstream/assemblies/platform/assembly-controller-glossary.adoc
downstream/modules/platform/ref-controller-activity-stream-schema.adoc
downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
downstream/modules/platform/ref-controller-credential-network.adoc
downstream/modules/platform/ref-controller-log-aggregators.adoc
downstream/modules/platform/ref-controller-old-job-history.adoc

Broken Link Report August 4 2025
https://issues.redhat.com/browse/AAP-51442

Correct links for 2.6 controller docs

---

downstream/assemblies/platform/assembly-gw-mapping.adoc
downstream/modules/platform/con-gw-authenticator-map-examples.adoc
downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
downstream/modules/platform/con-gw-authenticator-map-types.adoc
downstream/modules/platform/con-gw-understanding-authenticator-mapping.adoc
downstream/modules/platform/proc-aap-enable-disable-auth.adoc
downstream/modules/platform/proc-controller-apps-create-tokens.adoc
downstream/modules/platform/proc-controller-organization-mapping.adoc
downstream/modules/platform/proc-controller-team-mapping.adoc
downstream/modules/platform/proc-gw-allow-mapping.adoc
downstream/modules/platform/proc-gw-role-mapping.adoc
downstream/modules/platform/ref-controller-token-session-management.adoc

* Editing access management files for DITA
Chapter 3 & 4 Access management and authentication
https://issues.redhat.com/browse/AAP-51507
* Completing DITA prep for chapters 3 and 4
* Fixing typo

Editing access management files for DITA (#4047)

---

downstream/assemblies/platform/assembly-controller-organizations.adoc
downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/assemblies/platform/assembly-controller-users.adoc
downstream/assemblies/platform/assembly-gw-managing-access.adoc
downstream/assemblies/platform/assembly-gw-roles.adoc
downstream/assemblies/platform/assembly-gw-settings.adoc
downstream/modules/platform/con-controller-access-organizations.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc
downstream/modules/platform/proc-controller-organization-notifications.adoc
downstream/modules/platform/proc-controller-user-permissions.adoc
downstream/modules/platform/proc-controller-user-roles.adoc
downstream/modules/platform/proc-gw-delete-roles.adoc
downstream/modules/platform/proc-gw-delete-team.adoc
downstream/modules/platform/proc-gw-edit-roles.adoc
downstream/modules/platform/proc-gw-editing-a-user.adoc
downstream/modules/platform/proc-gw-remove-roles-user.adoc
downstream/modules/platform/proc-gw-select-auth-type.adoc
downstream/modules/platform/proc-gw-team-access-resources.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc

Chapter 5,6 & 7 Access management and authentication
https://issues.redhat.com/browse/AAP-51509

Editing access management files for DITA

---

downstream/assemblies/platform/assembly-controller-organizations.adoc
downstream/assemblies/platform/assembly-controller-teams.adoc
downstream/assemblies/platform/assembly-controller-users.adoc
downstream/assemblies/platform/assembly-gw-managing-access.adoc
downstream/assemblies/platform/assembly-gw-roles.adoc
downstream/assemblies/platform/assembly-gw-settings.adoc
downstream/modules/platform/con-controller-access-organizations.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc
downstream/modules/platform/proc-controller-organization-notifications.adoc
downstream/modules/platform/proc-controller-user-permissions.adoc
downstream/modules/platform/proc-controller-user-roles.adoc
downstream/modules/platform/proc-gw-delete-roles.adoc
downstream/modules/platform/proc-gw-delete-team.adoc
downstream/modules/platform/proc-gw-edit-roles.adoc
downstream/modules/platform/proc-gw-editing-a-user.adoc
downstream/modules/platform/proc-gw-remove-roles-user.adoc
downstream/modules/platform/proc-gw-select-auth-type.adoc
downstream/modules/platform/proc-gw-team-access-resources.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc

* Editing access management files for DITA
Chapter 5,6 & 7 Access management and authentication
https://issues.redhat.com/browse/AAP-51509
Affects titles/central-auth
* Final DITA edits in PR

Editing access management files for DITA (#4074)

---

downstream/assemblies/platform/assembly-ag-controller-config.adoc
downstream/assemblies/platform/assembly-gw-settings.adoc
downstream/modules/platform/proc-controller-configure-system.adoc
downstream/modules/platform/proc-controller-set-up-azure.adoc
downstream/modules/platform/proc-gw-define-rules-triggers.adoc
downstream/modules/platform/proc-gw-settings-insights-settings.adoc
downstream/modules/platform/proc-settings-gw-additional-options.adoc
downstream/modules/platform/proc-settings-gw-authentication.adoc
downstream/modules/platform/proc-settings-gw-security-options.adoc

Changes to system settings
[Docs] Document CSRF Trusted Origins feature and how to configure vanity URL in AAP
https://issues.redhat.com/browse/AAP-47498

Changes to system and gateway settings

---

downstream/modules/platform/proc-edge-manager-build-bootc-image.adoc
downstream/modules/platform/proc-edge-manager-virt.adoc
downstream/modules/platform/proc-edge-manager-vmware.adoc

[Docs] Update Containerfile in RHEM doc
https://issues.redhat.com/browse/AAP-50654

Updating RHEM container image build

---

downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc
downstream/modules/platform/ref-controller-automation-analytics.adoc
downstream/modules/platform/ref-controller-cred-type-counts-json.adoc
downstream/modules/platform/ref-controller-data-collection-details.adoc

Configuring automation execution modular compliance chapter 18
https://issues.redhat.com/browse/AAP-46738

Editing controller files for DITA (#4124)

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/async-24-20250827.adoc

Release notes for the 2.4-20250827 async release

---

downstream/titles/release-notes/async/aap-25-20250827.adoc
downstream/titles/release-notes/master.adoc

Release notes for 2.5-20250807 async (#4149)

---

downstream/assemblies/platform/assembly-operator-troubleshoot.adoc
downstream/modules/platform/con-operator-understand-operator-logs.adoc
downstream/modules/platform/proc-operator-collect-diagnostic-data.adoc
downstream/modules/platform/proc-operator-config-log-verbosity.adoc
downstream/modules/platform/proc-operator-crd-config-parameters.adoc
downstream/modules/platform/proc-operator-debug-crashing-pods.adoc
downstream/modules/platform/proc-operator-inspect-k8s-resource.adoc
downstream/modules/platform/proc-operator-viewing-events.adoc
downstream/modules/platform/proc-viewing-operator-logs.adoc
downstream/modules/platform/ref-operator-core-aap-resources.adoc
downstream/modules/platform/ref-operator-standard-k8s-resources.adoc
downstream/titles/aap-operator-installation/master.adoc

[AAP-51782](https://issues.redhat.com/browse/AAP-51782)
Troubleshooting Documentation for AAP on OCP

New Assembly and modules for OCP (AAP-51782)

---

downstream/assemblies/platform/assembly-operator-troubleshoot.adoc
downstream/modules/platform/con-operator-understand-operator-logs.adoc
downstream/modules/platform/proc-operator-collect-diagnostic-data.adoc
downstream/modules/platform/proc-operator-config-log-verbosity.adoc
downstream/modules/platform/proc-operator-crd-config-parameters.adoc
downstream/modules/platform/proc-operator-debug-crashing-pods.adoc
downstream/modules/platform/proc-operator-inspect-k8s-resource.adoc
downstream/modules/platform/proc-operator-viewing-events.adoc
downstream/modules/platform/proc-viewing-operator-logs.adoc
downstream/modules/platform/ref-operator-core-aap-resources.adoc
downstream/modules/platform/ref-operator-standard-k8s-resources.adoc
downstream/titles/aap-operator-installation/master.adoc

* New Assembly and modules for OCP (AAP-51782)

New Assembly and modules for OCP (AAP-51782) (#4094)

---

downstream/assemblies/platform/assembly-operator-customize-aap.adoc
downstream/modules/platform/proc-operator-crd-config-parameters-ui.adoc
downstream/modules/platform/proc-operator-defining-nested-parameter.adoc
downstream/titles/aap-operator-installation/master.adoc

[[AAP-52126](https://issues.redhat.com/browse/AAP-52126)] Customizing your Automation Ansible Platform deployment 
One new assembly and three new modules.

AAP-52126 New assembly and modules

---

downstream/assemblies/platform/assembly-edge-manager-architecture.adoc
downstream/assemblies/platform/assembly-edge-manager-install.adoc
downstream/assemblies/platform/assembly-edge-manager-manage-apps.adoc
downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
downstream/assemblies/platform/assembly-edge-manager-provisioning-devices.adoc
downstream/assemblies/platform/assembly-edge-manager-troubleshooting.adoc
downstream/modules/platform/con-edge-manager-provisioning-openshift-virt.adoc
downstream/modules/platform/con-edge-manager-view-devices.adoc
downstream/modules/platform/proc-edge-manager-build-app-packages.adoc
downstream/modules/platform/proc-edge-manager-monitor-device-resources-cli.adoc
downstream/modules/platform/proc-edge-manager-provision-cloudinit-config.adoc
downstream/modules/platform/proc-edge-manager-provision-virt-create.adoc
downstream/modules/platform/proc-edge-manager-view-device-inventory-ui.adoc
downstream/modules/platform/ref-edge-manager-config-inline.adoc
downstream/modules/platform/ref-edge-manager-disruption-parameters.adoc
downstream/modules/platform/ref-edge-manager-fields-discovery.adoc
downstream/modules/platform/ref-edge-manager-rule-files.adoc
downstream/modules/platform/ref-edge-manager-specify-apps-inline.adoc
downstream/modules/platform/ref-edge-manager-success-threshold.adoc

* Editing RHEM files for DITA
Managing device fleets with the Red Hat Edge Manager
https://issues.redhat.com/browse/CCSINTL-472
* Further RHEM DITA update

Editing RHEM files for DITA (#4175)

---

downstream/assemblies/platform/assembly-controller-inventories.adoc
downstream/modules/platform/proc-controller-use-custom-inventory.adoc

[Docs] Adding Guide for Using Inventory Sync Plugins from Multiple Collections
https://issues.redhat.com/browse/AAP-43019

Add procedure to use custom inventory plugin

---

downstream/assemblies/platform/assembly-controller-inventories.adoc
downstream/modules/platform/proc-controller-use-custom-inventory.adoc

* Add procedure to use custom inventory plugin
[Docs] Adding Guide for Using Inventory Sync Plugins from Multiple Collections
https://issues.redhat.com/browse/AAP-43019
* Add procedure to use custom inventory plugin
Correction
[Docs] Adding Guide for Using Inventory Sync Plugins from Multiple Collections
https://issues.redhat.com/browse/AAP-43019

Add procedure to use custom inventory plugin (#4178)

---

downstream/assemblies/eda/assembly-eda-decision-environments.adoc
downstream/modules/eda/ref-eda-controller-install-builder.adoc

Prepped [Chapter 5. Decision environments](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-decision-environments) in the Using automation decisions guide for migration compliance.

Backport-2.6-4171 for AAP-46218 Pre-migration work EDA user guide, Chapt 5

---

lightspeed/assemblies/assembly_troubleshooting-lightspeed.adoc
lightspeed/modules/con_overview-lightspeed-onpremise.adoc
lightspeed/modules/proc_create-connection-secrets.adoc
lightspeed/modules/proc_use-rest-api.adoc
lightspeed/modules/ref_troubleshooting-lightspeed-onpremise-config.adoc

This PR addresses the onprem doc updates as part of JIRA https://issues.redhat.com/browse/AAP-51163.
Changes made:
- Miscellaneous updates to the Lightspeed onprem section.
- Added the 'troubleshooting onprem deployment errors' back in (it was pending tech. review, the content was reviewed before. I unpublished it bcoz the errors + workarounds were yet to be verified by SME).

AAP-51163-onprem: Miscellaneous updates to Lightspeed onprem docs

---

downstream/assemblies/playbooks/assembly-intro-to-playbooks.adoc
downstream/assemblies/playbooks/assembly-networking-playbook.adoc
downstream/modules/playbooks/proc-build-an-inventory.adoc
downstream/modules/playbooks/proc-creating-a-playbook.adoc
downstream/modules/playbooks/proc-run-ansible-network-playbook.adoc
downstream/modules/playbooks/proc-starting-automation.adoc
downstream/modules/playbooks/ref-create-variables.adoc
downstream/modules/playbooks/ref-how-do-playbooks-work.adoc
downstream/modules/playbooks/ref-how-to-use-ansible-playbooks.adoc
downstream/modules/playbooks/ref-playbook-execution.adoc
downstream/modules/playbooks/ref-playbooks-yaml-ini.adoc
downstream/modules/playbooks/ref-tips-build-inventory.adoc
downstream/titles/playbooks/playbooks-getting-started/master.adoc

DITA pre-migration tasks. Getting  started with Playbooks
https://issues.redhat.com/browse/AAP-51374

DITA migration changes: Playbooks Getting Started

---

downstream/assemblies/playbooks/assembly-intro-to-playbooks.adoc
downstream/assemblies/playbooks/assembly-networking-playbook.adoc
downstream/modules/playbooks/proc-build-an-inventory.adoc
downstream/modules/playbooks/proc-creating-a-playbook.adoc
downstream/modules/playbooks/proc-run-ansible-network-playbook.adoc
downstream/modules/playbooks/proc-starting-automation.adoc
downstream/modules/playbooks/ref-create-variables.adoc
downstream/modules/playbooks/ref-how-do-playbooks-work.adoc
downstream/modules/playbooks/ref-how-to-use-ansible-playbooks.adoc
downstream/modules/playbooks/ref-playbook-execution.adoc
downstream/modules/playbooks/ref-playbooks-yaml-ini.adoc
downstream/modules/playbooks/ref-tips-build-inventory.adoc
downstream/titles/playbooks/playbooks-getting-started/master.adoc

DITA pre-migration tasks. Getting  started with Playbooks
https://issues.redhat.com/browse/AAP-51374

DITA migration changes: Playbooks Getting Started (#4193)

---

downstream/modules/platform/ref-controller-credential-terraform.adoc

https://issues.redhat.com/browse/AAP-50894
https://github.com/ansible/aap-docs/pull/4167

Backport 2.6 4167 for AAP-50894: Clarify Terraform Backend Config in COntroller User Guide

---

downstream/assemblies/platform/assembly-upgrade-faqs.adoc

[AAP-52550](https://issues.redhat.com/browse/AAP-52550) - FAQ for upgrade-related product docs info
Converting SME approved draft into asciidoc:
https://docs.google.com/document/d/14AzkjXpzQlNY9HPmsrHuJ4YRsiHp2cjtFtdZaHUMQXw/edit?tab=t.nbr52rvbz3t5

AAP-52550 FAQ content added to planning your upgrade

---

downstream/assemblies/terraform-aap/assembly-terraform-migrating-from-community.adoc
downstream/attributes/attributes.adoc
downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc

* Upate wording for better accuracy in COmmunity Migration section
* Fixed links
* more edits
* Removed note
* Fixed punctuation
* https://issues.redhat.com/browse/AAP-51980

Backport for 2.6 - AAP 51980: Clarifications for migrating from community to TFE (#4166)

---

downstream/modules/platform/proc-create-chatbot-config-secret.adoc

This PR backports PR #4192 from main repo to AAP 2.5 repo.

Backport PR #4192 from main to AAP 2.5 branch

---

downstream/modules/platform/proc-create-chatbot-config-secret.adoc

This PR backports Pr #4192 from main to AAP 2.6 branch.

Backport PR4192 from main to AAP 2.6 branch

---

downstream/assemblies/terraform-aap/assembly-terraform-product.adoc
downstream/assemblies/vault-aap/assembly-vault-product.adoc
downstream/attributes/attributes.adoc
downstream/titles/terraform-aap/terraform-aap-getting-started/docinfo.xml
downstream/titles/terraform-aap/terraform-aap-getting-started/master.adoc
downstream/titles/terraform-aap/terraform-aap-getting-started/vault-aap

https://issues.redhat.com/browse/AAP-52745
Changing title and TOC of guide to accommodate other Hashicorp products. (Future PRs will add the new feature/product content.)

AAP-52745: Updating TOC and title of Getting started with Terraform and AAP guide

---

downstream/aap-common/gplv3-license.adoc

Correction
Correct build error in Playbooks Guide
https://issues.redhat.com/browse/AAP-52852

Correct build error in Playbook guide

---

downstream/modules/aap-hardening/con-deployment-methods.adoc

Update the hardening and compliance guide to properly reflect the state of RPM based installs
https://issues.redhat.com/browse/AAP-52499

Correct statement on RPM installer.

---

downstream/modules/platform/proc-aap-platform-pvc-restore.adoc

* Fixing broken link in OCP backup guide
* Typo

Fixing broken link in OCP backup guide (#4232)

---

stories/topics/con-saas-backup-and-diaster-recovery.adoc

Fixing a minor typo in the saas guide

Fixing typo in Saas backup table

---

downstream/assemblies/platform/assembly-upgrade-support-matrix.adoc
downstream/modules/platform/ref-upgrade-rhel-support.adoc
downstream/modules/platform/ref-upgrade-scenarios-container.adoc
downstream/modules/platform/ref-upgrade-scenarios-openshift.adoc
downstream/modules/platform/ref-upgrade-scenarios-rpm.adoc

Affected title: titles/planning-your-upgrade
Support matrix for upgrade scenarios - AsciiDoc conversion
https://issues.redhat.com/browse/AAP-52670

AsciiDoc conversion for planning your upgrade

---

downstream/assemblies/platform/assembly-metrics-utility.adoc
downstream/modules/platform/con-controller-metrics-utility-containerized.adoc
downstream/modules/platform/con-controller-metrics-utility-ocp.adoc
downstream/modules/platform/proc-confguring-cron-jobs.adoc
downstream/modules/platform/proc-configure-a-config-map.adoc
downstream/modules/platform/proc-controller-metrics-utility-rhel.adoc
downstream/modules/platform/proc-host-scripts-directories.adoc
downstream/modules/platform/proc-making-scripts-executable.adoc

[AAP-52254](https://issues.redhat.com/browse/AAP-52254)
Files modified: 
- proc-controller-metrics-utility-rhel.adoc
- assembly-metrics-utility.adoc
- controller-metrics-utility-containerized.adoc
- controller-metrics-utility-ocp.adoc
- proc-confguring-cron-jobs.adoc
- proc-configure-a-config-map.adoc
- proc-host-scripts-directories.adoc
- proc-making-scripts-executable.adoc

AAP-52254 2.6 metrics-utility updates

---

downstream/modules/platform/proc-attaching-subscriptions.adoc
downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
downstream/snippets/cont-tested-system-config.adoc

Backports #4243 from main to 2.6
Misc updates to Containerized installation guide
Minor Containerized Doc Issues
https://issues.redhat.com/browse/AAP-51917

2.6 Update Containerized installation (#4243)

---

downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc
downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
downstream/modules/platform/ref-eda-system-requirements.adoc
downstream/modules/platform/ref-postgresql-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-53263. 
Changes made:
- Asciidoc conversion for RPM 2.6 install guide updates.

AAP-53263: 1st set of Asciidoc conversion

---

downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc
downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
downstream/modules/platform/ref-eda-system-requirements.adoc
downstream/modules/platform/ref-postgresql-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR backports PR #4293 from main to AAP 2.6 branch. 
Changes made:
Asciidoc conversion of RPM install guide 2.6

Backport PR #4293 from main to AAP 2.6 branch. 

---

downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
downstream/modules/platform/con-gw-configure-auth-timeouts.adoc
downstream/modules/platform/proc-aap-enable-disable-auth.adoc
downstream/modules/platform/proc-gw-setting-timeout-values.adoc

Document password based auth timeout recommendation
https://issues.redhat.com/browse/AAP-48999

Adding authenticator timeouts section

---

downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/con-aap-upgrade-planning.adoc
downstream/modules/platform/con-aap-upgrades.adoc
downstream/modules/platform/con-upgrade-controller-hub-eda-unified-ui.adoc
downstream/modules/platform/proc-choosing-obtaining-installer.adoc
downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-services.adoc
downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-53267. 
Changes made:
- Asciidoc conversion for RPM 2.6 upgrade guide updates.
- @jself-sudoku's update (JIRA https://issues.redhat.com/browse/AAP-50802).

AAP-53267: Asciidoc conversion of RPM upgrade guide 2.6

---

downstream/attributes/attributes.adoc
downstream/modules/platform/ref-upgrade-scenarios-container.adoc
downstream/modules/platform/ref-upgrade-scenarios-openshift.adoc
downstream/modules/platform/ref-upgrade-scenarios-rpm.adoc

Affected title: `planning-your-upgrade`
- The usage of inline links was confirmed with PM.
- Links included to different AAP product versions is intentional.
Update the Support matrix for upgrade scenarios "Process" column to include inline links to the relevant documentation
https://issues.redhat.com/browse/AAP-53516

Update Support matrix for upgrade scenarios

---

downstream/assemblies/terraform-aap/assembly-terraform-introduction.adoc
downstream/assemblies/vault-aap/assembly-vault-authenticating.adoc
downstream/assemblies/vault-aap/assembly-vault-introduction.adoc
downstream/assemblies/vault-aap/assembly-vault-migrating-from-community.adoc
downstream/assemblies/vault-aap/vault-aap
downstream/attributes/attributes.adoc
downstream/modules/vault-aap/con-vault-authentication-architecture.adoc
downstream/modules/vault-aap/con-vault-intro.adoc
downstream/modules/vault-aap/con-vault-migration-examples-secret-get-lookup.adoc
downstream/modules/vault-aap/con-vault-migration-examples-secret-module.adoc
downstream/modules/vault-aap/proc-vault-configuring-kv2-secret-get-lookup.adoc
downstream/modules/vault-aap/proc-vault-configuring-kv2-secret.adoc
downstream/modules/vault-aap/proc-vault-creating-credential-type.adoc
downstream/modules/vault-aap/proc-vault-creating-custom-credential.adoc
downstream/titles/terraform-aap/terraform-aap-getting-started/master.adoc
vault-aap

AAP-50389-FIXED: Add Vault content to HashiCorp Getting Started guide #4242 
Also backported #4269

2.6 AAP-50389-FIXED: Add Vault content to HashiCorp Getting Started guide

---

downstream/modules/eda/proc-eda-set-up-new-project.adoc

Correction to the Source control URL description and 1 additional change to the Source control credential field for setting up Projects.

Backport-2.5-4087 for AAP-51751 Correct part of the description for Source Control URL field

---

downstream/assemblies/platform/assembly-gw-mapping.adoc
downstream/modules/platform/con-gw-pluggable-authentication.adoc
downstream/modules/platform/proc-gw-using-jinja-syntax-auth-maps.adoc
downstream/modules/platform/proc-settings-gw-additional-options.adoc
downstream/modules/platform/ref-upgrade-authentication-movement-2.4-to-2.6.adoc
downstream/modules/platform/ref-upgrade-manage-org-auth-setting.adoc
downstream/titles/planning-your-upgrade/master.adoc

The following Jiras are covering these updates:
* https://issues.redhat.com/browse/AAP-52506
* https://issues.redhat.com/browse/AAP-53438
Affects:
* `titles/central-auth`
* `titles/planning-your-upgrade`

2.6 Access Management asciidoc updates

---

downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
downstream/assemblies/platform/assembly-controller-api-search.adoc
downstream/assemblies/platform/assembly-controller-api-sorting.adoc
downstream/modules/platform/con-controller-api-oauth2-token.adoc
downstream/modules/platform/proc-controller-api-browsing-api.adoc
downstream/modules/platform/proc-controller-api-enable-users-oauth.adoc
downstream/modules/platform/proc-controller-api-filtering.adoc
downstream/modules/platform/proc-controller-api-search.adoc
downstream/modules/platform/proc-controller-api-sorting.adoc
downstream/modules/platform/proc-controller-api-using-pagination.adoc
downstream/modules/platform/ref-controller-api-config-settings.adoc
downstream/modules/platform/ref-controller-api-field-lookups.adoc

* Updating controller API examples
Docs - 2.5 API Examples Outdated
https://issues.redhat.com/browse/AAP-45587
* Further API updates
* Last edits to API guide
* Editing OAuth 2 API commands

Updating controller API examples (#4230)

---

downstream/modules/platform/proc-controller-add-organization-user.adoc
downstream/modules/platform/proc-controller-creating-a-team.adoc
downstream/modules/platform/proc-controller-creating-a-user.adoc
downstream/modules/platform/proc-gw-add-admin-organization.adoc
downstream/modules/platform/proc-gw-add-admin-team.adoc
downstream/modules/platform/proc-gw-add-team-organization.adoc
downstream/modules/platform/proc-gw-delete-team.adoc
downstream/modules/platform/proc-gw-editing-a-user.adoc
downstream/modules/platform/proc-gw-team-add-user.adoc
downstream/modules/platform/proc-gw-users-list-view.adoc

This work is being tracked in [AAP-52315](https://issues.redhat.com/browse/AAP-52315).

AAP-52315: updates links in RBAC content

---

downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc

https://issues.redhat.com/browse/AAP-53692

Tested deployment models - Operator topologies

---

downstream/titles/release-notes/master.adoc
downstream/titles/release-notes/topics/async-24-20250922.adoc

https://issues.redhat.com/browse/AAP-52956

2.4 Update 2.4 async RNs

---

downstream/assemblies/platform/assembly-upgrade-overview.adoc
downstream/modules/platform/con-aap-upgrade-overview.adoc

Asciidoc conversion
https://issues.redhat.com/browse/AAP-53954

AAP-53954: Asciidoc conversion of Overview content for Planning your Upgrade guide

---

downstream/modules/platform/con-aap-upgrade-overview.adoc

Backport for #4377 
https://issues.redhat.com/browse/AAP-53954

Added description and links to last row (#4377)

---

downstream/modules/topologies/ref-ocp-a-env-a.adoc
downstream/modules/topologies/ref-ocp-b-env-a.adoc

* Add admonitions to explain database use
Inconsistent and misleading infos in docs
https://issues.redhat.com/browse/AAP-52498
* Add admonitions to explain database use.
Minor correction
Inconsistent and misleading infos in docs
https://issues.redhat.com/browse/AAP-52498

Add admonitions to explain database use (#4390)

---

downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc
downstream/modules/platform/proc-configure-custom-mcp-server-chatbot.adoc
downstream/modules/platform/proc-create-chatbot-config-secret.adoc
downstream/modules/platform/proc-update-aap-operator-yaml-chatbot.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-51490. Updates are being made in incremental stages. 
Changes made:
- Asciidoc conversion of Ansible Lightspeed chatbot docs for AAP 2.6 release
- Latest changes as of 09/23: Added content for ALIA 2.6 and MCP server integration tech preview.

AAP-51490: AAP-51490: Asciidoc conversion of Ansible Lightspeed chatbot docs for AAP 2.6 release

---

downstream/assemblies/devtools/assembly-rhdh-intro.adoc
downstream/assemblies/devtools/assembly-rhdh-ocp-required-installation.adoc
downstream/attributes/attributes.adoc
downstream/modules/devtools/proc-devtools-publish-roles-collection-pah.adoc
downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
downstream/modules/devtools/proc-rhdh-download-plugins.adoc
downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
downstream/modules/devtools/proc-self-service-download-tar.adoc
downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc
downstream/modules/devtools/ref-rhdh-full-helm-chart-ansible-plugins.adoc
downstream/titles/aap-plugin-rhdh-install/master.adoc

AAP-50437 Remove ansible-plugin-backstage-rhaap-backend-dynamic.tgz

AAP-50437 Remove ansible-plugin-backstage-rhaap-backend-dynamic.tgz

---

downstream/assemblies/eda/assembly-eda-rulebook-troubleshooting.adoc
downstream/modules/eda/proc-eda-activation-keeps-restarting.adoc
downstream/modules/eda/proc-eda-activation-stuck-pending.adoc
downstream/modules/eda/proc-eda-cannot-connect-to-controller.adoc
downstream/modules/eda/proc-eda-event-streams-not-sending-events.adoc

Prepped [Chapter 8. Rulebook activations troubleshooting](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-rulebook-troubleshooting) in the Using automation decisions guide for migration compliance.

Backport-2.6-4413 for AAP-46222 Pre-migration prep for Chapter 8, Using automation decisions

---

downstream/modules/platform/con-aap-upgrade-overview.adoc

https://issues.redhat.com/browse/AAP-54344

AAP-54344: Add more content to Planning Your Upgrade overview content

---

downstream/modules/platform/con-aap-upgrade-overview.adoc

https://issues.redhat.com/browse/AAP-54344
Backport for #4416

Backport 2.6 for 4416 (Updates to Planning Guide Overview)

---

downstream/titles/release-notes/topics/aap-26.adoc

Release Notes Draft: https://docs.google.com/document/d/1agwmsLP7nC6cGAf2pknjxJhT4JJxOR9VF-YA7k6bK7M/edit?tab=t.0

Added new edits from draft. (#4414)

---

downstream/assemblies/platform/assembly-configure-egress-proxy.adoc
downstream/modules/platform/proc-controller-scm-ssh-proxy-config.adoc
downstream/titles/aap-operations-guide/master.adoc

* Add scm configure info
Add procedure to configure SCM Project Sync Using SSH through a proxy
https://issues.redhat.com/browse/AAP-54408
* Add SCM configure info
Corrections
Add procedure to configure SCM Project Sync Using SSH through a proxy
https://issues.redhat.com/browse/AAP-54408

Add scm configure info (#4435)

---

downstream/titles/hub/managing-content/master.adoc

- adds spaces btwn include statements in the hub master.adoc file
This work is being tracked in [AAP-49578](https://issues.redhat.com/browse/AAP-49578)

AAP-49578: DITA migration formatting updates

---

downstream/titles/release-notes/topics/aap-26-removed-features.adoc
downstream/titles/release-notes/topics/aap-26.adoc
downstream/titles/release-notes/topics/platform-intro.adoc

Release Notes Draft: https://docs.google.com/document/d/1agwmsLP7nC6cGAf2pknjxJhT4JJxOR9VF-YA7k6bK7M/edit?tab=t.0
* Small edits + Updated platform-intro file.
* Removed rest of platform-intro file.
* Fixing errors
* Edits
* Minor edits
* Minor edits

R.N. - Small edits + Updated platform-intro file. (#4436)

---

downstream/titles/ansible-workspaces/docinfo.xml
downstream/titles/ansible-workspaces/master.adoc

Update title for /title/ansible-workspaces doc

2.6 AAP-49869b Update Ansible Workspaces title (#4462)

---

downstream/assemblies/eda/assembly-simplified-event-routing.adoc
downstream/modules/eda/con-event-streams.adoc
downstream/modules/eda/proc-eda-check-rule-audit-event-stream.adoc
downstream/modules/eda/proc-eda-config-remote-sys-to-events.adoc
downstream/modules/eda/proc-eda-create-event-stream-credential.adoc
downstream/modules/eda/proc-eda-create-event-stream.adoc
downstream/modules/eda/proc-eda-replace-sources-with-event-streams.adoc
downstream/modules/eda/proc-eda-resend-webhook-data-event-streams.adoc
downstream/modules/eda/proc-eda-verify-event-streams-work.adoc

Prepped [Chapter 10. Simplified event routing](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/simplified-event-routing) in the Using automation decisions guide for migration compliance.

AAP-46224 Pre-migration work EDA user guide, Chapter 10

---

downstream/modules/platform/proc-controller-scm-ssh-proxy-config.adoc

[Docs] Missing "Renewing and Changing the SSL Certificate" section
https://issues.redhat.com/browse/AAP-54522

Formatting updates AsciiDoc/DITA

---

downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc
downstream/modules/platform/con-using-chatbot.adoc
downstream/modules/platform/proc-create-chatbot-config-secret.adoc
downstream/modules/platform/proc-update-aap-operator-yaml-chatbot.adoc

This PR backports PR #4455 from main to AAP 2.6 repo.

Backport PR #4455 from main to AAP 2.6 repo

---

downstream/modules/platform/ref-container-resource-requirements.adoc

JIRA: https://issues.redhat.com/browse/AAP-54284

Replaced broken link with new link.

---

downstream/titles/self-service-install/docinfo.xml
downstream/titles/self-service-install/master.adoc
downstream/titles/self-service-using/docinfo.xml
downstream/titles/self-service-using/master.adoc

2.5 Update titles for Self-service automation portal (#4302)

---

downstream/assemblies/platform/assembly-upgrade-faqs.adoc

Just making a change now the section exists.

Post release update for planning your upgrade guide

---

downstream/assemblies/platform/assembly-upgrade-faqs.adoc

* Post release update for planning your upgrade guide
* PR suggestion

Post release update for planning your upgrade guide (#4508)

---

downstream/assemblies/platform/assembly-operator-configure-gateway.adoc
downstream/modules/platform/ref-operator-aap-faq.adoc
downstream/modules/platform/ref-operator-crd-customize.adoc

AAP-54924 edits (#4534)

---

downstream/assemblies/eda/assembly-eda-logging-strategy.adoc
downstream/modules/eda/ref-eda-logging-samples.adoc

Prepped [Chapter 13. Event-Driven Ansible logging strategy](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/using_automation_decisions/eda-logging-strategy) in the Using automation decisions guide for migration compliance.

AAP-46228 Pre-migration work EDA user guide, Chapter 13

---

downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc

https://issues.redhat.com/browse/AAP-55092
Xrefs were broken due to a funky TOC change. They work now in the preview.

AAP 55092: Fix Xrefs in GS with Hasi/AAP guide

---

downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc

* Fixing xrefs
* Another try a fixing Hashi links
* More experimenting to fix xrefs in GS Hashi guide
#4566

Backport 2.5: AAP 55092: Fix Xrefs in GS with Hasi/AAP guide (#4566)

---

downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc

* Fixing xrefs
* Another try a fixing Hashi links
* More experimenting to fix xrefs in GS Hashi guide
#4566

Backport 2.6: AAP 55092: Fix Xrefs in GS with Hasi/AAP guide (#4566)

---

downstream/modules/automation-dashboard/proc-installing-automation-dashboard.adoc
downstream/modules/automation-dashboard/proc-integrating-automation-dashboard.adoc

2.4 backport of https://github.com/ansible/aap-docs/pull/4581

AAP-55160 updated playbook (#4581)

---

downstream/modules/platform/con-install-mesh.adoc
downstream/modules/platform/proc-editing-inventory-file.adoc
downstream/modules/platform/proc-running-setup-script.adoc

* Add containerized install to VM-mesh description
Deprecated RPM installer doc reference
https://issues.redhat.com/browse/AAP-55065
* Add containerized install to VM description
Deprecated RPM installer doc reference
https://issues.redhat.com/browse/AAP-55065
* Add containerized install to VM-mesh description
Deprecated RPM installer doc reference
https://issues.redhat.com/browse/AAP-55065

Add containerized install to VM-mesh description (#4575)

---

downstream/assemblies/devtools/assembly-self-service-about.adoc
downstream/modules/devtools/con-self-service-customize-template.adoc
downstream/modules/devtools/proc-rhdh-create.adoc
downstream/modules/devtools/proc-self-service-add-template.adoc
downstream/modules/devtools/proc-self-service-set-up-rbac.adoc
downstream/modules/devtools/ref-self-service-interactive-demo.adoc

Affects `titles/self-service-install/`

Self-service: Clarify RBAC

---

downstream/assemblies/devtools/assembly-self-service-about.adoc
downstream/modules/devtools/con-self-service-customize-template.adoc
downstream/modules/devtools/proc-rhdh-create.adoc
downstream/modules/devtools/proc-self-service-add-template.adoc
downstream/modules/devtools/proc-self-service-set-up-rbac.adoc
downstream/modules/devtools/ref-self-service-interactive-demo.adoc

Affects `titles/self-service-install/`

2.6 Self-service: Clarify RBAC (#4533)

---

downstream/attributes/attributes.adoc
downstream/titles/release-notes/topics/aap-25.adoc
downstream/titles/release-notes/topics/tech-preview.adoc

2.5 release notes - update portal name

2.5 release notes - update portal name

---

downstream/modules/platform/proc-operator-upgrade.adoc

JIRA: https://issues.redhat.com/browse/AAP-54930

Clearing confusion.

---

downstream/titles/release-notes/topics/aap-26.adoc

Fixed 2.5 links for 2.6 Upgrade_Migration section

---

downstream/titles/release-notes/topics/aap-26.adoc

Fixed 2.5 links for 2.6 Upgrade_Migration section (#4604)

---

downstream/modules/platform/con-controller-benefits-fact-caching.adoc

Outdated smart inventory reference
https://issues.redhat.com/browse/AAP-55067

Remove smart inventory reference (#4610)

---

downstream/modules/platform/proc-operator-upgrade.adoc

https://issues.redhat.com/browse/AAP-54930

Backport - accept incoming changes - AAP-54930

---

downstream/modules/platform/proc-operator-upgrade.adoc

JIRA: https://issues.redhat.com/browse/AAP-54930

Backport - Clearing confusion. (#4599) -AAP-54930

---

downstream/assemblies/platform/assembly-controller-ee-setup-reference.adoc
downstream/modules/platform/ref-controller-config-options.adoc
downstream/modules/platform/ref-controller-ee-configuration-options.adoc

Clarify EE package manager
https://issues.redhat.com/browse/AAP-55068

Correct values

---

downstream/modules/aap-migration/con-artifact-structure.adoc
downstream/modules/aap-migration/con-containerized-to-ocp-prerequisites.adoc
downstream/modules/aap-migration/con-manifest-file.adoc
downstream/modules/aap-migration/con-rpm-to-containerized-prerequisites.adoc
downstream/modules/aap-migration/con-rpm-to-ocp-prerequisites.adoc
downstream/modules/aap-migration/con-secrets-file.adoc
downstream/modules/aap-migration/proc-containerized-post-import.adoc
downstream/modules/aap-migration/proc-containerized-source-environment-export.adoc
downstream/modules/aap-migration/proc-containerized-target-import.adoc
downstream/modules/aap-migration/proc-containerized-target-prep.adoc
downstream/modules/aap-migration/proc-containerized-validation.adoc
downstream/modules/aap-migration/proc-managed-post-import.adoc
downstream/modules/aap-migration/proc-ocp-target-import.adoc
downstream/modules/aap-migration/proc-rpm-source-environment-export.adoc
downstream/modules/aap-migration/ref-migration-artifact-checklist.adoc

Backports #4618 from main to 2.6
Audit the migration guide to ensure no code snippet typos
https://issues.redhat.com/browse/AAP-55488

2.6 Updates the Ansible Automation Platform migration guide (#4618)

---

downstream/assemblies/platform/assembly-controller-ee-setup-reference.adoc
downstream/modules/platform/ref-controller-config-options.adoc
downstream/modules/platform/ref-controller-ee-configuration-options.adoc

Clarify EE package manager
https://issues.redhat.com/browse/AAP-55068

Correct values (#4616)

---

downstream/modules/builder/proc-installing-builder.adoc

JIRA: https://issues.redhat.com/browse/AAP-55074

Backport - Editing attribute to view. (#4635)

---

downstream/modules/builder/proc-installing-builder.adoc

JIRA: https://issues.redhat.com/browse/AAP-55074

AAP-55074 - Changed the attribute to 2.6

---

downstream/titles/release-notes/topics/aap-25-known-issues.adoc

Add 2 known issue bugs to 2.5 release notes for self-service automation portal

2.5 release notes: add portal known issues

---

downstream/titles/release-notes/topics/aap-26-known-issues.adoc

2.6 Release notes: add issues for self-service (#4601)

2.6 Release notes: add issues for self-service (#4601)
