titles/aap-on-azure/aap-on-azure.asciidoc
Add preface for Ansible on Azure guide
=> Remove lorem ipsum line from Ansible on Azure guide preface

attributes/attributes.adoc
Added hub and content attributes
=> Updated attributes to match Ansible branch

stories/topics/ref-aap-aws-automation-performance.adoc
=> Corrections to AWS documentation

attributes/attributes.adoc
Added attributes using the 'from' naming convention
=> Add new cloud attributes

stories/topics/ref-aap-aws-add-extension-nodes.adoc
Signed-off-by: Zack Kayyali <zkayyali812@gmail.com>
=> Remove hardcode AMI name

stories/assembly-aap-aws-extension-nodes.adoc, stories/topics/proc-aap-aws-add-extension-nodes.adoc
Changed ref topic to proc. Reformatted procedure.
=> Changes to extension nodes chapter

stories/assembly-aap-gcp-additional-configs.adoc, stories/assembly-aap-gcp-monitoring-logging.adoc, stories/assembly-aap-gcp-networking-access.adoc, stories/assembly-aap-gcp-support.adoc, stories/topics/con-aap-gcp-network-peering-options.adoc, stories/topics/proc-aap-gcp-additional-configs-update-admin-password.adoc, stories/topics/proc-aap-gcp-application-deploy.adoc, stories/topics/proc-aap-gcp-deploying-extension-nodes.adoc, stories/topics/proc-aap-gcp-extension-nodes.adoc, stories/topics/proc-aap-gcp-external-load-balancer.adoc, stories/topics/proc-aap-gcp-marketplace.adoc, stories/topics/proc-aap-gcp-secure-communication-SSL.adoc, stories/topics/proc-aap-gcp-vpc-peering.adoc, stories/topics/ref-aap-gcp-ansible-podman-config.adoc, stories/topics/ref-aap-gcp-automation-performance.adoc, stories/topics/ref-aap-gcp-configure-google-cloud-ops-agent.adoc, stories/topics/ref-aap-gcp-networking-options.adoc, stories/topics/ref-aap-gcp-security-considerations.adoc, stories/topics/ref-aap-gcp-vm-image-packages.adoc
=> Final changes to aap-on-gcp doc

README.adoc
Signed-off-by: Chris Ahl <cahl@redhat.com>
=> Add draft link for GCP

README.adoc, stories/topics/proc-aap-gcp-external-load-balancer.adoc
Signed-off-by: Leena Jawale <ljawale@redhat.com>
issue: https://issues.redhat.com/browse/AAP-7471
=> fix gcp ext lb

stories/assembly-aap-aws-additional-configs.adoc, stories/assembly-aap-aws-automation-workloads.adoc, stories/assembly-aap-aws-backup-and-recovery.adoc, stories/assembly-aap-aws-install.adoc, stories/assembly-aap-aws-intro.adoc, stories/assembly-aap-aws-support.adoc, stories/topics/con-aap-aws-access-application.adoc, stories/topics/con-aap-aws-deployment-scaling.adoc, stories/topics/con-aap-aws-network-peering-options.adoc, stories/topics/con-aws-application-architecture.adoc, stories/topics/proc-aap-aws-add-extension-nodes.adoc, stories/topics/proc-aap-aws-backup-and-recovery.adoc, stories/topics/proc-aap-aws-configure-route-tables.adoc, stories/topics/proc-aap-aws-configure-security-network.adoc, stories/topics/proc-aap-aws-routing-to-vpcs.adoc, stories/topics/proc-aap-aws-traffic-to-vpc.adoc, stories/topics/proc-aap-aws-uninstall.adoc, stories/topics/proc-aap-aws-vpc-peering.adoc, stories/topics/proc-aws-create-ec2-pair.adoc, stories/topics/proc-aws-marketplace.adoc, stories/topics/ref-aap-aws-additional-configs-update-admin-password.adoc, stories/topics/ref-aap-aws-additional-configs-update-rds-password.adoc, stories/topics/ref-aap-aws-automation-performance.adoc, stories/topics/ref-aap-aws-install-prerequisites.adoc, stories/topics/ref-aap-aws-transit-gateway.adoc, titles/aap-on-aws/aap-on-aws.asciidoc
Updated attribute and did some tidying up.
=> Update attribute used for AAP from AWS marketplace

stories/topics/con-aap-gcp-application-architecture.adoc
These are a couple edits from the google doc that didn't make it into the GitHub repo.
=> change egress to ingress in GCP arch description

stories/topics/proc-aws-marketplace.adoc
Adding context for accepting certain virtual machine counts which is a required step for accepting a private offer properly.
=> Added updates for VM context when accepting private offers

stories/topics/proc-aap-gcp-application-deploy.adoc, stories/topics/ref-aap-gcp-networking-options.adoc
Minor corrections. Resize icon.
Please enter the commit message for your changes. Lines starting
=> Resize icon and modify GCP Chapter 2

stories/topics/proc-aap-gcp-external-load-balancer.adoc, stories/topics/proc-aap-gcp-vpc-peering.adoc
Tidied up procedures and minor corrections
=> Corrections and tweaks to Chapter 3

stories/topics/proc-aap-gcp-marketplace.adoc
Add text to identify which option to choose
=> Amend initial instructions

aap-common/external-site-disclaimer.adoc, titles/aap-on-aws/stories.adoc, titles/aap-on-gcp/stories.adoc
Add legal disclaimer for content of external sites.
=> Added disclaimer

stories/topics/proc-azure-update-route-tables.adoc
Azure: Add DNS blocking info in network peering section
=> Azure: Add DNS blocking info in network peering section

stories/assembly-aap-gcp-uninstall.adoc, stories/topics/proc-aap-gcp-application-deploy.adoc, stories/topics/proc-aap-gcp-application-uninstall.adoc
Corrected images in Ch7 and Ch2
=> Corrected issues with icons and text.

stories/topics/proc-aap-aws-add-extension-nodes.adoc
Ensures tag is added to identify extension node instances as being associated with their related cloudformation stack.
=> Update extension node doc w/ tag

stories/topics/ref-aap-aws-install-prerequisites.adoc
=> Add AAP on AWS min required roles

stories/topics/proc-azure-update-route-tables.adoc
Add mcr.microsoft.com to Azure domain list
=> Azure Add mcr.microsoft.com to outbound routing list

stories/assembly-aap-gcp-backup-and-recovery.adoc, titles/aap-on-gcp/stories.adoc
=> Added backup and restore assembly

stories/topics/ref-aap-aws-iam-policies.adoc
=> Minor corrections

stories/assembly-aap-gcp-monitoring-logging.adoc, stories/topics/proc-aap-gcp-change-config-controller-hub.adoc, stories/topics/ref-aap-gcp-ansible-podman-config.adoc, stories/topics/ref-aap-gcp-configure-google-cloud-ops-agent.adoc
For issue https://issues.redhat.com/browse/AAP-10058, which is for AAP 2.3 on GCP with containerized installer, but it may also apply to current AAP 2.2 on GCP.  Still investigating
=> Log config

stories/topics/proc-aap-gcp-backup-and-restore.adoc
Signed-off-by: Leena Jawale <ljawale@redhat.com>
=> gcp backup and restore

stories/assembly-aap-gcp-backup-and-recovery.adoc, stories/topics/proc-aap-gcp-application-upgrade.adoc, stories/topics/proc-aap-gcp-backup-and-restore.adoc, stories/topics/proc-aap-gcp-backup-process.adoc, stories/topics/proc-aap-gcp-restore-process.adoc, titles/aap-on-gcp/stories.adoc
Corrections to upgrade chapter
=> Corrections to text

stories/topics/proc-aap-aws-secure-hub-controller-connection.adoc
=> Corrected error

stories/assembly-aap-aws-application-upgrade.adoc, stories/topics/proc-aap-aws-application-upgrade.adoc
**DO NOT MERGE IT YET**
Must be merged at the same time with:
- https://github.com/ansible/aap-docs/pull/71
=> AWS upgrade

stories/assembly-aap-aws-removing-extension-nodes.adoc, stories/topics/proc-aap-aws-prepare-environment-to-remove.adoc, stories/topics/proc-aap-aws-removing-extension-nodes.adoc
=> Corrected and reformatted Ch4

stories/topics/ref-aap-aws-deploying-extension-nodes.adoc
=> Fixed typo

stories/assembly-aap-aws-install.adoc, stories/topics/proc-aap-aws-deploy-existing-vpc.adoc, stories/topics/proc-aap-aws-deploy-new-vpc.adoc, stories/topics/proc-aap-aws-modify-cidr-ranges.adoc, stories/topics/proc-aap-aws-modify-lb-cidr-range-before.adoc, stories/topics/proc-aws-application-deploy.adoc, stories/topics/proc-aws-create-ec2-pair.adoc, stories/topics/ref-aap-aws-iam-policies.adoc, stories/topics/ref-aap-aws-install-prerequisites.adoc
Updated, largely putting iam policies into a table
=> AWS Install Updates

stories/assembly-aap-aws-application-upgrade.adoc, stories/topics/con-aap-aws-upgrade-backup-process.adoc, stories/topics/con-aap-aws-upgrade-upgrading-aap.adoc, stories/topics/con-aws-upgrade-restore-from-stack.adoc, stories/topics/proc-aap-aws-backup-platform-stack.adoc, stories/topics/proc-aap-aws-prepare-backup-environment.adoc, stories/topics/proc-aap-aws-run-ops-container.adoc, stories/topics/proc-aap-aws-upgrade-pull-container-image.adoc, stories/topics/proc-aap-gcp-application-upgrade.adoc, stories/topics/proc-aws-from-stack-prepare-environment.adoc, stories/topics/proc-aws-from-stack-pull-container-image.adoc, stories/topics/proc-aws-from-stack-run-to-upgrade.adoc, stories/topics/proc-aws-generate-upgrade-data-file.adoc, stories/topics/proc-aws-running-upgrade.adoc, stories/topics/ref-aap-aws-iam-minimum-permissions.adoc, stories/topics/ref-aap-aws-iam-upgrade-minimum-permissions.adoc, stories/topics/ref-aws-from-stack-minimum-permissions.adoc, stories/topics/ref-aws-update-upgrade-data-file.adoc
Two stages of procedures added so far
=> Update the AWS Upgrade information

stories/assembly-aap-aws-deploying-extension-nodes.adoc, stories/topics/con-aap-aws-pull-container-image.adoc, stories/topics/con-aap-aws-pull-deploy-container-image.adoc, stories/topics/proc-aap-aws-deploying-extension-nodes.adoc, stories/topics/proc-aap-aws-generate-add-data-files.adoc, stories/topics/proc-aap-aws-update-add-data-files.adoc
Added files (see PR for notes)
=> Updated AWS add extension nodes

stories/topics/proc-azure-update-route-tables.adoc
Update the domain list in the Network peering section of the Azure docs
=> Azure: Add domains and allowlist

stories/assembly-gcp-upgrade.adoc, stories/topics/con-gcp-upgrade-backup-process.adoc, stories/topics/con-gcp-upgrade-restore-from-stack.adoc, stories/topics/proc-gcp-backup-platform-stack.adoc, stories/topics/proc-gcp-generate-upgrade-data-file.adoc, stories/topics/proc-gcp-prepare-backup-environment.adoc, stories/topics/proc-gcp-run-restore-playbook-as-container.adoc, stories/topics/proc-gcp-running-upgrade.adoc
=> Correction to upgrading GCP

stories/topics/con-gcp-restore-process.adoc, stories/topics/proc-gcp-run-restore-command.adoc
Moved information from the end to the beginning of the section
=> Moved restore information to admonition

stories/topics/con-gcp-application-architecture.adoc
Fix GCP leveloffset build warning
=> Fix GCP leveloffset build warning

stories/topics/proc-aws-backup-platform-stack.adoc, stories/topics/proc-aws-from-stack-pull-container-image.adoc, stories/topics/proc-aws-set-container-image.adoc, stories/topics/proc-aws-upgrade-pull-container-image.adoc, stories/topics/proc-gcp-backup-container-image.adoc, stories/topics/proc-gcp-from-stack-pull-container-image.adoc, stories/topics/proc-gcp-pull-backup-container-image.adoc, stories/topics/proc-gcp-upgrade-pull-container-image.adoc
issue: https://issues.redhat.com/browse/AAP-13098
=> add registry.redhat login instructions

archive/archived-topics/proc-gcp-prepare-upgrade-aap-platform-stack.adoc, stories/assembly-azure-support.adoc, titles/aap-on-azure/stories.adoc
=>  Azure Add support page

stories/topics/con-gcp-service-account.adoc, stories/topics/proc-gcp-external-load-balancer.adoc, stories/topics/proc-gcp-retrieve-admin-password.adoc
For issue https://issues.redhat.com/browse/AAP-12575
=> A few changes for 2.3 based on user feedback

stories/topics/proc-aws-vpc-peering.adoc
Fix image reference in AWS guide
=> 2.2.1 Fix AWS image reference

stories/topics/proc-aws-deploy-existing-vpc.adoc, stories/topics/proc-aws-deploy-new-vpc.adoc, stories/topics/proc-aws-deploying-extension-nodes.adoc, stories/topics/proc-aws-marketplace.adoc
=> Revert "Corrections to AWS procedures"

stories/topics/proc-aws-create-ec2-pair.adoc, stories/topics/proc-aws-deploy-existing-vpc.adoc, stories/topics/proc-aws-deploy-new-vpc.adoc, stories/topics/proc-aws-marketplace.adoc
Changes to existing procedures
=> More corrections to AWS procedures

stories/topics/proc-gcp-delete-sevice-account.adoc
=> Correct typo GCP

titles/images
Fix symlink in the titles directory to point to the correct directory
=> Fix images symlink in titles directory

stories/topics/con-gcp-backup-process.adoc, stories/topics/proc-gcp-backup-requirements.adoc
https://issues.redhat.com/browse/AAP-13119
=> Create bucket before backup (2.4 Only)

aap-common/assembly-aap-command-generator.adoc, aap-common/proc-aap-playbooks.adoc, aap-common/proc-aap-run-generated-command.adoc
https://issues.redhat.com/browse/AAP-10828
=> Add GCP extra-playbooks (2.4 Only)

stories/topics/proc-aws-deleting-backups-playbook.adoc, stories/topics/proc-gcp-deleting-backups-playbook.adoc, stories/topics/proc-gcp-listing-backups-playbook.adoc
Fix build problems that were caused by wrong codeblock style.
=> Fix codeblock style

stories/assembly-gcp-backup-and-restore.adoc, stories/topics/con-gcp-restore-process.adoc, stories/topics/ref-gcp-populate-restore-file.adoc
https://issues.redhat.com/browse/AAP-13964
=> Update restore data file

aap-common/proc-aap-list-available-playbooks.adoc
For issues https://issues.redhat.com/browse/AAP-12563 and https://issues.redhat.com/browse/AAP-12562
=> add labels doc for AAP-12563 and AAP-12562

stories/topics/proc-azure-locate-aap-marketplace.adoc, stories/topics/proc-azure-provisioning-aap.adoc
Add a step to emphasise the requirement for a valid subscription.
=> Azure Add step to enable AAP subscription in marketplace

stories/assembly-aws-install.adoc, stories/topics/ref-aws-install-prerequisites.adoc
Reverse section order and demote one.
=> Move sections

stories/topics/proc-aws-deleting-backups-playbook.adoc
=> Correct section

aap-common/providing-direct-documentation-feedback.adoc, titles/aap-on-aws/stories.adoc, titles/aap-on-azure/stories.adoc, titles/aap-on-gcp/stories.adoc
* Add DDF module
* Include DDF module in Ansible on Clouds titles
=> 2.4 Add Direct Doc Feedback text to all Ansible on Clouds guides (#195)

stories/topics/proc-gcp-external-load-balancer.adoc
issue: https://issues.redhat.com/browse/AAP-14056
=> fix gcp external lb instructions

stories/topics/con-gcp-backup-process.adoc, stories/topics/ref-gcp-iam-backup-minimum-permissions.adoc
=> Modify backup process

stories/topics/con-gcp-restore-process.adoc, stories/topics/ref-gcp-iam-restore-minimum-permissions.adoc
=> Modify restore instructions

stories/assembly-gcp-backup-and-restore.adoc
For issue https://issues.redhat.com/browse/AAP-13159
=> gcp changes to 2.4

stories/topics/ref-gcp-install-permissions.adoc
=> Modify install instructions

stories/topics/proc-gcp-deploy-with-existing-vpc.adoc, stories/topics/proc-gcp-deploy-with-new-vpc.adoc
For https://issues.redhat.com/browse/AAP-14176 and release-2.4
=> add info on GCP label character limitations

stories/topics/proc-gcp-uninstall-application.adoc
Based on July 17, 2023 scrum discussion
=> GCP uninstall needs a bit more about removing external load balancer

stories/topics/con-aws-update-backup-data-file.adoc, stories/topics/con-aws-update-restore-data-file.adoc, stories/topics/proc-aws-deleting-backups-playbook.adoc, stories/topics/proc-aws-generate-backup-data-file.adoc, stories/topics/proc-aws-generate-remove-data-files.adoc, stories/topics/proc-aws-generate-restore-data-file.adoc, stories/topics/proc-aws-run-backup-playbook.adoc, stories/topics/proc-aws-run-restore-playbook.adoc, stories/topics/proc-aws-update-add-data-files.adoc, stories/topics/proc-aws-update-remove-data-file.adoc, stories/topics/proc-gcp-deleting-backups-playbook.adoc, stories/topics/ref-aws-update-upgrade-data-file.adoc
For issue https://issues.redhat.com/browse/AAP-13159
=> AWS backup changes

aap-common/proc-aap-list-available-playbooks.adoc, aap-common/proc-aap-playbooks.adoc
Just updated the outdated list of playbooks.
Not specific to AWS or GCP.
=> AoC minor update for playbooks list

stories/assembly-gcp-deploying-extension-nodes.adoc, stories/topics/con-gcp-pull-deploy-container-image.adoc, stories/topics/proc-gcp-deploying-add-extension-nodes.adoc, stories/topics/proc-gcp-generate-add-data-files.adoc, stories/topics/proc-gcp-update-add-data-files.adoc, stories/topics/ref-gcp-decide-offer-type.adoc, stories/topics/ref-gcp-permissions-to-manage-nodes.adoc, titles/aap-on-gcp/stories.adoc
=> Add GCP deploying extension nodes chapter

stories/topics/con-aws-application-architecture.adoc, stories/topics/con-gcp-application-architecture.adoc
=> Added new architecture diagrams

aap-common/assembly-release-notes.adoc, titles/aap-on-aws/stories.adoc, titles/aap-on-gcp/stories.adoc
Release notes doc. This doc is common for both AWS/GCP.
=> 2.4 - Add release notes doc

stories/topics/con-aws-application-architecture.adoc, stories/topics/con-gcp-application-architecture.adoc
=> Tidy up architecture descriptions

stories/topics/proc-aws-deploy-existing-vpc.adoc, stories/topics/proc-aws-deploy-new-vpc.adoc
=> Tidy up procedure

stories/topics/proc-aws-configure-security-network.adoc, stories/topics/proc-aws-retrieve-admin-password.adoc, stories/topics/proc-aws-retrieve-lb-addresses.adoc
=> Remove single numbered steps

stories/assembly-gcp-upgrade.adoc, stories/topics/proc-aws-uninstall-extension-nodes.adoc, stories/topics/proc-gcp-create-data-file.adoc, stories/topics/proc-gcp-deleting-backups-playbook.adoc, stories/topics/proc-gcp-generate-upgrade-data-file.adoc, stories/topics/proc-gcp-generate-variables.adoc, stories/topics/proc-gcp-running-upgrade.adoc
=> Tidied up cross references

stories/assembly-aws-upgrade.adoc, stories/assembly-gcp-upgrade.adoc, stories/topics/con-aws-update-restore-data-file.adoc, stories/topics/con-gcp-upgrade-backup-process.adoc, stories/topics/con-gcp-upgrade-upgrading.adoc, stories/topics/proc-aws-marketplace.adoc, stories/topics/proc-gcp-deploying-extension-nodes.adoc
Corrections
enter the commit message for your changes. Lines starting
=> Tidy up procedures

stories/assembly-aws-upgrade.adoc, stories/assembly-gcp-upgrade.adoc, stories/topics/con-aws-upgrade-backup-process.adoc, stories/topics/con-aws-upgrade-restore-from-stack.adoc, stories/topics/con-gcp-upgrade-backup-process.adoc, stories/topics/con-gcp-upgrade-restore-from-stack.adoc
Switch necessary doc links from 2.x to 2.3
=> Update references to 2.3 doc

aap-common/proc-aap-list-available-playbooks.adoc
For issue https://issues.redhat.com/browse/AAP-14528
=> remove a few playbooks that are no longer available to the user

stories/topics/proc-gcp-additional-configs-replace-tls-certificate.adoc, stories/topics/proc-gcp-additional-configs-update-admin-password.adoc
[Docs] [SMAC-GCP] Doc typo on sections 6.1 and 6.2 "Manger"
https://issues.redhat.com/browse/AAP-14677
=> Correct typo

attributes/attributes.adoc
To replace image statements
DOC: Create new attribute for IMAGE value
https://issues.redhat.com/browse/AAP-14901
=> Created image attribute

attributes/attributes.adoc
Added attribute
https://issues.redhat.com/browse/AAP-14901
=> Added additional attribute for standalone Image reference

stories/topics/con-azure-scaling.adoc
This PR aligns the minimum node count to 2, which is also set here:
https://github.com/ansible/aap-docs/blob/aap-clouds-latest/stories/topics/con-azure-infrastructure-usage.adoc?plain=1#L12
=> Updating the minimum node count to 2.

attributes/attributes.adoc
* Created image attribute
To replace image statements
DOC: Create new attribute for IMAGE value
https://issues.redhat.com/browse/AAP-14901
* Create image attribute
Updated image name, added registry
DOC: Create new attribute for IMAGE value
https://issues.redhat.com/browse/AAP-14901
* Created image attribute
Corrected image name
DOC: Create new attribute for IMAGE value
https://issues.redhat.com/browse/AAP-14901
=> Created image attribute (#264)

attributes/attributes.adoc
Backports #266  to `2.4`
Added attribute
https://issues.redhat.com/browse/AAP-14901
=> Added additional attribute for standalone Image reference (#266)

aap-common/assembly-appendix-release-notes.adoc, aap-common/proc-aap-pull-command-container-image.adoc, stories/assembly-aws-upgrade.adoc, stories/assembly-gcp-upgrade.adoc, stories/topics/con-aws-application-architecture.adoc, stories/topics/con-aws-pull-container-image.adoc, stories/topics/con-aws-pull-deploy-container-image.adoc, stories/topics/con-aws-update-restore-data-file.adoc, stories/topics/con-gcp-application-architecture.adoc, stories/topics/con-gcp-pull-deploy-container-image.adoc, stories/topics/con-gcp-pull-remove-container-image.adoc, stories/topics/con-gcp-use-container-image.adoc, stories/topics/proc-aws-backup-platform-stack.adoc, stories/topics/proc-aws-from-stack-pull-container-image.adoc, stories/topics/proc-aws-running-upgrade.adoc, stories/topics/proc-aws-set-container-image.adoc, stories/topics/proc-aws-upgrade-pull-container-image.adoc, stories/topics/proc-azure-update-route-tables.adoc, stories/topics/proc-gcp-backup-container-image.adoc, stories/topics/proc-gcp-from-stack-pull-container-image.adoc, stories/topics/proc-gcp-pull-backup-container-image.adoc, stories/topics/proc-gcp-running-upgrade.adoc, stories/topics/proc-gcp-upgrade-pull-container-image.adoc, stories/topics/tech-note-aws-upgrade.adoc, stories/topics/tech-note-gcp-upgrade.adoc
* Replace image names and registry.redhat.io witth attributes
=> 2.4 Replace image names and registry.redhat.io with attributes (#267)

downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
Additional step after modifying fstab
[DDF] Need to execute `systemctl daemon-reload` after you modify the fstab
https://issues.redhat.com/browse/AAP-15204
=> Additional instruction added

downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
Additional step after modifying fstab
[DDF] Need to execute `systemctl daemon-reload` after you modify the fstab
https://issues.redhat.com/browse/AAP-15204
=> Additional instruction added (#280)

downstream/modules/platform/ref-eda-controller-variables.adoc
Correction
Typo in Red Hat Ansible Automation Platform Installation Guide
https://issues.redhat.com/browse/AAP-15045
=> Corrected typo

downstream/modules/platform/ref-eda-controller-variables.adoc
Correction
Typo in Red Hat Ansible Automation Platform Installation Guide
https://issues.redhat.com/browse/AAP-15045
=> Corrected typo (#282)

downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
Correction
[DDF] This should be example.com
https://issues.redhat.com/browse/AAP-15337
=> Correct typo (#288)

downstream/assemblies/platform/assembly-migrate-isolated-execution-nodes.adoc
Fixes "box" issue in ch. 4 of Upgrade and Migration Guide v2.2.
=> Fixes formatting issue in V2.2 of the Upgrade and Migration Guide

downstream/assemblies/dev-guide/assembly-tools-components.adoc, downstream/modules/dev-guide/con-content-workflows.adoc
This PR fixes broken links in the Creator Guide. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more.
=> AAP-15176 Fix broken links in Creator Guide

downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc, downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc, downstream/modules/aap-hardening/con-hardening-guide-audience.adoc, downstream/modules/aap-hardening/con-platform-components.adoc, downstream/modules/aap-hardening/con-product-overview.adoc, downstream/titles/aap-hardening/master.adoc
Jira link: [AAP-14808](https://issues.redhat.com/browse/AAP-14808)
Converting Chapter 1 of AAP hardening guide into asciidoc for September 1st publication.
Link to guide as google doc: [[WIP] AAP hardening guide - Draft 3](https://docs.google.com/document/d/1A6VLRNEzvKw4GWhcQpIMpSN9ylFpMGsGLeIUU-7p19I/edit#heading=h.sm5b5wvn3vvk)
=> [WIP] AAP-14808: Chapter 1 build of AAP Hardening Guide

downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc, downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc, downstream/modules/aap-hardening/con-hardening-guide-audience.adoc, downstream/modules/aap-hardening/con-platform-components.adoc, downstream/modules/aap-hardening/con-product-overview.adoc, downstream/titles/aap-hardening/master.adoc
Backporting to 2.4 release branch...
Jira link: [AAP-14808](https://issues.redhat.com/browse/AAP-14808)
Converting Chapter 1 of AAP hardening guide into asciidoc for September 1st publication.
Link to guide as google doc: [[WIP] AAP hardening guide - Draft 3](https://docs.google.com/document/d/1A6VLRNEzvKw4GWhcQpIMpSN9ylFpMGsGLeIUU-7p19I/edit#heading=h.sm5b5wvn3vvk)
=> [2.4] AAP-14808: Fixed order of sections (#293)

downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc, downstream/modules/aap-hardening/con-logging-log-capture.adoc, downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc, downstream/modules/aap-hardening/con-planning-considerations.adoc, downstream/modules/aap-hardening/con-rhel-host-planning.adoc, downstream/modules/aap-hardening/con-user-authentication-planning.adoc, downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc, downstream/modules/aap-hardening/proc-fapolicyd.adoc, downstream/modules/aap-hardening/ref-auditing-incident-detection.adoc, downstream/modules/aap-hardening/ref-automation-controller-operational-secrets.adoc, downstream/modules/aap-hardening/ref-dns-load-balancing.adoc, downstream/modules/aap-hardening/ref-ntp.adoc, downstream/modules/platform/proc-change-ssl-installer.adoc
=> Modify hardening guide IDs

downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc, downstream/modules/aap-hardening/con-logging-log-capture.adoc, downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc, downstream/modules/aap-hardening/con-planning-considerations.adoc, downstream/modules/aap-hardening/con-rhel-host-planning.adoc, downstream/modules/aap-hardening/con-user-authentication-planning.adoc, downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc, downstream/modules/aap-hardening/proc-fapolicyd.adoc, downstream/modules/aap-hardening/ref-auditing-incident-detection.adoc, downstream/modules/aap-hardening/ref-automation-controller-operational-secrets.adoc, downstream/modules/aap-hardening/ref-dns-load-balancing.adoc, downstream/modules/aap-hardening/ref-ntp.adoc, downstream/modules/platform/proc-change-ssl-installer.adoc
Fix hardening guide IDs
Backports #309 to 2.4
=> 2.4 Modify hardening guide IDs (#309)

downstream/modules/aap-hardening/con-credential-management-planning.adoc
Fixing an xref that's breaking the Hardening guide build.
=> hgfix - Fixing an xref causing a build error

downstream/modules/aap-hardening/con-credential-management-planning.adoc
This PR backports the change for #328 to the 2.4 branch.
=> [Backport] hgfix - Fixing an xref causing a build error (#328)

downstream/modules/platform/proc-defining-node-types.adoc, downstream/modules/platform/ref-multiple-hybrid-nodes.adoc
Replaced node-type with node_type where appropriate
[DDF] It should be node_type.
https://issues.redhat.com/browse/AAP-15618
=> Correct typo (#330)

aap-common/proc-aap-playbooks.adoc, aap-common/ref-aap-using-playbooks.adoc, stories/topics/proc-gcp-generate-restore-yml-file.adoc, stories/topics/proc-gcp-running-upgrade.adoc
Added to list of playbooks and added *_sos_report to using playbooks
=> Added playbooks information

downstream/titles/aap-hardening/docinfo.xml, downstream/titles/aap-hardening/master.adoc
Re [AAP-14809](https://issues.redhat.com/browse/AAP-14809), revisions to:
- master.adoc
Updated "providing feedback" section.
=> AAP-14809-edits updated master.adoc feedback

downstream/titles/aap-hardening/docinfo.xml, downstream/titles/aap-hardening/master.adoc
2.4 backport of [PR333](https://github.com/ansible/aap-docs/pull/333)
Re [AAP-14809](https://issues.redhat.com/browse/AAP-14809), revisions to:
- master.adoc
- docinfo.xml
=> AAP-14809-edits updated master.adoc feedback (#333)

downstream/assemblies/platform/assembly-system-requirements.adoc
Add NTP configuration step to prerequisites section of chapter 2 of the AAP installation guide
NTP configuration in AAP installation
https://issues.redhat.com/browse/AAP-14103
=> Add NTP configuration to AAP installation

downstream/assemblies/platform/assembly-controller-licensing.adoc, downstream/modules/platform/ref-controller-license-support.adoc, downstream/modules/platform/ref-controller-licenses.adoc, downstream/modules/platform/ref-controller-node-counting.adoc, downstream/modules/platform/ref-controller-trial-evaluation.adoc, downstream/titles/controller/controller-user-guide/master.adoc
* Create Section 2  of Controller UG https://issues.redhat.com/browse/AAP-15344
=> Create Section 2 'licensing' of Controller UG (#332)

downstream/assemblies/platform/assembly-network-ports-protocols.adoc, downstream/modules/builder/con-ansible-config-file-path.adoc, downstream/modules/dev-guide/proc-create-collections.adoc, downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
Replaced cloud.redhat.com with console.redhat.com
Outdated URLs in doc
https://issues.redhat.com/browse/AAP-15483
=> Replaced URL

downstream/assemblies/platform/assembly-network-ports-protocols.adoc, downstream/modules/builder/con-ansible-config-file-path.adoc, downstream/modules/dev-guide/proc-create-collections.adoc, downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
* Replaced cloud.redhat.com with console.redhat.com
https://issues.redhat.com/browse/AAP-15483
=> Replaced cloud.redhat.com with console.redhat.com (#302)

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc, downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-ansible-core.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc, downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc, downstream/modules/platform/proc-using-postinstall.adoc, downstream/modules/platform/ref-aap-containerized-dns-config.adoc, downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Cherry-picked commits from https://github.com/rogrange/aap-docs/commits/container-update to my branch for a PR to aap-docs/main
=> Modify container guide

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc, downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc
=> Fixed attribute name, numbering.

downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
Link to Jira issue: [AAP-15836](https://issues.redhat.com/browse/AAP-15836)
Section **2.3.2.1 Configure centralized logging**
- Changed `var/log/awx` to `var/lib/awx`
- Changed `<FQDN>` to `<automation controller server>`
=> AAP-15836: Fix typos

downstream/assemblies/platform/assembly-controller-login.adoc, downstream/modules/platform/proc-controller-logging-in.adoc, downstream/titles/controller/controller-user-guide/master.adoc
Added shared assembly
Create Section 3 of automation controller user guide
https://issues.redhat.com/browse/AAP-15347
=> Create Section 3 'Login' of the Controller UG

downstream/assemblies/platform/assembly-controller-login.adoc, downstream/modules/platform/proc-controller-logging-in.adoc, downstream/titles/controller/controller-user-guide/master.adoc
Added shared assembly
Create Section 3 of automation controller user guide
https://issues.redhat.com/browse/AAP-15347
=> Create Section 3 'Login' of the Controller UG (#370)

downstream/modules/dev-guide/con-content-workflows.adoc
See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for further details.
=> fix broken link in creator guide v2.4

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc, downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-ansible-core.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc, downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc, downstream/modules/platform/proc-using-postinstall.adoc, downstream/modules/platform/ref-aap-containerized-dns-config.adoc, downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Backports the following PRs to `2.4`:
*  #364 
*  #366 
*  #368 
*  #372
=> 2.4 Update containerized install doc (#364) (#366) (#368) (#372)

downstream/assemblies/platform/assembly-controller-inventory-templates.adoc, downstream/modules/platform/ref-controller-aap-template.adoc, downstream/modules/platform/ref-controller-amazon-web-services.adoc, downstream/modules/platform/ref-controller-google-compute.adoc, downstream/modules/platform/ref-controller-microsoft-azure.adoc, downstream/modules/platform/ref-controller-openstack.adoc, downstream/modules/platform/ref-controller-rh-satellite.adoc, downstream/modules/platform/ref-controller-rh-virtualization.adoc, downstream/modules/platform/ref-controller-vmware-vcenter.adoc, downstream/titles/controller/controller-user-guide/master.adoc
Added assembly and reference modules
Create Section 20 of the Controller user Guide
https://issues.redhat.com/browse/AAP-15831
=> Create section 20 "Supported Inventory" of the Controller UG

downstream/assemblies/platform/assembly-controller-inventory-templates.adoc, downstream/modules/platform/ref-controller-aap-template.adoc, downstream/modules/platform/ref-controller-amazon-web-services.adoc, downstream/modules/platform/ref-controller-google-compute.adoc, downstream/modules/platform/ref-controller-microsoft-azure.adoc, downstream/modules/platform/ref-controller-openstack.adoc, downstream/modules/platform/ref-controller-rh-satellite.adoc, downstream/modules/platform/ref-controller-rh-virtualization.adoc, downstream/modules/platform/ref-controller-vmware-vcenter.adoc, downstream/titles/controller/controller-user-guide/master.adoc
* Create section 20 "Supported Inventory" of the Controller UG
Added assembly and reference modules
Create Section 20 of the Controller user Guide
https://issues.redhat.com/browse/AAP-15831
* Adding block headers
=> Create section 20 "Supported Inventory" of the Controller UG (#376)

downstream/titles/hub/repo-management/temp.adoc
Adding a temporary file to the repo-management title directory so that we can delete it in a later PR.
=> Add temporary file to repo-management title directory

downstream/titles/hub/repo-management/temp.adoc
Delete temporary file so that `titles/repo-management` can be deleted.
=> Delete temporary file

downstream/modules/hub/proc-delete-collection.adoc, downstream/modules/hub/proc-upload-collection.adoc
Reviewed and tweaked "Chapter 4 Uploading content to Red Hat automation hub" of the Getting started with automation hub guide, focusing on the following sections:
- 4.1. Uploading a collection to automation hub
- 4.2. Deleting a collection on automation hub
=> AAP 15788 [HubDocathon] Chapter 4 of the Getting started with automation hub guide

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc, downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc, downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc, downstream/modules/platform/proc-using-postinstall.adoc
Final edits from Phil for the containerized installation guide.
=> Final edits

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc, downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc, downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc, downstream/modules/platform/proc-using-postinstall.adoc
* Final edits
* Update proc-downloading-containerized-aap.adoc
Added containerized name to PATH variable.
* Update proc-preparing-the-rhel-host-for-containerized-installation.adoc
Changed AAP to {PlatformNameShort}.
* Update proc-preparing-the-rhel-host-for-containerized-installation.adoc
Deleted 'then'. Superfluous.
=> Final edits (#389)

downstream/assemblies/hub/assembly-faq.adoc, downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc, downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/assemblies/hub/assembly-validated-content.adoc, downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc, downstream/modules/hub/proc-downloading-signature-public-keys.adoc, downstream/modules/hub/proc-set-community-remote.adoc, downstream/modules/hub/proc-set-rhcertified-remote.adoc, downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
Some assemblies commented out. Minor changes throughout.
[HubDocathon] Managing content Chapter 1
https://issues.redhat.com/browse/AAP-15791
=> [HubDocathon] Created 'Managing Content' Chapter 1

downstream/assemblies/hub/assembly-user-access.adoc, downstream/assemblies/hub/assembly-view-only-access.adoc, downstream/modules/hub/con-enable-view-only.adoc, downstream/modules/hub/con-user-access.adoc, downstream/modules/hub/proc-create-content-developers.adoc, downstream/modules/hub/proc-create-groups.adoc
Jira link: [AAP-15785](https://issues.redhat.com/browse/AAP-15785)
See [content tracker spreadsheet](https://docs.google.com/spreadsheets/d/1NIrCUPhKjGaCL2Bs81qPQajow__KMIDT/edit#gid=679299608) for notes
=> AAP-15785: Revised titles and sections

downstream/assemblies/hub/assembly-hub-overview.adoc
This PR adds and Overview section for Hub and provides the distinction between AH and PAH.
=> AAP-15782 - Added overview and clarification between AH and PAH

downstream/modules/hub/proc-approve-collection.adoc, downstream/modules/hub/proc-create-content-developers.adoc, downstream/modules/hub/proc-reject-collections.adoc
Updating the Managing collections in automation hub assembly in the `/titles/hub/managing-content` guide.
Some suggestions from comments in #386 incorporated.
=> AAP-15793-a Docathon: Managing Collections in AH

downstream/modules/hub/proc-set-rhcertified-remote.adoc
Removed full stop
[HubDocathon] Managing content Chapter 1
https://issues.redhat.com/browse/AAP-15791
=> Created Managing Content Chapter 1(Correction)

downstream/modules/platform/ref-system-requirements.adoc
Added Notes to RAM and CPUs sections of hybrid nodes table in the AAP Installation Guide
Clarify notes for Hybrid Nodes in the AAP Installation Guide
https://issues.redhat.com/browse/AAP-15864
=> Update hybrid nodes table to add more clarity

downstream/assemblies/hub/assembly-repo-management.adoc, downstream/assemblies/hub/assembly-user-access.adoc, downstream/modules/hub/con-user-access.adoc, downstream/modules/hub/proc-add-user-to-group.adoc, downstream/modules/hub/proc-adding-collections-repository.adoc, downstream/modules/hub/proc-approve-collection.adoc, downstream/modules/hub/proc-basic-repo-sync.adoc, downstream/modules/hub/proc-create-api-token.adoc, downstream/modules/hub/proc-create-content-developers.adoc, downstream/modules/hub/proc-create-groups.adoc, downstream/modules/hub/proc-create-namespace.adoc, downstream/modules/hub/proc-create-remote.adoc, downstream/modules/hub/proc-create-repository.adoc, downstream/modules/hub/proc-create-super-users.adoc, downstream/modules/hub/proc-create-users.adoc, downstream/modules/hub/proc-delete-namespace.adoc, downstream/modules/hub/proc-delete-user.adoc, downstream/modules/hub/proc-edit-namespace.adoc, downstream/modules/hub/proc-export-collection.adoc, downstream/modules/hub/proc-import-collection.adoc, downstream/modules/hub/proc-provide-remote-access.adoc, downstream/modules/hub/proc-provide-repository-access.adoc, downstream/modules/hub/proc-reject-collections.adoc, downstream/modules/hub/proc-revert-repository-version.adoc, downstream/modules/hub/proc-review-collection-imports.adoc, downstream/modules/hub/proc-set-community-remote.adoc, downstream/modules/hub/proc-set-rhcertified-remote.adoc, downstream/modules/hub/proc-uploading-collections.adoc, downstream/modules/hub/ref-permissions.adoc
Editing UI steps in hub and adding missing attributes
[HubDocathon] Minor edits to the Getting started with automation hub and Managing content
https://issues.redhat.com/browse/AAP-16043
=> Making edits to UI as per test environment

downstream/modules/platform/ref-system-requirements.adoc
Added Notes to RAM and CPUs sections of hybrid nodes table in the AAP Installation Guide
Clarify notes for Hybrid Nodes in the AAP Installation Guide
https://issues.redhat.com/browse/AAP-15864
=> Update hybrid nodes table to add more clarity (#403)

downstream/modules/platform/proc-installing-containerized-aap.adoc
Changed from: 
ansible-playbook -i ansible.containerized_installer.install
to
ansible-playbook -i inventory ansible.containerized_installer.install
=> Minor change in installation line

downstream/modules/core/con-about-ansible-cli.adoc
Reword "About the Ansible command line interface" abstract section to improve clarity based on Red Hat style guide.
Red Hat Ansible Automation Platform Creator Guide - About the Ansible command line interface - Suggestions to improve readability
https://issues.redhat.com/browse/AAP-16036
=> Reword About the Ansible command line interface to improve clarity

downstream/assemblies/platform/assembly-system-requirements.adoc, downstream/modules/platform/ref-eda-system-requirements.adoc
- Added a new module "Event-Driven Ansible controller system requirements" to both the Installation and Planning guides.
- This was added to the assembly for the overall system requirements chapter (Chapter 4 in the Planning Guide and Chapter 2 in the Installation Guide)
=> AAP-13785 New minimum requirement for EDA controller section

downstream/modules/platform/ref-postgresql-requirements.adoc
Remove duplicate content from PostgreSQL requirements table in Platform Planning Guide
[DDF] In here twice, can be consolidated
https://issues.redhat.com/browse/AAP-15999
=> Remove duplicate content from Platform Planning Guide

downstream/modules/platform/ref-postgresql-requirements.adoc
Remove duplicate content from PostgreSQL requirements table in Platform Planning Guide
[DDF] In here twice, can be consolidated
https://issues.redhat.com/browse/AAP-15999
=> Remove duplicate content from Platform Planning Guide (#431)

downstream/assemblies/eda/assembly-eda-set-up-token.adoc, downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Editing chapter 4 title in EDA user guide
[EDA][DOCS] misleading title for chapter 4
https://issues.redhat.com/browse/AAP-16055
=> Editing title in EDA user guide

downstream/assemblies/eda/assembly-eda-set-up-token.adoc, downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
* Editing title in EDA user guide
Editing chapter 4 title in EDA user guide
[EDA][DOCS] misleading title for chapter 4
https://issues.redhat.com/browse/AAP-16055
* Edits as per peer review
=> Editing title in EDA user guide (#436)

downstream/assemblies/hub/assembly-configure-hub-primary.adoc, downstream/assemblies/hub/assembly-hub-create-api-token.adoc, downstream/assemblies/hub/assembly-hub-overview.adoc, downstream/modules/hub/con-offline-token-active.adoc, downstream/modules/hub/proc-configure-automation-hub-server-cli.adoc, downstream/modules/hub/proc-configure-automation-hub-server-gui.adoc, downstream/modules/hub/proc-create-api-token-pah.adoc, downstream/modules/hub/proc-create-api-token.adoc, downstream/titles/hub/getting-started/master.adoc
This PR incorporates the improvements suggested during the docathon editorial review.
=> it-15782 - Incorporated changes based on editorial review

downstream/assemblies/hub/assembly-uploading-content-hub.adoc, downstream/modules/hub/proc-delete-collection.adoc, downstream/modules/hub/proc-upload-collection.adoc
Applied updates from editorial review for original branch and PR (AAP-15788 / PR #385)
=> AAP-15788A Applied updates from editorial review for original branch AAP-15788 / PR #385

downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc, downstream/assemblies/hub/assembly-faq.adoc, downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc, downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/assemblies/hub/assembly-validated-content.adoc, downstream/modules/hub/con-rh-certified-synclist.adoc, downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc, downstream/modules/hub/proc-configure-content-signing-on-pah.adoc, downstream/modules/hub/proc-create-synclist.adoc, downstream/modules/hub/proc-downloading-signature-public-keys.adoc, downstream/modules/hub/proc-obtaining-org-collection-url.adoc, downstream/modules/hub/proc-set-community-remote.adoc, downstream/modules/hub/proc-set-rhcertified-remote.adoc, downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
Corrections
[HubDocathon] Managing content Chapter 1
https://issues.redhat.com/browse/AAP-15791
=> Editorial corrections to first chapter of Managing Content Guide

downstream/assemblies/hub/assembly-container-user-access.adoc, downstream/assemblies/hub/assembly-delete-container.adoc, downstream/assemblies/hub/assembly-managing-container-registry.adoc, downstream/assemblies/hub/assembly-managing-containers-hub.adoc, downstream/assemblies/hub/assembly-populate-container-registry.adoc, downstream/assemblies/hub/assembly-pull-image.adoc, downstream/assemblies/hub/assembly-setup-container-repository.adoc, downstream/assemblies/hub/assembly-working-with-signed-containers.adoc, downstream/modules/hub/proc-add-container-readme.adoc, downstream/modules/hub/proc-add-group-to-container-repo.adoc, downstream/modules/hub/proc-add-user-to-group.adoc, downstream/modules/hub/proc-adding-an-execution-environment.adoc, downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc, downstream/modules/hub/proc-assigning-permissions.adoc, downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc, downstream/modules/hub/proc-create-credential.adoc, downstream/modules/hub/proc-create-groups.adoc, downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc, downstream/modules/hub/proc-obtain-images.adoc, downstream/modules/hub/proc-pull-image.adoc, downstream/modules/hub/proc-push-container.adoc, downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc, downstream/modules/hub/proc-sync-image.adoc, downstream/modules/hub/proc-tag-image.adoc, downstream/modules/hub/proc-using-policies-with-signed-images.adoc, downstream/modules/hub/ref-container-permissions.adoc
https://issues.redhat.com/browse/AAP-15796
=> Editorial review edits

downstream/assemblies/platform/assembly-disconnected-installation.adoc, downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc, downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc, downstream/modules/platform/proc-adding-a-subscription-manifest-to-aap-without-an-internet-connection.adoc, downstream/modules/platform/proc-completing-post-installation-tasks.adoc, downstream/modules/platform/proc-creating-a-new-web-server-to-host-repositories.adoc, downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc, downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
This PR integrates edits I made to the Disconnected Installation chapter, sections 6.1-6.7. I focused primarily on adding attributes, adding abstracts beneath headings where necessary, and making minor edits for clarity. Section 6.7 in particular will need further restructuring, but this will likely need to be saved for post-docathon tasks.
=> AAP-16032: Docathon updates to Disconnected Installation chapter

downstream/assemblies/hub/assembly-view-only-access.adoc, downstream/modules/hub/con-enable-view-only.adoc, downstream/modules/hub/con-user-access.adoc, downstream/modules/hub/proc-add-user-to-group.adoc, downstream/modules/hub/proc-assigning-permissions.adoc, downstream/modules/hub/proc-create-content-developers.adoc, downstream/modules/hub/proc-create-groups.adoc, downstream/modules/hub/proc-create-super-users.adoc, downstream/modules/hub/proc-create-users.adoc, downstream/modules/hub/ref-permissions.adoc
Jira issue [AAP-15785](https://issues.redhat.com/browse/AAP-15785)
- These edits/revisions are based off of [Ingrid's editorial review](https://docs.google.com/document/d/1FbYuUrfWUZEzc0Xko2t82c9uxoSnXVPZhRX_NhQlK1w/edit#heading=h.pga2xksfc8t2) **Chapter 4 Configuring user access for your local automation hub - 4.2.1**  
- In order to have this completed in time for SME review, I did not incorporate any changes that required rewriting, title change, etc.
=> AAP-15785-Revisions: Revisions based on editorial review

downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc, downstream/modules/platform/proc-approving-the-imported-collection.adoc, downstream/modules/platform/proc-creating-collection-namespace.adoc, downstream/modules/platform/proc-importing-collections-into-private-automation-hub.adoc, downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
This PR makes edits to sections 6.8-6.12 of the Disconnected Installation chapter in the Installation Guide. See [AAP-16032](https://issues.redhat.com/browse/AAP-16032) for more info.
=> AAP-16032: Docathon edits to Disconnected Installation chapter pt. 2 

downstream/modules/hub/proc-assigning-permissions.adoc, downstream/modules/hub/proc-set-community-remote.adoc, downstream/modules/hub/ref-variables-connect-hub-sso.adoc, downstream/modules/platform/proc-approving-the-imported-collection.adoc, downstream/modules/platform/ref-standalone-hub-inventory.adoc
Minor corrections to fix trailing conflict characters, broken attribute, missing heading before delivering drafts to SMEs.
=> Minor corrections before delivering to SMEs

downstream/modules/navigator/ref-faq-navigator.adoc
Update Automation Content Navigator Creator Guide to improve readability based on suggestions in SSG and IBM SG
Automation Content Navigator Creator Guide - 9.2. Automation content navigator Frequently asked questions
https://issues.redhat.com/browse/AAP-16322
=> Improve automation content navigator frequently asked questions section

bin/sync_cloud_docs.sh
Add script in `/bin` directory for self-managed Azure sync to Gitlab production repo.
=> Add script for self-managed Azure sync to prod repo

downstream/modules/platform/ref-controller-variables.adoc
Moved from https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1313
=> Document installer variable for max_connections

downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
* Added note about ISP blocking port 445
* Update ref-accessing-control-auto-hub-eda-control.adoc
* Update ref-accessing-control-auto-hub-eda-control.adoc
=> Added note about ISP blocking port 445 (#513)

downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Jira link: [AAP-16182](https://issues.redhat.com/browse/AAP-16182) 
- Update section with revised diagram that shows correct port
- Add diagram heading
=> AAP-16182: Updated network ports and protocols diagram

downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Backport for [PR#526](https://github.com/ansible/aap-docs/pull/526)
Jira link: [AAP-16182](https://issues.redhat.com/browse/AAP-16182)
- Update section with revised diagram that shows correct port
- Add diagram heading
- Revise alt text
=> [2.4] AAP-16182: Revise alt text of diagram (#526)

downstream/modules/platform/con-install-scenario-examples.adoc, downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-eda-controller-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
Correction
Clarify what characters are not acceptable for passwords
https://issues.redhat.com/browse/AAP-15242
=> Corrected statement about special characters in passwords

downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-eda-controller-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
This PR adds the details requested in https://issues.redhat.com/browse/AAP-16463.
=> AAP-16463 - Add information about enclosing passwords in quotes

downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-eda-controller-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
This PR merges the changes from #522 to the 2.4 branch.
=> AAP-16463 - Add information about enclosing passwords in quotes (#522)

downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc, downstream/assemblies/hub/assembly-repo-management.adoc
- Corrected incorrect attribute and corrected a typo in first section
- Clarified difference between staging and custom repositories in Repo management with automation hub section
=> AAP 15790 fixes based on SME comments

downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc, downstream/assemblies/hub/assembly-repo-management.adoc
This PR applies the changes from [PR 544](https://github.com/ansible/aap-docs/pull/544) to the 2.4 release.
=> AAP 15790 fixes based on SME comments (#544)

bin/sync_lightspeed_docs.sh
Add a script to the lightspeed docs that will be used by the Jenkins job to sync the lightspeed docs to the production repo on Gitlab.
=> Add lightspeed sync script

downstream/modules/platform/proc-change-ssl-installer.adoc
Backports part of #291 to 2.3
One file wasn't backported in the cherry-pick.
=> Add SSL change module

downstream/assemblies/hub/assembly-collection-import-export.adoc, downstream/assemblies/hub/assembly-remote-management.adoc, downstream/assemblies/hub/assembly-repo-management.adoc, downstream/modules/hub/con-approval-pipeline.adoc, downstream/modules/hub/con-repo-rbac.adoc, downstream/modules/hub/proc-adding-collections-repository.adoc, downstream/modules/hub/proc-basic-repo-sync.adoc, downstream/modules/hub/proc-create-remote.adoc, downstream/modules/hub/proc-create-repository.adoc, downstream/modules/hub/proc-export-collection.adoc, downstream/modules/hub/proc-import-collection.adoc, downstream/modules/hub/proc-provide-remote-access.adoc, downstream/modules/hub/proc-revert-repository-version.adoc
This PR adds editorial changes to the Managing Content section of the hub docs. See[ AAP 15795](https://issues.redhat.com/browse/AAP-15795) for further detail.
=> AAP 15795: Editorial changes to Managing Content 

stories/topics/con-gcp-application-architecture.adoc, stories/topics/con-gcp-application-deploy.adoc
Added required text.
Update Ansible on Cloud GCP Docs
https://issues.redhat.com/browse/AAP-16284
=> Added virtual machine text

stories/topics/con-gcp-application-architecture.adoc, stories/topics/con-gcp-application-deploy.adoc
Added required text.
Update Ansible on Cloud GCP Docs
https://issues.redhat.com/browse/AAP-16284
=> Added virtual machine text (#561)

stories/topics/con-gcp-application-architecture.adoc, stories/topics/con-gcp-application-deploy.adoc
Added required text
Update Ansible on Cloud GCP Docs.
https://issues.redhat.com/browse/AAP-16284
=> Added virtual machine text.

downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc, downstream/modules/platform/proc-change-ssl-controller-ocp.adoc, downstream/modules/platform/proc-change-ssl-controller.adoc, downstream/modules/platform/proc-change-ssl-hub-ocp.adoc, downstream/modules/platform/proc-change-ssl-hub.adoc, downstream/modules/platform/proc-change-ssl-installer.adoc, downstream/modules/platform/proc-renew-ssl-cert.adoc, downstream/titles/aap-installation-guide/master.adoc
… (#291)
AAP-11096
Add a chapter to the Installation guide that describes how to replace SSL certs and keys.
=> 2.2 AAP-11096 Add changing SSL certs and keys chapter to operations guide (#291)

stories/topics/ref-aws-iam-policies.adoc, stories/topics/ref-aws-iam-upgrade-minimum-permissions.adoc, stories/topics/ref-aws-permissions-to-manage-nodes.adoc, stories/topics/ref-aws-permissions.adoc, stories/topics/ref-aws-restore-process-permissions.adoc
For issue https://issues.redhat.com/browse/AAP-16984 based on customer interaction
=> Add note about AWS IAM Policy Simulator for checking IAM permissions

downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-eda-controller-variables.adoc, downstream/modules/platform/ref-general-inventory-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
Inventory variables added,moved some into alphabetical order
Update AAP Inventory File Variables section with new nginx header/config variables
https://issues.redhat.com/browse/AAP-16103
=> Added inventory variables

downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-eda-controller-variables.adoc, downstream/modules/platform/ref-general-inventory-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
* Update AAP Inventory File Variables section with new nginx header/config variables https://issues.redhat.com/browse/AAP-16103
=> Added inventory variables (#478)

stories/topics/ref-aws-iam-policies.adoc, stories/topics/ref-aws-iam-upgrade-minimum-permissions.adoc, stories/topics/ref-aws-permissions-to-manage-nodes.adoc, stories/topics/ref-aws-permissions.adoc, stories/topics/ref-aws-restore-process-permissions.adoc
For issue https://issues.redhat.com/browse/AAP-16984.  Backport to branch aap-clouds-2.4
=> Cahl/aws policy sim 2.4

aap-common/assembly-appendix-release-notes.adoc, stories/topics/proc-aws-deploy-new-vpc.adoc, stories/topics/proc-gcp-deploy-with-new-vpc.adoc
Doc - Write deprecation note for new vpc
https://issues.redhat.com/browse/AAP-16519
=> Added deprecation notice

aap-common/assembly-appendix-release-notes.adoc, stories/topics/proc-aws-deploy-new-vpc.adoc, stories/topics/proc-gcp-deploy-with-new-vpc.adoc
Doc - Write deprecation note for new vpc
https://issues.redhat.com/browse/AAP-16519
=> Added deprecation notice (#579)

downstream/assemblies/platform/assembly-controller-glossary.adoc, downstream/titles/controller/controller-user-guide/master.adoc
Created assemby.
Create section 34 of the Controller user guide
https://issues.redhat.com/browse/AAP-16829
=> Create 'Glossary' section

downstream/assemblies/platform/assembly-controller-glossary.adoc, downstream/titles/controller/controller-user-guide/master.adoc
* Create 'Glossary' section: section 34 of the Controller user guide https://issues.redhat.com/browse/AAP-16829
=> Create 'Glossary' section (#587)

downstream/assemblies/platform/assembly-ug-controller-attributes-custom-notifications.adoc, downstream/modules/platform/ref-controller-supported-attributes.adoc, downstream/titles/controller/controller-user-guide/master.adoc
Adding assembly and module
Create section 29 of the Controller user guide
https://issues.redhat.com/browse/AAP-16685
=> Initial commit:  Adding section 29 to Controller UG

downstream/assemblies/platform/assembly-ug-controller-attributes-custom-notifications.adoc, downstream/modules/platform/ref-controller-supported-attributes.adoc, downstream/titles/controller/controller-user-guide/master.adoc
* Initial commit:  Adding section 29 to Controller UG
Adding assembly and module
Create section 29 of the Controller user guide
https://issues.redhat.com/browse/AAP-16685
* Second commit, section 29
=> Initial commit:  Adding section 29 to Controller UG (#590)

downstream/assemblies/platform/assembly-controller-best-practices.adoc, downstream/titles/controller/controller-user-guide/master.adoc
Added assembly.
Create section 32 of the Controller user guide
https://issues.redhat.com/browse/AAP-16827
=> Create 'Best practices' section.

downstream/assemblies/platform/assembly-controller-best-practices.adoc, downstream/titles/controller/controller-user-guide/master.adoc
* Create 'Best practices' section.
Added assembly.
Create section 32 of the Controller user guide
https://issues.redhat.com/browse/AAP-16827
* Create 'Best Practices' section
Corections
Create section 32 of the Controller user guide
https://issues.redhat.com/browse/AAP-16827
=> Create 'Best practices' section. (#603)

lightspeed/attributes/attributes.adoc
This PR updates the Lightspeed attributes file.
=> Lightspeed attributes update

downstream/titles/release-notes/topics/docs-24.adoc
This PR adds a release note to section 2.6 Ansible Automation Platform Documentation of the release notes to explain the updates made during the Hub Docathon.
=> AAP-15814 - Added a release note regarding the hub docathon changes

downstream/titles/release-notes/topics/docs-24.adoc
This PR backports the changes from #608 to the 2.4 branch.
=> AAP-15814 - [Backport] Added a release note regarding the hub docathon changes

stories/assembly-smazure-install.adoc, stories/assembly-smazure-intro.adoc, stories/topics/con-smazure-application-architecture.adoc, stories/topics/con-smazure-application-deploy.adoc, stories/topics/con-smazure-get-deployment-info.adoc, stories/topics/proc-smazure-deploy-existing-vpc.adoc, stories/topics/proc-smazure-deploy-new-vpc.adoc, stories/topics/proc-smazure-retrieve-admin-password.adoc, stories/topics/proc-smazure-retrieve-lb-addresses.adoc
Add modules
Create framework for self-managed Azure
https://issues.redhat.com/browse/AAP-16221
=> Add modules to self-managed azure framework

stories/assembly-gcp-intro.adoc, stories/assembly-gcp-support.adoc, stories/topics/ref-gcp-supported-changes.adoc
GCP Doc - 14. Support: Suggestions for fixes
https://issues.redhat.com/browse/AAP-14487
=> Changed title and moved section

stories/topics/con-azure-infrastructure-usage.adoc
We have changed the machine type and the minimum count for AAP on Azure.  This pull request adjusts the documentation to reflect the current state of the offer.
=> Adjust machine type and minimum count

lightspeed/assemblies/assembly_assigning-seat-licenses.adoc, lightspeed/assemblies/assembly_configure-code-assistant.adoc, lightspeed/assemblies/assembly_configuring-vscode-extension.adoc, lightspeed/assemblies/assembly_logging-in-lightspeed-admin-portal.adoc, lightspeed/assemblies/assembly_logging-in-out-portal.adoc
Makes include statements lowercase instead of capitalizing them; changes "module" to "modules" in one assembly.
=> Updates include statements

downstream/titles/release-notes/attributes, downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/aap-24.adoc, downstream/titles/release-notes/topics/controller-440.adoc, downstream/titles/release-notes/topics/docs-24.adoc, downstream/titles/release-notes/topics/eda-24.adoc, downstream/titles/release-notes/topics/errata-24-aug-10.adoc, downstream/titles/release-notes/topics/errata-24-aug-28.adoc, downstream/titles/release-notes/topics/errata-24-jul-26.adoc, downstream/titles/release-notes/topics/errata-24-sep-12.adoc, downstream/titles/release-notes/topics/errata-24-sep-24.adoc, downstream/titles/release-notes/topics/hub-464.adoc, downstream/titles/release-notes/topics/operator-240.adoc, downstream/titles/release-notes/topics/platform-intro.adoc, downstream/titles/release-notes/topics/upgrading.adoc
Add the Ansible bundle errata releases to the 2.4 Release Notes
https://issues.redhat.com/browse/AAP-16768
=> Add bundle errata releases to 2.4 release notes

lightspeed/assemblies/assembly-lightspeed-intro.adoc
Hala, please review and delete.
=> Test PR creation [Sayee]

downstream/assemblies/platform/assembly-ag-controller-start-stop-controller.adoc, downstream/modules/platform/con-controller-start-stop.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
* Create section 2 of the Controller AG
Adding assembly and module
Create section 2 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17256
* Adding concept module to assembly
* Second commit, edits to section 2 AG
=> Create section 2 of the Controller AG (#639)

downstream/assemblies/platform/assembly-controller-licensing.adoc, downstream/modules/platform/ref-controller-trial-evaluation.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Added files
Create section 1 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17255
=> Create 'Licensing' section of Controller AG

downstream/assemblies/platform/assembly-controller-licensing.adoc, downstream/modules/platform/ref-controller-trial-evaluation.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Added files
Create section 1 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17255
=> Create 'Licensing' section of Controller AG (#647)

lightspeed/assemblies/assembly-lightspeed-intro.adoc, lightspeed/modules/con_training-data.adoc, lightspeed/modules/con_wca-key-model-id.adoc
Also changes one apostrophe in lightspeed/modules/con_wca-key-model-id.adoc.
=> Adds new module content to introduction

downstream/assemblies/platform/assembly-custom-inventory-scripts.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Created Assembly
Create section 3 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17257
=> Create Section 3 of the Controller Admin Guide

downstream/assemblies/platform/assembly-custom-inventory-scripts.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
* Create Section 3 of the Controller Admin Guide
Created Assembly
Create section 3 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17257
* Create Section 3 of the Controller AG
Correction
Create section 3 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17257
* Create Section 3 of the Controller  AG
Corrected references
Create section 3 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17257
* Create section 3
Corrections
Create section 3 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17257
=> Create Section 3 of the Controller Admin Guide (#655)

lightspeed/titles/lightspeed-release-notes/master.adoc, lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc
Created Lightspeed release notes. 
Files updated:
- aap-docs/lightspeed/titles/lightspeed-release-notes/master.adoc
- aap-docs/lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc
=> Created Ansible Lightspeed release notes

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/errata-24-aug-10.adoc, downstream/titles/release-notes/topics/errata-24-aug-28.adoc, downstream/titles/release-notes/topics/errata-24-jul-26.adoc, downstream/titles/release-notes/topics/errata-24-oct-10.adoc, downstream/titles/release-notes/topics/errata-24-oct-17.adoc, downstream/titles/release-notes/topics/errata-24-oct-19.adoc, downstream/titles/release-notes/topics/errata-24-sep-12.adoc, downstream/titles/release-notes/topics/errata-24-sep-24.adoc
Add Ansible bundle errata releases to 2.4 release notes - Update 2
https://issues.redhat.com/browse/AAP-17459
=> Add next set of errata release bundles to the release notes

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/errata-24-aug-10.adoc, downstream/titles/release-notes/topics/errata-24-aug-28.adoc, downstream/titles/release-notes/topics/errata-24-jul-26.adoc, downstream/titles/release-notes/topics/errata-24-oct-10.adoc, downstream/titles/release-notes/topics/errata-24-oct-17.adoc, downstream/titles/release-notes/topics/errata-24-oct-19.adoc, downstream/titles/release-notes/topics/errata-24-sep-12.adoc, downstream/titles/release-notes/topics/errata-24-sep-24.adoc
Add Ansible bundle errata releases to 2.4 release notes - Update 2
https://issues.redhat.com/browse/AAP-17459
=> Add next set of errata release bundles to the release notes (#659)

lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc, lightspeed/modules/proc_configure-repo-scan.adoc, lightspeed/modules/proc_install-code-bot.adoc, lightspeed/modules/proc_manually-scan-repo.adoc
- assemblies/assembly_using-code-bot-for-suggestions.adoc
- modules/proc_configure-repo-scan.adoc
-  modules/proc_install-code-bot.adoc
- modules/proc_manually-scan-repo.adoc
=> Updated Ansible code bot chapter with latest changes

lightspeed/modules/proc_multi-task-recs.adoc, lightspeed/modules/proc_single-task-recs.adoc
Remove inline settings icon from user guide procedures
=> Lightspeed Remove inline settings icon

downstream/assemblies/hub/assembly_ppah-installation.adoc, downstream/modules/hub/proc_ppah-install-dev.adoc, downstream/modules/hub/proc_ppah-install-ha.adoc, downstream/modules/hub/proc_ppah-online-offline-install.adoc, downstream/modules/hub/proc_ppah-pre-install.adoc, downstream/modules/hub/ref_ppah-access.adoc, downstream/modules/hub/ref_ppah-config.adoc, downstream/titles/ppah/ppah-install/master.adoc
This PR creates and populates an assembly module for the Private Partner Automation Hub Installation Guide. See [AAP-16337](https://issues.redhat.com/browse/AAP-16337) for more info.
=> Creates new assembly for ppah guide

downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
This PR updates the Disconnected Installation documentation based on request in https://issues.redhat.com/browse/AAP-12818.
=> 12818-p2 - Update builder example to version 3 in Disconnected Install doc

downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
This PR backports the changes for #697 to the 2.4 branch.
=> 12818-p2 - Update builder example to version 3 in Disconnected Install doc (#697)

downstream/assemblies/eda/assembly-eda-projects.adoc
Update project path in Chapter 3 of EDA user guide
[DOCS] Misleading description of eda projects
https://issues.redhat.com/browse/AAP-17678
=> Update to project path in EDA user guide

downstream/assemblies/eda/assembly-eda-projects.adoc
Update project path in CHapter 3 of EDA user guide
[DOCS] Misleading description of eda projects
https://issues.redhat.com/browse/AAP-17678
=> Update to project path in EDA user guide (#702)

downstream/modules/platform/ref-postgresql-requirements.adoc
This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-17097.
=> AAP-17097 - removed incorrect example details and added a link

downstream/modules/platform/ref-postgresql-requirements.adoc
This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-15617.
=> AAP-15617 - Removed controller and hub from the postgresql requirements

downstream/modules/platform/ref-postgresql-requirements.adoc
This PR backports the changes from #592 to the 2.4 branch.
=> AAP-17097 [Backport] - removed incorrect example details and added a link (#592)

downstream/titles/hub/install/master.adoc
See [AAP-17151](https://issues.redhat.com/browse/AAP-17151) and [this Slack thread](https://redhat-internal.slack.com/archives/C047VNFEM/p1697132713792449) for more info.
=> Updates postgres version in system requirements table

stories/topics/proc-gcp-deploying-add-extension-nodes.adoc, stories/topics/proc-gcp-generate-add-data-files.adoc, stories/topics/proc-gcp-update-add-data-files.adoc
For issue https://issues.redhat.com/browse/AAP-17634
=> update gcp add extension node

downstream/titles/release-notes/topics/docs-24.adoc
Update broken link in AAP Release Notes and consolidate docs updated as part of docathon
Update broken link in AAP Release Notes
https://issues.redhat.com/browse/AAP-17893
=> Update broken link in AAP Release Notes

downstream/titles/release-notes/topics/docs-24.adoc
Update broken link in AAP Release Notes and consolidate docs updated as part of docathon
Update broken link in AAP Release Notes
https://issues.redhat.com/browse/AAP-17893
=> Update broken link in AAP Release Notes (#732)

stories/assembly-gcp-release-notes-24.adoc, stories/topics/ref-gcp-release-notes-2-4-20231024-00.adoc, titles/release-notes-gcp/stories.adoc
Add an assembly to the GCP release notes for AAP 2.4, and a module for 2.4.20231024-00
=> Add content for 2.4.20231024-00 GCP release notes

downstream/assemblies/platform/assembly-ag-controller-secret-handling.adoc, downstream/modules/platform/con-controller-secret-handling.adoc, downstream/modules/platform/ref-controller-external-access.adoc, downstream/modules/platform/ref-controller-internal-services.adoc, downstream/modules/platform/ref-controller-managed-nodes.adoc, downstream/modules/platform/ref-controller-secret-handling-automation-use.adoc, downstream/modules/platform/ref-controller-secret-handling-operational-use.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
* Create Section 15 of the Controller Admin guide https://issues.redhat.com/browse/AAP-17271
=> Create Section 15 of the Controller Admin guide (#743)

downstream/modules/platform/ref-controller-system-requirements.adoc
This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-16574. See Chapter 4, Section 2 Automation controller system requirements of the preview draft below to verify changes.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP16574/master.html
=> AAP-16574 - Combined requirements for controller/hybrid and execution/hop nodes

downstream/modules/platform/ref-controller-system-requirements.adoc
This PR backports the changes from #698 to the 2.4 branch.
=> AAP-16574 - Combined requirements for controller/hybrid and execution/hop nodes (#698)

downstream/modules/platform/con-controller-database-use-improvements.adoc, downstream/modules/platform/con-controller-job-events-processing.adoc, downstream/modules/platform/con-controller-monitor-controller.adoc, downstream/modules/platform/con-controller-task-manager-settings.adoc, downstream/modules/platform/ref-controller-capacity-planning.adoc, downstream/modules/platform/ref-controller-database-settings.adoc
Corrections
Create section 14 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17269
=> Updates to Section 14 of Controller Admin Guide

downstream/modules/platform/con-controller-database-use-improvements.adoc, downstream/modules/platform/con-controller-job-events-processing.adoc, downstream/modules/platform/con-controller-monitor-controller.adoc, downstream/modules/platform/con-controller-task-manager-settings.adoc, downstream/modules/platform/ref-controller-capacity-planning.adoc, downstream/modules/platform/ref-controller-database-settings.adoc
Corrections
Create section 14 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17269
=> Updates to Section 14 of Controller Admin Guide (#757)

downstream/titles/release-notes/topics/bundle-installer-24-24.adoc
Remove date from bundle installer relase heading
2.4 Release Notes - AAP 2.4-2.4 Bundle Installer Release
https://issues.redhat.com/browse/AAP-18030
=> Remove date from bundle installer release heading

downstream/titles/release-notes/topics/bundle-installer-24-24.adoc
Remove date from bundle installer relase heading
2.4 Release Notes - AAP 2.4-2.4 Bundle Installer Release
https://issues.redhat.com/browse/AAP-18030
=> Remove date from bundle installer release heading (#756)

downstream/assemblies/platform/assembly-ag-controller-security-best-practices.adoc, downstream/modules/platform/con-controller-enforce-separation-duties.adoc, downstream/modules/platform/con-controller-minimize-administrative-accounts.adoc, downstream/modules/platform/con-controller-minimize-system-access.adoc, downstream/modules/platform/con-controller-remove-access-credentials.adoc, downstream/modules/platform/con-controller-understand-architecture.adoc, downstream/modules/platform/ref-controller-audit-functionality.adoc, downstream/modules/platform/ref-controller-available-resources.adoc, downstream/modules/platform/ref-controller-django-password-policies.adoc, downstream/modules/platform/ref-controller-existing-security.adoc, downstream/modules/platform/ref-controller-external-account-stores.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Create section 16 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17272
Affects titles/controller-admin-guide
=> Create Section 16 of the Controller Admin guide

downstream/assemblies/platform/assembly-ag-controller-security-best-practices.adoc, downstream/modules/platform/con-controller-enforce-separation-duties.adoc, downstream/modules/platform/con-controller-minimize-administrative-accounts.adoc, downstream/modules/platform/con-controller-minimize-system-access.adoc, downstream/modules/platform/con-controller-remove-access-credentials.adoc, downstream/modules/platform/con-controller-understand-architecture.adoc, downstream/modules/platform/ref-controller-audit-functionality.adoc, downstream/modules/platform/ref-controller-available-resources.adoc, downstream/modules/platform/ref-controller-django-password-policies.adoc, downstream/modules/platform/ref-controller-existing-security.adoc, downstream/modules/platform/ref-controller-external-account-stores.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
* Create Section 16 of the Controller Admin guide
Create section 16 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17272
Affects titles/controller-admin-guide
* Second commit, adding section 16 to AG
* Second commit, adding section 16 to AG
=> Create Section 16 of the Controller Admin guide (#751)

downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc, downstream/assemblies/platform/ref-controller-expire-sessions.adoc, downstream/modules/platform/ref-controller-analytics-gathering.adoc, downstream/modules/platform/ref-controller-cleanup-old-data.adoc, downstream/modules/platform/ref-controller-clear-sessions.adoc, downstream/modules/platform/ref-controller-clear-tokens.adoc, downstream/modules/platform/ref-controller-cluster-management.adoc, downstream/modules/platform/ref-controller-create-oauth2-token.adoc, downstream/modules/platform/ref-controller-expire-sessions.adoc, downstream/modules/platform/ref-controller-inventory-import.adoc, downstream/modules/platform/ref-controller-revoke-oauth2-token.adoc, downstream/modules/platform/ref-controller-token-session-management.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Created assembly and modules
Create section 17 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17273
=> Create section 17 of Controller Admin Guide

downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc, downstream/assemblies/platform/ref-controller-expire-sessions.adoc, downstream/modules/platform/ref-controller-analytics-gathering.adoc, downstream/modules/platform/ref-controller-cleanup-old-data.adoc, downstream/modules/platform/ref-controller-clear-sessions.adoc, downstream/modules/platform/ref-controller-clear-tokens.adoc, downstream/modules/platform/ref-controller-cluster-management.adoc, downstream/modules/platform/ref-controller-create-oauth2-token.adoc, downstream/modules/platform/ref-controller-expire-sessions.adoc, downstream/modules/platform/ref-controller-inventory-import.adoc, downstream/modules/platform/ref-controller-revoke-oauth2-token.adoc, downstream/modules/platform/ref-controller-token-session-management.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Created assembly and modules
Create section 17 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17273
=> Create section 17 of Controller Admin Guide (#766)

downstream/aap-common/providing-feedback.adoc
Update Jira component in feedback module.
=> Update feedback module

downstream/aap-common/providing-feedback.adoc
Backports #770 to 2.4: Updates Jira component in feedback module.
=> Update feedback module (#770)

downstream/modules/platform/ref-hub-variables.adoc
See [AAP-18084](https://issues.redhat.com/browse/AAP-18084) for more detail.
=> AAP-18084 adds collection count variable to ansible automation hub variables table in appendix

downstream/modules/platform/ref-hub-variables.adoc
* Added ldap variables to hub variables https://issues.redhat.com/browse/AAP-16762
=> Added ldap variables to hub variables (#761)

downstream/assemblies/hub/assembly_ppah-installation.adoc, downstream/modules/hub/proc_ppah-install-dev.adoc, downstream/modules/hub/proc_ppah-pre-install.adoc
Further edits based on SME feedback.
This work is being tracked in [AAH-2793](https://issues.redhat.com/browse/AAH-2793).
=> PPAH: edits based on SME feedback

downstream/assemblies/platform/assembly-platform-install-overview.adoc, downstream/modules/platform/con-aap-installation-prereqs.adoc
Applied editorial suggestions for chapter 1 and 1.1 Editorial changes for chapter 1:
https://issues.redhat.com/browse/AAP-18141
Editorial edits: https://docs.google.com/document/d/1tRNUZxvBDFxPbiPDVGWEywvwV2Eta_5mhk-CvbQIObc/edit
=> Editorial changes for Chapter 1

downstream/assemblies/platform/assembly-platform-install-overview.adoc, downstream/modules/platform/con-aap-installation-prereqs.adoc
* Editorial changes for Chapter 1
Applied editorial suggestions for chapter 1 and 1.1 Editorial changes for chapter 1:
https://issues.redhat.com/browse/AAP-18141
* Added sayee's suggestion
=> Editorial changes for Chapter 1 (#786)

downstream/assemblies/platform/assembly-platform-install-scenario.adoc, downstream/modules/platform/con-ha-hub-installation.adoc, downstream/modules/platform/con-install-scenario-examples.adoc, downstream/modules/platform/con-install-scenario-recommendations.adoc, downstream/modules/platform/proc-apply-selinux-context.adoc, downstream/modules/platform/proc-configure-pulpcore-serivce.adoc, downstream/modules/platform/proc-editing-inventory-file.adoc, downstream/modules/platform/proc-install-ha-hub-selinux.adoc, downstream/modules/platform/ref-ldap-config-on-pah.adoc, downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
Improved the first sentence, adding a missing "by" in the closing sentence
Editorial changes for Chapter 3 Section 1
https://issues.redhat.com/browse/AAP-18116
=> Editorial changes for Chapter 3 Section 1

downstream/assemblies/platform/assembly-platform-install-scenario.adoc, downstream/modules/platform/con-ha-hub-installation.adoc, downstream/modules/platform/con-install-scenario-examples.adoc, downstream/modules/platform/con-install-scenario-recommendations.adoc, downstream/modules/platform/proc-apply-selinux-context.adoc, downstream/modules/platform/proc-configure-pulpcore-serivce.adoc, downstream/modules/platform/proc-editing-inventory-file.adoc, downstream/modules/platform/proc-install-ha-hub-selinux.adoc, downstream/modules/platform/ref-ldap-config-on-pah.adoc, downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
backporting editorial changes for chapter 3 section 1
https://issues.redhat.com/browse/AAP-18116
=> Editorial changes for Chapter 3 Section 1 (#759)

downstream/assemblies/platform/assembly-ag-controller-LDAP-auth.adoc, downstream/assemblies/platform/assembly-ag-controller-set-up-enterprise-authentication.adoc, downstream/modules/platform/proc-controller-change-timeout-auth.adoc, downstream/modules/platform/proc-controller-enable-logging-LDAP.adoc, downstream/modules/platform/proc-controller-set-up-LDAP.adoc, downstream/modules/platform/ref-controller-LDAP-organization-team-mapping.adoc, downstream/modules/platform/ref-controller-referrals.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Added assembly and modules
Create section 23 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17279
=> Create Section 23 of the Controller Admin guide

downstream/assemblies/platform/assembly-ag-controller-LDAP-auth.adoc, downstream/assemblies/platform/assembly-ag-controller-set-up-enterprise-authentication.adoc, downstream/modules/platform/proc-controller-change-timeout-auth.adoc, downstream/modules/platform/proc-controller-enable-logging-LDAP.adoc, downstream/modules/platform/proc-controller-set-up-LDAP.adoc, downstream/modules/platform/ref-controller-LDAP-organization-team-mapping.adoc, downstream/modules/platform/ref-controller-referrals.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
* Create Section 23 of the Controller Admin guide
Added assembly and modules
Create section 23 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17279
* Second commit, adding section 23 to UG
=> Create Section 23 of the Controller Admin guide (#794)

downstream/assemblies/platform/assembly-controller-kerberos-authentication.adoc, downstream/assemblies/platform/assembly-kerberos-authentication.adoc, downstream/modules/platform/ref-controller-AD-and-kerberos-credentials.adoc, downstream/modules/platform/ref-controller-set-up-kerberos-packages.adoc, downstream/modules/platform/ref-controller-work-with-kerberos-tickets.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Created assembly and modules
Create section 25 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17281
=> Create Section 25 of Controller Admin Guide

downstream/assemblies/platform/assembly-controller-kerberos-authentication.adoc, downstream/modules/platform/ref-controller-AD-and-kerberos-credentials.adoc, downstream/modules/platform/ref-controller-set-up-kerberos-packages.adoc, downstream/modules/platform/ref-controller-work-with-kerberos-tickets.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
* Create Section 25 of Controller Admin Guide https://issues.redhat.com/browse/AAP-17281
=> Create Section 25 of Controller Admin Guide (#797)

downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc, downstream/assemblies/platform/assembly-ag-controller-session-limits.adoc, downstream/assemblies/platform/assembly-ag-controller-tips-and-tricks.adoc, downstream/assemblies/platform/assembly-ag-controller-troubleshooting.adoc, downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc, downstream/modules/platform/proc-controller-work-with-session-limits.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Added assembly and modules
Create section 26 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17282
=> Create Section 26 of the Controller Admin guide

downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc, downstream/assemblies/platform/assembly-ag-controller-session-limits.adoc, downstream/assemblies/platform/assembly-ag-controller-tips-and-tricks.adoc, downstream/assemblies/platform/assembly-ag-controller-troubleshooting.adoc, downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc, downstream/modules/platform/proc-controller-work-with-session-limits.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
* Create Section 26 of the Controller Admin guide
Added assembly and modules
Create section 26 of the Controller admin guide
https://issues.redhat.com/browse/AAP-17282
* Second commit, adding section 26 to AG
=> Create Section 26 of the Controller Admin guide (#803)

downstream/modules/platform/proc-aap-create_controller.adoc
This PR addresses the request in https://issues.redhat.com/browse/AAP-14891.
=> AAP-14891 - specified where to select secret keys

downstream/assemblies/platform/assembly-controller-management-jobs.adoc
Fixing local build issue with include file not found
https://issues.redhat.com/browse/AAP-17286
=> Fixing build issue

downstream/assemblies/platform/assembly-controller-management-jobs.adoc
Fixing local build issue with include file not found
https://issues.redhat.com/browse/AAP-17286
=> Fixing build issue (#818)

downstream/assemblies/platform/assembly-controller-execution-environments.adoc, downstream/assemblies/platform/assembly-controller-inventories.adoc, downstream/modules/platform/ref-controller-build-exec-envs.adoc, downstream/modules/platform/ref-controller-ee-definition.adoc
Correction to Execution Environments Definition in Controller UG. Also tidied up execution environments assembly
https://issues.redhat.com/browse/AAP-17707
=> Corrected execution environment definition

downstream/assemblies/platform/assembly-controller-execution-environments.adoc, downstream/assemblies/platform/assembly-controller-inventories.adoc, downstream/modules/platform/ref-controller-build-exec-envs.adoc, downstream/modules/platform/ref-controller-ee-definition.adoc
* Corrected execution environment definition https://issues.redhat.com/browse/AAP-17707
=> Corrected execution environment definition (#820)

downstream/modules/platform/proc-aap-create_controller.adoc
This PR backports the changes for #524 to the 2.4 branch.
=> [Backport] AAP-14891 - specified where to select secret keys (#524)

stories/topics/proc-azure-accessing-aap.adoc
Azure: Add info about notifications on landing page
=> Azure: Add info about notifications on landing page

downstream/modules/platform/proc-controller-sourced-from-project.adoc
Update cross references to Admin Guide in Getting Started and User Guides
https://issues.redhat.com/browse/AAP-18517
=> Updated cross references

downstream/modules/platform/proc-controller-sourced-from-project.adoc
Update cross references to Admin Guide in Getting Started and User Guides
https://issues.redhat.com/browse/AAP-18517
=> Updated cross references (#826)

downstream/modules/hub/proc-tag-pulled-image.adoc
Updated URL to hostname
[DDF] This should be `automation_hub_hostname` as the URL includes the protocol, including the protocol will produce an
https://issues.redhat.com/browse/AAP-18024
=> Update variable name

downstream/modules/hub/proc-tag-pulled-image.adoc
Updated URL to hostname
[DDF] This should be `automation_hub_hostname` as the URL includes the protocol, including the protocol will produce an https://issues.redhat.com/browse/AAP-18024
=> Update variable name (#825)

downstream/modules/platform/ref-ansible-inventory-variables.adoc, downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-eda-controller-variables.adoc, downstream/modules/platform/ref-general-inventory-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
Editorial changes for Appendix A:
https://issues.redhat.com/browse/AAP-18148
=> AAP install Guide editorial revamp - Appendix A.1

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/bundle-installer-24-3.adoc, downstream/titles/release-notes/topics/eda-24.adoc
Add the release notes updates for bundle installer release 2.4-3
2.4 Release Notes - AAP 2.4-3 Bundle Installer Release
https://issues.redhat.com/browse/AAP-18443
=> Release notes for bundle installer release 2.4-3

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/bundle-installer-24-3.adoc, downstream/titles/release-notes/topics/eda-24.adoc
* Release notes for bundle installer release 2.4-3
Add the release notes updates for bundle installer release 2.4-3
2.4 Release Notes - AAP 2.4-3 Bundle Installer Release
https://issues.redhat.com/browse/AAP-18443
* Updates based on peer-review feedback
=> Release notes for bundle installer release 2.4-3 (#835)

downstream/assemblies/platform/assembly-migrate-platform.adoc, downstream/assemblies/platform/assembly-platform-whats-next.adoc, downstream/modules/platform/con-why-automation-mesh.adoc, downstream/modules/platform/con-why-migrate-ansible-29.adoc, downstream/modules/platform/con-why-migrate-ansible-core-213.adoc, downstream/modules/platform/con-why-migrate-venvs-ee.adoc, downstream/modules/platform/proc-update-ee-image-locations.adoc, downstream/modules/platform/proc-verify-controller-installation.adoc, downstream/modules/platform/proc-verify-eda-controller-installation.adoc, downstream/modules/platform/proc-verify-hub-installation.adoc, downstream/modules/platform/ref-controller-configs.adoc, downstream/modules/platform/ref-hub-configs.adoc
All changes were made to imporove readability, searchability, and clarity to the documentation.
Resolves: AAP-18138
See also: AAP-17970
=> Made editorial changes to chapter 3, 3.2-3.6

README.adoc, aap-common/proc-aap-list-available-playbooks.adoc, aap-common/proc-aap-pull-command-container-image.adoc, attributes/attributes.adoc, stories/assembly-gcp-release-notes-24.adoc, stories/assembly-gcp-upgrade.adoc, stories/topics/con-gcp-pull-deploy-container-image.adoc, stories/topics/con-gcp-pull-remove-container-image.adoc, stories/topics/con-gcp-restore-process.adoc, stories/topics/con-gcp-upgrade-backup-process.adoc, stories/topics/con-gcp-use-container-image.adoc, stories/topics/proc-gcp-backup-container-image.adoc, stories/topics/proc-gcp-pull-backup-container-image.adoc, stories/topics/proc-gcp-restore-container-image.adoc, stories/topics/proc-gcp-running-upgrade.adoc, stories/topics/proc-gcp-upgrade-pull-container-image.adoc, stories/topics/ref-gcp-release-notes-2-2-20230215-00.adoc, stories/topics/ref-gcp-release-notes-2-3-20230221-00.adoc, stories/topics/ref-gcp-release-notes-2-4-20230630-00.adoc, stories/topics/ref-gcp-release-notes-2-4-20231024-00.adoc, titles/release-notes-gcp/stories.adoc
=> Clouds: Add GCP release notes

titles/release-notes-gcp/stories.adoc
Update feedback module for GCP release notes.
=> GCP release notes: update feedback module

aap-common/proc-aap-pull-command-container-image.adoc, stories/topics/con-gcp-pull-deploy-container-image.adoc, stories/topics/con-gcp-pull-remove-container-image.adoc, stories/topics/con-gcp-use-container-image.adoc, stories/topics/proc-gcp-backup-container-image.adoc, stories/topics/proc-gcp-pull-backup-container-image.adoc, stories/topics/proc-gcp-restore-container-image.adoc, stories/topics/proc-gcp-upgrade-pull-container-image.adoc
=> Clouds: Update link to GCP release notes

aap-common/proc-aap-list-available-playbooks.adoc, aap-common/proc-aap-playbooks.adoc, aap-common/ref-aap-using-playbooks.adoc
Revert the change from this PR https://github.com/ansible/aap-docs/pull/799
=> revert gcp_manage_label

downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc, downstream/modules/platform/proc-adding-a-subscription-manifest-to-aap-without-an-internet-connection.adoc
Revisions made for the installation guide refactoring effort.
Resolves: AAP-18139
See also: AAP-17970
=> Made editorial revisions for chapter 4

downstream/assemblies/platform/assembly-migrate-platform.adoc, downstream/assemblies/platform/assembly-platform-whats-next.adoc, downstream/modules/platform/con-why-automation-mesh.adoc, downstream/modules/platform/con-why-migrate-ansible-29.adoc, downstream/modules/platform/con-why-migrate-ansible-core-213.adoc, downstream/modules/platform/con-why-migrate-venvs-ee.adoc, downstream/modules/platform/proc-update-ee-image-locations.adoc, downstream/modules/platform/proc-verify-controller-installation.adoc, downstream/modules/platform/proc-verify-eda-controller-installation.adoc, downstream/modules/platform/proc-verify-hub-installation.adoc, downstream/modules/platform/ref-controller-configs.adoc, downstream/modules/platform/ref-hub-configs.adoc
* Made editorial changes to chapter 3, 3.2-3.6
All changes were made to imporove readability, searchability, and clarity to the documentation.
Resolves: AAP-18138
See also: AAP-17970
* Update assembly-migrate-platform.adoc
Fixed punctuation issue.
=> Made editorial changes to chapter 3, 3.2-3.6 (#824)

lightspeed/assemblies/assembly_requesting-task-recommendations.adoc, lightspeed/modules/con_lightspeed-key-features.adoc, lightspeed/modules/proc_install-code-bot.adoc, lightspeed/modules/proc_manually-scan-repo.adoc, lightspeed/modules/proc_multi-task-recs.adoc, lightspeed/modules/proc_provide-feedback.adoc, lightspeed/modules/proc_view-training-matches.adoc, lightspeed/titles/lightspeed-release-notes/docinfo.xml, lightspeed/titles/lightspeed-user-guide/docinfo.xml
This PR includes the following updates:
- Titles of a few topics as per gerund format
- Subtitles of Release Notes and User Guide (earlier they were the Guide names, which was repetitive)
=> Updated titles of few topics per gerund format

aap-common/proc-aap-list-available-playbooks.adoc, aap-common/proc-aap-playbooks.adoc, aap-common/ref-aap-using-playbooks.adoc
Reopening pr https://github.com/ansible/aap-docs/pull/799 to target branch aap-clouds-next 
slack discussion - https://redhat-internal.slack.com/archives/C04HR93SRN1/p1701397380059369?thread_ts=1701263555.289609&cid=C04HR93SRN1
=> update gcp documentation for gcp_manage_labels playbook

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/bundle-installer-24-11.adoc, downstream/titles/release-notes/topics/bundle-installer-24-12.adoc, downstream/titles/release-notes/topics/bundle-installer-24-13.adoc, downstream/titles/release-notes/topics/bundle-installer-24-14.adoc, downstream/titles/release-notes/topics/bundle-installer-24-2.adoc, downstream/titles/release-notes/topics/bundle-installer-24-21.adoc, downstream/titles/release-notes/topics/bundle-installer-24-22.adoc, downstream/titles/release-notes/topics/bundle-installer-24-23.adoc, downstream/titles/release-notes/topics/bundle-installer-24-24.adoc, downstream/titles/release-notes/topics/bundle-installer-24-3.adoc
Update release notes heading hierarchy to raise leveloffset 2 to leveloffset 1 where appropriate and add asynchronous updates dedicated section
https://issues.redhat.com/browse/AAP-18719
=> Update release note heading hierarchy (#857)

downstream/assemblies/central-auth/assembly-configuring-central-auth-generic-oidc-settings.adoc, downstream/assemblies/platform/assembly-network-ports-protocols.adoc, downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc, downstream/modules/dev-guide/proc-downloading-base-ees.adoc, downstream/modules/platform/proc-choosing-obtaining-installer.adoc, downstream/modules/platform/proc-controller-adding-an-instance.adoc, downstream/modules/platform/proc-create-secret-key-secret.adoc, downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc, downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc, downstream/modules/platform/proc-installing-with-internet.adoc, downstream/modules/platform/proc-installing-without-internet.adoc
Corrected AAP to attribute
Remove AAP acronym from documentation
https://issues.redhat.com/browse/AAP-17399
=> AAP acronym removed

downstream/assemblies/central-auth/assembly-configuring-central-auth-generic-oidc-settings.adoc, downstream/assemblies/platform/assembly-network-ports-protocols.adoc, downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc, downstream/modules/dev-guide/proc-downloading-base-ees.adoc, downstream/modules/platform/proc-choosing-obtaining-installer.adoc, downstream/modules/platform/proc-controller-adding-an-instance.adoc, downstream/modules/platform/proc-create-secret-key-secret.adoc, downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc, downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc, downstream/modules/platform/proc-installing-with-internet.adoc, downstream/modules/platform/proc-installing-without-internet.adoc
Corrected AAP to attribute
Remove AAP acronym from documentation
https://issues.redhat.com/browse/AAP-17399
=> AAP acronym removed (#861)

downstream/titles/release-notes/topics/aap-24.adoc
Update release notes to include GA of AAP on IBM Power, IBM Z, and IBM LinuxONE architectures
Updating release notes documentation for the GA of AAP on Power and Z
https://issues.redhat.com/browse/AAP-16503
=> Update release notes to include GA of AAP on Power and Z (#871)

lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc, lightspeed/modules/proc_troubleshooting-code-bot.adoc
This PR addresses JIRA issue https://issues.redhat.com/browse/AAP-18291.
Changes:
- Added troubleshooting info. for cleaning up bot PRs
=> AAP-18291: Added troubleshooting info. for cleaning up bot PRs

downstream/modules/platform/con-ha-hub-installation.adoc, downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc, downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc, downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc, downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc, downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc, downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc, downstream/modules/platform/ref-standalone-hub-ext-database-customer-provided.adoc, downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc, downstream/modules/platform/ref-standalone-hub-inventory.adoc
Removed quotes
[DOC] Database port definition should match default inventory file
https://issues.redhat.com/browse/AAP-18919
=> Corrected port definitions

downstream/modules/platform/con-ha-hub-installation.adoc, downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc, downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc, downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc, downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc, downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc, downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc, downstream/modules/platform/ref-standalone-hub-ext-database-customer-provided.adoc, downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc, downstream/modules/platform/ref-standalone-hub-inventory.adoc
* Corrected port definitions: Removed quotes [DOC] Database port definition should match default inventory file https://issues.redhat.com/browse/AAP-18919
=> Corrected port definitions (#889)

downstream/modules/platform/ref-controller-use-credentials-in-playbooks.adoc
Replaced tower with controller
Change TOWER to CONTROLLER in variable names
https://issues.redhat.com/browse/AAP-18982
=> Updated variable names

downstream/modules/platform/ref-controller-use-credentials-in-playbooks.adoc
Change TOWER to CONTROLLER in variable names
https://issues.redhat.com/browse/AAP-18982
=> Updated variable names (#893)

downstream/modules/platform/ref-controller-system-requirements.adoc
Add umask requirement to controller system requirements
[Cee.Next] Add the umask requirement for AAP 2.X documentation
https://issues.redhat.com/browse/AAP-17977
=> Add umask requirement to controller system requirements

downstream/modules/platform/ref-controller-system-requirements.adoc
Add umask requirement to controller system requirements
[Cee.Next] Add the umask requirement for AAP 2.X documentation
https://issues.redhat.com/browse/AAP-17977
=> Add umask requirement to controller system requirements (#896)

downstream/modules/platform/proc-controller-attaching-subscriptions.adoc, downstream/titles/controller/controller-admin-guide/docinfo.xml, downstream/titles/controller/controller-admin-guide/master.adoc
Building admin guide for editorial review and making corrections
Build automation controller admin guide for editorial review
https://issues.redhat.com/browse/AAP-18983
Affects `titles/admin-controller-guide`
=> Corrections to controller admin guide

downstream/modules/platform/proc-controller-attaching-subscriptions.adoc, downstream/titles/controller/controller-admin-guide/docinfo.xml, downstream/titles/controller/controller-admin-guide/master.adoc
https://issues.redhat.com/browse/AAP-18983
=> Corrections to controller admin guide (#909)

downstream/modules/platform/ref-controller-metrics-monitoring.adoc, downstream/modules/platform/ref-controller-settings-to-modify-events.adoc, downstream/modules/platform/ref-scaling-control-nodes.adoc
Per [AAP-19239](https://issues.redhat.com/browse/AAP-19239) fixed formatting issues in [Chapter 14. Performance tuning for automation controller](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/automation_controller_administration_guide/assembly-controller-improving-performance)
=> AAP-19239 fix formatting issues for ch 14 Controller Admin Guide

downstream/modules/platform/ref-controller-metrics-monitoring.adoc, downstream/modules/platform/ref-controller-settings-to-modify-events.adoc, downstream/modules/platform/ref-scaling-control-nodes.adoc
2.4 backport of [PR 917](https://github.com/ansible/aap-docs/pull/917)
=> AAP-19239 fix formatting issues for ch 14 Controller Admin Guide (#917)

downstream/modules/platform/con-controller-overview-details.adoc, downstream/modules/platform/proc-controller-create-job-template.adoc, downstream/modules/platform/ref-controller-credential-machine.adoc, downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc
This PR fixes broken links in the Controller user guide. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
=> AAP-15176: Fix broken links in controller user guide

lightspeed/modules/con-lightspeed-about.adoc, lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-19320. 
Changes:
- Added info. About AAP and IBM WCA trial and paid plans
=> AAP-19320: Add info. About AAP and IBM WCA trial and paid plans

downstream/modules/platform/ref-controller-clear-sessions.adoc
See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.
=> AAP-15176: broken link fix in controller admin guide

downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc, downstream/modules/platform/proc-uninstalling-containerized-aap.adoc, downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
These updates reflect new development functionality
Partially resolves: AAP-18875
See also: ANSTRAT-246
=> AAP-18875 Update containerized install guide after TP refresh

attributes/attributes.adoc, stories/topics/con-azure-about.adoc
Update the Azure documentation: Automation mesh is now included in the Azure offering.
=> Azure: AAP-18006 Automation mesh now available on Azure

downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc, downstream/modules/platform/proc-uninstalling-containerized-aap.adoc, downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
These updates reflect new development functionality
Partially resolves: AAP-18875
See also: ANSTRAT-246
=> AAP-18875 Update containerized install guide after TP refresh (#939)

downstream/modules/platform/ref-controller-clear-sessions.adoc
This PR adds the changes in [PR 938](https://github.com/ansible/aap-docs/pull/938) to the 2.4 branch.
=> backport to 2.4: AAP-15176 fix link in controller admin guide

downstream/modules/platform/con-install-scenario-recommendations.adoc, downstream/modules/platform/proc-verify-controller-installation.adoc, downstream/modules/platform/proc-verify-eda-controller-installation.adoc, downstream/modules/platform/proc-verify-hub-installation.adoc
This PR backports the changes for #927 to the 2.4 branch.
=> [Backport] AAP-16022 - updated the information to state admin is default userid (#927)

downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
This PR addresses the change requested in https://issues.redhat.com/browse/AAP-16378.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP16378/master.html
=> AAP-16378 Added ldap-ca.crt for the LDAP certificate selection

downstream/modules/platform/proc-controller-create-job-template.adoc
Link for passing variables on the CLI leads to a 404
https://issues.redhat.com/browse/AAP-19499
=> Corrrected links in Controller  UG

downstream/modules/platform/proc-controller-create-job-template.adoc
Link for passing variables on the CLI leads to a 404
https://issues.redhat.com/browse/AAP-19499
=> Corrrected links in Controller  UG (#952)

downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
This PR backports the changes from #594 to the 2.3 branch.
=> [Backport] - AAP-16378 Added ldap-ca.crt for the LDAP certificate selection (#594)

downstream/modules/platform/ref-ldap-config-on-pah.adoc
AAP-19350 correcting incorrect steps in the install guide. I also reformatted steps to highlight mandatory steps from optional.
https://issues.redhat.com/browse/AAP-19350
=> Backport 2.4 966

README.adoc
Updating the repo organization chart.
Updating the directory information bullet points. 
https://issues.redhat.com/browse/AAP-19778
=> Updating Repository Organization chart and bullets

downstream/modules/platform/proc-installing-hub-using-operator.adoc
Updated example for changes to web_replicas and task_replicas as requested in https://issues.redhat.com/browse/AAP-17100.
Link to preview draft (VPN Required):  http://file.rdu.redhat.com/~ddacosta/AAP17100/master.html
=> AAP17100 - Updated web and task replicas

downstream/modules/platform/proc-installing-hub-using-operator.adoc
This PR backports the changes from #919 to the 2.4 branch and includes the following change:
* AAP17100 - Updated web and task replicas
=> [Backport] AAP17100 - Updated web and task replicas (#919)

downstream/modules/platform/proc-aap-controller-backup.adoc, downstream/modules/platform/proc-aap-controller-restore.adoc, downstream/modules/platform/proc-aap-hub-backup.adoc
This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-14300.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP14300/master.html
=> AAP-14300 Add verification steps for controller backup and restore

downstream/assemblies/builder/assembly-definition-file-breakdown.adoc, downstream/modules/builder/con-additional-build-files.adoc, downstream/modules/builder/con-additional-custom-build-steps.adoc, downstream/modules/builder/con-building-definition-file.adoc, downstream/modules/builder/con-container_file.adoc, downstream/modules/builder/con-definition-dependencies.adoc, downstream/modules/builder/con-galaxy-dependencies.adoc, downstream/modules/builder/con-optional-build-command-arguments.adoc, downstream/modules/builder/con-python-dependencies.adoc, downstream/modules/builder/con-system-dependencies.adoc, downstream/modules/builder/con-why-builder.adoc, downstream/modules/builder/proc-installing-builder.adoc, downstream/modules/builder/ref-definition-file-images.adoc
This PR updates content on Builder in chapter 2 of Creating and Consuming Execution Environments. See [AAP-17700](https://issues.redhat.com/browse/AAP-17700) for more info.
=> AAP-17700: Updates to Builder documentation 

downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc, downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc, downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
Updated signing script and procedures in line with [AAP-10305](https://issues.redhat.com/browse/AAP-10305)
Updated content in [Google doc](https://docs.google.com/document/d/17S1ZrkTMpFZV4Cpc9x9QqamdIKt5_SJdIhmyTkj_d40/edit)
- proc-configuring-the-client-to-verify-signatures.adoc
- proc-deploying-your-system-for-container-signing.adoc
- proc-pushing-container-images-from-your-local.adoc
=> AAP-10305 modified hub signing procedures

lightspeed/modules/proc_manually-scan-repo.adoc
This PR addresses JIRA issue: https://issues.redhat.com/browse/AAP-20092
Changes made
Specified the repo Settings button for Ansible code bot manual scan.
=> AAP-20092: Specified the repo Settings button for manual scan

downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
See [AAP-10252](https://issues.redhat.com/browse/AAP-10252) for more details.
=> AAP-10252: add note to remind user not to leave fields blank

downstream/modules/builder/con-additional-build-files.adoc, downstream/modules/builder/con-building-definition-file.adoc, downstream/modules/builder/ref-scenario-using-authentication-ee.adoc
See [AAP-17700](https://issues.redhat.com/browse/AAP-17700) for context.
=> AAP-17700: Further updates to Builder documentation

downstream/modules/platform/ref-mesh-minimum-resilient-config.adoc, downstream/modules/platform/ref-mesh-segregated-execution_nodes.adoc
Mesh Document example is not correct it is missing information.
https://issues.redhat.com/browse/AAP-20181
=> Correct mesh examples

downstream/modules/platform/ref-mesh-minimum-resilient-config.adoc, downstream/modules/platform/ref-mesh-segregated-execution_nodes.adoc
Mesh Document example is not correct it is missing information. https://issues.redhat.com/browse/AAP-20181
=> Correct mesh examples (#995)

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
Add bundle installer 2.4-4 to release notes
2.4 Release Notes - AAP 2.4-4 Bundle Installer Release
https://issues.redhat.com/browse/AAP-20389
=> Add bundle installer 2.4-4 to release notes

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
Add bundle installer 2.4-4 to release notes
2.4 Release Notes - AAP 2.4-4 Bundle Installer Release
https://issues.redhat.com/browse/AAP-20389
=> Add bundle installer 2.4-4 to release notes (#997)

downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
See [AAP-19173](https://issues.redhat.com/browse/AAP-19173) for more info.
=> AAP-19173: correct formatting errors in Configuring Central Authentication Generic OICD

downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
This PR backports the changes from [PR 1007](https://github.com/ansible/aap-docs/pull/1007) to the 2.4 branch. See [AAP-19173](https://issues.redhat.com/browse/AAP-19173) for more info.
=> BP to 2.4: AAP-19173 correct formatting errors (#1007)

downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
This PR is associated with [PR 1007](https://github.com/ansible/aap-docs/pull/1007) and [PR 1010](https://github.com/ansible/aap-docs/pull/1010). See [AAP-19173](https://issues.redhat.com/browse/AAP-19173) for more info. 
This edit has already been made in the 2.4 backport.
=> AAP-19173: change "click on" to "click" per style guidelines

downstream/assemblies/platform/assembly-controller-credentials.adoc, downstream/assemblies/platform/assembly-controller-dashboard.adoc, downstream/assemblies/platform/assembly-controller-inventories.adoc, downstream/assemblies/platform/assembly-controller-job-templates.adoc, downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc, downstream/modules/platform/proc-controller-add-groups-hosts.adoc, downstream/modules/platform/proc-controller-create-credential.adoc, downstream/modules/platform/proc-controller-create-inventory.adoc, downstream/modules/platform/proc-controller-importing-subscriptions.adoc, downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc, downstream/modules/platform/proc-controller-review-organizations.adoc, downstream/modules/platform/proc-controller-run-job-template.adoc, downstream/modules/platform/proc-controller-viewing-dashboard.adoc, downstream/titles/controller/controller-getting-started/master.adoc, downstream/titles/controller/controller-user-guide/master.adoc
Link and style corrections in Controller GS guide
Update links in Getting started with controller user guide
https://issues.redhat.com/browse/AAP-20883
Affects `titles/controller-getting-started`
=> Corrections in Controller GS guide

downstream/assemblies/platform/assembly-controller-credentials.adoc, downstream/assemblies/platform/assembly-controller-dashboard.adoc, downstream/assemblies/platform/assembly-controller-inventories.adoc, downstream/assemblies/platform/assembly-controller-job-templates.adoc, downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc, downstream/modules/platform/proc-controller-add-groups-hosts.adoc, downstream/modules/platform/proc-controller-create-credential.adoc, downstream/modules/platform/proc-controller-create-inventory.adoc, downstream/modules/platform/proc-controller-importing-subscriptions.adoc, downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc, downstream/modules/platform/proc-controller-review-organizations.adoc, downstream/modules/platform/proc-controller-run-job-template.adoc, downstream/modules/platform/proc-controller-viewing-dashboard.adoc, downstream/titles/controller/controller-getting-started/master.adoc, downstream/titles/controller/controller-user-guide/master.adoc
* Corrections in Controller GS guide
Link and style corrections in Controller GS guide
Update links in Getting started with controller user guide
https://issues.redhat.com/browse/AAP-20883
Affects `titles/controller-getting-started`
=> Corrections in Controller GS guide (#1021)

downstream/modules/platform/con-install-scenario-recommendations.adoc
Removed database support statement until a decision is made about the support.
Please correct the docs for AAP2.4 state : Internal databases [database] are not supported.
https://issues.redhat.com/browse/AAP-20847
=> Removed statement on database support (#1025)

downstream/modules/analytics/proc-calculating-automation.adoc
Replace plain text with attribute for content in the analytics module
=> Replace plain text with attribute for analytics module

downstream/modules/analytics/proc-calculating-automation.adoc
Incorporates feedback update from the 2.4 backport into main: https://github.com/ansible/aap-docs/pull/1029
=> updates based on peer review feedback

downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc, downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc, downstream/modules/platform/proc-controller-create-job-template.adoc, downstream/modules/platform/proc-controller-create-workflow-template.adoc
Adding clarity around limits for workflow and job templates
Workflow limit not working as expected
https://issues.redhat.com/browse/AAP-15512
=> Update docs for workflow and job template limits

downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc, downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc, downstream/modules/platform/proc-controller-create-job-template.adoc, downstream/modules/platform/proc-controller-create-workflow-template.adoc
* Update docs for workflow and job template limits
Adding clarity around limits for workflow and job templates
Workflow limit not working as expected
https://issues.redhat.com/browse/AAP-15512
* Third commit
=> Update docs for workflow and job template limits (#1032)

downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Removed duplicate hub parameters and added missing EDA parameters
Running the script as described fails
https://issues.redhat.com/browse/AAP-20952
=> Removed duplicates and added missing lines

downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
* Removed duplicates and added missing lines
Removed duplicate hub parameters and added missing EDA parameters
Running the script as described fails
https://issues.redhat.com/browse/AAP-20952
* Removed duplicates and added missing lines
Corrections from tech review
Running the script as described fails
https://issues.redhat.com/browse/AAP-20952
* Removed duplicates and added missing lines
Correction
Running the script as described fails
https://issues.redhat.com/browse/AAP-20952
* Removed duplicates and added missing lines
Correction
Running the script as described fails
https://issues.redhat.com/browse/AAP-20952
=> Removed duplicates and added missing lines (#1027)

downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc, downstream/modules/platform/con-alternative-capacity-limits.adoc, downstream/modules/platform/con-pod-specification-mods.adoc, downstream/modules/platform/proc-configure-controller-OCP.adoc, downstream/modules/platform/proc-customizing-pod-specs.adoc, downstream/modules/platform/proc-enable-pods-ref-images.adoc, downstream/modules/platform/proc-set-custom-pod-timeout.adoc, downstream/modules/platform/proc-specify-nodes-job-execution.adoc, downstream/modules/platform/ref-assign-pods-to-nodes.adoc, downstream/modules/platform/ref-container-resource-requirements.adoc, downstream/modules/platform/ref-requests-limits.adoc, downstream/modules/platform/ref-resource-management-pods-containers.adoc, downstream/modules/platform/ref-resource-types.adoc, downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc, downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
Performing an editorial review of the [Red Hat Ansible Automation Platform Performance Considerations for Operator Based Installations](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_performance_considerations_for_operator_based_installations/index) doc.
* Considerations for OCP editorial review
=> AAP-20823 Editorial review on Considerations OCP doc (#1038)

downstream/assemblies/platform/assembly-planning-mesh.adoc, downstream/modules/platform/con-about-automation-mesh.adoc, downstream/modules/platform/con-automation-mesh-node-types.adoc, downstream/modules/platform/proc-defining-node-types.adoc, downstream/titles/automation-mesh/docinfo.xml, downstream/titles/automation-mesh/master.adoc
* Renaming mesh guide https://issues.redhat.com/browse/AAP-20269
=> Renaming mesh guide (#993)

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/modules/hub/proc-configure-proxy-remote.adoc, downstream/modules/hub/proc-set-community-remote.adoc, downstream/modules/hub/proc-set-rhcertified-remote.adoc
This change was requested in [AAP-19025](https://issues.redhat.com/browse/AAP-19025); see that ticket for more details.
=> AAP-19025 add procedure for configuring proxy settings in automation hub

downstream/modules/platform/ref-controller-system-requirements.adoc
Added minimum requirements and statement on recommended CPU and RAM levels to planning docs.
'system requirements' section needs more explanation for resource management
https://issues.redhat.com/browse/AAP-18552
=> Added minimum requirements to doc

downstream/modules/platform/ref-controller-system-requirements.adoc
* Added minimum requirements to doc
Added minimum requirements and statement on recommended CPU and RAM levels to planning docs.
'system requirements' section needs more explanation for resource management
https://issues.redhat.com/browse/AAP-18552
* Added minimum requirements to doc
Correction
'system requirements' section needs more explanation for resource management
https://issues.redhat.com/browse/AAP-18552
=> Added minimum requirements to doc (#1014)

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/eda-24.adoc, downstream/titles/release-notes/topics/installer-24-6.adoc
Add installer-2.4-6 release notes
2.4 Release Notes - AAP 2.4-6 Installer Release
https://issues.redhat.com/browse/AAP-21131
=> Add installer-2.4-6 release notes

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/eda-24.adoc, downstream/titles/release-notes/topics/installer-24-6.adoc
* Add installer-2.4-6 release notes
Add installer-2.4-6 release notes
2.4 Release Notes - AAP 2.4-6 Installer Release
https://issues.redhat.com/browse/AAP-21131
=> Add installer-2.4-6 release notes (#1056)

downstream/modules/platform/proc-creating-the-custom-execution-environment-definition.adoc, downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Made changes to process steps by separating and creating new steps. Created four new sections, and pared down the entire document from the previous version due to simplified installation and configuration development. The main changes can be found here:
https://github.com/ansible/aap-docs/pull/1003/files?diff=split&w=0 The initial PR had to be closed due to Github not registering the commits properly.
Partially resolves: #1003
=> AAP-17672 Made updates to process steps.

downstream/modules/platform/proc-creating-the-custom-execution-environment-definition.adoc, downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Made changes to process steps by separating and creating new steps. Created four new sections, and pared down the entire document from the previous version due to simplified installation and configuration development. The main changes can be found here:
https://github.com/ansible/aap-docs/pull/1003/files?diff=split&w=0 The initial PR had to be closed due to Github not registering the commits properly.
Partially resolves: #1003
=> AAP-17672 Made updates to process steps. (#1051)

downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
* Added information to inventory variable.
doc update inventory file variables
https://issues.redhat.com/browse/AAP-21254
* Added information to inventory file
Removed unnecessary file
doc update inventory file variables
https://issues.redhat.com/browse/AAP-21254
* Add information to inventory variable
Correction
doc update inventory file variables
https://issues.redhat.com/browse/AAP-21254
* Added information to inventory variables
Corrections and also changes to the controller instance of this variable
doc update inventory file variables
https://issues.redhat.com/browse/AAP-21254
`:
=> Added information to inventory variable. (#1053)

downstream/modules/platform/ref-controller-variables.adoc
Changed recptor to receptor
Typo in Installation Guide
https://issues.redhat.com/browse/AAP-21430
=> Corrected typo (#1071)

downstream/modules/hub/proc-add-user-to-group.adoc, downstream/modules/hub/proc-assigning-permissions.adoc, downstream/modules/hub/proc-configure-automation-hub-server-gui.adoc, downstream/modules/hub/proc-configure-content-signing-on-pah.adoc, downstream/modules/hub/proc-create-credential.adoc, downstream/modules/hub/proc-create-groups.adoc, downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc, downstream/modules/hub/proc-shared-filesystem.adoc, downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
=> Replace plain text with attributes for content in the hub module (#1073)

downstream/assemblies/platform/assembly-controller-api-access-resources.adoc, downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc, downstream/assemblies/platform/assembly-controller-api-browsing-api.adoc, downstream/assemblies/platform/assembly-controller-api-conventions.adoc, downstream/assemblies/platform/assembly-controller-api-filter.adoc, downstream/assemblies/platform/assembly-controller-api-pagination.adoc, downstream/assemblies/platform/assembly-controller-api-readonly-fields.adoc, downstream/assemblies/platform/assembly-controller-api-search.adoc, downstream/assemblies/platform/assembly-controller-api-sorting.adoc, downstream/assemblies/platform/assembly-controller-api-tools.adoc, downstream/modules/platform/ref-controller-api-tools.adoc, downstream/titles/controller/controller-api-guide/master.adoc
* Create section 1 of controller API guide
Adding content for section 1 as well as assemblies to master.adoc
Create section 1 of the Automation Controller API Guide
https://issues.redhat.com/browse/AAP-21361
* Edits per peer review
=> Create section 1 of controller API guide (#1075)

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/bundle-installer-24-6.adoc, downstream/titles/release-notes/topics/installer-24-6.adoc
Also ensure bundle installer and installer sections are correct and remove release types.
2.4 Release Notes - AAP 2.4-6 Bundle Installer Release
https://issues.redhat.com/browse/AAP-21251
=> Add bundle installer 2.4-6 release notes

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/bundle-installer-24-6.adoc, downstream/titles/release-notes/topics/installer-24-6.adoc
Also ensure bundle installer and installer sections are correct
2.4 Release Notes - AAP 2.4-6 Bundle Installer Release
https://issues.redhat.com/browse/AAP-21251
=> Add bundle installer 2.4-6 release notes (#1083)

downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc, downstream/modules/platform/ref-removing-instances.adoc
Removed Mesh Ingress details for now.
Temporarily remove Mesh Ingress from Operator-Mesh guide
https://issues.redhat.com/browse/AAP-21593
=> Commented out include statement (#1092)

aap-common/assembly-appendix-release-notes.adoc, attributes/attributes.adoc, stories/assembly-gcp-release-notes-24.adoc, stories/topics/ref-gcp-release-notes-2-4-20240215-00.adoc
For issue https://issues.redhat.com/browse/AAP-17419
=> New SMAC GCP offer for CVE fixes - 2.4.20240215

aap-common/assembly-appendix-release-notes.adoc, attributes/attributes.adoc, stories/assembly-gcp-release-notes-24.adoc, stories/topics/ref-gcp-release-notes-2-4-20240215-00.adoc
* New SMAC GCP offer for CVE fixes
Signed-off-by: Chris Ahl <cahl@redhat.com>
Backports #1033 to `aap-clouds-2.4`
=> clouds-2.4 New SMAC GCP offer for CVE fixes - 2.4.20240215 (#1033)

downstream/assemblies/platform/assembly-controller-api-access-resources.adoc, downstream/assemblies/platform/assembly-controller-api-readonly-fields.adoc, downstream/modules/platform/con-controller-api-identifier-format-protocol.adoc, downstream/modules/platform/con-controller-api-readonly-fields.adoc, downstream/modules/platform/ref-controller-api-config-settings.adoc
Adding content for sections 8 and 9
Create sections 8 and 9 of the Automation Controller API Guide
https://issues.redhat.com/browse/AAP-21477
=> Create sections 8 and 9 of controller API guide

downstream/assemblies/platform/assembly-controller-api-access-resources.adoc, downstream/assemblies/platform/assembly-controller-api-readonly-fields.adoc, downstream/modules/platform/con-controller-api-identifier-format-protocol.adoc, downstream/modules/platform/con-controller-api-readonly-fields.adoc, downstream/modules/platform/ref-controller-api-config-settings.adoc
* Create sections 8 and 9 of controller API guide
Adding content for sections 8 and 9
Create sections 8 and 9 of the Automation Controller API Guide
https://issues.redhat.com/browse/AAP-21477
=> Create sections 8 and 9 of controller API guide (#1100)

.gitignore
Update `.gitignore` to ignore VSCode and other artefacts.
=> 2.4 Update .gitignore

.gitignore
Update .gitignore to ignore .vscode directory
=> Update .gitignore to ignore .vscode directory

downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
Typo in the Automation Controller Administrator Guide https://issues.redhat.com/browse/AAP-21370
=> Correcting Typo

downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
Typo in the Automation Controller Administrator Guide https://issues.redhat.com/browse/AAP-21370
=> Correcting Typo (#1114)

downstream/modules/platform/proc-building-the-custom-execution-environment.adoc
Backports #1062 to 2.4
* AAP-17672 Made corrections to number formatting.
=> 2.4 Correct num (#1062)

downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc, downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
* AAP-17672 upated numbering, and added content.
Added a parapragh to section 4.12 "Building an ee in a disconnected environment." Fixed a numbering issue in section 4.12.1.
Resolves: AAP-17672
See also: #1058, #1059
* Update con-building-an-execution-environment-in-a-disconnected-environment.adoc
* Update con-building-an-execution-environment-in-a-disconnected-environment.adoc
=> AAP-17672 upated numbering, and added content. (#1123)

downstream/assemblies/platform/assembly-controller-instances.adoc, downstream/modules/platform/proc-define-mesh-node-types.adoc, downstream/modules/platform/proc-set-up-virtual-machines.adoc, downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
Updated the Managing Instances chapter with up to date procedures
Update Controller Information
https://issues.redhat.com/browse/AAP-21769
=> Combine operator-mesh info with Controller Admin

downstream/assemblies/platform/assembly-controller-instances.adoc, downstream/modules/platform/proc-define-mesh-node-types.adoc, downstream/modules/platform/proc-set-up-virtual-machines.adoc, downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
* Combine operator-mesh info with Controller Admin
Updated the Managing Instances chapter with up to date procedures
Update Controller Information
https://issues.redhat.com/browse/AAP-21769
* Combine operator-mesh info with Controller Admin
Correction
Update Controller Information
https://issues.redhat.com/browse/AAP-21769
=> Combine operator-mesh info with Controller Admin (#1127)

downstream/assemblies/hub/assembly-managing-collections-hub.adoc
Added a link to content creation material
Developing collection documentation needs more information about required files before uploading a collection to automation hub.
https://issues.redhat.com/browse/AAP-19550
=> Added link to Managing Content

downstream/assemblies/hub/assembly-managing-collections-hub.adoc
Added a link to content creation material
Developing collection documentation needs more information about required files before uploading a collection to automation hub.
https://issues.redhat.com/browse/AAP-19550
=> Added link to Managing Content (#1131)

downstream/modules/platform/proc-change-ssl-installer.adoc, downstream/modules/platform/ref-eda-controller-variables.adoc
See [AAP-20863](https://issues.redhat.com/browse/AAP-20863) for more info.
=> AAP-20863: Adds EDA controller variables to procedure for changing SSL certification

downstream/assemblies/platform/assembly-controller-topology-viewer.adoc, downstream/assemblies/platform/assembly-custom-inventory-scripts.adoc, downstream/modules/platform/con-why-automation-mesh.adoc, downstream/modules/platform/proc-controller-access-topology-viewer.adoc, downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
* Modified link addresses https://issues.redhat.com/browse/AAP-21262
=> Modified link addresses (#1138)

downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Update our LDAP Docs with local user information
https://issues.redhat.com/browse/AAP-16323
=> Update controller admin guide LDAP info

downstream/modules/platform/ref-controller-smart-inventories.adoc
Removed information about changing variables
Clarify documentation for editing host/group variables in Smart Inventories
https://issues.redhat.com/browse/AAP-10694
=> Altered smart inventory details

downstream/modules/platform/ref-controller-smart-inventories.adoc
* Altered smart inventory details
Removed information about changing variables
Clarify documentation for editing host/group variables in Smart Inventories
https://issues.redhat.com/browse/AAP-10694
* Altered smart inventory details
Corrections from tech review
Clarify documentation for editing host/group variables in Smart Inventories
https://issues.redhat.com/browse/AAP-10694
=> Altered smart inventory details (#1128)

stories/assembly-azure-install.adoc, stories/topics/proc-azure-resource-providers.adoc
Updated doc requirements for installing Ansible on Azure:
https://issues.redhat.com/browse/AAP-19996
=> Add RP requirements in Azure docs

downstream/modules/builder/con-about-ee.adoc, downstream/modules/builder/con-container_file.adoc, downstream/modules/builder/con-ee-precedence.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/builder/proc-push-execenv-to-hub.adoc, downstream/modules/builder/ref-build-args-base-image.adoc
This PR is specific to the 2.3 branch and version of our docs. The `main` PR is #1036.
Affects the following title: `builder`.
=> Replace plain text with attributes for content in the builder module

README.adoc
Update repo links in README.md to point to the aap-docs repo.
=> Update repo URL in README

README.adoc
=> Update repo URL in README (#1161)

README.adoc
=> 2.1 Update repo URL in README (#1161)

README.adoc
=> 2.0-ea Update repo URL in README (#1161)

README.adoc
=> 1.2 Update repo URL in README (#1161)

downstream/modules/platform/ref-controller-dependencies.adoc
Correction
Make edits to Controller User Guide
https://issues.redhat.com/browse/AAP-21967
=> Correction to Controller UG

downstream/modules/platform/ref-controller-dependencies.adoc
Correction
Make edits to Controller User Guide
https://issues.redhat.com/browse/AAP-21967
=> Correction to Controller UG (#1171)

downstream/attributes/attributes.adoc
Update OCPLatest version to 4.15
=> Update OCPLatest version to 4.15

downstream/attributes/attributes.adoc
Backports #1174 to 2.4
Update OCPLatest version to 4.15
=> 2.4 Update OCPLatest version to 4.15 (#1174)

stories/topics/proc-azure-update-route-tables.adoc
Removing the Azure DNS allowlist section since it's no longer needed.
https://issues.redhat.com/browse/AAP-21911
=> Removing unnecessary Azure DNS allowlist.

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
See [AAP-19094](https://issues.redhat.com/browse/AAP-19094) for more info.
=> AAP-19094: adds API URL to EDA user guide

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
This PR backports changes from [PR 1188](https://github.com/ansible/aap-docs/pull/1188) to the 2.4 branch. See [AAP-19094](https://issues.redhat.com/browse/AAP-19094) for more info. 
* adds API URL to EDA user guide
* formatting fixes
=> AAP-19094: adds API URL to EDA user guide (#1188)

downstream/modules/platform/proc-controller-use-an-exec-env.adoc, downstream/modules/platform/ref-controller-run-the-builder.adoc
Small initial change
Clearer documentation concerning execution environment pull policy
https://issues.redhat.com/browse/AAP-12534
=> Changes to execution environment pull policy

downstream/modules/platform/proc-controller-use-an-exec-env.adoc
* Changes to execution evironment pull policy
Small initial change
Clearer documentation concerning execution environment pull policy
https://issues.redhat.com/browse/AAP-12534
Resolve conflicts
* Add note to set default.
Added note to state value of default.
Clearer documentation concerning execution environment pull policy
https://issues.redhat.com/browse/AAP-12534
* Changes to execution environment pull policy
Removed conflict
Clearer documentation concerning execution environment pull policy
https://issues.redhat.com/browse/AAP-12534
=> Changes to execution environment pull policy (#1193)

lightspeed/assemblies/assembly_configuring-vscode-extension.adoc, lightspeed/modules/proc_configure-vscode-extension.adoc, lightspeed/modules/proc_login-vscode-extension.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-20287. 
Changes made:
- Created a new file "Logging in to Ansible Lightspeed through the Ansible VS Code extension".
=> AAP-20287: Added info. about logging in to Ansible Lightspeed Service through VS Code extension

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/bundle-installer-24-61.adoc
Add bundle-installer-2.4-6.1 to release notes
2.4 Release Notes - AAP 2.4-6.1 Bundle Installer Release
https://issues.redhat.com/browse/AAP-21892
=> Add bundle-installer-2.4-6.1 to release notes

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
See [AAP-19094](https://issues.redhat.com/browse/AAP-19094) for more info.
=> AAP-19094: fixed formatting to make API link inactive

downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Just fixing some small erros noticed after [AAP-20779](https://issues.redhat.com/browse/AAP-20779) was published
Location : proc-add-operator-execution-nodes.adoc
=> backport 2.4

downstream/modules/platform/ref-eda-controller-variables.adoc
Added additional information and reordered the list
Add new variable description for EDA max running activations
https://issues.redhat.com/browse/AAP-20102
=> Amended eda inventory variable

downstream/modules/platform/ref-eda-controller-variables.adoc
Added additional information and reordered the list
Add new variable description for EDA max running activations
https://issues.redhat.com/browse/AAP-20102
=> Amended eda inventory variable (#1222)

downstream/modules/platform/con-pod-specification-mods.adoc
[AAP-22864](https://issues.redhat.com/browse/AAP-22864) updating hyperlink text to be more accurate
location: con-pod-specification-mods.adoc
=> AAP-22864 updating hyperlink text to be more accurate (#1231)

downstream/.vscode/settings.json, downstream/modules/platform/con-pod-specification-mods.adoc
[AAP-22864](https://issues.redhat.com/browse/AAP-22864) updating hyperlink text to be more accurate
location: con-pod-specification-mods.adoc
=> backporting 1232 to 2.3

.gitignore
Add items to `.gitignore` to prevent unnecessary artefacts clogging up the repo.
=> 2.3 Update .gitignore

attributes/attributes.adoc, stories/assembly-aws-upgrade.adoc, stories/assembly-gcp-intro.adoc, stories/assembly-gcp-release-notes-24.adoc, stories/assembly-gcp-upgrade.adoc, stories/tmp.docx, stories/topics/con-aws-upgrade-backup-process.adoc, stories/topics/con-aws-upgrade-restore-from-stack.adoc, stories/topics/con-azure-about.adoc, stories/topics/con-gcp-pull-deploy-container-image.adoc, stories/topics/con-gcp-pull-remove-container-image.adoc, stories/topics/con-gcp-upgrade-restore-from-stack.adoc, stories/topics/con-gcp-use-container-image.adoc, stories/topics/proc-gcp-backup-container-image.adoc, stories/topics/proc-gcp-deploy-with-new-vpc.adoc, stories/topics/proc-gcp-generate-restore-yml-file.adoc, stories/topics/proc-gcp-pull-backup-container-image.adoc, stories/topics/proc-gcp-restore-container-image.adoc, stories/topics/proc-gcp-upgrade-pull-container-image.adoc, stories/topics/tech-note-gcp-upgrade-logging-and-monitoring.adoc
AAP-21516 Update URLs in Clouds docs to use the BaseURL attribute
=> Update URLs to use BaseURL

downstream/modules/platform/ref-system-requirements.adoc
* Update ref-system-requirements.adoc
* Update ref-system-requirements.adoc
Removed the Tower reference, found the more generic Ansible installation doc where they mention what's required.
=> Update ref-system-requirements.adoc (#1017)

downstream/attributes/attributes.adoc
This backport includes the changes from PR #1225 in the 2.4 branch.
=> [Backport] Adding attributes for menu selections for 2.4 (#1225)

downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc, downstream/modules/platform/proc-define-mesh-node-types.adoc, downstream/modules/platform/proc-set-up-virtual-machines.adoc, downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
Amend Peers from Control nodes
Adding a Remote Execution Node to AAP
https://issues.redhat.com/browse/AAP-22358
=> Changes to operator mesh setup

downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc, downstream/modules/platform/proc-define-mesh-node-types.adoc, downstream/modules/platform/proc-set-up-virtual-machines.adoc, downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
* Changes to operator mesh setup
Amend Peers from Control nodes
Adding a Remote Execution Node to AAP
https://issues.redhat.com/browse/AAP-22358
* Changes to operator mesh setup
Moved removing instances section
Adding a Remote Execution Node to AAP
https://issues.redhat.com/browse/AAP-22358
* Changes to operator mesh setip
Added reference to RHEL subscriptions
Adding a Remote Execution Node to AAP
https://issues.redhat.com/browse/AAP-22358
* Changes to operator mesh setup
Correction
Adding a Remote Execution Node to AAP
https://issues.redhat.com/browse/AAP-22358
* Changes to operator mesh set up
Correction
Adding a Remote Execution Node to AAP
https://issues.redhat.com/browse/AAP-22358
* Changes to operator mesh setup
Changed reference to Simple Content Access
Adding a Remote Execution …
=> Changes to operator mesh setup (#1211)

downstream/assemblies/platform/assembly-system-requirements.adoc, downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
[CEE.NExt]Add PseudoCode for the Db user permission for the external DB.
https://issues.redhat.com/browse/AAP-19951
=> Add section on setting up database

downstream/assemblies/platform/assembly-aap-architecture.adoc, downstream/assemblies/platform/assembly-aap-platform-components.adoc, downstream/assemblies/platform/assembly-attaching-subscriptions.adoc, downstream/assemblies/platform/assembly-choosing-obtaining-installer.adoc, downstream/assemblies/platform/assembly-network-ports-protocols.adoc, downstream/assemblies/platform/assembly-system-requirements.adoc, downstream/modules/platform/con-SM-standalone-contr-non-inst-database.adoc, downstream/modules/platform/con-about-eda-controller.adoc, downstream/modules/platform/con-declaring-variables.adoc, downstream/modules/platform/con-editing-inventory-files.adoc, downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc, downstream/modules/platform/proc-benchmark-postgresql.adoc, downstream/modules/platform/proc-installing-without-internet.adoc, downstream/modules/platform/proc-securing-secrets-in-inventory.adoc, downstream/modules/platform/ref-automation-hub-requirements.adoc, downstream/modules/platform/ref-controller-system-requirements.adoc, downstream/modules/platform/ref-eda-system-requirements.adoc, downstream/modules/platform/ref-guidelines-hosts-groups.adoc, downstream/modules/platform/ref-postgresql-requirements.adoc, downstream/modules/platform/ref-system-requirements.adoc, downstream/titles/aap-planning-guide/master.adoc
Correct formatting, spelling, and grammar items noted when going through the pre-release checklist for the Platform Planning Guide
Platform Planning Guide - Resolve items noted during pre-release cleanup tasks
https://issues.redhat.com/browse/AAP-23047
=> Correct formatting, spelling, and grammar in Platform Planning Guide

bin/sync_cloud_docs.sh
AAP-23136 Add SaaS on AWS to script that Jenkins uses to sync clouds docs to the production repo.
=> AAP-23136 Add SaaS on AWS to sync script

downstream/modules/platform/proc-define-mesh-node-types.adoc
This PR fixes a broken link in the Controller Admin guide.
=> Fix broken link in Controller Admin guide

downstream/modules/platform/proc-define-mesh-node-types.adoc
This PR backports the changes from #1262 to the 2.4 branch.
=> [Backport] Fix broken link in Controller Admin guide (#1262)

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/aap-24.adoc, downstream/titles/release-notes/topics/eda-24.adoc
Update the following files:
- master.adoc
- aap-24.adoc
- eda-24.adoc
Stage 2 - Work on structural feedback from AAP writer notes document - Michelle
https://issues.redhat.com/browse/AAP-22348
=> Update release notes based on feedback from minimalism session

downstream/assemblies/dev-guide/assembly-migrate-ansible-versions.adoc, downstream/modules/builder/con-about-ee.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/dev-guide/proc-create-collections.adoc, downstream/modules/platform/con-why-ee.adoc, downstream/modules/platform/con-why-migrate-ansible-29.adoc, downstream/modules/platform/proc-controller-inv-source-vm-vcenter.adoc, downstream/modules/platform/proc-install-ansible-colls.adoc, downstream/modules/platform/proc-update-ee-image-locations.adoc, downstream/modules/platform/ref-system-requirements.adoc, downstream/modules/security/con-requirements.adoc, downstream/modules/security/proc-creating-firewall-rule.adoc
Removed Ansible 2.9 references
Update references to Ansible 2.9
https://issues.redhat.com/browse/AAP-18771
=> Removed references to out-of-date Ansible version

downstream/assemblies/dev-guide/assembly-migrate-ansible-versions.adoc, downstream/modules/builder/con-about-ee.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/dev-guide/proc-create-collections.adoc, downstream/modules/platform/con-why-ee.adoc, downstream/modules/platform/con-why-migrate-ansible-29.adoc, downstream/modules/platform/proc-controller-inv-source-vm-vcenter.adoc, downstream/modules/platform/proc-install-ansible-colls.adoc, downstream/modules/platform/proc-update-ee-image-locations.adoc, downstream/modules/platform/ref-system-requirements.adoc, downstream/modules/security/con-requirements.adoc, downstream/modules/security/proc-creating-firewall-rule.adoc
* Removed references to out-of-date Ansible version Removed Ansible 2.9 references
https://issues.redhat.com/browse/AAP-18771
=> Removed references to out-of-date Ansible version (#1249)

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/aap-24.adoc, downstream/titles/release-notes/topics/eda-24.adoc
Update the following files:
master.adoc
aap-24.adoc
eda-24.adoc
Stage 2 - Work on structural feedback from AAP writer notes document - Michelle
https://issues.redhat.com/browse/AAP-22348
=> Update release notes based on feedback from minimalism session (#1218)

downstream/titles/release-notes/topics/bundle-installer-24-11.adoc, downstream/titles/release-notes/topics/bundle-installer-24-12.adoc, downstream/titles/release-notes/topics/bundle-installer-24-13.adoc, downstream/titles/release-notes/topics/bundle-installer-24-14.adoc, downstream/titles/release-notes/topics/bundle-installer-24-21.adoc, downstream/titles/release-notes/topics/bundle-installer-24-22.adoc, downstream/titles/release-notes/topics/bundle-installer-24-24.adoc, downstream/titles/release-notes/topics/bundle-installer-24-6.adoc, downstream/titles/release-notes/topics/bundle-installer-24-61.adoc, downstream/titles/release-notes/topics/docs-24.adoc, downstream/titles/release-notes/topics/hub-464.adoc, downstream/titles/release-notes/topics/installer-24-2.adoc, downstream/titles/release-notes/topics/installer-24-3.adoc, downstream/titles/release-notes/topics/installer-24-4.adoc, downstream/titles/release-notes/topics/installer-24-5.adoc, downstream/titles/release-notes/topics/installer-24-6.adoc
This PR tracks doc updates for JIRA https://issues.redhat.com/browse/AAP-22347. 
Changes made to following files:
- docs-24.adoc
- hub-464.adoc
- installer-24-4.adoc
- installer-24-5.adoc
- installer-24-6.adoc
=> AAP-22347: Updated AAP release notes per feedback from minimalism session

downstream/assemblies/platform/assembly-network-ports-protocols.adoc
This change updated 2 tables to name the required URLs in a consistent manner
=> AAP-21797 Provide URL naming consistency

downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Created backport to 2.4 of PR#1129
Inconsistent URL naming in required network connctions
https://issues.redhat.com/browse/AAP-21797
=> Provide URL naming consistency

stories/assembly-saas-install.adoc, stories/assembly-saas-intro.adoc, stories/assembly-saas-planning.adoc, stories/assembly-saas-post-install-config.adoc
[AAP-23354 ](https://issues.redhat.com/browse/AAP-23354)
Creating four new assemblies in the aap-clouds-latest branch
- assembly-saas-intro.adoc
- assembly-saas-planning.adoc
- assembly-saas-install.adoc
- assembly-saas-post-install-config.adoc
Assemblies created in the stories folder
=> Adding Saas Assemblies as part of AAP-23354

downstream/attributes/attributes.adoc
Update the Satellite version attribute
https://issues.redhat.com/browse/AAP-23332
=> Changed attribute value

downstream/assemblies/platform/assembly-ag-controller-clustering.adoc, downstream/assemblies/platform/assembly-controller-execution-environments.adoc, downstream/modules/platform/proc-controller-awx-manage-utility.adoc, downstream/modules/platform/proc-controller-configure-secret-lookups.adoc, downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc, downstream/modules/platform/proc-controller-importing-subscriptions.adoc, downstream/modules/platform/ref-controller-api-considerations.adoc, downstream/modules/platform/ref-controller-dependencies.adoc, downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc, downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc, downstream/modules/platform/ref-controller-run-the-builder.adoc
Pre-release fixes for Controller docs
https://issues.redhat.com/browse/AAP-23339
Affects:
`titles/controller-user-guide`
`titles/controller-admin-guide`
`titles/controller-getting-started-guide`
=> Corrections to controller docs before 2.5 GA

downstream/attributes/attributes.adoc
Update the Satellite version attribute
https://issues.redhat.com/browse/AAP-23332
=> Changed attribute value (#1284)

downstream/assemblies/platform/assembly-ag-controller-clustering.adoc, downstream/assemblies/platform/assembly-controller-execution-environments.adoc, downstream/modules/platform/proc-controller-awx-manage-utility.adoc, downstream/modules/platform/proc-controller-configure-secret-lookups.adoc, downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc, downstream/modules/platform/proc-controller-importing-subscriptions.adoc, downstream/modules/platform/ref-controller-api-considerations.adoc, downstream/modules/platform/ref-controller-dependencies.adoc, downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc, downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc, downstream/modules/platform/ref-controller-run-the-builder.adoc
* Corrections to controller docs before 2.5 GA
Pre-release fixes for Controller docs
https://issues.redhat.com/browse/AAP-23339
Affects:
`titles/controller-user-guide`
`titles/controller-admin-guide`
`titles/controller-getting-started-guide`
* Further peer review edit
=> Corrections to controller docs before 2.5 GA (#1272)

stories/topics/proc-saas-set-up.adoc
[AAP-23355](https://issues.redhat.com/browse/AAP-23355)
Getting the first draft of the new Saas set up procedure into the repo.
Location aap-clouds-latest > Stories > Topics > proc-saas-set-up.adoc
=> Saas Set up proc (AAP23355)

downstream/assemblies/devtools/assembly-developer-workflow.adoc, downstream/assemblies/devtools/assembly-devtools-install.adoc, downstream/assemblies/devtools/assembly-devtools-setup.adoc, downstream/assemblies/devtools/assembly-scaffolding-playbook-directory.adoc, downstream/assemblies/devtools/assembly-writing-running-playbook.adoc, downstream/assemblies/devtools/devtools, downstream/titles/develop-automation-content/dev-guide, downstream/titles/develop-automation-content/devtools, downstream/titles/develop-automation-content/master.adoc
Adding assemblies for the Devtools doc
=> AAP-17190 Create assemblies for devtools doc

downstream/assemblies/devtools/assembly-developer-workflow.adoc, downstream/assemblies/devtools/assembly-devtools-install.adoc, downstream/attributes/attributes.adoc, downstream/modules/devtools/proc-devtools-install.adoc, downstream/modules/devtools/ref-devtools-components.adoc, downstream/modules/devtools/ref-devtools-workflow.adoc
AAP-17190 Add installation and workflow chapters to devtools doc.
=> AAP-17190 Modules for devtools workflow and installation chapters

downstream/assemblies/devtools/assembly-developer-workflow.adoc, downstream/assemblies/devtools/assembly-devtools-install.adoc, downstream/attributes/attributes.adoc, downstream/modules/devtools/proc-devtools-install.adoc, downstream/modules/devtools/ref-devtools-components.adoc, downstream/modules/devtools/ref-devtools-workflow.adoc
Backports #1298 to 2.4
Adds 2 chapters to the devtools doc.
=> 2.4 AAP-17190 Modules for devtools workflow chapter (#1298)

downstream/titles/release-notes/topics/aap-24.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-22352. 
Change made:
- Moved Tech. Preview section after New features and enhancements.
=> AAP-22352: Updated AAP release notes per e2e review

stories/assembly-saas-install.adoc
Linking the set up procedure to the install assembly. 
Location aap-clouds-latest > Stories > assembly-saas-install.adoc
=> including proc in the assembling

downstream/assemblies/devtools/assembly-devtools-setup.adoc, downstream/modules/devtools/proc-configure-extension-settings.adoc, downstream/modules/devtools/proc-create-python-venv.adoc, downstream/modules/devtools/proc-directory-setup.adoc, downstream/modules/devtools/proc-install-vscode-extension.adoc, downstream/modules/devtools/proc-installing-vscode.adoc, downstream/modules/devtools/proc-setup-vscode-workspace.adoc, downstream/modules/devtools/ref-devtools-workflow.adoc
=> AAP-17190 Add configuration chapter to Devtools doc

downstream/assemblies/devtools/assembly-devtools-setup.adoc, downstream/modules/devtools/proc-configure-extension-settings.adoc, downstream/modules/devtools/proc-create-python-venv.adoc, downstream/modules/devtools/proc-directory-setup.adoc, downstream/modules/devtools/proc-install-vscode-extension.adoc, downstream/modules/devtools/proc-installing-vscode.adoc, downstream/modules/devtools/proc-setup-vscode-workspace.adoc, downstream/modules/devtools/ref-devtools-workflow.adoc
=> 2.4 AAP-17190 Add config chapter to Devtools doc (#1303)

downstream/titles/release-notes/topics/aap-24.adoc
This PR backports PR https://github.com/ansible/aap-docs/pull/1300 from main to 2.4 branch.
=> AAP-22352: Updated AAP release notes per e2e review (#1300)

attributes/attributes.adoc, stories/assembly-saas-set-up.adoc
[AAP-23685](https://issues.redhat.com/browse/AAP-23685)
updating attributes for SaaS full and short.
Location > aap-clouds-latest > Attributes > attributes.adoc
Location 2 : aap-clouds-latest > stories > assembly-saas-set-up.adoc
=> Updating SaaS Attributes

downstream/assemblies/devtools/assembly-scaffolding-playbook-directory.adoc, downstream/assemblies/devtools/assembly-testing-playbooks.adoc, downstream/attributes/attributes.adoc, downstream/modules/devtools/proc-create-molecule-scenario.adoc, downstream/modules/devtools/proc-scaffolding-playbook-directory.adoc, downstream/titles/develop-automation-content/master.adoc
AAP-17190 Add scaffolding chapter to Devtools doc
=> AAP-17190 Add scaffolding chapter to Devtools doc

downstream/assemblies/devtools/assembly-scaffolding-playbook-directory.adoc, downstream/assemblies/devtools/assembly-testing-playbooks.adoc, downstream/attributes/attributes.adoc, downstream/modules/devtools/proc-create-molecule-scenario.adoc, downstream/modules/devtools/proc-devtools-install.adoc, downstream/modules/devtools/proc-scaffolding-playbook-directory.adoc, downstream/modules/devtools/ref-devtools-components.adoc, downstream/titles/develop-automation-content/master.adoc
Backports #1314 and #1315 to 2.4
=> AAP-17190 Add scaffolding chapter to Devtools doc (#1314)(#1315)

downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Doc Bug - Hyperlink text incorrect
https://issues.redhat.com/browse/AAP-23769
=> Correct internal link

downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Doc Bug - Hyperlink text incorrect
https://issues.redhat.com/browse/AAP-23769
=> Correct internal link (#1322)

downstream/modules/platform/proc-importing-collections-into-private-automation-hub.adoc
Doc Bug in Red Hat Ansible Automation Platform Installation Guide
https://issues.redhat.com/browse/AAP-23771
=> Add console link

downstream/modules/platform/proc-importing-collections-into-private-automation-hub.adoc
Doc Bug in Red Hat Ansible Automation Platform Installation Guide
https://issues.redhat.com/browse/AAP-23771
=> Add console link (#1324)

downstream/modules/platform/ref-controller-supported-oses.adoc
Remove supportability of Windows Server 2012/2012R2 from AAP
https://issues.redhat.com/browse/AAP-22131
=> Remove support for Windows Server

downstream/modules/platform/ref-controller-supported-oses.adoc
Remove supportability of Windows Server 2012/2012R2 from AAP
https://issues.redhat.com/browse/AAP-22131
=> Remove support for Windows Server (#1326)

lightspeed/assemblies/assembly_managing-admin-dashboard-telemetry.adoc, lightspeed/modules/proc_obtain-config-wca-and-model-id.adoc, lightspeed/modules/proc_view-admin-dashboard.adoc, lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-15feb2024.adoc, lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc, lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-7march2024.adoc
This PR captures doc updates for JIRA https://issues.redhat.com/browse/AAP-21865.
Updates made:
- Added content for 'admin dashboard phase 2 capabilities'
- Release notes cross-refs.
=> AAP-21865: Created docs for Admin dashboard phase 2 feature

lightspeed/modules/proc_obtain-config-wca-and-model-id.adoc
Fix cross reference in lightspeed user guide
=> Fix xref in lightspeed user guide

downstream/modules/platform/ref-controller-auth-code-grant-type.adoc
Location added for /etc/tower/conf.d/custom.py
https://issues.redhat.com/browse/AAP-23141
affects `controller-admin-guide`
=> Doc Bug in Automation Controller Administration Guide (#1337)

downstream/assemblies/analytics/assembly-using-job-explorer.adoc, downstream/modules/analytics/con-drill-down.adoc, downstream/modules/analytics/con-jobs-explorer.adoc, downstream/modules/analytics/proc-ignoring-nested-workflows-jobs.adoc, downstream/modules/analytics/proc-top-template-job-explorer.adoc, downstream/modules/analytics/proc-view-failed-jobs-detail.adoc
This PR addresses the changes needed to update the Job Explorer documentation for the 2.5 UI changes.
=> AAP-20542 - Updating Job Explorer doc for 2.5 UI changes

downstream/assemblies/platform/assembly-controller-inventories.adoc, downstream/assemblies/platform/assembly-controller-organizations.adoc, downstream/assemblies/platform/assembly-controller-teams.adoc, downstream/assemblies/platform/assembly-ug-controller-instance-groups.adoc, downstream/modules/platform/con-controller-access-organizations.adoc, downstream/modules/platform/con-controller-capacity-determination.adoc, downstream/modules/platform/con-controller-configure-hostname-notifications.adoc, downstream/modules/platform/proc-controller-adding-new-inventory.adoc, downstream/modules/platform/proc-controller-apps-create-tokens.adoc, downstream/modules/platform/proc-controller-create-application.adoc, downstream/modules/platform/proc-controller-create-instance-group.adoc, downstream/modules/platform/proc-controller-creating-a-team.adoc, downstream/modules/platform/proc-controller-pass-extra-variables-provisioning-callbacks.adoc, downstream/modules/platform/proc-controller-sourced-from-project.adoc, downstream/modules/platform/proc-controller-user-tokens.adoc, downstream/modules/platform/proc-controller-view-jobs-associated-with-instance-group.adoc, downstream/modules/platform/ref-controller-credential-openShift.adoc, downstream/modules/platform/ref-controller-credential-vault.adoc, downstream/modules/platform/ref-controller-export-old-scripts.adoc
Controller user guide link goes to docs.ansble.com instead of access.com
https://issues.redhat.com/browse/AAP-23922
=> Corrected links from docs.ansible.com

downstream/assemblies/platform/assembly-inventory-file-importing.adoc, downstream/modules/platform/ref-controller-inventory-import.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Remove Chapter 3 'Custom Inventory Scripts'
https://issues.redhat.com/browse/AAP-23537
=> Remove chapter on custom inventory scripts

downstream/modules/platform/con-install-scenario-recommendations.adoc, downstream/modules/platform/ref-guidelines-hosts-groups.adoc
[Cee.neXT] Missing information on the FQDN and the skeope working.
https://issues.redhat.com/browse/AAP-24164
=> Added information about format of FQDN

downstream/modules/platform/con-install-scenario-recommendations.adoc, downstream/modules/platform/ref-guidelines-hosts-groups.adoc
[Cee.neXT] Missing information on the FQDN and the skeope working.
https://issues.redhat.com/browse/AAP-24164
=> Added information about format of FQDN (#1355)

downstream/modules/platform/con-install-scenario-examples.adoc, downstream/modules/platform/ref-guidelines-hosts-groups.adoc
To 2.3
[Cee.neXT] Missing information on the FQDN and the skeope working.
https://issues.redhat.com/browse/AAP-24164
=> Add information about format of FQDN

downstream/assemblies/platform/assembly-controller-search.adoc, downstream/modules/platform/con-controller-overview-details.adoc, downstream/modules/platform/proc-controller-importing-subscriptions.adoc, downstream/modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc, downstream/modules/platform/ref-controller-licenses.adoc, downstream/modules/platform/ref-controller-node-counting.adoc, downstream/modules/platform/ref-controller-search-tips.adoc
https://issues.redhat.com/browse/AAP-23672
Affects `controller-user-guide`
=> Controller User Guide UI update chapters 1-11

downstream/modules/platform/ref-controller-variables.adoc
AAP-19392 Add new postgres_max_connections variable for controller v4.5
Affects `/titles/aap-installation-guide`
=> AAP-19392 Add new postgres_max_connections variable for controller v4.5

downstream/modules/platform/ref-controller-variables.adoc
=> 2.4 AAP-19392 Add postgres_max_connections variable (#965)

downstream/modules/platform/ref-controller-setup-considerations.adoc
[Docs] 20 node limit in docs is obselete
https://issues.redhat.com/browse/AAP-23909
=> Removed 20 node limit

downstream/assemblies/platform/assembly-controller-resource-operator.adoc, downstream/attributes/attributes.adoc, downstream/modules/platform/con-resource-operator-overview.adoc, downstream/modules/platform/proc-add-controller-access-token.adoc, downstream/modules/platform/proc-create-a-connection-secret.adoc, downstream/modules/platform/proc-create-a-jobtemplate.adoc, downstream/modules/platform/proc-create-an-ansiblejob.adoc, downstream/modules/platform/proc-use-controller-resource-operator.adoc, downstream/titles/aap-operator-installation/master.adoc
[AAP-14684](https://issues.redhat.com/browse/AAP-14684):
Converting upstream controller resource operator to downstream
[Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/index)
Doc location : downstream > titles > aap-operator-installation
=> creating assembly and modules for Resource Operator (AAP-24684)

downstream/assemblies/platform/assembly-controller-resource-operator.adoc, downstream/attributes/attributes.adoc, downstream/modules/platform/con-resource-operator-overview.adoc, downstream/modules/platform/proc-add-controller-access-token.adoc, downstream/modules/platform/proc-create-a-connection-secret.adoc, downstream/modules/platform/proc-create-a-jobtemplate.adoc, downstream/modules/platform/proc-create-an-ansiblejob.adoc, downstream/modules/platform/proc-use-controller-resource-operator.adoc, downstream/titles/aap-operator-installation/master.adoc
[AAP-14684](https://issues.redhat.com/browse/AAP-14684):
Converting upstream controller resource operator to downstream
[Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/index)
Doc location : downstream > titles > aap-operator-installation
=> creating assembly and modules for Resource Operator (AAP-24684) (#1367)

stories/assembly-saas-post-install-config.adoc
[AAP-23357](https://issues.redhat.com/browse/AAP-23357)
Editing the Configuration assembly 
Location: aap-clouds-latest > Stories > assembly-saas-post-install-config.adoc
=> AAP-23357 edits to assembly

downstream/assemblies/platform/assembly-controller-applications.adoc, downstream/modules/platform/proc-controller-apps-create-tokens.adoc, downstream/modules/platform/proc-controller-create-application.adoc
Typo in attribute in Automation User Guide
https://issues.redhat.com/browse/AAP-24758
=> Corrected broken link (#1386)

downstream/assemblies/platform/assembly-ug-controller-schedules.adoc, downstream/modules/platform/proc-controller-define-schedule-exceptions.adoc, downstream/modules/platform/proc-controller-define-schedule-rules.adoc
Additions to schedule section
Controller User Guide UI updates chapters 24-33
https://issues.redhat.com/browse/AAP-23674
=> Additions to Controller UG UI changes

downstream/modules/platform/con-controller-capacity-determination.adoc
Typo in attribute in Automation Controller User Guide
https://issues.redhat.com/browse/AAP-24759
=> Corrected link (#1389)

downstream/assemblies/platform/assembly-ag-controller-secret-handling.adoc, downstream/modules/platform/con-controller-secret-handling.adoc
* Add notes about use of local users
Documentation should clarify if local users are needed
https://issues.redhat.com/browse/AAP-19240
* Add notes about use of local users
Corrected and added details of other user accounts
Documentation should clarify if local users are needed
https://issues.redhat.com/browse/AAP-19240
* Add notes about use of local users
Updated text
Documentation should clarify if local users are needed
https://issues.redhat.com/browse/AAP-19240
* Added notes about local users.
Correction
Documentation should clarify if local users are needed
https://issues.redhat.com/browse/AAP-19240
=> Add notes about use of local users (#1335)

downstream/assemblies/platform/assembly-ag-controller-config.adoc, downstream/modules/platform/con-controller-custom-logos.adoc, downstream/modules/platform/proc-controller-configure-jobs.adoc, downstream/modules/platform/proc-controller-configure-system.adoc, downstream/modules/platform/proc-controller-configure-user-interface.adoc, downstream/titles/controller/controller-admin-guide/master.adoc
Restructure Configuring Automation Controller chapter based on new UI
https://issues.redhat.com/browse/AAP-25063
=> Restructure configuation chapter

downstream/modules/platform/ref-connect-hub-to-rhsso.adoc
Improve PAH SSO documentation
https://issues.redhat.com/browse/AAP-21847
=> Changed documentation link

downstream/modules/platform/ref-connect-hub-to-rhsso.adoc
Improve PAH SSO documentation
https://issues.redhat.com/browse/AAP-21847
=> Changed documentation link (#1406)

downstream/modules/platform/ref-operator-ocp-version.adoc, downstream/titles/aap-containerized-install/master.adoc, downstream/titles/aap-hardening/master.adoc, downstream/titles/aap-installation-guide/master.adoc, downstream/titles/aap-operations-guide/master.adoc, downstream/titles/aap-operator-backup/master.adoc, downstream/titles/aap-planning-guide/master.adoc, downstream/titles/analytics/automation-savings/master.adoc, downstream/titles/analytics/job-explorer/master.adoc, downstream/titles/builder/master.adoc, downstream/titles/central-auth/master.adoc, downstream/titles/dev-guide/master.adoc, downstream/titles/eda/eda-getting-started-guide/master.adoc, downstream/titles/navigator-guide/master.adoc, downstream/titles/ocp_performance_guide/master.adoc, downstream/titles/security-guide/master.adoc, downstream/titles/upgrade/master.adoc
This reverts commit 277fa90fb1e54c57786a84f0ea0fbea247797641.
=> Revert "Title updates aap 17967 (#1384)"

downstream/modules/platform/ref-operator-ocp-version.adoc, downstream/titles/aap-containerized-install/master.adoc, downstream/titles/aap-hardening/master.adoc, downstream/titles/aap-installation-guide/master.adoc, downstream/titles/aap-operations-guide/master.adoc, downstream/titles/aap-operator-backup/master.adoc, downstream/titles/aap-planning-guide/master.adoc, downstream/titles/analytics/automation-savings/master.adoc, downstream/titles/analytics/job-explorer/master.adoc, downstream/titles/builder/master.adoc, downstream/titles/central-auth/master.adoc, downstream/titles/dev-guide/master.adoc, downstream/titles/eda/eda-getting-started-guide/master.adoc, downstream/titles/navigator-guide/master.adoc, downstream/titles/ocp_performance_guide/master.adoc, downstream/titles/security-guide/master.adoc, downstream/titles/upgrade/master.adoc
I've reverted the rogue commits in the 2.4 branch and now this PR reverts the changes in the main branch introduced in ansible/aap-docs#1384.
=> Revert "Title updates aap 17967 -master.adoc files"

downstream/assemblies/hub/assembly-populate-container-registry.adoc
Consolidate all firewall openings to the planning guide
https://issues.redhat.com/browse/AAP-17590
* `titles/builder/`
* `titles/hub/managing-content/`
=> Add link to Planning Guide

downstream/assemblies/hub/assembly-populate-container-registry.adoc
* Add link to Planning Guide Consolidate all firewall openings to the planning guide https://issues.redhat.com/browse/AAP-17590
=> Add link to Planning Guide (#1412)

downstream/titles/controller/controller-admin-guide/master.adoc
Remove User Analytics chapter from Controller Admin Guide
https://issues.redhat.com/browse/AAP-25200
=> Added note to say usability analytics isn't supported

titles/saas-aws/stories.adoc
Just adding the assmeblies ot the master.adoc file. 
aap-clouds-latest > titles > saas-aws > master.adoc
=> including assemblies in master.adoc file

downstream/modules/platform/ref-projects-collections-support.adoc
Update docs to list order of precedence if project is using execution environment and requirements.yml file
https://issues.redhat.com/browse/AAP-20646
=> Add note about collection precedence when running a job

downstream/modules/platform/ref-projects-collections-support.adoc
Update docs to list order of precedence if project is using execution environment and requirements.yml file
https://issues.redhat.com/browse/AAP-20646
=> 2.4 Add note about collection precedence when running a job (#1423)

downstream/titles/aap-containerized-install/docinfo.xml, downstream/titles/aap-containerized-install/master.adoc
This PR is being created to update the Containerized install guide title to reflect style guidelines.
=> Update the containerized install title

downstream/titles/aap-containerized-install/docinfo.xml, downstream/titles/aap-containerized-install/master.adoc
This PR backports the changes from #1430 to the 2.4 branch.
=> [Backport] - Update the containerized install title (#1430)

downstream/templates/installer-rn-template.adoc, downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/installer-24-7.adoc, downstream/titles/release-notes/topics/installer-version-table.adoc, downstream/titles/release-notes/topics/rpm-version-table.adoc
2.4 Release Notes - AAP 2.4-7 Bundle installer release
https://issues.redhat.com/browse/AAP-24793
=> 2.4 Add 2.4-7 bundle installer release to release notes (#1433)

downstream/titles/release-notes/topics/rpm-24-7.adoc
2.4 Release Notes - AAP 2.4-7 Bundle installer release
https://issues.redhat.com/browse/AAP-24793
=> 2.4 Backport 1435 to 24

downstream/titles/aap-installation-guide/docinfo.xml, downstream/titles/aap-installation-guide/master.adoc
This PR updates the title for the AAP Installation Guide.
=> Updates title for style consistency

downstream/titles/aap-installation-guide/docinfo.xml, downstream/titles/aap-installation-guide/master.adoc
This PR backports the changes from #1437 to the 2.4 branch.
=> Updates title for style consistency (#1437) [backport]

attributes/attributes.adoc, stories/assembly-saas-post-install-config.adoc, stories/assembly-saas-set-up.adoc, stories/topics/con-saas-intro.adoc, stories/topics/proc-saas-set-up-private.adoc, stories/topics/proc-saas-set-up-public.adoc
[AAP-14780 ](https://issues.redhat.com/browse/AAP-14780)
AAP Service on AWS docs tech review edits applied 
aap-docs > aap-clouds-latest > stories > 
assembly-saas-planning.adoc
assembly-saas-set-up.adoc
assembly-saas-post-install-config.adoc
attributes.adoc
=> Tech review edits applied to SaaS docs

downstream/titles/controller/controller-api-overview/docinfo.xml, downstream/titles/controller/controller-api-overview/master.adoc, downstream/titles/operator-mesh/docinfo.xml, downstream/titles/operator-mesh/master.adoc, downstream/titles/release-notes/docinfo.xml, downstream/titles/release-notes/master.adoc
Updated titles for the AAP API guide, the mesh guide, and release notes for style & consistency
=> Changed titles for consistency for API, mesh guide, and release notes

downstream/titles/aap-installation-guide/master.adoc
This PR backports the fixes from #1448 to the 2.4 branch.
=> [Backport] Fix title issue in AAP install guide (#1448)

stories/topics/con-azure-about.adoc
AAP-25229 Update link from Azure doc to mesh doc
=> AAP-25229 Update URL for link from Azure doc to mesh doc

titles/saas-aws/docinfo.xml, titles/saas-aws/master.adoc, titles/saas-aws/title-attributes.adoc
Fixing title to "Red Hat Ansible Automation Platform Service on AWS"
=> Update SaaS title

downstream/titles/controller/controller-api-overview/docinfo.xml, downstream/titles/controller/controller-api-overview/master.adoc, downstream/titles/operator-mesh/docinfo.xml, downstream/titles/operator-mesh/master.adoc, downstream/titles/release-notes/docinfo.xml, downstream/titles/release-notes/master.adoc
Changes made to titles in PR https://github.com/ansible/aap-docs/pull/1445 backporting to 2.4.
=> Updated titles to reflect style guide standards for AAP books

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/async-updates.adoc
Add detail to asynchronous updates section of release notes to explain what they are and include CVE detail.
Add CVE detail to AAP release notes
https://issues.redhat.com/browse/AAP-22059
=> Add detail to asynchronous updates section of release notes

downstream/titles/release-notes/master.adoc, downstream/titles/release-notes/topics/async-updates.adoc
Add detail to asynchronous updates section of release notes to explain what they are and include CVE detail.
Add CVE detail to AAP release notes
https://issues.redhat.com/browse/AAP-22059
=> 2.4 Add detail to asynchronous updates section of release notes (#1457)

stories/assembly-azure-support.adoc, stories/topics/ref-azure-limited-support-status.adoc
AAP-25121 Azure: Add limited support info
=> AAP-25121 Azure: Add limited support info

downstream/modules/platform/proc-controller-inv-source-terraform.adoc
Update Terraform document links
https://issues.redhat.com/browse/AAP-25605
=> Editing terraform doc links

lightspeed/titles/lightspeed-release-notes/master.adoc, lightspeed/titles/lightspeed-release-notes/modules/lightspeed-intro.adoc, lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-june2024.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-25669
=> AAP-25669: Added release notes blurb for Lightspeed on-premise deployment and playbook generation features

lightspeed/modules/proc_create-oauth-app.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-25693.
Change made:
Updated PNG file callout in 'Creating OAuth app' topic.
=> AAP-25693: Updated the PNG reference in creating OAuth topic

lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-june2024.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-25696. Added cross-references in Release Notes to relevant topics in the Ansible Lightspeed User Guide.
=> AAP-25696: Added cross-references in release notes blurbs

downstream/titles/release-notes/topics/async-updates.adoc, downstream/titles/release-notes/topics/docs-24.adoc, downstream/titles/release-notes/topics/platform-intro.adoc, downstream/titles/release-notes/topics/rpm-24-2.adoc, downstream/titles/release-notes/topics/rpm-24-3.adoc, downstream/titles/release-notes/topics/rpm-24-6.adoc
* Update release notes based on editorial review feedback
Editorial Review of 2.4 Release Notes
https://issues.redhat.com/browse/AAP-22353
=> 2.4 Update release notes based on editorial review feedback (#1469)

downstream/assemblies/platform/assembly-configure-aap-operator.adoc, downstream/modules/platform/proc-operator-aap-faq.adoc, downstream/modules/platform/proc-operator-aap-troubleshooting.adoc, downstream/modules/platform/proc-operator-access-aap.adoc, downstream/modules/platform/proc-operator-deploy-central-config.adoc, downstream/modules/platform/proc-operator-link-components.adoc, downstream/titles/aap-operator-installation/master.adoc
2.5 prep 
Updating central configuration to marketing approved "platform gateway" 
Updating Troubleshooting section to an FAQ section
doc title: aap-operator-installation
=> Updating verbiage to platform gateway and updating FAQ section

stories/topics/ref-azure-limited-support-status.adoc
Update wording in Limited Support statement
=> AAP-25121 Azure: Update limited support status section

downstream/attributes/attributes.adoc
This PR introduces changes to menu attributes based on the latest navigation panel selections from the test build dated 6/21/2024.
=> Refreshed menu attributes based on the latest test build

downstream/assemblies/platform/assembly-aap-backup.adoc, downstream/assemblies/platform/assembly-aap-recovery.adoc, downstream/modules/platform/proc-aap-platform-gateway-backup.adoc, downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
Getting a start on the backend of AAP-22178 while the tech review is on going
Adding new procs to:
- assembly-aap-backup.adoc
- assembly-aap-recovery.adoc
=> Setting up new proc files for AAP-22178

lightspeed/assemblies/assembly_configuring-custom-models.adoc, lightspeed/modules/con_ansible-content-parser.adoc, lightspeed/modules/proc_configure-custom-models-lightspeed.adoc, lightspeed/modules/proc_generate-training-data-set.adoc, lightspeed/modules/proc_install-content-parser.adoc, lightspeed/modules/proc_resolve-ansible-lint-rule-violations.adoc, lightspeed/modules/proc_view-content-parser-output.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-25788. 
Changes made:
- Incorporated SME feedback
- Language edits found during self review
=> AAP-25788: Incorporate SME feedback and language edits for 'Configuring custom models' chapter

downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Inconsistencies in firewall documentation
https://issues.redhat.com/browse/AAP-21720
=> Create new ports and networks routing table

downstream/assemblies/platform/assembly-network-ports-protocols.adoc
* Create new ports and networks routing table
Inconsistencies in firewall documentation
https://issues.redhat.com/browse/AAP-21720
* Create new ports and networks routing table
Added two rows
Inconsistencies in firewall documentation
https://issues.redhat.com/browse/AAP-21720
* Create new ports and network routing table
Correction
Inconsistencies in firewall documentation
https://issues.redhat.com/browse/AAP-21720
=> Create new ports and networks routing table (#1460)

downstream/assemblies/platform/assembly-aap-backup.adoc, downstream/assemblies/platform/assembly-aap-recovery.adoc, downstream/modules/platform/proc-aap-platform-gateway-backup.adoc, downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
* adding proc content (AAP-22718)
* Adding PR Suggestions
=> Adding proc content (AAP-22718) (#1483)

downstream/titles/controller/controller-admin-guide/docinfo.xml, downstream/titles/controller/controller-admin-guide/master.adoc, downstream/titles/controller/controller-api-overview/docinfo.xml, downstream/titles/controller/controller-api-overview/master.adoc, downstream/titles/controller/controller-user-guide/docinfo.xml, downstream/titles/controller/controller-user-guide/master.adoc
Titles updated as per:
https://miro.com/app/board/uXjVNGGa88w=/
https://issues.redhat.com/browse/AAP-25866
=> Update controller doc titles for 2.5

downstream/titles/controller/controller-admin-guide/docinfo.xml, downstream/titles/controller/controller-admin-guide/master.adoc, downstream/titles/controller/controller-api-overview/docinfo.xml, downstream/titles/controller/controller-api-overview/master.adoc, downstream/titles/controller/controller-user-guide/docinfo.xml, downstream/titles/controller/controller-user-guide/master.adoc
Titles updated as per:
https://miro.com/app/board/uXjVNGGa88w=/
https://issues.redhat.com/browse/AAP-25866
=> Update controller doc titles for 2.5 (#1486)

stories/topics/con-azure-aks-cidr.adoc
AAP-25806 Azure - update CIDR range minimums for Service CIDR and Pod CIDR
Affects `/titles/aap-on-azure`
=> AAP-25806 Azure - update CIDR range minimums

downstream/assemblies/platform/assembly-aap-backup.adoc, downstream/modules/platform/proc-aap-platform-gateway-backup.adoc, downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
[AAP-22718](https://issues.redhat.com/browse/AAP-22718)
Applying SME feedback to the backup and restore sections. 
Doc title: aap-operator-backup
=> Adding in SME feedback on backup and restore drafts

downstream/assemblies/platform/assembly-aap-backup.adoc, downstream/modules/platform/proc-aap-platform-gateway-backup.adoc, downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
[AAP-22718](https://issues.redhat.com/browse/AAP-22718)
Applying SME feedback to the backup and restore sections.
Doc title: aap-operator-backup
=> Adding in SME feedback on backup and restore drafts (#1491)

downstream/assemblies/hub/assembly-populate-container-registry.adoc, downstream/modules/hub/proc-obtain-images.adoc
Backporting AAP-1623 represented in #1489
=> Backport #1489 to 2.4

stories/topics/proc-saas-set-up-private.adoc, stories/topics/proc-saas-set-up-public.adoc
[AAP-14780](https://issues.redhat.com/browse/AAP-14780)
Adding additional context around the AWS account ID that needs to be used for subscribing. 
Doc location aap-docs > aap-clouds-latest > titles > saas-aws
=> Adding note on AWS account ID

downstream/titles/aap-containerized-install/docinfo.xml, downstream/titles/analytics/automation-savings-planner/docinfo.xml, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/analytics/reports/docinfo.xml, downstream/titles/controller/controller-admin-guide/docinfo.xml, downstream/titles/controller/controller-getting-started/docinfo.xml, downstream/titles/controller/controller-user-guide/docinfo.xml, downstream/titles/dev-guide/docinfo.xml, downstream/titles/playbooks/playbooks-getting-started/docinfo.xml, downstream/titles/release-notes/docinfo.xml
Updated abstracts based on Donna's title, subtitle, and abstract spreadsheet where changes were indicated.
Jira ticket: https://issues.redhat.com/browse/AAP-22841
Source: https://github.com/ansible/aap-docs/pull/1498
=> Updated book title abstracts per AAP-22841

downstream/titles/aap-containerized-install/docinfo.xml, downstream/titles/analytics/automation-savings-planner/docinfo.xml, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/controller/controller-admin-guide/docinfo.xml, downstream/titles/controller/controller-getting-started/docinfo.xml, downstream/titles/controller/controller-user-guide/docinfo.xml, downstream/titles/dev-guide/docinfo.xml, downstream/titles/playbooks/playbooks-getting-started/docinfo.xml, downstream/titles/release-notes/docinfo.xml
Updated book abstracts per #1498 and backporting to 2.4
=> Backport to 2.4 for book abstrats PR-1498

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc, downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc, downstream/modules/platform/proc-using-postinstall.adoc, downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc, downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Update containerized installer product docs to incorporate Gateway
https://issues.redhat.com/browse/AAP-18760
=> Update containerized install guide to incorporate gateway

downstream/assemblies/platform/assembly-aap-containerized-installation.adoc, downstream/modules/platform/proc-downloading-containerized-aap.adoc, downstream/modules/platform/proc-installing-containerized-aap.adoc, downstream/modules/platform/proc-using-postinstall.adoc, downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc, downstream/modules/platform/ref-using-custom-tls-certificates.adoc
* Update containerized install guide to incorporate gateway https://issues.redhat.com/browse/AAP-18760
=> Update containerized install guide to incorporate gateway (#1506)

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc, downstream/modules/platform/ref-containerized-troubleshoot-config.adoc, downstream/modules/platform/ref-containerized-troubleshoot-install.adoc, downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc, downstream/titles/aap-containerized-install/master.adoc
Create Containerized AAP Troubleshooting content
https://issues.redhat.com/browse/AAP-15683
=> Create Containerized AAP Troubleshooting content

downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc, downstream/modules/platform/ref-containerized-troubleshoot-config.adoc, downstream/modules/platform/ref-containerized-troubleshoot-install.adoc, downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc, downstream/titles/aap-containerized-install/master.adoc
Create Containerized AAP Troubleshooting content
https://issues.redhat.com/browse/AAP-15683
=> Create Containerized AAP Troubleshooting content (#1499)

downstream/attributes/attributes.adoc
AAP-25848 Add an attribute for Microsoft Entra ID  to the downstream docs.
=> AAP-25848 Add Microsoft Entra ID attribute to downstream docs

downstream/attributes/attributes.adoc
AAP-25848 Add an attribute for Microsoft Entra ID to the downstream docs.
=> 2.4 AAP-25848 Add Microsoft Entra ID attribute to downstream docs (#1517)

downstream/modules/platform/proc-verify-controller-installation.adoc, downstream/modules/platform/proc-verify-eda-controller-installation.adoc, downstream/modules/platform/proc-verify-hub-installation.adoc
Backport to 2.4 for PR #1521 about adding a second step to login using Satellite credentials
=> Backport to 2.4 for #1451

downstream/modules/platform/ref-automation-hub-requirements.adoc
Added warning about memory use with the formula on how to figure out a good amount for the user's use case.
=> warned users about too much memory

downstream/aap-common/apache-2.0-license.adoc, downstream/aap-common/gplv3-license-text.adoc
Create open-source license modules
https://issues.redhat.com/browse/AAP-26401
=> Created Open Source licenses

downstream/modules/platform/ref-automation-hub-requirements.adoc
* warned users about too much memory
* automation hub update - may --> might
changed "may not" to "might not"
BP of PR#1523
=> warned users about too much memory (#1523)

downstream/aap-common/apache-2.0-license.adoc, downstream/aap-common/gplv3-license-text.adoc
Create open-source license modules
https://issues.redhat.com/browse/AAP-26401
=> Created Open Source licenses (#1529)

downstream/assemblies/platform/assembly-platform-install-scenario.adoc, downstream/modules/platform/con-eda-2-5-with-controller-2-4.adoc
Adding new file and content for installing EDA 2.5 with controller 2.4. Updated the assembly-platform-install-scenario.adoc to reflect the new file.
Resolves: AAP-23518
=> Adds new EDA 2.5 w/controller 2.4 adoc. Updates main assembly file.

downstream/snippets/snip-gateway-component-description.adoc
This PR addresses the request to create a reusable snippet that describes the gateway and points a user to the new overview content that will be part of the new Getting started guide. This is for https://issues.redhat.com/browse/AAP-26282. 
**Note:** The placeholder link will need to be included once the overview content is available in the repo. This can be done in a separate PR.
=> AAP-26282 - Create snippet that describes the platform gateway

downstream/modules/platform/ref-system-requirements.adoc
Correct table number
https://issues.redhat.com/browse/AAP-26749
=> Corrected table number

downstream/modules/platform/ref-system-requirements.adoc
Correct table number
https://issues.redhat.com/browse/AAP-26749
=> Corrected table number (#1547)

downstream/snippets/snip-gateway-component-description.adoc
This PR backports the changes for #1543 to the 2.5 branch and includes the following changes:
* AAP-26282 - Create snippet that describes the platform gateway
* AAP-26282 included a placeholder to link to the new overview content
=> AAP-26282 - Create snippet that describes the platform gateway (#1543)
